### ISSUE TITLE
Followup of bug #4639: Hangs Associated with Ammo Weapons on Fighter Squadrons

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/megamek#10]
I'm not sure how best to transfer an open SF ticket to this system, so I've just copied the history in.

Steps to reproduce:
Start a new game with a space map of any size. Set Advanced Aerospace Rules to all on except:  Aero Sanity (This issue happens whether it's on or not).
Allow return Flyovers
Reduce to-hit mods for StratOps AAA

Create two or three fighter squadrons for each of two players. It doesn't matter how many fighters are in them, or what models of fighters are chosen, but the squadrons should carry a mix of energy and ammo-using weapons. 

Start the game and deploy the opposing squadrons within firing range of each other. You should not have to move any of the squadrons to reproduce this issue. 

Try firing the ammo-based weapons only for a couple of turns. Sometimes just firing can cause the issue. Otherwise you may get it by inflicting weapon critical hits on an ammo-based weapon.

Either the same or a similar hang can be caused if a squadron takes enough weapon critical hits to reduce a weapon line to (0) functional weapons, and then that weapon line is fired in a subsequent turn. 

--------------------------------------------------------------------------------

I haven't looked at this in a while, but when I tried to look at it before, I wasn't able to make much headway. I wasn't able to reproduce the issue. I seem to recall that I just tried skipping through units, and that didn't seem to work. I'm not very keen on "dogfighting for a turn or two" as I'm not very well versed in space battles, and I feel like it's likely that I won't be doing the same things you would be doing, so I might not be able to reproduce the issue.

Basically, this ticket is sitting in limbo, as it's not going to make progress unless I can reproduce the bug, but I'm not sure what to do to reproduce it.

--------------------------------------------------------------------------------

[bugs:#4639] Ammo Weapon Issues with Fighter Squadrons

Status: open
Milestone: undetermined
Created: Tue Oct 20, 2015 08:39 PM UTC by Magnus Kerensky
Last Updated: Wed Oct 21, 2015 06:54 PM UTC
Owner: nobody

I think fighter squadrons may also suffer from this issue. They'll generally show the correct number of reloads until they start both expending rounds and/or taking weapon critical hits to ammo-dependent weapon groups. At this point all of the squadron's ammo counters, even those that have not been used or damaged, display (Current shots in slot/0). Weapons in this state are unusable, and if listed first in the display the server will hang. You can reorder the weapon display, placing energy weapons first, to get around this. Sometimes the ammo count will recover a turn or two later and allow the weapons to be used again. I am not sure if this happens on its own or only after further weapon critical hits are taken. 

This seems like it could be related to bug [#4517] regarding dropship/warship ammo values. I don't currently have any savegames displaying this issue, but I should be able to add one soon. This is using version 41.9 Dev as there are so many other apparent space combat bugs introduced in 41.10 that it is unplayable. This bug is not new to 41.9 and may already have an open ticket.

**Comment by HammerGS** [comment]
Just tried to duplicate this with the instructions provided.  Played 14 turns only firing ammo (Streak SRMs) until one squadron was destroyed and everything worked.

**Comment by arlith** [comment]
Can you not post comments on the SF tickets?  I was under the assumption that open  tickets could still be commented on, but new tickets can't be opened.  If you can still comment on the tickets, it would be preferred to keep the comments on SF.  If you can't comment on the old ticket, I'll look into permissions.

**Comment by mkerensky** [comment]
Huh.  I can still get it to happen nearly every space battle in 41.13 and 41.11.  Whenever a squadron is affected, it is all of the ammo-fed weapons that squadron has. Perhaps you can try a squadron with Autocannon or Gauss Rifles of various types. I've always run squadrons with a variety of ammo-fed weapons and I start fighting at ranges beyond Streak range, so those are never the only ammo-fed weapons fired. 

Also, I'm using the windows client. Is it possible that this is platform-based?

**Comment by mkerensky** [comment]
Ok, I can still comment on existing Sourceforge tickets. Would you rather move this topic back over or keep it here for further updates?

**Comment by arlith** [comment]
I think it would be best to keep using the ticket on SF.

**Comment by arlith** [comment]
Ok, I updated the SF ticket with Magnus' original post (I edited his test comment, to make it seem like the comment came from him).  In order to maintain the original authors, I would suggest repeating comments made here on the SF ticket.  I'm going to close this issue as well.

**Comment by arlith** [comment]
https://sourceforge.net/p/megamek/bugs/4639/
Link to SF, for posterity.
