### ISSUE TITLE
Illegal unit design (Kobold Battle Armor (CS) [SL/Flamer])

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#1000]
### Environment
MegaMek v0.43.11-RC5
Java version 1.8.0_144
Platform Windows 8.1 6.3 (amd64)

### Description
Troopers are overweight and is considered an illegal unit.

> 17:14:03,140 ERROR [megamek.server.Server] {Packet Pump} 
Chassis: Kobold Battle Armor (CS) [SL/Flamer] (BLOODWOLF) - IS_TW_Non_Box (3069)
Movement: 1/2/3
Trooper 1 Weight: 0.754 is greater than 0.75
Trooper 2 Weight: 0.754 is greater than 0.75
Trooper 3 Weight: 0.754 is greater than 0.75
Trooper 4 Weight: 0.754 is greater than 0.75
Trooper 5 Weight: 0.754 is greater than 0.75
Structure:                                                                       0.17500000000000002
Armor: 30 IS BA Stealth (Standard)                                 0.30
Equipment:
Auto-Rifle (Modern..Squad                                          0.004
Swarm Mek           Squad                                          0.00
Attack Swarmed Mek  Squad                                          0.00
Stop Swarm Attack   Squad                                          0.00
Leg Attack          Squad                                          0.00
Small Laser         Squad                                          0.20
Flamer [BA]         Squad                                          0.15

*Neoancient is already aware and plans to fix this tomorrow.  This is a reminder ticket.

### Files
NA

**Comment by neoancient** [comment]
If you run from the source after pulling the fix you will need to delete the units cache first.

**Comment by MGM175** [comment]
Well, congrats on reaching 1000th issue milestone. ;)
