### ISSUE TITLE
Screen Shot collection site.

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#1004]
Using this as a location for people to post screen shots for all three projects.

**Comment by NickAragua** [comment]
I like to call this one "adding insult to injury".

https://i.imgur.com/xqqWiEu.jpg

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/41801259-14a3c2b8-763f-11e8-8599-91f85c389e95.png)

![image](https://user-images.githubusercontent.com/16950832/41801270-1fe92c6c-763f-11e8-8612-c98f2576ec94.png)

https://github.com/MegaMek/megamek/issues/256

**Comment by Schugger** [comment]
A partuculary bloody battle on Pollux in 2956 with my mercenary unit Hernandez Hoplites against some Marik invaders.

[img]https://ibb.co/gY16LT[/img]

**Comment by Schugger** [comment]
A particulary bloody battle on Pollux in 2956 with my mercenary unit Hernandez Hoplites against some Marik invaders.

`[url]https://ibb.co/gY16LT[/url]`

**Comment by Schugger** [comment]
I had a particulary vicious battle on Pollux while under contract for the Lyran Commonwealth against some persistent invaders from the FWL. It was epic :)

![vicious battle](https://user-images.githubusercontent.com/30797128/41811307-4be89e6e-770d-11e8-9be7-2c117860cdd0.jpg)

**Comment by mchapman1970** [comment]
![4th skye guard](https://user-images.githubusercontent.com/22855199/41815925-d45f04a6-773d-11e8-93f0-ce7644cc369d.jpg)

**Comment by mchapman1970** [comment]
![untitled 2](https://user-images.githubusercontent.com/22855199/41815931-0129cd4a-773e-11e8-9a6a-eddf03f1498c.jpg)

**Comment by mchapman1970** [comment]
![untitled1](https://user-images.githubusercontent.com/22855199/41815933-0a201dd2-773e-11e8-82d1-31f0f793904c.jpg)

**Comment by mchapman1970** [comment]
![untitled](https://user-images.githubusercontent.com/22855199/41815934-11667212-773e-11e8-8474-3d6bc6eff5ab.jpg)

**Comment by mchapman1970** [comment]
![image](https://user-images.githubusercontent.com/22855199/41815941-3a1226d4-773e-11e8-9926-a13fc6d4d06f.png)

**Comment by Qwertronix** [comment]
A few "boring" screenshots of MegaMekLab, that should still show heavy unit customizers (like me!) just how much you can actually tweak all the units in here and what kind of tools you can expect to have when doing so. 
[MML_Showcase.zip](https://github.com/MegaMek/megamek/files/2130520/MML_Showcase.zip)

**Comment by mchapman1970** [comment]
![image](https://user-images.githubusercontent.com/22855199/41819413-d8ccef38-7785-11e8-9274-99f73e18567c.png)

**Comment by mchapman1970** [comment]
![image](https://user-images.githubusercontent.com/22855199/41819421-f83906a4-7785-11e8-8efd-816a8d7d2ba6.png)

**Comment by mchapman1970** [comment]
![image](https://user-images.githubusercontent.com/22855199/41819468-8b13a074-7786-11e8-8c51-a1abb6fe9546.png)

**Comment by mchapman1970** [comment]
![image](https://user-images.githubusercontent.com/22855199/41819492-d2801a1e-7786-11e8-82d9-5dbe65532ca9.png)

**Comment by mchapman1970** [comment]
![image](https://user-images.githubusercontent.com/22855199/41819511-0e617dac-7787-11e8-8679-3987783e5777.png)

**Comment by mchapman1970** [comment]
![image](https://user-images.githubusercontent.com/22855199/41819516-17afd5ca-7787-11e8-86a3-cb6aae0c4fd9.png)

**Comment by mchapman1970** [comment]
![image](https://user-images.githubusercontent.com/22855199/41819519-20dbec10-7787-11e8-9dfb-7ce5370e6d86.png)

**Comment by mchapman1970** [comment]
![image](https://user-images.githubusercontent.com/22855199/41819522-2ca87ce8-7787-11e8-996d-67cccc0b1419.png)

**Comment by mchapman1970** [comment]
![image](https://user-images.githubusercontent.com/22855199/41819594-86a413c8-7788-11e8-9b5e-7fb971d7aeba.png)

**Comment by mchapman1970** [comment]
![image](https://user-images.githubusercontent.com/22855199/41819757-9c5c9476-778b-11e8-9bb4-b01085ae3d07.png)

**Comment by mchapman1970** [comment]
![image](https://user-images.githubusercontent.com/22855199/41819760-a5c09242-778b-11e8-9773-78ed7d5a52af.png)

**Comment by mchapman1970** [comment]
![image](https://user-images.githubusercontent.com/22855199/41819762-adcbb318-778b-11e8-9f67-472f4308e251.png)

**Comment by mchapman1970** [comment]
![image](https://user-images.githubusercontent.com/22855199/41819766-b47b2ca2-778b-11e8-85a9-52dbbd613613.png)

**Comment by mchapman1970** [comment]
![image](https://user-images.githubusercontent.com/22855199/41819770-c1f1ee7a-778b-11e8-85c0-c9a983a68409.png)

**Comment by BLOODWOLF333** [comment]
![github0](https://user-images.githubusercontent.com/16950832/41824611-b3e2dd4c-77d8-11e8-8e59-2afd60d0ef8b.png)
FWL vs Kell Hounds

**Comment by SirMegaV** [comment]
![temp01](https://user-images.githubusercontent.com/17064665/41886065-4a414148-792d-11e8-8712-c04305d8ad58.png)

![image](https://user-images.githubusercontent.com/17064665/41886027-1f5b4faa-792d-11e8-975f-4fb5ffb2e911.png)

![image](https://user-images.githubusercontent.com/17064665/41886089-64563c0a-792d-11e8-9814-9d252721190e.png)

![image](https://user-images.githubusercontent.com/17064665/41886105-8498212c-792d-11e8-93fd-9ecae17938fe.png)

**Comment by Schugger** [comment]
Stunning harbour map. did you design the tiles for yourself?

**Comment by SirMegaV** [comment]
Those containers in the harbor is actually light woods. It's for sharing but file size is too big. Just drop me a message in slack.

**Comment by BLOODWOLF333** [comment]
![github](https://user-images.githubusercontent.com/16950832/42120946-d0e5d38a-7be9-11e8-88cb-8f8df940717f.png)

To show that we have helicopters/VTOLs

**Comment by BLOODWOLF333** [comment]
Kell Hounds vs Oberon Confederation around the mouth of a volcano

![image](https://user-images.githubusercontent.com/16950832/42139155-09189aac-7d4e-11e8-89ea-726e85642dfa.png)

**Comment by BLOODWOLF333** [comment]
Battlearmor
![image](https://user-images.githubusercontent.com/16950832/42357415-66c62ec4-809d-11e8-99ac-fa015a0d0b6d.png)

**Comment by SimonLandmine** [comment]
I would call this one "Fields of Fire" (the battle ended with a one-armed Locust chasing an armless Jenner from the map - everything else was destroyed, and mostly on fire)
![screenshot](https://user-images.githubusercontent.com/26851644/42402386-61e5da50-8172-11e8-969c-6d445ad95f1e.jpg)

**Comment by BLOODWOLF333** [comment]
Burrock vs Diamond Shark showing our infantry.
![github](https://user-images.githubusercontent.com/16950832/43240081-78ff51c0-905a-11e8-8da8-20c4d0367aa0.png)

**Comment by Windchild292** [comment]
Replaced by discord
