### ISSUE TITLE
When adding units through Add A Combat Unit dialog adds two instead of one when using enter key

### ISSUE THREAD

**Issue by MeadHall** [MegaMek/megamek#1008]
### Environment
Java 1.8.0_151 
0.43.12-RC6
Standalone MegaMek
Linux Mint

### Description
A bug where adding units using Enter key through the Add Unit dialog adds multiple units instead of one. To reproduce it, open Add Unit Dialog, select a unit in the list and press enter. It will add two units of selected type to your force.

**Comment by MeadHall** [comment]
I believe i have fixed the problem. After some digging i found that two listeners got triggered when user pressed Enter, and both called the Select() method which results in two units being added.

**Comment by wildj79** [comment]
You'll want to fork the project. This will make a copy of this repository on your Github account. Then you'll clone your fork to your local machine. Create a new branch on your fork. Make your changes, push them to your fork, then issue a pull request.

**Comment by MeadHall** [comment]
Thanks! i will give it a shot.
