### ISSUE TITLE
NPE while using Princess for AtB

### ISSUE THREAD

**Issue by Menzius** [MegaMek/megamek#101]
Hi,
this is the first time for me that Princess did not manage to move at all during my AtB time hence I looked into the mekhqlog.txt and saw the following error:

Exception in thread "Princess-precognition (Clan Jade Falcon)" java.lang.NullPointerException
	at megamek.client.bot.princess.PathEnumerator.adjustPathForBidge(PathEnumerator.java:308)
	at megamek.client.bot.princess.PathEnumerator.adjustPathsForBridges(PathEnumerator.java:300)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:264)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:424)
	at java.lang.Thread.run(Unknown Source)

This is repeated for all of the four bots in the current game.
At first I started the game the usual way, without changing anything concerning the bots, via the briefing room in MekHQ. The Bots deployed fine but did not move in the first round. I saved the game and restarted both programms and added bots with different personalities - no change. /skiping the first bot controlled unit brings no changes as well. I'm fairly sure that the bot is completely inactive since the CPU load is at 0%.

MekHQ 0.3.25, MegaMek 0.41.15
attached are the campaign savegame, megamek savegame and mekhqlog.txt

I'd guess that simply starting a new instance of the scenario would fix the problem by generating a new map but for the time being I won't continue in case further information is needed. Please let me know if you require further files. 
[24032016 NPEBugReportPrincess.gz](https://github.com/MegaMek/megamek/files/188316/24032016.NPEBugReportPrincess.gz)

**Comment by pheonixstorm** [comment]
> adjustPathForBidge

Typo in the code?

**Comment by arlith** [comment]
That never happens.

**Comment by arlith** [comment]
Ultimately, the issue comes down to the fact that Princess is calculating moves for an offboard unit.  This causes a problem in PathEnumerator.adjustPathForBridge as it loops through all of the `Coords` in a `MovePath`.  In this instance, there was a "StrJump" `MovePath`.  It may be possible that this issue only shows up with offboard jump-capable units, but I'm not sure.

I saw two solutions: figure out why Princess is computing moves for offboard units, or make `PathEnumerator.adjustPathForBridge` (I did rename it, fyi) able to handle offboard `Coords` (and hence null `Hex`s).

The chose the latter, as it was quick and easy.  I don't want to make it so moves for offboard units aren't calculated without digging into the Princess logic.

**Comment by Menzius** [comment]
One of my units is a Nova Cat with 4/6/4 and two Arrow IVs, deployed as offboard artillery, but I used the Nova one week (ingame) earlier without problems. Other units used changed a bit but it is still the same contract so I'm not sure what changed for Princess. 

Thank you for your work on this Issue.

**Comment by dericpage** [comment]
Huh.  Princess shouldn't be trying to move off-board units at all.  If you check the Precognition.insureUpToDate() method, you'll find the following code:
`                if (!entity.isDeployed() || entity.isOffBoard()) {
                    continue;
                }
`

So, she should be completely skipping off-board units.  I wonder if Entity.isOffBoard() is failing or of something else is going on.

**Comment by dericpage** [comment]
Looks like a similar check is needed in Precognition.run() (the other place where PathEnumerator.recalculateMovesFor(Entity) gets called).  Looking at the stack trace, that's the source of the bad behavior.

**Comment by arlith** [comment]
Yes, I had thought that Princess didn't calculate moves for offboard or undeployed units, but when I looked at the stack trace I couldn't find any.  I should dug into it deeper, but I didn't have time.  Adding that check to `Precognition.run()` is probably somewhat important.

**Comment by dericpage** [comment]
If it hasn't been handled by this weekend, I'll try to set aside some time to fix and test it.  It would give me the chance to familiarize myself with our pull request process anyway.
