### ISSUE TITLE
Aeros hitting ground units for Aero Damage instead of using cluster tables

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#1011]
SRM 4 at Javelin JVN-10N (The Pony Express); needs 5, rolls 7 : hits.

        Javelin JVN-10N (The Pony Express) takes 4 damage to LL.
            Armor destroyed.
             6 Internal Structure remaining.
            Critical hit on LL. Roll is 11; 2 locations.
            CRITICAL HIT on Jump Jet.
            CRITICAL HIT on Lower Leg.

    SRM 4 at Javelin JVN-10N (The Pony Express); needs 5, rolls 10 :  - Direct Blow - hits.

        Javelin JVN-10N (The Pony Express) takes 5 damage to CT.
            Armor destroyed.
             8 Internal Structure remaining.
            Critical hit on CT. Roll is (4+1) = 5; no effect.

[AerosNoCluster.sav.gz](https://github.com/MegaMek/megamek/files/2151315/AerosNoCluster.sav.gz)

Is this working as intended? Looks like a bug. Latest version.

**Comment by BLOODWOLF333** [comment]
Yes I reported this already because it didn't look right to me either (I could have swore Aero used to use the cluster table) but, it does say in TW that aero use the average damage of cluster weapons.

**Comment by BLOODWOLF333** [comment]
#998
