### ISSUE TITLE
Unit Display - Systems Tab - Standard Slot

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#1012]
### Environment
MegaMek v0.44.0
Java version 1.8.0_144
Platform Windows 8.1 6.3 (amd64)

### Description
In the slots column for the systems of the Panther there are two "Standard" entries.  Standard what?  I'm thinking that is supposed to be for the gyro (which also has taken one hit so, if that is gyro it's not giving any indication that it is damaged if thats what it is supposed to display).

![image](https://user-images.githubusercontent.com/16950832/42120333-37ba4f42-7bdf-11e8-9bd7-44bbb266504a.png)

### Files
[SystemsStandard.sav.gz](https://github.com/MegaMek/megamek/files/2151316/SystemsStandard.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/2151317/megameklog.txt)

**Comment by neoancient** [comment]
Standard armor, standard structure.
