### ISSUE TITLE
illegal unit design (Centurion CNT-1A)

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#1016]
### Environment
MegaMek v0.44.0
Java version 1.8.0_144
Platform Windows 8.1 6.3 (amd64)

### Description

> 23:04:21,882 ERROR [megamek.server.Server] {Packet Pump} 
> Chassis: Centurion CNT-1A (BLOODWOLF) - IS_Experimental (2430)
> Movement: 8/12
> Weight: 32.0 is greater than 30.0
> Engine: 220 Fusion                                                10.00
> Primitive Cockpit:                                                 5.00
> Fuel:                                                              5.00
> Heat Sinks: 10                                                     0.00
> Armor: 96 (Primitive Fighter)                                      9.00
> Equipment:
> Medium Laser        NOS                                            1.00
> Medium Laser        RWG                                            1.00
> Medium Laser        LWG                                            1.00

### Files
[megameklog.txt](https://github.com/MegaMek/megamek/files/2153734/megameklog.txt)

**Comment by neoancient** [comment]
I don't see an issue here. The Centurion CNT-1A is two tons overweight and MM flagged it as illegal. Which it is. Unless CGL puts out errata correcting the design, there's nothing for us to do.
