### ISSUE TITLE
Ostscout OTT-7J Image

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#1018]
### Environment
MegaMek 0.44.0
Java 8
Windows 8.1

### Description
Working on creating colored images for all the intro tech light mechs right now.  The Ostscout OTT-7J is using the just generic Ostscout.png image but, we have an image for the OTT-7J that the mechset is not using.  Thing is the image looks like an older sprite not made by DeadBorder(is very fuzzy and hard to tell what weapons are on the thing) so, am unsure what to do for the colored sprite on this design.

### Files
OTT-7J
![ostscout ott-7j](https://user-images.githubusercontent.com/16950832/42288733-a7399f62-7f81-11e8-972d-fe0fd9e5115b.png)

Ostscout.png what MegaMek is currently using.
![ostscout](https://user-images.githubusercontent.com/16950832/42288756-ca298af0-7f81-11e8-9f7e-0bf6b78a8a3a.png)

> exact "Ostroc OSR-5C" "mechs/Ostroc OSR-5C.png"
chassis "Ostscout" "mechs/Ostscout.png"
exact "Ostscout OTT-7K" "mechs/Ostscout OTT-7K.png"
exact "Ostscout OTT-9CS" "mechs/Ostscout OTT-9CS.png"
exact "Ostscout OTT-9S" "mechs/Ostscout OTT-9S.png"
exact "Ostscout OTT-10CS" "mechs/Ostscout OTT-10CS.png"
exact "Ostscout OTT-11J" "mechs/Ostscout OTT-11J.png"
chassis "Ostsol" "mechs/Ostsol OTL-4D.png"

**Comment by BLOODWOLF333** [comment]
The Valkyrie VLK-QA also looks like an older image and megamek is instead using the new valkyrie.png.  I think you probably did this on purpose hammer.

**Comment by Deadborder** [comment]
The OTT-7J and OTT-7Jb should be using this sprite
![ostscout](https://user-images.githubusercontent.com/17820161/43361288-534bbb7e-930e-11e8-88d9-663588678540.gif)
The OTT-7K should be using this
![ostscout_7k](https://user-images.githubusercontent.com/17820161/43361289-5bfb11de-930e-11e8-9657-55f2190d98be.gif)

The VLK-QA and VLK-QD should be using this sprite

![valkyrie_original](https://user-images.githubusercontent.com/17820161/43361294-a2cada90-930e-11e8-9965-9b363de652bb.gif)

The VLK-QF should be using this one

![valkyrie_qf_original](https://user-images.githubusercontent.com/17820161/43361296-acff5e50-930e-11e8-8add-e6615143b521.gif)

This is based on the Classic version; it's just that the differences are hard to tell on this scale

**Comment by BLOODWOLF333** [comment]
I have all these now and will be coloring them before sending to Hammer along with a mechset.txt

**Comment by Deadborder** [comment]
A couple more who are using old ones:

Griffin GRF-1DS should be using this sprite
![griffin_1ds_original](https://user-images.githubusercontent.com/17820161/43363338-1de9dd70-9346-11e8-8c52-8efc5f910730.gif)

Thunderbolt TDR-9SE should be using this sprite
![thunderbolt_9se_original](https://user-images.githubusercontent.com/17820161/43363362-79316572-9346-11e8-8e37-ec0a6eb715d4.gif)


Also, only the side parts of the Stinger's rear torso are the jump jet's; the middle is just plain body

**Comment by BLOODWOLF333** [comment]
K ill fix those stingers

**Comment by BLOODWOLF333** [comment]
That GRF-1DS I think is the same image as the GRF-3M and that TDR-9SE looks like either just the standard Thunderbolt.gif or the TDR-5SE?

**Comment by BLOODWOLF333** [comment]
![cougar_c](https://user-images.githubusercontent.com/16950832/43370191-1ce28eaa-9340-11e8-8e93-9d67e64ea0aa.png)

**Comment by Deadborder** [comment]
Hmm... will check. All I know is as of the last stable, the GRF-1DS was using the old, old unseen Griff icon, while the TDR-9SE should use the same as the TDR-5SE

![cougar_c_original](https://user-images.githubusercontent.com/17820161/43393983-6f2968d0-943c-11e8-9bf7-fde4d4106401.gif)
Updated Cougar C

**Comment by BLOODWOLF333** [comment]
I suspect your mechset_local is screwing you up with the GRF-1DS?  Cause MM 0.44.0 currently is using these images which you had emailed to Hammer almost a year ago which I then colored.
![github](https://user-images.githubusercontent.com/16950832/43426563-aab75efa-941b-11e8-9c49-d29203423336.png)

I will color the new Cougar C and change the 9SE to the 5SE image in the mechset and that should be everything for the new mech sprites.  Will email em to you to review one last night.

**Comment by Deadborder** [comment]
Both the TDR-9SE and the GRF-1DS there (or in the unused or wherever) are old icons; I have no idea why they're at all. As said, the TRD-9SE should use the same as the TDR-5SE. That's what I sent to Hammer last time.

![griffin_1ds_original](https://user-images.githubusercontent.com/17820161/43428546-26250e30-94a2-11e8-8e00-94f3b260a2e6.gif)

This is an updated and (hopefully) fixed Griffin GRF-1DS. Please use this one.

**Comment by BLOODWOLF333** [comment]
Alright that DS looks right without the laser in the LT.  This what we have from Jan 2017 for the Tbolts and that GRF-1DS which you fixed already so the griffin is good.  Why are there two versions of the same thunderbolt?  Like the Thunderbolt TDR-9SE and then there is a thunderbolt_9se?  This might have been while I was on a long break during the beginning of the year but, can check that the right ones are being used and get them colored now that I have everything I need.
[DBDownloads.zip](https://github.com/MegaMek/megamek/files/2243186/DBDownloads.zip)

**Comment by Deadborder** [comment]
I "refereshed" the Griffin and Thunderbolt when we got the Classics art for them with Second Succession War. It looks like the old sprites for the GRF-1DS and TRD-9SE weren't cleared out along the way.

**Comment by HammerGS** [comment]
Cleaning up some old data bugs, did this get resolved?

**Comment by Deadborder** [comment]
It did. New versions have been submitted

**Comment by HammerGS** [comment]
Per the comments resolved.
