### ISSUE TITLE
MegaMek Does Not Inform Player That A Anti-Mech Attack & A Weapon Attack Cannot Both Occur

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#1023]
### Environment
MegaMek 0.44.0
Java 8
Windows 8.1

### Description
BA and Infantry cannot both make an anti-mech attack and fire their weapons in the same weapon attack phase.  If the player fires their weapon first and then tries to perform a leg attack megamek correctly informs them that they cannot.

![image](https://user-images.githubusercontent.com/16950832/42358837-58a20a1e-80a4-11e8-92b6-a00379b9e130.png)

But if the player performs a leg attack first and then tries to fire their weapons megamek makes it seem like everythings ok.  Though in the attack resolution phase megamek will just skip the leg attack and only register the weapon fire.

![image](https://user-images.githubusercontent.com/16950832/42358877-839cc074-80a4-11e8-81ec-3480c0df6662.png)

### Files
[BAUnitDisplay.sav.gz](https://github.com/MegaMek/megamek/files/2168933/BAUnitDisplay.sav.gz)

**Comment by arlith** [comment]
The issue here is related to `WeaponAttackAction.toHitImpossible`.  Some weapons have a `F_SOLO_ATTACK` flag and there is a check to see if the weapon being fired has it, and if another weapon has been fired then the attack is marked as impossible.  However, what it does *not* check is if another solo attack weapon has already been fired.

**Comment by arlith** [comment]
I added a check that loops through all of the actions for the attacking entity to see if any of them are `WeaponAttackActions` that have the `F_SOLO`  flag and if so mark the new attack as invalid.  I feel like this approach is a bit inefficient as it requires looping through all current actions in the game.  It would likely be possible to cache this state.
