### ISSUE TITLE
Feature Request: Protomech equipment

### ISSUE THREAD

**Issue by Xeno426** [MegaMek/megamek#1026]
Since I've not seen these features requested, and don't know if there's any formal plans, I'd like to properly make a request for some Protomech equipment still missing from MegaMek.

Fusillade (WoR, page 199). There's currently no way to launch ATM rounds in Protomechs, and the only systems can can use the IIW and IMP rounds are iATM, which provide a streak capability that the Fusillade does not have (making them poor replacements). Further, attempting to put an iATM into a protomech and providing only one reload still allows a user to place a full tonne of ammo in the unit editing screen. Since the lack of Fusillades is preventing the addition of a few canon Protomechs (Sprite 3, Hobgoblin 2), there's all the more reason to add it.

Protomech Magnetic Clamp System (WoR, page 200). Even more prolific than the Fusillade, the MagClamps are used by several Protomechs (Centaur Z, Minotaur Z, Hobgoblin, Procyon Z, and the later NTNU Roc 5 and Gorgon 5). It would really be nice if these units could have their full capability provided.

Protomech Quad Melee Weapon System (WoR, page 200). So far only featured in the quad Basilisk, this is still a missing feature for some fun fan-made Protomechs (and if we can get Feralize added, even better). You guys already have the icon image for the quad Basilisk, the lack of a QMWS is the only thing holding back the use of the unit.

**Comment by HammerGS** [comment]
Glider Protos where coded in the last Dev cycle along with LAMs.

**Comment by Xeno426** [comment]
Huh, then what's up with the Svartalfa?

**Comment by neoancient** [comment]
It works as a glider protomech, using the same controls as LAMs in airmech mode. Click the "go up" button to get them off the ground and they move more or less like WiGEs but with the option to hover or increase elevation.

**Comment by Xeno426** [comment]
Ah, I see. 
In that case I'll remove that part of my feature request.

**Comment by neoancient** [comment]
I'm nearly finished with jumpship/warship/space station construction in MML and I've been planning to do protomechs next, and implement the remaining equipment in the process. I expect it to have it in the development branch some time around early-mid fall.

**Comment by HammerGS** [comment]
Implemented
