### ISSUE TITLE
Feature Request: select Infantry SRM ammo

### ISSUE THREAD

**Issue by ndrwstn** [MegaMek/megamek#1030]
### Environment
Megamek 0.44.0
MacOS 10.13.5
Java 8 Update 171?

### Description
I think this is a bug: Infantry SRM ammo isn't selectable in the lobby of MegaMek, even when other units (including BattleArmor) have that as a selection choice.

**Comment by wildj79** [comment]
This is working RAW (rules as written). Infantry ammunition in Total Warfare is more abstract than other units in the system.

**Comment by neoancient** [comment]
BattleArmor missile launchers are smaller versions of the full-sized launchers used on mechs, etc., and launch the same ammo. Infantry weapons are a different scale and work on very different principles. The alternate munition types available to full-sized weapons are not applicable to infantry.
