### ISSUE TITLE
Confirm Deployment onto Building that will Collapse

### ISSUE THREAD

**Issue by ndrwstn** [MegaMek/megamek#1031]
### Environment
Megamek 0.44.0
MacOS 10.13.5
Java 8 Update 171?

### Description
When deploying a 'mech onto a building that will collapse, it would be great to have a notification that it might happen.

**Comment by giorgiga** [comment]
(just an idea...)

in addition to (or maybe "instead of") showing a confirmation dialog, the map could highlight the dangerous hexes. It would be nice if the same happened during movement too.

**Comment by HoneySkull** [comment]
![image](https://github.com/MegaMek/megamek/assets/83041327/0f03c220-33d6-455f-8475-c1e1bec5db88)
