### ISSUE TITLE
Request: Toggle to Prevent 'Mechs from falling into hull-down

### ISSUE THREAD

**Issue by ndrwstn** [MegaMek/megamek#1032]
### Environment
Megamek 0.44.0
MacOS 10.13.5
Java 8 Update 171?

### Description
If you have hull down enabled, 'mechs go hull-down instead of falling. This is RAW, but dumb. It would be nice if we could unofficially disable the ability to "fall" into hull-down and avoid damage.

Example (emphasis added):
> Enforcer ENF-5D (Daniel) (Princess) must make 1 piloting skill roll(s) (20+ damage).
> The base target is 5 [4 (Base piloting skill) + 1 (fatigue)].
>     Roll #1, (4 (Base piloting skill) + 1 (fatigue) + 1 (20+ damage) + 0 (weight class modifier)); needs 6, rolls 5 : falls.
> **Enforcer ENF-5D (Daniel) (Princess) goes back to the hull down position instead of falling to the ground.**

**Comment by NickAragua** [comment]
Have you tried disabling the TacOps Falling (Expanded) setting?

**Comment by pheonixstorm** [comment]
Expanded falling is actually more complex than what is coded and does not seem to require the hull down option for use. (p22 and p24)

Also, going hull down to avoid a fall is NOT part of the Hull Down option. This is either going to be a bug or invalid depending on if you have expanded falling turned on or not

**Comment by ndrwstn** [comment]
I do have expanded falling setting on; that's probably the cause. I'm closing this. Thank you.
