### ISSUE TITLE
Enhancement: Allow 'Mech Equipment Changes during end of turn

### ISSUE THREAD

**Issue by ndrwstn** [MegaMek/megamek#1037]
The final end of turn display shows physical attacks, heat, control rolls, and the end phase. It would be nice if you could make final tweaks to your equipment settings prior to confirming the turn over.

**Comment by wildj79** [comment]
The current UI does already allow for these types of actions, you just have to do them in the movement and firing phases, instead of in the end phase. Most of these actions can be accomplished in the Unit dialog. You can do stuff like turn off and on heat sinks, change weapon mode, etc...

**Comment by HammerGS** [comment]
MegaMek isn’t coded with an end phase.  Going from memory here.... Arlith has looked into this years ago and would require a lot of coding.

**Comment by neoancient** [comment]
We try to be as close to the tabletop game as possible, but there are cases where some adjustments have to be made. The functionality is there, all the required information is there, and you just have to learn to think ahead. It is possible that we will make some changes in the architecture that will lead us to revisit this in the future, but for now it will stay as it is.
