### ISSUE TITLE
BA Leg Attack Damage Report Missing New Line Code

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#1038]
### Environment
MegaMek .44.0
Windows 8.1
Java 8

### Description
![image](https://user-images.githubusercontent.com/16950832/42549185-910f2658-8490-11e8-9cb1-fe1ac271d5ee.png)

Tried resizing the window and the damaged RL report stays put so it's missing the new line code I believe.

### Files
[megameklog.txt](https://github.com/MegaMek/megamek/files/2182831/megameklog.txt)
[NewLine.sav.gz](https://github.com/MegaMek/megamek/files/2182834/NewLine.sav.gz)

**Comment by wildj79** [comment]
Probably not. Reporting can get a little wonky in double blind play sometimes when units fall unconscious, especially if falling unconscious causes a previously spotted enemy unit to be no longer spotted.

**Comment by arlith** [comment]
For some reason, leg attacks don't seem to have the code to add the "hit" report.  It doesn't look like it's ever had this (or at least the log messages related to `LegAttackHandler` don't mention anything going back to 2009).  I added some code to add the report and it looks like it works.
