### ISSUE TITLE
Skill Randomizing in MM Lobby

### ISSUE THREAD

**Issue by BairdEC** [MegaMek/megamek#1043]
### Environment
MegaMek version 0.44.0 (w/MekHQ)
Win10
Java Version 1.8.0_171

### Description
In both stand-alone MM and MM with MekHQ, randomizing a pilot's skills in the MM lobby always sets the pilot skills to 4/5.  This affects player and bot pilots, singly or _en masse_.  Randomizing the pilot names appears to work as intended (not attempted below).

### Files
[Metal Magic29970619.zip](https://github.com/MegaMek/megamek/files/2186949/Metal.Magic29970619.zip) 

![mm lobby1](https://user-images.githubusercontent.com/38081112/42611133-75675f56-8549-11e8-8452-12359cc0b75d.png)

![mm lobby2](https://user-images.githubusercontent.com/38081112/42611135-776ebb78-8549-11e8-8f57-1cb2ebab2c64.png)

**Comment by BLOODWOLF333** [comment]
You have to change the methods the default is constant regular 4/5

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/42611684-f657c9da-855c-11e8-9e3e-6e8c351c870a.png)

Click the random skills button right there under create random army and change to total warfare or Taharqa method and then it will randomize.

**Comment by BairdEC** [comment]
Derp....  I had somehow forgotten where that was.  Thanks for the reminder.
