### ISSUE TITLE
Infantry Flamer, have no range

### ISSUE THREAD

**Issue by inqistor** [MegaMek/megamek#1044]
MekHQ 0.44.0
Megamek reports the same version
Windows 10

Although I don't know, where this BUG could start. It might have occured, after transfer to MekHQ.

I had generated enemy Infantry Platoon (Foot), from xotl RAT infantry, and it made a Flamer one. I had not traced, how they fought, but they died quickly, failing to get in range for more, than two rounds. I got unit as spoils after battle (it was Scenario in MekHQ), and refilled it with my own soldiers. In new mission, it seems, that Flamer have no range, I can't fire even mech in nearby hex. Moreover, Platoon description says, that they should be also armed with Rifles, but there are only Flamers.

**Comment by mkerensky** [comment]
This isn't a bug. Flamer infantry as presented in Total Warfare have a range of 1, which then violates the construction rules provided for them in Tech Manual (the Flamer has a range of 0). In order to gain the benefits of the flamer weapon, the platoon would have to have 2 of them per squad, which also makes the platoon use the flamer's range stats.

Infantry can fire at range 0, so there's nothing wrong with the platoon you rolled up.

**Comment by inqistor** [comment]
I recall, that in BT Compendium, Flamer Infantry had range of 2, same as Rifles. With range 0, they are quite useless, if they have to chase target into open terrain. Can I improve them in my MekHQ campaign, or should I just sell it?

And, since we are speaking about Infantry, and I don't want to seek again specific rule. What does it mean, that infantry have ONE SHOT SRM Launcher? Is it finite, can I choose, when to use it?

**Comment by NickAragua** [comment]
For current stats on infantry flamers, please see Page 351 of the TechManual (Conventional Infantry Weapons, Support Weapons).

The SRM Launchers also have an entry in that table. Page 148 has the infantry construction rules. 

Experimentally, infantry weapons do not have limited ammo.

For future reference, if you have questions about the rules, feel free to drop into the slack channel.

**Comment by inqistor** [comment]
I checked several sources, and it gets little complicated:
@mkerensky is basically right, as current implementation. Table at TW page 213, shows Flamers at 0 MP, which suggests, that they are using 2 Support Weapons per squad, according to TM page 151. However table on TM page 148 shows, that only Special Feature type B requires 2 weapons per squad for benefit.
Both Infantry Tables (TW page 215, and Infantry Record Sheet) shows range of Flamers as 3, which suggest, that they are using 1 Support Weapon per squad. I am not quite sure at what range heat damages are inflicted, but rules suggest, that at all of them, not only 0 (but Flamers should also add additional to-hit bonus, at 0 range, because of 1E).

And to answer my other questions:
1. Yes, it is possible to change number of Support Weapons in MegaMekLab, only few extra rifles are needed, and they can be obtained from disbanded platoon, or bought. Haven't checked them in combat yet, but sheet shows increase in movement points.
2. I'm pretty sure, "ONE SHOT SRM Launcher" should use Disposable Weapons rule, from TacOps page 304, but I'm guessing this is not implemented yet.
