### ISSUE TITLE
Narc Ammo Type Missing From Reports

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#1046]
### Environment
0.44.0 Megamek
Java 1.8.0_171
Windows 8.1

### Description
I believe normal Narc displays this same behavior but, iNarc attacks in the round reports will display as `iNarc ( ammo)` for attacks made with all the various ammo types a unit may be loaded with.  The space before ammo looks like it is failing to get() the ammo type that was just fired maybe?

![github](https://user-images.githubusercontent.com/16950832/42669320-53d434b4-861a-11e8-8fdd-822b8650b4e0.png)

![github2](https://user-images.githubusercontent.com/16950832/42669323-57a2632c-861a-11e8-8472-d8b99ab2b23c.png)

### Files
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/2190987/autosave.sav.gz)
BLOODWOLF(observer)
Comstar
Free Rasalhague Republic
[megameklog.txt](https://github.com/MegaMek/megamek/files/2190990/megameklog.txt)

**Comment by arlith** [comment]
For any ammo that has a `munitionType != AmmoType.M_STANDARD` the `submunitionStart` and `submunitionEnd` state variables need to be set.  These are what pull the submunition name out of the name for the report. iNarc and Narc special ammo didn't have these values set.
