### ISSUE TITLE
Field Gunners unable to target Air Units 

### ISSUE THREAD

**Issue by servo01** [MegaMek/megamek#1048]
MegaMek 44.0 

Field Gunners are unable to target air units
 
Attempting to attack either in-range air units or air units that intercept the Field Gunners along flight path, actively target and/or attack the Field Gunners gives "Infantry not allowed to engage air units" message. 

Attached savegame (players: Fighters, FieldGunners)
 
[AA.sav.gz](https://github.com/MegaMek/megamek/files/2195207/AA.sav.gz)

[megameklog.txt](https://github.com/MegaMek/megamek/files/2195200/megameklog.txt)

**Comment by arlith** [comment]
I did in fact "fix" this in the past: d08063
It looks like I read the errata to mean that only LB-X field guns and field artillery could hit airborne units.  I checked the errata and it does look like all field guns should be able to hit airborne units.
