### ISSUE TITLE
AMS Nag Displaying For A Shutdown Mech

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#1051]
### Environment
MegaMek 0.44.0
Java 8
Windows 8.1

### Description
Warhammer is shutdown and received two flights of missiles, the nag popped up asking which salvo I wanted the AMS to target (mech is shutdown), I chose the Stalker's SRM6, firing resolution screen the AMS did not engage which is correct but, the nag asking the user about it should not have appeared.

### Files
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/2195429/autosave.sav.gz)
BLOODWOLF
Taurian Concordat
[megameklog.txt](https://github.com/MegaMek/megamek/files/2195430/megameklog.txt)

**Comment by mkerensky** [comment]
Assign this one to me. I know where all the relevant AMS code is.

**Comment by mkerensky** [comment]
Fixed. Should be available in the next development release.
