### ISSUE TITLE
Pilot names in MM now show as un-named

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#106]
Started a using using the latest build (https://github.com/MegaMek/megamek/commit/c18cb0be78c1414f929198a3b73ef7afc26f9595).  Started a game added 4 mechs from the RATs and none of the mechs had a pilot name assigned.

**Comment by Akjosch** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/1920824a6172d11b41c774c760dd047d53c86f4d - I can't do anything about names like "WyszyÕski" in there just as quickly though (I guess that should have been "Wyszyński"?).
