### ISSUE TITLE
Princess Does Not Attack BA With Aero

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#1060]
### Environment
Megamek 0.44.0 standalone
Java 1.8
Windows 8.1

### Description
I have two princess bots fighting one has an ASF and the other has BA in their force.  Noticed a game prior to this when it got down to the aero vs just the BA she would not attack them as if they are an invalid target.  Suspect she handles conv infantry the same way when she is using aero but, havent tested that yet.

![image](https://user-images.githubusercontent.com/16950832/43049296-cfefa3d8-8dba-11e8-8c87-8cab373c5dfc.png)

### Files
[AvsBA.sav.gz](https://github.com/MegaMek/megamek/files/2217312/AvsBA.sav.gz)
BLOODWOLF (Im just an observer)
Lyran Commonwealth (Princess aero force)
I.S. - General (Princess BA force)

**Comment by NickAragua** [comment]
Unfortunately, the provided save isn't very helpful, as that aero is going to fly off the map no matter what. I think I've found and fixed *an* issue where the bot would discard normally viable paths that fly over enemy units, but that only happened on maps with buildings.
