### ISSUE TITLE
Princess able to manuever out of control atmospheric fighter

### ISSUE THREAD

**Issue by ndrwstn** [MegaMek/megamek#1073]
### Environment
Megamek 0.44.0
MacOS 10.13.5
Java 8 Update 171

### Description
Princess is able to manuever/evade (at least) atmospheric fighters despite being "out of control". Attached game has Heavy Strike Fighter Meteor out of control for the last two turns, but she has been turning and evading.

### Files
[princessnotoutofcontrol.sav.gz](https://github.com/MegaMek/megamek/files/2250957/princessnotoutofcontrol.sav.gz)

**Comment by NickAragua** [comment]
In the future, when providing saved games, please specify the names of the players to save time.
