### ISSUE TITLE
[0.44.0 : Bug] Not All "Troops" Carrying Tanks Can Be Generated

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#1077]
As titled, common APC units such as APC, heavy APC, Heavy Transport B1 cannot be generated by any factions using RAT Generator even when APC option is selected.

**Comment by Windchild292** [comment]
This appears to be a duplicate of #612

**Comment by neoancient** [comment]
#612 says it's generating tanks that can't carry troops. This says it's not generating some that can.
