### ISSUE TITLE
Narc Explosive Ammo Type Missing The Letter "E" In Reports

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#1081]
### Environment
Megamek 0.45.0
Java 1.8
Windows 8.1

### Description
Related to #1046 the Narc ammo is missing the letter E in the reports.
![github](https://user-images.githubusercontent.com/16950832/43690859-2358242e-98d7-11e8-8876-117e12bb7cf4.png)

### Files
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/2260764/autosave.sav.gz)
Player name: BLOODWOLF
[megameklog.txt](https://github.com/MegaMek/megamek/files/2260765/megameklog.txt)

**Comment by sixlettervariables** [comment]
This results from `AmmoType::getSubmunitionName` when subMunitionBegin/subMunitionLength aren't correct. The Narc ammo types do not set the correct values for those, as mentioned in #1046: https://github.com/MegaMek/megamek/blob/71fb163ae5c8a6cc6c379538cef560933f61dd24/megamek/src/megamek/common/AmmoType.java#L3693-L3713

Compare that to: https://github.com/MegaMek/megamek/blob/71fb163ae5c8a6cc6c379538cef560933f61dd24/megamek/src/megamek/common/AmmoType.java#L2750-L2778
