### ISSUE TITLE
Security Vulnerability Found

### ISSUE THREAD

**Issue by ProDigySML** [MegaMek/megamek#1087]
Hi,
I found a security vulnerability and would like to responsibly disclose this. Who would be the best person to talk to? Any email address I can contact?

*Official contributors of the project only*

**Comment by sixlettervariables** [comment]
You can contact megamekteam@gmail.com.

I would suggest you join our slack if you'd like to chat with the development team: http://megamek.org:3000/

**Comment by ProDigySML** [comment]
Contacted thanks!

**Comment by HammerGS** [comment]
Thank you, we received the email and will review internally.
