### ISSUE TITLE
Princess over deploys units

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#1091]
Princess just triple deployed tanks in my game in the same hex.

![image](https://user-images.githubusercontent.com/19868605/43914649-6ff49cde-9bd6-11e8-89f6-7b6417451afc.png)

[Triple.sav.gz](https://github.com/MegaMek/megamek/files/2275145/Triple.sav.gz)

**Comment by NickAragua** [comment]
Duplicate of #1088
