### ISSUE TITLE
[0.45.0 : Bug] Hover Tank Dropping onto Liquid Magma Not Destroyed

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#1093]
### Environment
0.45.0

### Description
Hover tank dropping onto liquid magma from magma crust not destroyed. Image below. (But it's hovering........)

### Files
![hovertankcannotmoveaboveliquidmagma-2](https://user-images.githubusercontent.com/17064665/43987492-1e996944-9d54-11e8-9120-7f1aaa42b821.png)

**Comment by BLOODWOLF333** [comment]
It looks like you mixed mine and ColSandersLite's tilesets together.

**Comment by SirMegaV** [comment]
Nope. I’m using your tileset then modify to use mine.
