### ISSUE TITLE
The Effects of Fire

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/megamek#111]
Per this comment from BT Forums and discussion above it.
http://bg.battletech.com/forums/index.php?topic=51280.msg1197736#msg1197736

TO pg 43 on Fire

And the unofficial MM Option fire burns down N TF per turn.

The TO rules state buildings burn at 2 per turn regardless of size/type. The MM Option allows the user to set how much damage Trees take per turn when on fire. There is nothing about Fields or other non-tree burnable stuff.

Fields should burn down like trees since that is obvious, perhaps even faster/slower.

Other terrains should probably burn down as well. If it has a Terrain Factor (except for Rough or including it) then it should be able to burn. In burning it should also be able to burn down.

Also Ref: TO pg 64

**Comment by scJazz2** [comment]
as me and BW have gone over stuff... Rough, Clear, Sand... they have TFs but should not be able to be ignited. Anything else with a TF < 131 should burn at the Option NN rate. (TF <131) covers ultra heavy woods which exist on some maps.) This also avoids burning Pavement and Roads which have TF values.

**Comment by BLOODWOLF333** [comment]
I second this request.

**Comment by neoancient** [comment]
Closing as nobody has shown any interest in implementing this.
