### ISSUE TITLE
Unable to replace allied bot

### ISSUE THREAD

**Issue by Schugger** [MegaMek/megamek#1114]
Using MegaMek HQ, Windows version 0.44.0 downloade June 25th 2018.
Java Version 8 Update 161 (build 1.8.0_161-b12)

I can't replace the allied bot (in this case Steiner) with Princess when restarting a battle from a savegame.
Replacing the other bots just works fine using either the toolbar command or chat comman.
Evenretrying repalcing the allied bot with testbot doesn't work, but here I recieve the message that the bot has connected to the game (but it does not cunduct any actions, though).

Added files
Megamek savegame file

[2018-08-26_Schugger.sav.gz](https://github.com/MegaMek/megamek/files/2321445/2018-08-26_Schugger.sav.gz)

**Comment by NickAragua** [comment]
It looks like the issue with the "Steiner" player in this case is that the player's name is actually spelled "Steiner ", with a space at the end. Not sure how it wound up that way.

A workaround that may be sufficient for you is to manually edit the save game file (extract it and the internal file is basically just a very large xml file). Look around for instances of "<name>Steiner " (with the space afterwards), and remove the trailing space. That should allow you to replace the player with no issue.

**Comment by Schugger** [comment]
Thnaks for having a look into it. I assume I added the space by renaming the bot name while editing the contract in MHQ.
As a workaround for this contract, I let MHQ create the battle, added another allied bot in the MM lobby and switched the units from "Steiner_" tp the newly created bot.
So if I had to teload a battle, I could replace the newly created bot just as fine as the other bots.
