### ISSUE TITLE
Princess won't cross bridges w ground vehicles

### ISSUE THREAD

**Issue by TrailblazerDan** [MegaMek/megamek#1119]
Princess Bot will not cross bridges with ground vehicles.

Issue noticed in both 0.44.0 and 0.45.0, savegame below from 0.45.0:

[PrincessBridgeLog.txt](https://github.com/MegaMek/megamek/files/2342729/PrincessBridgeLog.txt)
[PrincessBridge.sav.gz](https://github.com/MegaMek/megamek/files/2342730/PrincessBridge.sav.gz)

**Comment by NickAragua** [comment]
Thanks for the save, that helped track the issue down pretty quickly.
