### ISSUE TITLE
Feature Request: Trailers

### ISSUE THREAD

**Issue by Necrofox91** [MegaMek/megamek#1125]
Moving it here from my post in 'HQ. Basically requesting support for trailers and hitching vehicles. Use for artillery and also the logistical chain side of things. Possible problem: all the crazy combinations and functionality we can come up with just standard models currently in game. Later problem: in mission reload and use of cargo, not just from 'arty but also from reloading mechs from cargo carried in said logistical chain. (Probably something for a different issue, but including it for completeness sake and the ease of modifying it later on... if my half remembered coding in basic from 7 years ago is right)
Also sorry from kinda screwing on and issue again Hammer&neo.
Err see issue 912 from 'HQ for my original post.

**Comment by HammerGS** [comment]
I actually opened it for you here - https://github.com/MegaMek/megamek/issues/1124

**Comment by Necrofox91** [comment]
Sorry, must have been similar times. Didn't find it when I searched before opening this.
Now I REALLY should go sleep.
Sorry for all the trouble Hammer.

**Comment by HammerGS** [comment]
No trouble, this way the person who's chipping away at it can see the comments in the other thread.

**Comment by Necrofox91** [comment]
Thanks.

**Comment by Necrofox91** [comment]
Forgot to properly refence it.
