### ISSUE TITLE
Cannot Increase/Decrease Elevation in Map Editor

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#1130]
### Environment
Megamek 0.45.0
Windows 8.1 x64
Java 1.8

### Description
![image](https://user-images.githubusercontent.com/16950832/45327883-1114f580-b51f-11e8-84ee-22962bb0415b.png)

Even if I select like the Woods:1-3 terrain it does not allow me to change a hex's elevation + or -.  I dont remember if there use to be a selectable elevation terrain or if the U and D buttons wrote Elevation:* to the board file.

### Files
[megameklog.txt](https://github.com/MegaMek/megamek/files/2368622/megameklog.txt)

**Comment by SJuliez** [comment]
I don't entirely understand the issue but in any case with the new Map Editor GUI this is probably solved or, if not, should be re-posted based on the new GUI. Therefore closing this.
