### ISSUE TITLE
Epimetheus Era inconsistent

### ISSUE THREAD

**Issue by sixlettervariables** [MegaMek/megamek#1147]
Copying from: https://bg.battletech.com/forums/index.php?topic=62796.0

It appears the Era is set incorrectly for the Epimetheus: https://github.com/MegaMek/megamek/blob/4de5dc6fbafda1eb8747d431acd09563324c0adc/megamek/data/mechfiles/mechs/3055U/Epimetheus%20Prime.mtf

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/cb3bf61b6735258f2dc6e1bea51de4a77e1fc2dc
