### ISSUE TITLE
[0.45.1 : Bug] Same team in double blind mode cannot deploy in the same zone

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#1150]
### Environment
Megamek 0.45.1

### Description
Previously in a double blind game, I/Princess can deploy in the same zone as my/Princess' allies, but not anymore. 

To test, just turn on double blind mode, create an ally bot, same team, set to same deployment zone.

**Comment by PhoenyxCullen** [comment]
Another is to turn off "Exclusive Double Blind deployment zones" in megamek game options.

**Comment by SJuliez** [comment]
I believe this is solved with 0.49
