### ISSUE TITLE
Autoenable machine gun burst fire for all units.

### ISSUE THREAD

**Issue by Crutchmaster** [MegaMek/megamek#1155]
If I play AtB with brust fire machineguns option bots not set it for self. I must select every unit and set all machineguns in brust mode. Need option/button/command for switch on them all. 
Any information how to implement this will be useful.

**Comment by HammerGS** [comment]
You should be able to do this in the lounge. Multiselect the units, and right click.  Units with MG would be able to switch to burst fire mode.

**Comment by Crutchmaster** [comment]
Ok, this already works:) Set as closed.
