### ISSUE TITLE
Deployed and immediately fell into a basement

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#1161]
![image](https://user-images.githubusercontent.com/19868605/46125664-1ef19880-c1f8-11e8-8daf-860087236126.png)

[DeployBasement.sav.gz](https://github.com/MegaMek/megamek/files/2422654/DeployBasement.sav.gz)

[gamelog.zip](https://github.com/MegaMek/megamek/files/2422696/gamelog.zip)

Is MM supposed to be  checking for random basements during deployment? I've never seen this before.

**Comment by neoancient** [comment]
Yes. If you have random basements turned on, it checks whenever you enter the hex. That can be during movement or deployment.

**Comment by giorgiga** [comment]
One related weirdness I noticed is that, when deploying infantry in a building, the hex basement is disclosed regardless of if the unit is at XXX a floor  higher than the ground floor and,  when moving infantry through a building, the basement is only disclosed when infantry  is on the ground floor.

I don't think this is worth a fix: I'm mentioning this just in case someone decides to look into basement disclosure code and happens to stumble into a solution to this very minor glitch.
