### ISSUE TITLE
MegaMek is not generating OpFors for campaigns in MekHQ

### ISSUE THREAD

**Issue by mvodusek** [MegaMek/megamek#1168]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
What version of MegaMek does your issue apply to? 45.1  Note whether it is the stand alone MegaMek or HQ's MegaMek.  MekHQ
What operating system are you using?  Windows
What java version are you using?  Version 8 Update 181

### Description
When generating scenario, my units appears, but Opfor is not being generated, although it states a team for the bots, it doesn't fill the team with units.

### Files
This is occurring during scenario generation,and so no saved file can be given.

**Comment by sixlettervariables** [comment]
A save game from MekHQ and both the megamek and mekhq logs are necessary to begin investigation.

**Comment by mvodusek** [comment]
Issue was resolved with beginning a new campaign, likely an operator error
