### ISSUE TITLE
[0.44.0 Bug] Rocket Launcher bug after configuring unit

### ISSUE THREAD

**Issue by blah2355** [MegaMek/megamek#1177]
MegaMek 0.44.0
Windows
Java 1.8.0_161

Configure a unit that has Rocket Launchers in the lobby and start the game normally. When firing the Rocket Launchers, only one Rocket Launcher appears to have fired. All other Rocket Launchers of the same size cannot be fired in the next firing phase as they're "out of ammo", even though they weren't fired at all.

The bug occurs when configuring the unit with the Rocket Launchers in the lobby. A work around I found is to configure the unit first, save it as an MUL, delete the unit from the lobby, and then load the MUL. Changing teams says that the unit has been configured but the bug did not appear for me afterwards.

**Comment by ObviousTech** [comment]
Bug also exists in 0.45.1.
