### ISSUE TITLE
[0.45.0 : Bug] BotClient.getStartingCoordsArray Error

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#1178]
### Environment
0.45.0

### Description
Princess was deploying units in space (space battle) then it went unresponsive. BotClient.getStartingCoordsArray was found in the log. Save game provided. Just deploy the remaining few units and it will be the Princess' turn to deploy and hit the error.

### Files
[BotClient.getStartingCoordsArrayLog.sav.gz](https://github.com/MegaMek/megamek/files/2477475/BotClient.getStartingCoordsArrayLog.sav.gz)
[BotClient.getStartingCoordsArrayLog.txt](https://github.com/MegaMek/megamek/files/2477476/BotClient.getStartingCoordsArrayLog.txt)

**Comment by NickAragua** [comment]
This area of the code has now been modified and bulletproofed to hell and back. Please reopen if it occurs again.
