### ISSUE TITLE
[0.45.0 : Bug] SerializationMethodInvoker.callReadObject Error

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#1180]
### Environment

0.45.0

### Description

Space battle with against Princess (using the newton movement).

Been getting 'save' error in this battle. Error SerializationMethodInvoker.callReadObject found when trying to load corrupted save. Happening occasionally, still cannot identify cause or a break point. It might or might not happen during save. One thing I notice is the working save at round 7 is 3MB while the corrupted save at round 8 is 7MB.

Will TRY to identify the cause, if possible.......

Save game with and without error attached. Log attached.

### Files

[SerializationMethodInvoker.callReadObject-Log.txt](https://github.com/MegaMek/megamek/files/2481397/SerializationMethodInvoker.callReadObject-Log.txt)
[SerializationMethodInvoker.callReadObject-SaveWithError.sav.gz](https://github.com/MegaMek/megamek/files/2481398/SerializationMethodInvoker.callReadObject-SaveWithError.sav.gz)
[SerializationMethodInvoker.callReadObject-SaveOneRoundBefore.sav.gz](https://github.com/MegaMek/megamek/files/2481404/SerializationMethodInvoker.callReadObject-SaveOneRoundBefore.sav.gz)

**Comment by SirMegaV** [comment]
Sorry, failed to find the cause. When I’m looking (very frequent save then load), it doesn’t happen. When I’m not looking (save at every start of the round and load), it happens.

**Comment by SJuliez** [comment]
This was an out-of-memory error, so we can't do much about it.
