### ISSUE TITLE
Armor not correct on some Warships

### ISSUE THREAD

**Issue by AaronGullickson** [MegaMek/megamek#1183]
### Environment
v0.45.1, OSX, Java 8. 
The issue is with the underlying data and is the same on MHQ, MM, and MML.

### Description
Several of the warships seem to have their AFT armor value swapped with one of the aft rear sides, most commonly ARS. I tracked the issue all the way back to the BLK file for the Black Lion II Cruiser so it is likely the same problem for other units. I have not checked against canon for alll units, but since ALS and ARS are generally supposed to match, its fairly easy to identify the problem cases. Here is what I have ID'ed:

- Aegis (2372)
- Aegis (2582)
- Agamemnon (Standard)
- Athena (2569)
- Black Lion II (2691)
- Congress (2542)
- Cruiser (Standard)
- Davion Destroyer (Block II)
- Essex II (2711)
- Feng Huang (Upgrade)
- Fox (3057)
- Impavido (3058)
- Inazuma (Standard)
- Kirishima (3061)
- Kyushu (3057)
- League (Block II)
- Luxor (2727)
- Monsoon (2574)
- Newgrange III (Erinyes)
- Newgrange (Standard)
- Suffren (3062)
- Tatsumaki (Standard)
- Tharkad (WoB)
- Thera (Standard)
- Volga (2709)
- Aegis (2843)
- Liberator (3024)
- Carrack (Clan)
- Congress (2914)
- Congess D Frigate (Standard)
- Faslane (Standard)
- Kimagure (Surprise)
- Naga Destroyer (Caspar II Control Ship)
- Whirlwind (2606)

**Comment by mkerensky** [comment]
I found this one too and asked Neoancient about it.  MML is saving the armor data in one order, and there was some kind of conversion in the BLK loader for warships that changes the order.  So essentially, you'll see this on any of the Canon ships that were modified with this release to bring them in line with construction rules.

**Comment by neoancient** [comment]
The blk files for JS/WS/SS previously had the armor values in a different order than the location indices. Rather than maintain extra code for changing the order on writing and reading I switched it to the natural order and the files were adjusted when they were updated. Apparently some were missed, which happens with an update of this magnitude. I can write a script that will implement a batch fix.

**Comment by AaronGullickson** [comment]
Not trying to make work for @HammerGS, but I am wondering if this is a small enough list that it could be fixed as quickly by hand. I did notice that at least one ship (Aegis 2582, IIRC) had a swap with ALS and AFT rather than ARS and AFT so an automated solution could be tricky.

**Comment by HammerGS** [comment]
I've got time this weekend to do the list. So I'm good either way.

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/1dc0a94cf9b07e063b44723edd3f5887b9a4c6a8
