### ISSUE TITLE
41.15 : Clan RATs exclude most variants?

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#119]
I've noticed that the 3052 RAT at least seems to exclude most clan variants for some odd reason.

For example, the clan jade falcon RAT only includes two entries for the Stormcrow, and both are for the prime variant. This seems odd because i highly doubt that any clan would use one variant exclusively for omni mechs.

Is this intended?

3052 CJF RAT below : 

3053 Clan Jade Falcon Mech - Medium
Black Lanner D,1
Black Hawk (Nova) C,2
Fenris (Ice Ferret) B,3
Dragonfly (Viper) A,4
Dragonfly (Viper) Prime,5
Ryoken (Stormcrow) Prime,6
Ryoken (Stormcrow) Prime,5
Black Hawk (Nova) A,4
Fenris (Ice Ferret) B,3
Shadow Hawk IIC (Standard),2
Shadow Cat Prime,1

**Comment by pheonixstorm** [comment]
My guess, if they are from a canon source then yes.

**Comment by Akjosch** [comment]
All the official RATs are meant to be exactly like that. That's not to say that it's *impossible* that they have errors in them, but you'd have to check against the actual source to be sure.

Thankfully, you can write your own RATs easily. They don't even have to conform to the weights imposed by the 2d6 roll (the 1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1 numbers at the end of the line in the example you cited) and they aren't limited in the number of entries either.
