### ISSUE TITLE
MegaMek 0.44.0 Boosted Cybernetic Comm Implant Can't Connect To C3i

### ISSUE THREAD

**Issue by TheSilken** [MegaMek/megamek#1194]
MegaMek version 0.44.0
Windows 8
Java version 1.8.0_31

Using the Manei Domini implant advanced rules I attempted to link a pilot with the Boosted Cybernetic Communications Implant to a unit with an open C3i Network, as both the description in MegaMek and the rules for the implant say on pg.78 of Interstellar Operations, but there is no support for this that I could identify in MegaMek. Please add the ability to properly link this implant with C3i.

**Comment by neoancient** [comment]
Most of the augmented warrior special abilities have yet to be implemented. Some that are implemented use the original rules from the Jihad sourcebooks and have yet to be updated to the newer Interstellar Operations rules.

**Comment by mkerensky** [comment]
This actually used to work and broke a couple of versions ago.  I'll take a look.

**Comment by mkerensky** [comment]
This should be fixed with the next release.  We changed the names of many of the MD implants fairly recently. Most likely this was introduced at that time.  The C3i network trigger was set to look for standard multimodal implants (instead of enhanced) and boosted comm implants.

**Comment by sixlettervariables** [comment]
Fixed by #1226.
