### ISSUE TITLE
[0.45.2] Sprite 3 armor and JJ errors

### ISSUE THREAD

**Issue by Xeno426** [MegaMek/megamek#1198]
### Environment
0.45.2
Platform Windows 7 6.1 (x86)
Java version 1.8.0_151

### Description
The Sprite 3 currently has 66 total armor points and three jump jets. This leaves the protomech 1,000kg underweight.
However, the original (illegal) design in the WoR Supplement had 65 points of armor (14 leg points rather than 15, like in the MM version) and five extended jump jets rather than three regular jump jets.
https://i.imgur.com/f2LdDQ5.png
The errata for the Sprite 3 *only* changes the two fusillades in the arms (1500kg each) to a pair of medium chemical lasers and 15 rounds each (1500kg each). Armor allocation and jump jets were not changed.

**Comment by HammerGS** [comment]
This has been fixed for the next release, just not committed.

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/cb3bf61b6735258f2dc6e1bea51de4a77e1fc2dc
