### ISSUE TITLE
New and Fixed Aerospace BLKs

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/megamek#12]
New:  Leopard (PPC) file. This one is in the MUL and several of the 3085 and 3145 RATs. 

[Aerospace BLKs.zip](https://github.com/MegaMek/megamek/files/105896/Aerospace.BLKs.zip)

Fixed:  Leviathan III file.  The original had NAC30s where NAC20s should have been, producing two bays instead of one, one of which had no ammo.

**Comment by HammerGS** [comment]
Commit 1cabaca
