### ISSUE TITLE
Woods images not chosen randomly, but by row

### ISSUE THREAD

**Issue by SJuliez** [MegaMek/megamek#120]
It seems the woods images chosen by the tilemanager for a given woods hex aren't chosen randomly, but based on the row number. In the screenshot, all hexes along a row have the same image. Makes woods look more regular than necessary.

![mm_tiles](https://cloud.githubusercontent.com/assets/17069663/14202262/4bd84f42-f7f7-11e5-9a65-983245ee5d02.png)

**Comment by Akjosch** [comment]
It uses the Coords.hashCode() code, which I noted earlier, when fixing the missing equals() code, as being kinda strange. It is essentially (for positive coordinates) `x * 512 + y * 4`, which then gets "improved" by using `seed = (seed >> 3) + (seed)`, which (for low values of x and y, as is usual for most maps) makes it to:

    seed = (x + 8) * 64 + (y + 8) / 2; // rounded down

So ... yeah. I guess we should remake Coords.hashCode() to be a bit more "hashy".

**Comment by SJuliez** [comment]
Ah ok thanks.
So, I get the impression (but haven't looked at the code) TileManager delivers a woods image based on the hashcode to make it reproducible and so it doesn't actually have to save what image belongs to a hex. In this case, we could just replace that with a more random, but reproducible function. This wouldn't have to fill the needs a hashcode has to. (x*23+y*17)^7, take two digits from the middle...

Do you think it's necessary to make the hashcode itself more randomly-looking for other purposes? What I mean is: does that have some other advantage? I can make the above work, but I have little idea of actual hashcodes.

**Comment by Akjosch** [comment]
A good int hash is valuable by itself, because you often have a need of repeatable pseudorandom numbers. PRNGs work better when seeded with a "hashed" number with multiple bits set, you can use them to create replayable dice rollers, and they result in visually pleasing "random" patterns for little cost.

So unless there's some major reason why we shouldn't, I'd suggest we add an utility int hash method based on one of the linked above and use it to create the hash in the `Coords` constructor.

**Comment by Akjosch** [comment]
There you go, a proposed bugfix. Feel free to just merge it if it fixes the issue and doesn't introduce any other visual strangeness.

If it does, it'd be trivially easy to replace `HashCodeUtil.hash1()` with something else and try again.

**Comment by arlith** [comment]
I'm be curious to see a before and after shot of some heavy woods or something.

**Comment by Akjosch** [comment]
Easy enough.

![Woods before](https://cloud.githubusercontent.com/assets/1029805/14226661/3ad57746-f8e8-11e5-8758-3dbee0e6da85.jpg)

![Woods after](https://cloud.githubusercontent.com/assets/1029805/14226663/4015c508-f8e8-11e5-852c-f88859d12b69.jpg)

I fiddled a bit with the code to make it even "more" random for low values of x and y.

By the way: XStream being a bit on the *edgy* side and using `sun.misc.Unsafe.allocateInstance(...)` to load the savegames means it's bypassing constructors - not just for Coords, *all* of them - and so "old" save games will have a coords hash of 0. It can be fixed, but I'm not sure it's worth the effort.

**Comment by arlith** [comment]
Do you find either of those images more appealing than the other?  I'm kind of curious what other people's opinions are.  In aggregate, they both appear pretty similar to me.

**Comment by vizax** [comment]
I don't particularly see too much of a difference at a glance, however, I'm not known for my OCD to lean that way. :-)  On principle, I like the variety it seems to add (on closer examination).

**Comment by pheonixstorm** [comment]
The top image has an unnatural pattern to it while the bottom is more natural and random.  While I don't like the woods icon itself I do prefer the method from the bottom image.

**Comment by pheonixstorm** [comment]
As an after thought this would make for a good PR rewrite post stable. Perhaps even request a few new woods/jungle icon sets to give an even greater number of choices for randomly chosen fauna.

**Comment by vizax** [comment]
I know this doesn't fit any theme, but i did this this morning. *shrug* like it or hate it, not gonna hurt my feelings. I'm no artist I can understand if you don't.  :grinning: 
![heavy woods_alt](https://cloud.githubusercontent.com/assets/1894549/14233370/28d14bca-f98c-11e5-9fb2-f1b4f81d758c.png)

**Comment by pheonixstorm** [comment]
Soo... we can call it essence of a baby diaper and you're ok with it?

But actually I think it you add some brown and lighten up the green slightly it would make a good swamp hex.

**Comment by vizax** [comment]
You think its that good?! Art School, here I come! Woohoo! 

Swamp... Yeah, thats what I meant it as.. Mispost to the "woods"  thread, apparently.

**Comment by BLOODWOLF333** [comment]
Im always willing to make new map images.  Though I do like those 'above" woods images better than the normal atmospheric tileset ones.  The above I think work very well for jungle themes.

**Comment by Akjosch** [comment]
You will also be able to be a little bit sneaky (since a few minutes :)) and utilise the same image four times, only mirrored. Note that it doesn't work particularly well with images which have shadows backed in ...

```
base 0 "" "" "boring/beige_plains_0.gif;boring/beige_plains_0.gif(0,72-84,-72);boring/beige_plains_0.gif(84,0--84,72);boring/beige_plains_0.gif(84,72--84,-72)"
```

What it does is using *negative* height and width values, which mean the image is mirrored accordingly when copying it. Easy, quick variation at least for rather "flat" images like the background one in the example.

**Comment by BLOODWOLF333** [comment]
^ That is nice, I have always wished that it would randomly flip or rotate the images on the board.  Can you get it to randomly rotate the images in 60 degree increments, buildings as well?

**Comment by Akjosch** [comment]
I *can* make them rotate, but I don't particularly *want* to. They lose quite a bit of quality this way, unless the base files are at least twice as large as the displayed ones.

**Comment by BLOODWOLF333** [comment]
Dang, mirror works then.  This gets my vote.  This will apply to buildings too right?

**Comment by Akjosch** [comment]
This does apply to every hex image. If you have one that's the default size, 84x72, these are the easy options which don't involve scaling or rotation:

    "image.ping(0,0-84,72)" -- No change. Why would you do this?
    "image.ping(0,72-84,-72)" -- Mirror vertically (switch top/bottom)
    "image.ping(84,0--84,72)" -- Mirror horizontally (switch left/right)
    "image.ping(84,72--84,-72)" -- Mirror on both, which is the same as a rotation of 180 degrees.

**Comment by BLOODWOLF333** [comment]
i like it!  This isn't going to mess up the building linker when it changes the images to light/medium/etc?

**Comment by Akjosch** [comment]
The building linker doesn't care what is in the image part of the tile set definition. That's purely for the visuals.

**Comment by arlith** [comment]
I'm going to close this ticket, as the Cords.hashCode change was implemented.
