### ISSUE TITLE
Mechwarrior Online - Corsair inclusion in MM

### ISSUE THREAD

**Issue by MGM175** [MegaMek/megamek#1200]
### Environment
Not applicable. 

### Description
There are 3 mechs exclusive to MwO as we know:

Roughneck - http://www.sarna.net/wiki/Roughneck

Sun Spider - http://www.sarna.net/wiki/Sun_Spider

And now the newly unveiled Corsair. 

http://www.sarna.net/wiki/Corsair_(BattleMech)

I don't know about incorporation of the previous two (fully or just Hero variants only), but I'm asking for Corsair inclusion to MegaMek as well. 

### Files
Not applicable.

**Comment by HammerGS** [comment]
We've added the Roughneck and Sun Spider. The Corsair is a Frankenmech and we currently don't support them.
