### ISSUE TITLE
Roc Z missing main gun

### ISSUE THREAD

**Issue by Xeno426** [MegaMek/megamek#1206]
### Environment
0.45.2
Platform Windows 7 6.1 (x86)
Java version 1.8.0_151

### Description
The Roc Z has medium chemical laser rounds, but no actual gun. It's just... missing. I've uploaded the version of the file from my download.
[Roc Z.zip](https://github.com/MegaMek/megamek/files/2687662/Roc.Z.zip)

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/cb3bf61b6735258f2dc6e1bea51de4a77e1fc2dc
