### ISSUE TITLE
Boggart and Basilisk (Quad) Protomechs missing map art

### ISSUE THREAD

**Issue by Xeno426** [MegaMek/megamek#1207]
### Environment
0.45.2
Windows 7 6.1 (x86)
Java version 1.8.0_151

### Description
The Boggart and Basilisk (Quad) protomechs recently (as of 0.45.2) had their file names changed (i.e. "Boggart" is now "Boggart Ultraheavy ProtoMech"). However, the mechset.txt file has not similarly been updated to this new chassis name. As a result, the icons on the map use the protomech default Roc art.

### Files
The lines in "mechset.txt" should be changed from:

exact "Basilisk (Quad)" "protomechs/Basilisk (Quad).png"
chassis "Boggart" "protomechs/Boggart.png"

to

exact "Basilisk ProtoMech (Quad)" "protomechs/Basilisk (Quad).png"
chassis "Boggart Ultraheavy ProtoMech" "protomechs/Boggart.png"

Alternatively, change the names of the Boggart and Basilisk (Quad) to 0.45.1 names.

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/cb3bf61b6735258f2dc6e1bea51de4a77e1fc2dc
