### ISSUE TITLE
Can't select Thunder LRMs for LRM launchers in 0.45.2

### ISSUE THREAD

**Issue by mhjacks** [MegaMek/megamek#1216]
### Environment
What version of MegaMek does your issue apply to?  0.45.2
What operating system are you using?  Windows, Mac, or Linux? Linux
What java version are you using?  If unsure it will state your java version at the top of the megameklog.txt file. openjdk version "1.8.0_191"

### Description
Describe the issue and provide screenshots ingame if able.  
When selecting Ammo types in the lobby, Thunder LRMs aren't available, despite the year allowing it and being at unofficial tech level.  FASCAMs are available for Arrow IV launchers.
Provide the rulebook, page number, and text if you feel like this is a rules issue.
And provide the steps you have taken to reproduce the issue in the saved game if applicable.
This holds with all LRM capable units I've tried (mechs, LRM carriers etc)

### Files
Provide a saved game of when the issue was found.  If possible try to save the game during the phase before the issue occurs so the 
developers can step through the code and find exactly what it is that is breaking in the code.
Provide the megameklog.txt file for any NPE's or errors that MegaMek might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual megameklog.txt file
And provide your playername so that they can load the saved game.
(Delete the above lines)

**Comment by NickAragua** [comment]
I'm unable to reproduce this. If it happens again, please provide an example of a unit, as well as a preset file with the megamek game settings.
