### ISSUE TITLE
[MekHQ 0.45.1] Movement Phase hung - Battle Armor unit that has swarmed a mek

### ISSUE THREAD

**Issue by nsecomb** [MegaMek/megamek#1220]
### Environment
MekHQ 0.45.1
Windows 10
Java version 1.8.0_161

### Description
Initiative Phase for Round #4
-------------------
The turn order for movement is:
Raven RVN-3M (Free Worlds League), rolled 5[5+0]
Lightning Attack Hovercraft (Royal) #3 (RB 2nd Reg), rolled 7[4+3] / 6[3+3]
Hermes II HER-5S (Free Worlds League), rolled 7[7+0] / 9[9+0]
Lightning Attack Hovercraft (Royal) #4 (RB 2nd Reg), rolled 8[5+3]
Stinger STG-3R (Free Worlds League), rolled 9[9+0] / 7[7+0]
IS Standard Battle Armor [SRM] (RB 2nd Reg), rolled 9[6+3] / 10[7+3]
... [rest of list deleted to save space]

Movement goes normally until I've moved Lightning Attack Hovercraft (Royal) #4, and then the game hangs such that I can't move my next unit - IS Standard Battle Armor [SRM]. This happens when I load it from both the last save in turn at the time it froze, and when I load the autosave from end of turn 3 and run through movement again.

In Turn 3, IS Standard Battle Armor [SRM] successfully swarmed Stinger STG-3R. I'm assuming the freeze is on IS Standard Battle Armor [SRM]'s turn, and when I zoom and hover it suggests Stinger has tried to run, and that IS Standard Battle Armor [SRM]'s did not move - see screenshot. It's also displaying the movement track from my previously moved unit.

### Files
Screenshot: BA_swarm_freeze.jpg
Autosave from end of Turn 3: BA_swarm_freeze_Autosave.sav.gz
Playername: RB 2nd Reg
(port = 2346)
![ba_swarm_freeze](https://user-images.githubusercontent.com/46305290/50577964-57ec7980-0e87-11e9-823d-acfd86ce38a2.jpg)
[BA_swarm_freeze_Autosave.sav.gz](https://github.com/MegaMek/megamek/files/2719751/BA_swarm_freeze_Autosave.sav.gz)

[Mek_HQLog_Copy.txt](https://github.com/MegaMek/megamek/files/2720018/Mek_HQLog_Copy.txt)

**Comment by HammerGS** [comment]
Was their a log file you can attach.

**Comment by nsecomb** [comment]
> 
> 
> Was their a log file you can attach.

Have played on since, so have extracted the log content for today up to the point where I started the mission from scratch, so that you can see what it had at the time of the hangs. Have attached to original post.

**Comment by NickAragua** [comment]
Took a while to get to this one, but I loaded this game up. Encountered a number of exceptions, but nothing related to swarm battle armor. Please re-open and let us know if you encounter something like this again.
