### ISSUE TITLE
Swarm Attacks should get a crit chance, even if they don't do damage (MM 0.45.2)

### ISSUE THREAD

**Issue by mhjacks** [MegaMek/megamek#1223]
### Environment

19:34:20,800 INFO [megamek.MegaMek] {main} 
Starting MegaMek v0.45.2 ...
        Compiled on Sun Nov 18 15:27:29 CST 2018
        Today is Thu Jan 03 19:34:20 CST 2019
        Java vendor Oracle Corporation
        Java version 1.8.0_191
        Platform Linux 4.19.12-301.fc29.x86_64 (amd64)
        Total memory available to MegaMek: 932,352 kB

### Description
TW says that Swarm attacks get a crit chance, even without armor penetration (TW p223).  TAG-equipped Achileus BA do not have other weapons and don't have a way to do damage, so my understanding of the rule may be flawed.

### Files
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/2725865/autosave.sav.gz)

**Comment by wildj79** [comment]
You're misinterpreting the rules here. Don't forget that the spirit of the rules is just as important as the explicit definition of the rules.

_**Critical Hits:** A swarm attack may also result in one or more critical hits. In addition to determining normal damage, the player rolls once on the Determining Critical Hits Table (p. 124), **even if no internal structure took damage in the attack.** If internal structure does take damage, this may result in two or more critical hits._ TW p. 223

The unit would still have to do _some_ damage. The bolded text above implies that some level of damage would still need to be applied. Any other interpretation would be a gross misuse according to the spirit of the rules.

**Comment by mhjacks** [comment]
OK - as I said, I'm not going to push my interpretation too hard, and on reflection I'm inclined to agree with you.  The "similar" cases I think, are leg attacks (which always damage, so always can crit) and reduced-damage-due-to-armor not inflicting pilot hits.  I can agree that looking at both of those cases, the way MegaMek does it is correct and consistent.
