### ISSUE TITLE
Please finish the Aero Sanity Mod

### ISSUE THREAD

**Issue by rogueranger1993** [MegaMek/megamek#1225]
I know that it may be a long time coming, but getting this feature finished and fully implemented would be a huge boon for some of us. I know I'd jump on the chance to have this implemented, since it makes aerospace support play a little nicer with the standard rules and thereby makes it more fun to include them in my forces for use in battles, rather than just flavor.

**Comment by mkerensky** [comment]
This has been implemented. Aero Sanity upgrade will be available in the next dev release.

**Comment by sixlettervariables** [comment]
Closed by #1258
