### ISSUE TITLE
Artillery automatic hit hex selection skipped 0.45.2

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#1228]
In a MekHQ ATB game, I had two Ballista artillery pieces deployed off-board.  Each time I deploy these pieces, MegaMek will not let me select 5 hexes, or any number of hexes for that matter, to mark for automatic hits.

I combed through the logs myself for clues, but couldn't find anything.  This happens each time I deploy my Ballistas.

[MegaMek Logs 1.18.2019.zip](https://github.com/MegaMek/megamek/files/2775514/MegaMek.Logs.1.18.2019.zip)

**Comment by neoancient** [comment]
Fixed by MegaMek/mekhq#1337
