### ISSUE TITLE
Feature Request: Intermittent Electrical Trouble

### ISSUE THREAD

**Issue by Bludlust135** [MegaMek/megamek#1232]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
What version of MegaMek does your issue apply to?  Note whether it is the stand alone MegaMek or HQ's MegaMek.
What operating system are you using?  Windows, Mac, or Linux?
What java version are you using?  If unsure it will state your java version at the top of the megameklog.txt file.
(Delete the above lines)

### Description
Describe the issue and provide screenshots ingame if able.
Provide the rulebook, page number, and text if you feel like this is a rules issue.
And provide the steps you have taken to reproduce the issue in the saved game if applicable.
(Delete the above lines)

### Files
Provide a saved game of when the issue was found.  If possible try to save the game during the phase before the issue occurs so the 
developers can step through the code and find exactly what it is that is breaking in the code.
Provide the megameklog.txt file for any NPE's or errors that MegaMek might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual megameklog.txt file
And provide your playername so that they can load the saved game.
(Delete the above lines)

**Comment by HammerGS** [comment]
No details provided closing.

**Comment by Bludlust135** [comment]
Sometimes, I like to set-up MegaMek to play a Scenario from some of the older scenario packs. Some the sceanrio's in a pack have special rules, in addition to Game Set-up with Defender and Deployment, Attacker and Deployment and Victory Conditions.  In particular, I was setting up for Sorenson's Sabres, The Red Forest on 28, the special Rules section on page 29 says that before I can fire, a +2 gunnery must be rolled to maintain lock on infantry. If the lock is failed, no fire takes place. In a scenario my group was playing a few weeks back, we were on a planet with very strong magnetics. Every turn, some of our electronic equipment would malfunction on an unmodified 2d roll of 10 or better for every player. Our GM had a chart made up that indicated what the trouble was, and what was needed to clear it.

Could something like that be automated in MegaMek?

**Comment by HammerGS** [comment]
This is something that has been discussed but nothing is pending. We have an RFE for this open on SourceForge.
