### ISSUE TITLE
0.42 : Bot continues fighting even after admitting defeat

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#1237]
At the start of the latest movement phase, i declared /victory and the bot admitted defeat, but in the firing phase, it still proceeded to fire on my units...it shouldnt be fighting anymore after admitting defeat.

[a.zip](https://github.com/MegaMek/megamek/files/2804317/a.zip)

**Comment by NickAragua** [comment]
If you want the game to end immediately after declaring /victory, there's a setting in game options that does that. Go to Victory -> Skip all phases when forced victory occurs.
