### ISSUE TITLE
Mad Cat (Timber Wolf) pod loadout error

### ISSUE THREAD

**Issue by pjfarland** [MegaMek/megamek#1256]
MekHQ 45.3
Java version 1.8.0_201
Platform Windows 10 10.0 (amd64)

There is a Hydra-TF Omnipod loadout that has four LB 10-X's and no ammo for them.

**Comment by HammerGS** [comment]
We don't support data fixes on Units in the unofficial folders.  Your best bet is to use MegaMekLab to fix the unit.

We don't have access to the original Record Sheets or Information to fix them.
