### ISSUE TITLE
[0.45.3] Hercules 'Mech sprite replaced by dropship sprite

### ISSUE THREAD

**Issue by Da-Nuker** [MegaMek/megamek#1265]
### Environment
0.45.3 Megamek & MekHQ, Windows 

### Description
Hercules HRC-LS-9000 and Hercules HRC-LS-9000 (Julius) uses the Hercules (3053) dropship sprite. 
Hercules HRC-LS-9001 shows the correct 'Mech sprite.

**Comment by mhjacks** [comment]
Bump - this still exists on a fresh install of the 0.46-rc1 mekhq tar.gz

**Comment by HammerGS** [comment]
Fixed recently.
