### ISSUE TITLE
Magna Laser Rifle has range 0 instead of 2.

### ISSUE THREAD

**Issue by stelljoe** [MegaMek/megamek#1266]
### Environment
Megamek 0.45.3 (Included in MegaMekLab). Win 7, Java 8 with latest updates.

### Description
Magna Laser Rifle has range 0 instead of 2. It's indicated in any and all instances (MegamekLab, MekWars unit view). Latest errata for TechManual does show range 2.

### Files
![default](https://user-images.githubusercontent.com/20140595/53261015-c49c2b80-36f4-11e9-8e54-6b98fb3f2689.png)
![default](https://user-images.githubusercontent.com/20140595/53261035-d8e02880-36f4-11e9-8084-e7e529279916.png)

**Comment by HammerGS** [comment]
Fixed here - https://github.com/MegaMek/megamek/commit/8b316136e0e814409267a858c88f12e02913aa8a
