### ISSUE TITLE
Vehicles Enter Heavy Woods

### ISSUE THREAD

**Issue by BairdEC** [MegaMek/megamek#1267]
MegaMek 0.45.3, started from MekHQ 0.45.3
Win 10
Java (build 1.8.0_201-b09)

Vehicles are able to move into heavy woods freely without taking damage or provoking PSR checks.  I believe I've seen hovercraft do this as well, but I don't have a screenshot.

Saved before movement: [autosaveWoods1.sav.gz](https://github.com/MegaMek/megamek/files/2897067/autosaveWoods1.sav.gz)
![woods](https://user-images.githubusercontent.com/38081112/53289794-e8448d80-3757-11e9-91ad-f87b1f871fd3.png)

Saved before movement: [autosavewoods2.sav.gz](https://github.com/MegaMek/megamek/files/2897068/autosavewoods2.sav.gz)
Saved after movement: [autosaveWoods2a.sav.gz](https://github.com/MegaMek/megamek/files/2897069/autosaveWoods2a.sav.gz)
![woods2](https://user-images.githubusercontent.com/38081112/53289798-f397b900-3757-11e9-94da-4f972374b84d.png)

[customs.zip](https://github.com/MegaMek/megamek/files/2897084/customs.zip)

**Comment by wildj79** [comment]
Based on your screen shots, I'd say this is rules as written. If the unit was traveling along a road, this is perfectly fine. Also, heavy woods doesn't force a PSR for entering into it's hex. (There is an unofficial _optional_ rule that forces a PSR, but that is specifically for 'Mechs jumping into heavy woods.)

See Total Warfare p. 61 for the relevant rules pertaining to units moving along a road.

**Comment by BairdEC** [comment]
You are completely right.  I missed the road somehow, although I think I've seen vehicles do it without a road.  I'll update the ticket if I see actual invalid movement.  Sorry about that.
