### ISSUE TITLE
Bug: Jungle move cost for infantry incorrect.

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/megamek#127]
Per TacOps movement example p30 infantry should pay 1 less MP for jungle movement. Currently infantry pay the full cost for jungle movement.

IE move to ultra heavy: Base +1 to enter hex +3 for ultra heavy jungle for 4MP
MM shows 5MP cost. 1 to enter hex and +4 to enter ultra heavy jungle

There are no changes in the errata to the example of movement into Hex from page 30 and did not find anything related on the forums.

**Comment by arlith** [comment]
Fixed with PR #183.
