### ISSUE TITLE
Better saved images for maps

### ISSUE THREAD

**Issue by rogueranger1993** [MegaMek/megamek#1270]
The map editor is a great tool, and when combined with the save as image function I can use it to create printable maps for my alpha strike games. However, the image is somewhat small, so it doesn't come out with the best quality when printed. Would it be possible for you guys to enhance this feature so that the image generated is already scaled to the default ~1" hexes of the default tabletop maps?

**Comment by SimonLandmine** [comment]
You can change the image size by zooming in (or out) on the map before hitting 'save as image' - would this resolve the issue without development work?
(Alternatively, a button that automatically triggers a zoom to the appropriate size and then triggers 'save as image', for that one-click feel.)

**Comment by SJuliez** [comment]
MM works with pixel images so any upscaling done in MM won't improve the quality (at least not any differently from what the printer driver does). I don't see any development possibility for this. Therefore closing this issue.
