### ISSUE TITLE
[0.45.3 : Bug] Cobra VTOL beginning game immobile.

### ISSUE THREAD

**Issue by GraalOtonami** [MegaMek/megamek#1271]
### Environment
Version: MekHQ Scenario, Version 0.45.3 - February 12/2019
OS: Windows 7 Ultimate
Java version: 1.8.0_181
(Delete the above lines)

### Description
Environmental Factors:
Wind = Calm
Weather = Clear
Gravity = 1.0 
Atmos = Standard
1 Pilot, 1 Gunner, custom units will be attached with save files at the end of the report for reproducibility.

After using the built-in army generator to create a force to match BV (700-1000) with 5 Vehicles, setting deployment time to "At the Start of the game" and mounting my two platoons within the Cobra, I start the game. There is no prior damage to the Cobra.
The game starts, and the Cobra is deployed as immobile. On following turns, rather than falling to the ground, it stays in place, but cannot move. It is able to shoot and be fired upon, able to mount infantry should it be deployed at height 0 or 1, and able to unmount them.

###Files
Drag and drop into MekHQ folder, screenshots and logs are also in the zipped folder.
[MekHQ.zip](https://github.com/MegaMek/megamek/files/2900801/MekHQ.zip)

**Comment by HammerGS** [comment]
Not sure if its related but the the log file has some errors around equipment. Which I suspect is hand modifications to custom unit files.

Also the last error listed in the log is thousands of lines of 

```
Exception in thread "AWT-EventQueue-0" java.lang.StackOverflowError
	at java.util.TreeMap.getEntry(Unknown Source)
	at java.util.TreeMap.get(Unknown Source)
	at mekhq.campaign.Campaign.getPart(Campaign.java:1665)
	at mekhq.campaign.parts.BattleArmorSuit.getTonnage(BattleArmorSuit.java:225)
	at mekhq.campaign.parts.BattleArmorSuit.getTonnage(BattleArmorSuit.java:227)
```
