### ISSUE TITLE
Missing Templar III TLR2-J "Arthur" from Shattered Fortress

### ISSUE THREAD

**Issue by Calvinfs852** [MegaMek/megamek#1274]
There's a unit in the back of Shattered Fortress that didn't make it into MM yet. 

MTF file renamed to a TXT:

[Templar III TLR2-J Arthur.txt](https://github.com/MegaMek/megamek/files/2916314/Templar.III.TLR2-J.Arthur.txt)

I have the PDF if you want to see the record sheet there, to double check the MTF

**Comment by HammerGS** [comment]
Added here - https://github.com/MegaMek/megamek/commit/d09f5fae41fb8eff5edd70fa53f4a55b8ae8612d
