### ISSUE TITLE
Artillery spotter modifier not working.

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/megamek#128]
Per TacOps when a spotter is present at when a shell is launched and lands the modifier should be -1:

> For every 2 points of Gunnery Skill less than 4 possessed by the spotting unit

Or +1 for every 2 above 4.
I am working on a fix for this and the other artillery bug I found.

**Comment by beerockxs** [comment]
Huh? This worked for a loooong time, that's what the ArtilleryTracker class is used for.

**Comment by pheonixstorm** [comment]
The fire adjust works, but not the other spotter modifier

**Comment by pheonixstorm** [comment]
@beerockxs @arlith 
How hard would it be to change how the roll reporting is done during the round reports? In situations such as this where the additional toHit data is not shown in the initial fire dialog I think that it should at least give a full valuation in the report that shows everything that goes into the hit/miss roll. Could also allow for finding current and/or future hit related bugs.

**Comment by arlith** [comment]
I think that it would probably be somewhat trivial to change.  I do feel like this would make the reports horribly cluttered though.  Maybe as an option, *shrug*.  Actually, could potentially do it as a hyperlink  too... Where it shows the number underlined, and either a tooltip would display the calculation, or you could click it and get a dialog (which seems effective but obnoxious).

**Comment by arlith** [comment]
Discussion can still continue, but, as you said earlier, this isn't an issue, so I'm going to close it.

**Comment by pheonixstorm** [comment]
I like the idea of a tooltip, so I guess whichever will be easier between a tooltip or as an option. I do think the tooltip would be better.
