### ISSUE TITLE
LRM5 smoke rounds says 'heavy smoke' on the report.

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megamek#1297]
### Environment
Ver 0.45.3
Windows 7

### Description
As title says, on the report it lands 'heavy smoke', although in the game it is actually a light smoke(and it should be, for its damage is 5 or less). 

So the report should says light smoke instead.

![000001](https://user-images.githubusercontent.com/47907439/54040224-394c8b00-4208-11e9-9370-d49b324db967.png)
![000002](https://user-images.githubusercontent.com/47907439/54040230-3d78a880-4208-11e9-894f-358609072f9e.png)

**Comment by mkerensky** [comment]
It appears that more than just the reporting for smoke LRMs/SRMs/MMLs  is off.  The smoke radius isn't being applied properly and it looks like firing more than one smoke round at different hexes with a single unit only registers 1 smoke hit on 1 hex.

**Comment by binaryspica** [comment]
So... for now even if a unit hits two smoke rounds on a hex it only results a Light Smoke?


And... just for the reference. The errata of Tactical Operations says;

> - Smoke Missiles fill a single target hex with a column of smoke 2 levels high (see p. 47)
>- This smoke is treated as Light Smoke if the weapon delivers 5 points or less in damage to the target hex. Otherwise, it is treated as Heavy Smoke.
>- This smoke dissipates in the End Phase of the third turn after the attack.

So... anything but LRM of LRM 5/MML 3/MML 5, or less(such as Battle Armor/Protomech/infantry weapons) are generates Light Smoke, otherwise it makes a Heavy Smoke.

**Comment by mkerensky** [comment]
Yeah there's definitely a bug and/or incomplete implementation here. I'll figure it out.

**Comment by mkerensky** [comment]
This has been fixed and you should see it in the next dev release.

**Comment by binaryspica** [comment]
Thank you for your hard work.
