### ISSUE TITLE
FM-3085 RATs Update

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/megamek#13]
[(3076 - 3100) - FM 3085.zip](https://github.com/MegaMek/megamek/files/105897/3076.-.3100.-.FM.3085.zip)

Update adds in the Leopard (PPC) to the appropriate dropship columns. Since this unit is not yet coded, I had replaced it with Leopard (3056) in my original submission.

**Comment by HammerGS** [comment]
I believe they are referencing the Leopard (Obsolete) version from TRO 3057.  I'm going to change the RATs in question to the Leopard (2537) version.

**Comment by mkerensky** [comment]
Check the Master Unit List - the Leopard (PPC) is a distinct variant from (2537), (3056) and - PA (which is the one I thought they were originally talking about, since it has the 5 PPCs with capacitors). I found the fluff text about it on www.sarna.net, which describes it being produced by the MoC. The RATs that use it are DC, CC and MoC so that fits.
It is apparently a Leopard (2537) that just has 5 extra standard PPCs instead of the 5 large lasers, and 10 fewer tons of cargo space to compensate for them.   It looked like the TRO the fluff comes from is 3057r. I only have the original, so I couldn't check it.

**Comment by HammerGS** [comment]
With Leopard (PPC) being mention in Objective Raids, which even CGL has said is very out of date and has lots of errors.  I'm going to stand by using the original 2537 in its place.  If CGL very gives stats are a more current write up we can alway switch it back in.

**Comment by HammerGS** [comment]
Commit 1cabaca
