### ISSUE TITLE
bombast Laser and vsp Laser targeting mods not working

### ISSUE THREAD

**Issue by beerockxs** [MegaMek/megamek#130]
The bombast Laser and VSP Laser bonus to to-htbin WeaponAttackAction#toHit are inside the isIndirectArtillery if and thus not applied correctly

**Comment by arlith** [comment]
Did you test that they are not being applied?  It looks like what happened is when the isIndirectArtillery conditional was added, all of the "weapon to-hit modifier" code was copied verbatim.  So there's the "VSP modifier" else "Bombat modifier" else "whatever the weapon has."  This code appears twice: line 1399 (isArtilleryDirect conditional) and also at line 1794.  The second part should be hit for non-artillery weapons.

I'm pretty sure this is just a case of superfluous code that can be removed, but I wanted to make sure you didn't have a test case that was failing.

**Comment by beerockxs** [comment]
I have no testcase, just noticed the code in the wrong if and had no time to fix it myself.

**Comment by arlith** [comment]
Alright, then I don't think it's a problem, just duplicate code.  I'll remove it.

**Comment by arlith** [comment]
Fixed in 47740f2
