### ISSUE TITLE
[0.45.3 : bug] Dropship Cannot Move In Atmospheric Map

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#1303]
### Environment

MegaMek version 0.45.3

### Description

All my dropship in atmospheric battle cannot move, only can hover. Just load my save and try moving it. No error in log.

### Files
[DropshipCannotMoveInAtmosphericMap.sav.gz](https://github.com/MegaMek/megamek/files/2959706/DropshipCannotMoveInAtmosphericMap.sav.gz)

**Comment by mkerensky** [comment]
Known issue I think.  This is on the "low altitude" map and applies to spheroid droppers and perhaps small craft, yes?  Your Aerodyne craft should be able to move.

**Comment by SirMegaV** [comment]
No problem with Aerodyne dropships. It was working the last time I played.

**Comment by SirMegaV** [comment]
Update - Still happening at MegaMek version 0.47.0

**Comment by NickAragua** [comment]
This set of rules was not fully implemented, but is will be mostly implemented as of the next release.
