### ISSUE TITLE
Princess doesn't know what to do after player breaks grapple with her 0.45.3

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#1306]
In a 'mech duel, my 'mech grappled with a Princess-controlled 'mech.  When I broke the grapple during the physical attack phase, Princess couldn't figure out what to do and the game did not continue through the physical attack phase.  I had to kick Princess, skip her turn, and replaced her again with Princess during the End Phase Report.

Log attached.

[megameklog.txt](https://github.com/MegaMek/megamek/files/2974601/megameklog.txt)

**Comment by NickAragua** [comment]
I tried to reproduce this behavior, but could not. It must have been some kind of specific case - at this point, I'm going to need a save.

**Comment by SJuliez** [comment]
As there doesn't seem to be a save forthcoming and no work on it is possible atm, closing this.
