### ISSUE TITLE
Use Dialogue when Unit Jumps/Moves on a Bridge

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/megamek#131]
Currently, if you jump/move on a Bridge hex you end up on the underlying terrain. Unless you use CLIMB.

Instead please use a Dialogue, use bridge/don't use bridge.
Needs option for this hex only or entire move. So that a unit can move onto a bridge hex, move across some bridges, and then get off the bridge into cover.

**Comment by beerockxs** [comment]
This currently works correctly when using climb Mode. Climb up = move onto bridge

**Comment by scJazz2** [comment]
Yeah it does Bee. But who in the hell would think of using Climb to stay on a Bridge? Arlith wasn't even sure it still worked. So how about fixing it so a newb isn't baffled. Or an Advanced Player.

**Comment by arlith** [comment]
No, I wasn't sure that it would be enabled in jump mode.  I knew for certain that it worked with walking.  You may quibble about the naming, but I think that the way it currently works is better than a dialog.  Basically, if you ignore the name, the button already does what you request (either you're in "don't use bridge" mode or you're in "use bridge mode" you just have to turn it on before you click on the destination hex, and you don't get an annoying pop-up).

I don't feel like climb mode is the most descriptive name for what the button does, however I don't know that there's a good one or two word alternative.  Really, the button needs a tooltip.  And really, *all* the buttons need tooltips.  This is a somewhat easy project that I've had in mind for a while.  Really, there are just like 6 code locations that need to be modified, and then the i18n entries need to be made (which is really the hardest part).

As it is, I don't think this request is the right way to solve the problem, so I'm closing it.

**Comment by Akjosch** [comment]
In particular, the buttons need a tooltip explaining why they *aren't* available in the current situation.
