### ISSUE TITLE
Easier Way to See What Units Have Already Moved

### ISSUE THREAD

**Issue by JaredHess** [MegaMek/megamek#1312]
I'm using 45.3.

Because initiative is very important in this game, I'd love to see a small icon or background color change on the unit icon on the battle map or something that shows whether a unit has already moved. 

Yes, I know I can hover over each unit and see a tooltip and whether they moved, but I have to hover over each unit. If you have 12 units on a side, that's going to take a while and then you might forget. 

Some visual indicator already on the battlemap directly ato the unit counter that shows whether a unit has moved is what's needed.

**Comment by NickAragua** [comment]
Units that have already moved will have their names displayed in gray. Additionally, if you look at the unit selection bar on the right, those units that have already moved will not be selectable.

**Comment by JaredHess** [comment]
Perfect. Didn't know that. That works fine.
