### ISSUE TITLE
Make pilot death more obvious in head destruction.

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#132]
In a typical report dealing with head destruction with the "Skin of Teeth" ejection option enabled, pilot death due to head damage isn't very obvious and a little confusing:

ER Medium Laser at Merlin MLN-1B (Princess); needs 6, rolls 6 : hits  (using Rear table) HD
        Merlin MLN-1B (Princess) takes 7 damage to HD.
            Armor destroyed.
             SECTION DESTROYED.
*** Merlin MLN-1B (Princess) DESTROYED by damage! ***
        >Merlin MLN-1B (Princess) suffers catastrophic damage, but the autoeject system was engaged.
    
Merlin MLN-1B (Princess) must make a piloting skill check (landing in clear terrain).
    Needs 6 [4 (ejecting) + 1 (automatic ejection) + 3 (Head Internal Structure Damage) - 2 (landing in clear terrain)], rolls 4 : fails.

        Pilot of MechWarrior Morton Khudiadadzai (Princess) "Morton Khudiadadzai" takes 1 damage.
        Pilot of MechWarrior Morton Khudiadadzai (Princess) "Morton Khudiadadzai" takes 4 damage.            Critical hit on HD. Roll is (5+1) = 6; no effect.

        Pilot of Merlin MLN-1B (Princess) "Morton Khudiadadzai" is already dead, so no damage is dealt!

    SRM 6 ((Clan) Artemis-capable ammo) at Merlin MLN-1B (Princess); needs 8, rolls 6 : misses

It would be easier to understand whether or not the pilot is dead if MegaMek would say the pilot died at his/her sixth damaging hit.

**Comment by arlith** [comment]
I added a new report message and updated the old report message.  Now, the pilot damage report will also list the total number of hits the pilot has.  Additionally, if the damage kills the pilot, the report will indicate that the pilot has been killed by the damage.
