### ISSUE TITLE
Ignore Clan ammo limitations bug/semi-guided missing

### ISSUE THREAD

**Issue by VincentRed** [MegaMek/megamek#1328]
Hello,

since mix-tech is better then clan-tech in 3150 I decided to balance things out by giving clans the semi-guided ammo (IS is using semi-guided ammmo on clan LRM launchers anyway). The problem is, I am unable to do that because "Ignore Clan ammo limitations" option doesn't work. Since I can't attach the rules file I've made screens of all the Game Options Tabs and the missing LRMs on my Vulture Prime. I am using the newest MegaMek  but I remamber having this issue in previous version also. 

P.S.
I've reached out for help on facebook first. The person there was unable to recreate my bug and suggested making this report.

Thank you

![Game opstions 1](https://user-images.githubusercontent.com/49694827/56236231-66068480-6089-11e9-9757-91c186ddc71e.jpg)
![Game opstions 2](https://user-images.githubusercontent.com/49694827/56236232-66068480-6089-11e9-86fb-902783e398aa.jpg)
![Game opstions 3](https://user-images.githubusercontent.com/49694827/56236233-66068480-6089-11e9-82fc-4ed1709e24a9.jpg)
![Game opstions 4 5](https://user-images.githubusercontent.com/49694827/56236234-66068480-6089-11e9-9eac-fa5992ade4f3.jpg)
![Game opstions 4](https://user-images.githubusercontent.com/49694827/56236235-669f1b00-6089-11e9-9f53-14c5f2f0d4ad.jpg)
![Game opstions 5 5](https://user-images.githubusercontent.com/49694827/56236236-669f1b00-6089-11e9-955e-a8b3e0efb2a9.jpg)
![Game opstions 5](https://user-images.githubusercontent.com/49694827/56236237-669f1b00-6089-11e9-8395-e2dbcf00e69b.jpg)
![Game opstions 6](https://user-images.githubusercontent.com/49694827/56236239-6737b180-6089-11e9-90f9-c343f02e2b0f.jpg)
![Game opstions 7](https://user-images.githubusercontent.com/49694827/56236240-6737b180-6089-11e9-8d6a-ef1edd9bafc2.jpg)
![Game opstions 8](https://user-images.githubusercontent.com/49694827/56236241-6737b180-6089-11e9-822d-7247c94cf923.jpg)
![Game opstions 9](https://user-images.githubusercontent.com/49694827/56236242-6737b180-6089-11e9-91b3-53bacf2af3cf.jpg)
![Semi-guided missing](https://user-images.githubusercontent.com/49694827/56236243-6737b180-6089-11e9-82cd-29e86172bdf3.jpg)

**Comment by PhoenixHeart512** [comment]
Issue seems to be resolved in 49.8, checking that box allowed me to select SGLRM ammo on a Timber Wolf, and unchecking the box caused the SGLRM's to disappear from the list again.
