### ISSUE TITLE
ASF Strike attacks can have more than one target if target is a building

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/megamek#133]
Was looking to get the message when trying to attack more than one target, but my targets were all in buildings. When I attacked the second building I received no message and was able to continue the second attack. I tested this a second time using nose, RW, and LW on separate targets and was able to attack 3 buildings with a loss of a single altitude. All hexes were adjacent.

**Comment by arlith** [comment]
`WeaponAttackAction.toHitIsImpossible` was using `Entity te` instead of the passed `Targetable` to check ids for previous weapon attacks.  `te` is a shortcut for the targeted `Entity`, but is null when the target isn't an `Entity`.  `Targetable.getTargetId` is the proper method to use in this case.
