### ISSUE TITLE
Ejected Pilot Allowed Excess Movement

### ISSUE THREAD

**Issue by BairdEC** [MegaMek/megamek#1331]
### Environment
MM 0.45.4 with MHQ 0.45.4
Java (build 1.8.0_211-b12)
Win10

### Description
An ejected mech pilot was able to move through light woods for free.  I do not believe that I've seen infantry units doing this.  The game did complete the move.

![sprint](https://user-images.githubusercontent.com/38081112/56450510-a8270480-62db-11e9-8042-380ea64707b2.PNG)
[sprint.sav.gz](https://github.com/MegaMek/megamek/files/3099695/sprint.sav.gz)

[Steel Recon30261027.zip](https://github.com/MegaMek/megamek/files/3099700/Steel.Recon30261027.zip)
[customs.zip](https://github.com/MegaMek/megamek/files/3099701/customs.zip)

**Comment by BlindGuyNW** [comment]
TW rules do say that (conventional) infantry can move through light woods for a cost of 1 MP.  

Woods: To enter any light woods hex, infantry pay only 1 MP  
(except for mechanized infantry units, which pay 2 MP). Infantry  
pay only 2 MP (mechanized infantry pays 3 MP) to enter any heavy  
woods hex, unless prohibited from entering by the specific unit’s  
movement type; see Movement Cost Table, p. 52).

**Comment by BairdEC** [comment]
Yes, but the pilot was able to move five hexes, four hexes of light woods and one clear hex, in one round.

**Comment by BlindGuyNW** [comment]
I was looking into this a bit. Terrain.java seems to have some specific handling for woods and infantry, but I'm not precisely sure what it does, since the option in question is off in your current game anyhow.

I'll leave it to the regular developers to figure this one out :(

**Comment by wildj79** [comment]
I've been able to replicate this. It would appear that the Mechwarrior in question, Private Thierry Pak, has the Terrain Master (Forest Ranger) SPA (p. 81, Campaign Operations). This SPA allows him to subtract one MP when moving through woods and jungle terrain. In theory, this is working rules as written. So, the question is, does this SPA still apply after a Mechwarrior ejects from his 'Mech?

**Comment by BairdEC** [comment]
While I think the Terrain Master (Forest Ranger) SPA could apply, there should also be a minimum movement cost of 1 to enter a new hex.  Per TW p214, "In general, infantry must pay the same Movement Point cost as other units (as noted on the Movement Cost Table, p52)."  On the same page, TW states:

Woods: To enter any light woods hex, infantry pay only 1 MP
(except for mechanized infantry units, which pay 2 MP). Infantry
pay only 2 MP (mechanized infantry pays 3 MP) to enter any heavy
woods hex, unless prohibited from entering by the specific unit’s
movement type; see Movement Cost Table, p. 52).

Allowing infantry to negate the movement cost through light woods entirely would be abusive, although this seems to be a moot point for the moment.  I gave an infantry unit the Forest Ranger SPA in the MM lobby, and they were not allowed to move through light woods for free.  MM seemed unsure what to do with foot and mechanized units.

![sprint4](https://user-images.githubusercontent.com/38081112/56481396-a2642700-6473-11e9-9cfb-fb80c7f3a79b.PNG)

![sprint5](https://user-images.githubusercontent.com/38081112/56481810-b872e700-6475-11e9-8202-051b8b222698.PNG)

![sprint6](https://user-images.githubusercontent.com/38081112/56481813-ba3caa80-6475-11e9-943e-f667ef81bf60.PNG)
