### ISSUE TITLE
MEch Descriptions of SOme Sort Would be NIce to Have

### ISSUE THREAD

**Issue by BlindGuyNW** [MegaMek/megamek#1333]
Currently, as a totally blind player I have no idea what any of the mechs looks like. The game stats are certainly interesting and vary a lot from design to design, but I miss the fluff that comes with knowing what the units actually are in-universe.

Perhaps a way could be added to include plain-text descriptions of the unit's visual appearance, in one of the "Add Combat Unit," tabs for instance. Someone would need to write descriptions with an eye for detail and decent grammar, ideally.

**Comment by HammerGS** [comment]
That is something we can't do on the account of copy write. CGL is very generous and gives us a lot of latitude. We have a few units with text, but the only way we could get away with it would be to rewrite the descriptions of all the units.  Something well beyond the resources available.

Could you access Sarna and have that useable?

**Comment by BlindGuyNW** [comment]
Yeah, Sarna is at least readable. I'll get in the habit of looking up the pages for any new mechs I run into I guess.

I hadn't thought a text description of a visual appearance would be problematical for copyright, but I don't want to get you guys into trouble.

**Comment by SJuliez** [comment]
Closing this as there is nothing to implement here.
