### ISSUE TITLE
AirMech/WiGE forced to pay 2 additional MP when enters the lower hex

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megamek#1334]
![aaaarr](https://user-images.githubusercontent.com/47907439/56468075-26151800-6462-11e9-95dc-4a58cdb84ac1.png)
### Environment
Ver 0.45.4
Windows 7

### Description
As title says. If the next hex has more level then it is fine and it only uses no more additional MP. But, in MegaMek, if the next hex has lower level then it automatically pays 2 additional MP without any other options. In the rules of page 55, Total Warfare says;

> .. A WiGE entering a hex with a level lower than its current hex automatically descends to maintain the standard one elevation above the underlying terrain, regardless of the difference in levels between the two hexes, at no additional MP expenditure. However, in certain circumstances, a WiGE vehicle may prefer to avoid such a descent. A WiGE vehicle may maintain the same elevation in a new hex (regardless of how many level changes occur in the lower level hex entered) by expending 2 additional MP per hex that it crosses. ..

And, if you put the unit down to zero elevation before move to the next hex it descends and it requires take off again.

So, can you make that keep one elevation with the ground by default and press Go Up on the new hex costs 2 additional MP up to its former absolute elevation, when the AirMech/WiGE have one elevation with the last hex? Else is there any better solution?

**Comment by neoancient** [comment]
Whether you descend to the new elevation or maintain the current (with the +2 MP cost) depends on climb mode. Climb mode defaults to on because that is the expected behavior for most units with respect to bridges and buildings. For WiGEs, airmechs, and glider protomechs it has to be turned off if you want the unit to descend.
