### ISSUE TITLE
Sitrep cOmmand Fails to WOrk COnsistently

### ISSUE THREAD

**Issue by BlindGuyNW** [MegaMek/megamek#1337]
### Environment
0.45.5 Snapshot, built from github and running with MekHQ also built from Github.
Mac for this test, though the behavior is identical on WIndows.
Java version 1.8.0_161, though I've seen identical behavior with Java 12.

### Description
The "sitrep," client command fails to behave consistently. It works if I set up the game locally, with just myself or myself and one bot, but fails with MekHQ's more elaborate setup. The command behaves as though it was not even sent to be processed, and the only thing I can do is ask for its syntax with "#sitrep help."

### Files
Attaching a save game, the player name should be "Caplin's Cannonfodder." Type "#sitrep 1," in the Accessibility WIndow and observe that no entity information is displayed.
[slaughterhouse.sav.gz](https://github.com/MegaMek/megamek/files/3125329/slaughterhouse.sav.gz)

**Comment by BlindGuyNW** [comment]
Attaching a log file, featuring an NPE in Coords.distance. 
[megameklog.txt](https://github.com/MegaMek/megamek/files/3125772/megameklog.txt)

**Comment by beerockxs** [comment]
The sitrep command fails to accout for units with position null, hence the NPE.
