### ISSUE TITLE
Copperhead automatically picks its target if there are multiple Tagged hexes.

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megamek#1351]
### Environment
Ver 0.45.4
Windows 7

### Description

Per errata of Tactical Operation, Arrow IV Homing Missile(that shares the same rule with Copperhead) works...

> On the turn the homing missile arrives, it may attack any unit successfully designated by friendly TAG within 8 hexes of the chosen hex. If there are multiple such units, the firer **choose** which to attack. 

But, in MegaMek, if you put two or more Tagged hexes, the barrage automatically scatters through all eligible hexes that was Tagged. I did it twice but the end result is same. There is no telling I can pick which one to be targetted. It gets the target automatically and I can't do anything for it.

So, can I pick which one is struck by the copperhead? 

Also, can you check if Arrow IV Homing round have the same bug?

![arrrr](https://user-images.githubusercontent.com/47907439/58367943-6879bb00-7f20-11e9-9188-ec257609487d.png)

**Comment by NickAragua** [comment]
Fixed with #1409
