### ISSUE TITLE
Changing Planetary Conditions prior to starting a new game causes a -40C without input

### ISSUE THREAD

**Issue by CrimsonThunderSB** [MegaMek/megamek#1352]
### Environment
Megamek 0.45.4

### Description
In the initial megamek menu, when I attempted change any parameters with the planetary conditions (temperature change, weather conditions, wind speeds, etc.) It will automatically set the temperature to -40C in which I cannot change back unless I start a new game again, and I am trying to create a custom scenario where Infantry is involved, and the bugged temperature to that will make the infantry die instantly on deployment due to extreme temperature.

### Files
N/A as this can be reproduced without a saved game file.

**Comment by wildj79** [comment]
Believe it or not, this is actually working rules as written, see pages 60 and 62 in Tactical Operations. That being said, I think it is reasonable to allow for adjusting the temperature up or down a few degrees.
