### ISSUE TITLE
Battle Armor Heavy Flamer only raise 2 heat per hit

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megamek#1353]
### Environment
Ver 0.45.4
Windows 7

### Description
As title says. Heavy Flamer says it raises heats as much as it can normally damages, but Battle Armor Heavy Flamer only raise 2 heat per hit when I choose to raise the heat.

**Comment by neoancient** [comment]
While working on this I noticed that the ER flamer also does two points in heat mode, but ER flamers are supposed to do half damage in heat mode.

**Comment by neoancient** [comment]
Here's a save game with ER and heavy flamers on a mech and std and heavy BA flamers.
/home/cwspain/git/megamek/megamek/savegames/flamer_test.sav.gz

**Comment by neoancient** [comment]
Save game with an assortment of flamers and targets.
[flamer_test.sav.gz](https://github.com/MegaMek/megamek/files/3267719/flamer_test.sav.gz)

**Comment by binaryspica** [comment]
Well, while viewing at the heat damage code, it seems that only mechs are suffered by heat, not aero and small craft.  Can you review this? 

on [FlamerHeatHandler.java](https://github.com/MegaMek/megamek/blob/master/megamek/src/megamek/common/weapons/FlamerHeatHandler.java) , line 60 says

>  if ((entityTarget instanceof Mech)

So it only checks if the target is mech. It is diffrent with [PlasmaRifleHandler.java](https://github.com/MegaMek/megamek/blob/master/megamek/src/megamek/common/weapons/PlasmaRifleHandler.java), which has 

>         if (!missed
> && ((entityTarget instanceof Mech) || (entityTarget instanceof Aero))) {


So... are both of these needs to be fixed?
