### ISSUE TITLE
Texts in hexes

### ISSUE THREAD

**Issue by SJuliez** [MegaMek/megamek#137]
I changed the way texts are written to hexes to make it more flexible and also more informative depending on the player's choice. Texts for the most frequent terrains can be configured in the Client Settings (Graphics tab).
The font, size, bold-ness and shadow (=outline) color are the same for all texts. The color and the actual text to display are set individually. 
- The text can be left empty 
- The color chooser allows setting an alpha value
- The "Separator" is used (only) when two or more texts fit in one line to separate those
- Setting the separator to something long like "XXXXXXXXX" will effectively make every text use its own line. The separator itself will not be used in that case.

![dialog](https://cloud.githubusercontent.com/assets/17069663/14409320/161bc1d0-ff0f-11e5-8ed0-d99baca97bab.png)

**Comment by SJuliez** [comment]
The standard setting reproduced with the new system:
![texts3](https://cloud.githubusercontent.com/assets/17069663/14409344/49b6de34-ff10-11e5-892f-fa87830950ae.png)

Something different. The official maps use "Light" and "Heavy" for forests. It isn't really necessary but it can be configured. Here the texts for the Level and Depth are empty so only the number is shown.
![texts1](https://cloud.githubusercontent.com/assets/17069663/14409346/623c3fb2-ff10-11e5-924f-59758c159635.png)

**Comment by SJuliez** [comment]
An obvious font choice:
![texts4](https://cloud.githubusercontent.com/assets/17069663/14409352/b9f73ab8-ff10-11e5-9806-8ac638a6d075.png)

Something with an inventive truetype font:
![texts5](https://cloud.githubusercontent.com/assets/17069663/14409355/e9003940-ff10-11e5-87e6-9535b0397e94.png)

**Comment by SJuliez** [comment]
This shows happy little swamps hiding under woods:
![texts2](https://cloud.githubusercontent.com/assets/17069663/14409360/26183a1c-ff11-11e5-9099-c0b24e2710d4.png)

Another idea. Note that the outline is produced by the font itself.
![texts6](https://cloud.githubusercontent.com/assets/17069663/14409366/41d843f0-ff11-11e5-8175-3caa861be1c1.png)

**Comment by arlith** [comment]
What about allowing presets to be saved and loaded?  I think that this is neat, however I feel like it'll get used more if MM comes with a few examples of what you can do, so users have a better idea how to adjust it.  Presets seem like the best way to handle this.

**Comment by BLOODWOLF333** [comment]
Could this be applied to the unit name tags as well?  Like making opponent name tags have a red background to stand out from your own units almost like what happens when a unit is immobile.  The magenta and cyan text is a good improvement already.

**Comment by SimonLandmine** [comment]
I agree with the idea of presets - having a single button that would toggle everything back to the MM default hex info settings could be useful, too - even if it was just a case of being able to switch off the custom information with a key combination.

**Comment by SJuliez** [comment]
It's not gone, just not necessary to have this open as an issue.
