### ISSUE TITLE
Successful TAG designation cause the unit to suffer the penalty of spot for LRM indirect fire on the same turn

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megamek#1388]
### Environment
Ver 0.45.4
Windows 7

### Description
Honestly, I have no idea why it does. It seems that whatever the artillery is onboard or offboard it have nothing to do with this. And both homing and nonhoming rounds are affected by it. Although the save files are only uses Arrow IV, I have seen the same problem on tube artillery as well before that(and that's why I did the test run with this).

On the game, friendly fire option is checked and all units are on your control. I doubt that it would be the reason for this, though.

And... by the result of savegame002 and 003, I suspect that the unit that already fires TAG on the same round are suffered by it. Units that not fired TAG are unaffected by it, if I check it correctly.

### Files
[savegame001.sav.gz](https://github.com/MegaMek/megamek/files/3294332/savegame001.sav.gz)
[savegame002.sav.gz](https://github.com/MegaMek/megamek/files/3294345/savegame002.sav.gz)

[savegame003.sav.gz](https://github.com/MegaMek/megamek/files/3294349/savegame003.sav.gz)
(savegame003 have few turns more after 002) 

![p_](https://user-images.githubusercontent.com/47907439/59566988-57951300-90a2-11e9-8bb3-4e9934861a59.png)

![p_02](https://user-images.githubusercontent.com/47907439/59567071-ad1def80-90a3-11e9-918d-dc242b94485d.png)
![p_03](https://user-images.githubusercontent.com/47907439/59567072-b018e000-90a3-11e9-9823-8ef840fdc0c3.png)

**Comment by binaryspica** [comment]
![p_15](https://user-images.githubusercontent.com/47907439/59845098-7bed3a00-9397-11e9-9c2b-b40d45f6ed61.png)
![p_16](https://user-images.githubusercontent.com/47907439/59845101-7ee82a80-9397-11e9-9607-73795f4359b2.png)



It seems that I was totally get the wrong point. The problem is **TAG itself**, not the artillery or anything else.

Per errata of Total Warfare, **TAG (Target Acquisition Gear) (p. 142)** section says;

> .. Successful TAG designation also spots the target for Indirect LRM Fire (see p.111), but as it occurs before the Weapon Attack Phase, no spotting to-hit modifier is incurred if the unit also fires weapons in the Weapon Attack Phase. This counts as the one target a unit can spot each turn.

But, for now, a unit that fires TAG is automatically considered as spot for LRM indirect fire, and it automatically suffers the penalty. Even if 'Indirect LRM fire always possible' unofficial option is checked, they are suffered by the penalty anyways.


[savegame104.sav.gz](https://github.com/MegaMek/megamek/files/3310086/savegame104.sav.gz)

**Comment by binaryspica** [comment]
For now, [common/actions/WeaponAtackAction.java](https://github.com/MegaMek/megamek/blob/6385ab9ac81c255de7cc23bd6379618889b30697/megamek/src/megamek/common/actions/WeaponAttackAction.java) and [common/actions/PhysicalAttackAction.java](https://github.com/MegaMek/megamek/blob/e35353a84e4bf1a8caf50f8d991031e1599c9f0f/megamek/src/megamek/common/actions/PhysicalAttackAction.java) have the line that actually cause the penalty(line 792 of WeaponAttackAction, and line 215 of PhysicalAttackAction). Both of them are determined by an if command.  [And, common/weapons/TAGHandler.java](https://github.com/MegaMek/megamek/blob/5bd2eb82128c84c9b99c056339aa9666366f5995/megamek/src/megamek/common/weapons/TAGHandler.java) makes the firing unit spot for LRM indirect fire.

If there is a variable on the entity that the unit is spotting but suffers no penalty for it, it would be easy to  implement. 

Such as, first add a flag (like as 'spotWithoutPenalty') on entity, then when TAGHandler makes the firing unit spot for LRM indirect fire it also turns on the flag, after then on Weapon/PhysicalAttackAction also check if the unit have no penalty for spotting before add +1 modifier for attacker is spotting for indirect LRM fire. 

But it seems that there is nothing, and adding a variable can be dangerous for an inexperienced user....

**Comment by neoancient** [comment]
Fixed by #1398
