### ISSUE TITLE
Mouse wheel scrolling and board soft centering

### ISSUE THREAD

**Issue by arlith** [MegaMek/megamek#139]
The soft centering can be broken out of with keyboard-based scrolling, however it doesn't stop if the mouse wheel is used to scroll.  This can lead to contention, where the soft centering moves in one direction, and the user moves in another direction.

**Comment by SJuliez** [comment]
OK got this. A question though: While there I want to disable the automatic arrow key scrolling of the scrollpane (it isn't necessary, works worse than our own scrolling and I can't control the soft centering without an override anyway I think). It's not difficult, but the 
`
scrollpane.getActionMap().put("unitScrollDown", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
            }});`

creates a warning (SerialVersionUID not created). Is that necessary here or just suppress the warning, or if necessary, should I leave it at the automatic 1 or just add some random number?
Thanks in advance.

**Comment by arlith** [comment]
Just allow Eclipse to generate a number.

**Comment by SJuliez** [comment]
Should be done.
