### ISSUE TITLE
[0.45.4] Warnings in terminal

### ISSUE THREAD

**Issue by NooneAtAll** [MegaMek/megamek#1395]
Downloaded 0.45.4 version from [here](https://megamek.org/downloads)  
Extracted to desktop, opened in terminal, launched via the startup file

>./startup

Everything launches and works alright, but terminal gives warning

>Redirecting output to megameklog.txt
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields ([user]/Desktop/megamek-0.45.4/lib/xstream-1.4.10.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Does it work as intended? Is it a problem on my end?

--------

Ubuntu 18.04, updated Ubuntu and java to last versions

**Comment by neoancient** [comment]
That is a warning about deprecated behavior in a third-party library which has not yet been updated to Java 9+ standards. It is outside our control, but harmless. It just means that if they don't fix it, it will stop working with some future version of Java.
