### ISSUE TITLE
FM 3145 RATs

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/megamek#14]
[(3130 on) - FM 3145.zip](https://github.com/MegaMek/megamek/files/105899/3130.on.-.FM.3145.zip)

This is the complete set, adding the missing Battle Armor, Protomek and Aerospace entries. 

There are a couple of known issues:
Clan Medium Battle Armor (Bar)  -  I couldn't get the special "a" character to be recognized by Megamek from a US version of Windows. I tried copying the characters from megamek into notepad, and using the system character translator. Both options produce the desired character in my .txt files, but MM doesn't detect it correctly and lists the entry as bad in the log.

Svartalfa protomech: The Hell's Horses RAT has entries for a Svartalfa (Standard) and 2.  MM only has a Svartalfa Ultra coded, which appears to be identical to the (Standard) model. I used the Ultra for both lines, as I did not have information/tools to produce a faithful "2" variant with its LRM 15s, unspecified number of shots and "less armor".

**Comment by HammerGS** [comment]
I've had similar problems in the past, which is why I use Nopepad++ and make sure the encoding is set to UTF-8.

**Comment by mkerensky** [comment]
I've heard lots of good things about Notepad++,  I'll check that out and use it for future submissions.

**Comment by HammerGS** [comment]
Commit 1cabaca
