### ISSUE TITLE
Infantry "Focus Fire"

### ISSUE THREAD

**Issue by visplaneoverflow** [MegaMek/megamek#140]
Infantry attacks strike like lightning - never in the same spot twice (or so the saying goes).

All infantry attacks, regardless of training, background, equipment, etc involve a kind of disorganized shoot-everywhere-at-once tactic that spreads their firepower into lots of little 2-point damage groupings. This is excellent when crit-seeking, and can be very irritating when used correctly against targets that have had their armour already cracked, but coupled with their short lifespans on the battlefield, troops rarely get a chance to do much more than put a couple of worthless dents in a mech or tank's armour.

I suggest an option to let infantry "focus" their firepower by allowing them to use 5-point damage groupings, which could represent the more competent squad leaders directing fire onto a target either verbally or with tracer rounds for example.

In-game I feel this could be accomplished by a "focus fire" button available in the attack phase, or probably less likely as a toggleable "mode" for infantry weapons. Units could be directed to spray and pray or take better aim as the commander sees fit. Perhaps this behavior would be available only for better-trained units.

I understand this could very well be exceptionally bad for game balance, and it may be a lot of work for units that people don't tend to care much about, but I felt it was worth consideration or discussion nonetheless.

What does everyone think? I'm sympathetic to the poor bloody infantry, but I am amenable to reason :)

**Comment by mkerensky** [comment]
I like it, especially for antimek-trained infantry. Yeah they already get leg and swarm attacks, but they have to live long enough to use those and rarely do, and they're difficult to execute successfully with standard infantry platoons even when in range. 

Perhaps Infantry should be given the 'aimed shot' option instead, as an unofficial rule option?  If you start reading A Time of War, note the huge bonuses for a single character to hit something as large as a mech or tank and imagine a veteran platoon of such marksmen. 

Also remember that the hidden units rules are currently in development, and those significantly enhance the combat power of infantry in a wooded or urban setting.

**Comment by scJazz2** [comment]
Infantry are quite fine. I do not like this option at all.

Rather than new options we need the current rules implemented in full.

**Comment by HammerGS** [comment]
I agree with scJazz on this.  I like to see all the infantry options implemented.

**Comment by neoancient** [comment]
Closing as nobody has shown any interest in implementing this.
