### ISSUE TITLE
Minor bug: Reference of 'Mech Mortar rounds are says it's on TM, not TO

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megamek#1427]
### Environment
Ver 0.45.4
Windows 7

### Description
As the title says. Shaped Charge Mortar Ammo is listed as 324, TO, and the other rounds - Airburst, Anti-personnel, Flare, Semi-Guided, Smoke - are listed as 373, TM. But all of them are must be listed as 373, **TO**, for 'Mech Mortar Ammunition is on 373~375, TO.

I have checked and all Mortar 1 to 8, and both IS and Clans ammo are have the same reference issues.

**Comment by neoancient** [comment]
Fixed by #1493
