### ISSUE TITLE
Bug Unable to move on map edges Intermittent 

### ISSUE THREAD

**Issue by MarcJC** [MegaMek/megamek#1429]
Playing on the new Stable 46.0  

A bug occurs sometimes when a unit (seen it happen with Mech and Areo units)  It does not always occur, and often will fix itself after a unit has spent a turn stuck.  (This behavior may have something to do with the unit turning)

As luck would have it the auto save from a crash happens to have the bug on it.  

Not sure what is causing the error so this is gonna be a bit long to give the exact steps to make sure it comes up.  I would bet most of the steps are irrelevant and you should try the short version first.

Short Version the Jenner IIC on the north edge is stuck.   It can turn or back up but attempting to walk normally or jump refuses to do anything.  

Long version.  Load the attached HQ file (custom file included if needed) Load the autosave from the chase mission with 8 units (4 mech 4 areo)  Replace player to get rid of ghost.  Set retreat edge to south.  

Deploy the planes to hex 0358 facing North, and hex 1828 facing South West.  
Move the Archer directly North.  
The Jenner should come up and be stuck.  

Let me know if you need any extra help detecting the issue.  

I should mention that I had a crash earlier while playing due to the MegaMek window staying on top of the other windows, refusing to respect ALT-TAB, and having to be minimized to get to other windows.  When I declared victory this turn the game froze when trying to load the HQ windows to determine the results to send back to HQ.  I think the windows were stuck under the MegaMek window and could not get focus.  I could not pull up any other windows or minimize MegaMek and could not close the window in any way.  All attempts to close the window were ignored.  
I ended up having to reboot to fix.  On the reload of the saves the window is acting normally.  
I would chalk this up to a weird JAVA issue and not worry too much about it, but if it becomes replicateable or others notice the issue, we will make sure to let you know.  

[autosave.sav.zip](https://github.com/MegaMek/megamek/files/3464557/autosave.sav.zip)

**Comment by neoancient** [comment]
Note that stable 0.46.0 has not been released. This is 0.46.0rc.1, which is the first candidate for the new stable.
I am able to reproduce this reliably in the stable branch but it does not occur in the master branch. I have traced it to a missed commit that left debugging code in place.

**Comment by MarcJC** [comment]
Good catch then.  
You all do great work.
