### ISSUE TITLE
TacOps Sensor Rules option have no effect on the other unit within the same C3 network and only the unit with sensor benefit by it.

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megamek#1433]
### Environment
ver 0.45.4
Windows 7

### Description
As title says. Per errata of Tactical Operations;

> **Active Probes (p.99)**
>_Under "Targeting", at the end of the entry insert the following:_ 
>This bonus applies only to the unit with the Probe, unless that unit is part of a C3 network, in which case the bonus is passed along to other units in that network.

So, it means, if the unit with sensor is the part of a C3 network, and the unit with sensor have the hex/enemy in its range of the sensor, its bonus(reducing terrain penalty) is also applied to the other units in the same C3 network the unit is participated with.

But when I have checked the option, only the unit with the sensor benefits by the option, and the rest of units in the C3 network are unaffected by it.

I have checked it by put the target unit on a light wood and see if is there any modifier, and only if the unit with sensor there is a modifier says '-1(target in/behind woods and attacker has BAP' modifier and the other unit in the same C3 Network never benefits for it. All of them are have the clear line of sight with the others as well.

I don't expect that it would be fixed in the near future, for it seems complicated a bit, though.

**Comment by gsparks3** [comment]
I am not actually sure when this was implemented, but as of version 0.49.20 (or even 0.48, IIRC), this feature has been added.
![image](https://github.com/user-attachments/assets/03ef6ab7-3fb2-4b0a-a37d-4b82a9b60a38)
