### ISSUE TITLE
MegaMek 45.4 "Unit Loading Failures" "Unsupported File Suffix"

### ISSUE THREAD

**Issue by MaxSizeis** [MegaMek/megamek#1435]
Created some custom units in MegamekLab, but accidentally didn't save them with the correct file suffix.  

Launched Megamek and it was helpful and let me know the files weren't proper.

Closed the program.

Deleted the files from the listed path that were incorrect, deleted the unitcache, and restarted, only to have the "Unit Loading Failures" dialogue pop up again with the now deleted units still registered.  Where are these cached, and how can I delete them?

**Comment by NickAragua** [comment]
Check out data/mechfiles folder and subfolders. There's a units.cache file you can delete. It probably won't affect your ability to use the rest of the application.

**Comment by MaxSizeis** [comment]
Deleted units.cache

Problem persists.

The problematic files have also been deleted.  the files that caused the problem no longer exist.

Problem persists.

Where is any additional information about custom units being stored?

**Comment by NickAragua** [comment]
Chances are, the files in question are still somewhere in the data/mechfiles folder or one of the subfolders, otherwise Megamek wouldn't be trying to load them.

**Comment by HammerGS** [comment]
Trying searching the mechfiles folder for .txt extension.

**Comment by neoancient** [comment]
You have to exit the program completely (not just back to the startup splash) to get it to reload or rebuild the unit cache.
