### ISSUE TITLE
Bug: Units stuck under grounded DropShip

### ISSUE THREAD

**Issue by TrailblazerDan** [MegaMek/megamek#1437]
This is an issue with the stable release candidate, 46.0-rc2

When a DropShip starts at altitude 0 in a scenario (or I imagine if you land a DropShip) any ground units adjacent to the ship at the time it turns into a 7-hex "grounded ship" piece will be stuck and unable to move.  Not a terrible problem for human players who can just stay away from grounded ships, but the bot doesn't know not to do this and can easily get its units stuck.

Screenshot and saved game attached...

![DSstuck](https://user-images.githubusercontent.com/19875435/63039178-bbfd0480-be90-11e9-8709-dc0483019ee0.JPG)
[DSstuck.sav.gz](https://github.com/MegaMek/megamek/files/3502365/DSstuck.sav.gz)

**Comment by NickAragua** [comment]
When you say "scenario", do you mean like a scenario defined in a .mms file?

Landing a dropship won't have that problem as any units under a landing dropship get squashed. It also shouldn't be possible to deploy grounded dropships on top of other units during a normal deployment phase.

**Comment by TrailblazerDan** [comment]
Yes, scenario = .mms file.  The issue arose with a scenario using the Set Deployment Altitude to 0 for the Union in the screenshot.  Good to know that this can't happen when landing ships, I guess it's just a problem for scenarios.

**Comment by TrailblazerDan** [comment]
Let me know if it would help to attach the .mms too

**Comment by NickAragua** [comment]
It definitely would, thanks.

**Comment by TrailblazerDan** [comment]
No prob, attached! (Had to change the extension to txt to get it to attach)

[1M04rescuedrop.txt](https://github.com/MegaMek/megamek/files/3502425/1M04rescuedrop.txt)

**Comment by repligator** [comment]
When trying to load the mms, I get the following error
`Error: Couldn't find board file '0Mission4'`
