### ISSUE TITLE
mechset.txt typo

### ISSUE THREAD

**Issue by foij00** [MegaMek/megamek#1439]
0.46.0-rc.2

This line within mechset.txt is in error.  There is a double " at the end of the line.
exact "Morrigu Fire Support Vehicle (Laser)" "vehicles/Morrigu_Laser.png""

**Comment by HammerGS** [comment]
Fixed https://github.com/MegaMek/megamek/commit/1d820473709bd77319b78ae47dd7d3e6fcf5fd48
