### ISSUE TITLE
Overhead Arms Quirk and LOS

### ISSUE THREAD

**Issue by EMaher81** [MegaMek/megamek#1443]
### Environment
What version of MegaMek does your issue apply to?  MegaMek version 0.45.4
Timestamp Sun Mar 24 14:34:30 CDT 2019. Stand alone
What operating system are you using?  Windows 10
What java version are you using?  1.8.0_211

### Description
Describe the issue and provide screenshots ingame if able. Mechs with Overhead Arms must be able to have LOS over level 2 hills and buildings in order to engage targets in accordance with the Overhead Arms Quirk. BattleMech Manual p/ 85
[Overhead2.sav.gz](https://github.com/MegaMek/megamek/files/3513361/Overhead2.sav.gz)

**Comment by HammerGS** [comment]
Overhead arms isn’t coded into Megamek.

**Comment by EMaher81** [comment]
Well that would be why.  Is it on the agenda?

**Comment by HammerGS** [comment]
Depends on Dev interest to code it. Most new features are driven by a Dev having the time and want to code it.

**Comment by EMaher81** [comment]
REF mooted by Quirk revision in Errata, new REF opened
