### ISSUE TITLE
Several XTRO mechs labeled 'Unofficial'

### ISSUE THREAD

**Issue by RexPearce** [MegaMek/megamek#1447]
I noticed the following mech files use "Rules Level:5" in their header, making them fall under the unofficial category.

From what I can see, these are all canon designs with MUL entries. They should probably be changed to "Rules Level:4" instead.

- Starterbook Sword and Dragon/Hatamoto-Chi HTM-27T Daniel.mtf
- Starterbook Sword and Dragon/Hunchback HBK-4G Shakir.mtf
- XTRs/Primitives I/Commando COM-1A.mtf
- XTRs/Primitives I/Helepolis HEP-1H.mtf
- XTRs/Primitives II/BattleAxe BKX-1X.mtf
- XTRs/Primitives II/Gladiator GLD-1R.mtf
- XTRs/Primitives II/Icarus ICR-1X.mtf
- XTRs/Primitives I/Kyudo KY2-D-01.mtf
- XTRs/Primitives I/Shadow Hawk SHD-1R.mtf
- XTRs/Primitives V/Trooper TP-1R.mtf
- XTRs/RetroTech/Centurion CN9-H.mtf
- XTRs/RetroTech/HawkWolf HWK-3F.mtf
- XTRs/RetroTech/Pathfinder PFF-2.mtf

**Comment by HammerGS** [comment]
Fixed https://github.com/MegaMek/megamek/commit/1d820473709bd77319b78ae47dd7d3e6fcf5fd48

**Comment by HammerGS** [comment]
Forget to close this.
