### ISSUE TITLE
Request/Help: Implement Superheavy Command Console

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megamek#1448]
### Environment
0.46.0-rc.2
Windows 7

### Description
As title says. Per 162, IO, superheavy biped or quadruped battlemech can install Command Console, but for now it only able to have default superheavy cockpit.

Since Superheavy Tripod Cockpit already work as the Command Console and it cannot have a separate Command Console, only biped and quadruped are required to have it.

I don't want to prod it, though. 

----

If I have enough time I will try this instead but it seems somewhat complicated. That's why I add help on the topic.

After search through the code, I found that these codes are related with cockpit command console so it seems that we need to edit them in order to actually implement it.

[equipmentmessages.properties](https://github.com/MegaMek/megamek/blob/master/megamek/i18n/megamek/common/equipmentmessages.properties)

Defines property.

[TestMech.java](https://github.com/MegaMek/megamek/blob/9329cc936aa5a0829b29d78c0879763106c4efe9/megamek/src/megamek/common/verifier/TestMech.java)

Defines cockpit's weight.

[Mech.java](https://github.com/MegaMek/megamek/blob/9329cc936aa5a0829b29d78c0879763106c4efe9/megamek/src/megamek/common/Mech.java)

Defines name, type, cost, etc. In this section you can also define the console to be command console for crew composition. Else you need to make the new crew type for them in [CrewType.java](https://github.com/MegaMek/megamek/blob/e35353a84e4bf1a8caf50f8d991031e1599c9f0f/megamek/src/megamek/common/CrewType.java
) but it makes the code too complicated.

[TechConstants.java](https://github.com/MegaMek/megamek/blob/e35353a84e4bf1a8caf50f8d991031e1599c9f0f/megamek/src/megamek/common/TechConstants.java)

Defines its tech level.

[equipmentmessages_ru.properties](https://github.com/MegaMek/megamek/blob/4de5dc6fbafda1eb8747d431acd09563324c0adc/megamek/i18n/megamek/common/equipmentmessages_ru.properties)

Same as equipmentmessages.properties but using russian. I can't read russian so I can't edit it....

-------------------------

But is there any other codes that need to be touched?

Also, how to define its rules level and its available year? Is the tech based on normal Command Console, or Superheavy Cockpit? 

To clarify, Cockpit Command Console is introduced on 2631(Terran Hegemony), extinct on 2850 then recovered on 3030. And Superheavy Battlemech is introduced on 3076(Word of Blake). So I am inclined to match its year with Superheavy Cockpit, because the time when functional Superheavy Battlemech was released a half of a century was already passed after the recovery of Command Console. But what do you think?

**Comment by neoancient** [comment]
It should also be possible to combine a command console with a small cockpit. The question is whether to add new cockpit values for base cockpit + command console or to change the way command consoles are handled to make them a separate piece of equipment that gets installed in an empty slot in the head along with the main cockpit. That's how I probably would have handled it if I had originally written that code, but there may be some other issues I'm not thinking of that favor the current approach.

**Comment by KojimaStorm** [comment]
For what it's worth, you can change Superheavy cockpit components with a simple .mtf edit. See below

Superheavy Cockpit line is replaced with Command Console
![image](https://user-images.githubusercontent.com/38634529/63369399-d41bca80-c34d-11e9-8974-cda0d931972c.png)

As it appears in-lobby, with both commander and pilot
![image](https://user-images.githubusercontent.com/38634529/63369419-e0a02300-c34d-11e9-8806-f941c602d492.png)

And the +2 bonus
![image](https://user-images.githubusercontent.com/38634529/63369481-0e856780-c34e-11e9-9c82-202adaaaf168.png)

It's not necessarily a terminal solution but it does work. You can also edit Superheavy .mtfs to carry Torso-Mounted Cockpits and, assumedly, all other types as well. I believe this also works for gyros. MegaMek is relatively malleable thankfully

**Comment by binaryspica** [comment]
Then, it is better to make both of them at once. And... I am also agreed that it would be better to make the command console as the separated equipment, but perhaps there are some problems we are not aware.

**Comment by binaryspica** [comment]
Thank you for review this. I will close it because the pull request was approved
