### ISSUE TITLE
(Data) RS:SW New Mechs are listed as Level 2 instead of Level 1

### ISSUE THREAD

**Issue by Da-Nuker** [MegaMek/megamek#1454]
Megamek 0.46.0 and 0.47.0

The new 'Mechs found in Record Sheets:Succession Wars folder are sorted as Inner Sphere Total War Tech Level 2 instead of Level 1 Introductory tech, blocking their selection when Tech Level filter is set to Introductory.

List of 'Mechs in RS Succession Wars\
Atlas AS7-A
Javelin JVN-10A
Thunderbolt TDR-5D
Wolverine WVR-6D
Zeus ZEU-6A

The unit summary correctly lists them as Introductory. 
The other added Level 1 'Mechs such as Flea FLE-16 and Panther PNT-9ALAG are correctly listed as Introductory Level 1.

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/9d123a2ae151dd1905139fd39a3ed49cba221402
