### ISSUE TITLE
Aurigan Coalition & Directoriate skins

### ISSUE THREAD

**Issue by MGM175** [MegaMek/megamek#1456]
Is there a possiblity to add Aurigan Coalition and Directoriate skins to MM?

**Comment by HammerGS** [comment]
The person that made the skins has left the project. The skin editor is available from the the start menu, and there are some notes on them in the \Megamek\docs\help\en folder

**Comment by HammerGS** [comment]
@BLOODWOLF333 Will have to decide if he is available to do this.

**Comment by BLOODWOLF333** [comment]
I have never heard of those factions and just had to sarna.net them.  I mainly just did the large and most famous factions because its a lot of tedious repetitive work making the skins so, honestly no i have no intention of adding the numerous little periphery factions.

**Comment by HammerGS** [comment]
Based on the feedback from Bloodwolf closing this.
