### ISSUE TITLE
Mechwarriors are not eject from the mech unless autoeject occurs by ammo explosion 

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megamek#1461]
### Environment
Ver 0.47.0
Windows 7

### Description
As title says. I have seen many cases that mechwarriors are not able to eject or automatically eject on destroyed. For example, destroyed by engine damage won't automatically eject the pilot immediately, and I don't have a chance to do either. 

(Unofficial) Conditional Autoejection option seems to make them actually eject though.

**Comment by NickAragua** [comment]
Advanced Ground Movement -> (Unofficial) Auto abandon unit.
