### ISSUE TITLE
Some of the Elemental battle armours have the claw mounted on the wrong hand

### ISSUE THREAD

**Issue by Tamren** [MegaMek/megamek#1469]
This is a minor issue with no gameplay effects (as far as I can tell) but all versions of the non-Space/Fireproof elemental battle armours have the battle claw and associated criticals mounted on the right hand. The claw should be on the left hand with the anti-personnel mount.

This isn't a problem with meklab itself but I didn't notice it until I used meklab to open the files. I'm using meklab 0.46 from the latest stable release of mekhq.

**Comment by HammerGS** [comment]
Really only impacts constructions and the presentation of data. Will look into it

**Comment by HammerGS** [comment]
Has no impact on play, closing this.
