### ISSUE TITLE
Data: Sprite 3 only has one shot of Medium Chemical Laser round.

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megamek#1472]
### Environment
Ver 0.47.0

### Description
As title says. It should have 30 rounds of Medium Chemical Laser. 

Although it seems the canon data is actually invalid, and its weight will be over if it has 30 rounds of Chemical Lasers.

**Comment by Xeno426** [comment]
It also has 1 more point of leg armor than it should; the file currently has 15 points of leg armor when it should have only 14.

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/1265c6d6665d9e6daadddacd1f4d44b9e0909d0f

The 30 shots of Chem laser ammo now makes the Sprite 3 overweight.  This should be addressed CGL as errata.

**Comment by binaryspica** [comment]
I think that it is what you only can. The data itself is a mess.
