### ISSUE TITLE
Please add a "dark mode" feature

### ISSUE THREAD

**Issue by mjbroekman** [MegaMek/megamek#1479]
### Environment
What version of MegaMek does your issue apply to?  **All**
What operating system are you using?  Windows, Mac, or Linux? **All**
What java version are you using? java version "1.8.0_45"

### Description
Please provide a "dark mode" theme to help it fit in with the commonly available desktop "dark mode" themes for reducing eye strain

**Comment by jdanielp** [comment]
I wonder if this would get us most of the way there: https://github.com/weisJ/darklaf

**Comment by sixlettervariables** [comment]
I attempted to add that to MekHQ and MM, but it unfortunately uses a new version of the JDK than we target (for now).

**Comment by DevCharly** [comment]
You could try FlatLaf (https://github.com/JFormDesigner/FlatLaf), which runs fine with Java 8+

**Comment by sixlettervariables** [comment]
Implemented in #1644
