### ISSUE TITLE
Request: Add option to skip firing turn for mechs/vees that sprint

### ISSUE THREAD

**Issue by Tamren** [MegaMek/megamek#1486]
Since they can't fire any weapons while sprinting there is no point in controlling them during the weapon phase, so the game could skip them like it does for mechs with no melee targets in the physical attack phase.

**Comment by inqistor** [comment]
But can they spot, while sprinting? What are the rules, when there is also gunner in cockpit of sprinting unit?

**Comment by TenkawaBC** [comment]
From BMM:

A ’Mech that sprints may not make any deliberate attacks that
turn. Accidental charges as a result of skidding are still possible, and a
’Mech may still fire weapons to generate heat, though such firing has
no chance of doing damage. Additionally, the ’Mech may not spot
for indirect fire or take any action that would require it to sacrifice
its attack.

So it cannot spot, but for mechs with TSM, you can still shoot to keep your heat up, just not actually hit anything.  So auto-skipping isn't really an option, unless you also add a flag for TSM mechs to not skip, and there could be other scenarios I'm not thinking of.

**Comment by gsparks3** [comment]
It could be made a game option, default off? The TSM mech example seems like the biggest reason why you wouldn't want to skip the weapons phase on a sprinting mech, and if you're using a TSM mech you'd know to keep it off, but others could turn it on to save time. Not 100% perfect, but still useful.

**Comment by HoneySkull** [comment]
Is it possible in MegaMek to fire a weapon at no target in the case of TSM?  Or do you at least need to target a hex or building?

**Comment by TenkawaBC** [comment]
> Is it possible in MegaMek to fire a weapon at no target in the case of TSM? Or do you at least need to target a hex or building?

Currently you must target something to fire weapons. Regardless of whether it is in range or not. So often for Tsm that means targeting a hex, which while sprinting you don't want to allow targeting, but maybe if it only allows hex targeting, or a phantom target hex (e.g.: auto target 99:99, almost guaranteed to be out of range)

**Comment by DM0000** [comment]
Can anything besides Meks sprint?

**Comment by gsparks3** [comment]
Tactical Operations: Advanced Rules page 23 has the rules for Overdrive, which is the vehicle equivalent of Sprinting (to the point of explicitly referring the mech sprinting rules).

**Comment by RaozSpaz** [comment]
Couldn't this just be included within the 'skip invalid units during firing phase' rule option?

**Comment by DM0000** [comment]
Yes in entity. It already has the same check for physical attacks.   Just need to add TSM check to itOn Oct 3, 2024, at 4:31 PM, RaozSpaz ***@***.***> wrote:﻿
Couldn't this just be included within the 'skip invalid units during firing phase' rule option?
