### ISSUE TITLE
IS Small Laser firing at LOS Range

### ISSUE THREAD

**Issue by ObviousTech** [MegaMek/megamek#149]
With LOS Range enabled, units are currently able to fire with IS Small Laser (or any other non-pulse energy weapon).

Small Laser has a long range of 3, which is less than 7 (direct-fire energy weapon minimum to use LOS range), thus is not allowed to fire at LOS range.

**Comment by ObviousTech** [comment]
I suspect MG is because is because MGWeapon is missing the F_DIRECT_FIRE flag

**Comment by ObviousTech** [comment]
For the small laser, the current logic is:
if (PULSE and (ENERGY or DIRECT_FIRE))


It should probably be:
if (DIRECT_FIRE AND (PULSE OR ENERGY))

**Comment by pheonixstorm** [comment]
LOS Range is pg 85

**Comment by ObviousTech** [comment]
F_DIRECT_FIRE appears to have been originally designed for determining if a weapon works with TCs.

F_DIRECT_FIRE currently is also used for determining if a weapon works with LOS Range and Strafing.

- Based on the strafing rules (TW p243) as direct-fire energy weapons, flamers should be able to be used in strafing.  They currently can't in Megamek because they aren't flagged as DIRECT_FIRE.
- MGs and Flamers are not flagged as DIRECT_FIRE, so right now they can fire at LOS Range (but shouldn't be able to according the LOS Range rules).

**Comment by mkerensky** [comment]
AMS has the same issue I think.  Princess fires them at me at LOS range. I've never tried to fire one back.

**Comment by pheonixstorm** [comment]
That would be a different issue entirely. AMS should not be used as a weapon. Ever.

**Comment by HammerGS** [comment]
@pheonixstorm Might want to read TO pg 99-100 Option Rule but still valid.

**Comment by pheonixstorm** [comment]
Didn't think that was actually in MM. Actual option in MM or just a bug that could be turned into that option?

**Comment by arlith** [comment]
Pretty sure there's an option to fire AMS like MGs per the optional rule.

**Comment by scJazz2** [comment]
I think this might have created a bug. Small Lasers are no longer able to fire at Extreme Ranges. Presumably, this effects MGs and Flamers, etc.

**Comment by arlith** [comment]
I cannot reproduce this issue.  If this is in fact a bug, you should create a new ticket for it, and provide steps to reproduce.  A saved game for testing would be useful.
