### ISSUE TITLE
The quirk named 'Ramshackle' have error on the tooltip.

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megamek#1490]
### Environment
Ver 0.47.0

### Description
As title says. I have no idea why it does.

### Files
![r01](https://user-images.githubusercontent.com/47907439/64927409-865b8a80-d845-11e9-808d-8c4a1f183cb5.png)

**Comment by sixlettervariables** [comment]
The code states it hasn't been implemented yet, but I'll update the description.
