### ISSUE TITLE
Request: An unofficial option that allow Leg Attack and Vibro-claw 'melee styled' anti-infantry attack for Heavy and Assault Battle Armor?

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megamek#1491]
### Environment
0.47.0, for now.

### Description
As title says. Although it surely an unofficial option and it must be low on priority, but I think that the option seems interesting. Since there are some canon Heavy/Assault Battle Armor models with claws, I think that give their 'decorations' a reason in a real combat seems not so bad.

Also, allow the attack with any claws, rather than only allows the attack with Vibro-Claws, seems an another option to give the another claws a job. In this case Vibro-Claws are need to cause more damages meanwhile.

I don't think that Heavy and Assaults are able to make anti-mech attacks, so I didn't add that in the request. Although, maybe, Heavy Battle Armor with Magnetic Claws attempt to do that in real Battletech world, but I am not sure about that.

**Comment by neoancient** [comment]
We don't have the time and developer resources to spend on the work this would take to implement, and even if someone were to do so it would be a significant increase in the burden of maintaining the code.

**Comment by binaryspica** [comment]
Alright, I understand your burden for adding such things.
