### ISSUE TITLE
Tractor Combat Vehicle cannot load the infantry/battle armor when it has a trailer.

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megamek#1496]
### Environment
Ver 0.47.0
Windows 7

### Description
As title says. It is not possible to load a conventional infantry/battle armor on the tractor while it has a trailer, although it may start with a team of CI/BA. Both Mechanized Battle Armor and the tractor with troop space are not works.

Trailers are not able to load CI/BA at all as well, unless on the lobby.

**Comment by mkerensky** [comment]
At the time trailers were written last year, the construction code didn't fully support them.  This is one of a couple of known issues involving stacking and 0MP that I had to accept as a result.  It should be something we can fix before too much longer.

**Comment by binaryspica** [comment]
So it was caused because it was in develop right now, rather than a bug. Even for the viewpoint of the bystander, it seems hard to implement.

If you are already aware of the issue, is it better to close the issue?

**Comment by mkerensky** [comment]
Leave this open.  I had forgotten about this until you said something, so this ticket will remind the team that it needs to be fixed.

**Comment by mkerensky** [comment]
This is being worked on and should be available with the next release.

**Comment by binaryspica** [comment]
> This is being worked on and should be available with the next release.

Thanks. Then I will close it for now.

**Comment by HammerGS** [comment]
Please don’t close issues until we either have a commit with the fix. Or the issue is shown invalid or is being withdrawn.

**Comment by SJuliez** [comment]
Can this be closed because of PR #1844 ?

**Comment by binaryspica** [comment]
Perhaps, but I am not sure I can close the issue.

**Comment by Windchild292** [comment]
Fixed in #1844
