### ISSUE TITLE
C3 network determine wrong distance from spotter

### ISSUE THREAD

**Issue by Flankir** [MegaMek/megamek#1505]
C3 spotter in 4 hexes from target (medium range), shooting unit at 12 hexes (extreme range).
But megamek says spotter at long range distance.
There no any units at long distance to target at all.

After moving spotter to close range modifier reduced from long to medium range.
Moving shooter from extreme to long range made C3 stop working at all and it just have long range modifier.
Another target in long distance from spotter also not have C3 effect and shooter have extreme range modifier.

There no ECM (not in range).

**Comment by Flankir** [comment]
[savegame.sav.gz](https://github.com/MegaMek/mekhq/files/3665593/savegame.sav.gz)
There custom mechs so dont know if it helps

**Comment by neoancient** [comment]
It's because you're firing from extreme range, which increases the range from the closest friendly unit by one. See Tactical Operations, p. 85 for the details of the optional extreme range rule.
