### ISSUE TITLE
Problem with dropping bombs after 0.47.0 snapshot

### ISSUE THREAD

**Issue by CrimsonThunderSB** [MegaMek/megamek#1506]
### Environment
0.47.0
Windows 10
Version 8 update 221

### Description

While using an Aerospace fighter, whether I have Cluster Bombs, or HE Bombs, I seem to not be able to bomb a hex regardless whether I am doing an altitude bombing run or a Dive Bombing run.  I don't know if this is deliberately changed or a bug, but it seems I am unable to use bombs as a result.  And this is an issue whether using advanced rules or non-advanced rules.  Snapshot is provided.  This will occur no matter if its a campaign or a regular Megamek game.  

### Files
![Bug in bombing](https://user-images.githubusercontent.com/47725829/65926705-8d95a300-e3c4-11e9-948e-0f402e265826.png)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/3673945/mekhqlog.txt)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/3673946/megameklog.txt)

**Comment by mkerensky** [comment]
This one was my fault.  The issue has been fixed, but I think the fix is in 0.47.1
