### ISSUE TITLE
#1261 was never merged properly?

### ISSUE THREAD

**Issue by blah2355** [MegaMek/megamek#1508]
### Environment
MegaMek v0.46.0

### Description
Supposedly #1259 was fixed in 0.45.4 with #1261. Our play group only recently used the new stable version of MegaMek and were surprised to find that ETT for quads was still not working. Looking at megamek/common/QuadMech.java, the fix was never merged with the master somehow.

**Comment by HammerGS** [comment]
Should be fixed again with https://github.com/MegaMek/megamek/commit/776bc6d954fd57ba6ff280a53c4c8e748acaf6ac
