### ISSUE TITLE
Flamers can't Strafe

### ISSUE THREAD

**Issue by ObviousTech** [MegaMek/megamek#151]
Based on the strafing rules (TW p243), flamers should be able to be used in strafing attacks because they are direct-fire energy weapons.

Flamers currently can't be used in strafing attacks in Megamek because Flamer weapons aren't flagged as F_DIRECT_FIRE and the F_DIRECT_FIRE flag is required for a weapon to be used in a strafing attack.

**Comment by ObviousTech** [comment]
(I didn't actually check if this is actually the case in megamek.  I was looking at places where WeaponType.F_DIRECT_FIRE is used in the code and came across this.)

**Comment by arlith** [comment]
Ironically, there are no ASF with flamers in MM for me to test this with...

**Comment by arlith** [comment]
Added an explicit check for flamers in the strafing code.
