### ISSUE TITLE
Some Protomechs Missing Map Art

### ISSUE THREAD

**Issue by Xeno426** [MegaMek/megamek#1514]
### Environment
0.47.0
Platform Windows 7 6.1 (x86)
Java Version 8 update 221

### Description
All the ultraheavy protomechs with the name "Ultraheavy Protomech" in their name use the default (Roc) map image, since the mechset.txt file has an entry only for the base unit name.
i.e. the mechset.txt has an entry for "Boggart", but the protomech's name in MM is "Boggart Ultraheavy Protomech".

This holds for the Boggart, Svartalfa, and Hobgoblin.

On a related issue, the quad Basilisk has a map image, but mechset.txt lists a unit by the name of "Basilisk (Quad)" while the actual MM file is named "Basilisk ProtoMech (Quad)". It's interesting to note that the Quad Basilisk is the only non-Ultraheavy protomech to have "Protomech" in its name. The entry is also for an "exact" match, so the "Basilisk ProtoMech (Quad) B" would still not get map art.

Curiously, the Sprite is the only Ultraheavy protomech to not have "Ultraheavy Protomech" in its name.

### Files
![boggart map icon](https://user-images.githubusercontent.com/3220418/66727229-5e8b2280-ee03-11e9-92e6-46d67aa6d577.PNG)

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/1265c6d6665d9e6daadddacd1f4d44b9e0909d0f
