### ISSUE TITLE
Corrected 3145 RAT - FWL States

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#1523]
The RATs for the FWL states had multiple mistakes in them. Oriente was a repeat of the Clan Protectorate, while Regulus was a repeat of Andurien. The Atrean Dragoons had a few 'Mechs from the Covenant Guards tables, and certain other 'Mech fixes were done.

See attached for the fixed RATs.

[Free Worlds League and Non-Affiliates.zip](https://github.com/MegaMek/megamek/files/3748587/Free.Worlds.League.and.Non-Affiliates.zip)

**Comment by HammerGS** [comment]
Which books did you pull the RATs from?

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/5bbc6a4082bbefbe7027ec93fa9a4fee68c8a696
