### ISSUE TITLE
Bug: Sprite 3 has too much armor

### ISSUE THREAD

**Issue by Xeno426** [MegaMek/megamek#1534]
### Environment
0.47.0
Platform Windows 7 6.1 (x86)
Java version 1.8.0_231-b11

### Description
As pointed out in issue #1472, the Sprite 3 in WoR supplemental has 65 points of armor: 14 in the legs, 30 in the torso, 6 in each arm, and 9 in the head.
The errata for the Sprite 3 *only* changed the weapons in the arms. These were originally Fusillade launchers, weighing 1,500 kg each for a total of 3,000 kg of mass. The errata changed these to two Medium Chemical Lasers (2,000 kg total) and 30 rounds of ammo (1,000 kg total), and changed nothing else.

The current Sprite 3 in MM has only 1 shot of MCL ammo, which hides its other error; having 66 armor points. The Sprite 3 in MegaMek sits with 15 points of leg armor rather than the 14 it should have. Thus when the ammo count on the Sprite 3 is corrected, it appears overweight by 50 kg.

I've uploaded the image from WoR Supplemental of the Sprite 3's armor layout, along with a fully fixed Sprite 3 that has both the correct armor and the correct amount of ammo.
### Files
![sprite 3 armor](https://user-images.githubusercontent.com/3220418/68305831-f8926380-006d-11ea-96bb-be2f7020e434.PNG)

[Sprite 3 fixed.zip](https://github.com/MegaMek/megamek/files/3814840/Sprite.3.fixed.zip)

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/4ae60b13f71b74533838f570df6469acac6ec2d2
