### ISSUE TITLE
Bug: Fan Council units broken with past updates

### ISSUE THREAD

**Issue by Xeno426** [MegaMek/megamek#1545]
### Environment
0.47.1
Platform Windows 7 6.1 (x86)
Java version 1.8.0_231-b11

### Description
Several of the units unofficial Fan Council units are tagged as "illegal" because they are overweight. This seems to be an issue regarding the special armor not being properly saved and loaded from these files, which were made back on 0.45. 
I've updated the units that were broken and included them in a zip file here. 

Several of the Fan Council units were made using fractional accounting. Since MM does not currently allow for this rule, these units are seen as illegal. I've edited the files to use the <history> tag to alert users that the unit was made using fractional accounting.

The F4W, F4V and F4X are still considered illegal, but that's due to https://github.com/MegaMek/megameklab/issues/372

### Files
[Fan_Council_TRO_3063.zip](https://github.com/MegaMek/megamek/files/3856167/Fan_Council_TRO_3063.zip)

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/4ae60b13f71b74533838f570df6469acac6ec2d2
