### ISSUE TITLE
Client freezes when selecting a unit with a lot of special pilot abilities

### ISSUE THREAD

**Issue by georgiaboy1966** [MegaMek/megamek#1549]
### Environment
0.47.2
Windows 7
Java Runtime Environment
	Path	C:\Program Files\Java\jre1.8.0_231\bin\java.exe
	Version	8.0
	Update	231
	Build	11

In first turn fire phase.
fire mech MAD-4A, finish then prompted for next mech to fire which should be  NSR-4J, shows MAD-4A weapons in pop-up, screen darken slightly and program freezes up. Has happened repeatedly in all versions tries. 0.47.2, 0.47.1, and 0.46. Have checked both mechs in Lab and both appears correct, all tonnage used, passes validation. Have tried increasing memory to 2048. Have tried playing game in Hotseat 2 player insteadd of player vs BOT. Mechs are not customized.

[megameklablog.txt](https://github.com/MegaMek/megamek/files/3869630/megameklablog.txt)
[megameklog.txt](https://github.com/MegaMek/megamek/files/3869631/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/3869632/mekhqlog.txt)

### Files
[Federated Suns CYOA30160807.cpnx.gz](https://github.com/MegaMek/megamek/files/3869616/Federated.Suns.CYOA30160807.cpnx.gz)
[Autosave-0-Federated Suns CYOA-30160807.cpnx.gz](https://github.com/MegaMek/megamek/files/3869617/Autosave-0-Federated.Suns.CYOA-30160807.cpnx.gz)
[Autosave-0-Federated Suns CYOA-30160806.cpnx.gz](https://github.com/MegaMek/megamek/files/3869618/Autosave-0-Federated.Suns.CYOA-30160806.cpnx.gz)
[Autosave-0-Federated Suns CYOA-30160805.cpnx.gz](https://github.com/MegaMek/megamek/files/3869619/Autosave-0-Federated.Suns.CYOA-30160805.cpnx.gz)
[Autosave-0-Federated Suns CYOA-30160804.cpnx.gz](https://github.com/MegaMek/megamek/files/3869620/Autosave-0-Federated.Suns.CYOA-30160804.cpnx.gz)
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/3869622/autosave.sav.gz)

**Comment by neoancient** [comment]
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 35
	at megamek.client.ui.swing.widget.PilotMapSet.setEntity(PilotMapSet.java:261)
	at megamek.client.ui.swing.widget.PilotMapSet.setEntity(PilotMapSet.java:168)
	at megamek.client.ui.swing.unitDisplay.PilotPanel.displayMech(PilotPanel.java:102)
	at megamek.client.ui.swing.unitDisplay.UnitDisplay.displayEntity(UnitDisplay.java:312)
	at megamek.client.ui.swing.FiringDisplay.selectEntity(FiringDisplay.java:742)
	at megamek.client.ui.swing.FiringDisplay.actionPerformed(FiringDisplay.java:2253)
