### ISSUE TITLE
Feature Request: AD Arrow IV ammunition

### ISSUE THREAD

**Issue by Apocal43** [MegaMek/megamek#1552]
As per TacOps, pg. 353. Alternate ammunition type for Arrow IV launchers.

**Comment by Sleet01** [comment]
I was just in the flak artillery code, I think I can get this done fairly quickly.

**Comment by Sleet01** [comment]
In my hubris I forgot that we are out of unused bits in our munitions bitmap, so I have to implement the munitions EnumSet throughout the entirety of the project before work on ADA can start.
