### ISSUE TITLE
Feature Request: BV1 table

### ISSUE THREAD

**Issue by TigerShark** [MegaMek/megamek#1564]
Requesting that the "Alternate Pilot Skill BV Mod" based on my table be replaced by the old BV1 table as an option. The table I proposed is now technically canon since the Piloting BV dropped from +15% to +10%, as of the recent errata.

This will be from the table in the old BattleTech Master Rules book. See attached.

![BV1](https://user-images.githubusercontent.com/951444/70383358-53df9c00-1921-11ea-89b8-02e24342353c.png)

**Comment by SJuliez** [comment]
I think we've removed unofficial alternatives to BV calculations and I don't think it's likely that this would be implemented. Therefore closing it.
