### ISSUE TITLE
Bug (47.2) - Several Trailer Units not tow-able

### ISSUE THREAD

**Issue by Thunderfleece** [MegaMek/megamek#1568]
In Megamek 47.2, several trailer units cannot be towed.
A list of trailers that cannot be towed:
- J-27 Ordnance Transport (Trailer)
- Galaport Ground Trailer (Standard)
- 'Oppie' (HMRV Salvage Bed Trailer) (Standard)
- Ballista Artillery Trailer (Standard)
- Bokkusu Support Trailer (Standard)
- Tenmaku Command Trailer (Standard)
- Gun Trailer (Artillery/AA)
- Gun Trailer (LRM)
- Gun Trailer (Mjolnir)
- Gun Trailer (Siege)
- Gun Trailer (Sniper Cannon)
- Gun Trailer (Stronghold)
- Gun Trailer (Thumper)
- Gun Trailer (Ultra)
- Gun Trailer (Ambush)

Reproduce:
Attempt to tow any of the above with any vehicle with a trailer hitch. The tow option will be greyed out.

**Comment by Thunderfleece** [comment]
Screenshot:

**Left side:** All trailers that cannot be towed. 
**Right side:** All trailers that can be towed.
![Trailer issue screenshot](https://user-images.githubusercontent.com/58954436/70938033-63db3800-2013-11ea-9c2c-88655d4b48e8.png)

**Comment by Thunderfleece** [comment]
Save file of above screenshot.
[TrailerBugReportSave.sav.gz](https://github.com/MegaMek/megamek/files/3969868/TrailerBugReportSave.sav.gz)

**Comment by HammerGS** [comment]
Not sure if this is a data issue or a bug. I've assigned to mkerensky as he did the trailer implementation.

**Comment by neoancient** [comment]
The Galaport and the Oppie listed above are towable if you have a large enough tractor. Those are both support vehicles. This only affects combat vehicle trailers.
