### ISSUE TITLE
Critical hit on armored hip actuator prevents unit from performing kick attacks 0.47.2

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#1569]
I have a custom arena 'mech that has armored hip actuators.  It jumped behind a prone target into an adjacent hex and suffered a hip critical hit from a laser.  The hip was armored so the armor absorbed the hit.  However, the unit wasn't allowed to perform a kick attack even though its hip was still functional due to it being armored.

Also upon the armored hip taking a critical hit, the 'mech was forced to make a PSR:

> Rock Monster RKM-1X (Harold) must make 1 piloting skill roll(s) (hip actuator hit).
> The base target is 5 [4 (Base piloting skill) + 1 (Hardened Armor)].
>     Roll #1, (4 (Base piloting skill) + 1 (Hardened Armor) + 2 (hip actuator hit)); needs 7, rolls 8 : succeeds.

[megameklog.txt](https://github.com/MegaMek/megamek/files/3971314/megameklog.txt)
[gamelog.zip](https://github.com/MegaMek/megamek/files/3971315/gamelog.zip)

I guess it's as if the hip slot armor isn't really working at all.

**Comment by neoancient** [comment]
In round 7, the hit on the leg resulted in two criticals, both of which were rolled against the hip. The first was ignored due to armor and the second damaged the hip.

```Weapons fire for Hachiwara HCA-6P (Princess)
    ER PPC at Rock Monster RKM-1X (Harold); needs 8, rolls 10 : hits  LL
        Rock Monster RKM-1X (Harold) takes 10 damage to LL.
            Reinforced internal structure takes half damage.
             10 Internal Structure remaining.
            Critical hit on LL. Roll is 11; 2 locations.
Critical hit to Hip avoided due to armored component.
            CRITICAL HIT on Hip.
