### ISSUE TITLE
Missing RATs From FM Warden Clans

### ISSUE THREAD

**Issue by xStormforgex** [MegaMek/megamek#158]
Currently FM Warden Clans has only Clan Ghost Bear and Clan Wolf-in-Exile. Attached is the remainder of the RATs for the rest of the Clans
[(3061) - FM Warden Clans.zip](https://github.com/MegaMek/megamek/files/226343/3061.-.FM.Warden.Clans.zip)

**Comment by xStormforgex** [comment]
Forgot this one. Fixed an error I saw in the log with the Aquarius Escort in the A Time of War/Clan/Generic/Aerospace/Small craft.txt RAT.

[Small Craft.txt](https://github.com/MegaMek/megamek/files/226412/Small.Craft.txt)

**Comment by xStormforgex** [comment]
Couple more error fixes on these 2 files. Both had Truck (AC Conversion) and Truck (SRM Conversion) replaced with Flatbed Truck (AC) and Flatbed Truck (SRM)

rat/default.zip/Against The Bot/

[CivilianUnits.txt](https://github.com/MegaMek/megamek/files/227494/CivilianUnits.txt)
[CivilianUnits_CivVeh.txt](https://github.com/MegaMek/megamek/files/227495/CivilianUnits_CivVeh.txt)

**Comment by mkerensky** [comment]
My fault on the AToW RAT.  What did I mess up?

**Comment by HammerGS** [comment]
@mkerensky 

Nothing the Aquarius Escort got a name change recently and I missed changing it in the RAT

**Comment by xStormforgex** [comment]
@mkerensky Noticed it in the MegaMek and MekHQ logs when I was testing a another RAT for errors. So I just did a quick name change and resubmitted it.

**Comment by HammerGS** [comment]
Added in f8bab5688619d7e60696c5893114ccf8148c41d7
