### ISSUE TITLE
Indirect fire penalty occuring on C3 Master TAG again

### ISSUE THREAD

**Issue by MarcJC** [MegaMek/megamek#1580]
Playing 47.2 and noticed when trying to shoot that I have an indirect fire penalty.  I haven't spotted for anything but I did use the C3 Master to TAG a mech.    

I thought this bug had been fixed in a previous version.  

![IDF](https://user-images.githubusercontent.com/20606833/71592869-e7ab1f00-2aff-11ea-85b3-f5d5b7b210fb.jpg)

**Comment by binaryspica** [comment]
It seems the same issue with #1388....

**Comment by MarcJC** [comment]
I didn't have a normal tag on board for this random RAT build.  I only have the Master as a TAG source.  

It does look like the same issue, but I thought that issue got fixed.  Looks like it is back.
