### ISSUE TITLE
0.47.2 : STK-4P's weight is incorrectly set to 75 tons

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#1581]
The weight of the STK-4P should be 85 tons, not 75 tons.

![image](https://user-images.githubusercontent.com/1191378/71623191-b91f6800-2c15-11ea-886b-f67eac48687b.png)

[megameklog.txt](https://github.com/MegaMek/megamek/files/4012775/megameklog.txt)

**Comment by HammerGS** [comment]
This unit is built correctly.  Please see 
http://www.masterunitlist.info/Unit/Details/5120/stalker-stk-4p

and

https://www.sarna.net/wiki/Stalker
