### ISSUE TITLE
Smoke SRMs only filling one hex.

### ISSUE THREAD

**Issue by Apocal43** [MegaMek/megamek#1582]
As per TacOps, page 371, "Smoke Missiles" the SRM6 should be able to cover a 2 hex radius in smoke. In MegaMek, it only fills one hex.

MegaMek 46.0

### Description
Tested with a Kintaro, firing three SRM6s into one hex, all hit and delivered smoke, only one hex of heavy smoke appear where it should have been more.

### Files
[megameklog.txt](https://github.com/MegaMek/megamek/files/4013260/megameklog.txt)
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/4013262/autosave.sav.gz)
Player name is "Apocal"

**Comment by binaryspica** [comment]
Check the errata; it is right that it only pops one hex smoke anyways.

**Comment by neoancient** [comment]
This is from Tactical Operations Errata 3.03, and the latest as of 6 December, 2019.
