### ISSUE TITLE
Map Editor Bug

### ISSUE THREAD

**Issue by Dusaro92** [MegaMek/megamek#1583]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
MegaMek V46
Windows 10x64 Home
Java version 1.8.0_201

### Description
The issue is the 'building:#:#' ID on specific hexs is disappearing. It is the same hexes every time and i have saved the map file under different names and locations, but the outcome remains the same.

### Files
[Truth Base 3.zip](https://github.com/MegaMek/megamek/files/4013555/Truth.Base.3.zip)

**Comment by NickAragua** [comment]
Could you describe in a little more detail what you're doing? e.g. what building you're placing, in what hex, etc.

**Comment by Windchild292** [comment]
@NickAragua I think this might be the same as #1209, but I'm not certain. Will discuss with the author (I suggested they make this ticket, but have easier ways to reach them than through Discord)

**Comment by NickAragua** [comment]
Looks similar. Not sure when I'll be able to look into it.

**Comment by Windchild292** [comment]
I'll be taking a look as part of the continuation of testing for #1613, although I'm not sure that PR will fix this.

**Comment by Windchild292** [comment]
I'm now certain it is the same issue, and it exists in the current develop. The issue appears to be that the building is illegal, because of how the exits are done, so it doesn't save properly. Changing around the exits fixes these issues.

**Comment by SJuliez** [comment]
Bridge:0 needs to marked as invalid in the Map Editor.
Bridge/building validity checks need to be more complete and reflect what the board loader will reject (exits / mixed building types)
(To be complete, I believe boards are fortunately saved properly, but loaded incorrectly)
