### ISSUE TITLE
MG Array BV C/IS Rules Issue

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#1586]
From a Discord message
For machine gun arrays, it looks like rather than correctly apply 0.67x(total BV of linked MGs), it always assumes the array is linking the max number of MGs it can link. Effectively, it carries a static BV, instead of scaling with how many MGs it links. I checked this across a number of canon builds for both Clan and IS

### Environment
What version of MegaMek does your issue apply to?  0.46.0

### Description
As above

Looks like their is also a difference between Clan and IS arrays.
TM pg 317 - has IS as BV is the total BV of all weapons in a machine gun array multiplied
by 0.67.

TO pg 385 - has clan as Machine Gun Array: BV is the BV of all the weapons on the array (but not the ammunition) x 0.1.

I've got a question into the rules team to confirm the two should be so different and will update this when I find out.

**Comment by neoancient** [comment]
Any update on this?

**Comment by HammerGS** [comment]
Nothing yet
