### ISSUE TITLE
bw_atmospheric.tileset

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#159]
Modified HQ_atmospheric tileset using a lot of the images that are already included with minor modifications and some new ones(snow theme).  All saved into a separate folder so as not to overwrite anyone else's work.  Can now type "grass, jungle, snow, lunar, mars, and volcano" into the theme box.  Does not include the crate images and lines in the tileset from my post on the bg. forums (I dont think anybody else cares).  This is the new "include..." format.  Reversed the brightness due to elevation just because I find that to be more realistic.

[BLOODWOLFimages.zip](https://github.com/MegaMek/megamek/files/251493/BLOODWOLFimages.zip)

*EDIT 5/5/2016: Made swamp images transparent 75% for when mud and swamp share the same hex.

[blank] / desert
![desert](https://cloud.githubusercontent.com/assets/16950832/15033435/53f7b5d4-1230-11e6-8771-d8af46c9db8e.png)

Beige_plains  | Sands | Ultra_Rough
----------------- | -------- | ----------
![beige_sinkhole_6](https://cloud.githubusercontent.com/assets/16950832/15033441/7f893380-1230-11e6-8896-39ed5bb73d97.png) | ![sand_-3](https://cloud.githubusercontent.com/assets/16950832/15033475/b92f228e-1230-11e6-8be0-a5c6b0fe1ab0.png) | ![ultra_rough](https://cloud.githubusercontent.com/assets/16950832/15033490/d0622172-1230-11e6-84fa-98be67c4da62.png)
![beige_sinkhole_5](https://cloud.githubusercontent.com/assets/16950832/15033442/84f2bea4-1230-11e6-9d5c-040ae4e9e3b7.png) | ![sand_-2](https://cloud.githubusercontent.com/assets/16950832/15033476/bea6005c-1230-11e6-906d-a5315a3216ac.png) | 
![beige_sinkhole_4](https://cloud.githubusercontent.com/assets/16950832/15033448/8bfb549a-1230-11e6-8881-c8bdb5e044ec.png) | ![sand_-1](https://cloud.githubusercontent.com/assets/16950832/15033479/c0f3882a-1230-11e6-8216-da911e3c4e2c.png)
![beige_sinkhole_3](https://cloud.githubusercontent.com/assets/16950832/15033452/9135028a-1230-11e6-88ae-a9571ee6a586.png) | ![sand_0](https://cloud.githubusercontent.com/assets/16950832/15033481/c2e5b90a-1230-11e6-834e-dbc919b5f46b.png)
![beige_sinkhole_2](https://cloud.githubusercontent.com/assets/16950832/15033455/93498654-1230-11e6-9dc4-491f2096dd05.png) | ![sand_1](https://cloud.githubusercontent.com/assets/16950832/15033483/c4aa6722-1230-11e6-82be-aa6699ae934c.png)
![beige_sinkhole_1](https://cloud.githubusercontent.com/assets/16950832/15033456/9646a3aa-1230-11e6-8872-1f93b023af94.png) | ![sand_2](https://cloud.githubusercontent.com/assets/16950832/15033484/c683f900-1230-11e6-8b72-53b2d8363aca.png)
![beige_plains_0](https://cloud.githubusercontent.com/assets/16950832/15033458/9a77ba72-1230-11e6-9438-65d85281709e.png) | ![sand_3](https://cloud.githubusercontent.com/assets/16950832/15033486/c84e6e0a-1230-11e6-81ff-6a9091119bc7.png)
![beige_plains_1](https://cloud.githubusercontent.com/assets/16950832/15033459/9c091066-1230-11e6-9aa3-a6f0fddb4476.png) |
![beige_plains_2](https://cloud.githubusercontent.com/assets/16950832/15033461/9d7c9206-1230-11e6-9d75-b2e502631c4c.png) |
![beige_plains_3](https://cloud.githubusercontent.com/assets/16950832/15033463/9f36ddf4-1230-11e6-9c4b-0b3a4d2dfbd1.png) |
![beige_plains_4](https://cloud.githubusercontent.com/assets/16950832/15033465/a152d44e-1230-11e6-9d7d-6de5d16b7c7f.png) |
![beige_plains_5](https://cloud.githubusercontent.com/assets/16950832/15033467/a691ac3c-1230-11e6-8629-182bccb7b3ae.png) |
![beige_plains_6](https://cloud.githubusercontent.com/assets/16950832/15033469/a875194e-1230-11e6-9c92-9b33b4085eb8.png) |

**Comment by BLOODWOLF333** [comment]
Grass
![grass](https://cloud.githubusercontent.com/assets/16950832/15033830/000af63e-1235-11e6-83cb-112e2473ed74.png)

Grass | Ultra_Heavy_Woods | Water | Swamp
------- | -------------------------- | -------- | ---------
![grass_sinkhole_6](https://cloud.githubusercontent.com/assets/16950832/15033838/1096a73c-1235-11e6-8af3-1616be3ea0cf.gif) | 
![uhf0](https://cloud.githubusercontent.com/assets/16950832/15033845/1c6109a4-1235-11e6-9c1c-c09e9aa79506.png) | 
![blue_water_4](https://cloud.githubusercontent.com/assets/16950832/15033854/23f36c48-1235-11e6-8424-c76ea4e83818.png) | 
![swamp_0](https://cloud.githubusercontent.com/assets/16950832/15033857/29bda058-1235-11e6-8aee-b78e44ca0f71.png)

**Comment by BLOODWOLF333** [comment]
Jungle
![jungle](https://cloud.githubusercontent.com/assets/16950832/15034143/27858456-1238-11e6-9fe1-93edfe7b8c8f.png)

Jungle_plains | Mud
----------------- | ------
![jungle_sinkhole_6](https://cloud.githubusercontent.com/assets/16950832/15034156/46c99aa0-1238-11e6-8be7-507bcd418f0c.png) | ![mud_-3](https://cloud.githubusercontent.com/assets/16950832/15034160/51770910-1238-11e6-90cc-9a9a108165f1.gif)

**Comment by BLOODWOLF333** [comment]
Snow
![snow](https://cloud.githubusercontent.com/assets/16950832/15034399/fc7387ec-123a-11e6-90c3-85b340784d3b.png)

Snow_plains | Light_woods | Heavy_woods | Ice
---------------- | ---------------- | ------------------ | ----
![snow_-6](https://cloud.githubusercontent.com/assets/16950832/15034419/2bd8b8fe-123b-11e6-903b-32cfd4b983fd.gif) | ![snow_l_woods_0](https://cloud.githubusercontent.com/assets/16950832/15034421/32a697f0-123b-11e6-8f82-df1fb2a2edac.png) | ![snow_h_woods_0](https://cloud.githubusercontent.com/assets/16950832/15034426/3d5b33ae-123b-11e6-972b-579f9b87abdf.png) | ![ice_0](https://cloud.githubusercontent.com/assets/16950832/15034431/474db5da-123b-11e6-9c08-4d57a802905a.png)

**Comment by BLOODWOLF333** [comment]
Images not included

Light_crate | Medium_crate | Heavy_crate | Hardened_crate | Target | Flare
-------------- | ------------------ | ---------------- | --------------------- | -------- | ------
![light_crate_0](https://cloud.githubusercontent.com/assets/16950832/15034634/467173d4-123d-11e6-91a4-5306b9a64253.gif) | ![medium_crate_0](https://cloud.githubusercontent.com/assets/16950832/15034638/4cbb4c92-123d-11e6-8b80-0654c89bd556.gif) | ![heavy_crate_0](https://cloud.githubusercontent.com/assets/16950832/15034643/5562319e-123d-11e6-8b01-ded6b056d677.gif) | ![hardened_crate_0](https://cloud.githubusercontent.com/assets/16950832/15034648/5c8b162a-123d-11e6-9ddd-e1aa19358100.gif) | ![attack_target](https://cloud.githubusercontent.com/assets/16950832/15034651/6606391e-123d-11e6-8761-709aa31ef505.png) | ![flare](https://cloud.githubusercontent.com/assets/16950832/15034657/7272e49a-123d-11e6-96c4-7dc7f7e24df6.png)

**Comment by BLOODWOLF333** [comment]
Was looking at this thread http://megamek.info/forums/index.php?topic=2443.msg16190;boardseen#new and attempted it with my tileset and realized I forgot to include base * "" "" "bloodwolf/hq_boring/beige_plains_0.png".  So, here is the updated tileset file.

[bw_atmospheric.zip](https://github.com/MegaMek/megamek/files/370383/bw_atmospheric.zip)

**Comment by BLOODWOLF333** [comment]
Were the new fire images updated as well that I emailed to you?
![fire_0](https://cloud.githubusercontent.com/assets/16950832/17081985/03bbec02-5132-11e6-8203-7ee33d2b57ae.png)
![fire_1](https://cloud.githubusercontent.com/assets/16950832/17081986/05b37174-5132-11e6-989e-838f1dc3cf04.png)
![fire_2](https://cloud.githubusercontent.com/assets/16950832/17081987/075c066c-5132-11e6-9c9f-d883343ab41e.png)
[Fire.zip](https://github.com/MegaMek/megamek/files/380134/Fire.zip)

**Comment by arlith** [comment]
If they weren't in a ticket, then they weren't updated
