### ISSUE TITLE
Fa Shih unable to lay mines

### ISSUE THREAD

**Issue by Flibjib** [MegaMek/megamek#1590]
Noticed while playing that I can't get the Fa Shih to deploy mines at all, tried both the Mac and Windows versions of 47.2

### Environment
This is with the bundled MekHQ version of the app

### Description
Step 1. Spawn a Fa Shih
Step 2. Attempt to lay mine during movement phase, click hex, click done, nada.

### Files
[FaShihMines.sav.gz](https://github.com/MegaMek/megamek/files/4031141/FaShihMines.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/4031142/megameklog.txt)

**Comment by neoancient** [comment]
After some digging through the code I found that it works if you click "Jump" before "Lay Mine" since BA can only lay mines when using jump or VTOL movement. I'm going to look at ways to make that easier and/or more obvious to the user.
