### ISSUE TITLE
RAT unit name fixes (47.2)

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#1597]
Corrected multiple RATs to eliminate naming errors.
If needed, the proper location for each RAT has been added in parentheses.

[Coyote Secondline ProtoMechs (Reaving).txt](https://github.com/MegaMek/megamek/files/4050170/Coyote.Secondline.ProtoMechs.Reaving.txt)
[LMs A (Oriente - 3145).txt](https://github.com/MegaMek/megamek/files/4050171/LMs.A.Oriente.-.3145.txt)
[LMs B (Oriente - 3145).txt](https://github.com/MegaMek/megamek/files/4050172/LMs.B.Oriente.-.3145.txt)
[LMs C (Oriente - 3145).txt](https://github.com/MegaMek/megamek/files/4050173/LMs.C.Oriente.-.3145.txt)
[Protomech Front Line (Horses - 3145).txt](https://github.com/MegaMek/megamek/files/4050174/Protomech.Front.Line.Horses.-.3145.txt)
[Protomech Keshik (Horses - 3145).txt](https://github.com/MegaMek/megamek/files/4050175/Protomech.Keshik.Horses.-.3145.txt)
[Protomech Second Line (Horses - 3145).txt](https://github.com/MegaMek/megamek/files/4050176/Protomech.Second.Line.Horses.-.3145.txt)
[Regulan Fiefs AMs C (3145).txt](https://github.com/MegaMek/megamek/files/4050177/Regulan.Fiefs.AMs.C.3145.txt)
[Regulan Fiefs AMs D (3145).txt](https://github.com/MegaMek/megamek/files/4050178/Regulan.Fiefs.AMs.D.3145.txt)
[Regulan Fiefs AMs F (3145).txt](https://github.com/MegaMek/megamek/files/4050179/Regulan.Fiefs.AMs.F.3145.txt)
[Society Command ProtoMechs (Reaving).txt](https://github.com/MegaMek/megamek/files/4050180/Society.Command.ProtoMechs.Reaving.txt)
[Society Standard ProtoMechs (Reaving).txt](https://github.com/MegaMek/megamek/files/4050181/Society.Standard.ProtoMechs.Reaving.txt)
[3085 Clan Hells Horses Protomech Front Line.txt](https://github.com/MegaMek/megamek/files/4050182/3085.Clan.Hells.Horses.Protomech.Front.Line.txt)
[3085 Clan Hells Horses Protomech Keshik.txt](https://github.com/MegaMek/megamek/files/4050183/3085.Clan.Hells.Horses.Protomech.Keshik.txt)
[Blood Spirit Frontline ProtoMechs (Reaving).txt](https://github.com/MegaMek/megamek/files/4050184/Blood.Spirit.Frontline.ProtoMechs.Reaving.txt)
[Blood Spirit Keshik ProtoMechs (Reaving).txt](https://github.com/MegaMek/megamek/files/4050185/Blood.Spirit.Keshik.ProtoMechs.Reaving.txt)

**Comment by NickAragua** [comment]
This is appreciated, but do you think you could do a pull request with these changes?

**Comment by AlphaSled** [comment]
Sure thing, sorry, not entire familiar with how github works. I'll repost this over there.

**Comment by Windchild292** [comment]
You can put me on this, I'll fix it between classes.
