### ISSUE TITLE
Quirk Fix Request: Narrow/Low Profile (47.2)

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#1602]
Currently, Narrow/Low profile provides a blanket +1 to-hit modifier for all attacks targeting the 'Mech with the quirk.

However, the Battletech Manual page 85 states the following:
"If the Margin of Success for a weapon attack made against a narrow/low profile ’Mech is 0 or 1, the hit is considered a glancing blow. For example, if you need to roll a 9 or better to hit the target,
a result of 10 would be a glancing blow.

A glancing blow inflicts half the normal damage (rounded down); for weapons that roll on the Cluster Hits Table, instead apply a –4 modifier to the Cluster roll result (with a minimum result of 2). Additionally, apply a –2 modifier when rolling on the Determining Critical Hits Table any time a glancing blow yields the possibility of a critical hit; if using the Advanced Determining Critical Hits rule (see p. 85, TO), apply a –4 modifier instead.

This quirk has no effect versus non-weapon attacks, such as falls or physical attacks. It also has no effect versus all-or-nothing weapon attacks, such as Streak missile launchers. If using the Linking Weapons rule (see p. 85, TO), the entire linked group is considered a glancing blow.

Damage Reduction: If also using the Glancing Blow rule (see p. 80, TO), the effects stack (1/4 damage is dealt). Any subtractive damage reduction effects (such as ferro-lamellor armor) are applied after all other damage reduction effects."

**Comment by binaryspica** [comment]
It does not means it overrides Narrow/Low Profile on Strategic Operations, isn't?

**Comment by AlphaSled** [comment]
It probably does override the Strategic Ops quirk description, since it came out in 2017 versus 2009.
Also, per here: https://bg.battletech.com/forums/index.php?topic=33847.msg789423#msg789423 , the Sarath should get the Narrow/Low Profile quirk.

**Comment by HammerGS** [comment]
Yes, BMM has errata'd the Narrow/Low Profile Quirk.

**Comment by binaryspica** [comment]
Then, I suggest to make an option to leave its old functions when the request would be resolved. At least SO have no direct errata on Narrow/Low Profile.

**Comment by neoancient** [comment]
The quirk descriptions in the BattleMech manual supercede Strategic Operations.
