### ISSUE TITLE
Kaji's 30x17 Maps

### ISSUE THREAD

**Issue by AskAgain** [MegaMek/megamek#1615]
Not so much an issue as a submission of some 30x17 maps I made a while ago.

[30x17 Maps.zip](https://github.com/MegaMek/megamek/files/4113007/30x17.Maps.zip)

**Comment by HammerGS** [comment]
Added in https://github.com/MegaMek/megamek/commit/4ae60b13f71b74533838f570df6469acac6ec2d2
