### ISSUE TITLE
RFE: Dirt and Gravel Roads (TacOps p51)

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#1619]
Would it be possible to implement Dirt and Gravel roads (as per TacOps p51)?

At present Road = 2 provides an alternative visual for the road (with boundary shrubs).
Road = 3 (or greater) provide a different alternative visual on the Saxarba tilesets (these appear to be tyre-marks) but do not appear to be supported on other tilesets.

To avoid breaking existing maps, would recommend that unreserved values be used to indicate dirt or gravel roads. Appreciate this would also require amendments to the tilesets with the addition of new sprites for the new road surface types.

**Comment by neoancient** [comment]
I'll be working on that part of the code some time in the next couple months when I implement rail support vehicle movement. I'll try to remember to do this also while I'm in there.

**Comment by SimonLandmine** [comment]
Thanks for letting me know! (Looking forward to rail movement, too - I have plans for shunting yards.) Thanks for all the hard work!

**Comment by SimonLandmine** [comment]
Sorry, hit wrong button.

**Comment by SimonLandmine** [comment]
Given the creation of the `foliage_elev` value to handle level 1 foliage, I wonder if one solution for this might be a secondary `road_type` value, where the default is 'paved' (as a null or 0 value?), with values of 1 for gravel and 2 for dirt. That might avoid problems with the fact that `road:2` is already assigned to a graphical representation in some tilesets.

**Comment by SJuliez** [comment]
Ideally, the road:XX number should not be a graphical distinction, so this number should be used to distinguish normal from gravel roads. To have different graphics, one can add road_fluff. I believe this even works for the alley type roads, but until I convert all the existing maps I won't force this change. So much to do, so little time.

**Comment by SimonLandmine** [comment]
Fully agree about what the `road:XX` number _should_ do. Would require an update to a number of existing maps, though - would they need manually updating, or would I be able to do a FIND `road:2` and replace with `road:1 road_fluff:x` (as appropriate)?

**Comment by SJuliez** [comment]
Ok thanks! I will have to check if I really added the alley roads to road_fluff or if I only imagined I did.

**Comment by SimonLandmine** [comment]
Are the "alley roads" the ones with the 'lined with bushes' effect, currently coded as `road:2`?

**Comment by stonewall072** [comment]
[Gravel and Alternate Dirt Roads.zip](https://github.com/user-attachments/files/18049131/Gravel.and.Alternate.Dirt.Roads.zip)
