### ISSUE TITLE
"The armor panel is null." warning during deployment phase

### ISSUE THREAD

**Issue by arlith** [MegaMek/megamek#162]
This looks to have been introduced in 32d7af3c, where mouse 3 for toggling minimap/unitdisplay was added.

The problem is with ClientGUI.setDisplayVisible(boolean visible).  Code was added to check to see if a unit was selected, and if not it selects one, otherwise setting the UnitDisplay visibility to true could cause issues.

When DeploymentDisplay.gameTurnChange gets called for the first time, and ClientGUI.setDisplayVisible is called, this new code will call UnitDisplay.selectEntity, but since ClientGUI.mechW has never been visible yet, it has never called ArmorPanel.addNotify(), so the DisplayMapSets are never get initialized, and this warning is printed.

**Comment by beerockxs** [comment]
This has been around much longer.

**Comment by arlith** [comment]
The warning has been around, and it may have gotten called periodically, but the code added in 32d7af3 now triggers it at the start of every new game.  I've got a fix for it, but I won't be able to get it committed until later today.

**Comment by arlith** [comment]
Looks like I accidentally committed this to the skinEditor branch, so then I cherry-picked it into master.

 Essentially, the problem boils down to `ArmorPanel.displayEntity` being called before the frame that is holding the `UnitDisplay` has its visibility set to true.

In the case of `ClientGUI.setDisplay`, I adjusted the code so that it sets an `Entity` to display, but doesn't call `UnitDisplay.displayEntity` until after the visibility of the mech window is set.
