### ISSUE TITLE
Barracuda missiles suffering from small craft to-hit penalty 0.47.2

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#1625]
![image](https://user-images.githubusercontent.com/18338059/73508253-5ef6fb80-43a9-11ea-9f4b-15c2bdc05547.png)

I'm not sure this is happening to all capital missiles as I haven't tested them.  Also, these are standard Barracuda missiles, just mis-labeled by MegaMek.  Game log file attached.

[megameklog.txt](https://github.com/MegaMek/megamek/files/4137339/megameklog.txt)

**Comment by mkerensky** [comment]
I think this issue has been fixed in the next release.  Non-teleoperated capital missile bays were being created as teleoperated bays.

**Comment by BLR-IIC** [comment]
I just played a game with capital missiles and the issue seems to be fixed.
