### ISSUE TITLE
RFE: Option to Disable the Ding Sounds in the Lobby

### ISSUE THREAD

**Issue by Windchild292** [MegaMek/megamek#1627]
This was requested on Discord, and would be a nice thing to have.

**Comment by neoancient** [comment]
Do you mean disable just in the lounge and have them active during a game, or mute the sound altogether? The latter is an option on the main tab of the client settings (from the view menu).

**Comment by Windchild292** [comment]
The latter. As a follow up question, is there a way to automatically have that selected when loading from MekHQ?

**Comment by neoancient** [comment]
The client settings are saved when exiting and should carry over between sessions, regardless of how it is started.

**Comment by Windchild292** [comment]
I'll close this, and will inform the person of that case.
