### ISSUE TITLE
Mouse Wheel doesn't change Terrain Settings.

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#1628]
The tool tip says I can wheel to change terrain types, While the image in the bottom right changes. Everything in the Terrain Settings box stays the same. 

Effectively you can say you're using heavy woods. Something intermittently causes it to work and other times it defaults back to the base terrain.

![image](https://user-images.githubusercontent.com/13752452/73600790-a64ccb80-4512-11ea-8d8a-d0bfd6046b1b.png)

### Environment
What version of MegaMek does your issue apply to?  47.4
What operating system are you using?  Windows

### Description
Describe the issue and provide screenshots ingame if able.
Provide the rulebook, page number, and text if you feel like this is a rules issue.
And provide the steps you have taken to reproduce the issue in the saved game if applicable.
(Delete the above lines)

### Files
Provide a saved game of when the issue was found.  If possible try to save the game during the phase before the issue occurs so the 
developers can step through the code and find exactly what it is that is breaking in the code.
Provide the megameklog.txt file for any NPE's or errors that MegaMek might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual megameklog.txt file
And provide your playername so that they can load the saved game.
(Delete the above lines)

**Comment by SJuliez** [comment]
Do you mean the selection box (that says "Arms")? This (intentionally) only changes when you click one of the terrains in the terrain list below it.

So if you select heavy woods by wheeling the button and then click on "Heavy Woods" in the terrain list beside the hex image, then the selection box above it will update to "Woods", "2".
