### ISSUE TITLE
Suggestion: A different beep when you're up

### ISSUE THREAD

**Issue by EMaher81** [MegaMek/megamek#1631]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
What version of MegaMek does your issue apply to?  0.47.2
What operating system are you using?  Windows
What java version are you using?  Current

### Description
Suggestion to add a "ready up" chime when your turn comes around to move, fire, click Done, etc.

**Comment by kuronekochomusuke** [comment]
implemented in #4151
