### ISSUE TITLE
Map Editor window title does not update reliably

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#1635]
v47.3 but also earlier versions.

Window title starts off "MegaMek Board Editor : Unnamed". When a board is saved using [Save As], the window title changes to give the location/name of the newly saved board.
When another board is loaded, the window title does not update, continuing to show the name/location of the previously saved board. Clicking [Save] will overwrite the newly loaded board - which is not the one whose name is in the window title. This can result in accidentally overwriting e.g. boards from standard map sets.

It appears that the Map Editor window title might only update on a [Save As] action, but not on a [Load] action.

**Comment by Windchild292** [comment]
If by [Load] you mean [Open] for the action names, I haven't been able to recreate this in 0.47.3 nor in my latest development branch.

**Comment by SimonLandmine** [comment]
[Load] is the button on the Map Editor interface that triggers the 'load'/'import'/'open' process. I'll work through again and document the steps and outcomes properly.

**Comment by Windchild292** [comment]
I forgot to update saying that I figured out which button you are using, and I'm still not having any issues.
