### ISSUE TITLE
Map Editor 47.3 - usability comment, not error

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#1638]
Map editor 47.3 requires a lot of vertical real estate - I'm running a 27" monitor, but I would still have to choose between being able to view the top three terrain types (Woods/Jungle/Water) and being able to click on the Resize/Save/Image/Validate buttons without scrolling the selection bar. Not a major issue, but a slight usability ease thing (especially as the scrollwheel is less available for moving the bar up and down, given the number of variables it now controls!)

On my 15.4" laptop monitor, the issue is even more challenging (see illustration below) - I can either see the bar from the terrain buttons to the hex elevation buttons, or the (excellent) brush size buttons to the detail area. (Being familiar with the options, I'd then use the detail area, which is very clear and useful, but it might increase the learning curve for new users.)

I'm guessing that a 'compact' option for the gridbag display to enable smaller buttons would require a fair amount of rebuilding, and possibly resizing of the graphics elements, for a possibly  limited return.

Anyway, also want to say thank you to everyone who's worked on the Map Editor!

![MapEditor-15 4inLaptop](https://user-images.githubusercontent.com/26851644/73612184-50932480-45e1-11ea-9aa7-cccb196213c0.png)

**Comment by Windchild292** [comment]
I've got an idea for this, but want to get the core systems fixed before I move on to implementing it.

**Comment by SimonLandmine** [comment]
Makes sense to me. And it's not a usability-breaking issue, so can definitely loiter a bit.
(I usually use my bigger monitor for map-building, but sometimes I do some when sat in a coffee shop with my laptop and trackball.)

**Comment by Windchild292** [comment]
Forgot to add, this is an enhancement to the map editor.

**Comment by sixlettervariables** [comment]
After the next release let me know if this is still an issue, #1751 addresses this in theory.
