### ISSUE TITLE
Map Editor 47.3 - Building Selection CF

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#1639]
When using CTRL+Scroll over the Buildings 'button' to change the Building Type, would it be possible to change the Building CF value to the default for that kind of building? That would avoid the occasional tendency to unintentionally end up with CF15 Heavy buildings and CF90 Light buildings on maps.

i.e. 15 for Light, 40 for Medium, 90 for Heavy, and 120 for Hardened

**Comment by Windchild292** [comment]
This one shouldn't be that hard to implement, and would make a lot of sense in preventing errors where the CF is greater than the maximum.

**Comment by SimonLandmine** [comment]
I couldn't recall offhand the 'acceptable ranges' for building structure from TacOps! Thanks.
Does the map editor also validate the number of hexes of the building against the Building Type value? (I appreciate that would be an extra layer of hassle for limited return, though.)

**Comment by SimonLandmine** [comment]
Might also be applicable to bridges, too, come to think of it.

**Comment by Windchild292** [comment]
This is an enhancement, and implementing it properly will take some time.
Currently we enforce bits and pieces of the logic, but it is scattered at best.
