### ISSUE TITLE
Next Valid Target

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#164]
Current 'Next' button will run thru all available target. Would be great if there's a 'Next Valid Target' button especially for larger games.

**Comment by arlith** [comment]
To be clear, you mean "valid target" as in one that you have LoS to, yes?  As it is now, I believe the "next target" button does only consider "valid" targets, where valid is defined as targets that you are allowed to shoot at (aka, enemies and not allies unless friendly fire is on).

**Comment by SirMegaV** [comment]
Valid target as in someone I can shoot at. Unless there are changes in the
last 2 releases, the next target button will cycle all enemy units that I
can see, but may or may not shoot.

**Comment by arlith** [comment]
Yea, the wording is really tricky here.  There are two interpretations for "can shoot at."  MM has a way to compute a "valid target" that doesn't consider line of sight (more or less, is this a phase where targeting is allowed, and this unit is an enemy, or an ally and friendly fire is on).  This is already used for "next target."

But what you want is for next target to only target units that actually have a chance of being hit by the shooting unit (aka, have line of sight, as well as being a "valid target").

This wouldn't be all that difficult to implement, I'm just not sure how to distinguish it from the current next target button.  I'm not sure we want to eliminate the old behavior, but I'm also reluctant to add yet another button.  I could possibly implement it via a keyboard shortcut without a button, but that's a good way for it to be a hidden feature.  I could make the behavior a toggle on a menu item.

**Comment by SirMegaV** [comment]
Toggle on the menu item is good. Reason for this request is because I
always have to click next target many times before I get to someone I can
shoot at, and ended up pressing the minimap instead.

**Comment by pheonixstorm** [comment]
If you do a button you can have them swapped out via client settings though correct? I would much rather have a Next Target for LOS units that I can swap out for the old button. Maybe have the valid LOS target button as the new default?

**Comment by crazys1** [comment]
I'm late to the comment stream, but maybe you should name it "Next Viable Target" and do not specify LOS. The reason is if you are doing indirect LRM fire and you have a spotter, then naturally you do not need LOS.

**Comment by arlith** [comment]
I implemented this feature in a branch, which got merged in 5846aa.

Now, if you hold shift when pressing the Next Target button, only targets that have a valid to-hit will be targeted (this should take indirect fire into effect).  Also, if you hold control, it will ignore allies (even if FF is on).  You can hold both control and shift for these to both take effect.  Additionally, I added keybinds for this.  I shifted around the default keys to accomodate this, now Z/C are prev/next target respectively with the same modifier scheme (ie, shift for valid only, etc.).
