### ISSUE TITLE
Hercules HRC-LS-9000 sprite

### ISSUE THREAD

**Issue by AskAgain** [MegaMek/megamek#1640]
### Environment
Still the case as of 0.47.0
Windows
Java version 1.8.0_241

### Description
Hercules HRC-LS-9000 is showing the sprite for the Hercules (3053) model Dropship and not the Sprite for the Hercules BattleMech.

### Files
![Hercules](https://user-images.githubusercontent.com/50790862/73606407-09a81f00-454e-11ea-9117-6844b0972208.JPG)

**Comment by HammerGS** [comment]
Your version has an outdated Mechset.  Fixed in current versions.
![image](https://user-images.githubusercontent.com/13752452/73612359-43a60f00-45a8-11ea-932d-8ec8337ed31a.png)
