### ISSUE TITLE
Map Editor 47.3 - Building selection issue

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#1641]
With the mouse pointer over the 'Buildings' icon, and using CTRL+scrollwheel to select the Building Type, there appears to be odd behaviour at the top and bottom end of the range ...

If you CTRL+ScrollDown beyond 'Light Building', you end up with the following in the detail window (I don't know what it's actually called) ...

_Building CF 40
Building Elevation 1
Woods (unknown)_

... and a starfield in the preview hex.

And if you CTRL+ScrollUp beyond 'Hardened Building', you get the following ...

_Building CF 40
Building Elevation 1
Wall_

... and, again, a starfield in the preview hex.

**Comment by Windchild292** [comment]
Fixed
