### ISSUE TITLE
Map Editor 47.3 - Mud selection issue

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#1642]
With the cursor over the 'Mud' icon, and using CTRL+Scroll to change the mud type, while there are different images in the preview hex for "Mud 1" and "Mud 2", the detail window only states _Mud_, without stating whether it's value 1 or 2. Equally, the tooltip over the map only states _Mud_.

Is there a functional difference between the two, or is it simply a visual difference? (The latter is also cool, just good to know!)

**Comment by Windchild292** [comment]
The difference appears to be visual only in the code. This can be closed.

**Comment by HammerGS** [comment]
Per Slack closing.
