### ISSUE TITLE
Map Editor 47.3 - Exits Button Tooltip

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#1643]
The Exit Selection button appears to retain the tooltip giving the button name, rather than the button function.

![MapEditor-ExitsButton](https://user-images.githubusercontent.com/26851644/73612956-9d2e2e00-45e8-11ea-94cf-577e10e7e7f1.png)

**Comment by Windchild292** [comment]
This will be fixed as part of #1629, as this is a missing localisation spotted there.
