### ISSUE TITLE
Terrain displayed on map is shifted to adjacent hexes

### ISSUE THREAD

**Issue by BairdEC** [MegaMek/megamek#1645]
### Environment
MM 0.47.3 started from MekHQ
Win10
Java (build 1.8.0_241-b07)

### Description
I am seeing some oddities when moving near water.  My meks show negative elevations, and I observed a pair of vehicles move onto and off of depth 2 water hexes.

The log recorded movement into water when the map showed a clear hex.  I had to jump the mek to get it to move.  It only moved one hex, even though the jump option showed four hexes.  It is consistent with only having one jump jet out of water.

> Wolverine WVR-6R #3 (Steel Recon) must make a piloting skill check while moving from hex 2812 to hex 2912 (entering Depth 2 Water).
> Needs 6 [2 (Base piloting skill) + 1 (cramped cockpit) + 3 (Tornado F1-F3) + 0 (entering Depth 2 Water)], rolls 9 : succeeds.

![Elevation -1](https://user-images.githubusercontent.com/38081112/73615159-c76cf500-45c2-11ea-829e-0ed78cb7924d.PNG)

![Elevation -2](https://user-images.githubusercontent.com/38081112/73615162-ccca3f80-45c2-11ea-906c-f4021633e4bc.PNG)

Vedettes moving onto and off of water hexes:
![Water Move1](https://user-images.githubusercontent.com/38081112/73615204-1e72ca00-45c3-11ea-92b7-8494f41d5358.PNG)

![Water Move2](https://user-images.githubusercontent.com/38081112/73615207-23d01480-45c3-11ea-8902-7f3cc3739cfa.PNG)

### Files

[Steel Recon30340120.zip](https://github.com/MegaMek/megamek/files/4145296/Steel.Recon30340120.zip)
[customs.zip](https://github.com/MegaMek/megamek/files/4145297/customs.zip)

Save game prior to the Vedette movement:
[autosave_2020-02-02_13-12-24.sav - Copy.gz](https://github.com/MegaMek/megamek/files/4145292/autosave_2020-02-02_13-12-24.sav.-.Copy.gz)

Save game after the Vedette movement:
[autosave_2020-02-02_13-15-18.sav - Copy.gz](https://github.com/MegaMek/megamek/files/4145294/autosave_2020-02-02_13-15-18.sav.-.Copy.gz)

Wolverine movement next to water:
[autosave_2020-02-02_13-26-51.sav - Copy.gz](https://github.com/MegaMek/megamek/files/4145295/autosave_2020-02-02_13-26-51.sav.-.Copy.gz)

The map was randomly generated.
[Water move.zip](https://github.com/MegaMek/megamek/files/4145298/Water.move.zip)

**Comment by Kailan7401** [comment]
I had an identical issue, but with 47.4. I reloaded the save game with 47.3 and noticed the water hexes were in different locations than they were before. A unit that was trapped with 0 movement on heavy woods in the 47.4 save was shown to be in water in 47.3

**Comment by neoancient** [comment]
Did you change the tileset theme?
