### ISSUE TITLE
c3 Networks and Cover

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#1646]
Per the BattleMech Manual page 110, spotters for c3 networks no longer need line of sight to a target unit in order to spot. Megamek currently has the old rules implemented, where line of sight was a requirement.

Exact quote: "LOS: While ’Mechs must have LOS to a target to make an attack using a C3 system, the C3 system itself need not have LOS."

**Comment by SimonLandmine** [comment]
That seems a little odd. I've put [a query](https://bg.battletech.com/forums/index.php?topic=68180.0) up for clarification on the forum.

**Comment by binaryspica** [comment]
I wonder that it helps, but C3 in Total Warfare also says that C3 system does not needs LOS to be functional, by the errata.
