### ISSUE TITLE
WiGEs can't sideslip across water

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#1647]
According to errata (see link below), all WiGE should now be treated as having the Floatation Hull perk, whether they've got it listed or not.

[https://bg.battletech.com/forums/index.php?topic=46241.msg1065439#msg1065439](https://bg.battletech.com/forums/index.php?topic=46241.msg1065439#msg1065439)

(There's also a clarification there regarding WiGEs and cover when travelling along a road through woods, but MM may already implement in line with that.)

(This note brought to you courtesy of a WiGE that went to Davy Jones' Locker following a flanking sideslip above a lake.)

**Comment by neoancient** [comment]
Based on the forum post it should not have mattered whether it has a flotation hull, since it should have ended above the surface of the water. So there appears to be a bug here as well as the erratum.

https://bg.battletech.com/forums/index.php?topic=68177.new#new

**Comment by SimonLandmine** [comment]
Thanks @neoancient - I wasn't sure if a side-slipping WiGE was supposed to 'stall-and-drop'.

**Comment by neoancient** [comment]
Do you remember which map you were using, or even better, have a saved game (even from after the incident)? The skid processing code looks like it should have accounted for it being a WiGE. There's something I'm missing.

**Comment by SimonLandmine** [comment]
Megamek: 46.1
OS: Windows 8.1
Java: 1.8.0_231

I've attached the board, as it's one I put together to try out different designs of dam for the 'dam-and-lake' board I'm working on (and to test launching Locusts off a damn at speed). Along with the savegames and the WiGE design in question (which was also a custom), in case you need to reload.
Player name is Simon.

There's also the possible description issue, where it's described as 'falling 7 levels', when technically, it fell one level to the water's surface, then through six levels of water. (It totals seven, but it's potentially confusing.)

(I didn't know exactly which files you might need, so here's a grab-bag.)
[20200203.zip](https://github.com/MegaMek/megamek/files/4172839/20200203.zip)

**Comment by neoancient** [comment]
The problem is that when it computes the elevation in the hex it sideslips into, it's not taking the water into account and treating it like a unit skidding into the water. I've fixed this to take water and ice into account and glide over the surface. I also verified that when sideslipping off the dam it either maintains elevation or drops to just above the water, depending on climb mode.

During my testing I was able to land the WiGE on water, so the flotation hull is implemented.

**Comment by SimonLandmine** [comment]
Thanks!
Does a WiGE sideslipping on land (on flat, non-icy terrain) also glide, or does it hit the ground? And should it?

**Comment by neoancient** [comment]
The rules for sideslipping are found on page 67 of TW. The unit does not change elevation on entering the new hex, with the exception of a WiGE entering a hex one elevation level higher. In that case it automatically rises. If the terrain is the new hex is any higher there is a collision. If the new hex is lower, my interpretation is that it maintains elevation during the sideslip, then automically drops to one level above the terrain unless the climb mode is set to maintain elevation and it still has MP remaining.

**Comment by SimonLandmine** [comment]
Aha! Thanks, that all makes sense. Sorry, should have waited until I could get to my books before replying!
