### ISSUE TITLE
NPE in Compute.canCompleteNodePath

### ISSUE THREAD

**Issue by arlith** [MegaMek/megamek#165]
Top of the stack trace:

`java.lang.NullPointerException
   at megamek.common.Compute.canCompleteNodePath(Compute.java:1676)
   at megamek.common.Compute.canCompleteNodePath(Compute.java:1683)
   at megamek.common.Compute.findC3Spotter(Compute.java:1627)
   at megamek.common.Compute.getRangeMods(Compute.java:1086)
   at megamek.common.actions.WeaponAttackAction.toHit(WeaponAttackAction.java:1472)`

This was originally posted [here](http://bg.battletech.com/forums/index.php?topic=52278.msg1208970#msg1208970).

Looking at the code, it would appear that code was copied from the `// Check for ECM between spotter and start` block to the `// ECMInfo for line between spotter's position and end's position` but the null guards remained `spotterStartECM` instead of being updated to `spotterEndECM`.

I would like to get a saved game to be able to reproduce this to know that it's fixed, waiting on a reply from the OP.

**Comment by arlith** [comment]
Fixed in 23d6c64.

After looking at the blame, it looks like I added the offending code in 70f064.  It looks pretty clear that this was a mistake made by copy/pasting code and not carefully checking.

**Comment by pheonixstorm** [comment]
@arlith In the commit and history file you labeled the fix as being for 163 (Feature Request) and not 165 (Bug) Shouldn't matter with the commit but might with the history text
