### ISSUE TITLE
Thumper Artillery Vehicle (Standard) should not have a turret location

### ISSUE THREAD

**Issue by BlackJesus1001** [MegaMek/megamek#1652]
Version 0.47.0 Megamek

Thumper Artillery Vehicle (Standard) aka the Star League variant incorrectly has a turret location with 0 armor when it should not have a turret at all.

Record sheet 3075 Unabridged - The Cutting Edge is the source
![Thumper](https://user-images.githubusercontent.com/60718633/73892661-a4488b00-48cb-11ea-9587-d8fad4c0cc23.png)

haven't checked on the most recent build but I couldn't find a ticket for it.

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/4ae60b13f71b74533838f570df6469acac6ec2d2
