### ISSUE TITLE
Printing wrong weapon

### ISSUE THREAD

**Issue by Maingunnery** [MegaMek/megamek#1655]
### Environment
megameklab-windows-0.47.2
windows 7

### Description
Created an OmniMech with Improved Heavy **Small** Lasers, but when printed to PDF (CTRL+L and CutePDF Writer) they became single critical Improved Heavy **Medium** Lasers

### Files

[KF2.zip](https://github.com/MegaMek/megameklab/files/4173128/KF2.zip)

**Comment by HammerGS** [comment]
As Neo mentioned copy and paste error in Shortname.  Fixed in
https://github.com/MegaMek/megamek/commit/ae93c3ffb7cf61c28d89ebc555558c2861317e85
