### ISSUE TITLE
RATs From Interstellar Expeditions.

### ISSUE THREAD

**Issue by xStormforgex** [MegaMek/megamek#166]
Here are the RATs for the Escorpion Imperio in Interstellar Expeditions. One thing of note. Since there is not beast mounted infantry, I replaced the Horse-Mounted Infantry on the Infantry RAT with Motorized Rifle Infantry as it has the same movement profile. 

[(3090) Interstellar Expeditions (Escorpion Imperio).zip](https://github.com/MegaMek/megamek/files/233438/3090.Interstellar.Expeditions.Escorpion.Imperio.zip)

**Comment by HammerGS** [comment]
I'll have a look and get them added.

**Comment by HammerGS** [comment]
Added in da0cd39e3ea374aaedc0c944359cf7915d748070

Thanks for making them.
