### ISSUE TITLE
A unit with C3 and Nova CEWS cannot access for C3 network of the unit without CEWS.

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megamek#1664]
### Environment
Ver 0.47.4

### Description
As title says. If you made a custom unit that has C3(either C3 Master or C3 Slave) and Nova Combined Electronic Warfare System, for now they can only make the network with the other units that also have Nova CEWS. For example:

Unit **M1N** and **M2N** have C3 Master **and** Nova CEWS
Unit **M1** and **M2** have C3 Master but does not have Nova CEWS

Unit **S1N** has C3 Slave **and** Nova CEWS
Unit **S1** has C3 Slave but does not have Nova CEWS

Then, in the lobby, if you put **M1N** and **M1** as the company master, **M1N** only accepts **M2N** as its platoon master, and **M1** only accepts **M2** as its platoon master. It is not possible to connect **M1N** and **M2**, and **M1** and **M2N**.

The same also goes with the slave; You cannot connect **S1N** to **M2**, and **S1** and **M2N** also have the same problem.

I didn't checked Improved C3(C3i) but I suspect that it may have the same problem.

Also, I have checked IO and errata but nothing says you can't put C3 and Nova in the same unit.

[Test Master - Nova.zip](https://github.com/MegaMek/megamek/files/4184060/Test.Master.-.Nova.zip)

**Comment by binaryspica** [comment]
Also, if you have a unit with both C3 Slave and Nova CEWS, on the C3 network configuration of lobby **the other units with Nova CEWS are on the list of its possible network.** For example on the list it have both the unit with C3 Slave &Nova and the unit with only Nova alike

**Comment by binaryspica** [comment]
An update for this:

If you set the C3 network on MekHQ, you CAN link a unit with C3 and Nova, and a unit with C3 but not Nova. As long as you don't touch its setting on the lobby it is possible to link it. So I guess that the problem only occurs on the lobby of Megamek.

**Comment by HammerGS** [comment]
From IO pg 66 - 

_Game Rules: The Nova CEWS operates as a combination of ECM,
active probe and C3i equipment, with the following exceptions.
The Nova CEWS can **link up to two other units mounting a Nova
CEWS.**_

Pretty clear that NOVA can only connect to NOVA not normal C3 or C3i systems.

**Comment by HammerGS** [comment]
So Tech Manual pg 209 - 
_Construction Rules: **C3 systems (including the C3 Master and C3 Slave) and C3i systems may not be combined on a single unit, as the two technologies are incompatible.** Units with either system may mount multiples, if desired, but only one C3 Slave or C3i computer may be employed at one time in game play. (Multiple C3 Master computers may be used to maintain multiple C3 networks)._

Talking to the rules team they are looking at extending this to the NOVA. So construction wise only one type of C3 system can be mounted in a unit.

**Comment by binaryspica** [comment]
> From IO pg 66 -
> 
> _Game Rules: The Nova CEWS operates as a combination of ECM, active probe and C3i equipment, with the following exceptions. The Nova CEWS can **link up to two other units mounting a Nova CEWS.**_
> 
> Pretty clear that NOVA can only connect to NOVA not normal C3 or C3i systems.
> 
> Rules confirmation posted - https://bg.battletech.com/forums/index.php?topic=68333.0

Sure but that wasn't the point, for the problem wasn't want to connect C3 and Nova.

> So Tech Manual pg 209 -
> _Construction Rules: **C3 systems (including the C3 Master and C3 Slave) and C3i systems may not be combined on a single unit, as the two technologies are incompatible.** Units with either system may mount multiples, if desired, but only one C3 Slave or C3i computer may be employed at one time in game play. (Multiple C3 Master computers may be used to maintain multiple C3 networks)._
> 
> Talking to the rules team they are looking at extending this to the NOVA. So construction wise only one type of C3 system can be mounted in a unit.

So it seems illegal to make a unit with both C3 and Nova in the first place.  Although I did think that Nova's description mentions C3i only for the mechanism. Is it better to close the issue, for the root of the problem is the illegal unit?
