### ISSUE TITLE
Request: Grouping off-board units as one icon

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megamek#1667]
### Environment
Ver 0.47.4

### Description
Well, it is not so serious problem, but it is annoying to use artilleries for each guns are have the separated icon and you need to confirm where to shoot individually. 

So, what if we can group a bunch of artilleries as one unit(and show every artillery weapons they have on a unit), or at least shares the same icon in MegaMek's unit list? 

I think that the former is not so easy task, and there are a manual solution for this(to create an unofficial artillery unit with a bunch of guns rather than use the official howitzers), though.

**Comment by neoancient** [comment]
The rules are designed around single units. If you have too many units to keep track of, reduce the size of your battles.
