### ISSUE TITLE
EntitySprite not getting updated when a unit becomes visible in a DB game

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#167]
![image](https://cloud.githubusercontent.com/assets/16950832/14768532/b14b0534-0a0a-11e6-998c-82e755b2437e.png)

Playing a DB game zoomed out to the first level where the hex coords disappear.  When an opposing unit comes into LOS for the first time as you can see its unit icon is drawn tiny/wrong scale (Ostol).  Have to zoom in/out or toggle iso to get the board to redraw causing the unit's icon to draw at the correct scale.

**Comment by SJuliez** [comment]
Are you speaking of the minimap? (EntitySprites are those on the board. The icon on the board seems ok to me)

**Comment by BLOODWOLF333** [comment]
How the Ostol is drawn tiny in that hex right above the red Centurion.  (on IRC with Arlith and he knows about this).

**Comment by SJuliez** [comment]
Ah now I see it...
The Ant-Ostsol...

**Comment by BLOODWOLF333** [comment]
lol pew pew pew

**Comment by BLOODWOLF333** [comment]
Ok so, this only occurs,
1. During a double blind game
2. When the player is zoomed out
3. Only when an enemy unit is first revealed will it draw small like this
http://i.imgur.com/HXMa83c.png

Player name: BLOODWOLF
[Antmechs.zip](https://github.com/MegaMek/megamek/files/358418/Antmechs.zip)

**Comment by BLOODWOLF333** [comment]
![mm0](https://cloud.githubusercontent.com/assets/16950832/17274179/58fa3eaa-5699-11e6-881e-0e12ef930184.png)

Saved the turn before this ^ happens
Player name: BLOODWOLF
[Antmech.sav.gz](https://github.com/MegaMek/megamek/files/392207/Antmech.sav.gz)

**Comment by arlith** [comment]
Turns out this only happens if isometric is on.  Adjusted some code in `IsometricSprite`.
