### ISSUE TITLE
Missing Ti Ts'ang (Jason)

### ISSUE THREAD

**Issue by mhjacks** [MegaMek/megamek#1687]
### Environment
What version of MegaMek does your issue apply to? 0.47.4
What operating system are you using?  Windows, Mac, or Linux? Linux
What java version are you using?  1.8

### Description
The Ti Ts'ang Jason is included in SSW and documented on the MUL: 
http://masterunitlist.info/Unit/Details/7395/ti-tsang-tsg-9h-jason

It's a particularly nasty TSM variant and a favorite of my local group.

### Files

[Ti Ts'ang TSG-9H (Jason).mtf.txt](https://github.com/MegaMek/megamek/files/4217137/Ti.Ts.ang.TSG-9H.Jason.mtf.txt)

**Comment by HammerGS** [comment]
Added here - https://github.com/MegaMek/megamek/commit/1533297e0693dd0f2dd8665dc61b00de8ea56fbb
