### ISSUE TITLE
SRT ammo has extinction and reintroduction dates for One-Shot launchers

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megamek#1701]
Using MML 0.47.4 on OS X, I was unable to add SRT ammo to a unit built in the 3020s because, while MML has no extinction date for short-range torpedo launchers, it has an extinction date of 2800 for short-range torpedoes themselves. It claims they were re-introduced in 3030 by the FWL. This appears to be data from the table on page 291 of Total Warfare, but taken from the row below the torpedo.

There should be no extinction or reintroduction dates for any SRT ammo.

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/53d19f0840e1d6c77c4a19c6d552764b416695e8
