### ISSUE TITLE
Bridge movement: does default climb mode on make sense?

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#172]
I am requesting that bridges would be handled differently.  I need to back this Assassin up five hexes over a bridge, all five hexes are level 0.  Enabled climb mode so that it would stay on the bridge and not have to perform that entering water hex PSR (climb mode is not obvious as discussed on the forums).  Maybe the elevation preference should always be to stay on a bridge rather than enter the water.  I think most people understand to check the CF before entering a hex and if it's lower than their mechs weight most would avoid entering it.  Or when selecting such a hex just click 'go down" to enter the water instead of the bridge might be more intuitive?  The planet is Fletcher with 1.3 gravity so, I dont want to risk jumping and shatter a hip.  But, that PSR for backing up over an elevation change I think is wrong since that bridge should be considered the same elevation as the other five hexes.

![image](https://cloud.githubusercontent.com/assets/16950832/14938356/692b373e-0ee6-11e6-9ed5-2537b2f467eb.png)

![image](https://cloud.githubusercontent.com/assets/16950832/14938358/70cfbfdc-0ee6-11e6-9608-21d5d25a765d.png)

[ECO.sav.gz](https://github.com/MegaMek/megamek/files/243807/ECO.sav.gz)

**Comment by pheonixstorm** [comment]
If its saying something about an elevation change I think this might be a bu rather than a feature request. My guess is that it still thinks you are trying to enter the water which would be an elevation change.

Maybe one of the devs will have a better answer.

**Comment by BLOODWOLF333** [comment]
Arlith's looking at it with me on IRC as well.  After attempting the movement backwards it doesn't make the roll at all so, I guess it's not a real biggie.  But, makes you want to not attempt that move when it actually wouldn't have any risk.

**Comment by arlith** [comment]
I guess, I see two issues here.  One is how climb mode works, the fact that it's not always that intuitive, and  the fact that it could arguably be the default.

The second is the PSR nag.  I've already fixed the PSR nag in e0f8df.

**Comment by BLOODWOLF333** [comment]
I think taking the higher terrain by default would be more intuitive at least for across bridge movement.  Telling the mech to go into the water instead with climb mode.....I think most players would click the "go down" button and expect that to work, I did.

**Comment by arlith** [comment]
In 396529 I made it so the default climb mode is an configurable option.  I defaulted it to "Climb up".
