### ISSUE TITLE
Reorder of include lines in tilesets

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#173]
Currently trees and swamps are drawn over road images with the new tileset style.  And I dont know what is going on with that floating bridge in hex 0810 (only when isometric view is on).

![ingame](https://cloud.githubusercontent.com/assets/16950832/14938811/3807fea2-0ef6-11e6-89d4-d650260c5f1e.png)

I would propose cutting the:
include "StandardIncludes/BasicBridges.tileinc"
include "StandardIncludes/BasicRoads.tileinc"

and pasting them after the swamp and woods image lines so that those draw under road images.  I supposed the swamp images could be made transparent like how ice is but, IMO they should be drawn under the roads.

![ingame1](https://cloud.githubusercontent.com/assets/16950832/14938823/82f94d80-0ef6-11e6-873d-6c9ca3dee762.png)

With iso view off that bridge image snaps back into the correct position.

**Comment by pheonixstorm** [comment]
Why does hex 0810 have a height of 2? If that wasn't there you wouldn't be seeing a floating bridge.

**Comment by BLOODWOLF333** [comment]
Oh thats right......I just randomly generated this map in the board editor to show examples of the interactions with the roads.  That makes no sense to me I'll try this again and see if its putting a building in that hex or something and not drawing the building image?

**Comment by arlith** [comment]
I've seen that before but never looked into it.  I presume it's a bug somewhere in the map generator.

**Comment by BLOODWOLF333** [comment]
Fixed atmospheric tileset

[atmospheric.zip](https://github.com/MegaMek/megamek/files/248035/atmospheric.zip)
