### ISSUE TITLE
Are weights working right in latest megamek? (67903a3855)

### ISSUE THREAD

**Issue by mhjacks** [MegaMek/megamek#1738]
### Environment
What version of MegaMek does your issue apply to?  Note whether it is the stand alone MegaMek or HQ's MegaMek.  MekHQ, v67903a3855
What operating system are you using?  Windows, Mac, or Linux? Linux
What java version are you using?  If unsure it will state your java version at the top of the megameklog.txt file.
Java 1.8.0

### Description
Several Battle Armor units fail to load, failing validation due to weight.  These are canon units that have loaded in previous megamek builds.  See attached.

### Files
The error occurs in the lobby with the units being rejected.
[megameklog.txt](https://github.com/MegaMek/megamek/files/4285312/megameklog.txt)

**Comment by neoancient** [comment]
I noticed that a couple days ago. Fixed by #1735
