### ISSUE TITLE
Deleting custom units breaks campaign file

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#174]
I removed two custom units from my unzipped "custom" folder that I don't use or have in my force for this campaign and now HQ does not load.  How do I fix this?  Have ran into this several times before and just find it way too easy to break a campaign file due to something as trivial as removing a few custom units that I decided I don't want or didn't need anymore.  I restored those two units(battalion & regiment HQ) out of the recycle bin back into the customs folder and still does not load.
[broken campaign.zip](https://github.com/MegaMek/megamek/files/244333/broken.campaign.zip)

**Comment by Akjosch** [comment]
Did you already try removing the units cache?

**Comment by BLOODWOLF333** [comment]
Yep, deleted the units.cache, deleted entity status, the hq log, Im going through the campaign file in gedit and it doesnt list those two units "Battalion HQ or Regiment HQ" after doing a search.  Im trying everything I can think of.  Opened in MML and resaved those two units.  All with same result :(

**Comment by BLOODWOLF333** [comment]
After deleting a custom.jar of MM out of the folder with the stock MM.exe it's ok now and loads whether I have those two custom units or not.  My fault.  I know I'm way out in left field with some of my stuff.
