### ISSUE TITLE
Anti-Personnel Weapons not staying on AP Weapon Mounts

### ISSUE THREAD

**Issue by GamerFoxNeumann** [MegaMek/megamek#1741]
MegaMek Lab 0.47.4

Battle Armor Bug/Problem I've been getting is that weapons that I originally put on AP weapon mounts migrate to the manipulators when loading again later. This is consistent and constantly makes my BA designs invalid. This happens with pistols and rifles. It also sometimes shifts weapons that I can't put on AP Weapon mounts like LAWs from the hands to an AP Weapon mount.

Is this a logged problem or is it just me?

**Comment by Windchild292** [comment]
I think @neoancient should comment on this.

**Comment by GamerFoxNeumann** [comment]
> I think @neoancient should comment on this.

I found out that I posted this in the wrong forum as it were... but if neoancient can ascertain about this problem, it would be helpful. :)

**Comment by neoancient** [comment]
Yes, it's a bug. It was reported as MegaMek/megameklab#441 and fixed by #1691 for the next release.
