### ISSUE TITLE
Variable Tech Level sometimes changes tech level of equipment the wrong way

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megamek#1746]
Using MML 0.47.4 on OS X with Java build 1.8.0_51-b16, turning on/off Variable Tech Level changes the tech level of some equipment the wrong way.

For example, with Variable Tech Level off, these items are incorrectly listed as having a Standard tech level:
Drone (Remote) Carrier Control System
Drone (Remote) Operating System
Drones (as Extra Equipment)
Remote Drone Command Console
Prototype Artemis IV FCS
Cockpit Command Console

Turning on Variable Tech Level makes them all show up as Advanced (except for the Artemis IV, which shows up as Experimental). I've tested this for the years 3027 and 3150, and the results are the same.

I haven't checked all the items, but I noticed these.

**Comment by neoancient** [comment]
Prototype equipment should all be experimental but most of it is treated as standard.

**Comment by HammerGS** [comment]
I'm going through misctype and will check what has a static tech level and look them up and set them.

**Comment by HammerGS** [comment]
Fixed with https://github.com/MegaMek/megamek/commit/b54c83c5be9e92ad67f387f8fdd5611885319453

There are still items with no clear guidance from CGL or I can find the books. Leaving those as is for now.
