### ISSUE TITLE
0.47.5-SNAPSHOT - Board Editor: Theme isn't kept from the board generation window

### ISSUE THREAD

**Issue by Windchild292** [MegaMek/megamek#1767]
Raised on discord, the theme is not set to the theme used when generating the initial board.

**Comment by SJuliez** [comment]
Not sure what this means but I guess the following: When generating a map with "grass" as theme, the theme in Hex Settings in the right-hand menu bar should also be set to grass.

**Comment by Windchild292** [comment]
Exactly
