### ISSUE TITLE
0.47.4 Map Editor. Resizing board jumbles buildings and roads. 

### ISSUE THREAD

**Issue by MechSalvager** [MegaMek/megamek#1768]
### Environment
Found to be present in 0.47.4 with the full MekHQ download (Has been seen in earlier versions as well.)
Megamek was running under Windows 8.1 6.3 (x86), Java version 1.8.0_241.

### Description
The bug jumbles up buildings and roads when you resize the board towards the west in the Map Editor. 
Before the resize (Map is city_downtown.board):
![image](https://user-images.githubusercontent.com/62211084/76704394-01a8d680-66d9-11ea-82c6-24bb8ecde171.png)

After resizing the board one hex bigger towards the west:
![image](https://user-images.githubusercontent.com/62211084/76704436-50ef0700-66d9-11ea-8941-7a7dcaf46c19.png)

I have been able to replicate it consistently on my machine by doing the following steps: 
-Open Megamek
-Open the Map Editor (Say no to reading the readme)
-Set it to make a random map with the TOWN setting for civilization/city (Or load a map that has buildings on it, both works)
-Press Resize Map.
-Put the number 1 into the "West" field and press "okay". (Any number seems to work, even negative ones)

This results in a jumbled map. The other directions in the Resize Map screen do not have the same problem. From limited testing, the size of the map doesn't seem to make a difference.

### Files
[megameklog.txt](https://github.com/MegaMek/megamek/files/4334417/megameklog.txt)

**Comment by Windchild292** [comment]
Key addition: this only appears to happen for odd number board changes. With this information, I can recreate this every time.

**Comment by SJuliez** [comment]
Well it is a hex map. Moving all hexes to the right by any odd number will either jumble the map (the current "solution") or move everything a half-hex up or down, discarding some of the top row or bottom row hexes. I don't see a good and not-overcomplicated solution and I'd ask users to add even numbers of columns to the west side.

**Comment by NickAragua** [comment]
Yeah, I think that's the only practical solution.

**Comment by Windchild292** [comment]
Do we want to enforce even additions on the west side?
