### ISSUE TITLE
[Bug] Searchlight Not Functioning

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#177]
MegaMek version 0.41.17

Was working previously, but now Augustus MBT with mounted searchlight cannot be turned on during firing phase. Savegame attached.

[Searchlight.sav.gz](https://github.com/MegaMek/megamek/files/248132/Searchlight.sav.gz)

**Comment by arlith** [comment]
That Augustus is carrying a spotlight, but it's currently off.  During the movement phase you need to activate it.  If you look on the Extras tab, under "Carrying:" it will say "Searclight (off)".
