### ISSUE TITLE
47.4 Map Editor doesn't resize minimap or scrollbars when loading bigger map

### ISSUE THREAD

**Issue by NickAragua** [MegaMek/megamek#1776]
When you start the map editor, it starts you off with a 16x17 map. When you click 'load' and select a larger map, the map scrollbars do not adjust appropriately, leaving you unable to scroll out of the top left 16x17 of the map. The minimap does not reflect the dimensions of loaded map, either, although it re-adjusts when you resize it.

The workaround is to generate a map of the same size as the map you're planning to load first.

**Comment by Windchild292** [comment]
I think I fixed this in #1674, but I'll double check

**Comment by Windchild292** [comment]
I'm pretty sure this is fixed by #1674

**Comment by NickAragua** [comment]
Good point. Guess I'm not quite as on the bleeding edge as I thought.
