### ISSUE TITLE
Indicator for Weapon Jammed

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#178]
Currently there are small indicators below the unit to inform the player of various information, such as T = carrying troops. Would be great if there's a J = weapon jammed, please unjam indicator too.

**Comment by pheonixstorm** [comment]
I know there is one in the unit display, but unless you are looking for it or missed the message in the phase report it is kinda useless

**Comment by SirMegaV** [comment]
Yes.. both the unit display and report does inform the player, but it will
be easier to remember if the player can see a little 'J' on the unit when
they are moving, kind of like "oh yea.. i forgot his AC was jammed"

**Comment by BLOODWOLF333** [comment]
I've run into this as well, yes you will get a * next to the weapon(I think only under the system tab?) when it is jammed in the unit display but if we put a J over the unit icon it would still have to show prone, hulldown, immobile, etc and the units hex could get really cluttered.  So, it would be nice to have something to make it very apparent when a weapon is jammed maybe the best bet is to change the text color of the AC under the weapons tab in the unit display?

**Comment by pheonixstorm** [comment]
Weapon jams are a j next to the weapon. * is used for damaged or destroyed unless it changed at some point.

**Comment by arlith** [comment]
Pretty that's still how it works.
This could potentially be implemented as a highlight or background color for the weapon in the tooltip in the weapons part of the tooltip.

**Comment by HammerGS** [comment]
Implemented
