### ISSUE TITLE
Bug: Jump Jets Interacting with terrain below buildings and bridges possibly due to implementation of Bog Down rule.

### ISSUE THREAD

**Issue by AskAgain** [MegaMek/megamek#1800]
### Environment
MekHQ 0.47.4 and below.
Windows
Java version 1.8.0_241

### Description
Units using Jump Jets to land on bridges over terrains that use Bog Down rules end up Stuck in the terrain below the bridge. I've tested normal walk/run, jumping and attempts to move using Climb Mode following the suggestions provided on the Facebook group. The results seems to work normally for ground movement but can be anywhere from mildly annoying to flat out disastrous for units that Jump onto the bridge. Screenshots to follow.

Running:
![LavaBridgeRunTest1](https://user-images.githubusercontent.com/50790862/77849918-d0191c00-716a-11ea-8026-a9a243cd0696.JPG)
![LavaBridgeRunTestTerrainToggled1](https://user-images.githubusercontent.com/50790862/77849923-d60efd00-716a-11ea-91ef-9b4f68316561.JPG)
![LavaBridgeRunTest2](https://user-images.githubusercontent.com/50790862/77849926-dd360b00-716a-11ea-8520-5bdaacd69a92.JPG)

Jumping:
![LavaBridgeJumpTest1](https://user-images.githubusercontent.com/50790862/77850095-e2478a00-716b-11ea-9978-81670cb10f54.JPG)
![LavaBridgeJumpTestTerrainToggled1](https://user-images.githubusercontent.com/50790862/77849938-f50d8f00-716a-11ea-9404-f2f7880f8a44.JPG)
![LavaBridgeJumpTest2](https://user-images.githubusercontent.com/50790862/77849952-140c2100-716b-11ea-8a6e-c0450bcd131a.JPG)
![LavaBridgeJumpTestTerrainToggled2](https://user-images.githubusercontent.com/50790862/77849960-1bcbc580-716b-11ea-97f1-fda87b6fceea.JPG)
![LavaBridgeJumpTest2ndRound1](https://user-images.githubusercontent.com/50790862/77849965-20907980-716b-11ea-9c98-9dcfbcd42f3c.JPG)

Climb Mode:
![LavaBridgeJumpClimbModeTest1](https://user-images.githubusercontent.com/50790862/77849974-30a85900-716b-11ea-87b3-0ce731f1c7a9.JPG)
![LavaBridgeJumpClimbModeTest2](https://user-images.githubusercontent.com/50790862/77849981-3dc54800-716b-11ea-805c-33ce687877e8.JPG)
![LavaBridgeJumpClimbModeTest2ndRound1](https://user-images.githubusercontent.com/50790862/77849984-43229280-716b-11ea-9c0c-87c8fccb9f61.JPG)
![LavaBridgeMovementTest1](https://user-images.githubusercontent.com/50790862/77849987-46b61980-716b-11ea-832f-dacf91da8e23.JPG)
 
I also have Screenshots of examples on bridges over Swamps.
### Files

 I've attached the Map where I replicated the above. It is the only thing in the zip file below.

[Mars Attacks.zip](https://github.com/MegaMek/mekhq/files/4398932/Mars.Attacks.zip)

**Comment by HammerGS** [comment]
For reference.  If it happens in Megamek it should be on the Megamek tracker.

**Comment by AskAgain** [comment]
Thanks Hammer, didn't notice it when I was posting it.

**Comment by AskAgain** [comment]
On the recommendation of a friend I did another test and it appears that this is probably related to the implementation of the Bog Down rule itself rather than the buildings and bridges.

![Capture](https://user-images.githubusercontent.com/50790862/77988093-314e0600-72b7-11ea-8741-7410645a55ff.JPG)
![Capture2](https://user-images.githubusercontent.com/50790862/77988098-33b06000-72b7-11ea-8049-3cae2e052bbc.JPG)

**Comment by NickAragua** [comment]
Guess it doesn't check height.

**Comment by AskAgain** [comment]
Thank you gents.
