### ISSUE TITLE
Bug: BV Discrepancies.

### ISSUE THREAD

**Issue by AskAgain** [MegaMek/megamek#1801]
### Environment
mekhq-windows-0.46.0 and mekhq-windows-0.46.1
Windows
Java version 1.8.0_241
(Delete the above lines)

### Description
Two separate issues that I have been looking at over the last few months. The first is tied to a question of why there has been a significant change in all BV calculations between 0.46.0 and 0.46.1. I had originally thought this might be intentional as I had heard Catalyst recently changed how BV2 was being calculated but recent inquiries have lead me to believe this might not be the case. The below were loaded from the same .mul in each with a decent shift in BV between the two.

![BV discrepancies](https://user-images.githubusercontent.com/50790862/77850681-d65dc700-716f-11ea-92f0-bc023b1351cb.JPG)

The second issue I came across several months ago but hadn't really thought it enough of a shift to mention, basically when I open the configure window on certain 'Mechs and select OK (whether or not I change anything that should have no affect on BV) the result is a small discrepancy in BV between the before and after. 

![Customizing changes BV](https://user-images.githubusercontent.com/50790862/77850756-3a808b00-7170-11ea-83c0-2b642afd1e23.JPG)
![Customizing changes BV2](https://user-images.githubusercontent.com/50790862/77850758-3fddd580-7170-11ea-98de-056bc91c2b33.JPG)

This seems to have continued on into 0.46.1 from 0.46.0.

![Customizing changes BV3](https://user-images.githubusercontent.com/50790862/77850761-42d8c600-7170-11ea-94a3-8fcf3af0cb0f.JPG)
![Customizing changes BV4](https://user-images.githubusercontent.com/50790862/77850764-453b2000-7170-11ea-84de-1064ec350493.JPG)

While I have nothing concrete I have reason to suspect this is only the case for Clan 'Mechs and even then it doesn't happen with every single one that I have needed to configure over the last month. I think it might be tied to a weapon system or a family of them. As the Stormcrow A I use regularly is one of the affected I suspect it might have something to do with Clan MD Pulse Lasers, Streak SRM6s, or LRM20s.

### Files
If more files are needed I am willing to try to provide them.

**Comment by neoancient** [comment]
This is not a bug. The BV adjustment due to piloting skill was changed. See the official rule change here: https://bg.battletech.com/forums/index.php?topic=67626.0
