### ISSUE TITLE
Maps and Scenarios: @Hammer. More submissions for Kaji's collection.

### ISSUE THREAD

**Issue by AskAgain** [MegaMek/megamek#1802]
Eight more maps that are companions to the one that originally got me started making more 30x17s, my revamp of the original Solaris/The_Jungle-30x17.

[TheexpandedJungle.zip](https://github.com/MegaMek/megamek/files/4399011/TheexpandedJungle.zip)

A simple scenario to be played against the BOT that pits a Warhawk against a staggered lance of Kuritans. Was hoping it might be considered as an addition to the current crop of scenarios. 

[OntheProwl.zip](https://github.com/MegaMek/megamek/files/4399016/OntheProwl.zip)

A scenario that pits two lances of Rasalhague Kungsarme against a star of Clan Wolf. Meant to be played with TacOps Double Blind and TacOps Sensor Rules. Have had difficulties getting the gameoptions to load properly on launch. Known issue?

[DownOnOurLevel.zip](https://github.com/MegaMek/megamek/files/4399032/DownOnOurLevel.zip)

This is another map that is the focus of the DownOnOurLevel scenario and necessary to be able to play it.

[RiverAmbush.zip](https://github.com/MegaMek/megamek/files/4399047/RiverAmbush.zip)

If approved then more are likely to follow. Thanks for your consideration.

**Comment by HammerGS** [comment]
Scenarios can't set rules.  Your best to add a note to the write up for it.

**Comment by AskAgain** [comment]
Edited Scenario .mms file to add note.

[DownOnOurLevel.zip](https://github.com/MegaMek/megamek/files/4399330/DownOnOurLevel.zip)

**Comment by HammerGS** [comment]
Fixed - https://github.com/MegaMek/megamek/commit/4324d8686c6984fbc3fc9775798ee156bf3b1791
