### ISSUE TITLE
BV Discrepancy

### ISSUE THREAD

**Issue by AskAgain** [MegaMek/megamek#1803]
Respectfully while I am glad to know that the first issue was indeed the official rules change, that still doesn't explain the second one.

The second issue I came across several months ago but hadn't really thought it enough of a shift to mention, basically when the configure window on certain 'Mechs is opened and closed by selecting OK (whether or not I change anything that should have no affect on BV) the result is a small discrepancy in BV between the before and after. Was it already addressed in the Developmental builds?

![Customizing changes BV](https://user-images.githubusercontent.com/50790862/77855092-06b25f00-718a-11ea-95d3-f707109a59d0.JPG)
![Customizing changes BV2](https://user-images.githubusercontent.com/50790862/77855093-09ad4f80-718a-11ea-9c12-27f1c28bfe7d.JPG)

This seems to have continued on into 0.46.1 from 0.46.0.

![Customizing changes BV3](https://user-images.githubusercontent.com/50790862/77855095-0ca84000-718a-11ea-925f-a8f0cdf6e8b4.JPG)
![Customizing changes BV4](https://user-images.githubusercontent.com/50790862/77855103-129e2100-718a-11ea-9a7a-95f3f19f461a.JPG)

While I have nothing concrete I have reason to suspect this is only the case for Clan 'Mechs and even then it doesn't happen with every single one that I have needed to configure over the last month. I think it might be tied to a weapon system or a family of them. As the Stormcrow A I use regularly is one of the affected I suspect it might have something to do with Clan MD Pulse Lasers, Streak SRM6s, or LRM20s.

Files
If more files are needed I am willing to try to provide them.

**Comment by HammerGS** [comment]
I just tested this running directly from the repo (so would be code in the next Dev release) and I can't duplicate it.

Are there changes being made in the equipment tab?

**Comment by AskAgain** [comment]
In the examples above I made no changes. Just opened the configure window and when I closed them the BV had shifted slightly (32-33 BV). I have seen it on other Clan Mechs as I track the roster on WolfNet. I can try to send examples of all the ones I can find that do it compared to the ones that don't. Will likely have to be later though. 

Promising that the newest code seems to have caught it. I might start with 0.47.4 and see if if happens there and if not then drop it altogether.

**Comment by AskAgain** [comment]
The following was using 0.47.4, loading the previously saved .mul and opening and closing the configure window by pressing OK (not closing the window).

![Customizing changes BV5](https://user-images.githubusercontent.com/50790862/77855825-b38edb00-718e-11ea-8b87-3d050c38f8ab.JPG)
![Customizing changes BV6](https://user-images.githubusercontent.com/50790862/77855826-b689cb80-718e-11ea-8ccf-e83e2d3db880.JPG)

Then I took every Clan Mech on my roster and did it for them and highlighted the ones that change to compare them to the ones that don't.

![Customizing changes BV7](https://user-images.githubusercontent.com/50790862/77855871-0c5e7380-718f-11ea-8bb3-10ed83cc0aa6.JPG)
![Customizing changes BV8](https://user-images.githubusercontent.com/50790862/77855875-0ec0cd80-718f-11ea-8e9f-2348be606676.JPG)

Hope that helps clarify what I am trying to point out. Happy to answer anymore questions as best I can.

**Comment by HammerGS** [comment]
Can you please attach the MUL you are using.

**Comment by AskAgain** [comment]
[3 Battalion.zip](https://github.com/MegaMek/megamek/files/4399383/3.Battalion.zip)

**Comment by AskAgain** [comment]
And I did just add two Stormcrow As directly from 0.47.4 and configure one with the same slight BV discrepancy.

![Customizing changes BV10](https://user-images.githubusercontent.com/50790862/77856003-ff8e4f80-718f-11ea-8dd9-801cda7050f5.JPG)

**Comment by AskAgain** [comment]
All I have time for atm, I'll try touch base this evening.

**Comment by HammerGS** [comment]
Also save your Game Options and attach them here.

**Comment by AskAgain** [comment]
[gameoptions bv bug.zip](https://github.com/MegaMek/megamek/files/4399394/gameoptions.bv.bug.zip)

**Comment by HammerGS** [comment]
I can confirm with the attached files and options this is happening is 47.4.

**Comment by Windchild292** [comment]
This is due to a difference in BV calculation for Ammunition. (pardon the rough visuals)
![image](https://user-images.githubusercontent.com/39067288/77859229-22435700-71d6-11ea-8111-b1c6fe17645b.png)

**Comment by neoancient** [comment]
The configuration dialog is replacing the Clan ammo with the IS equivalent.
