### ISSUE TITLE
41.17 : Units with 2 or more ECM suites generate no ECM field at all

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#181]
Per TM page 213, units may only use one ECM suite at a time. However, if you have a unit with 2 or more ECM suites, Megamek responds by not generating any ecm field at all (see the Eagle ASF in the attached save). It should be generating one ECM field and the second ECM should be non-functional (regardless of what setting it is set to).

[#battletech.zip](https://github.com/MegaMek/megamek/files/253980/battletech.zip)

**Comment by pheonixstorm** [comment]
ecm on the ground map with aero only works while grounded

**Comment by Question2** [comment]
Im confused by this...page 238 of TW just says that ECM works on non-aerospace units. Page 91 and 92 of TW makes no mention of ECM rules while grounded. I dont see anything about it in the TW errata either.

**Comment by pheonixstorm** [comment]
I had a question about aero and ecm in the rules forum. It was really about dropships but should be the same for asf. If its parked on the ground it works against ground units. If not...

**Comment by arlith** [comment]
This is related to a [bug report on SF](https://sourceforge.net/p/megamek/bugs/4498/).  There's new errata that was added, although it's not currently in the released errata (it should be in the errata thread though):

Total Warfare, p. 238

    "ECM and Active Probes: Electronic countermeasures have no effect on combat between aerospace units, but they still affect other types of units."

    Change to:

    "ECM and Active Probes: Electronic countermeasures have no effect on combat between aerospace units, but they still affect other types of units. Aerospace and ground units' ECM only affect each other when the Aerospace Units on Ground Mapsheet rules are being used (see p. 91), the affected unit is within range, and the aerospace unit occupies the NoE altitude. However, in this scenario a unit mounting ECM always receives the benefits of ECM, even if the attack comes from
    beyond NoE altitude."

**Comment by arlith** [comment]
The ASF in this saved game doesn't generate ECM because it's not nape of the earth (NoE).  There are still some other aspects of the aforementioned errata to be implemented, but those are covered in [SF Bug#4498](https://sourceforge.net/p/megamek/bugs/4498/).
