### ISSUE TITLE
Visual range limits (TacOps) are obsolete

### ISSUE THREAD

**Issue by bsielski** [MegaMek/megamek#1811]
Stand alone MegaMek 0.46.1 and 0.47.4
Linux
```$ java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
```
With TacOps Double Blind option and planet condition Full Moon Night the mech has visual range 5.

It should be 10.

Here is a table from TacOps PDF (p. 221)

https://i.imgur.com/Wfgtfy5.png

This is how it should look after errata 3.03

https://i.imgur.com/ocZ4dsU.png

**Comment by mkerensky** [comment]
This has been addressed for the next release.
