### ISSUE TITLE
Turn timer to force click on "Done" after set time

### ISSUE THREAD

**Issue by Graysho** [MegaMek/megamek#1815]
I host a gaming league for battletech games at innerspherewars.eu, which held seasons for MWO, HBS:Battletech and even MWLL back in the days.

Now, with HBS:BT getting worse on MP every day, we are looking for new ways to facilitate league games and naturally evaluate megamek too.

Currently the lack of a turn timer prevents usage, as in league play time windows are important and we dont want to give players a way to ruin other players gaming experience by dragging out already lost games.

So, we request to evaluate a game option "turn timer" which will click the "Done" button of a player after a given time and show a count down, maybe on said "Done" button. The actual time limit should be setable in seconds from 30 to unlimited, which would deactivate the timer.

**Comment by neoancient** [comment]
Implemented by #1835
