### ISSUE TITLE
'Simultaneous Firing' and spotting for indirect fire

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#1822]
Applies to 0.46.1, but probably all versions.

It was noted that with the 'Simultaneous Firing' unofficial initiative option switched on, players can only spot with units they directly control. When playing online with multiple players (which is currently more common, and makes 'simul-fire' even more common), this can penalise some forces (especially in pre-TAG eras).

Possible suggestion - when Simultaneous Firing is enabled, add in a 'spotting phase' immediately before the firing phase, so that other units on the same team can spot before firing is declared.

**Comment by SimonLandmine** [comment]
(Accidentally saved issue before putting the details in at first. Sorry!)

**Comment by pakfront** [comment]
There is also an issue with individual initiative: a unit later in the initiative mechanically cannot spot for a unit ahead of it in initiative. This is contrary to the rules, which imply any unit with line of sight may spot for any allied unit.
Possible fixes would be to add spotting to the prefire phase, or to make the firer able to designate which units are spotting for them (as in the example in TO (p. 111)

**Comment by pakfront** [comment]
I can take a look at this.
