### ISSUE TITLE
Sarath 'Mech - Lacking Quirk

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#1830]
Per the BattleMech Manual page 83, all 'Mechs with the Compact 'Mech quirk need to also have the Narrow/Low Profile quirk.

As of 47.5, the Sarath currently only has Compact 'Mech, but not Narrow/Low Profile.

**Comment by HammerGS** [comment]
Fixed - https://github.com/MegaMek/megamek/commit/4324d8686c6984fbc3fc9775798ee156bf3b1791
