### ISSUE TITLE
BW UI skins

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#185]
Default
![skineditor](https://cloud.githubusercontent.com/assets/16950832/15203188/c892c460-17c6-11e6-9afd-6b4153335635.png)

Default_chrome
![skineditor1](https://cloud.githubusercontent.com/assets/16950832/15203197/d0eee7ec-17c6-11e6-9b25-a1bb092a996e.png)

Default_theme
![skineditor2](https://cloud.githubusercontent.com/assets/16950832/15203200/d948d52e-17c6-11e6-8ac0-96d04f9859cd.png)

[skins.zip](https://github.com/MegaMek/megamek/files/260569/skins.zip)

**Comment by BLOODWOLF333** [comment]
I dont know how to make a branch or any of that where are the instructions?

**Comment by pheonixstorm** [comment]
@BLOODWOLF333 this should help https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/

**Comment by BLOODWOLF333** [comment]
These are on my branch now

**Comment by pheonixstorm** [comment]
@BLOODWOLF333 don't forget to delete all the other branches from this repo as well as the tagged releases. No sense keeping unwanted data around.

**Comment by BLOODWOLF333** [comment]
I cant delete these closed issues right?  And I dont need that BW_images branch?  I can just make issues for everything on my fork like you do?  Still have to figure out how to commit/push.

**Comment by pheonixstorm** [comment]
No, issues can't be deleted even by the owner of the repo. I only use the issue tracker on my repo to track the work I am doing and ideas from others (such as yours). 

Commits are rather simple to do, but for now if you are on windows use github desktop for all your work. Once you get the hang of it I suggest switching to smartgit

**Comment by BLOODWOLF333** [comment]
I have zero experience and knowledge about this stuff.  Will stick to doing issues like this, sorry if that makes things harder on you all but, I dont know this.
