### ISSUE TITLE
Problem bug with /joinTeam x and /allowTeam Change

### ISSUE THREAD

**Issue by Mekslayer** [MegaMek/megamek#1851]
So we were doing a battle with 8+ players and wanted to add in 4-6 more players..

we did /joinTeam x (x is the team number) and did the /allowTeamChange etc successfully, but found that after the first person that did this, everyone that subsequently tried to join a team in that turn thereafter was unsuccessful, so we found it necessary to have one person join a team per turn MAXIMUM

### Environment

We were using MM 46.1 Stable running on a Ded server ....and I drive a Win 10 laptop
I have no idea what everyone else drives.

I run java ver 8 build 241 (build 1.8.0_241-b07)

### Description
I can do better I think. Here is the game save attached if that is possible.... Though I can't see how to do that yet here.

### Files

**Comment by Mekslayer** [comment]
[FFA_Pickup_4-14.zip](https://github.com/MegaMek/megamek/files/4483152/FFA_Pickup_4-14.zip)

**Comment by Windchild292** [comment]
Closing as the opener has been banned for his behaviour.
