### ISSUE TITLE
ArrayIndexOutOfBoundsException while loading certain mechs and viewing in Selector.

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#1853]
From this forum post.
https://bg.battletech.com/forums/index.php?topic=68772.msg1598976#msg1598976

- arana ara-s-1
- archer arc-1A
- banshee bnc-1e
- battleaxe bkx-1x
- bellerphon bel-1x
- buster series
- carbine con-8 constructionmech
- carbine con-8h haulermech
- cattlemaster ctl-3r3 securitymech
- centurion cn9-h
- chaffee servicemech
- commando com-7s2
- commando com-1a
- copper securitymech cpk-19
- copper securitymech cpk-65
- crossbow crs-x
- crosscut ed-x2 (flamer)
- crosscut ed-x4m loggermech mod
- crosscut ed-x5m loggermech mod
- corsscut ed-x5m-b loggermech
- dasher ii 4
- dervish dv-1s
- dig king rcl-1 miningmech mod
- dig king rcl-1 miningmech (standard)
- dig lord rcl-4m miningmech mod
- diomede d-m3d-3 constructionmech
- diomede d-m3d-4 demolitionmech
- diomede d-m3d-m
- eisenfaust eft-2
- emperor emp-1a

### Environment
What version of MegaMek does your issue apply to?  47.6 in Repo and 47.5
What operating system are you using?  Windows

### Description
some units don't show up in the preview. no stats, no picture.

```
java.lang.ArrayIndexOutOfBoundsException: -1
	at megamek.common.Entity.getArmorType(Entity.java:10560)
	at megamek.common.templates.TROView.addEquipment(TROView.java:428)
	at megamek.common.templates.TROView.addEquipment(TROView.java:406)
	at megamek.common.templates.MechTROView.initModel(MechTROView.java:52)
	at megamek.common.templates.TROView.createView(TROView.java:115)
	at megamek.client.ui.swing.UnitSelectorDialog.refreshUnitView(UnitSelectorDialog.java:697)
	at megamek.client.ui.swing.UnitSelectorDialog.lambda$0(UnitSelectorDialog.java:272)
```

### Files
[megameklog.txt](https://github.com/MegaMek/megamek/files/4488291/megameklog.txt)

**Comment by sartris** [comment]
As the person who raised the issue on the forums, I'd add that only went through A-E to hopefully be able to establish a pattern of where the error(s) is taking place and the rest get sorted out automatically in a fix. If it is necessary to fix each unit individually, I can complete the list for F-Z

**Comment by AlphaSled** [comment]
From what I can see, it has to do with certain specialty armors. 
The ones affected use are all 'Mechs that use Hardened, Commercial, Heavy Industrial, or Primitive armor.

**Comment by sartris** [comment]
yes, that appears to be the case. i'm seeing that non-mech units appear to be unaffected.
