### ISSUE TITLE
Several Units considered Illegal design upon

### ISSUE THREAD

**Issue by CrimsonThunderSB** [MegaMek/megamek#1854]
Megamek 0.47.5

### Description
Upon Selecting some units (primarily tanks, with at least 1 mech), some units are being rejected into the game due to what is considered an illegal design, most likely for incorrectly having components in the wrong area (not custom units).  Some of these vehicles include, but may not limited to: Ground Car, Mackie MSK-7A, Sleipnir APC (both SRM and Standard), Vargr APC (Both LRM and Standard) Centurion CNT-1A, Demon Tank (Both PPC and Royal Variants) Flatbed Truck (AC variant) and several other vehicles that are listed under Level F on the add combat unit on the main menu.  I did notice on the log that I will be providing the errors on some of the designs.  These are not custom units.
[megameklog.txt](https://github.com/MegaMek/megamek/files/4489904/megameklog.txt)

**Comment by HammerGS** [comment]
Ground Car - has never had official stats not counting MW1 so in game its not even remotely built to any rules.

Mackie MSK-7A - The issue with the Mackie is the AC20 is sporting an AC20, 18 years before it's invented that is an issue for CGL to resolve with errata.

Sleipnir APC - Fixed

Vargr APC - Fixed

Centurion CNT-1A - This is a long known issue and CGL needs to Errata the design

Demon Tank (Both PPC and Royal Variants) - Fixed

Flatbed Truck (AC variant) - This unit technically doesn't exist according to the MUL. Fixed it based on where you'd put an AC on a flatbed truck.

Other units to be fixed via entity verifier tool in Megamek.

**Comment by HammerGS** [comment]
Can't find the comment, but the fixable ones are fixed.
