### ISSUE TITLE
Spindrift SecurityMech - Corrected Files

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#1870]
The Spindrift, as of 47.5, was missing Advanced Fire Control and had SRM ammo for its SRT launcher.
Here are the corrected files.

[Spindrift Aquatic SecurityMech SDT-1.zip](https://github.com/MegaMek/megamek/files/4510881/Spindrift.Aquatic.SecurityMech.SDT-1.zip)
[Spindrift Aquatic SecurityMech SDT-1A.zip](https://github.com/MegaMek/megamek/files/4510883/Spindrift.Aquatic.SecurityMech.SDT-1A.zip)

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/131f9ec0eb33845b1ea6bfc31cad545cb47ab98c
