### ISSUE TITLE
Folder name change

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#1879]
Is there any chance of renaming the folder "data/boards/unofficial/DFL" to "data/boards/unofficial/SimonLandmine" - trying to get all of my BT relevant names aligned! Cheers!

**Comment by HammerGS** [comment]
Fixed in - https://github.com/MegaMek/megamek/commit/7ef3ee98f2e14ac52c7c2deb3f1eed4ca3f8e80d
