### ISSUE TITLE
Field Artillery and terrain restrictions (awaiting ruling from CGL)

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/megamek#188]
http://bg.battletech.com/forums/index.php?topic=52721.0

Hope to have something soon. As it is, MM currently has ALL Field Artillery prohibited from all terrain other than clear, pavement, road...

**Comment by pheonixstorm** [comment]
For the most part the Field Artillery work as intended with terrain restriction based on motive type. I am not particularly happy with the answer as it still leaves the wording in TO ambiguous at best.

Will retest this as I believe I removed the prohibition that caused this ticket. Will close if it is fixed.

**Comment by arlith** [comment]
I don't think it's ambiguous, it's just weird.  Why can a mechanized unit suddenly drive into woods once it hitches up that long tom?  Who knows, those are the rules.

**Comment by pheonixstorm** [comment]
That isn't what I find odd, it's this from the TO rules

> Units with Field Artillery (regardless of motive type) are treated as **motorized infantry** with 1 MP

**Comment by arlith** [comment]
Isn't that exactly what I said? Mechanized infantry (which cannot enter light woods), can all of a sudden enter light woods (treated as motorized), when they hitch up a long tom (become a unit with field artillery).  For Battletech rules, it's surprisingly unambiguous, and I guess for Battletech rules it's also *un*surprisingly odd.

**Comment by pheonixstorm** [comment]
Ah, I thought you were referring to the code and not the ruling.
