### ISSUE TITLE
Terrain Camo

### ISSUE THREAD

**Issue by teerayne** [MegaMek/megamek#1880]
### Environment

47.5
Windows
Java 8

### Description
Some terrain camo
![camo](https://user-images.githubusercontent.com/64233510/80228710-60893600-861d-11ea-974c-0f8e971d4f6d.png)

### Files
[Terrain.zip](https://github.com/MegaMek/megamek/files/4529780/Terrain.zip)

**Comment by SimonLandmine** [comment]
RealTree for 'meks! (And Demolishers.)

**Comment by HammerGS** [comment]
Added https://github.com/MegaMek/megamek/commit/313b192ff83c512aacc83e2b2fefb0bb81b0eb35
