### ISSUE TITLE
RFE Change View Game Board to show actual board not Mini-Map

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#1887]
I've seen this request a few times over the years.  Could we make that when you use the view game board option it would show the full map rather then the mini-map.

**Comment by HammerGS** [comment]
@SJuliez Would this be something you'd be willing to look at? It feels like the type of enhancement that's in your wheelhouse.

**Comment by SJuliez** [comment]
Yes I can keep that in mind. This is about the "Select Map" view in the game lobby, right?

**Comment by HammerGS** [comment]
This specifically
![image](https://user-images.githubusercontent.com/13752452/80392358-45f8cc00-886c-11ea-87e3-9c1a97901f32.png)

Instead of showing the mini-map we show the full board like in game.  Thank you for considering this.
