### ISSUE TITLE
Boards of sizes xx:yyy don't load

### ISSUE THREAD

**Issue by SJuliez** [MegaMek/megamek#1898]
Tested with a few versions from current development to MM 0.45:

Boards with a two-digit x size and a three digit y size don't load. The issue is I think with board.indexFor which doesn't work for that situation. There is currently only one such board, SimonLandmine's Valley sample board (30x150).

The whole board loading seems a bit arcane, probably for historical reasons. The coords are unfortunately written in the board file without a separator or enough 000000 to separate them safely. The indexFor function tries to find the real coordinates from the coord string. The board saves the hex in an 1D-array based on those coordinates and retrieves hexes from this but assigns that hex Coords based on count variables (which could be different from the coord read from the file if the file has been altered).

**Comment by SimonLandmine** [comment]
Oops. Sorry!
