### ISSUE TITLE
41.17 : Artillery cannons generate indirect fire artillery images and popup tooltip

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#190]
When artillery cannons hit a hex, they generate the mushroom cloud image used to indicate that the hex has been hit by an indirect fire artillery attack, and the tooltip indicating that the hex is now designated as an auto-hit hex for artillery units. Artillery cannons do not make artillery attacks so they shouldn't be generating the image and popup tooltip for them.

Test save (just fire the long tom cannons anywhere, targetting the hex)

[#battletech.zip](https://github.com/MegaMek/megamek/files/264104/battletech.zip)

**Comment by arlith** [comment]
Looks like it was a case of code in ArtilleryCannonWeaponHandler being copied from ArtilleryWeaponIndirectFireHandler.
