### ISSUE TITLE
Transfering custom pilot images 

### ISSUE THREAD

**Issue by djhuhman** [MegaMek/megamek#1903]
A reminder to check on the ability to allow custom/ preset pilot images set in Mekhq to transfer into megamek and be viewable by players other than the host/ GM. 

Thanks for the hard work!

**Comment by binaryspica** [comment]
Well, isn't it works for now if you shares the portrait already? If you shares the portrait, and put it on the same location, the others are also have the same image on the portrait.

**Comment by Windchild292** [comment]
As per self note on April 30th, this works as intended and was already implemented, just part of the suite I did not have experience with.
