### ISSUE TITLE
LAM and Leaping Optional Rule

### ISSUE THREAD

**Issue by ParsonBoyles** [MegaMek/megamek#1905]
I'm using the stand-alone Megamek 0.47.5 on Windows 10, running a 64 bit Java Version 8 Update 251 build 1.8.0_251-b08

I've been using LAMs lately, and I've noticed a few things. I'll just post one for now, since I'm new to posting bugs.

When the optional Leaping Rules (TacOps Pg 22) are in play, any time the LAM in AirMech mode lowers itself more than 3 elevations, the game thinks it is leaping down a cliff and forces the two piloting skill rolls associated with Leaping.

I don't see anything in the LAM rules about dropping too fast, so I'm assuming it's a bug?

Thanks!

**Comment by neoancient** [comment]
I can't reproduce this. I can fly a LAM in AirMech mode off a level 8 cliff and drop to just above the surface or turn off climb mode and have it drop to just above ground level automatically and never have to roll a PSR. Can you provide a saved game that demonstrates the issue?

**Comment by ParsonBoyles** [comment]
That's interesting.

It turns out that it only pops up when flying off the edge of a building. I tried it with a cliff, as you did, and got the same results.

I've included two save files, I hope I've set them and attached them correctly. 

"LeapingTest-LeapingOn" sets up the conditions before movement, and "LeapingTest-LeapingOn-FromBuilding-EndElevation" shows the results. The behaviour seems to need all of those conditions - dropping from over a building, having the Leaping Option on, and using End Elevation to lower the LAM - to show itself. I've tried changing the variables and it doesn't happen. As long as you have passed over a building in your movement path, and then drop using End Elevation, it triggers the PSR. Unless there's something I'm misunderstanding.

User name "Scott" and no password.

[LeapingTest-LeapingOn.sav.gz](https://github.com/MegaMek/megamek/files/4575925/LeapingTest-LeapingOn.sav.gz)


[LeapingTest-LeapingOn-FromBuilding-EndElevation.sav.gz](https://github.com/MegaMek/megamek/files/4575919/LeapingTest-LeapingOn-FromBuilding-EndElevation.sav.gz)

**Comment by ParsonBoyles** [comment]
I just realized I sent you save files using my custom LAM unit, which are no use to you. :)

Here's the same files with a Phoenix Hawk LAM.

User name "Scott" no password

[LeapingTest-LeapingOn-PH.sav.gz](https://github.com/MegaMek/megamek/files/4576259/LeapingTest-LeapingOn-PH.sav.gz)
[LeapingTest-LeapingOn-FromBuilding-EndElevation-PH.sav.gz]

(https://github.com/MegaMek/megamek/files/4576261/LeapingTest-LeapingOn-FromBuilding-EndElevation-PH.sav.gz)

**Comment by neoancient** [comment]
I tried several times in different ways but couldn't reproduce the issue with either saved game. I'll need detailed steps to reproduce.

**Comment by ParsonBoyles** [comment]
That's so weird.

From the saved game position, it happens for me every time. I've included the save file again just to make sure we're talking about the same one. I've also included three screen caps of the move and the results.

The weird thing is, it never actually asks me to confirm the PSR, as with other moves that require one.

The first screen shot, "LeapingPSRStartingPosition" shows the LAM exactly as it is when the save file is opened. At level 20 elevation above a building, with the Leaping optional rule on. 

![LeapingPSRStartingPosition](https://user-images.githubusercontent.com/64654277/81424593-0ef7a580-910b-11ea-9d33-3fb305f54053.jpg)

The second screen shot, LeapingPSRPlottingMove-EndKeepElevationOff shows the move just before I hit the "Move" button and commit. I've done just two things. I have switched the Climb Mode to End Keep Elevation and moved one hex off the building to the street. The LAM has dropped from elevation 20 to Elevation 1. (If you don't use "End Keep Elevation" it won't trigger the Leaping PSR, as far as I can tell.)

![LeapingPSRPlottingMove-EndKeepElevationOff](https://user-images.githubusercontent.com/64654277/81424654-233ba280-910b-11ea-862a-4c1a4ed4efc3.jpg)
[LeapingTest-LeapingOn-PH.sav.gz]

The third screen shot shows the results, just after I hit "Move," with a crash from leaping damage, but without a warning of the PSR roll. I have seen other times when the game does warn me about the coming PSR roll for leaping damage using LAMs in similar situations, but I can't recreate that with these conditions.

![LeapingPSRResult-WithLeapingDamage](https://user-images.githubusercontent.com/64654277/81425062-bb398c00-910b-11ea-87d8-e9e1500a48da.jpg)

I also get Leaping Damage on my LAMs going over a building, but not dropping immediately over the side. From the same save file (i.e. starting from the same position as the first screen shot) I can move a few hexes away from the building, and then drop using End Keep Elevation and still receive damage from a failed Leaping PSR. Here's a screen shot of that longer move just before I hit "Move"

![LeapingPSR-LongerMove](https://user-images.githubusercontent.com/64654277/81425573-b0cbc200-910c-11ea-8cc9-0764460f5f0d.jpg)

I hope it's not just something that I'm doing weird or wrong? I really thought this would be a slam dunk, bug wise. I hope that helps!

Here's the save game file I've been using for the screenshots.

(https://github.com/MegaMek/megamek/files/4600120/LeapingTest-LeapingOn-PH.sav.gz)

**Comment by neoancient** [comment]
I don't know why it wasn't working for me before, because now I can reproduce it reliably doing exactly what I thought I had been doing. Anyway, thanks for the detailed steps. It turns out that the place where leaping is checked the elevation has been updated but the position hasn't been, so it's checking whether it's airborne using the final elevation of the new hex and the terrain of the old hex. Since the elevation in the new hex is lower than the building, it's treated as not airborne.
