### ISSUE TITLE
Replacement truck_wreck image

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#191]
![truck_wreck](https://cloud.githubusercontent.com/assets/16950832/15265631/66cbf6ae-194f-11e6-930c-9367f2f9eac5.gif)

Old truck_wreck on the left (APC just to show these side by side) and new truck_wreck on the right.

![ingame](https://cloud.githubusercontent.com/assets/16950832/15265632/71ff6e66-194f-11e6-8454-7d402e8735d8.png)

[wrecks.zip](https://github.com/MegaMek/megamek/files/264304/wrecks.zip)

**Comment by pheonixstorm** [comment]
The new image works better as the old wreck image looks too close to the pre-wreck image and if you aren't paying attention or scrolling too quickly it can be easy enough to get the two confused.
