### ISSUE TITLE
Primitive and Primitive Prototype Weapons should have fixed intro dates.

### ISSUE THREAD

**Issue by Windchild292** [MegaMek/megamek#1916]
From Discord: 
The part has not been invented yet, and the ignore date setting is not selected nor is the allow extinct parts setting.

I'd assume this has something to do with the ITechManager::isLegal check.

[The_Cherokee_Legion_-_01.zip](https://github.com/MegaMek/mekhq/files/4575369/The_Cherokee_Legion_-_01.zip)

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/ababd747fb2ebb17af0de552c27998904104ea9f
