### ISSUE TITLE
[Feature Request] Set variable for admins gain "X" xp every "Y" weeks

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#192]
Didn't find anything about this on SF but, was brought up on the bg.battetech forums that even 1 xp every week for admins causes them to level a little bit too quickly.  The ability to set how many weeks it takes to gain that 1 xp for admins I think would be useful.  Just like with how every person can gain X xp every Y months on a roll of Z or higher.

**Comment by arlith** [comment]
This should be a MHQ issue.

**Comment by BLOODWOLF333** [comment]
Aw crap my bad
