### ISSUE TITLE
Feature Request: Customize 'mechs within MegaMek

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#1923]
I was thinking about this while playing with MML.  I think it would be really cool if players could customize 'mechs or re-pod omnimechs right in the game lobby.  The 'mechs would be given a different name and model and saved right on the player's computer.  Then they can be used right away when the game setup is done.  MekHQ already does this, but I'd rather not use MekHQ any time I want to just do a pickup game or experiment with new units or tech.

**Comment by neoancient** [comment]
The three programs have a set hierarchy. MM is the base, MML is dependent on MM, and MekHQ is dependent on both. So you can get MM and MML functionality in MekHQ, but it doesn't work the other direction. You can't create a circular dependency where MM depends on MML and vice versa.
