### ISSUE TITLE
Feature Request:  Remove offboard artillery from play at any time

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#1926]
I run into some scenarios where I run out of ammo with my offboard artillery.  I think it would be great to be able to reduce clicking by allowing removal of offboard artillery from play at any time, especially if they are useless after they run out of ammo.

**Comment by repligator** [comment]
This feature is present in the current version (50.00). Closing. Please feel free to reopen if you feel it has been closed in error.
