### ISSUE TITLE
VSPL Availablility

### ISSUE THREAD

**Issue by UB-JM** [MegaMek/megamek#1927]
### Environment
HQ's MekLab, version 0.47.5
Windows 10

### Description
New Mech, Inner Sphere, Advanced. Year 3145. 
The Small VSPL and Large VSPL are available, while the medium VSPL is experimental technology. 
Yet all of them have the same "Common" date.

I am not absolutely sure this isn't some oversight in the rules.

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/fc2aadaea2cd0d20504e07112731aad331059b92
