### ISSUE TITLE
0.46.1 - Quirk spelling error - "Stablized Weapon" rather than "Stabilized Weapon".

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#1928]
Error found in spelling of weapon quirk "Stabilized Weapon" - appears to be spelt "Stablized Weapon", with an missing "i" in 0.46.1

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/19b75b32936a26065e051843b8ba7289991721f9
