### ISSUE TITLE
Sandblaster SPA requires pilot also have Weapon specialist SPA

### ISSUE THREAD

**Issue by SBBurzmali** [MegaMek/megamek#1930]
### Environment
MegaMek 0.47.6

### Description
In MegaMek 0.47.6, the Sandblaster special piloting ability (SPA) requires that the Weapon specialist SPA also be set in order for the pilot to gain the benefit from Sandblaster. Per the rules, CamOps 79 and CamOps 82, these two SPAs are independent whereas it is not currently possible for a pilot in MegaMek to have the clustering bonus from Sandblaster without also having the to hit bonus from Weapon specialist.

### Files
I've attached a save game with 4 archers facing off with an atlas, archer 1 has both SPAs, archer 2 has the Sandblaster SPA, archer 3 had the Weapon specialist (LRM 20) SPA, and archer 4 has no SPAs. By firing on the atlas with each archer, you can see that only 1 is gaining the benefit of the Sandblaster SPA, while 1 and 3 are gaining the -2 to hit from Weapon specialist. I've also attached a gamelog if required.
[SandblasterBug.sav.gz](https://github.com/MegaMek/megamek/files/4604026/SandblasterBug.sav.gz)
[gamelog.tar.gz](https://github.com/MegaMek/megamek/files/4604033/gamelog.tar.gz)

**Comment by SBBurzmali** [comment]
The issue appears to be in that GUNNERY_WEAPON_SPECIALIST is used in both WeaponAttackAction and WeaponHandle, meaning that the bonuses are always paired. The solution would seem to be to create a new entry in PilotOptions for a Sandblaster specialization, duplicate the setup in CustomMechDialog for the new option and use that new option in place of GUNNERY_WEAPON_SPECIALIST in WeaponHandle.

**Comment by SBBurzmali** [comment]
Here's a patch that corrects the issue. I'm not sure what the best way to submit it is.
[Fix-for-1930-Changing-Sandblaster-SPA-from-a-boolean.tar.gz](https://github.com/MegaMek/megamek/files/4604854/Fix-for-1930-Changing-Sandblaster-SPA-from-a-boolean.tar.gz)

**Comment by HammerGS** [comment]
Can you please review this and submit as a PR. It will create a PR that we can better review and merge.  Thanks.

https://github.com/MegaMek/megamek/wiki/Creating-a-Pull-Request%28PR%29-if-an-outside-contributor

**Comment by SBBurzmali** [comment]
All set. PR created.

**Comment by sixlettervariables** [comment]
I'm not sure MHQ ever implemented Sandblaster, but if it did the code would need to look like Weapon Specialist.
