### ISSUE TITLE
Quirk Updates

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#1931]
Per BattleMech Manual errata, there are a few quirk changes that haven't been implemented.

-The Phoenix Hawk should receive the "Command 'Mech" quirk, and lose the "Jettison-Capable Weapon (Large Laser)" quirk.
-The Battle Hawk should lose the "Bad Reputation (Inner Sphere) quirk.
-The Shadow Hawk should receive the "Rugged (1)" quirk.

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/19b75b32936a26065e051843b8ba7289991721f9
