### ISSUE TITLE
ProtoMech Torso Critical Hit Issues - Save Files

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#1934]
As requested by Hammer, here are two save files where I tested whether ProtoMechs can get a critical hit on a Torso Weapon or not.

It appears that for nearly every design, Torso criticals either act as a generic critical hit (and do not strike a weapon), or are said to hit Weapon C (which is not used by nearly any canon designs).

The Hobgoblin 2 is the sole exception, most likely due to the fact that all three of its Torso locations have critical items in them. However, no matter which weapon (A/B/C) the critical hits, the AP Gauss Rifles are never "critted" (nor do they explode), although the Magnetic Clamps are disabled as they should be.

The Hobgoblin 2 also shows a secondary issue - once one of the critical hits somehow "registers", all of the ammunition for the ProtoMech's weapons is destroyed (the AP Gauss ammo, in this case), which should not happen.

[UltraHeavy Test.sav.gz](https://github.com/MegaMek/megamek/files/4605112/UltraHeavy.Test.sav.gz)
[Hobgoblin + Centaur Test.gz](https://github.com/MegaMek/megamek/files/4605113/Hobgoblin.%2B.Centaur.Test.gz)

**Comment by neoancient** [comment]
I suspected the lack of weapon damage from torso crits based on a logic error I found while working on expanded protomech record sheets. I saw some weird stuff with ammo showing up as torso weapons when I experimented with a quick fix.
