### ISSUE TITLE
Request:  Mass Individual Camo

### ISSUE THREAD

**Issue by VictorMorson** [MegaMek/megamek#194]
I am unsure if others have an equally rough experience, but currently you cannot assign Individual Camo to more than one unit at a time.  This makes games where you are going lances with coordinated color schemes somewhat tedious to setup (or other such scenarios) as you must do each change manually.

The suggestion is for Individual Camo to be applied to all highlighted units, cutting out several minutes of work per company designed.

Steps to repro:
1) Put several mechs
2) Highlight at least 2 mechs
3) Change the Individual Camo
4) Note that it only will change one mech per camo selection.

**Comment by mkerensky** [comment]
I'll heartily second this request!  In playing through the Jihad Chaos campaigns, I run a lot of games with multiple allied units assigned to a single player and like to have the members of each unit wear their canon camo schemes. 

It would also be nice to set the camo scheme in an MUL file for use with the 'reinforce from MUL' option.
