### ISSUE TITLE
Extracted file, does not include .exe

### ISSUE THREAD

**Issue by MrMagolor** [MegaMek/megamek#1940]
### Environment
What version of MegaMek does your issue apply to?  Note whether it is the stand alone MegaMek or HQ's MegaMek.
Stand-alone
What operating system are you using?  Windows, Mac, or Linux?
Windows 10
What java version are you using?  If unsure it will state your java version at the top of the megameklog.txt file.
Version 8, Update 241

### Description
Describe the issue and provide screenshots ingame if able.
The README file says there is a .exe file to run to start the game, but I could not find one, even looking through the entire game with a search.
Trying the "Startup.sh" file only ends with an error that I can barely see before it disappears: ~~"Too many arguments" or something.~~
I was able to see the error properly, it says: "Unable to find MegaMek JAR file"

**Comment by Windchild292** [comment]
Did you download the windows distribution?

**Comment by MrMagolor** [comment]
I downloaded the github repository here. Unless "windows distribution" refers to another thing?

**Comment by Windchild292** [comment]
Ah, you downloaded the direct code files. You can download the releases here:
https://megamek.org/downloads.html

**Comment by MrMagolor** [comment]
oh. woops. closing issue
