### ISSUE TITLE
Colour options organisation - 'Shock and Awe' camo patterns

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#1941]
v0.46.1 (and probably others)

In the 'Standard Camouflage' section of the colour/camo picker ...

Under the 'Misc' section is a camo pattern called "Shock and Awe".
Under the 'Self Defence' section are several "Self Defence" patterns ... and two variants of the "Shock and Awe" pattern.

Should "Shock and Awe" have it's own section under 'Standard Camouflage', or at least should all variants be under the same heading?

**Comment by HammerGS** [comment]
Makes sense but not sure when I'll have time to tweak it.  If you want to reorganize it and zip up a fix here I'll get it added.

**Comment by SimonLandmine** [comment]
Here's a re-organize of the 'Standard Camouflage' folder within /data/images/camo/, with 'Shock And Awe' moved to it's own subfolder. Is this what you need?

[Standard Camouflage.zip](https://github.com/MegaMek/megamek/files/4615739/Standard.Camouflage.zip)

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/131f9ec0eb33845b1ea6bfc31cad545cb47ab98c
