### ISSUE TITLE
Princess seems to lock up or grab memory

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/megamek#1942]
win 10
47.6 (through MHQ)

running a large space battle, about half way through after casualties have been taken.  windows reported memory usage spikes to the maximum allocated and the game locks up and droes not progress a single units turn for an hour or more.  eventually it completes all actions over ~5-10 minutes time, and interface is jittery and laggy.  process starts over at the start of each new turn.

attached below is the JvisualVM snapshots of 2 instances of memory before the lockup (1&2) and 1 during the lockup (3)

issue might or might not be related to the memory, that is just a current best guess.  issue might be related to large battle size, or space battles

[snapshot.zip](https://github.com/MegaMek/megamek/files/4613000/snapshot.zip)

**Comment by sixlettervariables** [comment]
Looks like we're hanging onto MoveSteps perhaps longer than we need to? Interesting that the top three bytes are:
1. Object[] (5Gb)
2. Integer (1Gb)
3. MoveStep (0.5Gb)

**Comment by NickAragua** [comment]
Out of curiosity, are you using newtonian physics or basic spaceflight rules?

**Comment by bczretribution** [comment]
basic spaceflight

**Comment by bczretribution** [comment]
here is another snapshot.  left for work with it "thinking" came back to it completely locked up.  restarted from autosave and this is from only a few minutes after loading.
[snapshot new.zip](https://github.com/MegaMek/megamek/files/4615319/snapshot.new.zip)

**Comment by sixlettervariables** [comment]
One improvement would be to not automatically instantiate `launched`. I can't tell if that's used very often, but I don't think it is.

**Comment by NickAragua** [comment]
I guess the other useful thing would be a save game. My computer's pretty beefy so I never get into "takes several minutes" situations (maybe 20-30 seconds at most on really big maps with super fast units).

**Comment by bczretribution** [comment]
i have an i7-8700K, and have currently allocated 12gb of 64gb of available ram.  this is not a question of available resources
[autosave.sav.zip](https://github.com/MegaMek/megamek/files/4625611/autosave.sav.zip)

**Comment by NickAragua** [comment]
Thanks for the save, it always helps to have a "working example".

**Comment by NickAragua** [comment]
lol, looks like the problem is with all the ejected pilots, it generates endlessly long paths for them for some reason.

**Comment by bczretribution** [comment]
that explains why it doesn't become an issue until several turns in

**Comment by NickAragua** [comment]
Fixed it for next release. 

Suggested workaround for now: call a cease fire for a turn by kicking the bot, exterminate all the ejected pilots. Re-invite the bot.
