### ISSUE TITLE
0.47.7 Snapshot 2020-05-11 - Tile displacement on theme change

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#1946]
0.47.7 Snapshot from 2020-05-11

I was testing the new Building Fluff functionality on a pre-existing 30x15 map (The Valley - Town map (as it had a variety of buildings)).

Using the 'Change Tileset Theme' option in the map editor worked without any problem.
Using the 'Change Tileset Theme' option in battle, however, caused the previously-seen tile displacement issue.

Is there a difference between the application of the the option in the map editor and in 'battle mode' which might cause this?

**Comment by neoancient** [comment]
Duplicate of #1645

**Comment by SimonLandmine** [comment]
Ah! Sorry!

**Comment by neoancient** [comment]
Not a problem. It's not always clear what's related. I added the link to help if we ever need to look into the history.
