### ISSUE TITLE
Tracer ammo 

### ISSUE THREAD

**Issue by Muddball** [MegaMek/megamek#1955]
I do not think that tracer ammo is removing 1 damage when normal autocannons are firing in burst mode when Direct blow is an option that is turned on. Either it fails to remove the 1 point of damage or direct blow is adding both a bonus to the cluster hit AND adding a point of damage.

Weapons fire for Shootist ST-8A (Thunder Riders)
    AC/20 (Tracer  ammo) at Enforcer ENF-4R (Federated Commonwealth); needs 7, rolls 12 :  - Direct Blow - 2 shot(s) hit (w/ +3 bonus).

        Enforcer ENF-4R (Federated Commonwealth) takes 20 damage to RA.
            Armor destroyed.
             2 Internal Structure remaining.
            Critical hit on RA. Roll is (5+1) = 6; no effect.

        Enforcer ENF-4R (Federated Commonwealth) takes 20 damage to CT.
            3 Armor remaining.

**Comment by HammerGS** [comment]
It's working just not well documented.  Per TacOps pg 81

> For every MoS of 3, increase the Damage Value of the attack by 1;

So roll of 12 versus 7 (MOS of 3), would be 21 points of damage.  The AC are doing 20 points so the -1 damage for tracer included.

**Comment by Muddball** [comment]
Correct, however I was firing the autocannon as burst. Which to my understanding increases the ShotstoHit table, not the raw damage. So it should be either one\two hits of 19 damage, right?
