### ISSUE TITLE
RAT - OTP: REVIVAL Trials

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#1957]
The full RATs for OTP: REVIVAL.

[(3048) OPT - Revival Trials.zip](https://github.com/MegaMek/megamek/files/4641211/3048.OPT.-.Revival.Trials.zip)

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/131f9ec0eb33845b1ea6bfc31cad545cb47ab98c
