### ISSUE TITLE
VTOL Starting Elevation

### ISSUE THREAD

**Issue by Piratikal** [MegaMek/megamek#1965]
Princess starts VTOLS at 1 elevation usually, which often leads to them crashing into things when the pilot skids. Bot elevation can be changed manually in the lobby by the player but I was wondering if it would be possible to set Princess default elevation for VTOLs higher automatically.

**Comment by binaryspica** [comment]
It would be possible to set the default elevations of **all the VTOLs**, though, so perhaps it would be easier than just set it for the bots. Also we don't need to set the elevation of each individual VTOLs on the lobby each times either.

**Comment by NickAragua** [comment]
For the next release, the bot will have the ability to adjust VTOL height as necessary to account for terrain obstacles.
