### ISSUE TITLE
PortraitChoiceDialog: Initial Portraits from Zipped File Load as White Boxes

### ISSUE THREAD

**Issue by Windchild292** [MegaMek/megamek#1968]
Portraits load as white boxes initially when loading from a zipped folder in the PortraitChoiceDialog. However, once the line is selected the image becomes visible, and there are some other inconsistencies with how they display on load (but are still usable)
![image](https://user-images.githubusercontent.com/39067288/82479349-40c02300-9aa0-11ea-99e9-1be20de5444b.png)

**Comment by SJuliez** [comment]
I had not thought about testing ZIP files and while they work with the new PortraitChooser, it's a little wonky. So this still an issue.

**Comment by Windchild292** [comment]
It appears like the issue is located in ItemFileFactory::createZippedImage, although that does assume that the ZipEntry and ZipFile being loaded are correct (which I believe to be the case)
