### ISSUE TITLE
No ammo on warships

### ISSUE THREAD

**Issue by chrisbfisher** [MegaMek/megamek#1976]
### Environment
What version of MegaMek does your issue apply to?  Megamek .46, MekHQ

What operating system are you using?  Windows 10
What java version are you using?  IJava version 1.8.0_221

### Description
Warships don't have ammo. NavalAC has no ammo. Missile launchers have no ammo. I managed to get this to work once by creating a MekHQ campaign and launching the warship from that. However, as soon as I added another unit to the game (as an opponent), all the warship ammo went away. I can't configure the ship and add ammo either. 

![Capture](https://user-images.githubusercontent.com/8221993/82849241-f9cd9580-9ec4-11ea-8396-c71ba24dd404.PNG)
[megameklog.txt](https://github.com/MegaMek/megamek/files/4679275/megameklog.txt)

**Comment by HammerGS** [comment]
I can't duplicate this is 46.0 or 46.1

![image](https://user-images.githubusercontent.com/13752452/82850131-4c548500-9eb8-11ea-96b5-1ef38ea9d9fe.png)

Are you bringing forward an older version of the programs?

**Comment by chrisbfisher** [comment]
Nope. It's fully .46

**Comment by HammerGS** [comment]
Is that a fresh install of .46? Are you installing over an older folder?

**Comment by chrisbfisher** [comment]
It's a clean install of .46. It seems that if you have any other unit
loaded besides the warship, you loose all your ammo. I closed out Megamek
and reloaded then tried to pull up a new warship. No ammo. I got ammo on
the ship the first time I loaded a freshly downloaded copy of Megamek.
That's the only time it worked. Once I added a second unit to the game, the
ammo went away. After that, I can't load any ships that have ammo.

**Comment by chrisbfisher** [comment]
Here's a screenshot from the fresh install. It's 46.1. When I first started
this I got the ammo, but haven't since. I just pulled up one ship and I got
nothin.

[image: image.png]

**Comment by HammerGS** [comment]
I can't seem to duplicate this.  Can you give me a step by step to recreate.  Thx.

**Comment by chrisbfisher** [comment]
Load Megamek.
Start a new game.
Load a warship.
No ammo.

It's that simple. It worked exactly once. Then I loaded other units for the
battle and the ammo disappeared and hasn't returned.

**Comment by HammerGS** [comment]
What warship did you load? Any warship I load has ammo.

what "other units"?

Did you load the warship then check the ammo, then add other units? Did you load the warship, then the other units then check the ammo?

Can you attach your gameoptions.xml from the \mmconf folder. You'll need to zip it.
 
I'm going to need very specific steps to recreate this.

**Comment by chrisbfisher** [comment]
I loaded the warship. I've used Aegis and Vincents, but just randomly
pulling new ships they all come without ammo, so I assume this applies to
all of them. I've attached a game with just a single Aegis. It doesn't have
any ammo. It's the only ship I loaded.

By "other units" I many any other unit, dropship, aerofighter, warship, you
name it. Anything. Not it seems I don't need another unit to cause the
error.

I've already given you the very specific directions to recreate this. Start
a game. Load a warship. Warship has no ammo. It's that simple. The error is
immediate and consistent. There also is no way to add ammo.

Can you send me a copy of the Megamek version you're using? I'm curious if
mine is corrupted or something.

**Comment by chrisbfisher** [comment]
I just downloaded Megamek .46.1 again and overwrote the full version I got
with the HQ version full download. Didn't fix the problem. I then went in
and cleared out all the options for aerospace and most of the other
options. I'm working on very minimal options now and advanced tech levels.
I'm attaching the options files. I have ammo in the ships now. I have three
warships loaded and they all have ammo. I suspect one of the options
somewhere is causing the issue.

**Comment by AlphaSled** [comment]
I was able to replicate on 47.6, and figured out what is most likely OP's problem.

Chris, under Game Settings/Allowed Units and Equipment/Year the game takes place in, check the date that's listed. If it's between 2956 and 3050, the Warship won't carry any ammo as Megamek lists the ammo as extinct during that time frame. If the date is set at 2955 or earlier, or 3051 or later, ammo should load normally without issue.

**Comment by NickAragua** [comment]
This is likely fixed with PR #2734
