### ISSUE TITLE
Long tom cannons cannot switch to indirect firing mode

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#198]
They should be able to fire indirectly like LRMs, but they cannot switch to indirect firing mode via the mode button. Other artillery cannons probably have the same issue.

**Comment by kutagh** [comment]
Tried it locally, as far as I am aware, the (IS at least) Long Tom Cannon is by default already in Indirect Fire mode (tested with no LoS to enemy unit and another unit spotting for indirect fire, MegaMek shows +1 indirect fire for all attacks with Long Tom Cannon and allows targetting & firing at said unit according to Indirect Fire rules).

**Comment by arlith** [comment]
While this is an issue, it's been an issue for a while, and isn't game breaking.  I'm going to defer this until post-stable.
