### ISSUE TITLE
Hachiman incorrectly considered advanced.

### ISSUE THREAD

**Issue by Logajam** [MegaMek/megamek#1982]
### Environment
Mm 47.6

### Description
The Hachiman fire support tank is concidered an advanced unit by MM.   Its only a standard unit.  Minor correction needed in the master files.

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/131f9ec0eb33845b1ea6bfc31cad545cb47ab98c
