### ISSUE TITLE
Implement SirMegaV Buildings and Saxarba Roads for hq_saxarba

### ISSUE THREAD

**Issue by Windchild292** [MegaMek/megamek#1983]
This is a RFE to implement the changes from #1843 and #1878 for the hq_saxarba tileset, not just the saxarba tileset.

**Comment by Windchild292** [comment]
@SJuliez 
Would you be open to implementing this, especially given your authorship of the two PRs that make up this RFE?

**Comment by SJuliez** [comment]
Sure.
