### ISSUE TITLE
41.17 : Ejected vehicle crews are considered to be killed

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#199]
Not sure if this is a megamek or mekhq issue, but i saw a previous ticket about ejected vehicle crews here : https://github.com/MegaMek/megamek/issues/31

I had forced withdrawal on and after ejecting a von luckner, the crew was considered killed in mekHQ. Not sure if thats because megamek is telling mekhq that the crew is dead or mekhq is reading the data incorrectly.

Player name was "My Campaign"

[#battletech.zip](https://github.com/MegaMek/megamek/files/266382/battletech.zip)

**Comment by SirMegaV** [comment]
I made a report in SF on this issue. Ejected vees crews shouldn't be made
dead automatically.

**Comment by arlith** [comment]
This issue was fixed in c753c1, and was tracked via [SF MHQ Bug #815](https://sourceforge.net/p/mekhq/bugs/815/).
