### ISSUE TITLE
Feature Request: Implement Bullet Shields

### ISSUE THREAD

**Issue by foij00** [MegaMek/megamek#1993]
### Description
Requesting the implementation (or at least an equipment placeholder) for riot shields in MM and MMLab, so that Heavy Riot Infantry can be built.
Handbook:House Kurita, Page 189 (as part of Heavy Riot Infantry).
Bullet shields as MW scale equipment is described in Lostech, Page 50 (as riot shield).

**Comment by neoancient** [comment]
There are no game statistics provided. Adding it as a placeholder that has no effect would result in a maximum of 7 points of damage instead of the 10 shown in the source. Ignoring the riot shield will give them the correct stats.
