### ISSUE TITLE
 Minor labeling bug - Cluster Master should be labeled Unofficial not atow

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/megamek#20]
Commit 0dcc5cd00e668b92d98487e0238ba44478647190 correctly shows that cluster master was unofficial while the addition of the cluster master text into messages.properties here 24a4dab577b67e8326a7b85af011b7d5c9878400

I have a fix with 2a915909982b6e73f9ac957ecc9b937fc525a262 that you can cherry pick during your next update.

**Comment by arlith** [comment]
Sorry, but your message was kind of confusing.  You're saying that the commit message in 0dcc5cd indicates that cluster master should be unofficial, but then when the i18n entries were added in 24a4dab they were added as (aToW).  I guess, reading your message I had assumed that I was looking for a file change in 0dcc5cd.

**Comment by arlith** [comment]
Fixed in 2f4efa6.
