### ISSUE TITLE
41.17 : "Darken outside field of view" doesnt appear to work in firing phase

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#200]
At least, not when non-standard lighting conditions are involved. See the screenshot, all hexes look the same color even though the Thor F is in a hex that is not in the LRM carrier's FOV.

![megamek](https://cloud.githubusercontent.com/assets/1191378/15320689/49179914-1c75-11e6-8873-8ab4d1e96983.jpg)

[#battletech.zip](https://github.com/MegaMek/megamek/files/268022/battletech.zip)

**Comment by arlith** [comment]
The darkening and highlighting FoV options are designed to not display during the firing phase.  The firing solutions basically give you the same information, and don't affect the view nearly as much.
