### ISSUE TITLE
Data query: 0.46.1 - Crockett CRK-5003-1b availability

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#2000]
According to the MUL, the CRK-5003-1b was introduced in 2752, and is only available in the Star League era, being extinct by the Clan Invasion era (but with no data shown for Succession Wars).

In MM, it is Advanced 2752-3044, Standard 3045+, and only extinct between 2850-3040. A user on one of the Discord channels queried this availability.

**Comment by isturdy** [comment]
I've noticed this with a number of other SLDF Royal/RWR variants. Some the MUL lists as kept in Clan (GRF-2N, CRD-2R) or Comstar (EMP-6A) usage, but the CRK-5003-1b, AEM-04, RMP-4G, etc. seem to have been extinct by the time their technology was rediscovered.

**Comment by neoancient** [comment]
The data in MM is based on the availability of the components. It has nothing to do with whether the unit shows up according to the fluff, but what rules level it is during any given year when using the era-based tech level option.

**Comment by SimonLandmine** [comment]
Ah! Thanks!

**Comment by HammerGS** [comment]
Extinct to the Inner Sphere.  But who knows what Comstar had sitting in it's collection of Castle Brian's. Or what was accidentally shipped to the Draconis Combine. Or what Kerensky dragged to Clan Space.
