### ISSUE TITLE
Spikes - Not working correctly

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#2004]
The rules for Spikes may be found in Tactical Operations, page 291.
Version 47.6

First off, Megamek currently only has the Spikes roll to break whenever the location mounting them is hit by a physical attack. However, there should be a break chance every time the location that mounts them suffers damage from any source at all.

Secondly, Megamek currently has Spikes only deal +2 damage to their target during a charge if the Spikes on a location damaged by the charge are "impacted" - legs included. TacOps states here that it should be an automatic +2 damage for every cluster of Spikes on a Torso location the attacker has.

Thirdly, Megamek does not have Spikes reduce physical damage to the attacker during a charge. Here TacOps says that 4 points of damage should be absorbed as per normal on any location that suffers damage but mounts Spikes.

Attached is an autosave that shows all three problems in effect.
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/4776648/autosave.sav.gz)

**Comment by neoancient** [comment]
Additional rules clarifications for spikes here: https://bg.battletech.com/forums/index.php?topic=47190.msg1088629#msg1088629
