### ISSUE TITLE
Mechwarrior in Water cannot flee the board.

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#2005]
Witnessed in a Game.  MW ejects and lands in water next to the board edge. Mechwarrior is stuck in water and can't flee board.

![image](https://user-images.githubusercontent.com/13752452/84603024-85916c80-ae48-11ea-99fc-fb5962293567.png)

### Environment
What version of MegaMek does your issue apply to?  47.6
What operating system are you using?  Windows

**Comment by sixlettervariables** [comment]
I take it that edge is not their home edge?

**Comment by HammerGS** [comment]
No, basically they ejected landed in the water and the pilot couldn't move or exit the board. My first thought is pilots don't have the ability to move in water like Scuba units.

**Comment by NickAragua** [comment]
Rules-wise, infantry are not allowed to go into water (per TO), and mechwarriors/vehicle crews are basically treated as infantry, so it probably just follows existing logic there. 

I guess the question would be how do we want to handle mechwarriors that inadvertently wind up in prohibited terrain? Instant death because nobody knows how to swim without specialized equipment? Something less obnoxious?

**Comment by sixlettervariables** [comment]
It auto generates a Flee move step, but only on their home edge. There is other logic checking for the absence of legal move steps that will generate another flee step. If a flee step isn't generated then the path finder is to blame, if one is it's the ranker.

**Comment by NickAragua** [comment]
We're not talking about a bot.

**Comment by sixlettervariables** [comment]
Test setup.

[EjectionTest.board.zip](https://github.com/MegaMek/megamek/files/4808882/EjectionTest.board.zip)
[water-edge-eject.sav.gz](https://github.com/MegaMek/megamek/files/4808881/water-edge-eject.sav.gz)

**Comment by sixlettervariables** [comment]
The following prohibits the flee action:
https://github.com/MegaMek/megamek/blob/131f9ec0eb33845b1ea6bfc31cad545cb47ab98c/megamek/src/megamek/common/MoveStep.java#L3475-L3491
