### ISSUE TITLE
Era Digest - Dark Age RATs

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#2006]
As title. This is my first time making an RAT that references other RATs, but I tested things out and everything seems to work fine.

[(3132-3135) Era Digest - Dark Age.zip](https://github.com/MegaMek/megamek/files/4777149/3132-3135.Era.Digest.-.Dark.Age.zip)

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/131f9ec0eb33845b1ea6bfc31cad545cb47ab98c
