### ISSUE TITLE
Unit size based Battle Armor unit image?

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megamek#2035]
### Environment
Ver 0.47.7

### Description
For now, the unit image is only determined by the unit's name. But it makes impossible to note 5 or 6 armors on a unit in the most times, if you make a custom unit. And, even on the unit that has both 4 and 6 armors, it only accepts some kind of name - such as adding (WOB) or (Level 1).

But isn't it better to refer the unit's size, rather than name?

**Comment by repligator** [comment]
@binaryspica 
Could you please clarify the request? As of 2022 all of the Battle Armor has been renamed to match the MUL, (sqd4), (sqd5), (sqd6). All Battle Armor is also available in all three squad sizes, with the number depicted in the image matching the squad size. Does this fulfill your request?

**Comment by HammerGS** [comment]
Actually I'm going to close this out, as we've made the decision to follow the MUL for naming conventions.

**Comment by binaryspica** [comment]
> @binaryspica Could you please clarify the request? As of 2022 all of the Battle Armor has been renamed to match the MUL, (sqd4), (sqd5), (sqd6). All Battle Armor is also available in all three squad sizes, with the number depicted in the image matching the squad size. Does this fulfill your request?

No, it wasn't the request. The request was put the actual numbers of BA currently alive on the field, so having 4/5/6 members by default isn't related with this.
