### ISSUE TITLE
Omni-Corvis .mtfs

### ISSUE THREAD

**Issue by AskAgain** [MegaMek/megamek#2036]
46.1 stable and 47.7 developmental
Windows
Java version 1.8.0_251

Omni-Corvis .mtfs in the mechfiles were created without designating the designs as an Omni. Minor but as such you could not mount Battle Armor on them.

Made the changes and attaching .mtfs to save the legwork assuming they pass muster. Note, had to allocate the two extra DHS as (Pod) and remove the lower arm and hand actuator as they are incompatible with arm-mounted ACs on Omni from the Prime variant.

[Omni-Corvis.zip](https://github.com/MegaMek/megamek/files/4850443/Omni-Corvis.zip)

**Comment by AskAgain** [comment]
One other note, the production year seems wrong. First Hell's Horses Omnimech was the Nova in 2870 and the Omni-Corvis itself seems like it was supposed to be a cutting edge design as a proto-Stormcrow rolled out just in time for the Battle of Tokasha in 2921. Curious where the 2864 date comes from.

**Comment by HammerGS** [comment]
Thanks, the dates for the Omni-Corvis were provided when I developed the RS for TP:Tokasha. The pending TRO:Golden Century will we fixing and updating a few things.

**Comment by AskAgain** [comment]
Welcome sir. Happy to help in some small way. As always, thank you all for your efforts.

**Comment by HammerGS** [comment]
The OTP Tokasha units have been removed but leaving this open pending the MUL updating with correct dates.
https://github.com/MegaMek/megamek/commit/773cbaecd0db68b139aa4ab5b2387f83faad7b48

**Comment by HammerGS** [comment]
Fixed as part of these series of commits https://github.com/MegaMek/megamek/commit/327d2d022f4b39293845d66760b7f3f7062a480e , https://github.com/MegaMek/megamek/commit/6cefd9790bcb825af394704919a21d1b1ee341fd , https://github.com/MegaMek/megamek/commit/f74e7da52c61d439866e7943d8aec5275afb68ca
