### ISSUE TITLE
Attn Hammer. New additions to TheJungle for Kaji maps.

### ISSUE THREAD

**Issue by AskAgain** [MegaMek/megamek#2037]
Three more 30x17s to go north of the other 9 maps for TheJungle. Added the outskirts of a city. Mahalo.

[TheNorthNorthernJungle.zip](https://github.com/MegaMek/megamek/files/4850486/TheNorthNorthernJungle.zip)

![TheJungle](https://user-images.githubusercontent.com/50790862/86104994-7b7f8880-ba5a-11ea-8467-ac2321cf9e59.png)

**Comment by HammerGS** [comment]
Added here - https://github.com/MegaMek/megamek/commit/0f155742d0c249809778d9ea692fa02999e8f97c
