### ISSUE TITLE
New Texture pack (Tileset) for the megamek client

### ISSUE THREAD

**Issue by Ahne02** [MegaMek/megamek#2054]
### Environment
I use the Version 0.7.0.2 of megamek.

### Description
I have created a tileset (texture pack) for megamek client. 

Examples how it looks ingame:
https://imgur.com/a/7UsWck2

### Files

https://www.file-upload.net/download-14180402/AhnesTexturePack.rar.html

The "LargeTextures" tileset file is already updated to replace the current large texture tileset in the megamek client with all the textures used in this texture pack. It can easily changed by name and than made accesible in the client graphics tilset options.

To test the pack just drag/drop the ../Ahne folder into ..data/images/hexes and also the largeTextures.Tileset file in the the same place.

Ingame just change to LargeTextures tileset in the client graphics settings. Later it should be an own selectable from the available options.

If you also want to use the updated roof textures you have to seperately copy/replace existing ones in their folders, dont know why i cant load them from my own largeTextures tileset file. 

 iLarge_Textures_hardened/"files" -> ..data/images/hexes/hardened/
 iLarge_Textures_light/"files" -> ..data/images/hexes/light/
 iLarge_Textures_heavy/"files" -> ..data/images/hexes/heavy/
 iLarge_Textures_megaart/"files" -> ..data/images/hexes/megaart/

(there are still some roof textures not 100% alligned but it works pretty fine)

greetings
Ahne

**Comment by HammerGS** [comment]
Added here - https://github.com/MegaMek/megamek/commit/ffc38b71741b7021d7152b0f81ef740f5b3f33a3
