### ISSUE TITLE
Advanced search for engines and quirks

### ISSUE THREAD

**Issue by StuartSlaugh** [MegaMek/megamek#2059]
Would it be possible to have an option in the advanced search of the purchase unit window to filter by engine types 
(fusion, XL, light) and be able to filter positively or negatively for quriks.  by that I mean I would like to be able to look for a mech with Command Mech, or avoid all mechs with No Torso Twist.

**Comment by HammerGS** [comment]
These are included in this - https://github.com/MegaMek/megamek/issues/1953
