### ISSUE TITLE
Locust has extra quirks

### ISSUE THREAD

**Issue by Rageoholic** [MegaMek/megamek#2064]
In MekHQ 46.1 the Locust appears to  have the cramped cockpit and No torso twist quirks. However these are not part of the Locust's quirks in either the BMM or the errata.

**Comment by HammerGS** [comment]
Going to need a clarification from Xotl on this (which I've asked about.)
We are showing the quirks from 1st SW Book but BMM doesn't.

**Comment by HammerGS** [comment]
Fixed as part of these series of commits https://github.com/MegaMek/megamek/commit/327d2d022f4b39293845d66760b7f3f7062a480e , https://github.com/MegaMek/megamek/commit/6cefd9790bcb825af394704919a21d1b1ee341fd , https://github.com/MegaMek/megamek/commit/f74e7da52c61d439866e7943d8aec5275afb68ca
