### ISSUE TITLE
Changing year or tech level for DropShip sometimes removes anti-missile systems from assigned bays

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megamek#2066]
Using MML 0.47.7 on OS X with Java build 1.8.0_51-b16, sometimes when I change the year or reduce the tech level of a DropShip, all of its AMS bays disappear. The anti-missile systems and ammo are placed on the list of unallocated equipment. I discovered this on a custom design, and both reducing the tech level from unofficial to experimental or _increasing_ the year from 3056 to 3070 would unmount all AMS. Nothing on the design required an unofficial tech level.

I reset everything and added one AMS to the nose of a brand new aerodyne. Setting the year from 3145 back to 3056 causes it, as does increasing the year to 3060. Setting the tech level to unofficial from standard doesn't change anything, but setting it to experimental from unofficial does.

Meanwhile, trying similar things with the Castrum does not cause the bug until I set the year back to 3070 or before. Nothing else changes in 3070.

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/8adb6f89149e7e7548258eddd79d33c683926a8b
