### ISSUE TITLE
Reactive armor not working against certain weapon types

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#2074]
Version 0.47.7

Reactive armor is not reducing damage from 'mech or battle armor mortars when mounted on 'mechs or vehicles.

When mounted on battle armor, reactive armor is not reducing damage against standard artillery, 'mech/battle armor mortars, or artillery cannons.

Relevant rules may be found on page 282 of Tactical Operations.
Attached is a game file where most of these were tested.
[explosive test.sav.gz](https://github.com/MegaMek/megamek/files/4957602/explosive.test.sav.gz)

**Comment by mhjacks** [comment]
Confirmed; it doesn't seem to be working properly for Arrow IV guided munitions either
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/5011456/autosave.sav.gz)

**Comment by NickAragua** [comment]
Note that Thumper, Sniper, Long Tom and Arrow IV are all listed as AE in TacOps, so those will not be affected by reactive armor.

**Comment by AlphaSled** [comment]
I don't see anything about Reactive armor only affecting "M" attacks. The write-up on Reactive rules does state that "Reactive Armor reduces all damage from explosive-type weapons such as missiles, mortars and artillery weapons by half..."

So from my understanding, the Thumper, Sniper, etc. should have their damage cut in half by Reactive armor.
