### ISSUE TITLE
Aerospace and Narc Ammo usage.

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#2081]
From this forum post.
https://bg.battletech.com/forums/index.php?topic=70289.msg1634087#msg1634087

Aerospace units should be able to mount NARC and NARC ammo, but per TW pg 238 
_NARC and TAG: Neither TAG nor NARC play a role in aerospace combat, and they confer no advantage to the user when targeting his opponents. Aerospace units may use such equipment against non-aerospace units._

Currently you can't equip NARC ammo to an Aero in either MML or MM. Looks like the ammo gives no bonus versus aerospace units but does against ground units.

### Environment
What version of MegaMek does your issue apply to?  47.7
What operating system are you using?  Windows

### Files
![image](https://user-images.githubusercontent.com/13752452/88319718-c8f9b900-ccd9-11ea-8ece-1eb81e994b42.png)

**Comment by binaryspica** [comment]
>**Special Munitions**: Aerospace units may not use special munitions, with the exception of Artemis-equipped missiles and LB-X autocannons (in which they always use Cluster ammunition).
>238. Total Warfare.

It is correct that it is not available.  Aerospace units are not allowed to use NARC-Capable missiles. Only NARC Pods are allowed, for they are still allowed to use NARC Pods(to assists ground force).

**Comment by HammerGS** [comment]
I've open a rules clarification on this, as the reference to using Narc missiles against ground targets.

**Comment by HammerGS** [comment]
Closing as invalid.
