### ISSUE TITLE
GUI Redraw issue on Widescreen

### ISSUE THREAD

**Issue by cam-smith** [MegaMek/megamek#2086]
### Environment
47.7
Windows 10
Phillips PHL 349P7FUBEB, NVidia 2060 
log file says:
showInfo : Starting MegaMek v0.47.7 ...
	Compiled on Thu Jan 01 10:00:00 AEST 1970
	Today is Sun Jul 26 12:34:01 AEST 2020
	Java vendor Oracle Corporation
	Java version 1.8.0_251
	Platform Windows 10 10.0 (x86)
	Total memory available to MegaMek: 1,037,440 kB

java --version gives
openjdk 14.0.1 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.1+7, mixed mode, sharing)

### Description
Wide screen issues, Gui Elements not redrawing correctly after a few turns.  Mainly happens where there are buttons (bottom of game screen, or on the UI between rounds).  Also happens on loading screen after it starts.  Only noticed after upgrading machine+monitor to 3440x1440 screen.  Resizing window, can sometimes cause a correct redraw, but any mouse over gui actions cause the redraw to fail again.

### Files
Any game this happens, it's not depenent on the game, so no savegame.
![Annotation 2020-07-26 130419](https://user-images.githubusercontent.com/7206764/88471228-006e9c80-cf4a-11ea-8c84-078c1965b665.png)
![Annotation 2020-07-26 133448](https://user-images.githubusercontent.com/7206764/88471230-02386000-cf4a-11ea-8e0e-2127b64466d3.png)
[megameklog.txt](https://github.com/MegaMek/megamek/files/4977125/megameklog.txt)

**Comment by HammerGS** [comment]
Try these
https://github.com/MegaMek/megamek/wiki/Known-Issues-and-Workarounds

**Comment by cam-smith** [comment]
tried messing around with the -xmx value, and didn't get anywhere, couldn't remember the other setting
