### ISSUE TITLE
Ability to link other players units with /nova command (at least within the same team)

### ISSUE THREAD

**Issue by MGM175** [MegaMek/megamek#2090]
### Environment
MegaMek 0.46.1 (stable)
Linux (Manjaro 20)
Alibaba Dragonwell 11.0.7.2

### Description
Me and my friend selected the mechs with Nova CEWS (Timber Wolf TBR-Z by me; Cephalus E by my buddy), and tried to link them using /nova command. Unfortunately, I'm getting the response, that the unit doesn't belong to me. We were in one team.

**Comment by HammerGS** [comment]
@psikomonkie This is was the bug on the NOVA I was think off.
