### ISSUE TITLE
RFE - Brighten Night Maps in Megamek.

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#2107]
From Discord

_Is there a way to brighten night maps in Megamek? Current darkening of map in night combats makes it harder to see. I'd almost prefer if the map was as bright as day (it's not like I'm going to forget that it's nighttime halfway through combat!). The issue is me and my bad eyesight lol, that needs every visual help it can get._ 

Not sure if we could lighten the tone of the darkness or make the color choose able.

**Comment by NickAragua** [comment]
This already exists, if you go to the advanced tab in client settings, there's a 'darken map at night' setting that you can change to 'false'.

**Comment by HammerGS** [comment]
Wow...all this years and I've never noticed that one before. Things you learn everyday.
