### ISSUE TITLE
41.17 : Changing weapons causes to hit numbers, range and target in weapons panel to dissapear

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#212]
With the von luckner selected, click on the mad cat. The weapons panel will say that it is out of range for the ultra AC 20. Then click on the large pulse laser. The to hit numbers, range and target in the weapons panel will dissapear for some reason. This seems to affect all my units on this map, but not on most maps.

[#battletech.zip](https://github.com/MegaMek/megamek/files/274661/battletech.zip)

![megamek](https://cloud.githubusercontent.com/assets/1191378/15429233/59f06322-1ee3-11e6-9c2f-36f9fd7d9510.jpg)

**Comment by arlith** [comment]
If you load the saved game in the attachment, can you reproduce the issue?  If you can reproduce the isssue, are there any errors in the logfile?  I'm not able to reproduce this issue.

**Comment by Question2** [comment]
Hmm, I just loaded the save game but I can't reproduce it either.

**Comment by arlith** [comment]
I looked in the logfile that you attached, and there are exceptions, but nothing that should relate to this issue.

**Comment by Question2** [comment]
I have a feeling it might be related to the dropship somehow, as it only happens if i have a dropship on the map. Might be something to do with the buggy artillery code for grounded dropships. I will update if i can replicate the issue.

**Comment by arlith** [comment]
I'm going to close the ticket for now then.  If you update the ticket, I will reopen it.

**Comment by SirMegaV** [comment]
I think this is related to this issue.

You have to start a new game (I'm doing it from MekHQ), because save and
reloading the game will solve the problem.

During firing phase, weapon 1 is selected automatically. Choose a target
and fire. Then weapon 2 will be selected automatically. Free weapon 3 from
the list. The last target info will vanish when weapon 3 or others are
chosen.
