### ISSUE TITLE
Default Ares Sprite

### ISSUE THREAD

**Issue by Diplominator** [MegaMek/megamek#2126]
The default sprite for the Ares Superheavy is very, very different from the rest of the variant-specific sprites. It's not a huge deal, but it's a little jarring when I use custom configurations. Would it be possible to make the default Ares be the ARS-V1 sprite?

**Comment by HammerGS** [comment]
I'm not seeing this.  Here are the current Ares sprites.

![image](https://user-images.githubusercontent.com/13752452/103671086-ac73d500-4f37-11eb-9f7e-ba6148c6c937.png)

**Comment by HammerGS** [comment]
Closing as invalid for now.
