### ISSUE TITLE
Physical attack to-hit values incorrect

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#2127]
Version 47.8

The to-hit values for many (but not all) physical weapons are incorrect. As it stands:

-The Lance suffers from a +1 to-hit penalty instead of simply being the 'Mech's piloting value.
-The Sword suffers from a +2 to-hit penalty instead of gaining a -2 to-hit bonus.
-The Retractable Blade suffers from a +2 to-hit penalty instead of gaining a -2 to-hit bonus.
-The Hatchet suffers from a +1 to-hit penalty instead of gaining a -1 to-hit bonus.
-The Mining Drill suffers from a +1 to-hit penalty instead of gaining a -1 to-hit bonus.

Rules may be found on page 38 of the BattleMech Manual.

**Comment by HammerGS** [comment]
Talked to Xotl the Lance is wrong in the BMM and the rest looks like an issue inside Megamek.

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/77d0e81887ec19c5783a01d98d054def0f3cd8bb
