### ISSUE TITLE
MM 47.9 Incline effects not loading

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#2128]
Standalone MegaMek 47.9
Windows 10
Java version 1.8.0_261

The new 'incline' effects are not being displayed when the map is rendered.
Checking the megameklog.txt file, it would appear that the images are not loading.
(This has been tested with both the default 'grass' saxarba tiles and the 'snow' set as well.)

Sample of error rows:
> Trying to load image for a non-existent file! Path: data\images\hexes\incline\snow\incline_top_snow_08.png
> Received null image from ImageUtil.loadImageFromFile!  File: data\images\hexes\incline\snow\incline_top_snow_08.png

The **data\images\hexes\Incline\Snow** folder only contains a single file - **Snow_atlas.png**. This file appears to contain the various incline renders in atlas format. There are no individual incline images in the folder.
The issue is the same with the **\Incline\Default** folder, which only contains a single **Default_atlas.png** file.

Two megameklog.txt files attached as example, one failing to load the default inclines, the other the snow inclines.

[megameklog20200809-1808.zip](https://github.com/MegaMek/megamek/files/5048539/megameklog20200809-1808.zip)
[megameklog20200809-2310.zip](https://github.com/MegaMek/megamek/files/5048540/megameklog20200809-2310.zip)

**Comment by HammerGS** [comment]
Not sure if @SJuliez can provide any insight.

**Comment by SJuliez** [comment]
I'll take a look.

**Comment by NickAragua** [comment]
This is probably fixed in #2130, but I won't be able to build a release for a few days to test whether it actually fixes the problem.
