### ISSUE TITLE
41.17 : Bull medium tank (3054 upgrade) is illegal

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#213]
This is a 50 ton IS tank, standard rules level, with the year set to 3054 and an Ultra AC/10. But it's illegal because the Ultra AC/10's start year was 3057.

Is this correct? Where did this unit even come from anyway? It doesn't appear to be listed on Sarna.net...

**Comment by HammerGS** [comment]
The unit isn't canon that I can find.  It might be from Dylans custom release or somewhere else.  

Check the mechfiles folder and see what folder it's in and fix it locally.

Closing this as invalid.
