### ISSUE TITLE
RFE:  Add total units and percentage of units remaining to /who and round summary

### ISSUE THREAD

**Issue by Kendricke** [MegaMek/megamek#2138]
MekHQ ATB has multiple win conditions that require tracking various forces by units, rather than BV.  I currently manually track these tallies turn by turn, per force/team.  I would like to have this tracked automatically by Megamek during gameplay as part of the summary. 

Current:
Kendricke's Templars: 16400 BV remaining (100.0% of 16400 initially) 0 BV fled
17th Donegal Guards: 12859 BV remaining (99.78% of 12887 initially) 0 BV fled
Thirty Weight Crew: 11871 BV remaining (98.68% of 12030 initially) 0 BV fled

Requested:
Kendricke's Templars: 16400 BV remaining (100.0% of 16400 initially) 0 BV fled, 8/8 units remaining (100%)
17th Donegal Guards: 12859 BV remaining (99.78% of 12887 initially) 0 BV fled, 12/12 units remaining (100%)
Thirty Weight Crew: 11871 BV remaining (98.68% of 12030 initially) 0 BV fled, 12/12 units remaining (100%)

**Comment by Windchild292** [comment]
I'll highly second this request as a solid improvement for AtB and alternative goal gameplay.
