### ISSUE TITLE
41.17 : BA get the PSR warning when trying to jump into heavy woods (unofficial rule)

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#214]
With the unofficial rule turned on, BA get the * PSR warning when attempting to jump into heavy woods. They dont actually have to make the PSR, but the * shouldnt appear in that case.

[#battletech.zip](https://github.com/MegaMek/megamek/files/277407/battletech.zip)

![megamek](https://cloud.githubusercontent.com/assets/1191378/15469858/4e098ab2-2130-11e6-91f3-8c6993f88297.jpg)

**Comment by arlith** [comment]
The check in MovePath (around line 316) for whether danger should be set for the jumping into heavy woods PSR wasn't as safe as it could be.  Basically, any time anything jumped into a heavy or ultra heavy woods hex, it would set danger to true.  I changed it to call `Entity.checkLandingInHeavyWoods` and if the `PilotingRollData` that is returned isn't set to CHECK_FALSE, then the danger flag is set.  This should make it so it's always inline with the PSR nag.
