### ISSUE TITLE
MM 0.47.9 - MegaMek refusing to allow DFA

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#2143]
Standalone MegaMek 47.9
Windows10
Java 1.8.0_261

Wolverine at 2426 attempting to DFA Locust at 2127 (which has finished movement)
Click DFA.
Select Locust as target.
Pop-up asks for confirmation (with a good target number!).
Click 'Yes'.
Unable to click 'Done' to finish move for that unit as was greyed out. (Also happened if 'Charge' selected as attack.)

Players:
SimonLandmine
Mi (Princess, Missile Boat configuration)
Sk (Princess, Skirmisher configuration)
Sc (Princess, Scout configuration)
Sn (Princess, Sniper configuration)

[megameklog20200813-0352.zip](https://github.com/MegaMek/megamek/files/5066912/megameklog20200813-0352.zip)
[FailSave_2020-08-13_03-52-00.sav.gz](https://github.com/MegaMek/megamek/files/5066913/FailSave_2020-08-13_03-52-00.sav.gz)

Closing game and reloading from save allowed DFA.

**Comment by SimonLandmine** [comment]
Remembered that you might need the autosave from the preceding turn to be able to replicate. Sorry!
[autosave_2020-08-13_03-49-24.sav.gz](https://github.com/MegaMek/megamek/files/5081021/autosave_2020-08-13_03-49-24.sav.gz)

**Comment by NickAragua** [comment]
I've tried to replicate this, but without success. The log indicates no errors other than failure to load incline cliff graphics, which, I believe has been fixed since then. Please re-open if it happens again, though.
