### ISSUE TITLE
Stoat Scout Car weight is incorrect

### ISSUE THREAD

**Issue by Davidizer13** [MegaMek/megamek#2154]
The weight of the Stoat Scout Car is listed as 50 tons; the vehicle source, page 11 of Experimental Technical Readout: Primitives, Volume 1, lists the vehicle weight as 15 tons. This affects MegaMek and MekHQ.

https://www.sarna.net/wiki/Stoat

**Comment by HammerGS** [comment]
Fixed as part of https://github.com/MegaMek/megamek/commit/d0fa61552ad502023e8b93884df50395a8535f7a
