### ISSUE TITLE
47.9 Harjel in head

### ISSUE THREAD

**Issue by Diplominator** [MegaMek/megamek#2161]
I put a similar issue in for MML, but when I hand-edited an MTF with Harjel III in the head, Megamek labels it as invalid. It will still function, but the flag is, as far as I can tell, erroneous. Nothing in the rules or errata for Harjel II or III says that they are restricted from the cockpit location. I can find that for the original Tacops Harjel system but nothing for the II or III.

**Comment by HammerGS** [comment]
Question for the Rules team posted.

https://bg.battletech.com/forums/index.php?topic=70686.0

**Comment by HammerGS** [comment]
Answered 
Harjel II/III systems can be mounted in the same location as the cockpit.
