### ISSUE TITLE
Zip Line Dialog sometimes displayed when it shouldn't be

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#217]
MegaMek version 0.41.17

Zip line dialog appearing for gounded VTOL unloading.. again. Was fixed but appearing again.

Savegame attach. Load save game.. go max down.. unload.. zip line dialog open again.. but no rolls was made.

[ZipLineAgain.sav.gz](https://github.com/MegaMek/megamek/files/281203/ZipLineAgain.sav.gz)

**Comment by arlith** [comment]
I previously made a fix in feab3df9, however I used `Entity.getElevation()` instead of `MovePath.getFinalElevation()`.  What was happening was it was using the Entity's elevation prior to moving.
