### ISSUE TITLE
MM 0.47.9 - Can break game in Lobby by using Bot Settings right-click

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#2171]
Standalone MegaMek 47.9
Windows10
Java 1.8.0_261

In the Lobby, create a bot player.
Assign some 'meks to that bot player.
Then, in the player list on the left, right-click the bot player and click 'Bot Settings...' to amend the bot.
It is possible to change the bot name at this point, but if you do so and click [Okay], the bot will become unselectable (cannot change team or start point, nor edit 'Bot Settings...'), and any units that have been allocated to that bot will be locked to that phantom bot, and cannot be transferred to another player.

(Does this mean that the player name is used as an ID key value, rather than simply being a label attached to a hidden player ID?)

**Comment by NickAragua** [comment]
Depending on the difficulty of fixing the actual bug, I may consider simply disabling the option to edit bot name after it's created.

**Comment by SJuliez** [comment]
Just yesterday I wanted to see if I could get rid of the warning dialog rejecting a duplicate bot name that appears when adding a second "Princess". So after entering some code that would alter the name automatically I noticed that the server already does this when given a chance by making it "Princess.2". But then what @SimonLandmine describes happens. I tried to see what to do about it but got seriously discouraged as it looks complicated and it's probably easy to break MM completely with changes here. At the very least, ClientGUI.client.bots needs to be updated with whatever the server returns as a PlayerChangeEvent and I don't know if the running Princess threads need to be informed of a changed name too.

**Comment by SimonLandmine** [comment]
(I tend to name my bots with their role (or a two-letter abbreviation of it) - I use the _pfarland_ bot behaviours, and if I don't give them those names, I can't remember which 'mek to assign to which bot! Does tend to avoid the 2ManyPrincesses issue. I found this issue when I mistyped one of the bot names, and found that I then couldn't change it without breaking things.)

**Comment by SJuliez** [comment]
Closing this as the name of an existing bot cannot be changed anymore.
