### ISSUE TITLE
Players become disconnected for unknown reason and cannot reconnect

### ISSUE THREAD

**Issue by mhjacks** [MegaMek/megamek#2172]
### Environment
What version of MegaMek does your issue apply to?  MekHQ's megamek built against today's master
What operating system are you using?  Windows, Mac, or Linux? Linux
What java version are you using? OpenJDK 11 on Fedora

### Description
The game disconnects players.  We've tried some really big battles, flinging Arrow IV's and stuff around.
This seems to be the most relevant error (from the log, also attached):
`19:40:00,588 ERROR [org.nibblesec.tools.SerialKiller] {Client Connection, Player Marty}
Blocked by whitelist. No match found for 'java.util.LinkedList'

`

After this error, clients are told that they are disconnected, and attempts to reconnect are told "you have become disconnected from the server".  The players are not ghosts, and cannot be kicked and thus not replaced.

[autosave.sav.gz](https://github.com/MegaMek/megamek/files/5115268/autosave.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/5115269/megameklog.txt)

**Comment by NickAragua** [comment]
@Algebro7 I think this one's yours. Can we do some kind of wildcard so that native java classes are allowed to be serialized?

**Comment by Algebro7** [comment]
The problem with whitelisting all java classes is there are well-known gadget chains that use [only JDK classes](https://github.com/frohoff/ysoserial/blob/master/src/main/java/ysoserial/payloads/Jdk7u21.java), so it would mostly defeat the purpose. 

There is a blacklist mode that can block well known gadget chains instead but there have been several [bypasses](https://github.com/pwntester/SerialKillerBypassGadgetCollection) discovered for those. The ideal solution is just not to deserialize raw objects in the first place--I just figured a lookahead library would be a decent bandaid until that can happen.

Let me know what you guys want to do, I'm happy to submit PRs for either case

**Comment by NickAragua** [comment]
For now, let's just add LinkedList to the whitelist in the same manner as Vector, etc.

**Comment by Algebro7** [comment]
Sounds good, I'll open a PR in a moment. Hopefully we're getting close to covering the majority of cases but we'll see

**Comment by NickAragua** [comment]
I think another option to think about, which will, at least, let people fix errors of this category in "real time" is to move the config file back out of the jar, and maybe into mmconf or something.

**Comment by NickAragua** [comment]
Thanks for the help testing, please keep an eye out for any more of these and let us know.
