### ISSUE TITLE
RFE Map Editor - add 'theme brush' option to map editor

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#2182]
With the addition of the 'elevation brush' functionality in the new editor, it would also be useful to have a 'theme brush' option, so that you could change the theme of hexes without changing the other features of the hex.

(This would need to include 'grass' as a selectable option, rather than just applying the default of 'null'.)

**Comment by SJuliez** [comment]
As I interpret this, you can clear the paint hex of anything except the theme you want to paint and then hold shift while painting. Which of course also works with the bigger brushes.
Is that what you intended with this RFE?

**Comment by SimonLandmine** [comment]
[facepalm] I should have thought of that. Sorry. In my (very weak) defence, I was tired. [rueful grin] I'll close this, as you've already got it covered. Thanks!
