### ISSUE TITLE
Unit sprites in the Combat Log are inconsistent when multiple players connected.

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#2186]
Casual Joker is testing a SNAPSHOT of 47.10.  When he is hosting he can't see the sprites in game but the other players can.

@Krashner 

Also if he turns it off it turns it off for connected players.

Reference to PR https://github.com/MegaMek/megamek/pull/2135

**Comment by Krashner** [comment]
Interesting, I'll take a look at it.

**Comment by HammerGS** [comment]
You'll need to watch the stream starting here to see some of the issues and what they were trying 
https://www.twitch.tv/videos/725652460?t=1h2m1s

Casual Joker was hosting and his never appeared but the other players did. When he turned his off they turned of for other players. When he turned them on they appeared for other player but not for him.
