### ISSUE TITLE
Underwater combat LOS

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/megamek#2187]
Megamek 0.47.9

I was wondering how, or if,  are underwater rules implemented in Megamek?
In the scenario below, if I use the LOS tool to measure LOS between the Phoenix Hawk 2 and the Scimitar Tank 3 it says it's blocked by terrain both ways (I assume because of the water, depth 2), and I cannot fire on the tank. Yet the tank fired on the mech the turn before with SRMs and an AC/5.

Can the LOS tool or targeting rules be modified to account for the water? I really thought I was safe from the tank.

![LOS](https://user-images.githubusercontent.com/67933202/91650518-92e9ea80-ea78-11ea-8e98-3fb0df90d637.jpg)

**Comment by SimonLandmine** [comment]
Not sure why the water would block LOS, as the Scimitar is hovering on top of it.
The devs might need a savegame to be able to try to replicate.

**Comment by JonhyBurner** [comment]
[LOS.sav.gz](https://github.com/MegaMek/megamek/files/5152310/LOS.sav.gz)
This is the savegame for the turn after I got attacked. No save from the round before, I'm afraid. But you can see in the round report the tank's attack. Player is MyCampaign.

The tank is over the water, I was just trying to make sense of the LOS calculation.

It's weird because supposedly LOS is reciprocal (if you ignore cover), so something fishy is going on.

**Comment by SJuliez** [comment]
LOS (TW rules) is blocked by the level 1 hex adjacent to the Scimitar. I can't say how it would have been able to fire on the PXH. This is what the tank sees:
![image](https://user-images.githubusercontent.com/17069663/93705176-7727b080-fb1b-11ea-9f54-3e4950a33a0d.png)

The LOS tool could be a little more informative when LOS is blocked.

**Comment by SJuliez** [comment]
Closing this as I believe there was nothing wrong in this particular case.
