### ISSUE TITLE
Heat Differences between tool tips and various tabs in unit view

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#2188]
Casual Joker player noticed that their seems to be discrepancy between heat on the tool tip and unit view in game. They've seen this when in extreme cold environments.  Will update with link to stream when available.

### Environment
What version of MegaMek does your issue apply to?  47.10 SNAPSHOT Megamek with MekHQ
What operating system are you using?  Windows

### Files
[hammersave.sav.gz](https://github.com/MegaMek/megamek/files/5146342/hammersave.sav.gz)

**Comment by HammerGS** [comment]
See the stream shortly after here for the heat issue.
https://www.twitch.tv/videos/725652460?t=1h2m1s

**Comment by gsparks3** [comment]
IIRC the value in the middle window is basically your projected heat at the end of the turn, including any declared weapons fire, but _also_ including movement and environmental heat effects - so if you haven't fired anything yet in an extreme cold environment, the value will be lower than your actual heat at the start of the turn.

**Comment by kuronekochomusuke** [comment]
// If a Mek is in extreme Temperatures, add or subtract one
            // heat per 10 degrees (or fraction of 10 degrees) above or
            // below 50 or -30 degrees Celsius
            ServerHelper.adjustHeatExtremeTemp(game, entity, vPhaseReport);

**Comment by KaiserFalk** [comment]
This was at -50. Attaching the gamelog now that I'm done
[gamelog.zip](https://github.com/MegaMek/megamek/files/15124348/gamelog.zip)

**Comment by repligator** [comment]
Fixed by https://github.com/MegaMek/megamek/pull/5910 . Closing.
