### ISSUE TITLE
41.17 : Tacops skin of teeth ejection not working

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#219]
Despite having it on, pilots are not ejecting when the head loses all internal structure (see round report in save game).

[#battletech.zip](https://github.com/MegaMek/megamek/files/281954/battletech.zip)

**Comment by scJazz2** [comment]
I'm fairly certain that is WaD.

**Comment by HammerGS** [comment]
Errata Pending.

http://bg.battletech.com/forums/index.php?topic=52942.0

**Comment by arlith** [comment]
Pilots do eject when the head is destroyed and skin-of-the-teeth ejection is on, unless they are dead, doomed (a MM term, when they should be marked as dead as the end of the phase), or the auto eject isn't on.

In your case, the pilot is already dead.  If you look back at the log, the hit that destroys the head is the 6th point of damage to the pilot, so he's dead before the auto ejection gets a chance to fire.

Looks at the log, he takes two head hits from the first SRM 6 on the SRM carrier, for a consciousness 3 and 5.  Then he takes another head hit from the third SRM 6, forcing a consciousness check at 7 which he fails and blacks out (that's 3 points of pilot damage).  Then the 8th SRM 6 hits the head 3 times, the first hit drops the head to 1 armor (4 pilot damage), the second hit drops the head to 2 IS (5 pilot damage), the third hit destroys the head, and kills the pilot (no autoeject for dead pilot).
