### ISSUE TITLE
Make the resolution phases in floating window or in a side portion of the screen at an option

### ISSUE THREAD

**Issue by Onirim** [MegaMek/megamek#2193]
I think it may be very useful to be able to see the map during the resolution phases. Why only having a big tab for just a little text (depend of the game), and not having a floating window option, or a side tab with the resolution texts ? (Prefer the floating window because you can arrange it like you want, like for the unit floating window).

I play with many new players and it's difficult for them to remember where they units are for reading the resolution texts, and it's better to read the resolutions during the firing phase (because of the shooting arrows) than to read the round report after that, without the arrows.

Thanks :)

**Comment by kuronekochomusuke** [comment]
implemented in https://github.com/MegaMek/megamek/pull/4030
