### ISSUE TITLE
Pilot Abilities are still working even when Pilot Abilities are disabled in Megamek

### ISSUE THREAD

**Issue by Mekslayer** [MegaMek/megamek#2199]
Even when special abilities are disabled in Megamek, a pilot, pulled from a mul file, that has Pilot abilities will still have those pilot abilities even when they are turned off in the Game options.

### Environment
All versions of MM I suuspect.
What version of MegaMek does your issue apply to?  Note whether it is the stand alone MegaMek or HQ's MegaMek.
What operating system are you using?  Windows, Mac, or Linux?
Windows 10
What java version are you using?  If unsure it will state your java version at the top of the megameklog.txt file.
Recent Java

### Description
Describe the issue and provide screenshots ingame if able.
Provide the rulebook, page number, and text if you feel like this is a rules issue.
And provide the steps you have taken to reproduce the issue in the saved game if applicable.
(Delete the above lines)

### Files
Provide a saved game of when the issue was found.  If possible try to save the game during the phase before the issue occurs so the 
developers can step through the code and find exactly what it is that is breaking in the code.
Provide the megameklog.txt file for any NPE's or errors that MegaMek might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual megameklog.txt file
And provide your playername so that they can load the saved game.
(Delete the above lines)

**Comment by Windchild292** [comment]
This is true for:
SPAs
Edge
Implants
Toughness
Artillery Skill
