### ISSUE TITLE
41.17 : Tacops vehicle crew rule seems to be based on number of weapons rather than number of targets

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#220]
The SRM carrier in this save game gets the secondary target penalty if it attempts to fire 3 SRMs at the puma and a 4th one at any other target. Page 218 tacops says that for every additional crewman above 2, the vehicle may target 1 more target without penalty. The 60 ton SRM carrier has a crew of 4, so should be able to target a total of 3 different targets with no penalty (primary target + 2 additional targets for 2 crewmembers above 2).

Megamek seems to be basing it on a total of 3 different weapons (rather than targets) though, so trying to shoot a 4th weapon at a 2nd target will trigger the secondary target penalty.

[#battletech.zip](https://github.com/MegaMek/megamek/files/282079/battletech.zip)

**Comment by arlith** [comment]
The logic for counting the targets was a bit flawed.  I adjusted it so it's accurate now.
