### ISSUE TITLE
[Request] Add unofficial abandon vehicle functionality to Torso Cockpit mechs

### ISSUE THREAD

**Issue by Marshymallow** [MegaMek/megamek#221]
At the moment, it is impossible for a torso cockpit-based mech to eject seeing as they are in the torso and all. There is an unofficial rule in megamek allowing vehicle crews to abandon their vehicle - it seems to make sense to me to expand this functionality to the torso cockpit mechs, seeing as the ability to abandon a mech is generally even more relevant for the purposes of campaigns and other scenarios than vehicle crews.

**Comment by pheonixstorm** [comment]
What do the rules say about torso cockpits and ejection.

**Comment by arlith** [comment]
Isn't there another ticket about requesting an unofficial option for abandoning 'mechs in general?  I think this may fall under that ticket.

**Comment by BLOODWOLF333** [comment]
#161

**Comment by HammerGS** [comment]
Duplicate closing.
