### ISSUE TITLE
Generic Infantry Types Data

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#2214]
When MekHQ generates infantry opposition from its random tables, some of them are from the TRO 3085 examples.  Many of these names are long, such as "Recon Infantry Recon Battalion 201st Pesht Assault Team 3rd Proserpina Hussars".  The long names are difficult to follow in MegaMek.   It also breaks the immersion to see Draconis Combine -named infantry being deployed by Fed Suns or other nations.

Please create a second set of these infantry with shorter, more generic names like the standard Total Warfare names such as "Foot platoon (rifle)".  For example, the above infantry type could be "Recon hover platoon (demo)".

Also adjust the RATs (random assignment tables) in the force generator so they select from the generically named units.

**Comment by HammerGS** [comment]
I really need the mechset data for the sprites before I can add these.

**Comment by SuperStucco** [comment]
> I really need the mechset data for the sprites before I can add these.

I might be able to handle that, if someone points me in the right direction.

**Comment by NickAragua** [comment]
In data\images\units, there's a file called mechset.txt which maps units to unit images. We need entries pointing those units to a reasonably similar image in data\images\units\infantry (better to look at the git repository, as they're in an image atlas in the releases)

**Comment by SuperStucco** [comment]
Done.

[mechset (generic infantry).txt](https://github.com/MegaMek/megamek/files/5287129/mechset.generic.infantry.txt)

**Comment by HammerGS** [comment]
Resolved with https://github.com/MegaMek/megamek/commit/fe7f00f5ac4eefd2123b5c8681b2cf6cfcff8d16

Thanks SuperStucco for all the work on this. Cheers.
