### ISSUE TITLE
V0.47.9 Can't Load Tileset on Linux/Ubuntu 20.04.1 - With Fix

### ISSUE THREAD

**Issue by helix-0311** [MegaMek/megamek#2218]
user@hostname:~/Downloads/mekhq-0.47.9$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"

<---------------------------------->

showInfo : Starting MegaMek v0.47.9 ...
        Compiled on Sat Aug 08 00:16:58 EDT 2020
        Today is Sun Sep 13 10:14:16 EDT 2020
        Java vendor Ubuntu
        Java version 11.0.8
        Platform Linux 5.4.0-47-generic (amd64)
        Total memory available to MegaMek: 8,194,048 kB

10:14:16,716 INFO [megamek.MegaMek] {main}

...

10:18:25,800 ERROR [megamek.client.ui.swing.tileset.TilesetManager] {AWT-EventQueue-0}
TilesetManager() : Error loading tileset saxarba.tileset Reverting to default hexset!
localclient_wreckset.txt.

<---------------------------------->

Did some troubleshooting (renamed the saxarba tilesets to the default tileset to throw an exception) and the fix was:

Changing these lines in saxarba.tileset:

include "incline/inclines2.tileinc"
include "high_incline/high_inclines.tileinc"
include "saxarba/SMV_SeaPort/SeaPort.tileinc"

to:

include "Incline/Inclines2.tileinc"
include "High_Incline/High_Inclines.tileinc"
include "saxarba/SMV_SeaPort/Seaport.tileinc"

**Comment by SJuliez** [comment]
Thanks! 
Will update this.
