### ISSUE TITLE
47.9 - Unloading units from Bays in Support Vehicles is not rules-correct

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#2220]
On p. 207 of _Total Warfare_ (2020 edition, 6th printing), it states ...

> "Unless specifically noted otherwise, units use the same rules to mount and dismount from Support Vehicles as for mounting and dismounting from grounded aerospace units (see _Carrying Units_, p. 89, in the _Aerospace Movement_ section)."

And on p. 91 of _Total Warfare_ (2020 edition, 6th printing), it states ...

> "Units carried by Small Craft and DropShips dismount into adjacent hexes (any adjacent hex, though the hex must be within two levels of the level of the underlying hex(s) of the aerospace unit), with a facing of their choice, and the dismounting unit must be able to enter the terrain (though a unit may use the Minimum Movement rule, p. 49, to enter a hex, but it still cannot be prohibited from entering that hex). The dismounting unit may not violate the stacking limits."

I can't find anything stating that this 'dismount into adjacent hex' rule is also applied for units dismounting Support Vehicles. (While it is specifically stated that to mount a (non-Large) SV, the mounting unit must be in the same hex, there appears to be no statement that units dismount into the same hex.)

However, in Standalone MM 0.47.9, a unit (vehicle or mech) unloaded from a Vehicle Bay or Mech Bay in a Support Vehicle is unloaded into the same hex as the Support Vehicle - even where this would violate stacking limits (e.g. a vehicle being unloaded from a Large Support Vehicle). Is this an error, or have I missed an exemption somewhere?

**Comment by SimonLandmine** [comment]
(A side-effect of this is that if a unit is unloaded from a Large Support Vehicle into the same hex as the Large Support Vehicle, it is then unable to move until the Large Support Vehicle moves out of the hex, presumably due to the stacking and 'impassable terrain' logic (as used when a hovercraft skids into woods.)

**Comment by SimonLandmine** [comment]
Should I put a query up on the Forum for a rules clarification on this?

**Comment by HammerGS** [comment]
Might be best.

**Comment by SimonLandmine** [comment]
Now up on the Forum ...
https://bg.battletech.com/forums/total-warfare/unloading-units-from-bays-in-support-vehicles/

**Comment by SimonLandmine** [comment]
(Might need to remove the 'Needs Investigation' note, as has now been clarified via the Forums. MM behaviour is incorrect.)
