### ISSUE TITLE
Primitive Prototype Weapons missing Static Tech tags.

### ISSUE THREAD

**Issue by NimoStar** [MegaMek/megamek#2235]
Issue wrongfully closed, see [here](https://github.com/MegaMek/megameklab/issues/771)

Why is it listed as standard and common tech. And why it allows you to put it in and then tells you it's invalid.

Even if that, if anything it should change the 'Mech summary to Experimental, instead of saying it's "Invalid", as it happens also in other units. When you put in experimental tech, they just change the ratings, not invalidate the unit. As it stands there is no point to having that tech listed when you say you want to build a standard unit.

![2020-09-23 05_25_13-Cuttergiant Arling mtf](https://user-images.githubusercontent.com/38392980/93987149-94e45800-fd5d-11ea-8563-ef11fc299f76.png)

_Primitive Prototype weapons, when I'm using them in industrialmechs, appear as just "experimental" tech, even if they display as standard - and were prototypes centuries ago.

This is an standard industrialmech of 2995 that doesn't get to use PRIMITIVE tech because it's too advanced, even if it's displayed as standard. This basically happens with all primitive prototype weapons._ If they aren't standard, put them in Experimental. If an industrial mech uses experimental tech, just change it to the corresponding category instead of breaking it.
![2020-09-23 05_25_13-Cuttergiant Arling mtf](https://user-images.githubusercontent.com/38392980/93951369-7e69dc80-fd1c-11ea-93fc-24f209f01120.png)
***
47.10

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/09b11050cebd299f378847103fc1c06ca2cecfc8
