### ISSUE TITLE
47.10 Default tooltip armor display characters not rendered properly in some MM themes

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#2240]
### Environment
Version 47.10
Windows 10
Java version 1.8.0_261

### Description
When switching to certain themes in Megamek Client Settings, the (default) special characters used for the tooltip armor display fail to display properly. This can be observed both in-game and in the Client Settings (Advanced) tab where the characters are defined, with the latter being easier to reproduce since you don't have to actually start a game and get some sections damaged and destroyed to show all the possibilities. 

Example of unaffected theme (Metal): 
![image](https://user-images.githubusercontent.com/59574316/94082101-268bae00-fdce-11ea-8028-d65c17a6a685.png)

Example of affected theme (Flat Light): 
![image](https://user-images.githubusercontent.com/59574316/94082140-458a4000-fdce-11ea-808a-0d14bebddd5f.png)

This issue renders the armor mini-display less useful on affected themes while using the default settings, as "Destroyed Component", "Undamaged IS", and "Undamaged Armor" all end up rendering as the same "character". Damaged armor or IS is at least still distinguishable by color. 

List of affected themes:
Flat Light
Flat IntelliJ
Flat Dark
Flat Darcula
(i.e., all of the "Flat" themes)

All other themes are unaffected.

As a workaround, I am using "■" for armor, "#" for internal structure, and "×" for destroyed sections, which display properly on all themes.

**Comment by sixlettervariables** [comment]
I believe this may be font related per theme.

**Comment by HammerGS** [comment]
They confirmed on Discord that it only happens on dark themes.

**Comment by gsparks3** [comment]
Rather, it only happens on _flat_ themes, but if you want to use a dark theme, the only available options are Flat Dark and Flat Darcula, both of which are affected.
