### ISSUE TITLE
Cannot Save Unit List

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#2245]
Version 47.10

After creating a force in the lobby megamek will not save the unit(s) to a .mul file.

After testing it a few times, it would appear that if a unit is left untouched in the lobby, it can be saved to a file. However, if the unit is modified in any game-affecting way (such as changing the piloting/gunnery skill, or changing an ammunition type) it is no longer able to be saved to a file.

Attached is a log where this occurs.

[megameklog.txt](https://github.com/MegaMek/megamek/files/5272840/megameklog.txt)

**Comment by SJuliez** [comment]
I suspect this has to do with the portrait issue and is already solved through #2230 
I will check.

**Comment by Windchild292** [comment]
Yup, portrait NPE

**Comment by SJuliez** [comment]
Just tried in the current master, changed a gunnery, assigned someone a portrait, saved. Loaded the list again, no problem. So I think this is solved.
