### ISSUE TITLE
Screwy speed on a Notos with QuadVee

### ISSUE THREAD

**Issue by cdalmas** [MegaMek/megamek#2253]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
Version 46.1
Windows 10
Latest Java

### Description

Notos with Quad Vee technology had two legs blown off in vehicle mode and suddenly had a movement of 23/35.
See screenshots
![image](https://user-images.githubusercontent.com/56173433/94346696-62a45600-fffc-11ea-92fa-5fe5e3164781.png)
![image](https://user-images.githubusercontent.com/56173433/94347109-8f0da180-ffff-11ea-91a5-da279a6ce7b6.png)

### Files
[Arena.sav.gz](https://github.com/MegaMek/megamek/files/5287090/Arena.sav.gz)

The player's name in the game is "Tony." It's the Notos Prime.

[megameklog.txt](https://github.com/MegaMek/megamek/files/5289478/megameklog.txt)

Megameklog.txt uploaded! Please let us know as soon as you get to this! Cheers.

**Comment by cdalmas** [comment]
Thanks for trying to fix this. I didn't find this as a problem when I
uploaded the bug, so I'm sorry I duplicated a known issue. I just hope our
screenshots, save game, and megameklog.txt file are helpful in fixing it!
Thank you, too, for creating this wonderful game. My friends and I,
farflung around the country, enjoy it immensely.

Charles

Am So., 4. Okt. 2020 um 15:16 Uhr schrieb neoancient <
notifications@github.com>:

**Comment by neoancient** [comment]
It was not a known issue. I fixed it because of your report.

**Comment by cdalmas** [comment]
Oh! I thought it was known because it was merged! Wow, I feel kinda cool
... sort of like a "mini-developer." HAHA. Anyway, thanks again for
creating this fabulous game. I cannot really conceive of the work that went
into it. It must have been hours upon hours upon hours, into months, and
even years of real time. We appreciate it more than you know.

Charles

Am So., 4. Okt. 2020 um 21:27 Uhr schrieb neoancient <
notifications@github.com>:

**Comment by HammerGS** [comment]
Megamek has been in continuous Development since 2002. The current team is just the latest in a line of developers. Enjoy the programs and please post any other bugs you see.

**Comment by cdalmas** [comment]
Well, then my hat's off to everyone who has created this game over the last
18 years. What a labor of love. Thank you, thank you, thank you ALL.

Cheers,

Charles

Am So., 4. Okt. 2020 um 21:44 Uhr schrieb Dave N <notifications@github.com>:
