### ISSUE TITLE
Guard GS-54 canon SecurityMech missing even as "Guardian" apocryphal one is added (file included)

### ISSUE THREAD

**Issue by NimoStar** [MegaMek/megamek#2257]
It seems strange that a [Canon Design, the GS-54](https://www.sarna.net/wiki/Guard) was passed in favor of a [non-canon one, the GRD-1N](https://www.sarna.net/wiki/Guardian_(BattleMech)) (specially as the non-canon design has less info and has the questionable armament for its size and drawing; and there is also two variants of it, both added in)

The apocryphal mech is OK to be in a non-official level.
However, the actual one should be available as well and with higher priority. The 'mech is also prominently featured in a classic story.

I took the liberty to already make the canon variant as described. There was no technical readout but **this includes all the available info and is built perfectly to specifications**. So to add this, it should be enough to include it.

### Environment
47.10

### Files
[Guard GS-54.zip](https://github.com/MegaMek/megamek/files/5287704/Guard.GS-54.zip)

**Comment by HammerGS** [comment]
Going to sit on this until Irregular Tech is released.

**Comment by HammerGS** [comment]
Irregular Tech released and all units in that TRO now in MegaMek.
