### ISSUE TITLE
CTRL-K does not hide keyboard shortcut display

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#2258]
0.47.10 Standalone
Windows 10
Java 11.0.8

The `CTRL + K` key combination does not hide the keyboard shortcut on-screen display, as described on that display. The display can still be hidden using the 'View' menu.

(It is listed in the Keybind tab of the Client Settings dialog, but does not appear functional. If another key combination is bound, this does not toggle the on-screen shortcut display either.)

**Comment by HammerGS** [comment]
I can confirm I saw this last night on the Casual Joker Stream.

**Comment by SimonLandmine** [comment]
(Other users have reported that this is also the case on the bundled version of 0.47.10.)

**Comment by SJuliez** [comment]
Yes :( should be fixed in the current master. It can be fixed in the 47.10 by going to the Client Options, Keybinds, assigning something new to this keybind (for example by removing the Ctrl-modifier) and clicking update. Then when starting MM the next time(!), it should work.

**Comment by SimonLandmine** [comment]
Ah, so the keybind update only takes affect for that when MM is started the next time? That I _didn't_ try! Thanks for fixing.

**Comment by SJuliez** [comment]
Closing this, as I think it is fixed.
