### ISSUE TITLE
Flamers not working, stuck on attack phase (47.10)

### ISSUE THREAD

**Issue by NimoStar** [MegaMek/megamek#2267]
Clan Heavy Flamers not working
(this probably extends to all flamers?)

Two different savegame files with the issue included

### Environment
47.10
Win 7 64 bits

### Description
When battling with mechs armed with flamers, the game gets stuck on firing phase. The flamers never fire. The bug seems to affect both human players and bots.

I tested it with Clan Heavy Flamers.

### Files
[heavyflame.sav.gz](https://github.com/MegaMek/megamek/files/5297968/heavyflame.sav.gz)
[trabado.sav.gz](https://github.com/MegaMek/megamek/files/5297969/trabado.sav.gz)
Edit: These games use custom units, if you can't use them, I will have to try with default units only.

**Comment by HammerGS** [comment]
Please zip up and attach custom units also provide player names.

**Comment by NickAragua** [comment]
The other things that would help are a) the megamek/mekhq log files and b) a save from before you hit 'done' on the firing turn.

**Comment by NimoStar** [comment]
Player names are: PlayerC and Princess

I attach all my units just in case
[vehicles NimoStar.zip](https://github.com/MegaMek/megamek/files/5305127/vehicles.NimoStar.zip)

**Comment by NickAragua** [comment]
Looks like the "real" issue is that the Cutman IIC does not have any ammo for its flamers, but for some reason was able to fire them. Clan heavy flamers actually require ammo per TacOps page 312.

**Comment by NickAragua** [comment]
Note that this won't fix any games in progress that have already had this happen, but will prevent it from occurring in future games.
