### ISSUE TITLE
0.47.10 Prototype Ultra Autocannons inaccurate. 

### ISSUE THREAD

**Issue by LiamsGhost** [MegaMek/megamek#2268]
The Inner Sphere Prototype Ultra AC-5 is listed as 7 tons and 2 critical slots rather than 9 tons and 6 critical slots.

**Comment by HammerGS** [comment]
Also moving to Megamek Tracker as equipment stats managed via Megamek.

**Comment by LiamsGhost** [comment]
Page 104 Interstellar operations: "Aside from occupying one more critical slot than its production standard version, the prototype ultra autocannon/5 may be mounted on any unit in accordance with its normal rules for mounting such weapons."

In addition to outright contradicting the above stat block, it follows the same pattern as the other prototype ballistic weapons discussed in the section (the LB-10X and Gauss Rifle) by keeping the mass the same as the production model but adding a critical slot. It's also identical to how the weapon was described in its initial appearance in the War of 3039 book.  The preponderance of evidence makes it clear that the stat block you cited is in error.

**Comment by KarlStreiger** [comment]
There is a table in the Scenario Book - Sword and Dragon with the correct stats, other sources (construction rules as text- in War of 39) - also support the 9ton 6crit - version. On top of this a 7ton 2crit UAC5 would have been better than a Clan UAC5.
 
![ultra5](https://user-images.githubusercontent.com/72197055/94794216-dd45ea80-03db-11eb-9b05-a66622ad32d8.png)

**Comment by LiamsGhost** [comment]
Just to nail this down... https://bg.battletech.com/forums/supplementary-rules/io-recovered-prototype-ultra-ac-5-tonnage-and-critical-slots/

**Comment by HammerGS** [comment]
Was fixed yesterday. https://github.com/MegaMek/megamek/commit/af5abea6dff825c76e2c2e0952790497cd25804b
