### ISSUE TITLE
0.47.10 Prototype LB-10X record sheet typo

### ISSUE THREAD

**Issue by LiamsGhost** [MegaMek/megamek#2269]
The prototype LB-10X is listed on the record sheet as the LC-10X

**Comment by HammerGS** [comment]
Moving to Megamek as all equipment data managed via Megamek.

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/28957c5b3b8d7ea07f3256f5ff9a83adebaf4ad8
