### ISSUE TITLE
Recovered Prototype Gauss Rifle Ammuntion intro date wrong.

### ISSUE THREAD

**Issue by LiamsGhost** [MegaMek/megamek#2270]
Recovered Prototype Gauss Rifles are available starting in 3038, however the ammunition for the prototype gauss rifle is not unless the "show extinct tech" option is enabled.

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/aa0cc0ec6b03a4099fc343f09aa8eebff4a2b3eb
