### ISSUE TITLE
0.47.9 Rocket Launcher introduction dates

### ISSUE THREAD

**Issue by LiamsGhost** [MegaMek/megamek#2271]
Standard rockets are available for units well before their introductory date, but prototype rockets are not. Prototype Rockets have an introductory date of early spaceflight on page 73 of Interstellar Operations, which corresponds to the prototype date for standard rockets. In addition the earliest canonical unit to use prototype rockets was the Hurricane Conventional fighter, with an introductory date of 2297. Assuming you're using the introductory date of 2320 found on 217 of interstellar operations, the preponderance of evidence would suggest that date is an error, as every other source contradicts it.

Also, the prototype date for standard rockets is clearly referring to their prototype form, not the modern form from 3064, in the same way that other prototype forms of weapons aren't listed separately from their modern forms on the Universal Technology Advancement Table in Interstellar Operations. Therefore, modern rockets should not be available before their 3064 production date.

**Comment by HammerGS** [comment]
Equipment Data handled via Megamek.

**Comment by HammerGS** [comment]
I agree with the logic, and has been address here - https://github.com/MegaMek/megamek/commit/96e37f1a8e82550e2958008b9ca213f0a9b2b2dd
