### ISSUE TITLE
Aerospace and Conventional Fighters change BV on save/load

### ISSUE THREAD

**Issue by RexPearce** [MegaMek/megamek#2273]
Confirmed on versions: 0.46.1, 0.47.10, and current master.

Steps to reproduce:
 1) start a new campaign
 2) add a conventional fighter, e.g. Guardian Fighter (Standard)
 3) add an aero fighter, e.g. Transit TR-9
 4) Note their BVs
 5) save/load the campaign
 6) Note their BVs have changed.

Doesn't seem to be related to the pilot - assigning a regular pilot the save/loading has no effect on BV.

**Comment by neoancient** [comment]
Capital fighters weapon groups combine left and right wing weapons into a single wing location. That's what the WNG is for. It doesn't represent an actual physical location. The question is where is it being marked destroyed?

**Comment by sixlettervariables** [comment]
MekHQ uses the location string logic from MM which checks the armor amount being `<= 0` in a location and if so it's destroyed. It uses all 6 locations for Aeros which includes the Wings and Fuselage.

**Comment by SJuliez** [comment]
From the linked PRs I assume this is fixed.
