### ISSUE TITLE
Add unofficial option to give every mech and vehicle a free searchlight for night missions if they don't have one already.

### ISSUE THREAD

**Issue by Tamren** [MegaMek/megamek#2277]
It would simplify night combat a little if Megamek could give searchlights to all of your units as an unofficial rule. This would simply automate the process of adding lights to all of your units through meklab when playing ATB. The construction rules say "combat vehicles and 'Mechs may have a larger mounted searchlight at no cost in weight, slots or C-Bills" so in effect all this does is give mechs and vees the searchlight quirk for free. The searchlight would be mounted in the CT or FR facing forward, which iirc only matters in checks that determine when the searchlight is destroyed by enemy fire.

**Comment by NimoStar** [comment]
Why only if they don't have one? This disadvantages 'mechs that are already spendin crits and tonnage in the Searchlight. If anything at least add a free extra one to them as well

**Comment by SimonLandmine** [comment]
IIRC, Searchlight is a Quirk, rather than a piece of equipment that costs crits or tonnage.

**Comment by SimonLandmine** [comment]
Most 'meks with Searchlights have it as a Quirk, for no weight or space, and the optional rule seems to apply this Quirk to all 'meks and combat vees. Units with additional Searchlights added as construction elements should certainly be treated as having more than one, so that they have a spare if the first one is destroyed.

**Comment by NimoStar** [comment]
I was going to respond this to your original comment (now edited out):

![2020-09-30 16_34_34-Lightbringer LTB-1 mtf](https://user-images.githubusercontent.com/38392980/94731551-59d4bc80-033b-11eb-87e8-e24723571c04.png)

Plus, MekLab doesn't allow quirks,
 so this is the only normal way of getting searchlights on custom units.

**Comment by SimonLandmine** [comment]
> I was going to respond this to your original comment (now edited out):

Yeah, sorry - I realised as I was correcting it that you would have got a notification email.
That is a _slightly_ specialised 'mek build, but it makes the point.

However, as I understand it, it's not the only way to get a Searchlight on a custom unit.
1. Create custom unit in MekLab.
2. Load custom unit into MegaMek.
3. Use 'Configure Quirks' option to apply desired Quirks.
4. Use 'Save Quirks for Chassis' or 'Save Quirks for Chassis/Model' as desired.
This will update the local quirk list for that chassis or model.

**Comment by SuperStucco** [comment]
In the MegaMek lobby, there's also a right-click context menu for this:
![Searchlights](https://user-images.githubusercontent.com/70451747/94735947-bb3f6000-0328-11eb-9141-1b5eadb76a4b.png)

**Comment by Tamren** [comment]
Would it be possible to automate that context menu click as an unofficial rule? That would save time over configuring vehicles individually in the lobby, or through meklab. Essentially if a mech or combat vee doesn't already have the Quirk for a free searchlight the game adds one automatically at no cost per the construction rules. I agree that if a mech or combat vee already has one or more built in searchlights at the cost of crits and tonnage, it should be granted an additional spare making it harder to knock out that capability.

If balance is a concern you could have this option apply to enemy forces as well, though I'm not sure if the AI currently handles searchlight mechanics.
