### ISSUE TITLE
Major Initiative bug! in game with all Canon Units provided by megamek

### ISSUE THREAD

**Issue by Mekslayer** [MegaMek/megamek#2296]
### Environment
What version of MegaMek does your issue apply to?  
Stable 46.1

Note whether it is the stand alone MegaMek or HQ's MegaMek.
Megamek played from the HQ download.

What operating system are you using?  Windows, Mac, or Linux?
Windows 10 on HP Envy Laptop

What java version are you using? 
	Java version 1.8.0_261
	Platform Windows 10 10.0 (x86)

### Description
Major Issue, Playing a decent sized battle with a Friend, we had a situation where I won Initiative, but despite winning init, my opponent was given the turn order movement to allow him and his units to move last. 

### Files
Here is the Save File Attach. you may have to move a few more units to see that despite wining init, it allowed init loser to move last.

[Todd_CBills_T20.sav.gz](https://github.com/MegaMek/megamek/files/5322637/Todd_CBills_T20.sav.gz)
[Todd_CBills_T20A.sav.gz](https://github.com/MegaMek/megamek/files/5322638/Todd_CBills_T20A.sav.gz)

**Comment by Mekslayer** [comment]
Oh sorry I just realized that one unit from one of the zip files, may not be canon.
[Oculus.zip](https://github.com/MegaMek/megamek/files/5327402/Oculus.zip)

**Comment by neoancient** [comment]
Master_Warrior_1234 rolled a 10 for initiative. Wiz rolled an 8. I played through the movement phase of the provided saved game, and Wiz moved last. I can find no problem.

**Comment by neoancient** [comment]
I reopened this because I thought I had erred when I tested it yesterday, but I just had a chance to try again, and confirmed that the player that lost the initiative moved first (two units), then the player that won initiative (one unit).
