### ISSUE TITLE
41.17 : Axel Heavy Tank IIC (XL) has incorrect name and stats

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#230]
There are two Axel Heavy Tank IICs in the files, one is supposed to be the XL version and has an XL engine, but it is still called (Standard) and has incorrect stats (it's stats are the exact same as the standard version except for the engine).

I checked this using a fresh install of 41.17 that I downloaded yesterday.

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/3ae0ebfbb1409fbfe355e36546e3c5f99005c3b4
