### ISSUE TITLE
0.47.11: Pegasus Scout Hover Tank Displays as Damaged Immediately Upon UnitSelector Add

### ISSUE THREAD

**Issue by Windchild292** [MegaMek/megamek#2309]
Noticed this when it loaded from AtB and one of the OpFor vehicles was displaying using the damage sprites upon load. 
![image](https://user-images.githubusercontent.com/39067288/95115455-827dfd00-0713-11eb-9fd6-bd613002629d.png)

There is nothing in the logs, and I can recreate just by adding from UnitSelector so I am not including a MUL file.

**Comment by NickAragua** [comment]
Check your gravity.

**Comment by Windchild292** [comment]
1.07G

**Comment by NickAragua** [comment]
That's probably enough to slow a fast hovercraft down. The various damage checks I don't think take gravity into account.

**Comment by gsparks3** [comment]
I can confirm that in various situations that cause vehicles to lose MP (high gravity, extreme cold, etc), they will show the damage decals and status dots even if otherwise undamaged. Presumably the lower-than-normal MP is being interpreted as mobility damage.

**Comment by SJuliez** [comment]
Yes that is exactly the case. It is much simpler to check lowered MP than the individual influences. One more possibility for improvement...
