### ISSUE TITLE
SSW -> MM BV Issues

### ISSUE THREAD

**Issue by rjhancock** [MegaMek/megamek#2313]
Issues noted by the SSW team when comparing their calculations against both MUL and MML:

~~Both MML and SSW both calculate ammo in the front legs of quads as ammo in arms, which affects BV.~~
~~MML isn't counting M-Pods as explosive~~
* iATMs may not count as half heat like streaks in MML

Tested against MML 0.47.9

Fixed (or think we are fixed)
~~Bridge Layer BV may not be in MML~~
~~Stealth STH-5X recordsheet may be wrong in MML~~
~~Turkina U missing coolant pod for at least BV calc purposes~~
~~Wolfhound WLF-2X recordsheet may be wrong in MML~~
~~2KO No-Dachi has an incorrect RS, 2 ERMLs firing to the rear that are firing to the front in the RS~~

**Comment by WEKarnesky** [comment]
Feel free to direct any questions to me, I'll field them to the SSW team if I can't answer.

**Comment by Maelwys** [comment]
For some odd reason in the ON1-H Orion, it has

"Explosive Weapons/Equipment Penalty |   | = -165.0"

60 of this is ammo. I'm not sure where the other 105 comes from. The only thing I can think of is that MM is treating the Primitive Prototype's AC10's crits as explosive ammo for some odd reason.

**Comment by HammerGS** [comment]
Some fixed in https://github.com/MegaMek/megamek/commit/74c3966a520f0b0ca4549e25763a064dde119bad

**Comment by HammerGS** [comment]
> For some odd reason in the ON1-H Orion, it has
> 
> "Explosive Weapons/Equipment Penalty |   | = -165.0"
> 
> 60 of this is ammo. I'm not sure where the other 105 comes from. The only thing I can think of is that MM is treating the Primitive Prototype's AC10's crits as explosive ammo for some odd reason.
> 
> edit
> And according to page 195 of IO, the PPAC10's ammo should be 12 for BV, not 21
> /edit

I've fixed the Ammo BV issue and think I've fixed this part of the issue here -  https://github.com/MegaMek/megamek/commit/b627b4cd8701be2047f9d3cd24c4912fe33def63

**Comment by HammerGS** [comment]
I'm not 100% sure of the code but in mech.java line 3790 looks like it's setting M-Pod to subtract 0 when To:AUE pg 195 shows them as 5 and explosive.
