### ISSUE TITLE
Searchlights should not be useable by units deployed as Hidden

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#2323]
Had a problem with a Princess-controlled hidden unit using a searchlight:

![Searchlights on hidden units](https://user-images.githubusercontent.com/70451747/95424103-650d8680-08ff-11eb-9a3b-56946c2c58af.png)

The hidden unit in hex 3010 (at the right) is illuminating the two Manticore tanks in hex 1109 at the left.  Under normal circumstances the unit using the searchlight should be illuminated, but as it is still hidden there is nothing to target.

The main options at play in this game:

- Princess controlled unit
- both the double blind and double blind sensor rules
- Pitch black visibility
- searchlights

Hidden units should start the game with any searchlights turned off.  They should be prevented from turning them on until the unit activates.  They should be able to use the searchlight with the point blank shot from hidden unit rule.

**Comment by NickAragua** [comment]
We're going to need a save for this one. MegaMek has a substantial number of different settings, and it's not practical for somebody to be able to guess all of them correctly.

**Comment by SuperStucco** [comment]
Took a bit to set up.  Users are definitely prohibited from using searchlights when hidden, through the "Hidden units can only spot!" restriction on targeting.  Princess is bypassing this restriction when its other units don't have a working searchlight.

Save file is using 47.11.

[Searchlight.sav.gz](https://github.com/MegaMek/megamek/files/5381309/Searchlight.sav.gz)
![Princess searchlight](https://user-images.githubusercontent.com/70451747/96053841-99bc9900-0e3d-11eb-9cf4-6752d46093dc.png)

Princess has two Warhammers, one "live" (visible in the screen grab) and one hidden in the heavy woods where the searchlight is originating from.  The live Mech has a destroyed searchlight, as does the user Archer.
