### ISSUE TITLE
NPE Displaying Client Options when no skins present

### ISSUE THREAD

**Issue by dericpage** [MegaMek/megamek#233]
Opening the Client Options dialog throws a NullPointerException.
[megameklog.zip](https://github.com/MegaMek/megamek/files/287985/megameklog.zip)

**Comment by arlith** [comment]
This happens when there are no valid skin specifications in `mmconf/skins`.  I added a null-guard to the code, so things don't crash.

**Comment by dericpage** [comment]
Yeah, this looks like it it's partially a packaging error in the MekHQ project since the base MM project ships with the skins dir. It's a good idea to have the null protection in place but the MHQ release process should probably be amended to include the same default skins dir that MM has.

**Comment by pheonixstorm** [comment]
I'm trying for a fix now. Might have something posted soonish

**Comment by arlith** [comment]
The problem is probably that I moved the skins directory from mmconf to mmconf/skins.  I bet the packaging script needs to be updated to reflect that.

**Comment by pheonixstorm** [comment]
Nope, it copies everything over from the mmconf folder. 
![skins](https://cloud.githubusercontent.com/assets/1787879/15635393/8548063c-25ab-11e6-912c-1f2bf67f4c56.png)

Though these are not named the same as what is in my custom build
