### ISSUE TITLE
Report Error for Message ID 3173 (Likely from Ammo Feed Quirk)

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#2335]
Spotted on Casual Joker's feed.  Was only able to get a screen shot.

### Environment
What version of MegaMek does your issue apply to?  47.11
What operating system are you using?  Windows, 

### Description
![image](https://user-images.githubusercontent.com/13752452/95685744-fa867000-0bb6-11eb-8ed7-205948edace9.png)

**Comment by NickAragua** [comment]
Fixed by update included in PR #2315
