### ISSUE TITLE
Corrected Yasha (Interdictor) .mtf

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#2337]
Simple fix to the Yasha (Interdictor). It was missing one instance of Art-IV, and was using ferro-fibrous armor instead of heavy ferro-fibrous. Currently (as of 47.10) reads as an illegal unit due to *either* an ammo bin problem or Artemis-IV taking up a slot (I'm not sure which), but it is a legal unit as per the rules.

[Yasha VTOL (Interdictor).zip](https://github.com/MegaMek/megamek/files/5362522/Yasha.VTOL.Interdictor.zip)

**Comment by HammerGS** [comment]
Fixed as part of https://github.com/MegaMek/megamek/commit/c7b47bfb44aafda65270eeba2074f87af11b690a
