### ISSUE TITLE
[Data] Mechbuster & Protector CF's Not Using Their Images

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#234]
Only noticed this because I'm filling out the news.xml with new technology notifications for the 31st century.  The Mechbuster was not using it's image because was named 'MechBuster instead of MechBuster.

Fixed: chassis "MechBuster" "convfighter/mechbuster.gif"

The Protector CF was using the default CF image when it is the exact same as the Bluehawk so, created an entry for it.

Added: chassis "Protector Combat Support Fighter" "convfighter/bluehawk.gif"

Verified that MM now uses the correct images for units with the above modifications.

[mechset.zip](https://github.com/MegaMek/megamek/files/288044/mechset.zip)

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/3ae0ebfbb1409fbfe355e36546e3c5f99005c3b4
