### ISSUE TITLE
Units unable to flee during tornado 

### ISSUE THREAD

**Issue by AQGadget** [MegaMek/megamek#2343]
Couldn't find any references to this in any open issues

### Environment
Using mekHQ 0.47.9 with weather enabled. Windows 10

### Description
My units are unable to flee during tornados. All the usual requirements are met. They are standing, have mp, start their turn on the board edge. The flee button is available and asks for confirmation that I want to flee, then the 'this unit has not moved' confirmation pops up. Confirming that results in the unit standing still on the board edge. 

I have not attempted to cripple a princess mech and see if they can flee.

**Comment by NickAragua** [comment]
We're going to need a save and logs for this one.

**Comment by AQGadget** [comment]
MekHQ save, customs, logs, Megamek save after turn 1 trying to flee with all friendly units

[tornado.zip](https://github.com/MegaMek/megamek/files/5447125/tornado.zip)

**Comment by AQGadget** [comment]
[tornadoflee3.sav.gz](https://github.com/MegaMek/megamek/files/5447822/tornadoflee3.sav.gz)

Engineered a situation where princess is crippled and withdrawing. The bot is able to flee the map, but my unit, right next to the fleeing bot mech, is unable.
