### ISSUE TITLE
Infantry force assignment tables

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#2345]
Adding to [this issue](https://github.com/MegaMek/megamek/issues/2214#issue-700344161), I've made changes to the force assignment tables to add the generic infantry types.  This also makes a number faction-specific infantry specific to their originating factions, so there isn't oddities like Kurita-named infantry being deployed by a Lyran faction.

[Force tables with generic infantry.zip](https://github.com/MegaMek/megamek/files/5394709/Force.tables.with.generic.infantry.zip)

All changes are for infantry only, except for one minor item:
```
<chassis name='Bluehawk Combat Support Fighter' unitType='Conventional Fighter'>
		<availability>MOC:6,OA.RA:5,FS:2,Periphery:4,DC:2</availability>
		<model name='MSF-42'>
			<availability>General:6</availability>
		</model>
	</chassis>
```

The chassis availability of "... OA.RA:5..." in context appears it should be "... RA.OA:5...", for Raven Alliance/Outworlds Alliance to be consistent with the rest of the entries.  This has been done in the provided files.

Also, is there any other documentation for the force generator XML data outside of the [root]\docs\RAT Stuff folder?  The rat-generator.txt file is a bit short of information (e.g. "Custom files can also be installed in "userdata/data/forcegenerator" and this will take precedence over the distribution files...", but doesn't specify where the path should be/need to create userdata folder/etc.).  
The faction abbreviations are not spelled out in detail, leaving it up to interpretation (e.g. "DC:pm" is... ?  Took a bit of research to figure out its "planetary militia".)
The list of "roles" element contents isn't text-correct (e.g. "Supported values are ... anti-infantry... spec ops..." when it's actually anti_infantry and specops).

Any objection to me getting working on improving the documentation, adding a few documentation comments to the XMLs themselves, and adding an XSD schema to help with intellisense/autocomplete in the era XML files?

**Comment by sixlettervariables** [comment]
Zero concerns with additional documentation!

**Comment by HammerGS** [comment]
Their is an editor built into Megamek. It's accessible via command line. Run the Megamek with -editratgen

![image](https://user-images.githubusercontent.com/13752452/96351577-88f86700-1079-11eb-83d9-6d5ae7b23b76.png)

**Comment by SuperStucco** [comment]
Thanks, the editor kinda-sorta helps - at least as far as the faction names.  I'm finding editing the raw XML to be faster for the rest.

The editor has a few parts that could be improved i.e. roles can only be added, there's no way to remove them.

**Comment by HammerGS** [comment]
Any roles we do need to be in line with the MUL (Master Unit List). If the MUL does't have a role listed it would need to stay blank in Megamek.

**Comment by SuperStucco** [comment]
Hmm... it list roles like recon, EW support, assault, and anti-infantry (among others) which aren't in the MUL.  These *are* toggles in the force generation system though.  Are we talking about the same thing?

Also, the mention of "roles can only be added, there's no way to remove them" means literally that.  I've assigned a role to a model as a test.  And now I can't remove it - it has to be removed through the era XML.

**Comment by HammerGS** [comment]
Added with https://github.com/MegaMek/megamek/commit/13bd14e1abba4afc6606155aa9b7c4584eec0086
