### ISSUE TITLE
[Data] News.xml (not complete)

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#235]
Am working on filling out the news.xml with everything of note from the timeline off sarna.net.  Starting with the 31st century and have made it up to 3020 beginning at 3000.  Have only filled out when new technology becomes available first (that is the most important to me so I know when I need to change my tech level from intro to standard) and would appreciate some proof reading before I get too far and find out this isn't the format or way it should be done.  Am not really interested in making them legitimate news articles since sometimes there isn't enough information provided to write a whole article on, I'm thinking of these being more as notifications to the player of important events and technology occurring and becoming available while they play, like the universe is more alive and moving in the background.  Have not overwritten anything Jay has done but, did fix a 3020 article that mentions the Lyran Alliance which was not created yet so, changed it to Lyran Commonwealth and LAAF to LCAF.

[news.zip](https://github.com/MegaMek/megamek/files/288046/news.zip)

**Comment by arlith** [comment]
This should be a MHQ issue, since the news.xml file is in MHQ and not MM.

**Comment by BLOODWOLF333** [comment]
Dang it dang it dang it dang it
