### ISSUE TITLE
47.11 AtB Big Battle produced MM crash/infinite loop?

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#2356]
### Environment
Version 47.11
Fight generated by AtB, issue originally found in MekHQ integrated Megamek. 
Windows 10
Java version 11.0.8

### Description
Upon loading a game from MekHQ AtB (Big Battle: Convoy Attack), Princess was taking a very long time to make the first move. Checking the logs showed some errors, which may or may not be related (see attached logs). More importantly, after closing Megamek and choosing to save the game before closing, the "Disconnected!" window that popped up after closing was itself locked up, and remained frozen until killed via Task Manager (which also meant killing MekHQ, as MekHQ could not be interacted with until the "Disconnected!" window was closed). As a test, I loaded the battle save in standalone Megamek, and on closing that game (without saving) the normal MM splash screen was also frozen, and again needed to be killed via Task Manager. The CPU and power usage reported by Task Manager for the Java instances looked suspiciously similar to what I saw from a previous (unrelated) infinite loop bug. I have no idea what might actually be causing the loop, but the save and logs are attached. Hopefully this reproduces on other computers so it can be diagnosed. 

### Files
Username: Greyscales
[Greyscales_lockupBug.sav.gz](https://github.com/MegaMek/megamek/files/5427307/Greyscales_lockupBug.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/5427308/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/5427309/mekhqlog.txt)

Edit: For what it's worth, reloading the MekHQ _campaign_ from the previous day's autosave (not having manually saved for some time), advancing to the day of the fight, and starting the fight once more does not seem to have reproduced the bug, even if reloading from the save provided above does. There may be something distinctive about that fight in particular.

**Comment by neoancient** [comment]
I can reproduce this reliably using 0.47.11, but not in the current code. I'm going to close this as resolved.
