### ISSUE TITLE
PSR in Heavy Snowfall also rolling for Swamp modifier

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/megamek#236]
Playing a game on a mixed Open Terrain (8 total sheets) and City Tech (1 sheet) map which is al clear Terrain. Planetary conditions are -10C temp and heavy snowfall. There have been no fires but the PSR rolls are including swamp conditions.

Normally when a snow hex (thin snow in this case) is attacked it is supposed to convert to mud. The locations of the enemy units which prompted this ticket are all in clear, snow covered terrain that has now been attacked.
![snowswamp](https://cloud.githubusercontent.com/assets/1787879/15632790/d6ed3d9a-256a-11e6-9795-8ce6ad8dc53e.png)

[snowswamp.sav.zip](https://github.com/MegaMek/megamek/files/288296/snowswamp.sav.zip)

**Comment by arlith** [comment]
I didn't do a good job when I vetted d259a96a, as it really screwed up Terrain.pilotingModifier.  If a case in a switch statement doesn't have a break, it falls through to the next case.  In d259a96a, most of the case statements had the breaks pulled into conditionals, so if the conditions aren't satisfied, the switch doesn't break, which was the cause of this bug (and a host of others).

**Comment by pheonixstorm** [comment]
Oops. My fault.

**Comment by arlith** [comment]
Writing code creates bugs, it's not a big deal.
