### ISSUE TITLE
RAT editor program "Load" always loads defaults, never custom files

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#2360]
This is a low priority item, as it's likely not used often.

Using the command-line option 

MegaMek.exe -editratgen

... opens a custom window for editing the availability tables used by the MegaMek force generator.  At the bottom of this window are two buttons, "Load" and "Save".

In 47.11 the "Load" button only loads the availability XML data from the default [exe]\data\forcegenerator folder.  While the "Save" button allows for saving virtually anywhere, the editor always loads the files from the default folder regardless of which folder the Load Dialog is pointed to.

Additionally, from what I can determine, if the availability XML files are saved to [exe]\userdata\forcegenerator these take precedence over the default folder contents, but _only_ for the force generator inside MegaMek, not the editor.

**Comment by neoancient** [comment]
I just tested the load button. It replaces the default data with data from the selected directory.
