### ISSUE TITLE
RAT editor should save contents in consistent order

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#2361]
This is a low priority item, as it's likely not used often.

Using the command-line option

MegaMek.exe -editratgen

... opens a custom window for editing the availability tables used by the MegaMek force generator.  At the bottom of this window are two buttons, "Load" and "Save".

In 47.11 when the contents are saved they are not consistent with the original XML files.  The data is identical (except for any deliberate changes), however the order of model elements under some chassis elements are not.  This is a diff view of original (from ZIP) and after saving from the RAT editor:

![RAT editor save errors](https://user-images.githubusercontent.com/70451747/97094580-253ee280-1613-11eb-8046-16e3547ba037.png)

These infantry were not changed in any way in the editor.  However, the order of the model elements in the XML has changed.  This doesn't affect its use in MegaMek, but checking for and validating changes using a diff tool is a nightmare because the content of random chassis elements don't match up.  The re-ordering is not consistent i.e. not alphabetical by 'name' attribute or availability element content.

When the RAT editor saves changes, it should keep everything the same except for what was modified.  If it does have to change order, it should be consistent (e.g. alphabetical by 'name' attribute'); this should also be noted in the documentation so those who add or edit content can easily spot errors.

**Comment by NickAragua** [comment]
I dunno, I think it's a good idea, the current setup makes even minor changes difficult to review.
