### ISSUE TITLE
Add guidelines for unit naming conventions

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#2363]
Over the years as different units have been added, there have been several different styles of name entry.  Mechs and fighters are mostly OK as its easy to follow the chassis/model number.  Vehicles are a mixed batch.  Battle armor and conventional infantry are not so consistent, and gets very messy once different formations (squad vs. point vs. Level I) are used for the same design.  A few examples of existing battle armor units in MegaMek:

Chassis: Nighthawk PA(L)
Model: Mk. XXI
Combined: Nighthawk PA(L) Mk. XXI
Notes: 4 suit squad, armed with Mauser 960

Chassis: IS Standard Battle Armor
Model: (Level I) [Flamer]
Combined: IS Standard Battle Armor (Level I) [Flamer]
Notes: 6 suit squad/Level I, armed with flamer

Chassis: Purifier Adaptive Battle Armor
Model: [Laser]
Combined: Purifier Adaptive Battle Armor [Laser]
Notes: 6 suit squad/Level I, armed with ER small laser

Chassis: Infiltrator Mk. II Battle Armor
Model: 'Puma'
Combined: Infiltrator Mk. II Battle Armor 'Puma'
Notes: 4 suit squad, standard design/MagShot gauss

Chassis: GD Infiltrator Suit
Model: (Sensors)
Combined: GD Infiltrator Suit (Sensors)
Notes: 4 suit squad, armed with David gauss

Chassis: Corona Battle Armor
Model: (SRM)
Combined: Corona Battle Armor (SRM)
Notes: 5 suit squad/point, armed with SRM 5/flamer/recoilless rifle

I would like to see some work towards standardizing how the various sizes/features are applied to these names.

For battle armor naming I would like to see documentation with this kind of guideline:

Chassis: [Name] [ Exoskeleton | PA(L) | BA ]  [ Squad | Point | Level I ]
Model: "(model name)" or "[primary weapon]" for modular configurations

So the above example BA names would look like this:
Chassis: Nighthawk Mk. XXI PA(L) Squad
Model: [Mauser 960]

Chassis: IS Standard BA Level I
Model: [Flamer]

Chassis: Purifier BA Level I
Model: [ERSL]

Chassis: Infiltrator Mk. II BA Squad
Model: (Standard)

Chassis: Gray Death Infiltrator BA Squad
Model: (Sensors)

Chassis: Corona BA Point
Model: (SRM)

Similar guidelines would be provided for each unit type.

This guideline would be put into place for the next stable release, to handle units added after that.  I would like to have existing battle armor and conventional infantry units eventually renamed to also meet the standards sometime after the next stable release.  Changing names is potentially breaking to existing campaigns (hence waiting until after the next stable), so the original named units can be bundled up for separate download, similar to the pilot pictures, to those who want to use them.

That's a lot of work, including the various tie-ins (mechset.txt, force builder, etc.), so I'm willing to do most of the work on that.

**Comment by HammerGS** [comment]
Our naming guidelines are designed to align with the MUL and we won't be changing them.
