### ISSUE TITLE
Incorrect battle armor manipulator location

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#2365]
In 47.11 (and I don't know how far back), many of the data files for first-gen battle armor have the battle claw on the wrong arm i.e. it should be opposite the "gun arm", not on the same arm.

Files with updated manipulator location are attached.

[BA Manipulator Fix.zip](https://github.com/MegaMek/megamek/files/5461648/BA.Manipulator.Fix.zip)

**Comment by HammerGS** [comment]
Add with https://github.com/MegaMek/megamek/commit/13bd14e1abba4afc6606155aa9b7c4584eec0086
