### ISSUE TITLE
Odd interaction between Modular Armor and Hardened Armor

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#2371]
Playing around with Hardened and Modular armor built the attached unit and the movement should be 0-1-2 but getting 0-(-1)-1.  I think it might be applying the modular armor reduction multiple times.

### Environment
What version of MekLab does your issue apply to?  MML from Repo
What operating system are you using?  Windows, 
What java version are you using?  47.12

### Files
[Tank Boi.zip](https://github.com/MegaMek/megameklab/files/5468350/Tank.Boi.zip)

**Comment by neoancient** [comment]
The rules for modular armor say the run MP is recalculated based on the new walk MP, so it should be 0-0-1 (the modular armor also reduces jump).
