### ISSUE TITLE
RFE - Option to disable Save Before Quit Message

### ISSUE THREAD

**Issue by IReallyHateGithub** [MegaMek/megamek#2374]
Currently, MegaMek asks me if I would like to save the game before exiting, regardless of whether I am in a game, or in the lobby. I wish to be able to disable this message, either via checkbox on the message, or via Client Settings

**Comment by HammerGS** [comment]
I concur this is annoying. Especially in the lobby since I'm often jumping in and out of Megamek to check or test things.
