### ISSUE TITLE
0.47.13 - odd rendering issue - "illuminated rocks"

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#2397]
0.47.13 standalone
Windows 10
Java 11.0.8

Nothing particularly major, just an odd rendering glitch, as some Rough hexes were in the shadow cast by high ground, and were fully in shadow, while in some other hexes that should have been equally affected, the base hex was shadowed, but the Rough 'boulders' were not in shadow. Did they have their own mood lighting?

Can be seen in attached screenshot under the north-east end of the bridge, while slightly to the north, there are some fully-shadowed Rough hexes. Also visible next to the narrowing of the gorge to the south.

![20201112-0200](https://user-images.githubusercontent.com/26851644/98946325-a6d7b100-24eb-11eb-9b54-b48987e8443e.png)

**Comment by SJuliez** [comment]
The shadow system is working under some limiting circumstances. The program part that draws the board (I call it "boardview", cause thats the name of the java program) and the shadows gets a stack of images delivered from the hex tile system (that handles the tilesets) with no information what these images represent. It just draws them. If there's only rough in a hex, the boardview could guess what the image is but if theres e.g. a road and a woods, it can't. So some shadow/terrain interactions are really wonky and we'd need an upgrade for the information delivery to the boardview to improve it.

**Comment by SimonLandmine** [comment]
That all makes sense. No problem! I just noticed it because otherwise the shadow system is really good, so it's only an occasional small glitch that stands out.
Might as well close this then, unless anyone wants it kept open as a reminder of some kind.
