### ISSUE TITLE
RFE - 'Mouse wheel zooms map' Client Settings option upgrade

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#2399]
When the 'Mouse wheel zooms map' Client Settings option is unchecked, the mouse wheel scrolls the map, with CTRL+wheel zooming the map.
However, when 'Mouse wheel zooms map' option is checked, the mouse wheel zooms the map ... and so does CTRL+wheel, leaving no mouse-based option to scroll the map.

Would it be possible to configure things so that, when 'Mouse wheel zooms map' is checked, CTRL+wheel scrolls the map?

**Comment by gsparks3** [comment]
You can right-click and drag to move the map, but it's not nearly as fast as scrolling.
