### ISSUE TITLE
[0.41.19 : Error] Black Eagle Dropship cannot fire from LRM Bay

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#240]
Tested using freshly loaded Black Eagle dropship from the lobby. Savegame attached. Load savegame and try shooting target at 2326 using LRM Bay [LS].

[LRMBayCannotShoot.sav.gz](https://github.com/MegaMek/megamek/files/304108/LRMBayCannotShoot.sav.gz)

**Comment by HammerGS** [comment]
There is an issue with the unit file and its ammo.  The ammo was separated from its launcher.  

I've fixed it in the file.  I've got other unit files to work on, I'll commit the fix with those and add commit information here when I do.

**Comment by HammerGS** [comment]
Fixed with

https://github.com/MegaMek/megamek/commit/2e79e87ce7843e21de48228962fca4ac39864bc3
