### ISSUE TITLE
RFE - "Reinforce From MUL" can select player to reinforce

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#2403]
At present the "Reinforce From MUL" function only seems to reinforce the player who runs it. Would it be possible to amend it so that it is possible to choose which player is reinforced? That way, additional forces could be gifted to Princess bot players, or to other players as part of a scenario?

There was also a question on Discord as to whether there could be a way to have 'triggered reinforcement' programmed into a scenario, so that e.g. the destruction of a unit or building results in the arrival of additional forces.

**Comment by plinythemechwarrior** [comment]
This would be a very useful feature. I GM a campaign with 6-9 regular players. Some published scenarios have indeterminate reinforcements such that you cannot program, in advance, when units should arrive (eg: "reinforcements arrive on turn 20, or when the last of the original force is destroyed.") It is cumbersome to have separate MUL files for each player that would receive reinforcements, which appears to be the only workaround besides reinforce and traitoring units, which is cumbersome.

**Comment by SimonLandmine** [comment]
I should note that, with this RFE, you would still need to have pre-prepared separate MULs for each player's reinforcements, the only change would be to give the ability to select which player they were allocated to. That probably requires the least changes to the program.
