### ISSUE TITLE
3150 Timberwolf (Mad Cat) naming issue

### ISSUE THREAD

**Issue by mouldsgame** [MegaMek/megamek#2414]
### Environment
What version of MekHQ does your issue apply to? 47.14

### Description
The new configurations of the Mad Cat (Timberwolf) are listed as TImberwolf (Mad Cat).  Because of the MekHQ treats this as a different unit, does not give it the Mad Cat icon or allow you to  reconfigure into those configuratioins
![Timber Wolf](https://user-images.githubusercontent.com/49316494/99758436-aa58d280-2abf-11eb-8ab5-c17dbf1c9423.png)

**Comment by HammerGS** [comment]
Moved to Megamek tracker to handle data.

**Comment by HammerGS** [comment]
I've tested adding the names to the name changes text file and doesn't seem to work for sprites.

Timber Wolf (Mad Cat) M|Mad Cat (Timber Wolf) M
Timber Wolf (Mad Cat) N|Mad Cat (Timber Wolf) N
Timber Wolf (Mad Cat) T|Mad Cat (Timber Wolf) T
Timber Wolf (Mad Cat) W|Mad Cat (Timber Wolf) W

@neoancient wrote the original code so note sure if I've got something messed up in the formating.
[name_changes.txt](https://github.com/MegaMek/megamek/files/5571260/name_changes.txt)

**Comment by neoancient** [comment]
The name changes file only affects retrieving the MechSummary, which is not involved in loading sprites.
