### ISSUE TITLE
Unit Can Self Destruct and Stackpole in same turn

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/megamek#242]
Since Self Destruct is the first thing to happen in Weapons Phase. Suggest having Stackpoles check for Self Destructs.

From Game Log

`Weapon Attack Phase
-------------------
    BattleMaster BLR-1G (Andies) Checking for self destruct on 3, roll is 4: EXPLODES!
        Start Secondary Damage Report.
        >BattleMaster BLR-1G (Andies) suffers catastrophic damage, but the autoeject system was engaged.
    
BattleMaster BLR-1G (Andies) must make a piloting skill check (landing in clear terrain).
    Needs 7 [3 (ejecting) + 5 (Mech is prone) + 1 (automatic ejection) - 2 (landing in clear terrain)], rolls 3 : fails.

        Pilot of MechWarrior Lieutenant Dejan Martic (Andies) "Lieutenant Dejan Martic" takes 2 damage.            The pilot ejects safely!
*** BattleMaster BLR-1G (Andies) DESTROYED by ejection! ***
        Grasshopper GHR-5H (Death Commando's) is hit for 34 damage!
        Grasshopper GHR-5H (Death Commando's) takes 5 damage to LL.
            21 Armor remaining.
        Grasshopper GHR-5H (Death Commando's) takes 5 damage to RA.
            17 Armor remaining.
        Grasshopper GHR-5H (Death Commando's) takes 5 damage to RT.
            15 Armor remaining.
        Grasshopper GHR-5H (Death Commando's) takes 5 damage to LL.
            16 Armor remaining.
        Grasshopper GHR-5H (Death Commando's) takes 5 damage to LA (critical).
            17 Armor remaining.
            Critical hit on LA. Roll is 5; no effect.
        Grasshopper GHR-5H (Death Commando's) takes 5 damage to RT.
            10 Armor remaining.
        Grasshopper GHR-5H (Death Commando's) takes 4 damage to LT.
            16 Armor remaining.

        Ostscout OTT-7J (Death Commando's) is hit for 17 damage!
        Ostscout OTT-7J (Death Commando's) takes 5 damage to LL.
             SECTION DESTROYED.
        1 damage transfers to LT.
            Critical hit on LL. Roll is 6; no effect.
        Ostscout OTT-7J (Death Commando's) takes 1 damage to LT.
            8 Armor remaining.
        Ostscout OTT-7J (Death Commando's) takes 5 damage to RA.
            Armor destroyed.
             5 Internal Structure remaining.
            Critical hit on RA. Roll is 7; no effect.
        Ostscout OTT-7J (Death Commando's) takes 5 damage to CT.
            2 Armor remaining.
        Ostscout OTT-7J (Death Commando's) takes 2 damage to LA.
            4 Armor remaining.

        End Secondary Damage Report.

Weapons fire for Warhammer WHM-6L (Death Commando's)
    PPC at Griffin GRF-1N (Andies); needs 4, rolls 7 :  - Direct Blow - hits  (using Right Side table) LTR
        Griffin GRF-1N (Andies) takes 11 damage to LTR.
             SECTION DESTROYED.
LIMB BLOWN OFF Left Arm blown off.
        4 damage transfers to CTR.
            Critical hit on LT. Roll is (9+3) = 12; 2 locations.
            Location is empty, so criticals transfer to CT.
            CRITICAL HIT on Heat Sink.
            CRITICAL HIT on Standard Gyro.
        Griffin GRF-1N (Andies) takes 4 damage to CTR.
             8 Internal Structure remaining.
            Critical hit on CT. Roll is (3+3) = 6; no effect.

    Medium Laser at Griffin GRF-1N (Andies); needs 6, rolls 7 : hits  (using Right Side table) HD
        Griffin GRF-1N (Andies) takes 5 damage to HD.
            3 Armor remaining.

        Pilot of Griffin GRF-1N (Andies) "Lieutenant Colonel Jeevana  Uttara" takes 1 damage.        
Pilot of Griffin GRF-1N (Andies) "Lieutenant Colonel Jeevana  Uttara" needs a 3 to stay conscious.  Rolls 2 : blacks out.

Weapons fire for Grasshopper GHR-5H (Death Commando's)
    Medium Laser at BattleMaster BLR-1G (Andies); needs -1, rolls 5 :  - Direct Blow - hits  (using Rear table) CTR
        BattleMaster BLR-1G (Andies) takes 7 damage to CTR.
             6 Internal Structure remaining.
            Critical hit on CT. Roll is (3+2) = 5; no effect.

    Medium Laser at BattleMaster BLR-1G (Andies); needs -1, rolls 4 : hits  (using Rear table) RL
        BattleMaster BLR-1G (Andies) takes 6 damage to RL.
        6 damage transfers to RTR.
        BattleMaster BLR-1G (Andies) takes 6 damage to RTR.
        6 damage transfers to CTR.
        BattleMaster BLR-1G (Andies) takes 6 damage to CTR.
             SECTION DESTROYED.
        BattleMaster BLR-1G (Andies) has taken 5 engine hits this phase.
        Checking for engine explosion on 10, roll is 11.
        ***The safety systems on the engine fail catastrophically resulting in a cascading engine failure!

        Start Secondary Damage Report.
        Grasshopper GHR-5H (Death Commando's) is hit for 34 damage!
        Grasshopper GHR-5H (Death Commando's) takes 5 damage to CT.
            25 Armor remaining.
        Grasshopper GHR-5H (Death Commando's) takes 5 damage to RT.
            5 Armor remaining.
        Grasshopper GHR-5H (Death Commando's) takes 5 damage to LL.
            11 Armor remaining.
        Grasshopper GHR-5H (Death Commando's) takes 5 damage to LA.
            12 Armor remaining.
        Grasshopper GHR-5H (Death Commando's) takes 5 damage to LA.
            7 Armor remaining.
        Grasshopper GHR-5H (Death Commando's) takes 5 damage to CT.
            20 Armor remaining.
        Grasshopper GHR-5H (Death Commando's) takes 4 damage to CT.
            16 Armor remaining.

        Ostscout OTT-7J (Death Commando's) is hit for 17 damage!
        Ostscout OTT-7J (Death Commando's) takes 5 damage to LT.
            3 Armor remaining.
        Ostscout OTT-7J (Death Commando's) takes 5 damage to LL.
        5 damage transfers to LT.
        Ostscout OTT-7J (Death Commando's) takes 5 damage to LT.
            Armor destroyed.
             4 Internal Structure remaining.
            Critical hit on LT. Roll is 8; no effect.
        Ostscout OTT-7J (Death Commando's) takes 5 damage to LA.
            Armor destroyed.
             5 Internal Structure remaining.
            Critical hit on LA. Roll is 8; no effect.
        Ostscout OTT-7J (Death Commando's) takes 2 damage to RL.
            4 Armor remaining.

        End Secondary Damage Report.
            Critical hit on CT. Roll is (7+1) = 8; no effect.
`

**Comment by arlith** [comment]
`Entity` has two states related to destruction: doomed and destroyed.  Doomed units are set to be destroyed, and will be destroyed at the end of the phase.  Destroyed units are destroyed.  `Server.checkEngineExplosion` won't make the check for destroyed entities, but it must operate on doomed entities (because a 'mech that has taken 3+ engine criticals is doomed).

Self destructing will doom an `Entity` but it won't destroy it; it's possible that it could set the state of the `Entity` to destroyed, but I fear this could lead to other bugs down the road.

`Entity` already tracks two self destruct states: selfDestructing and selfDestructInitiated.  The former tracks whether the `Entity` is starting to self destruct, and the later represents a succeeded PSR, with the unit set to explode at the start of the weapons phase.

To fix this, I added a new state, selfDestructedThisTurn, which is set to true once the self destruction occurs, and is reset at the start of a new round.  `Server.checkEngineExplosion` now checks this state and won't explode engines that have self destructed already this turn.
