### ISSUE TITLE
Overweight default unit (Bulldog Fuel Cell version)

### ISSUE THREAD

**Issue by NimoStar** [MegaMek/megamek#2422]
The bulldog vehicle labeled (Fuel Cell), on IS advanced tech, is two tons overweight, therefore invalid.

I could fix this but I don't have the actual thing record sheet to look at how is it really, or if the error is in the original version. It should be fixed regardless since this is an official design.

Reproduce:
- Set type to tank
- Set tech to IS advanced
- Search bulldog (or bull dog, idk)
- Load Fuel Cell Version (2 mml-5, 1 Snub PPC)
- 62 tons for 60 ton vehicle error

**Comment by HammerGS** [comment]
Unfixable at this point. Its information is only available on the RS 3145 NTNU book. Our unit is built in accordance with the Record sheet. The error is likely on the RS product.

For reference CGL has 100 or so units that are wrong.

**Comment by NimoStar** [comment]
I see. However, this does mean the design is unusable in a skirmish when the option "Allow invalid designs" is not checked. And it is unchecked by default. Meaning that normally, you can't use some canon, published designs, while in TableTop, you could. 

Unless you make all fixs manually yourself...
![2020-11-24 20_48_46-gh - MegaMek](https://user-images.githubusercontent.com/38392980/100165021-f2993b80-2e97-11eb-98a8-0b0baad7d063.jpg)

**Comment by neoancient** [comment]
The default tech level is standard. If you want to use any of the numerous advanced and experimental canon units you have to change an option. This is no different.

**Comment by NimoStar** [comment]
I do think it is quite different, since advanced and experimental units have to be explicitely constructed as such, whereas these units were never intended to be "invalid" (which isn't a tech level).

**Comment by sixlettervariables** [comment]
Invalid Design simply means the unit does not follow construction rules. If you believe the unit should be valid per construction rules, I would raise a construction rules question with CGL to have them fix the rules.

As already stated, MM doesn't care about canon when reporting invalid designs. You're free to allow or disallow invalid designs per construction rules, just as advanced tech levels or any of the hundreds of other MM options.
