### ISSUE TITLE
Bridge failed to collapse when weight limit exceeded

### ISSUE THREAD

**Issue by IanBellomy** [MegaMek/megamek#2423]
### Environment
v0.46.1
OSX 10.15.7
Java 8 Update 251
35x35 Frozen City Princess Edition.board

### Description
A 65 ton thunderbolt ran across a bridge hex with CF 58. The bridge did not collapse. 
FWIW, later in the game a different building did collapse when weight limit was exceeded during movement.

<img width="488" alt="Screen Shot 2020-11-23 at 10 39 19 AM" src="https://user-images.githubusercontent.com/17239616/99983098-701a5a00-2d79-11eb-8cbe-6090dc25110e.png">
[jags.sav.gz](https://github.com/MegaMek/megamek/files/5584145/jags.sav.gz)

**Comment by NickAragua** [comment]
A. Github appears to have eaten your save and B. This is fixed in the current dev version.
