### ISSUE TITLE
NPE in doEntityDisplacement

### ISSUE THREAD

**Issue by jpawlicki** [MegaMek/megamek#2430]
### Environment
Standalone MegaMek v0.46.1
Java version 1.8.0_271
Platform Windows 10 10.0 (amd64)

### Description
Exception in thread "Packet Pump" java.lang.NullPointerException
	at megamek.server.Server.doEntityDisplacement(Server.java:13546)
	at megamek.server.Server.resolveDfaAttack(Server.java:19918)
	at megamek.server.Server.resolvePhysicalAttack(Server.java:34925)
	at megamek.server.Server.resolvePhysicalAttacks(Server.java:15939)
	at megamek.server.Server.endCurrentPhase(Server.java:3181)
	at megamek.server.Server.changeToNextTurn(Server.java:3494)
	at megamek.server.Server.endCurrentTurn(Server.java:2484)
	at megamek.server.Server.receiveAttack(Server.java:14126)
	at megamek.server.Server.handle(Server.java:32866)
	at megamek.server.Server$PacketPump.run(Server.java:369)

Physical Attack Phase.
SQR-L conducts a DFA against I1A. SQR-L#2 and DJN-1 also declared kick and punch attacks against I1A. I1A has declared a kick against SQR-L#2.

The DFA is successful (I think) and displaces I1A down the hill into J2A. The player controlling J2A is given the option to step out of the domino effect (forward or backward). This puzzled us because stepping forward would step into SQR-L#2. The player decided to step forward and see it it would displace SQR-L#2. The server and client then became unresponsive and the above exception stack trace appeared in the log.

The screenshot is garbled a bit because we saved after the exception and reloaded. On reloading the save, we see that the game has displaced I1A but not J2A, nor resolved any of the physical attacks. The game cannot proceed (neither player can take an action).

### Files
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/5593906/autosave.sav.gz)

[megameklog_npe.txt](https://github.com/MegaMek/megamek/files/5593909/megameklog_npe.txt)

Players: "Josh" (controls the DFA'ing unit), "Mike" (controls the opfor)

**Comment by jpawlicki** [comment]
![npe](https://user-images.githubusercontent.com/2081348/100173031-a64dfb80-2e97-11eb-944e-cfda1812cab2.png)

Forgot the illustration, sorry.

**Comment by neoancient** [comment]
I can reproduce this in the current code. Here is a saved game at the beginning of the physical attack phase: 
[dfa_displacement_test.sav.gz](https://github.com/MegaMek/megamek/files/5600717/dfa_displacement_test.sav.gz)
Player name is test.
The MovePath sent by the client is correct, but the deserialized object received by the client feedback request is not.

**Comment by neoancient** [comment]
Now that I've slept and come back to this, I see that the path sent by the client is not what it's supposed to be, and it's tied to the failure to recognize that moving forward is a stacking violation, and thus not a legal move.
