### ISSUE TITLE
Variable tech level toggle working incorrectly

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#2436]
v.47.14

Enabling the "variable tech level" option currently shows all illegal units, regardless of whether they are invalid due to the introductory date of their components or due to construction issues (eg:overweight).

Conversely, enabling the "allow invalid unit designs" option does not show any invalid units.

**Comment by neoancient** [comment]
I don't understand the problem. The variable tech level option has nothing to do with unit legality. It determines what tech level it is in a given year as its components move from prototype to production to common.

**Comment by AlphaSled** [comment]
I wasn't clear, sorry.

If I currently check the "variable tech level" option, it will show illegal units (those listed as "F" under tech level) in the unit selection box--units that weren't previously available to choose from.

For example, if I do a search for the Bulldog tank with "variable tech level" unchecked, I get four results. However, if I check "variable tech levels", a fifth result appears in the search box: the Bulldog (Cell), a unit that is 2.5 tons overweight.

My understanding is that the Bulldog (Cell) should only appear if the "Allow invalid unit designs" option is checked. As it stands, though, "Allow invalid unit designs" doesn't cause the Bulldog (Cell) (or other illegal/invalid designs) to show up in the search bar, and so I'm unsure as to what the "Allow invalid unit designs" toggle actually does.

**Comment by neoancient** [comment]
It causes the server to reject any invalid unit that you attempt to add to the game. I can't reproduce your example. I see invalid units regardless of the settings of those particular examples.

**Comment by gsparks3** [comment]
After further testing, the reason the Bulldog (Cell) wasn't showing up is because it's being treated as part of the IS Advanced tech category, despite all of its components being Standard tech by its introduction year. Having Variable Tech Level active pushes it down to Standard and therefore makes it show up given AlphaSled's unit selector settings. If you make sure to have the Advanced category enabled and selected, it shows up without needing Variable Tech Level active.

**Comment by AlphaSled** [comment]
Can confirm, gsparks helped me out in testing it. Ticket can be closed.

**Comment by neoancient** [comment]
Nevertheless, I don't think invalid units should show up in the selector when they're not allowed in the game, so I've opened a PR to address that.
