### ISSUE TITLE
RFE: Please include Tigershark's Table in docs

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/megamek#244]
Reference... that way people can know what the Option does.

http://bg.battletech.com/forums/index.php/topic,30779.0.html

**Comment by arlith** [comment]
I created a new file in docs: alternativePilotSkillBV.txt.  I copied the post text on the forums to this doc file, and also indicated that the text was copied from the forums, with a link to the post (this includes the table).  I then updated the tooltip to point to this file instead of the forums.
