### ISSUE TITLE
Filename contains non en_US.UTF-8 character. Prevents file from being unpacked.

### ISSUE THREAD

**Issue by mjbroekman** [MegaMek/megamek#2446]
### Environment
What version of MekHQ does your issue apply to? 0.47.14
What operating system are you using?  Mac

### Description
Describe the issue and provide screenshots ingame if able.
Unpacking the MacOS tar file, I get the following error because of the non en_US-UTF-8 character in the filename:
mekhq-0.47.14/data/boards/unofficial/Dervs/Map Pack 3/35x35 Eisenj�ger.board: Can't create 'mekhq-0.47.14/data/boards/unofficial/Dervs/Map Pack 3/35x35 Eisenj�ger.board'

All other files were unpacked successfully, but the ä in the filename prevents that file from being unpacked successfully.

> mycomputer:/Games/MegaMek$ tar -ztf ~/Downloads/mekhq-0.47.14.tar.gz | wc -l
>   22055
> mycomputer:/Games/MegaMek$ find mekhq-0.47.14 | wc -l
>   22054

**Comment by neoancient** [comment]
Fixed by #2479
