### ISSUE TITLE
47.14 Bridge elevation bugs - charging from bridge & reversing from bridge

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#2447]
MegaMek 47.14 (standalone)
Windows 10
Java 11.0.8

Vehicles on height six bridge encountered two issues ...

1. Unable to Charge unit on terrain at end of bridge (at same level as bridge surface). Pop-up message states "Target must be within 1 elevation level".
2. Reversing backwards from bridge onto terrain at end (at same level as bridge surface) triggered a 'Moving backwards over elevation change' warning.

Issue discovered in 47.13 and re-tested in 47.14.

See attached savegame to replicate. Player name "SimonLandmine", friendly fire on for demonstration of charge.
To replicate issue 1, attempt to charge Hornet (ID:3) with Manticore (ID:1).
To replicate issue 2, attempt to use 'Back Up' to reverse Manticore (ID:2) off the bridge.

As these issues both relate to bridge/elevation calculations, I suspect that they might be resulting from the same cause.

[20201128-2229.sav.gz](https://github.com/MegaMek/megamek/files/5611322/20201128-2229.sav.gz)

**Comment by SimonLandmine** [comment]
(Someone recently referred to me on Discord as "the bridge bug guy". [shrugs])

**Comment by SJuliez** [comment]
I believe that is a unique title.
