### ISSUE TITLE
[Feature] Grounded aero units in scenarios

### ISSUE THREAD

**Issue by TrailblazerDan** [MegaMek/megamek#246]
It's not currently possible to have a DropShip, fighter or other air unit deploy grounded in a scenario (MMS) file. This would be a nice feature.

(Previously a feature request on SF: https://sourceforge.net/p/megamek/feature-requests/1172/)

**Comment by HammerGS** [comment]
Recently there was an overall of the scenario (MMS) files and here is a link to all the set-up options.

http://megamek.info/forums/index.php?topic=2381.msg16120#msg16120

**Comment by TrailblazerDan** [comment]
Thank you!  I didn't realize so much had been done on scenarios.  Really
appreciate the work.
