### ISSUE TITLE
Cannot fix vehicle engine/motive damage

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#2465]
In 47.14, and for several prior releases, if I try to fix engine/motive damage on a vehicle in the Repair Bay it stays immobile (not just the listed 0 MP - actual motive damage).  Even under the GM tools for editing damage, I can unclick all the checked-off boxes for motive damage, click OK, and when checked again the boxes are still ticked.  Sometimes this goes away if I save and close MekHQ before trying repairs but not always.

Please check the attached campaign file.  There is a single vehicle present, with engine/motive damage.  In the Hangar, right-click and GM Mode => Edit damage...  Uncheck one or more boxes under Motive damage and OK the dialog.  Go to the Repair Bay tab and handle the Repair Motive System task (GM complete if necessary).  Go back to the Hangar and again go through GM Mode => Edit damage...  All motive damage boxes are still checked.  Uncheck all boxes, and OK the dialog.  Once again go through GM Mode => Edit damage...  All motive damage boxes are still checked.

[Vehicle engine fix.cpnx.gz](https://github.com/MegaMek/mekhq/files/5618256/Vehicle.engine.fix.cpnx.gz)

**Comment by sixlettervariables** [comment]
Okay this is going to be resolved partially in MHQ when the next dev release comes out. You'll be able to use GM Restore or GM Edit Damage to fix crippled motive systems on vehicles.

NOTE: you will _still_ see Crippled if the vehicle is unmanned. That was not addressed in this fix.
