### ISSUE TITLE
[Feature] Non-standard ammo in scenarios

### ISSUE THREAD

**Issue by TrailblazerDan** [MegaMek/megamek#247]
It would be awesome to have the ability to include units with special ammo (precision AC ammo, thunder LRMs, etc) in the initial forces in a scenario (MMS) file.

(Previously on SF: https://sourceforge.net/p/megamek/feature-requests/1173/)

**Comment by HammerGS** [comment]
Recently there was an overall of the scenario (MMS) files and here is a link to all the set-up options.

http://megamek.info/forums/index.php?topic=2381.msg16120#msg16120
