### ISSUE TITLE
Princess Bot: Jump movement with battle armor and infantry

### ISSUE THREAD

**Issue by TrailblazerDan** [MegaMek/megamek#249]
Princess doesn't currently seem to be able to jump with battle armor or infantry units.

(Previously on SF: https://sourceforge.net/p/megamek/feature-requests/1287/)

**Comment by arlith** [comment]
In my tests, Princess jumps  with a  Jump Platoon, and Elementals.  Perhaps this is more a bug related to certain circumstances?

**Comment by NickAragua** [comment]
As of some time ago, the bot will consider, though not necessarily undertake, jump movement with infantry and BA.
