### ISSUE TITLE
47.14 Hidden unit can't move immediately when becoming active during movement phase.  

### ISSUE THREAD

**Issue by orcmaul** [MegaMek/megamek#2497]
A hidden unit set to activate in the movement phase in the previous turn becomes active in the new turn but despite showing that it has full movement points for walk, run, and jump can not walk, run, jump, charge, or DFA.  Charge and DFA give error message indicating unit can't reach target hex.  

Repro

1. Start two clients. Make one player1 and have him host the game. Make the other player2 and have him connect to the game.
2. Give each unit a mech (I chose a wsp-1a wasp for player1 and a stg-3r stinger for player2.
3. Enable hidden unit rule in game options.
4. Configure the player1's wasp to be hidden.
5. Choose a map sheet with buildings that are at least two levels tall or a map with woods hexes.
6. Start game.
7. Deploy player1's wasp to a building hex or a woods hex where player2 can close to a distance of two hexes and player1 will have LOS to player2's position.
8. Deploy player2's stinger at least two hexes away from player1 to avoid discovery of the unit.
9. During the movement or firing phase have player1 view his wasp, switch to the extras tab, and set the unit to activate during the next movement phase.  
10. Complete phases until wasp is active during the movement phase.  Note that all movement is marked in grey numbers which indicate it can't move there with it's remaining MPs and that charges and DFAs can't be completed because the unit is unable to reach the target hex.  If you input a movement ignoring the grey numbers and click done the game will report you are ending the unit's movement phase without having moved.  The unit does not move even if movement is plotted.  

![hiddenunitcannotmoveafteractivating](https://user-images.githubusercontent.com/75004088/101584551-d070e480-3992-11eb-9a7d-163cefe7f960.png)

[hiddenunitcannotmoveimmediatelyafterbecomingactivebefore.sav.gz](https://github.com/MegaMek/megamek/files/5663477/hiddenunitcannotmoveimmediatelyafterbecomingactivebefore.sav.gz)

[hiddenunitcannotmoveimmediatelyafterbecomingactivenow.sav.gz](https://github.com/MegaMek/megamek/files/5663478/hiddenunitcannotmoveimmediatelyafterbecomingactivenow.sav.gz)

**Comment by HammerGS** [comment]
Which rule set are you getting this from? BMM rewrote Hidden units, and we are using the original implementation.

**Comment by orcmaul** [comment]
Total Warfare pg.259 "However, if a player plans to move a hidden unit, they must reveal it at the start of the Movement Phase."
Battlemech Manual pg.82 "However, if a player plans to move a hidden ’Mech, they must reveal it at the start of the Movement Phase."
Megamek currently requires that you activate a unit in the movement or firing phases prior to the phase you want to move or fire in.  (I haven't tested physical attacks phase or other phases you have access to the map view in like indirect targeting)

**Comment by orcmaul** [comment]
I said that stuff above and I think it's missing the point.  In the turn where you are supposed to be able to move you can't move.  That's the big takeaway here.  You've gone through all of the steps to activate the hidden unit and it should be active now and yet you can't move.  It only happens if you set a unit to unmask in the movement phase.  If you activated in the previous firing phase the unit works normally in the next movement phase.
