### ISSUE TITLE
Problems with camo and Megamek

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/megamek#2499]
Megamek 47.14

Camouflage on my Megamek games has been behaving...badly.

The attached unit always spawns with my team colours, even though the campaign options should prevent that.

And on this particular game, the allied civilian and the enemy forces have the same colour in the lobby, even if the Draconis Combine forces have "green" camo when I enter the camo setting menu.

The "No Camo" folder, which I suppose should hold the basic colours for camo, has only one option.

![Camo Bug](https://user-images.githubusercontent.com/67933202/101788297-d6cca100-3af7-11eb-9f61-b8c27f09a02b.png)

Edit:
A few extra details:
- In MekHQ, the ally color is red and the enemy's green, but all the opfor on the mission have been in red camo
- The exceptions are scenarios with allied forces like civilians and allied lances, where the enemy spawns in green, allies in red
- This is the first time allied civilians and enemy forces spawned in the same colour
- I can choose any camo in the lobby for individual units, except any basic color (red green, yellow, etc). Those don't show anywhere
- I can choose those basic colours for players when changing the players colours on the left in the lobby

Files
[megameklog.zip](https://github.com/MegaMek/megamek/files/5674911/megameklog.zip)
[mekhqlog.zip](https://github.com/MegaMek/megamek/files/5674912/mekhqlog.zip)
[CamoBug.cpnx.gz](https://github.com/MegaMek/megamek/files/5674913/CamoBug.cpnx.gz)

**Comment by SJuliez** [comment]
The last two points
- I can choose any camo in the lobby for individual units, except any basic color (red green, yellow, etc). Those don't show anywhere
- I can choose those basic colours for players when changing the players colours on the left in the lobby
are working normally. As an individual camo, you can only choose a camo image. Choosing a color reverts to the player's camo (or color, whichever is chosen at the time).

**Comment by Windchild292** [comment]
These are being handled as part of my icon rework.

**Comment by Windchild292** [comment]
This is largely subsumed by https://github.com/MegaMek/mekhq/issues/2318 (as MekHQ is the proper tracker), with colours being expanded and fixed as part of https://github.com/MegaMek/megamek/pull/2531
