### ISSUE TITLE
47.14 Prosthetic leg MASC issues

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#2505]
Interstellar Operations page 83-84 states that "Attacks _against_ infantry units equipped with PL-MASC suffer a +1 to-hit modifier to account for these troopers' improved ability to dodge and weave in combat." Code for a +1 to-hit modifier related to PL-MASC [exists](https://github.com/MegaMek/megamek/blob/a034cc6a9ed6c905d7a305145841a8b341666bb5/megamek/src/megamek/common/actions/WeaponAttackAction.java#L3917), but gives the +1 to-hit malus to the infantry unit equipped with PL-MASC, rather than to units attacking said unit. 

PL-MASC is also very specifically limited to _foot_ infantry platoons (by both the text on IntOps p83 and [this rules confirmation thread](https://bg.battletech.com/forums/supplementary-rules/answered-io-prosthetic-leg-masc-rules-intent/)), and should not be valid for other motive types. Not certain how difficult it is to code such restrictions; this particular issue might also be more of a MegaMekLab issue (discovered both of these issues while creating a custom infantry unit with an unreasonable number of implants).

**Comment by HammerGS** [comment]
Almost all our MD options are legacy options and don't account for errata.

**Comment by gsparks3** [comment]
By "don't account for errata", do you mean you're just not going to change them period due to being too old and a hassle to mess with? Because this is the text as originally written, no errata.

**Comment by HammerGS** [comment]
As in its old and no one has looked at them. We are aware all the MD options are dated and need updating to IntOps but no one has done it. We also have no ETA when they will happen they are a low priority at this time.

**Comment by neoancient** [comment]
Most of the warrior augmentations appeared originally in one of the Jihad sourcebooks, and those that are implemented were done before IO came out.

**Comment by gsparks3** [comment]
Gotcha. Fair enough.

**Comment by pakfront** [comment]
I can take a look at this one

**Comment by pakfront** [comment]
Is there an existing unit-type that has PL-MASC I can use to test my changes?

**Comment by gsparks3** [comment]
I don't believe so by default, but if you turn on "Manei Domini implants" in Game Options, you can set an arbitrary CI platoon to have whichever cybernetics you desire. That should do the trick.

**Comment by pakfront** [comment]
Also, according to Sarna, the current code is at least  partially correct, infantry so equipped have a +1 malus to hit. Is that not true? I only have TW and tacops, so cannot dig into the rules myself.
 https://www.sarna.net/wiki/Prosthetic_Leg_MASC

**Comment by gsparks3** [comment]
See first post in this issue - per IOps the +1 to hit is only for attacks _against_ the infantry so equipped. The reference on Sarna is to an older rulebook (Jihad Hot Spots: 3072) and therefore should be superseded by Interstellar Operations.

Interestingly, IOps also does not mention the incompatibility with TSM implants mentioned on Sarna. Presumably that changed as well.

**Comment by pakfront** [comment]
Thanks for clarifying.
 How do I test for "foot" infantry? (isConventional && !isMechanized)? or getMovementMode() == EntityMovementMode.INF_LEG ?

**Comment by gsparks3** [comment]
All of the effects should only be functional on foot infantry.

**Comment by pakfront** [comment]
gotcha - code people, what is the approved way to test for "foot-ness?" I'm going with INF_LEG for the moment. Also, it looks like the +1 MP is being incorrectly applied to jump infantry. Should I fix that as well?
https://github.com/MegaMek/megamek/blob/3912e8d3fdc3635496254ea46fd82de22226db45/megamek/src/megamek/common/Infantry.java#L418

**Comment by pakfront** [comment]
I submitted a pull request: https://github.com/MegaMek/megamek/pull/3411
