### ISSUE TITLE
Mustang Fighter should not be a support vehicle (?)

### ISSUE THREAD

**Issue by SJuliez** [MegaMek/megamek#2506]
On the current master (minus the last few commits maybe), A Mustang Fighter (Standard) (XTRO Primitives IV - Age of War) seems to think of itself as a Support Vehicle. My guess would be it shouldnt, it has only weapons, no carrying compartments or other support stuff.
Same with the Colt Medium Fighter and Asher Hover Scout (XTRO Primitives V - Age of War). 
There are some more units among the support vehicles that don't seem to belong there. 
Also, these fighters seem to lose their weapons when added to the game (while the ground units dont).

**Comment by neoancient** [comment]
Primitive combat vehicles and conventional fighters are built as support vehicles.
