### ISSUE TITLE
47.14 Medium Laser Turrent Building dies to ammo explosion

### ISSUE THREAD

**Issue by buzzzz2138** [MegaMek/megamek#2510]
### Environment
MekHQ MegaMek 47.14
Windows 10
Jame 1.8.271

### Description
Medium Laser building, no ammo, died to ammo explosion.

Grasshopper shot building.  It went boom. See attached file.  Medium file is after the explosion.  The autosave it from before.

### Files
[Medium_Laser_Turret_Ammo_Explosion.gz](https://github.com/MegaMek/megamek/files/5700177/Medium_Laser_Turret_Ammo_Explosion.gz)
[autosave_2020-12-15_21-36-28.sav.gz](https://github.com/MegaMek/megamek/files/5700180/autosave_2020-12-15_21-36-28.sav.gz)

**Comment by NickAragua** [comment]
![image](https://user-images.githubusercontent.com/29387808/102434845-94b5ca80-3fe3-11eb-8829-089b4aa8f133.png)

If you read through the log, the ammo explosion does 0 damage, and then the rest of the grasshopper's attacks cause the building to reach 0 CF "naturally", at which point it collapses. We do need to update the ammo explosion message, however.
