### ISSUE TITLE
Unable to switch ammo bins in 47.15

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#2517]
Save game in 47.15 is attached.  The Avatar C has a bin of LRM 10 (standard) ammo and a bin of LRM 10 Thunder ammo, which cannot be selected.  Similarly the Exterminator has multiple bins of iNarc ammo which cannot be switched between.

Players are Brilliant Light III-Gamma (player) and Draconis Combine (Princess).

[Ammo_switching.sav.gz](https://github.com/MegaMek/megamek/files/5713614/Ammo_switching.sav.gz)

**Comment by sixlettervariables** [comment]
Many thanks to @arlith for making this really simple to test with the player name dropdown!
