### ISSUE TITLE
Minor intro date correction

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#2520]
v.47.15

The following introductory year changes have happened on the MUL and should be implemented into megamek:
-Fire Scorpion (Standard): introduced in 2852.

**Comment by HammerGS** [comment]
These are still under review with the MUL team.  Going to hold open and we can add units as needed then I'll do a bulk fix pre stable.

**Comment by AlphaSled** [comment]
Adding: 
--Templar III TL2R-OD: change to 3120.
--Kodiak II 2: change to 3139.

**Comment by HammerGS** [comment]
Fixed
