### ISSUE TITLE
Vehicular Grenade Launchers

### ISSUE THREAD

**Issue by arekP64** [MegaMek/megamek#2522]
Issue - unable to deploy smoke on any of the hexes within firing arcs.
Potential second issue - Not sure if Incendiary grenades should be able to set woods on fire or cause check for fire, but they do not and they add heat to firing unit if there is another unit in one of the target hexes.
Frags and Chaffs seems to be working fine (I am not familiar with VGL Chaff rules).

All above tested on Tracked Vehicles, Mechs, LAMs in Air Mech mode (same results) and Fighter mode (unable to employ any weapons, seems reasonable).

MM 0.46.1 ,0.47.7  & 0.47.15
Java 1.8.0_261
Windows 10 Home updated

**Comment by sixlettervariables** [comment]
Can we get a save game from 0.47.15?

**Comment by arekP64** [comment]
Enyo #4 is the one with smoke while #3 is with incendiary, you only need to order them to fire, every tank is loaded with both IS and Clan ammo for VGLs I believe
https://www.dropbox.com/s/uyvae7c4bqgswq3/autosave.sav.gz?dl=0

**Comment by neoancient** [comment]
There's a bug in the check for smoke munitions. Setting fires is an optional rule that has to be enabled for incendiary grenades to set woods on fire.
