### ISSUE TITLE
Dead-fire ammo wrong shots/ton

### ISSUE THREAD

**Issue by alexbib** [MegaMek/megamek#2529]
Dead-fire ammo (both LRM and SRM) should have the same number of shots/ton as standard ammo, not half. 
The relevant rule is in Interstellar Operations, p.132: "A ton of DF missiles provides the same number of shots as an equivalent ton of standard missiles for all given launcher sizes and types."

Version 0.47.15 on Windows 10 64-bit.

**Comment by alexbib** [comment]
Only the IS SRM version seems to be fixed (at least in MegaMekLab, I don't run MegaMek itself). Clan SRM and both IS and Clan LRM versions are still at half the number of shots.

**Comment by HammerGS** [comment]
Missed some refixed in https://github.com/MegaMek/megamek/commit/a9d6eace34caac716798949614c39134fe9452f0
