### ISSUE TITLE
[0.41.19 : Error] Dropship Cannot Unload

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#253]
Landed Vulture (Standard) #3's 'unload' button greyed out despite having units for unloading.

[DropshipCannotUnload.sav.gz](https://github.com/MegaMek/megamek/files/315529/DropshipCannotUnload.sav.gz)

**Comment by arlith** [comment]
`Weapons fire for Ymir BWP-2B #9 (Lyran Commonwealth Assault)
    AC/5 at Vulture (Standard) #3 (SirMegaV); needs 8, rolls 8 :  - Glancing Blow - hits  (using Right Side table) AFT
        Vulture (Standard) #3 (SirMegaV) takes 1 damage to AFT.
            95 Armor remaining.


    LRM 5 at Vulture (Standard) #3 (SirMegaV); needs 6, rolls 12 :  - Direct Blow - 5 missile(s) hit (using Right Side table) (w/ +4 bonus).

        Vulture (Standard) #3 (SirMegaV) takes 5 damage to LS.
            110 Armor remaining.
            Possible critical hit (12 to hit); needs 8, rolls (6+2) = 8 : An Light Vehicle bay door is destroyed!
`

All of the doors on the light vehicle bay were destroyed, so it can't unload.  This is why it can't unload, which is correct.  Unfortunately, it's not indicated to users well.

**Comment by arlith** [comment]
I updated the free space display for bays to also display the # of doors.

Previously, you would've seen:
> Light Vehicle Bay - 4 units

Now you will see
> Light Vehicle Bay (0 doors) - 4 units

I updated all of the bays to display current # of doors.

**Comment by SirMegaV** [comment]
For clarity, will displaying Light Vehicle Bay (0/4 Doors) - 4 Units better?

**Comment by arlith** [comment]
Probably, but we don't track original doors vs current doors, we just track current number of doors.  It might be useful to know how many originally existed, but what is most important is the current number.
