### ISSUE TITLE
Explosive Ammunition BV Penalty Errata

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#2533]
v.47.15

Just got these changes confirmed with DarkISI, and errata is up for them in their respective threads. Those can be seen here:
[https://bg.battletech.com/forums/errata/tactical-operations-advanced-units-equipment/msg1680361/#msg1680361](https://bg.battletech.com/forums/errata/tactical-operations-advanced-units-equipment/msg1680361/#msg1680361)

1) HVACs should provide a BV discount as well--but only ever 1-point, no matter how many crits the weapon system has.
2) HVACs should provide the discount even if the design carrying one does not carry any ammunition for it.

EDIT: Removed B-Pod issue, Megamek is doing it fine.

**Comment by neoancient** [comment]
The construction rules require the unit to carry ammo for all its weapons.
