### ISSUE TITLE
Fatal MML bug in Making sure "broken" (or old) `Coords` instances get loaded properly

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/megamek#254]
From MM Commit 2a466381c3166438c3e10102a9a0d40734a4d001
See MegaMek/megameklab#16

There is some issue with the new xstream code that doesn't cause issue with MM but stops MML from functioning when trying to build the cahce or display anything in the equipment tab.

**Comment by arlith** [comment]
The problem isn't with MM, it's with MML.
