### ISSUE TITLE
0.47.15:  Arrow IV ammo is not selectable

### ISSUE THREAD

**Issue by mhjacks** [MegaMek/megamek#2540]
### Environment
What version of MegaMek does your issue apply to?  MegaMek embedded in MekHQ, Standalone on Windows.  Both v0.47.15
What operating system are you using?  Embedded is Linux, Standalone Windows
What java version are you using?  Embedded 11, Standalone 8

### Description
Multiple types of ammo are loaded in Arrow IV launchers (demolishers in this case).  Only the "default" loaded ammo is visible and selectable in-game.

### Files
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/5749079/autosave.sav.gz)

**Comment by sixlettervariables** [comment]
I believe I have fixed this as of https://github.com/MegaMek/megamek/pull/2518

Before I close this I will double check though.

**Comment by mhjacks** [comment]
I just tried on a mekhq built with a0a2bb00a8 of megamek and it worked as expected.
