### ISSUE TITLE
Rear or turret-mounted weapons failing to load

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#2544]
V.47.15

As title, nothing more to it. Ordering units by Level shows a bunch of new units with the F tag, all due to rear-mounted or turreted weapons.

**Comment by HammerGS** [comment]
[Entity.txt](https://github.com/MegaMek/megamek/files/5756066/Entity.txt)
List of units with issues.

**Comment by sixlettervariables** [comment]
Introduced by https://github.com/MegaMek/megamek/pull/2444
