### ISSUE TITLE
Rear-mounted small laser not loading on Deva C-DVA-OU Exanimus 0.47.15

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#2546]
Looking through some experimental unit files, I noticed that the rear-mounted IS ER Small Laser on the Deva C-DVA-OU Exanimus is not loading.

**Comment by kguuh** [comment]
Good

**Comment by sixlettervariables** [comment]
Duplicate of https://github.com/MegaMek/megamek/issues/2544
