### ISSUE TITLE
Princess.calculateFiringTurn Error

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#255]
Hit this error during Princess shooting phase.

java.lang.NullPointerException
    at megamek.client.bot.princess.Princess.calculateFiringTurn(Princess.java:305)
    at megamek.client.bot.BotClient.calculateMyTurn(BotClient.java:389)
    at megamek.client.bot.BotClient$CalculateBotTurn.run(BotClient.java:98)

Savegame and log attached. Load savegame, assign Princess, you will see the error again.

[Princess.calculateFiringTurnErrorLog.txt](https://github.com/MegaMek/megamek/files/317551/Princess.calculateFiringTurnErrorLog.txt)
[Princess.calculateFiringTurnError.sav.gz](https://github.com/MegaMek/megamek/files/317552/Princess.calculateFiringTurnError.sav.gz)

**Comment by arlith** [comment]
Huh, this is interesting.  What's happening is, you've got inidividual initiative on, so every turn is an "Individual Entity Turn", which means it is only valid for a specific unit.  It's currently the Marsden II MBT II (Primitive)'s turn, however that Entity reports that it's already done, so it's not  valid for that turn.  Because it's not valid, no Entity is valid, and the shooter Princess is calculating the turn for becomes null, which then causes an NPE.  I'll have to figure out how that Marsden's done state got set to true...

**Comment by arlith** [comment]
(As a work around, you could load the saved game, skip the current turn, and then add the bots back, I think that would allow you to continue your game.)

**Comment by SirMegaV** [comment]
Yup. Already finished that game. Used skip. Not sure how it got into that
state, but the attached save game's turn and its next have the same issue.
But it will take a long time to reach the next occurrence. :)

**Comment by BLOODWOLF333** [comment]
### Environment
Megamek standalone 0.43.5
Java version 1.8.0_144
Platform Windows 8.1 6.3 (amd64)

### Description
Princess hangs during her physical attack phase.

Line 3,747
> java.lang.NullPointerException
	at megamek.client.bot.princess.Princess.calculatePhysicalTurn(Princess.java:803)
	at megamek.client.bot.BotClient.calculateMyTurn(BotClient.java:460)
	at megamek.client.bot.BotClient.access$000(BotClient.java:83)
	at megamek.client.bot.BotClient$CalculateBotTurn.run(BotClient.java:104)

![github](https://user-images.githubusercontent.com/16950832/34464259-002d3942-ee3e-11e7-8903-0f7f0ea3cca2.png)

### Files
Player Name:  BLOODWOLF
[PhysicalPhase.sav.gz](https://github.com/MegaMek/megamek/files/1595475/PhysicalPhase.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/1595476/megameklog.txt)

Pretty sure this is the same thing but during the firing phase.

**Comment by neoancient** [comment]
This is not the same issue.

**Comment by neoancient** [comment]
After spending a lot of time on this what I've found is that the current and next unit are both set to done. The last two actions in the game's action vector are a weapon attack by the current unit and current + 2. If I allow the process to proceed by setting the done flag to false for current and current + 1 I find that the current entity and the next two submit the same weapon attacks that are already in the game's action vector (which is no attack for current + 1).

I believe this is a race condition resulting from the nonatomic increment-and-get operation in `Game.changeToNextTurn()`.

**Comment by mmnet-jackal** [comment]
In my own testing I've noticed this issue happening in cities, presumably when there is the opportunity to physical, but (from Princess's POV) no 'enemies' within range to attack.

**Comment by neoancient** [comment]
Based on my comment here five years ago I believe this should be fixed by #4674.
