### ISSUE TITLE
0.47.16 (RC2) Out-of-date folder in data/boards/unofficial/

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#2557]
The folder "data/boards/unofficial/SimonLandmineMaps" is an old version, and should be replaced with the attached as "data/boards/unofficial/SimonLandmine", which is the latest version of this folder.

[SimonLandmine.zip](https://github.com/MegaMek/megamek/files/5772533/SimonLandmine.zip)

(The folder name change from 'SimonLandmineMaps' to 'SimonLandmine' was applied for 0.47.7 to 0.47.11, but appears to have reverted after that version.)

**Comment by HammerGS** [comment]
Thanks Simon, I'll get it sorted.

**Comment by SimonLandmine** [comment]
Cheers!

**Comment by HammerGS** [comment]
@SimonLandmine Have a look at that commit and see if it makes sense. I added the one special map.

**Comment by SimonLandmine** [comment]
Yeah, that's got the recent ones. Ta!
