### ISSUE TITLE
Cannot select boards on servers if they are not local

### ISSUE THREAD

**Issue by sixlettervariables** [MegaMek/megamek#2560]
### Environment
What version of MegaMek does your issue apply to?  0.47.16
What operating system are you using?  Windows, Mac, or Linux.
What java version are you using?  Java 11

### Description
Attempting to select a board on a server that isn't local:
```
21:13:34,446 ERROR [megamek.common.Board] {AWT-EventQueue-0} 
load(), line 931 : IO Error opening file to load board! java.io.FileNotFoundException: data\boards\unofficial\JimBoards\FreeWolves_League1.board (The system cannot find the path specified)

Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: board is the wrong size, expected 40x20, got 0x0
	at megamek.common.util.BoardUtilities.combine(BoardUtilities.java:85)
	at megamek.client.ui.swing.ChatLounge.previewGameBoard(ChatLounge.java:1150)
	at megamek.client.ui.swing.ChatLounge.actionPerformed(ChatLounge.java:2804)
```

### Files
![image](https://user-images.githubusercontent.com/8238690/104080587-ff2ee480-51f6-11eb-852f-9ec02e81ebc3.png)

**Comment by SJuliez** [comment]
The lobby wants to create a minimap preview for the board and see if the board has invalid hexes both of which isnt possible. Should the lobby (which Im currently working on a lot) support server boards that aren't present on the client? And local boards that the server doesnt have?

**Comment by sixlettervariables** [comment]
It only shows server boards. Once someone with the board selected it, the rest of us without it were fine. We couldn't see it in the lobby still, but it loaded and we played.
