### ISSUE TITLE
46.16 - Princess becomes stalled on her turn to move units and does not recover

### ISSUE THREAD

**Issue by Morkath** [MegaMek/megamek#2565]
### Environment
0.47.16 RC2 - MekHQ
Windows
Java version 1.8.0_271

### Description
During the second round of a Hide and Seek (Attacker) mission against FRR, Princess became stalled during her turn to move units. and the phase does not progress.

Reloading the save does not fix the issue, she remains stalled.

Did not reproduce when starting the battle from scratch.

### Files
[megameklog.txt](https://github.com/MegaMek/megamek/files/5807790/megameklog.txt)
[TempSave.sav.gz](https://github.com/MegaMek/megamek/files/5807792/TempSave.sav.gz)

Name: My Campaign

**Comment by BowtieBob** [comment]
After reloading the game, you should be able to go to "File/Game/Replace Player.." for each bot to reload them

**Comment by NickAragua** [comment]
It's not a crash, the bot is actually taking a really long time to calculate the move for the Ostscout.
