### ISSUE TITLE
Recognition Guides - Various Unit Fixes

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#2566]
As title. Most of these stem from errata that has since been posted in the Recognition Guide errata thread found here: 
https://bg.battletech.com/forums/errata/recognition-guide-ilclan-all-volumes/

[RecGuide1.zip](https://github.com/MegaMek/megamek/files/5810486/RecGuide1.zip)

**Comment by HammerGS** [comment]
Thanks I'll get these added!

**Comment by AlphaSled** [comment]
Recognition Guide 2 corrections.

[RecGuide2.zip](https://github.com/MegaMek/megamek/files/5810605/RecGuide2.zip)

**Comment by AlphaSled** [comment]
Recognition Guide 3 corrections.

[RecGuide3.zip](https://github.com/MegaMek/megamek/files/5810919/RecGuide3.zip)

**Comment by AlphaSled** [comment]
Griffin C file--base tech changed to Clan to give it CASE.

[Griffin C.zip](https://github.com/MegaMek/megamek/files/5818029/Griffin.C.zip)

**Comment by AlphaSled** [comment]
RecGuide 4 corrections - note that there are many more in this batch due to introductory date changes. In addition, the Thresher II was renamed the Thresher Mk II, so the original Thresher II mtf will need to be deleted.

[RecGuide4.zip](https://github.com/MegaMek/megamek/files/5823778/RecGuide4.zip)

**Comment by AlphaSled** [comment]
RecGuide 5. A crap ton of date changes.

[RecGuide5.zip](https://github.com/MegaMek/megamek/files/5833636/RecGuide5.zip)

**Comment by AlphaSled** [comment]
RecGuide 6. Date changes again, though I also modified the name of the Marauder Red Hunter.

[RecGuide 6.zip](https://github.com/MegaMek/megamek/files/5839064/RecGuide.6.zip)

**Comment by AlphaSled** [comment]
More date changes, but with a decent number of name changes. The following should be done when importing them:
--In the ilClan Rec Guides, Vol 7 folder:
delete all Mist Lynx (Koshi) files
delete all Incubus (Vixen) files
delete all Stormcrow (Ryoken) files

--delete "Vixen (Incubus) 2" file from 3055u folder (duplicate w/ error)
--delete Warhammer WHM-7M file from RecGuide 7 folder (duplicate w/ error)
--delete Warhammer WHM-7A file from Operation Klondike folder (duplicate)
--delete Warhammer WHM-7S file from 3085u, Phoenix folder (duplicate)
--delete Warhammer WHM-8R file from ilClan Rec Guides, Vol 4 folder (duplicate)
--delete Warhammer WHM-9K file from ilClan Rec Guides, Vol 4 folder (duplicate w/ error)

[RecGuide7.zip](https://github.com/MegaMek/megamek/files/5846105/RecGuide7.zip)

**Comment by AlphaSled** [comment]
Names and dates again. Delete existing RecGuide8 file and replace with this one.

[Vol 8.zip](https://github.com/MegaMek/megamek/files/5853238/Vol.8.zip)

**Comment by AlphaSled** [comment]
Not a RecGuide fix, but a fixed Chevalier (Speed) mtf with its missing ERLL added.

[Chevalier Light Tank (Speed).zip](https://github.com/MegaMek/megamek/files/5862665/Chevalier.Light.Tank.Speed.zip)

**Comment by AlphaSled** [comment]
Hope it's not too late for one last fix. Slight correction to the Dominator name (added (Standard)).

[Dominator.zip](https://github.com/MegaMek/megamek/files/5863304/Dominator.zip)

**Comment by HammerGS** [comment]
@AlphaSled I think you're Rec Guide 8 is missing units.  Rifleman's come to mind with a quick look.

**Comment by AlphaSled** [comment]
I just did a check, and everything is OK. Many of the units were older and were already in Megamek; any Rifleman (or other units) I omitted were duplicates. I figured it'd be best to do that then to send you on a merry hunt like I did for RecGuide7. 

If you do have a preference one way or another though, lemme know and I'll adopt that going forward.

**Comment by AlphaSled** [comment]
Corrected mtfs for volume 9. The following should be done when importing them:
--Delete Valkyrie VLK-QD from 3085u, Phoenix folder
--Delete Shadow Cat J from 3058Uu folder
--Delete Goshawk (Vapor Eagle) from 3055U folder
--Delete Goshawk (Vapor Eagel) 2 from 3055U folder

--Delete Shadow Cat E from 3145, NTNU RU folder
--Delete Gladiator (Executioner) F from 3145, NTNU folder
--Delete Gladiator (Executioner) G from 3145, NTNU folder
--Delete Gladiator (Executioner) I from 3145, NTNU folder

[Vol 9 v2.zip](https://github.com/MegaMek/megamek/files/5915255/Vol.9.v2.zip)

**Comment by AlphaSled** [comment]
In case Vol 9 has already been downloaded, I just updated it. Forgot a few name changes.
Volume 10 here. The following will need to be done: 
--Delete Vulture (Mad Dog) G from 3145, NTNU RS folder
--Delete Archer ARC-2Rb from Operation Klondike folder
--Delete Archer ARC-4M from 3085u, Phoenix folder
--Delete Archer ARC-5R from 3085u, Phoenix folder
--Delete Archer ARC-5S from 3085u, Phoenix folder
--Delete Archer ARC-5W from 3085u, Phoenix folder
--Delete Archer C from 3085u, Phoenix folder
--Delete Archer Wolf from 3085u, Phoenix folder

[Vol 10 v2.zip](https://github.com/MegaMek/megamek/files/5915466/Vol.10.v2.zip)

**Comment by AlphaSled** [comment]
All the new Tukayyid stuff, including the Locust C from Tukayyid:Supplemental.
The following needs to be done when integrating these files:
--Delete Black Knight BL-9-KNT from the 3050u folder

[Tukayyid v2.zip](https://github.com/MegaMek/megamek/files/5916653/Tukayyid.v2.zip)

**Comment by HammerGS** [comment]
I'm going to close this one. Going forward lets do one report for the specific book. But please keep the formatting like we discussed.

Fixed as part of these series of commits https://github.com/MegaMek/megamek/commit/327d2d022f4b39293845d66760b7f3f7062a480e , https://github.com/MegaMek/megamek/commit/6cefd9790bcb825af394704919a21d1b1ee341fd , https://github.com/MegaMek/megamek/commit/f74e7da52c61d439866e7943d8aec5275afb68ca
