### ISSUE TITLE
LAM using depth of water to determine movement cost

### ISSUE THREAD

**Issue by BowtieBob** [MegaMek/megamek#2576]
In a battle yesterday in 0.47.16, I noticed that my LAM in airmech mode went from being at elevation one to elevation four when I went across some depth 3 water. It's possible it was just showing the elevation change, but I'm pretty sure I was losing the movement cost for it as well.

**Comment by neoancient** [comment]
I couldn't reproduce the reported behavior with climb mode on or off. I'm closing this since you stated that you did not actually confirm the issue.
