### ISSUE TITLE
Placable objects

### ISSUE THREAD

**Issue by musicman609** [MegaMek/megamek#2577]
### Environment
46.1

### Description
Can we get placable boxes or random objects that can be placed at random by one side or another during deployment? I've been going through and adding all the specialized maps for all the early supplements, and more than a few of those scenarios require crates or whatnot distributed at random either to be destroyed, collected, etc.

I know I could place markers on the map itself in the map editor that can be destroyed (buildings, fuel tanks, etc),  but this removes the randomization factor.

**Comment by repligator** [comment]
See also #353
