### ISSUE TITLE
47.16 Building said it took damage during round report, but didn't actually take damage?

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#2580]
### Environment
47.16
Windows 10
Java 11.0.8
MekHQ integrated Megamek

### Description
My Atlas was facing a Warhammer standing on a 1-level tall Hardened Building with 117 CF. I decided to attack the building during both the Weapon Attack Phase and Physical Attack Phase to push its CF low enough for it to collapse. The Round Report recorded the building taking damage as normal, dropping to 75 CF during the Weapon Attack Phase, and then to 33 CF during the Physical Attack Phase - but it didn't actually collapse, and when I checked its CF out of confusion at the start of the next turn, its CF was still at 117? Very strange.

Weapon Attack Phase attacks on the building:
![image](https://user-images.githubusercontent.com/59574316/104823651-bd66f500-5819-11eb-807f-f6b3ba7d9e16.png)

Physical Attack Phase attacks on the building:
![image](https://user-images.githubusercontent.com/59574316/104823667-d8396980-5819-11eb-9712-4c7c253ce666.png)

Screenshot of Warhammer still standing on 117 CF building hex 1855 next turn:
![image](https://user-images.githubusercontent.com/59574316/104823684-f737fb80-5819-11eb-93b1-499d07ca52ba.png)

### Files
Savegame (player name: Coppercoats):
[buildingBug.sav.gz](https://github.com/MegaMek/megamek/files/5825184/buildingBug.sav.gz)

Logs (didn't see anything obvious):
[megameklog.txt](https://github.com/MegaMek/megamek/files/5825182/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/5825183/mekhqlog.txt)

**Comment by gsparks3** [comment]
Update: _after the Warhammer moved off the hex_, it updated to 33 CF. Now I can't even climb up there and kick him ...

![image](https://user-images.githubusercontent.com/59574316/104823981-44b56800-581c-11eb-8912-61ffa09bde66.png)

[buildingBug2.sav.gz](https://github.com/MegaMek/megamek/files/5825191/buildingBug2.sav.gz)

**Comment by gsparks3** [comment]
Further update: in a different fight, I have a building showing as 0 CF (with nothing standing on it) that hasn't collapsed. I suspect there's just some collapse shenanigans going on. This is still MekHQ-integrated Megamek, if that's relevant. 
![image](https://user-images.githubusercontent.com/59574316/105563519-5ac79a80-5cec-11eb-98a4-6736f21d051d.png)

[buildingBug3.sav.gz](https://github.com/MegaMek/megamek/files/5859331/buildingBug3.sav.gz)

Laser shots that round:
![image](https://user-images.githubusercontent.com/59574316/105563759-4c2db300-5ced-11eb-8d84-e68582e74056.png)

Seems to have skipped the "BUILDING DESTROYED" marker somehow and is refusing to collapse.

**Comment by NickAragua** [comment]
Next time you see this, could you grab the autosave from the beginning of the turn as well?

**Comment by gsparks3** [comment]
Would if I could have - the issue with both of those is that I only noticed that it hadn't collapsed on the next turn, when I could view the hex and see that it's at 0 CF (or lower-than-what's-standing-on-it in the first case) but not collapsed, at which point the autosave had already saved on said next turn. Unhelpfully, so far I haven't been able to deliberately reproduce it. I'll definitely grab one if I can.

**Comment by JonhyBurner** [comment]
Just to add that I recently managed to walk across the top of a building with 96 or 97 CF with an Atlas, so there's definitely something going on. Will be on the look out for this as well.
