### ISSUE TITLE
Corrected Introductory Dates

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#2582]
v.47.16

mtfs for the Enforcer III 6Ma and Centurion 9-Da with corrected introductory dates.

[Corrected Dates.zip](https://github.com/MegaMek/megamek/files/5826523/Corrected.Dates.zip)

**Comment by HammerGS** [comment]
Fixed as part of these series of commits https://github.com/MegaMek/megamek/commit/327d2d022f4b39293845d66760b7f3f7062a480e , https://github.com/MegaMek/megamek/commit/6cefd9790bcb825af394704919a21d1b1ee341fd , https://github.com/MegaMek/megamek/commit/f74e7da52c61d439866e7943d8aec5275afb68ca
