### ISSUE TITLE
Null-Signature System Should be Disabled Upon Hit Location Destruction

### ISSUE THREAD

**Issue by Windchild292** [MegaMek/megamek#2586]
TO: AU&E pg 148 states that the null-signature system should be disabled when any crit slot or hit location is hit.

**Comment by NickAragua** [comment]
I can't reproduce this behavior. The system *says* it's on as per #2857, but targeting the unit with weapon attacks shows the proper modifiers.

**Comment by Windchild292** [comment]
This is definitely not working if the mech loses a hit location.
![image](https://user-images.githubusercontent.com/39067288/105503971-3a202600-5c95-11eb-9067-f9abef6d1d32.png)

**Comment by NickAragua** [comment]
Think I'm going to need a save, because I haven't been able to reproduce it in an arbitrary situation.

**Comment by Windchild292** [comment]
Here's a save showing the null signature and chameleon cloak applying on a mech that doesn't have a left arm, and thus the system should be disabled.

[nullSigChameleonPreBug.sav.gz](https://github.com/MegaMek/megamek/files/5857106/nullSigChameleonPreBug.sav.gz)

[nullSigChameleonBug.sav.gz](https://github.com/MegaMek/megamek/files/5857081/nullSigChameleonBug.sav.gz)
