### ISSUE TITLE
Bug: 47.16 Random army creation by BV Tech of ALL becomes ALL Clan upon reopen of subwindow

### ISSUE THREAD

**Issue by MarcJC** [MegaMek/megamek#2592]
In 47.16 I was creating a random army using the BV matching.  I had set the Tech level to ALL.  When I closed the window, and reopened it to make the next army the Tech level had changed to ALL Clan.  

![ALL to ALL Clan1](https://user-images.githubusercontent.com/20606833/105274954-48beee00-5b6c-11eb-891b-5bee03d3f413.png)

becomes 

![ALL to ALL Clan2](https://user-images.githubusercontent.com/20606833/105275027-67bd8000-5b6c-11eb-9ef8-7ddf08e3824d.png)

No other tech types/levels seem to be effected.

**Comment by Windchild292** [comment]
At a glance this is likely related to a contains or equalsIgnoreCase check.
