### ISSUE TITLE
Warn before collapsing buildings via movement due to weight

### ISSUE THREAD

**Issue by LimiterDrive** [MegaMek/megamek#2595]
As suggested on Slack, a warning popup when attempting to move through a building hex that will collapse due to the weight of the mech would be good. 

 Additionally, a warning when ending your turn on a building hex with a CF X above your mech, where X is configurable in preferences, would also be good.

**Comment by HoneySkull** [comment]
![image](https://github.com/MegaMek/megamek/assets/83041327/bc38a2fa-229a-45a5-88a1-1edd6b539ad1)
