### ISSUE TITLE
Bad Image for Shologar

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/megamek#260]
The Shologar icon is getting LEFT and TOP Camo. Is it only the Shologar? I can't find any other examples.

[BadShologar1.zip](https://github.com/MegaMek/megamek/files/325958/BadShologar1.zip)

**Comment by Akjosch** [comment]
The image used was weird: It hat the right dimensions, but the only layer declared was *smaller* (and in the lower right corner).
