### ISSUE TITLE
Minor Mortar Data Issues

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#2600]
Firstly, two 'Mech Mortar turrets has the wrong name. Fixed files here.
[Mortar Turrets.zip](https://github.com/MegaMek/megamek/files/5862720/Mortar.Turrets.zip)

Secondly, certain images were associated with the wrong turrets. The 'Mech Mortar turret section in the mechset document should be replaced with the following:

exact "'Mech Mortar/1 Battery (Dual)" "GunEmplacements/Mortar1_Dual.png"
exact "'Mech Mortar/1 Battery (Quad)" "GunEmplacements/Mortar1_Single.png"
exact "'Mech Mortar/1 Battery (Single)" "GunEmplacements/Mortar1_Single.png"
exact "'Mech Mortar/1 Battery (Triple)" "GunEmplacements/Mortar1_Triple.png"
exact "'Mech Mortar/2 Battery (Dual)" "GunEmplacements/Mortar2_Dual.png"
exact "'Mech Mortar/2 Battery (Quad)" "GunEmplacements/Mortar2_Single.png"
exact "'Mech Mortar/2 Battery (Single)" "GunEmplacements/Mortar2_Single.png"
exact "'Mech Mortar/2 Battery (Triple)" "GunEmplacements/Mortar2_Triple.png"
exact "'Mech Mortar/4 Battery (Dual)" "GunEmplacements/Mortar4_Dual.png"
exact "'Mech Mortar/4 Battery (Quad)" "GunEmplacements/Mortar4_Single.png"
exact "'Mech Mortar/4 Battery (Single)" "GunEmplacements/Mortar4_Single.png"
exact "'Mech Mortar/4 Battery (Triple)" "GunEmplacements/Mortar4_Triple.png"
exact "'Mech Mortar/8 Battery (Dual)" "GunEmplacements/Mortar8_Dual.png"
exact "'Mech Mortar/8 Battery (Quad)" "GunEmplacements/Mortar8_Single.png"
exact "'Mech Mortar/8 Battery (Single)" "GunEmplacements/Mortar8_Single.png"
exact "'Mech Mortar/8 Battery (Triple)" "GunEmplacements/Mortar8_Triple.png"

**Comment by HammerGS** [comment]
Fixed as part of these series of commits https://github.com/MegaMek/megamek/commit/327d2d022f4b39293845d66760b7f3f7062a480e , https://github.com/MegaMek/megamek/commit/6cefd9790bcb825af394704919a21d1b1ee341fd , https://github.com/MegaMek/megamek/commit/f74e7da52c61d439866e7943d8aec5275afb68ca
