### ISSUE TITLE
Corrected Triumph mtf

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#2602]
This is a three-parter.

Firstly, I believe that the "Triumph (2593)" (the 5,600 ton dropship) that is currently included in Megamek should be moved to the unofficial folder. It's not on the MUL and was superseded by the new version of the design in 3057u.

Secondly, the "Triumph (2593b)" should be deleted altogether. It doesn't line up with any existing Triumphs, with an incorrect total tonnage (among other differences) when compared with the 3057u version of the design.

Finally, attached is a new "Triumph (2593)" mtf that lines up with both TR:3057u and the MUL.

[Triumph (2593).zip](https://github.com/MegaMek/megamek/files/5864058/Triumph.2593.zip)

**Comment by HammerGS** [comment]
Fixed as part of these series of commits https://github.com/MegaMek/megamek/commit/327d2d022f4b39293845d66760b7f3f7062a480e , https://github.com/MegaMek/megamek/commit/6cefd9790bcb825af394704919a21d1b1ee341fd , https://github.com/MegaMek/megamek/commit/f74e7da52c61d439866e7943d8aec5275afb68ca
