### ISSUE TITLE
[Bug] Host cannot deploy as observer if commander killed vic condition active

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#261]
Mekhq 3.29 version of MM.

I was hosting a game for two other players and could not launch the game with commander killed set as a victory condition, even setting myself to team 0. MM required me to assign a unit and set it as a commander before I could launch, so I could not be an observer.

**Comment by arlith** [comment]
The check was "if commander killed victory and the player has no commanders, stop"  I changed it to "if commander killed victory and the player has no commanders and actually has units, stop."  So now any players without units won't be required to have commanders.
