### ISSUE TITLE
Corrected Mech mtf

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#2612]
Corrected Viper (Black Python) (Standard)
[Viper (Black Python) (Standard).zip](https://github.com/MegaMek/megamek/files/5897387/Viper.Black.Python.Standard.zip)

**Comment by HammerGS** [comment]
Thanks. Can you do a couple of things for me with new unit files. Iterate the version from 1.0 to 1.x if anything changes, and let me know which folder it needs to go in. Saves me searching for them.  Thanks! :)

**Comment by AlphaSled** [comment]
Of course! You've already told me that before, too...
Corrected Titan 1Ar and 1Aj mtfs. Should go into the 3145/NTNU folders.

[Titan.zip](https://github.com/MegaMek/megamek/files/5901349/Titan.zip)

**Comment by HammerGS** [comment]
Fixed as part of these series of commits https://github.com/MegaMek/megamek/commit/327d2d022f4b39293845d66760b7f3f7062a480e , https://github.com/MegaMek/megamek/commit/6cefd9790bcb825af394704919a21d1b1ee341fd , https://github.com/MegaMek/megamek/commit/f74e7da52c61d439866e7943d8aec5275afb68ca
