### ISSUE TITLE
NPE while attempting to DFA target.

### ISSUE THREAD

**Issue by mjbroekman** [MegaMek/megamek#2613]
### Environment
 	MegaMek via MekHQ 0.47.16
	Java vendor N/A (openjdk via homebrew)
	Java version 15.0.1
	Platform Mac OS X 10.15.7 (x86_64)

### Description
While attempting to DFA a target mech, I clicked the DFA button and selected the target hex/unit at the edge of my jump range. The to-hit/damage confirmation window popped up and I clicked to confirm the attack. At that point, my mech was unselected, but the turn did not progress. It claimed that it was still my turn and the unit which was attempting the DFA was still the active unit.
![Screen Shot 2021-01-30 at 5 10 00 PM](https://user-images.githubusercontent.com/5141448/106369258-df826c00-631d-11eb-89de-38c6ad1aab22.png)
![Screen Shot 2021-01-30 at 5 10 18 PM](https://user-images.githubusercontent.com/5141448/106369266-e7daa700-631d-11eb-88e8-84fe318136f4.png)
![Screen Shot 2021-01-30 at 5 10 40 PM](https://user-images.githubusercontent.com/5141448/106369272-f4f79600-631d-11eb-8533-b94dc2303782.png)

### Files
Beginning of turn autosave: [predfa-autosave.sav.gz](https://github.com/MegaMek/megamek/files/5898814/predfa-autosave.sav.gz)
Save after unit became stuck: [stuckunit.sav.gz](https://github.com/MegaMek/megamek/files/5898815/stuckunit.sav.gz)
Custom Units [Knights of the Periphery.zip](https://github.com/MegaMek/megamek/files/5898819/Knights.of.the.Periphery.zip)
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/5898817/mekhqlog.txt)
[megameklog.txt](https://github.com/MegaMek/megamek/files/5898818/megameklog.txt)

**Comment by HammerGS** [comment]
Couple of NPE's in the log. This also sounds familiar to a DFA bug Casual Joker had on a stream a few weeks ago. But they didn't have a log or save to send us.

Should this the be considered Stable blocking.

```
Exception in thread "Packet Pump" java.lang.NullPointerException: Cannot invoke "megamek.common.Targetable.getTargetType()" because "target" is null
	at megamek.server.Server.processMovement(Server.java:7542)
	at megamek.server.Server.receiveMovement(Server.java:4908)
	at megamek.server.Server.handle(Server.java:31339)
	at megamek.server.Server$PacketPump.run(Server.java:254)
	at java.base/java.lang.Thread.run(Thread.java:832)
```
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "megamek.common.Entity.equals(Object)" because "ce" is null
	at megamek.client.ui.swing.MovementDisplay.chooseTarget(MovementDisplay.java:4163)
	at megamek.client.ui.swing.MovementDisplay.hexMoused(MovementDisplay.java:1953)
	at megamek.client.ui.swing.boardview.BoardView1.processBoardViewEvent(BoardView1.java:1131)
	at megamek.client.ui.swing.boardview.BoardView1.mouseAction(BoardView1.java:5133)
	at megamek.client.ui.swing.boardview.BoardView1.mouseAction(BoardView1.java:5159)
	at megamek.client.ui.swing.boardview.BoardView1.mouseReleased(BoardView1.java:4889)
```

**Comment by NickAragua** [comment]
Were you, by chance, attempting to kick the Blackjack with the Vulcan?

**Comment by mjbroekman** [comment]
> Were you, by chance, attempting to kick the Blackjack with the Vulcan?

No. I was attempting to DFA the Griffin with my Wolverine.

**Comment by NickAragua** [comment]
Hmm. Loading those saves, I can DFA Griffin just fine.

**Comment by mjbroekman** [comment]
I think the NPE borked my session completely because I wasn't able to complete any moves at all using any of the savefiles after that.

In order to complete the combat:
* I had to close out MegaMek
* then relaunch the scenario from MekHQ
* then load the savefile (I used the predfa-autosave.sav file) into MegaMek to get me to the point where I left off.

I don't know whether the NPE was attributable to the DFA itself or not. I just know that it was working fine and then I attempted the DFA and things stopped working.

**Comment by AlphaSled** [comment]
I'm just chiming in to say that I game I was in had the same bug a few weeks ago under the exact same circumstances. An attempt to make a DFA was made, and everything locked up in the exact same way as mjbroekman said. We also had to relaunch everything in order to get the game working.

I don't have the save file myself, but I'll ask around to see if anyone else still has it.

**Comment by NickAragua** [comment]
The fix will prevent the NPE, which appears to be caused by the DFA target being invalid - in that situation, the game will behave as if the original target had been destroyed - so it'll do displacement etc.

It seems like there's some kind of problem with the generation of DFA attack commands, but it's pretty tough to track down what went wrong there.
