### ISSUE TITLE
Map Editor 0.47.16 (and earlier, probably) - 'Validate' button and buildings

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#2614]
On the Map Editor for 0.47.16 it is possible to define a hex as ...

> Light building
> Building elevation 1

... but with no "Building CF" value defined. These can be 'placed' on the map, and appear as if pavement hexes (but with "HEIGHT 1" on them). When the [Validate] button is pressed, no 'INVALID' warning is raised.

(It is also possible to add buildings with "Building CF 0", or, with a bit of accidental keyboard-mashing, a negative CF value. Neither of these count as errors when [Validate] is pressed, either.)

Should these be flagged as errors by the [Validate] button? They do cause odd behaviour if the map is then loaded to MM ... (e.g. Princess can NPE during deployment, etc.)

(This bug bought to you on behalf of someone who managed to discover this on Discord.)

**Comment by HammerGS** [comment]
Going to tag @SJuliez for his thoughts.

**Comment by SJuliez** [comment]
Yes, hexes like that should be flagged as invalid. I'll look into it.
