### ISSUE TITLE
Unloaded ammo in ATMs and MMLs can cause NPEs

### ISSUE THREAD

**Issue by varcolac** [MegaMek/megamek#262]
As mentioned in the title, princess has suddenly started taking so long to move, the game has become unplayable. This problem is recent, and i have not knowingly done anything to cause this, and i have no idea what would fix this, so hopefully somebody else will know what is wrong. i am sorry for not being able to post any more details. 

[megameklog.txt](https://github.com/MegaMek/megamek/files/329040/megameklog.txt)

**Comment by pheonixstorm** [comment]
You should probably post your save game as well. I noticed two different errors in the log file but I was the last one that may be the cause.

**Comment by varcolac** [comment]
i dont have a save, as princess would freeze upon loading for as long as i used megamek, but that is another problem in of itself.

**Comment by pheonixstorm** [comment]
even if princess is frozen you should be able to go under file -> save unless MM itself is freezing.
Is this during deployment, movement phase, what?

**Comment by varcolac** [comment]
it is during movement phase, and i have started a new game under the same settings as the previous log to make a save, along with the new log.        
[princessbug.sav.gz](https://github.com/MegaMek/megamek/files/329232/princessbug.sav.gz)

[megameklog.txt](https://github.com/MegaMek/megamek/files/329230/megameklog.txt)

**Comment by pheonixstorm** [comment]
Between the log and the save arlith should have enough to fix this. Looks like the same errors as before as well.

**Comment by varcolac** [comment]
alright, i'll just hang tight till then.

**Comment by varcolac** [comment]
an update, princess suddenly seems to be mostly working now, but only with relatively small numbers of mechs in the game, with around 6 mechs being the point where princess slows down significantly for me.

**Comment by pheonixstorm** [comment]
Do another updated log if you would. The more information the devs have about a bug the easier it is to fix.

**Comment by varcolac** [comment]
i seem to have tracked at least part of the problem to a certain combination of custom mechs that somehow throws princess off when put onto the board, regardless of who uses them. below is a ZIP containing the custom mechs, a unit list containing them, plus the updated log and save. it's likely that the best fix will be simply to not try using the mechs, but maybe they will have something worth looking at.    
[bugpackage.zip](https://github.com/MegaMek/megamek/files/332811/bugpackage.zip)

**Comment by arlith** [comment]
Yes, the problem appears to be that there's an ATM launcher that doesn't have ammo.  I haven't loaded the saved game yet, but by looking at the stack trace and seeing the code in question, what's happening is it's trying to get the range for an ATM launcher, and to do that, it needs to know the ammo type.  The code just assumes there's ammo loaded and gets it, but in this case it must be returning null for the loaded ammo.

**Comment by arlith** [comment]
`WeaponType.getRanges` now checks to see if `weapon.getLinked()` returns non-null before using the value to adjust ranges based on ammo types.  If the value is null, the range weapon type's default ranges are used.

**Comment by arlith** [comment]
It's worth noting that this also causes other inconsistencies, such as the unit not having a tool tip if the weapon information is turned on for tool tips, and the unit display weapons tab also won't function.  The fix also takes care of these other issues.
