### ISSUE TITLE
Arrow VI Homing Artillery vs hex containing Elemental Battle Armor 

### ISSUE THREAD

**Issue by strategoslevel3** [MegaMek/megamek#2620]
### Environment
47.16 MacOS

### Description
Bug- Arrow IV Homing Artillery against hex containing Elemental Battle Armor [AOE Attack].
A Sprint VTOL uses TAG to tag the hex some Elementals are in. (The hex, not the BA)
An Arrow IV round lands in that hex.
By my understanding of the rules in TacOps it should do 5 damage to each Elemental.
For some reason in 47.16 it seems to be doing 3 lot of 5 damage.
TacOps AR pg 150
TacOps AUE pg 166

### Files
Game Log attached
![Screen Shot 2021-01-31 at 23 26 47](https://user-images.githubusercontent.com/67537490/106479487-4a5cb000-64a2-11eb-9099-271e9c235b8f.png)

**Comment by HammerGS** [comment]
You TAG'd the hex not a unit (TW pg 143). The the Arrow hits the hex and per pg 166 TO:AUE

_Alternatively, a homing missile may simply be fired, directly or indirectly, at a single hex without a TAG-designated target. If fired in this fashion, the attack only deals 5 damage to all units in the hex struck. If such an attack misses the target hex, it scatters as would a normal, non-guided artillery attack._

So in this case the Arrow works like an arty and does 20 points of damage in 5 point blocks to all units in the hex. 

So working as intended.

**Comment by HammerGS** [comment]
Digging around old errata...re-opening for now. Might be an issue with damage to terrain.

**Comment by jefga85** [comment]
> 
> 
> You TAG'd the hex not a unit (TW pg 143). The the Arrow hits the hex and per pg 166 TO:AUE
> 
> _Alternatively, a homing missile may simply be fired, directly or indirectly, at a single hex without a TAG-designated target. If fired in this fashion, the attack only deals 5 damage to all units in the hex struck. If such an attack misses the target hex, it scatters as would a normal, non-guided artillery attack._
> 
> So in this case the Arrow works like an arty and does 20 points of damage in 5 point blocks to all units in the hex.
> 
> So working as intended.

Perhaps I'm confused, but in the quoted text from AUE it says "only deals 5 damage to all units in the hex struck," but then you state that all units take 20 damage.  Where do you get the full 20 damage instead of 5?

**Comment by HammerGS** [comment]
Megamek had a bug regarding this. The rules team has clarified things as:

The hex is tagged,  the Battle Armor is not the target.

The hex takes 20 damage from the homing round as the tagged target.  The battle armor unit takes 5 damage as being another unit in the same hex as the target.

Each trooper in that battle armor unit takes 5 damage because it's an AE attack doing 5 damage.
