### ISSUE TITLE
47.16 Falconer quirk error

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#2623]
In Megamek, the Falconer mech (both variants) is listed as having the Stable quirk. Per Battlemech Manual (p. 91), it should have Stable and No Torso Twist. Please add the missing quirk to the quirk document.

**Comment by HammerGS** [comment]
Fixed as part of these series of commits https://github.com/MegaMek/megamek/commit/327d2d022f4b39293845d66760b7f3f7062a480e , https://github.com/MegaMek/megamek/commit/6cefd9790bcb825af394704919a21d1b1ee341fd , https://github.com/MegaMek/megamek/commit/f74e7da52c61d439866e7943d8aec5275afb68ca
