### ISSUE TITLE
Searchlight ranges not used.

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#2633]
From TacOps (corrected second printing, old omnibus edition) page 57, under **Searchlights**:

`Hand-held searchlights only reach 10 hexes, while mounted searchlights reach 30 hexes.`

Please add an option to use these ranges (10 hexes for infantry, 30 hexes for other units).

**Comment by HammerGS** [comment]
I think this is a bug. But while testing I found I could use a mech search light to illuminate 31 hexes away.

**Comment by HammerGS** [comment]
Tac Ops:AR pg 55 has the most current ranges
