### ISSUE TITLE
Melee specialist SPA description needs fixing

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#2639]
For the longest time, the Melee Specialist SPA is being shown as "melee_specialist":

![Melee specialist description](https://user-images.githubusercontent.com/70451747/107255122-37dbfc80-69f5-11eb-851c-1bedb0976912.png)

Probably using an internal name field rather than the display one.

**Comment by Windchild292** [comment]
I'm going to do a quick fix for this, but it brings up a deeper issue with how SPAs have been implemented that will need to be resolved going forwards.
