### ISSUE TITLE
[0.41.19 : Error] Dropship.isLocationProhibited Error

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#264]
There's more than enough place to deploy a landed dropship, but for some reason the Princess can't locate one. Savegame attached. Just load Princess up to see the error.
[Dropship.isLocationProhibitedErrorLog.txt](https://github.com/MegaMek/megamek/files/329126/Dropship.isLocationProhibitedErrorLog.txt)
[Dropship.isLocationProhibited.sav.gz](https://github.com/MegaMek/megamek/files/329127/Dropship.isLocationProhibited.sav.gz)

**Comment by SirMegaV** [comment]
Edit: Not more than enough, I've located 3.

**Comment by arlith** [comment]
Dropship.isLocationProhibited has an elevation check for seeing if a landing position is valid.  It checks all of the adjacent hexes.  This code wasn't written to handle cases where the central hex is a board edge.  I added some null-guards for null Coords.
