### ISSUE TITLE
Corrected Centurion CN10-D mtf

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#2645]
v47.17

Was missing CASE II. Goes into the ilClan Rec Guides/Vol 10 folder.
[Centurion CN10-D.zip](https://github.com/MegaMek/megamek/files/5955450/Centurion.CN10-D.zip)

**Comment by AlphaSled** [comment]
Bumping this, got missed in the last release.

**Comment by HammerGS** [comment]
Added
