### ISSUE TITLE
Quirks not loading for some units

### ISSUE THREAD

**Issue by ObviousTech** [MegaMek/megamek#265]
Originally, I thought units in unitQuirksOverride.xml that are not in canonUnitQuirks.xml are ignored, but it's not that exactly (see Atlas example).  After looking through a bit more, not sure what is causing some units to load with correct quirks and others to be missing all expected quirks.

0.41.19, windows
Was working fine in 0.41.17
Quirks override file that I was using is attached.
[unitQuirksOverride.zip](https://github.com/MegaMek/megamek/files/329141/unitQuirksOverride.zip)
To reproduce, try adding some units to your force in megamek.

Example units whose override quirks were missing for me:  Vindicator, Assassin, Savannah Master, Atlas (except AS7-00 (Jurn)), Marauder (except MAD-4X).

Some chassis (for example: Wasp, Wolverine) appear to have their canon and override custom quirks properly imported.

Note: There is a warning in the logs when loading KTO-19b, but removing that unit from the override file does not appear to fix the issue.

**Comment by pheonixstorm** [comment]
A new tag for quirks was added I think in this or the previous release.
For the mechs try adding `<unitType>Mech</unitType>` and see if that has any affect

**Comment by scJazz2** [comment]
Pheonixstorm, went and loaded a stock 3.29 clean download.

Quirks are not loading correctly at all.

For units like the Wolverine which has an "all" entry on line 5380 of canonunitquirks.xml only the models with specific entries like the WVR-7D get their quirks added. Models like the WVR-9W which do not have specific entries do not get any quirks.

Double checked this in override as well... fixing the old entry not containing unitType for the Atlas.

Only the specific models with specific entries get quirks. "ALL" entries are not working at all :)

**Comment by scJazz2** [comment]
Side note: Quirks do not match previous Quirks.

For instance 3.29 (MM 0.41.19) contains a reference to extended twist for specific Wolverines which has not existed previously.

**Comment by HammerGS** [comment]
@scJazz2 
1st SW books adds quirks for Locust, Wasp,Valkyrie, Shadow Hawk and the Wolverine.

**Comment by scJazz2** [comment]
> 1st SW books adds quirks for Locust, Wasp,Valkyrie, Shadow Hawk and the Wolverine.

Thanks Hammer, since I'm playing in 3025 era these same mechs come up a lot. Wasn't sure if that was an issue.

**Comment by HammerGS** [comment]
Doing some testing, I can't get any quirks to load.  I also tried adding a mech using the save quirks option for a Marauder and the save output matches whats in the Canon file.

**Comment by scJazz2** [comment]
So as not to confuse things... Quirks will load from canonQuirks as long as they declare a specific model. Any use of "all" does not work at all.

**Comment by Akjosch** [comment]
Fixed. If there are any other quirks bugs, open a new ticket please.
