### ISSUE TITLE
CamoChooser problems

### ISSUE THREAD

**Issue by SJuliez** [MegaMek/megamek#2650]
Unless this is already corrected on the master:

* The CamoChooser does not react to double clicking anymore.
* Selecting another directory, then NOT selecting a camo and clicking OK throws an NPE.

**Comment by Windchild292** [comment]
The double clicking was removed when I had to split it into panels because it kept breaking, and the NPE might be fixed in #2570

**Comment by SimonLandmine** [comment]
Darn. The double-click was handy. Ah well. The new panel display also hides the name of the came (which used to be visible next to the camo when it was a list format, and was handy when assigning the 'correct' camo to OpFor) - would it be possible to display it in a tooltip?
