### ISSUE TITLE
Conventional infantry should not inflict battle armor critical hits

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#2652]
Per TacOps (second corrected printing, old omnibus edition) page 108/109, battle armor should not take critical hits from conventional infantry unless they're firing a field gun.  However, with 47.16 (and all previous releases, from what I can tell) this still happens, including from ejected vehicle crews.

Gamelog attached, as txt:
[gamelog.txt](https://github.com/MegaMek/megamek/files/5975298/gamelog.txt)

```
Weapons fire for Vehicle Crew Jared Akinwole (Player 2)
    Auto-Rifle (Modern, Generic) at Cavalier BA Squad [MG] (Player 1);  needs 4, rolls 11 : 1 troopers hit, causing 1 damage.
        CRITICAL HIT on Trooper 1 (critical).
        Cavalier BA Squad [MG] (Player 1) takes 10 damage to Trooper 1 (critical).
TROOPER KILLED
```

**Comment by NickAragua** [comment]
@HammerGS will need to weigh in on this one, I'm not seeing anything in my copy of TacOps regarding no crits from infantry.

**Comment by neoancient** [comment]
I don't see it in the 2018 printing, but it's in the errata and in the newer TO:AR, p. 106.
