### ISSUE TITLE
ilClan Recognition Guide duplicates

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#2654]
The following changes should be made in the ilClan Rec Guides folders:

-The Warhammer WHM-8R file in Vol. 4 should be deleted.
-The Warhammer WHM-9K in Vol. 4 should be deleted.
-The Marauder IIC 5 file in Vol. 6 should be deleted.
-The Marauder IIC 6 file in Vol. 6 should be deleted.
-The Phoenix Hawk PXH-2K should have its introductory date fixed to be 3050.

**Comment by AlphaSled** [comment]
In additition, the Phoenix Hawk PXH-3D, -3K, -3M, and -3S should be deleted from Vol. 11

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/415bdd1a94011a6619a401eb44695d697d84b73f
