### ISSUE TITLE
Battlemech Quad Turret firing arc does not reflect turret rotation changes

### ISSUE THREAD

**Issue by mjbroekman** [MegaMek/megamek#2659]
### Environment
 	MekHQ 0.47.17
	Java vendor N/A (openjdk)
	Java version 15.0.1
	Platform Mac OS X 10.15.7 (x86_64)

### Description
When a Quad mek is equipped with battlemech turrets, the firing arcs of the turret do not update to reflect turret rotation. Instead, the firing arcs remain fixed according to the firing arc of the location that the turret is in.
<img width="1237" alt="Screen Shot 2021-02-16 at 9 01 58 AM" src="https://user-images.githubusercontent.com/5141448/108073817-7a758880-7036-11eb-9f58-ab03a0415fcb.png">
<img width="878" alt="Screen Shot 2021-02-16 at 9 02 19 AM" src="https://user-images.githubusercontent.com/5141448/108073848-85301d80-7036-11eb-879b-9fdacaa5e697.png">
<img width="860" alt="Screen Shot 2021-02-16 at 9 02 29 AM" src="https://user-images.githubusercontent.com/5141448/108073864-89f4d180-7036-11eb-852f-c1f581708cbf.png">

### Files
[firingarc.sav.gz](https://github.com/MegaMek/megamek/files/5989146/firingarc.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/5989151/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/5989152/mekhqlog.txt)

**Comment by HoneySkull** [comment]
![image](https://github.com/MegaMek/megamek/assets/83041327/c1df54bf-d8f0-4fba-bac4-b1d2181cbadd)
