### ISSUE TITLE
Searchlight & Physical Attacks Bug During Night

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#266]
Bronzebeard had brought this up first on IRC and I verified it during my full moon night scenario.  Without clicking the searchlight button after targeting an enemy unit the searchlight will be turned on when you fire illuminating your mech and the target without the player's request for the searchlight to be turned on.

During the physical attacks phase MM will select and want me to declare physical attacks for my unit(s) that dont have an enemy unit near them and I think these units did fire and use their searchlight during the firing phase if that has anything to do with it.  Skip ineligible during physical attack phase option is checked.

Also, (Arlith is already aware) Athenry's gravity is 1.04G and is applying the +1 modifier to all PSRs instead of just for jumping in high/low gravity and also should not apply the +1 unless the gravity is +/- 0.5G from standard.

TacOps pg55:
Potential Damage From Jumping: Make a standard Piloting Skill Roll, applying a modifi er for every full 0.5 gravities above or below 1. For example .2 would apply a +1 modifi er, while a 2.6 would apply a +3 modifi er
.......
Weapon Attacks: Add a +1 to-hit modifi er to all direct-fi re ballistic and missile weapon attacks for every .2 G (or fraction thereof) above or below the Terran standard 1 G.

[multibug.zip](https://github.com/MegaMek/megamek/files/331228/multibug.zip)

**Comment by pheonixstorm** [comment]
That first example makes no sense... +1 for every full .5 means a .2 should not get a modifier. Think that might need to get a question in the rules forum. Have you checked the latest errata?

**Comment by BLOODWOLF333** [comment]
High/Low Gravity (p. 55)
Under “Potential Damage From Jumping”, first sentence
“Make a Piloting Skill Roll, adding the appropriate modifiers for low gravity; a standard Piloting Skill Roll is made in high
gravity, with no modifiers.”
Change to:
“Make a standard Piloting Skill Roll, applying a modifier for every full 0.5 gravities above or below 1. For example .2 would
apply a +1 modifier, while a 2.6 would apply a +3 modifier.”

That still contradicts itself with 0.2 adding a +1 when in the previous sentence "applying a modifier for every full 0.5 gravities above or below 1."

**Comment by BLOODWOLF333** [comment]
I dont think this errata is applied in MM either http://bg.battletech.com/forums/index.php?topic=41824.msg964155#msg964155

Add a +1 to-hit modifier to all direct-fire ballistic and missile weapon attacks for every .2 G (or fraction thereof) above or below the Terran standard 1 G.
Change to:
Add a +1 to-hit modifier to all direct-fire ballistic and missile weapon attacks for every full .2 G above or below the Terran standard 1 G.

**Comment by BLOODWOLF333** [comment]
Asked xtol http://bg.battletech.com/forums/index.php?topic=53311.0

**Comment by pheonixstorm** [comment]
That makes more sense. 99% of the time its user error lol

**Comment by BLOODWOLF333** [comment]
After seeing the new release notes, the "above" high/low grav issue is related to #243 .

**Comment by BLOODWOLF333** [comment]
Searchlight function can only be turned off during the movement phase since MM does not have an end phase which the players can adjust options for their units.  As told to me by Arlith.

**Comment by BLOODWOLF333** [comment]
Did it again, is asking for my enforcer to declare physical attacks when the only thing next to him is trees.
HQ 0.3.32 bundle.  Skip ineligible for phsyical is checked.

[physbug.sav.gz](https://github.com/MegaMek/megamek/files/453803/physbug.sav.gz)

**Comment by BLOODWOLF333** [comment]
If no luck with ^ that save this is at the beginning of the phys phase and the archer has nothing around him except trees, find club option is not selectable

[physbug.sav.gz](https://github.com/MegaMek/megamek/files/453805/physbug.sav.gz)

**Comment by BLOODWOLF333** [comment]
Saved during the firing phase before the bug occurs afterwards during the physical attacks for ineligible units (no targets around the Archer and friendly fire is off).

[PhysicalBug.zip](https://github.com/MegaMek/megamek/files/465760/PhysicalBug.zip)

**Comment by arlith** [comment]
Ok, so what's happening here is this "assist" code that's written in.  MM checks to see if a unit could make physical attacks *or* assist someone else making a physical attack.  Right now, assistance basically comes down to searchlight spotting.  If a unit has an active searchlight, in theory they could use it to illuminate someone elses' target, and hence assist that.  If they were skipped, they'd miss that opportunity, so they can't be skipped.
