### ISSUE TITLE
(MegaMek 0.47.17) NullPointerException Error Found During a Mission

### ISSUE THREAD

**Issue by ACluelessFool** [MegaMek/megamek#2662]
### Environment
```
MekHQ v0.47.17 RC3
Windows 10
Java 11
```

### Description
Was playing in a Probe mission on the Attacker side, deployed two mech lances (I unfortunately forgot to take screenshots when I ran into the issue). On Round 3 after I collapsed a building a turret was on, Princess immediately entered a state of no action when the physical attack phase came up (I had simul. phys attacks on). Parsed both megameklog and mekhqlog and came across a NPE error in the mekhqlog.

### Files
[mekhqlog_ApocAngelsVSLyranCommon_no1.txt](https://github.com/MegaMek/mekhq/files/5992731/mekhqlog_ApocAngelsVSLyranCommon_no1.txt)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/5992734/megameklog.txt)
[Bug Report Package.zip](https://github.com/MegaMek/mekhq/files/5992749/Bug.Report.Package.zip)

.zip file has the .cpnx file and the customized mechs at the time.

**Comment by NickAragua** [comment]
A MegaMek save would be more helpful in these situations - ideally, a save from right before the behavior occurred, or, if not possible, an autosave from the beginning of the round and a description of the actions taken.

**Comment by NickAragua** [comment]
Looking at the code, the error appears to have been caused by error logging. How ironic.
