### ISSUE TITLE
Warhammer IIC

### ISSUE THREAD

**Issue by WildKadabra** [MegaMek/megamek#2665]
This is not really a bug but more of, what to my understanding, is a mistake with the build. I couldn't find anything about it being reported.

v.0.47.17 and v.0.47.16

Warhammer IIC - 13

Listed as having IS Medium Pulse Lasers

BattleTech: Recognition Guide: ilClan Volume 3 lists the mech tech base as being purely clan tech. Its record sheet shows the medium pulse lasers with clan range and damage values.

I apologize if this is the wrong section to post this issue.

**Comment by HammerGS** [comment]
Fixed https://github.com/MegaMek/megamek/commit/415bdd1a94011a6619a401eb44695d697d84b73f
