### ISSUE TITLE
[41.19 bug] Unit camo fails to load

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#268]
In two of my last games the camo for one of my units failed to load. The unit used plain white for the entire game. I've saved what I think are the proper logs. Is there some way I can upload them, and which do you need?

**Comment by HammerGS** [comment]
You should be able to drag or select them into the text box here.

**Comment by arlith** [comment]
Any possibility of getting those files uploaded?  

At the bottom of the text box in GitHub, there's a message that says, "Attach files by dragging & dropping or selecting them."  The "selecting them" part is a link that will open a file dialog.

**Comment by VampireSeraphin** [comment]
[megameklablog.txt](https://github.com/MegaMek/megamek/files/350230/megameklablog.txt)
[megameklog.txt](https://github.com/MegaMek/megamek/files/350228/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/350229/mekhqlog.txt)

I think these are the right ones. My bad, I got side tracked and forgot to add these.

**Comment by VampireSeraphin** [comment]
Saw this bug again last night. 
[megameklog.txt](https://github.com/MegaMek/megamek/files/354534/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/354535/mekhqlog.txt)

**Comment by BLOODWOLF333** [comment]
I missed this being reported already......mine has pictures #273

**Comment by arlith** [comment]
Closing this one as a duplicate of #273.
