### ISSUE TITLE
Target info cleared when switching weapons

### ISSUE THREAD

**Issue by BowtieBob** [MegaMek/megamek#2684]
### Environment
What version of MegaMek does your issue apply to?  HQ's MegaMek
What operating system are you using?  Windows
What java version are you using?  	AdoptOpenJDK version 11.0.9.1

### Description
When switching weapons without firing, the targeting info in the weapon pane disappears unless you manually reselect the target again.
![image](https://user-images.githubusercontent.com/70545594/109249937-4b85b200-77ae-11eb-9aa7-cabeb06e086d.png)
![image](https://user-images.githubusercontent.com/70545594/109249975-5dffeb80-77ae-11eb-927a-c3f6f57b4cec.png)
Notice that the target is still highlighted, and the fire button is still available, you just can't see what the target is or the to hit value.
It does not seem to matter if the weapon is in range or not.

**Comment by kuronekochomusuke** [comment]
fixed by #4012
