### ISSUE TITLE
Elementals have no movement points

### ISSUE THREAD

**Issue by BowtieBob** [MegaMek/megamek#2692]
### Environment
What version of MegaMek does your issue apply to?   HQ's MegaMek 0.47.17.
What operating system are you using?  Windows
What java version are you using? Openjdk 11

### Description
I've started a battle (twice) with a star of elementals, and for some reason they have 0 movement points.
![image](https://user-images.githubusercontent.com/70545594/109742978-92501f00-7b95-11eb-901c-b13cf798ee3c.png)

### Files
[Battle.sav.gz](https://github.com/MegaMek/megamek/files/6073227/Battle.sav.gz)
playername: Nightstalkers
[Nightstalkers30621117.cpnx.gz](https://github.com/MegaMek/megamek/files/6073231/Nightstalkers30621117.cpnx.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/6073233/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/6073234/mekhqlog.txt)

Custom units
[customs.zip](https://github.com/MegaMek/megamek/files/6073242/customs.zip)

**Comment by BowtieBob** [comment]
I think I found the problem. I didn't notice that this scenario has the wind value set to "Storm". Changing that setting allows them to move.

**Comment by HammerGS** [comment]
Closing.
