### ISSUE TITLE
48.0 (Data) - unit intro dates and names

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#2696]
Spotted some unit introduction dates in MM that were inconsistent with the MUL while collecting "civilian" units. I assume these should be updated to match the MUL. 

Garrot Superheavy Transport - MM says 3125, [MUL says 3100.](http://www.masterunitlist.info/Unit/Details/6539/garrot-superheavy-transport-standard)
Nifty Transportable Field Repair Unit - MM says 3069, [MUL says 3071.](http://www.masterunitlist.info/Unit/Details/4716/nifty-transportable-field-repair-unit-standard)
Peacekeeper PK-6 SecurityMech - MM says 3065, [MUL says 2522.](http://www.masterunitlist.info/Unit/Details/7159/peacekeeper-pk-6-securitymech)
Peacemaker PM-6 PoliceMech - MM says 3070, [MUL says 3067.](http://www.masterunitlist.info/Unit/Details/7173/peacemaker-pm-6-policemech) (Note that this unit's name currently uses "PM6" rather than the correct "PM-6", so that should also be corrected)
Dig King RCL-1 MiningMech MOD - MM says 2573, [MUL says 2802.](http://www.masterunitlist.info/Unit/Details/7172/dig-king-rcl-1m-miningmech-mod)
Crosscut ED-X4 LoggerMech - MM says 2786, [MUL says 2876.](http://www.masterunitlist.info/Unit/Details/4024/crosscut-ed-x4-loggermech)
Powerman SC XV HaulerMech - MM says 2795, [MUL says 2895.](http://www.masterunitlist.info/Unit/Details/4852/powerman-sc-xv-haulermech)
Scavenger SC-V-M MilitiaMech - MM says 2800, [MUL says 2990.](http://www.masterunitlist.info/Unit/Details/7174/scavenger-sc-v-m-militiamech)
Heavy Lifter HCL-1 CargoMech - MM says 3060, [MUL says 3066.](http://www.masterunitlist.info/Unit/Details/4274/heavy-lifter-hcl-1-cargomech)
Uni ATAE-70T CargoMech - MM says 3050, [MUL says 3074.](http://www.masterunitlist.info/Unit/Details/7175/uni-atae-70t-cargomech) (Note that this is the variant with TSM; similar name to the base variant)
Lumberjack LM5/M MilitiaMech - MM says 3070, [MUL says 3076.](http://www.masterunitlist.info/Unit/Details/7177/lumberjack-lm5m-militiamech)

MM also lists a unit as "Crosscut ED-X5M-B LoggerMech MOD"; both the MUL and the TRO:VA record sheets refer to the matching unit as the ["Crosscut ED-X5M-B DemolitionMech MOD"](http://www.masterunitlist.info/Unit/Details/7171/crosscut-ed-x5m-b-demolitionmech-mod) (name issue only, rather than intro date). Note that this is the -B variant with the dual saw and snub PPC; the "Crosscut ED-X5M LoggerMech MOD" with an AC/2 is correctly named.

Megamek has unit entries for the "Danais (2720)" and "Danais (Standard)" dropship. The former (listed with TRO 3057R as the source) is not listed on the MUL and should probably be removed. [The latter](http://www.masterunitlist.info/Unit/Details/823/danais-standard) (with Jihad Secrets - The Blake Documents listed as the source) appears to be correct, including the introduction date of 2728. Similarly, the Trojan (Blockade Runner) dropship is listed twice, with one being tagged as (2720) as well. That one should also be deleted, and the introduction date of the remaining Trojan (Blockade Runner) updated to [2745 to match the MUL](http://www.masterunitlist.info/Unit/Details/5300/trojan-blockade-runner) (currently both are listed as 2720). 

The Overlord (Combined Arms) variant introduced in 2775 should be renamed to Overlord (Vehicle) to [match the MUL.](http://www.masterunitlist.info/Unit/Details/4775/overlord-vehicle)

**Comment by HammerGS** [comment]
Fixed with - https://github.com/MegaMek/megamek/commit/a6602c27214d17c626c4f741c50cef5edf57568d
