### ISSUE TITLE
MegaMekLab Freeze when using Load from Cache

### ISSUE THREAD

**Issue by thudgun** [MegaMek/megamek#270]
Every time I try to load from Cache the program freezes, and I have to End Task to clear it.
Using MegaMekLab v 0.1.55
Windows 10
Java 8 Update 91

**Comment by BLOODWOLF333** [comment]
This was fixed over on the MegaMekLab tracker issue #16.  Version 0.1.56 is the latest release where this should be fixed.

**Comment by HammerGS** [comment]
Per Bloodwolfs comments fixed in latest release.
