### ISSUE TITLE
Target Weight not working in Force Generator

### ISSUE THREAD

**Issue by BowtieBob** [MegaMek/megamek#2701]
In 0.48.0, I'm trying to generate a light recon force, but no matter what I set the target weight to, I get mostly heavy/medium forces. Every so often it will list an assault class force, and even less than that a light force will appear. 

![image](https://user-images.githubusercontent.com/70545594/110245233-e8bbb580-7f27-11eb-862c-1dc2cf59a6bb.jpeg)

**Comment by neoancient** [comment]
The target weight is a hint that tends to make the unit lighter or heavier, but as the tooltip explains there is no guarantee of a match.

**Comment by BowtieBob** [comment]
Maybe the weighting needs to change then. I tried to generate a light star. I'll bet I clicked it more than 50 times and only one light force came up.

**Comment by neoancient** [comment]
The tool is not suited to generating a unit with a specific weight class.
