### ISSUE TITLE
Stormcrow names for .mtf files

### ISSUE THREAD

**Issue by AskAgain** [MegaMek/megamek#2707]
### Environment
48.0
Windows
Java version 1.8.0_281

### Description
New Ryoken (Stormcrow) configuration naming conventions are reversed causing them to improperly source the associated sprite. I am uncertain if this is true for other new additions as well.

### Files
![Capture](https://user-images.githubusercontent.com/50790862/110724505-fdaf7780-81b9-11eb-8ae5-f0e26862393b.JPG)
![Capture](https://user-images.githubusercontent.com/50790862/110724544-11f37480-81ba-11eb-9522-e191d806932d.JPG)

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/954145efc0c825f404cb357ff7bc9ef4f21dc176
