### ISSUE TITLE
Equipment improperly tagged as fixed on recent omni designs

### ISSUE THREAD

**Issue by flowerygrackle** [MegaMek/megamek#2709]
### Environment
What version of MegaMek does your issue apply to?  48.0, MekHQ's Megamek.

### Description
Many recent mechs - from the ilClan recognition guides, mostly/entirely? Have equipment that is set as fixed in their MTFs that are, in reality, omnipod mounted. I currently do not have time to dig through them thoroughly and find every single one, but an almost-certainly non-exhaustive list is the following:

War Crow
Carrion Crow
Inferno
Stormcrow J K P T
Uller T
Dragonfly L M J K T
Lupus C (Just The Supercharger)
Dasher I J
Vulture I T
Dasher T
Koshi M N T
Shadow Cat T

**Comment by HammerGS** [comment]
- [ ] War Crow
- [ ] Carrion Crow
- [ ] Inferno
- [ ] Stormcrow J K P T
- [ ] Uller T
- [ ] Dragonfly L M J K T
- [ ] Lupus C (Just The Supercharger)
- [ ] Dasher I J
- [ ] Vulture I T
- [ ] Dasher T
- [ ] Koshi M N T
- [ ] Shadow Cat T

**Comment by HammerGS** [comment]
Fixed
