### ISSUE TITLE
Cannot Move Through Hex Occupied by a Friendly, Swarmed Unit

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/megamek#271]
[337th.sav.gz](https://github.com/MegaMek/megamek/files/352123/337th.sav.gz)

See the swarmed Ajax tank owned by player 337th in the attached save. I noticed that I can move a friendly unit into its hex, but not through it - the hex is being counted as though occupied by an enemy unit. Total Warfare p63 suggests that swarming infantry (and even normally deployed infantry) do not count towards stacking limits, nor halt the movement of a mech that enters their hex.

**Comment by arlith** [comment]
I can't reproduce this.  I presume you're talking about the Ajax in 0719.  It looks like the Devestator in 0921 is the only unit that can move through that hex legally.  However, I am able to move the Devestator into and through the Ajax's hex.

![mp1](https://cloud.githubusercontent.com/assets/13815237/16743259/10bdedd0-4771-11e6-805b-d3a2bf78e058.png)

![mp2](https://cloud.githubusercontent.com/assets/13815237/16743263/13f55c4a-4771-11e6-9699-9359a693f4de.png)

**Comment by pheonixstorm** [comment]
what option is that arlith and where can i find it?

**Comment by arlith** [comment]
@mkerensky 
Yea, I *did* find that when I moved to 0718 that Princess got a pointblank shot.

@pheonixstorm 

I'm not sure what you're referring to.  Are you referring to the "movement envelope" (showing possible moves)?  It's in View -> Show Possible moves.  There's a keyboard shortcut too, I think the default is Ctrl-Q.

**Comment by pheonixstorm** [comment]
Yeah, that sounds like it, thanks arlith
