### ISSUE TITLE
Battle Armor and Turret BV calculations not appearing

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#2716]
v.48.0

The "Show BV Calculation" button does not display the calculations for Battle Armor or Turrets.
Instead, the pop-up that appears contains no text.

![Capture](https://user-images.githubusercontent.com/17106678/111074350-ebcf1c80-84b8-11eb-88f9-836020e77a0a.PNG)

**Comment by sixlettervariables** [comment]
Not currently implemented.

BA and Turrets do not create any text when they calculate their battle value:

https://github.com/MegaMek/megamek/blob/954145efc0c825f404cb357ff7bc9ef4f21dc176/megamek/src/megamek/common/BattleArmor.java#L892

https://github.com/MegaMek/megamek/blob/954145efc0c825f404cb357ff7bc9ef4f21dc176/megamek/src/megamek/common/GunEmplacement.java#L195

**Comment by HammerGS** [comment]
BA is now implemented in the latest Dev release. Given our turrets aren't ever remotely close to RAW closing this and when one day we get building and turrets proper BV can be revisited at that time.
