### ISSUE TITLE
Hardened Armor PSR roll from damage incorrect

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#2720]
From Facebook
![image](https://user-images.githubusercontent.com/13752452/111173278-234ad100-856c-11eb-9ac8-476487e436a9.png)

### Environment
What version of MegaMek does your issue apply to?  .48
What operating system are you using?  Windows
What java version are you using?  Java 11 

### Description
TacOps Advanced Units & Equipment states, on page 93, under hardened armor:
"Each full armor bubble lost only counts as one point of damage for Piloting Skill Roll purposes"

**Comment by AlphaSled** [comment]
Related: https://github.com/MegaMek/megamek/issues/2032

**Comment by neoancient** [comment]
Duplicate of #2032
