### ISSUE TITLE
Marauder II Sprite Facing Incorrect, Camo not applied

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#273]
Trying to work on making a movie for the weapons & sound FX but, the sprite for the Marauder II is not facing the correct direction in regards to the white facing arrow.

![mm0](https://cloud.githubusercontent.com/assets/16950832/16705232/eae3ef6c-4548-11e6-963e-6c30bd48082d.png)

And I seen that camo color error in my log I think that  has to do with the color for the mini map?  Am using the poprocks high quality camos and I think it would be less problematic to just leave the unit color determination how it was in the old versions instead of going off the camo since it obviously is causing issues with custom camos.  Doesnt cause any problems though, Im blue and princess is red.
EntityImage.applyColor(): Failed to grab pixels for camo image.null

Player name: BLOODWOLF
[Facing.zip](https://github.com/MegaMek/megamek/files/355343/Facing.zip)

**Comment by BLOODWOLF333** [comment]
Also, that MAD should have a green & black poprocks camo on it.....

**Comment by BLOODWOLF333** [comment]
You fixed this @alrith

**Comment by arlith** [comment]
This will be fixed by changes that are in PR #319.  The issue won't actually be fixed until that PR is merged in, so I'm going to leave it open until that happens.
