### ISSUE TITLE
MM 0.48.0 Data: Scorpion Light Tank APC (Kaliban)

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#2733]
Data error in MM 0.48.0

The "Scorpion Light Tank APC (Kaliban)" is coded as Chassis = "Scorpion" Model = "Light Tank APC (Kaliban)", so gets assigned the Scorpion 'mek sprite.

Suggest classifying as Chassis = "Scorpion Light Tank" Model = "APC (Kaliban)".

**Comment by HammerGS** [comment]
I don't even see this unit in the repo

![image](https://user-images.githubusercontent.com/13752452/115944972-6d31ab80-a476-11eb-955a-35955481fbbf.png)

**Comment by SimonLandmine** [comment]
That would be because I'm an idiot, and it's an unofficial unit that I acquired from someone on the forum, so it's in my customs folder. I should have checked that. [facepalm]
