### ISSUE TITLE
Corrected Warhammer C 3 mtf

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#2739]
v.48.0 
Unit was missing its targeting computer.
Goes into mechs/ilclan rec guides/volume 7 folder.

[Warhammer C 3.zip](https://github.com/MegaMek/megamek/files/6179408/Warhammer.C.3.zip)

**Comment by HammerGS** [comment]
Fixed

**Comment by AlphaSled** [comment]
Bumping this---looks like the fix didn't make it into the most recent version of MM as of 49.8

**Comment by HammerGS** [comment]
Fixed again.
