### ISSUE TITLE
Update MegaMek Readme

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#274]
MegaMek/docs/readme (last line)

BattleTech, Mech, BattleMech and MechWarrior are Registered Trademarks of 
WizKids, LLC.  Original BattleTech material Copyright by  WizKids, LLC.
All Rights Reserved.  Used without permission. 

Change to:

Classic BattleTech, BattleTech, BattleMech, ‘Mech, and MechWarrior are registered trademarks and/or trademarks of The Topps Company, Inc. in the United States and/or other countries.

I can change this when I get home and provide the new readme.txt if this is correct?

**Comment by arlith** [comment]
This was fixed with the pull request.
