### ISSUE TITLE
48.0 Missing Gazelle DropShip variant

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#2746]
Megamek currently has unit data for two variants of the Gazelle DropShip - the original variant introduced in 2531, and the upgraded variant introduced in 3055. However, there is a third variant listed in TRO 3057r and the MUL, the [Heavy Vehicle variant introduced in 2857](http://www.masterunitlist.info/Unit/Details/4206/gazelle-heavy-vehicle), which swapped the original 15 Light Vehicle Bays for 15 Heavy Vehicle Bays by cutting into the cargo space (according to the description and unit data provided in TRO 3057r). 

Attached is a .blk file for the Heavy Vehicle Gazelle, constructed according to the data in TRO 3057r (identical to the 2531 Gazelle outside of the Light to Heavy vehicle bay swap, and the resulting reduced cargo tonnage, plus the name and intro date change). This should go in the dropships.zip\TRO3057R\IS folder. 

[Gazelle (Heavy Vehicle).zip](https://github.com/MegaMek/megamek/files/6201394/Gazelle.Heavy.Vehicle.zip)

**Comment by HammerGS** [comment]
Added
