### ISSUE TITLE
MASC/Supercharger target numbers not handled separately

### ISSUE THREAD

**Issue by jma5terj** [MegaMek/megamek#2749]
### Environment
Megamek 48.0 (though this was present in 46.1 as well)
Windows 10
Java 1.8.0_281

### Description
When a mech has both a supercharger and MASC, they aren't treated as separate systems with different target numbers. Rules-wise, that mech should be able to turn off the supercharger and turn on MASC on turn one and take a 3+ roll for MASC when using it. On turn two, if the mech turns on the supercharger and turns of MASC, there should be a 3+ roll for the supercharger. This swapping should be continuable until one of them fails. Megamek does not handle the target number separately for each system. In the above example, on turn two the target number is 5+ for the supercharger system.

Appears to be related to #2563 . It seems as if MASC and supercharger are not handled separately enough.

### Files
Game is saved after the two turns described above. I turned on both systems and now they both need a 7+ to function, when it should be a 5+ for the supercharger and a 3+ for the MASC system. Player name is Eagle, bot name is Princess.
The megameklog.txt has been provided, but there are no errors besides an initial one where I tried to start a second server on the same port.
[masc_supercharger_bug.zip](https://github.com/MegaMek/megamek/files/6211918/masc_supercharger_bug.zip)

**Comment by jma5terj** [comment]
In `Entity.java` there's only one number to track the number of turns both MASC and supercharger has been used:
```
// MASCLevel is the # of turns MASC has been used previously
    protected int nMASCLevel = 0;
```

**Comment by Tecmes** [comment]
Also in 49.1+398, the confirm message to roll for SC actually says "MASC".

**Comment by pakfront** [comment]
I can take this.

**Comment by pakfront** [comment]
Just to clarify, reading the BTM, MASC needs the turn counter to track how many turns it has been used for, as risk accumulates over time, but superchargers do not, as they have no malus for continued operation. Correct?

**Comment by gsparks3** [comment]
Per TO:AUE page 157 or BMM page 116, Superchargers "follow the same rules as MASC" with regards to failure chance increasing and decreasing depending on usage.

**Comment by pakfront** [comment]
I can see why the code does what it does  - Superchargers are a subtype of MASC in MiscType, so their tracking gets conflated in Entity, Mech and MoveStep (and elsewhere.) It often checks if it has one, or both, but not which specific one. This will take some more digging and likely a lot of small changes.

**Comment by pakfront** [comment]
if a player has both systems armed, but moves only enough to need one, should we automatically assume they are using the one with the lowest chance of failure?

**Comment by jma5terj** [comment]
I think that makes the most sense. If they want to specify the worse roll they can always deactivate the other one. Thanks for working on this!

**Comment by pakfront** [comment]
It's unclear in the rules if a failed supercharger roll applies both the MASC leg crits and the Supercharger torso crits, or just the torso crits. The existing code applied both, but I suspect this is incorrect and only the torso crits should be applied. Anyone know for sure?

**Comment by gsparks3** [comment]
It's definitely only the (guaranteed) leg crits for MASC and (possible) CT crits for SC. The effect on a failure is specified as one of the differences between SC and MASC.

**Comment by pakfront** [comment]
Are there any non-Mech units that have MASC, Supercharger or some other Run MP multiplying system?

**Comment by gsparks3** [comment]
Ground vehicles can use Superchargers. VTOLs also have the "VTOL Jet Booster" item. However, the latter doesn't have a failure roll the way MASC or SC do.

**Comment by pakfront** [comment]
What are one or two of specific vehicles that have Superchargers and VTOLs that have Jet Boosters? Would be helpful to have them to test with.

**Comment by HammerGS** [comment]
You and can search for them using advanced search in the unit selector. Not near my machine.

**Comment by gsparks3** [comment]
Some quick examples:
SC: Pegasus Scout Hover Tank X
VJB: Kestrel VTOL (Scout)

**Comment by AlphaSled** [comment]
Just chiming in to mention the ProtoMech Myomer Booster. An example would be the Centaur 4.
It operates a bit differently in that its failure number is always 2, regardless of how many consecutive turns you use it, and that failure leads to a single pilot hit.

**Comment by pakfront** [comment]
![StepSprite](https://user-images.githubusercontent.com/1423800/152409342-9203078b-691f-4d90-b4de-4424d60f39c0.png)
I have pretty much everything working (pending more testing) - one issue is that if you have MASC and SC, displaying the two rolls in StepSprite takes up a lot of room, larger than the sprite allows. I think the right fix is to reduce the font size for the roll hints. Agree/Disagree/other ideas?

**Comment by jma5terj** [comment]
Could you make it two lines? Not sure that fits either. Maybe slightly smaller font and two lines would work?

**Comment by pakfront** [comment]
![StepSprite2](https://user-images.githubusercontent.com/1423800/152416947-77f02c60-a43a-4067-a68c-dd2ebc3614e3.png)
Yes, how about this?

**Comment by HammerGS** [comment]
I find the side by side confusing. What about adding a M or an S, or MASC on the side and Supercharger on the bottom? Something that says which each number is.

**Comment by pakfront** [comment]
![StepSprite3](https://user-images.githubusercontent.com/1423800/152421385-fad965ab-0033-4f97-8504-d5e2d0733a86.png)

**Comment by HammerGS** [comment]
Yeah, that works for me.

**Comment by NickAragua** [comment]
Can we retain the brackets, or does that spill outside the hex? If it spills outside the hex, this is fine.

**Comment by pakfront** [comment]
It just fits, but is pretty crowded
![StepSprite4](https://user-images.githubusercontent.com/1423800/152448194-6145b862-4326-4dcb-8fe0-f136c447e21b.png)
.

**Comment by Windchild292** [comment]
I prefer without myself
