### ISSUE TITLE
Non-optimal paths planned in certain circumstances

### ISSUE THREAD

**Issue by arlith** [MegaMek/megamek#275]
There are certain circumstances where the paths planned are no optimal.  Here's a screenshot with an example:

![screenshot-4](https://cloud.githubusercontent.com/assets/13815237/16751306/ee2403a4-479d-11e6-8a34-c825eb4dd5c6.png)

The cause of this issue is in how ties are arbitrated in the A* heuristic.  Right now, if two paths are tie, then the tie is arbitrated by picking the path with the *most* hexes moved.  I think the idea is that, if two paths have equal cost, choose the one with the most hexes moved, in hopes of achieving a higher target movement modifier.  However, as is seen in the above screenshot, this can lead to non-optimal paths.  Essentially the problem can be seen in these examples from testing output I created:

````
Path L F (7) vs Path L L (7): first
...
Path L F L (7) vs Path L L (7): first
...
Path L F L (7) vs Path L L (7): first
````

The selected non-optimal path consistently ties with the optimal path, put the non-optimal path is chosen because it moves more hexes than the optimal path.

**Comment by arlith** [comment]
I fixed this by instead preferring paths with fewer moved hexes (basically removed the sign change on the number of hexes moved difference).

**Comment by dericpage** [comment]
Would a better fix for this be using the TMM as a tie-breaker for the heuristic?  I know it's more complex, but that better fits original the intent of defaulting to the longer path.  This potentially has greater impact for bot clients and human, of course.

**Comment by Akjosch** [comment]
Wait, how is the chosen path "non-optimal"? It has the exact same heat, movement modifier (for both sides) and movement mode (walking) characteristics, while *also* at the same time covering one more hex and thus allowing to potentially see more of the map in a double-blind scenario.

I'd say the screen-shot shows the *more* optimal path given the game rules.

**Comment by djmbm** [comment]
Except that it doesn't give you any more distance at the end of the path, so you won't see anything more.

**Comment by Akjosch** [comment]
Well, it'll at the very least give you more information about things which trigger during movement phase, like (some) mine fields or hidden units.

**Comment by dericpage** [comment]
Mainly, I'd say it's non-optimal from a designating "waypoints" stance.  There's been a few times when I've clicked on a hex with the intention of either marking a specific path or planning a one or two hex turn at the end of my move.  When the pathing code auto-picks the longest path (regardless of actual advantage), I end up not being able to do what I planned and end up having to cancel the input and then manually enter each step.  

For example, if the above unit had a walk of only 7 and there were an enemy unit in hex 206, I cannot do a one-hex turn to keep him out of my rear arc without cancelling the move and then going back to manually click hex 307 before clicking 309 in order avoid stepping into 306 and "wasting" an MP.

**Comment by arlith** [comment]
It's non-optimal because it takes 7MP to get to 0309, whereas the optimal path (L L F L F F) takes 6MP.

**Comment by arlith** [comment]
Using TMM to break ties would cause the same 7MP path to get chosen in this case (since it has a TMM of +1, whereas the shortest path has a TMM of +0).

Ultimately, I think this is at odds with what we are trying to accomplish: finding the shortest path (in terms of MP) between two locations.  If we arbitrate ties by finding a "longer" path, then it's not going to behave well in all cases.

We already have other path planners for different purposes, such as finding longest paths.  If we want to find a path with the best TMM, we have a planner to do that.
