### ISSUE TITLE
[Feature Request] Option to use Hex lines and numbers like in 0.46 

### ISSUE THREAD

**Issue by MGM175** [MegaMek/megamek#2751]
### Environment
MegaMek 0.48.0
Windows 10 20H2
Java Vendor Azul Systems, Inc.
Java Version 15.0.2

### Description
I have a buddy who's using 49 inch TV to play MegaMek, and he's complaining about readability of hex net and numbering in 0.48. He suggested to add option to switch between the thickness and hex number size, like it was in 0.46.

### Files
Screenshots for comparision:

0.48.0
![2021-03-28_16-44-02](https://user-images.githubusercontent.com/20325180/112756584-39ce3f00-8fe6-11eb-8355-f61960c790d6.png)

0.46.1
![2021-03-28_17-23-27](https://user-images.githubusercontent.com/20325180/112757693-296c9300-8feb-11eb-8c9f-3df4180f5bda.png)

PS: I've told him to post the issue himself, yet he told me that he doesn't want to create Github account. I've posted this due to fact that due to this, we're effectively stuck with 0.46.

PS2: I may screwed this by using tropical theme instead of grass one on 0.48... :(

PS3: Additional screenshots.

0.48.0
![2021-03-28_20-45-50](https://user-images.githubusercontent.com/20325180/112764116-7e1e0700-9007-11eb-9ba9-b316406612f7.png)

0.46.1
![2021-03-28_20-50-27](https://user-images.githubusercontent.com/20325180/112764128-8413e800-9007-11eb-9787-27892a4a229b.png)

**Comment by SJuliez** [comment]
Closing this as (I believe) this can be solved with the current client settings.
