### ISSUE TITLE
Make it easier for LAMs to turn searchlights on/off

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#2753]
Using 48.0 (and all previous versions), LAMs with added searchlights don't have the convenient "Searchlight on/off" button at the bottom of the screen during the movement phase, like Mech and vehicle units do.  You have to dig through one of the menus to find a command to do this.

Please add the "Searchlight on/off" button for LAM units.

**Comment by SJuliez** [comment]
I can't reproduce this on the most recent game version. In a game with a LAM in moonless night with the searchlight that every mek gets automatically the button was there. Please reopen if there is a specific condition where the button doesn't appear.
