### ISSUE TITLE
[0.48] Charge + DFA 'null target' then... issues.

### ISSUE THREAD

**Issue by IanBellomy** [MegaMek/megamek#2757]
### Environment

MM 0.48

Client A: 
macOS 10.15.7
Java 10.0.2

Client B: 
PC?... :/

### Description
Game 1:
I attempted to charge a unit.
Received an error about illegal/null target.
Charging unit returned to initial position, turn control shifted to networked opponent. 
On my next turn I attempted to charge again.
No trouble. 
On returning to my last turn to move, my last unit's moved was skipped and treated as if it hadn't moved. Fire phase then began.

Game 2:
Opponent attempted to DFA a unit.
Received an error about illegal/null target.
DFAing unit placed in adjacent hex like with normal DFA.
When physical attacks were resolved the DFA seemed to execute but with a very unexpected set of logged events. (Image attached)
Based on final positions and damage, it appears the DFA executed correctly though.

<img width="712" alt="dfa" src="https://user-images.githubusercontent.com/17239616/112933503-fb23ac00-90ed-11eb-8201-77498e548a61.png">
 
[megameklog.txt](https://github.com/MegaMek/megamek/files/6226140/megameklog.txt)

**Comment by sixlettervariables** [comment]
Do you have a save game or auto save for this? Unlikely to track this down easily without one.

**Comment by IanBellomy** [comment]
Doesn't look like it ( :/ ), though I'll ask the other player if they have one. 
Hopefully will have a chance to hunt for a repro this week regardless.

**Comment by Northman3050** [comment]
I get this every time I try to do a charge in 0.48.0

Just start a game.  Add another as LocalHost.  Select one mech for each side.  Move one.  Then use the other to charge and get the Null target /illegal charge notification.

[megameklog.txt](https://github.com/MegaMek/megamek/files/6620620/megameklog.txt)
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/6620621/autosave.sav.gz)

**Comment by HammerGS** [comment]
Casual Joker just had this with a Mech DFA'ing a VTOL that was killed earlier in the phase.

From the stream Sept 18th/2021 around 2 hours 15 min in.
[dfa_error.sav.gz](https://github.com/MegaMek/megamek/files/7190889/dfa_error.sav.gz)
.
