### ISSUE TITLE
Swarm and Legs attacks bug

### ISSUE THREAD

**Issue by Antoluu** [MegaMek/megamek#2758]
### Environment
What version of MegaMek does your issue apply to?
MegaMek 0.48.0.
What operating system are you using?
Windows.
What java version are you using?
1.8.0_251

### Description
Infantry swarm and leg attacks checks don't count target movement.
It was working in MegaMek 0.46.1.

**Comment by sixlettervariables** [comment]
Do you have a save game?

**Comment by Antoluu** [comment]
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/6233166/autosave.sav.gz)
