### ISSUE TITLE
Swarm attack vs VTOL

### ISSUE THREAD

**Issue by Antoluu** [MegaMek/megamek#2759]
### Environment
What version of MegaMek does your issue apply to?
MegaMek 0.48.0.
What operating system are you using?
Windows.
What java version are you using?
1.8.0_251

### Description
Infantry can do a swarm attack againts flying VTOL.

(Total Warfare p. 220) Prohibited Attacks: Aerospace units and VTOLs cannot be targets of swarm attacks unless they land.

**Comment by NickAragua** [comment]
Fixed with PR #2763
