### ISSUE TITLE
Indirect fire source not displayed during double blind play

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#276]
Several releases ago a change was made, and now, during the firing phase report, there is no line break or source information for indirect lrm fire. Damage will be displayed correctly, but it will be lumped with the prior units fire, which can be extremely confusing.

Before (not sure how many releases back) all indirect fire created a line break in the firing phase report with ????? attacked xyz unit. This was much better because it let you know you were under attack, and clearly delineated that the attack came from a separate source.

**Comment by arlith** [comment]
Do you have a specific change in mind?  I think you're just using different game rules.  With Double Blind, information a player doesn't know about is obscured with "?????" in reports. If you select the "No Double Blind Messages" option, then all of those reports with "?????" in them are hidden instead.  This generally works, but can occasionally lead to line break issues.

**Comment by VampireSeraphin** [comment]
Hmm, yes, we are using "No double blind messages."

Can you tell me what each of the things that option suppresses are? Depending on what else is in there, is might be worth making indirect fire an exemption to this rule.

**Comment by BLOODWOLF333** [comment]
Could this be related to #225  where there seems to be funky things going on with DB reports?

Weapons fire for Griffin GRF-1N (McCarron's Armoured Cavalry)
    LRM 10 at Hex: 3452 (Deliver minefield); needs 8, rolls 4 : _[should have a line break here]_Weapons fire for Awesome AWS-8Q (McCarron's Armoured Cavalry)
    PPC at Ostroc OSR-2C (Michi) (Reaper Company); needs 12, rolls 7 : misses

**Comment by arlith** [comment]
Yes, it's the same underlying problem.
