### ISSUE TITLE
Tripods BV wrong ?

### ISSUE THREAD

**Issue by tbkainer** [MegaMek/megamek#2761]
MegaMek 48.0 

Mech (Tripod) BV2 dont match with the masterunitlist... i know is realy rare mech typ.
Triskelion TRK-4V 
MUL = 2,837
meg 47 = 2972
meg 48 = 2702

the ""ares" var. have the same problems with the BV 
Ares ARS-V1A Hera 
MUL = 3,320
meg 48 = 2,944

maybe the masterunitlist is bugged ?

anyway stay healthy

**Comment by SJuliez** [comment]
On the Triskelion, Mordel and MM agree on a different value from the MUL. On the Ares types, Mordel doesn't have an entry, so unfortunately there isn't any calculation to compare to. I can't see anything obviously wrong, so I'm going to pronounce MM correct until someone can point out a definitive error.
