### ISSUE TITLE
Minimizing minimap results in empty summary screenshots

### ISSUE THREAD

**Issue by Cryosleeper** [MegaMek/megamek#2762]
### Environment
Standalone MM 0.48.0
Kubuntu 20.04.2
Java 11.0.10

### Description
When minimap is minimized, Save Game Summary Image Of Minimap option generates screenshots 14 px high if minimap was minimized with a green Minimize button at the bottom.
![round_1_14_Firing](https://user-images.githubusercontent.com/35873071/113221639-718dee80-9253-11eb-9f8d-9a47737732ea.png)

**Comment by SJuliez** [comment]
I'm taking a look at the minimap and can look into this.
