### ISSUE TITLE
[48.0] Incorrect Citation for "(Unofficial) Specify the number of predesignated artillery autohit hexes per map area" rule

### ISSUE THREAD

**Issue by Delusional-Dreamer** [MegaMek/megamek#2767]
The "(Unofficial) Specify the number of predesignated artillery autohit hexes per map area" rule cites page 180 of Total Warfare in its mouseover text as having information on artillery autohit hexes, but that information is actually on page 180 of Tactical Operations.

![Megamek citation](https://user-images.githubusercontent.com/81841613/113483355-9b6c2e80-9468-11eb-9395-1f437ec7bd91.png)

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/f6ce00c34398e7a750dacfd0060f4964ead8e705
