### ISSUE TITLE
Telling a unit to withdraw

### ISSUE THREAD

**Issue by Akjosch** [MegaMek/megamek#277]
In a big fight, some units have just outlived their usefulness - all weapons out of order, no ammo, vehicle crews and so on. It would be nice if we could just right-click on them and tell them to go home (towards some/any edge) via a menu, effectively handing them over to a simple AI. The same right-click menu could disable that setting again.

They should probably have a "fleeing" icon (something like a small hare?) near them, to make them visually distinctive.

**Comment by SJuliez** [comment]
Closing this as 
- this would be very complicated and probably error-prone to implement (
- I don't see a simple way to integrate this into initiative order without player interaction and/or frustration
