### ISSUE TITLE
Patchwork armor calculations not using TacOps : AUE

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#2771]
We seem to be doing Patchwork wrong. Per TacOps:AUE pg 189

_The designer of a unit must designate the armor type to be used in each hit location and, using the Fractional Armor Table
on page 376, compute the weight of the armor by multiplying its weight (in tons per point) by the number of points assigned to the location, rounding the final result up to the nearest half-ton._

There is a note in the code that we are using the 3.3 errata which was changed again.

![image](https://user-images.githubusercontent.com/13752452/113600708-a3110c00-95fd-11eb-99ab-5fdea7f0c8af.png)

The yellow is how Megamek seems to be doing it.

### Environment
What version of MegaMek does your issue apply to?  0.48.0
What operating system are you using?  Windows
What java version are you using? openJDK 11

### Files
[Aquagladius AQS-5 MAM.zip](https://github.com/MegaMek/megamek/files/6259350/Aquagladius.AQS-5.MAM.zip)

**Comment by neoancient** [comment]
We're rounding total armor for the unit rather than per location because it says to round the "final result."

**Comment by HammerGS** [comment]
I'm going to get Xotl and Jymset to confirm this again. The issues is coming from SSW vs MML and the AquaGladius.

I've sent them this thread - https://bg.battletech.com/forums/tactical-operations/answered-patchwork-armor-calculations-question/msg1568985/#msg1568985

**Comment by neoancient** [comment]
The Zeus X and X2 assume the rounding is done at the end. If rounded per location, they are overweight.

**Comment by HammerGS** [comment]
Confirmation we are right.

![2021-04-05 13 41 17](https://user-images.githubusercontent.com/13752452/113634829-b4bdd800-962c-11eb-98c6-0bec51ce470b.jpg)
