### ISSUE TITLE
Mechset Error Re: Marauder Red Hunter

### ISSUE THREAD

**Issue by Kojak3** [MegaMek/megamek#2772]
### Environment
MegaMek 48.0, Wndows, Java 11.0.10

### Description
The mechset.txt has:
exact "Marauder (Red Hunter 3146)" "mechs/Marauder_RH.png"
But there is no corresponding sprite. I have talked to Alex (Deadborder) and he says he submitted the sprite prior to the latest release.

### Files
Supplied via Deadborder, here's the sprite in question that should be in the data/images/units/mechs folder: 

![image](https://user-images.githubusercontent.com/48396020/113817430-2b40ff80-972b-11eb-8163-bf7ee553e3f2.png)

**Comment by HammerGS** [comment]
Fixed in last sprite update.
