### ISSUE TITLE
Omnimech Pods Incorrect Labels

### ISSUE THREAD

**Issue by XanKortal** [MegaMek/megamek#2801]
What version of MekLab does your issue apply to?  0.48.0 Stable
What operating system are you using?  Windows 10
What java version are you using?  1.8.0_271

### Description
Multiple omnimechs in the megameklab cache have improperly tagged omnipod/fixed equipment slots.

Mechs found so far:
Deimos H - Head AMS + AMS ammo tagged as Pod
Dragonfly (Viper) J, K, L, M, R, T - all equipment tagged Fixed
Gladiator (Executioner) J - all equipment tagged Fixed
Koshi (Mist Lynx) I, J, K, L, M, T - all equipment tagged Fixed. N tagged LRM's, LAMS, and TAG tagged as Fixed
Mad Cat (Timber Wolf) Bounty Hunter, Bounty Hunter 2 - not tagged as Omnimechs. U tagged Harjel I as Fixed
Puma (Adder) I, K, L, S, T - Flamer tagged as Pod
Shadow Cat D, I, M, T - all equipment tagged Fixed
Snow Fox (Omni) Prime, A, B - all equipment tagged Fixed
Stormcrow (Ryoken) J, K, P, T - all equipment tagged Fixed
Sun Spider Prime, A, B, C, D, Manul, Vanguard - all equipment tagged Fixed
Uller (Kit Fox) J, T, V - all equipment tagged Fixed
Vulture (Mad Dog) DD, I, T - all equipment tagged Fixed. U has Harjel I tagged as Fixed
Templar III TLR2-J 'Arthur' - not tagged as Omnimech
Carrion Crow Prime, A, B, C,D - all equipment tagged Fixed
Hierofalcon B, C, D - Partial Wing tagged as Pod
Sojourner B, C, D - Supercharger tagged as Pod
Blackjack OU - Harjel I tagged as Fixed
Templar TLR1-OU - Harjel I tagged as Fixed
Black Hawk (Nova) U - Harjel I tagged as Fixed
Daishi (Dire Wolf)  U - Harjel I tagged as Fixed
Dasher (Fire Moth) I, J, P, R, T - all equipment tagged Fixed
Osteon U - Harjel I tagged as Fixed
Pariah (Septicemia) U - Harjel I tagged as Fixed
Turkina U - Harjel I tagged as Fixed
War Crow Prime, A, B, C - all equipment tagged Fixed

(Note with the inclusion of Harjel in this - Harjel I from TO. 288 has no limitations on pod mounting, but Harjel II and Harjell III from IO. 88 do have limits where they need to be fixed mounted instead of pod mounted. The mechs included all have Harjel I, not Harjel II or III)

Example:
![image](https://user-images.githubusercontent.com/83326142/116343416-61195700-a7b2-11eb-9c8e-a6cf9c7c32d6.png)

**Comment by HammerGS** [comment]
Related to https://github.com/MegaMek/megamek/issues/2709

**Comment by HammerGS** [comment]
- [ ] Deimos H - Head AMS + AMS ammo tagged as Pod
- [ ] Dragonfly (Viper) J, K, L, M, R, T - all equipment tagged Fixed
- [ ] Gladiator (Executioner) J - all equipment tagged Fixed
- [ ] Koshi (Mist Lynx) I, J, K, L, M, T - all equipment tagged Fixed. N tagged LRM's, LAMS, and TAG tagged as Fixed
- [ ] Mad Cat (Timber Wolf) Bounty Hunter, Bounty Hunter 2 - not tagged as Omnimechs. U tagged Harjel I as Fixed
- [ ] Puma (Adder) I, K, L, S, T - Flamer tagged as Pod
- [ ] Shadow Cat D, I, M, T - all equipment tagged Fixed
- [ ] Snow Fox (Omni) Prime, A, B - all equipment tagged Fixed
- [ ] Stormcrow (Ryoken) J, K, P, T - all equipment tagged Fixed
- [ ] Sun Spider Prime, A, B, C, D, Manul, Vanguard - all equipment tagged Fixed
- [ ] Uller (Kit Fox) J, T, V - all equipment tagged Fixed
- [ ] Vulture (Mad Dog) DD, I, T - all equipment tagged Fixed. U has Harjel I tagged as Fixed
- [ ] Templar III TLR2-J 'Arthur' - not tagged as Omnimech
- [ ] Carrion Crow Prime, A, B, C,D - all equipment tagged Fixed
- [ ] Hierofalcon B, C, D - Partial Wing tagged as Pod
- [ ] Sojourner B, C, D - Supercharger tagged as Pod
- [ ] Blackjack OU - Harjel I tagged as Fixed
- [ ] Templar TLR1-OU - Harjel I tagged as Fixed
- [ ] Black Hawk (Nova) U - Harjel I tagged as Fixed
- [ ] Daishi (Dire Wolf) U - Harjel I tagged as Fixed
- [ ] Dasher (Fire Moth) I, J, P, R, T - all equipment tagged Fixed
- [ ] Osteon U - Harjel I tagged as Fixed
- [ ] Pariah (Septicemia) U - Harjel I tagged as Fixed
- [ ] Turkina U - Harjel I tagged as Fixed
- [ ] War Crow Prime, A, B, C - all equipment tagged Fixed
- [ ]
