### ISSUE TITLE
java.lang.NullPointerException on start of autosave

### ISSUE THREAD

**Issue by MarcJC** [MegaMek/megamek#281]
Attached log and save game.

Game hung at beginning of turn.  Loaded autosave, hang at beginning of turn.
Also noted an issue where one of my mech's could not target some of the enemy mech's
Could not even click on the errored mech with a left of right click to try to target it.
That error is unlikely to be able to be reproduced, but I thought I would mention it if anyone else sees it. 

Player name for game is Marc

Let me know if I can give you any other info to help find a fix.

[megameklog.txt](https://github.com/MegaMek/megamek/files/379335/megameklog.txt)

[Marc.sav.gz](https://github.com/MegaMek/megamek/files/379336/Marc.sav.gz)

**Comment by HammerGS** [comment]
Your running an older version of MegaMek (41.16) and going from memory I think that bug was fixed.

I don't have access to MegaMek right now...could you try it with the most current version here:

https://github.com/MegaMek/megamek/releases/tag/v0.41.20

Thanks

**Comment by MarcJC** [comment]
Loaded the save on the new version (I don't update as often as I should)
No npe so that is good.
On the other hand the log shows lots of bad skin and array out of bounds errors.
A lot of the mechs are not visually there just a regular hex but the C3 lines are connected and the name plate is on the hex.

Some of the mechs are customs so I can understand them being messed up but I don't see the issue on the mechs that came with the files.

I'll see how it goes from there (gonna be a pain figuring out facings)

As an old coder I do have to ask if there is any info on the bug that was fixed.  Those things just keep you up at night :)

**Comment by arlith** [comment]
The canCompleteNodePath bug was reported as #165. If you view that ticket, you can see the notes and there's also a link to the commit that fixed the issue if you'd like to see how the code changed.

**Comment by arlith** [comment]
As for missing icons, if you have custom units that use custom icons, then you must have edited the mechset.txt (likely the local one, there are three: a default one and a local one for client and server).  You should edit the local ones, as those are designed to be replaced.  If you edit the mechset.txt, then it's harder to merge your changes with new releases.

**Comment by arlith** [comment]
You can keep discussing in this ticket, but since the issue has already been solved, I'm going to close this ticket.

**Comment by MarcJC** [comment]
Thank you for all the help on the ticket.
I will check out the other ticket for understanding.

I don't have any art skills so I have done nothing with the mechset.txt file just using the default mech icons.  Some of the default mech icons show up some don't.  And some of the base mechs icons show up and some don't.  So I can rule out it being just a custom mech issue.  
However until I can reproduce the error I am willing to chalk it up to a issue transferring a save game between versions.

If it comes up again I will open up another ticket.

Thanks again for all the help

**Comment by arlith** [comment]
There has been an on-going bug related to loading images in the last two releases (41.20 and 41.19).  This has been repoorted as an NPE in BoardView1.drawHex, but I think it also affects image icons and camos (there's another bug about camos not displaying).  I'm guessing your issue is related to that.

**Comment by MarcJC** [comment]
Interesting, I do notice a bunch of NPE exceptions in the log.  However it is able to be worked around so that doesn't worry me so much.  I do see that it is interesting that in the game I have two copies on a number of mechs on the field.  One is drawn and one is blank.  The logic going on messes with my head, but I need to be able to reproduce it in a clean game to get a better handle on it.

Some other notes to watch for.

The string the Blue Shield is saying less then when it means greater than (not sure on equal here)
Blue Ranger BLR-001 (Marc) needs to roll less than 4 to avoid Blue Shield Failure, rolls 8: no effect

Obviously an 8 is not less than a 4 but the shield did not fail.
I don't think a simple text fix needs its own bug report but I can open one if you want.

More alarming is one of my customs started taking half damage from all weapons for no reason I can understand.  As with most of the others I have two versions of the custom on the board.  One of them just started taking half damage, the other was not effected.  I do have some customs in play with blue shield and reflective armor, but the effected mech does not have any of these techs.  Again I want to be able to reproduce this error in a clean game before opening a bug ticket on it, but if someone else mentions it you have another case of it.  I hope it doesn't reappear I think it will be a bitch to track down if it comes to that.

Thanks for all the help
