### ISSUE TITLE
Data: Wolverine WVR-6D Missing Quirks

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#2810]
MM 0.48.0 Standalone

It appears that the Wolverine WVR-6D has no quirks, while the rest of the WVR-6* variant list has the Wolverine's traditional extensive shopping list of quirks. Is this intentional, or an error?

**Comment by HammerGS** [comment]
Looks like an oversight.

**Comment by SimonLandmine** [comment]
Sorry!

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/f573cf2bd044ad86b9527d2af57646721bb1c946
