### ISSUE TITLE
0.48.0 - Infantry swarm attack situation modifiers not being applied

### ISSUE THREAD

**Issue by orcmaul** [MegaMek/megamek#2813]
### Environment
Megamek 0.48.0 on Windows 10 [Version 10.0.19042.928] with openjdk version "1.8.0_282"

### Description
Situation modifiers outlined in Swarm Attack Modifiers Table on pg 221 of Total Warfare (5th printing) are not being applied to infantry swarm attacks.  

### Files
[swarm.sav.gz](https://github.com/MegaMek/megamek/files/6410319/swarm.sav.gz)
![swarm mods missing 1](https://user-images.githubusercontent.com/75004088/116795321-f5244080-aa88-11eb-892a-62aefdfce170.PNG)
![swarm attack modifiers table TW_5thprinting p221](https://user-images.githubusercontent.com/75004088/116795348-2a309300-aa89-11eb-9eab-a06477bf44b2.PNG)

**Comment by HammerGS** [comment]
Adding to this BattleArmor with Vibro-Claws aren't adding the bonus damage.
