### ISSUE TITLE
Lobby feedback - the proportion is too weird.

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megamek#2815]
### Environment
Ver 0.49.0
Windows 10 - 1600x900 Resolution
OpenJDK build 11.0.10+9

### Description
The new lobby seems good... except for proportion. 

By the default settings, now it looks like;

![01](https://user-images.githubusercontent.com/47907439/116807583-efa12600-ab6e-11eb-924f-7c15297c54ec.jpg)
![02](https://user-images.githubusercontent.com/47907439/116807587-f334ad00-ab6e-11eb-9676-027bea5621d3.jpg)

In comparison, this is the 0.48 or before;
![08](https://user-images.githubusercontent.com/47907439/116807776-f8dec280-ab6f-11eb-8275-c4f41c56c339.jpg)

Yes, you may change the GUI scale but still it's weird.
![03](https://user-images.githubusercontent.com/47907439/116808084-f1201d80-ab71-11eb-8bd3-6d2f4dddc750.jpg)

And the words on the buttons are too thin and small when I reduce the GUI.

The another problem is unit load from cache.
![04](https://user-images.githubusercontent.com/47907439/116808124-2462ac80-ab72-11eb-9c6e-07a3f8d0979a.jpg)
![05](https://user-images.githubusercontent.com/47907439/116808125-2593d980-ab72-11eb-8ba0-f0bd645c689c.jpg)
![06](https://user-images.githubusercontent.com/47907439/116808126-26c50680-ab72-11eb-8a79-cc8ae2ccdd30.jpg)

It is only useful with 70% minimum GUI, and still bigger. Also, although an arrow for change the width is shown on the middle of the line, it does nothing - I can't drag it to left nor right.

So, can't we use it with smaller window and still make it functional? The UI is always static and cannot be adjusted but  is too large to actually use. At least isn't it possible to make the size adjustable, not fixed?

**Comment by SJuliez** [comment]
Concerning the lobby: I don't know what you mean by weird. The shots of 0.48 and 0.49 look almost exactly the same to me. Also I can't see which text would be unreadable. Please be more specific.

Concerning the Unit Selection window: There have been no changes to this. It does not react to gui scale changes at all. So any changes between versions must come from somewhere else.

Are you having Windows scale your UI as well? And maybe freshly installed Java 11? I think I remember reading that Java 11 reacts differently to Windows UI scaling than older versions of Java. This may interfere. (Only a guess)

**Comment by binaryspica** [comment]
'Change the size of text, apps' is 100% now. I didn't changed this.

![screen01](https://user-images.githubusercontent.com/47907439/116817037-91d90200-ab9f-11eb-9c27-fabfd0c89548.png)

This is the comparison between 0.48.0. and 0. 49.0. With 100% GUI. As you see, the UI become very large and can't have much space to see below.

![screen02](https://user-images.githubusercontent.com/47907439/116817168-1297fe00-aba0-11eb-9a5e-f125650ec971.png)

This is 70% GUI on 0.49.0. The scale is largely same but the words on the button are too small and make it harder to read.

It seems that the unit selection may my mistake, for it was occur on the default setting(because it is too small) and when I stretch it I can't make it smaller. Still, it is somewhat bigger than 0.48.0.

**Comment by SJuliez** [comment]
OK the player list gets a bit small. But now that I look at your screenshots again I notice that they're like 900x600 pixels. That is a size where it's really difficult to display the MM lobby. I had not planned for such tiny windows. The 0.48 one did that a little better because a) it used a pretty small font making it difficult to read on resolutions upwards of HD (except for the buttons) and b) it displayed the players in only one line. The new lobby takes a bit more space but you can scale it down. I'd expect that if you make MM fullscreen you can scale it up to 80 or 90 % and it would fit ok.

**Comment by Tecmes** [comment]
It's surprising that the OP has issue with a 1600 screen. I'm using a 1024-wide screen and though it is much more squished than 0.48, it's still useable, and the new smarter info display makes it work.

**Comment by SJuliez** [comment]
Closing this issue as there's no error here.

**Comment by binaryspica** [comment]
Then, if I need to request for the make it more suit for the smaller window, must I put the other thread?
