### ISSUE TITLE
Placeholder image on killed Condor

### ISSUE THREAD

**Issue by ProjectileWaterfowl** [MegaMek/megamek#2818]
MekHQ version 0.49.0
Windows
JDK 11

![Capture](https://user-images.githubusercontent.com/8988919/116815683-a92ad780-ab2c-11eb-932a-8513cc3c50f1.PNG)
[bug.sav.gz](https://github.com/MegaMek/mekhq/files/6411500/bug.sav.gz)

Killed a Condor hover tank, got this. Looks like something that would happen if the image was missing, but I checked the wrecks folder and Condor.png looks just fine.

**Comment by sldfgunslinger2766** [comment]
I experienced this behavior as well.
v.0.49.0 Dev
Java vendor AdoptOpenJDK
Java version 11.0.10
Platform Windows 10 10.0 (amd64)
Total memory available to MegaMek: 1,048,576 kB

**Comment by Tecmes** [comment]
0.49.0 and openjdk 11.
Also experienced this twice. Was a howitzer and a guardian fighter, on pretty big scenarios. One was allied force, one was mine. one was killed (I think) during the physical attack phase, the other (i think) during movement. Couldn't find a pattern.
