### ISSUE TITLE
[48 and 49] Turret deployement hangs

### ISSUE THREAD

**Issue by Tecmes** [MegaMek/megamek#2824]
I've had this issue repeatedly since 0.48 at least, and still in 0.49.0.
In AtB scenarios featuring local defenses with turrets, when deploying the turrets, the game hangs (though the interface responds). I've tried delaying their deployement to before turn 1, same thing. I'd like to say it happens on large map, but turret pretty much happen only on large map, so it's hard to say. I've tried waiting a LONG time, but no cigar.

Savegame provided. IT was saved as the game was hung.
[stuckgame_turret_deploy.sav.gz](https://github.com/MegaMek/megamek/files/6417737/stuckgame_turret_deploy.sav.gz)

**Comment by NickAragua** [comment]
Going to need to see a log for this next time it happens. I can't reproduce it in 49.0 with the save game provided - on my end, the bot deletes the turret as there is no place for it to deploy, then moves on.

**Comment by Tecmes** [comment]
It doesn' tseem to be linked to the lack of deploy spaces as it hangs on base maps with buildings as well. HOWEVER I found out that disabling "simultaneous deploy" removed that issue.

**Comment by NickAragua** [comment]
That's generally a good practice as the bot does not support simultaneous anything.
