### ISSUE TITLE
49.0 PlayerSettings must be read-only in game

### ISSUE THREAD

**Issue by SJuliez** [MegaMek/megamek#2833]
The new PlayerSettingsDialog should turn read-only when in the game.

**Comment by NickAragua** [comment]
I disagree - I've actually seen people use this to simulate time-limited initiative bonuses, such as those described in the various scenario books.

**Comment by gsparks3** [comment]
I can confirm that at least one Chaos Campaign scenario we've played recently had an initiative bonus that could activate mid-battle, contingent on certain things happening.

**Comment by HammerGS** [comment]
Yeah, I agree with Nick here. I've used it games and I know recently it came up in a conversation in Discord and was recommended to them.

One day we'll have really force abilities :)

**Comment by SJuliez** [comment]
OK. I assume there's no sense having the number of minefields, the deployment position and the random skills roll-method available though, right?

**Comment by NickAragua** [comment]
Probably not minefields. As for deployment, I can easily see a scenario where a player may want to reinforce via MUL and have it be limited to a particular deployment zone, or reinforce via RAT and have the random skill roll method be something different.

**Comment by SJuliez** [comment]
OK... gonna close this again. Thought this was something I should quickly adjust but obviously no change is really necessary.
