### ISSUE TITLE
48.0/49.0 AR10 Capital Missile launchers cannot select ammo type

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#2841]
AR10 Capital Missile Launchers used on the space map cannot select from any ammo type other than the first. This can be easily reproduced: choose a unit with AR10 launchers and multiple ammo types by default (I use the Mule 'Pocket WarShip' variant) and start a battle on the space map. The only ammunition type available to select will be the first type (in this case AR10 Killer Whale ammo), as shown below. 

![image](https://user-images.githubusercontent.com/59574316/117394666-89950580-aec4-11eb-896d-da8a6a04130a.png)

However, the ammunition is still present, it simply cannot be selected to fire. This can easily be confirmed on the Systems tab, as shown below.

![image](https://user-images.githubusercontent.com/59574316/117394743-b21cff80-aec4-11eb-9be3-7a59523b5e1c.png)

**Comment by HammerGS** [comment]
Any chance this could get a look? Have a few players reporting its impacting games
