### ISSUE TITLE
48.0 Thin snow increasing ground MP cost for Battle Armor

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#2842]
Per page 35 of my old version of TacOps, Thin Snow increases MP cost by +1 per hex for wheeled vehicles and conventional infantry, but no other types of units. I do not have access to the newer TO, but there is no errata listed for this particular piece of information. However, as of v48.0, Megamek has Thin Snow increasing the Ground MP cost for Battle Armor, implying the cost increase is applied for all infantry rather than only conventional infantry. Image and save provided below for ease of reproduction. Save also includes a CI unit, which correctly has its MP cost increased by the Thin Snow.

Note that this MP cost increase is separate from the unit MP decrease applied to infantry ground movement by extreme cold (in the save provided, the temperature is normal, although the map was defined as having Thin Snow in various hexes). 

![image](https://user-images.githubusercontent.com/59574316/117395761-99154e00-aec6-11eb-8e32-0a8f798bc4f0.png)
[thinSnowInfantry.sav.gz](https://github.com/MegaMek/megamek/files/6438918/thinSnowInfantry.sav.gz)

**Comment by pheonixstorm** [comment]
Rules reference TO:AR p50

Code should be easy enough to change.

**Comment by pheonixstorm** [comment]
This has a fix, PR #4002 

Hopefully it can get reviewed and merged before the next release.
