### ISSUE TITLE
[49.1 may 5] Right-click issue is gone... and new twist issue

### ISSUE THREAD

**Issue by Tecmes** [MegaMek/megamek#2844]
The right-click-to-select issue is gone, but now when clicking on Twist, you cannot click to twist (neither the left nor right buttons).
You can still shift-click to do so (or use the context menu), but for all purposes the Twist button doesn't work anymore.

**Comment by Tecmes** [comment]
Also (seemingly since 49.1 build 390) the right-click selection issue is back, but specifically for Physical Attacks.

**Comment by HoneySkull** [comment]
I checked this in the latest dev build as of 5/13 and torso twisting seems to be working exactly as 0.48.  Is there a use-case that is broken?  I.e. when you click on the twist button, you then click on the left or right arc of the selected mek.

**Comment by Tecmes** [comment]
No, as of 390 the twist issue and "can't left-click to attack" issue is resolved, but a new issue popped out: you can't left-click on physical attack targets; you have to right-click. It's exactly the same issue as before, but specifically for phys atk, and has nothing to do with twist anymore.

**Comment by Tecmes** [comment]
Fixed in release 398.
