### ISSUE TITLE
[0.49] Text on bot behaviour control panel is too small

### ISSUE THREAD

**Issue by Tamren** [MegaMek/megamek#2853]
When I go to add a bot to a megamek match it opens a window that lets you set the behaviour using sliders. The text for the sliders is too small and the letters become almost unreadable (left side of the pic). I'm using the 0.49 development snapshot of mekhq and the recommended adoptopen JDK 11 java distro. I remember having issues with garbled text in meklab (the right side of the pic) and I solved them by updating to the adoptopen JDK 16 release. However the new 0.49 release doesn't recognize JDK 16 and the issues returned when I installed 11 instead.

Since we'll be stuck with JDK 11 for the foreseeable future you might be able to fix the problem by using a different font. Only certain bits have problems, most of the text is fine.

![megamek bot text problem](https://user-images.githubusercontent.com/25917471/117918727-76a57b00-b2a0-11eb-891f-d35b21f5f504.png)

**Comment by HammerGS** [comment]
Some players have had success trying these. 
https://github.com/MegaMek/megamek/wiki/Known-Issues-and-Workarounds
