### ISSUE TITLE
[49.1+390] Invalid design stops loading but doesn't prevent game start

### ISSUE THREAD

**Issue by Tecmes** [MegaMek/megamek#2854]
[Open JDK 11.0.11+9, Win10/64. Win reports more than 50% memory free.]

When starting a game from MHQ, it may happen that RAT-generated units are illegal, for some reason. In that case it interrupts loading if you've not allowed illegal designs in the options.
The problem is, it still allows you to start the game, meaning you might be missing part or all of a unit group and not realize it (the only feedback is a warning in the bottom pane). In the example provided, the whole OpFor is missing, so that's obvious, but it might be much less so.

I'm attaching everything.
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/6466365/mekhqlog.txt)
[megameklog.txt](https://github.com/MegaMek/megamek/files/6466366/megameklog.txt)

[MHQ_missing_units.cpnx.gz](https://github.com/MegaMek/megamek/files/6466367/MHQ_missing_units.cpnx.gz)
[MM_Missing_units.sav.gz](https://github.com/MegaMek/megamek/files/6466368/MM_Missing_units.sav.gz)

**Comment by NickAragua** [comment]
Realistically speaking, you can address this by enabling the "allow invalid units" setting in MegaMek options.
