### ISSUE TITLE
Board Editor Level Up/Dn and left-click drag broken.

### ISSUE THREAD

**Issue by HoneySkull** [MegaMek/megamek#2856]
### Environment
What version of MegaMek does your issue apply to?  0.49.1.SNAPSHOT
What operating system are you using?  Windows
What java version are you using?  OpenJDK11

### Description
Ctrl and Alt clicking on the MegaMek board editor no longer work due to KeyEvents being replaced by Java 11 modifiers.  As a result you can no longer increase and decrease hex levels by Ctrl-clicking or Alt-click with the elevation button selected.

This is related to #2800 

I have a fix I'm preparing a PR.  #2857

**Comment by HoneySkull** [comment]
It looks like this issue can be closed.

**Comment by Windchild292** [comment]
Missed that, closing
