### ISSUE TITLE
[49.1+350] Armour tooltip is wrong!

### ISSUE THREAD

**Issue by Tecmes** [MegaMek/megamek#2863]
I've noticed this by accident. In one unit the armour tooltip shows an intact CT and busted LL. But the unit details show busted CT as well!

![Tooltip_armor_wrong](https://user-images.githubusercontent.com/80174634/118375096-8c12f180-b58d-11eb-82f8-f1b50db24257.png)

**Comment by SJuliez** [comment]
Do you have a savegame?

**Comment by SJuliez** [comment]
Ah wait no I should be good without.
