### ISSUE TITLE
[Princess][49.0] Bot allies not aware of mines

### ISSUE THREAD

**Issue by Tecmes** [MegaMek/megamek#2865]
It seems quite clear that bot allies are not aware of mines you deploy, of if they are, the pathfinding penalty for them is way too low. 
With the much more widespread use of mines due to StratCon, it would be great if your allies would stop blowin themselves up...

Also, there is currently no way to NOT deploy mines if you have them. Because StratCon gives you free mines in some circumstances, and the aforementionned issue, it would be cool to be able to just hit Done before deploying all mines.

**Comment by NickAragua** [comment]
First crack at fix with #2898
