### ISSUE TITLE
Mounting infantry rule is not as per TW

### ISSUE THREAD

**Issue by Tecmes** [MegaMek/megamek#2870]
[49.0, but that's an old issue I guess]

TW says (223-4):

> To mount a carrying unit during a turn, an infantry unit must start its Ground Movement Phase in the same hex as the carrier. The infantry unit may mount only at the end of the carrier’s movement.

So this implies both must start the Turn (and hence phase) in the same hex, and neither can move at all during that turn.

But MM does it very differently: inf can move into a vee hex, then the vee can still load it, and at the *start* of its movement, and then it can even move!

(Honestly I think inf needs all the help they can get, but...)

**Comment by gsparks3** [comment]
This is actually subject to a further recent update - see [rules question thread](https://bg.battletech.com/forums/total-warfare/mounting-infantry-in-a-carrier/).

**Comment by Tecmes** [comment]
Ah yes, my description is not quite exact. It's indeed:
- Vee moves into inf hex.
- Inf uses all its movement to board (and hence it cannot have moved into the vee hex that turn).

And, even if the vee starts in the inf hex, it cannot move afterwards.

But so MM is still wrong there (though I prefer the way MM does it...) and as you point out it should be an infantry action, not a vee action. Annoying...

**Comment by HammerGS** [comment]
To further clarify. The new errata and process should be:

_"To mount a carrying unit during a turn, an infantry unit must start its Ground Movement Phase in the same hex as the carrier._

Change to:

_To mount a carrying unit during a turn, an infantry unit must spend all its MP to enter a carrier in its hex."_

So the carrier can move first, and an infantry can mount if the infantry is in the hex with the carrier when the infantry begins it's movement.

See here as well - https://bg.battletech.com/forums/total-warfare/rules-clarification-mounting-infantry/

**Comment by NickAragua** [comment]
This was addressed with PR #3358; the transport unit is the one that carries out the loading action and no longer has to do so at the beginning of its movement - but the act of loading does end its movement. Having the loading action be initiated by the infantry is too much of a change to make, but this is effectively the same.
