### ISSUE TITLE
[49.1] Cannot set strategic targets in the lobby

### ISSUE THREAD

**Issue by Tecmes** [MegaMek/megamek#2878]
In the lobby, if you edit a bot's settings and add a strategic unit target, once you click "Okay", instead of popping the "save strategic targets" dialog, it does nothing and you can't close the pane without removing the strat target.
This wasn't there in nightly 398.

**Comment by Windchild292** [comment]
Can you please post logs with your bug reports? That significantly simplifies what we need to do

**Comment by Tecmes** [comment]
I'll try to put a log but in this case I thought the issue wouldn't appear there. I will add one as soon as able.
(Also I don't think I can "upgrade" to the stable as the 49.1 DS release is the latest one, isn't it?).

**Comment by Windchild292** [comment]
Apologies, meant dev version... swapped the names between chats.

**Comment by Tecmes** [comment]
Here's a log, at the moment I clicked on "Okay" (for no effect).
[megameklog.txt](https://github.com/MegaMek/megamek/files/6535415/megameklog.txt)

**Comment by Tecmes** [comment]
Sorry I didn't test properly. The issue is much more severe: if you change anything in the bot settings, like the bot behaviour setting, you can't Okay the window. So it's not related to the strategic tareget confirmation dialog.

This is quite crippling as many StratCon scn cannot be played without setting custom bot options and targets.
