### ISSUE TITLE
Reminder: Check if Quicksand Rules are Coded?

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#288]
http://megamek.info/forums/index.php?topic=2446.msg16527;boardseen#new

Page 51 of TO:
Quicksand: A swamp hex can also unexpectedly turn into quicksand; it remains quicksand for the rest of the scenario. Anytime a unit (not including DropShips) enters a swamp hex and becomes stuck, roll 2D6. On a result of 12, the swamp hex has become a quicksand hex. If a unit is in a hex that turns to quicksand, or enters a quicksand hex, it automatically gets stuck. During every End Phase after the turn in which the swamp hex becomes a quicksand hex, the unit will sink 1 level; apply a +3 modifi er to the Piloting Skill Roll to get unstuck from a quicksand hex, as well as a cumulative +3 modifi er for each level under the surface. As soon as the surface of the quicksand hex is higher than the unit in question, the unit is destroyed.

**Comment by beerockxs** [comment]
QuickSandProcessor.java and Server#doSinkEntity say that it is coded. I didn't check if it works correctly, though.

**Comment by BLOODWOLF333** [comment]
(For my own personal reference) Does anyone know before I ask xotl, does this mean when a mech sinks 2 levels it is destroyed with a mech being two levels high.  Or on three its destroyed?

**Comment by BLOODWOLF333** [comment]
Closing, Sanders tested it and it works.

**Comment by pheonixstorm** [comment]
@BLOODWOLF333 As I read it a mech should be destroyed at lvl 3, infantry at lvl 2 which means MM may not be processing a units death correctly. You may want to pester xotl anyway to check if that is the correct reading as that is how the example makes it sound as well.

**Comment by BLOODWOLF333** [comment]
http://bg.battletech.com/forums/index.php?topic=53805.0

**Comment by pheonixstorm** [comment]
You probably should have mentioned a page number for reference. For the example given in the book at any rate.

**Comment by HammerGS** [comment]
We have an official answer unit destroyed at level 3.  But is it salvageable would be the next question.  

Having done work in the oil and gas industry around quicksand and muskeg my vote is gone for good.

**Comment by BLOODWOLF333** [comment]
I second that vote, destroyed at 3 and then just keeps sinking for the rest of the game so, toast.

**Comment by arlith** [comment]
Clearly @HammerGS preferred Luke to remain on Degobah...

**Comment by HammerGS** [comment]
@arlith If he finished his training......or not tried a non-ILS landing when he needed ILS things might have been different :)

**Comment by VampireSeraphin** [comment]
Objection! Wesley survived the Fire Swamps.

**Comment by pheonixstorm** [comment]
Ruling in, depth 3 for mechs depth 2 for other units (infantry, tanks, etc)
http://bg.battletech.com/forums/index.php?topic=53805.0

**Comment by HammerGS** [comment]
@pheonixstorm Did you read up the thread I kinda said that 3 hours ago.

**Comment by pheonixstorm** [comment]
Doh! didn't read up far enough apparently :rewind:
