### ISSUE TITLE
Ko'd unconscious mech uses searchlight

### ISSUE THREAD

**Issue by AQGadget** [MegaMek/megamek#2888]
A KO'd mech with an unconscious pilot is using its searchlight in the shooting phase

### Environment
MekHQ V0.49.1
Windows
Latest Java version 16, downloaded 5.27.21

### Description
An unconscious pilot in the Locust is still using his searchlight

### Files
The Outworlds Outriders
![KO searchlight](https://user-images.githubusercontent.com/17732457/120016954-3f7add80-bfb3-11eb-8d00-872e8fd91804.png)
[KOsearchlight.sav.gz](https://github.com/MegaMek/megamek/files/6562263/KOsearchlight.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/6562266/megameklog.txt)

**Comment by SuperStucco** [comment]
Is this a Princess/bot player?

**Comment by NickAragua** [comment]
Apparently, there has been some errata on this subject. This is terrible because it means we'll have to keep searchlight state around in case the mechwarrior gets KO'd. Oh well.

https://bg.battletech.com/forums/tactical-operations/how-does-consciousness-affect-searchlights/msg1729333/#new

**Comment by AQGadget** [comment]
It was a Princess bot populated by mekhq

**Comment by SuperStucco** [comment]
> It was a Princess bot populated by mekhq

I've seen Princess do a few questionable things with searchlights.  It used to illuminate targets using searchlights on hidden units (now fixed).  I still see it sometimes using the searchlight outside of the front torso arc, not backwards or anything, just a hex or two outside of where it should be.  It's not a common situation that I can replicate easily (observationally only) so I've held off putting in a report for that.
