### ISSUE TITLE
Jumped vehicle and Shaky Stick on non-Aerospace units have no to-hit modifiers for this.

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megamek#2918]
### Environment
Ver 0.49.1

### Description
As title says. When you check the to-hit modifier on the reports, those modifiers are not applied at all on the attacks against those units;
- Jumped modifier on the units using Vehicular Jump Jets.
- Non-Aerospace airborne units(VTOL, WiGE and VTOL Infantry/Battle Armor) with **Shaky Stick** Special Pilot Advantage(79, CO), when the enemy unit is ground unit so it must be eligible for those SPA.

Also, it seems that Battle Armors are not able to have Ghost Target modifier even if they succeeded the roll. You know, Battle Armors are able to roll for the ghost target if they possess an ECM Suite. I have checked some to-hit modifiers against the battle armor that succeeded Ghost Target rolls but none of these rolls have Ghost Target modifier.

**Comment by NickAragua** [comment]
Shaky Stick does not apply to units with jump jets. Ghost Targets is not implemented in MegaMek according to the latest rules, so there's not really any point in fixing any discrepancies in it, since it'll need to be re-written anyway. Will be changing Shaky Stick to apply to units with VTOL/WIGE movement above ground level.

**Comment by binaryspica** [comment]
> Shaky Stick does not apply to units with jump jets. Ghost Targets is not implemented in MegaMek according to the latest rules, so there's not really any point in fixing any discrepancies in it, since it'll need to be re-written anyway. Will be changing Shaky Stick to apply to units with VTOL/WIGE movement above ground level.

Yes Shaky Stick does not apply to units with jump jets, but that's not the point. The point is, the combat vehicle jumped by Vehicular Jump Jets has no modifier for jump at all, and it's separate thing with Shaky Stick&airborne unit. Perhaps it's better to make a separated thread?

**Comment by NickAragua** [comment]
Yes, I think so.

**Comment by binaryspica** [comment]
Sorry for confusion. I'll open a new thread for this.
