### ISSUE TITLE
0.48.0 | Bot-Only match between BA and ProtoMeks may cause crippled ProtoMeks to cause AI to Break. 

### ISSUE THREAD

**Issue by dmitbor** [MegaMek/megamek#2926]
### Environment
MegaMek 0.48.0 Standalone Combat Sim
Windows 10
Java 1.8.0_241

### Description
Attempted to use 2 Princess Bots to attempt Elemental VS ProtoMek battle. Attempted situation twice, each time it ended up the same way: 1 Remaining Elemental Unit without direct line of fire against remaining, crippled ProtoMek. It appears that Elementals do not attempt to pursue crippled unit, while crippled ProtoMek is unable to leave the battlefield due to terrain or destroyed legs. This causes endless loop of turns ending, which override attempts to leave the game through UI, Alt+F4, or through closing the window - only remaining way is to use Task Manager to kill the process.

### Files
Autosave was corrupted due to requiring manual Task Manager use to stop the process.
[megameklog.txt](https://github.com/MegaMek/megamek/files/6625329/megameklog.txt)
[gamelog.html.txt](https://github.com/MegaMek/megamek/files/6625343/gamelog.html.txt)

HTML extension renamed to txt due to issues encountered by GitHub.

**Comment by Windchild292** [comment]
Duplicates #2768
