### ISSUE TITLE
Game freezes on "Select Mech" screen after picking up a unit on Java 9-ea

### ISSUE THREAD

**Issue by MGM175** [MegaMek/megamek#294]
After managing to successfully connect to the dedicated server, I've wanted to pick up some units.
And then: Issue #284 (ok, something is wrong), but after clicking "Select", the whole game freezes, and megamek log gets flooded with errors (IllegalAccess-like) (here: [megameklog.txt](https://github.com/MegaMek/megamek/files/391320/megameklog.txt) ).

And to be honest, here is the data from About screen:

`MegaMek version 0.41.20
Timestamp Tue Jun 28 04:29:47 CEST 2016
Java Vendor Azul Systems, Inc.
Java Version 9-ea'

I seriously think to downgrade java 'till Java 9 will be stable enough to use (and 'till Launch4J will deal with JEP 223)

`

**Comment by MGM175** [comment]
Forgot to tell:

Azul Zulu is a commercialized version of OpenJDK, I'll download Oracle Java 9-ea if needed. If this will still show up; I'll downgrade then.

**Comment by arlith** [comment]
Yea, I think that's the problem here.  It's complaining about not having access to sun.awt.ToolkitImage.

**Comment by MGM175** [comment]
In the fact, that I'm using commercialized OpenJDK? I'll check tomorrow if the problem will persist.

**Comment by arlith** [comment]
Any luck with another JDK?

**Comment by MGM175** [comment]
So far on Azul Zulu 1.8, OpenJDK 1.8 and Oracle Java 1.8 everything work in order, but I couldn't test Java  1.9 due to "Couldn't find java.dll" error.

**Comment by arlith** [comment]
If this is working fine for you on Java 1.8, I'm going to close this issue.  If there are problems with Java 1.9, we'll address them when we look into migrating.  At this point, Java 1.9 support hasn't really been considered.
