### ISSUE TITLE
cannot deploy units

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/megamek#2940]
from the discord.  get the cannot deploy unit message when trying to deploy in a new battle (from strat con) 49.1

[glitch.zip](https://github.com/MegaMek/megamek/files/6640758/glitch.zip)

**Comment by Windchild292** [comment]
https://cdn.discordapp.com/attachments/458706493659807801/852997437572907068/unknown.png

**Comment by NickAragua** [comment]
It's probably hidden. But my recommendation is to start the battle again, turn on the 'hidden units' rules and make sure you deploy your units as 'not hidden'.

**Comment by bczretribution** [comment]
that was the issue, 3 of the units were autodeploying as hidden.  why would they default to that?

**Comment by NickAragua** [comment]
It's a known bug that's been fixed since 49.1 in the nightly builds.

**Comment by Windchild292** [comment]
Closing as already fixed.
