### ISSUE TITLE
Can't change Killer Whale or White Shark ammo to nukes in unit config 0.49.1

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#2943]
There are no tech limits set, all nuke options are enabled.  But for some reason I can't change the Killer Whale or White Shark missiles to their respective nuclear-tipped variants.

[megameklog.txt](https://github.com/MegaMek/megamek/files/6641503/megameklog.txt)
[Aegis Heavy Cruiser (2600 Revised).zip](https://github.com/MegaMek/megamek/files/6641505/Aegis.Heavy.Cruiser.2600.Revised.zip)

**Comment by repligator** [comment]
Under 50.01 snapshot, both flavors of nuclear warheads can now be loaded onto warships. Closing as resolved.
