### ISSUE TITLE
How should roads interact with other terrain?

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#295]
Tested this out to figure out how the drawing order should be with roads and other terrain occupying the same hex.  Rubble and road still require a PSR when moving through but only costs 1 MP in MM 0.41.20.  Swamp and sand all only cost 1 MP with roads but, swamp will require a PSR with sand also adding a +1 to the roll.  And whether the ice modifiers apply or not doesnt matter since pavement requires a PSR when running and turn just like with ice so did not test that.  So, I am just wanting to rationalize what should roads draw over and what should they not?  And also if the "above" observations are correct with how MM should be handling movement over roads that share a hex with other difficult terrain?

Player name: BLOODWOLF
Four mechs already in position to test the various observations from the above descriptions
[terrain&roads.sav.gz](https://github.com/MegaMek/megamek/files/392192/terrain.roads.sav.gz)

**Comment by BLOODWOLF333** [comment]
TW pg.32

ROADS 
Roads are narrow strips of pavement that pass through other terrain. All the rules that apply to a paved hex apply to a road hex, except that units must move from one road or paved hex to another road or paved hex to be considered “on” the road. **A unit not on the road in a hex** is considered to be moving on the underlying terrain type.

**Comment by VampireSeraphin** [comment]
Since roads override the underlying terrain they should always draw on top.

**Comment by BLOODWOLF333** [comment]
Yeah so, thats what Im going to do with the tilesets cutting the includeStandardRoads & Bridges lines and paste them below the rubble lines so they will draw over all the terrain supers but, if a mech starts on a road hex and then moves over a road hex with a swamp or rubble in it MM is currently handling it like the mech is moving through the underlying terrain.  You can get bogged down in a swamp with a road and fall in a hex with rubble and a road.  Which I think is not correct?  "...units must move from one road or paved hex to another road or paved hex to be considered “on” the road. A unit not on the road in a hex is considered to be moving on the underlying terrain type.""

Although it does handle the MP correctly and its always 1 MP to move into roads hexes with swamp, rubble, or any other terrain that doesnt cause an elevation change.

**Comment by arlith** [comment]
So, I'm going to co-opt this "question" report as a report for an issue.  I have now made it so that PSRs aren't required when traveling on a road over swamp and rubble hexes.  Actually, it looks like now bog-down check was performed for swamp, however the "danger" asterisk on the move step was there.  The danger asterisk is no longer there for either, nor will there be a PSR nag or PSRs rolled.

Additionally, this should make the answer to the original question clearer: since roads can allow you to travel over these terrains, roads should draw on top of them.
