### ISSUE TITLE
Landed Drop ship missing Firing at Grounded Dropship Penalty

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#2951]
Reported from Discord
"Hey, so I don't know if this is Megamek thing, an Aero Sanity Mod thing, or a StratCon thing for balance, but:

Where is the -4 grounded dropship modifier? From what Total Warfare says, that modifier is supposed to be there whether the grounded dropship is immobile or not"

Poked around in Weaponattackactions.java line 3727 and couldn't find reference to a -4 per the rules on Total Warfare pg 110

### Environment
What version of MegaMek does your issue apply to?  0.49.1
What operating system are you using?  Windows

### Description
![image](https://user-images.githubusercontent.com/13752452/122615250-7342a380-d045-11eb-94c0-0e78597951b5.png)

### Files
No save available

**Comment by vulcanmagus** [comment]
I'm the player in from the screenshot
here's my game save
[Epoch.sav.gz](https://github.com/MegaMek/megamek/files/6679372/Epoch.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/6679376/megameklog.txt)

Player Name: Epoch
