### ISSUE TITLE
'Select Unit' window's left part is too big

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megamek#2959]
### Environment
Ver 0.49.2

### Description
![r](https://user-images.githubusercontent.com/47907439/122760997-b2d3ee80-d2d6-11eb-93c2-f998104e9cfc.png)
As title says. It is too big, while it is impossible to make it shorter. I am always cannot understand why we cannot change the size of these.

**Comment by kuronekochomusuke** [comment]
#3983 should fix this

**Comment by binaryspica** [comment]
> #3983 should fix this

I can't wait this! Thank you so much!
