### ISSUE TITLE
[MekHQ 49.3 Nightly #400] MegaMek lockup during movement

### ISSUE THREAD

**Issue by grylock666** [MegaMek/megamek#2979]
### Environment
MekHQ 49.3 Nightly#400
Windows 10
Java version 11.0.11

### Description
Megamek Princess Lockup during space movement phase calculation. See attached log

### Files
[megameklog.txt](https://github.com/MegaMek/megamek/files/6733116/megameklog.txt)

**Comment by NickAragua** [comment]
This is likely fixed with PR #2990
