### ISSUE TITLE
Princess setting tooltips and labels are incorrect

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#2986]
The Princess setting dialog has incorrect labels and ranges for Bravery and Self Preservation.  They do not perform as indicated in the tooltips and range labels, and conflict with the available help documentation (which appears to be correct).

Tooltips as they stands now:
Bravery - How quickly will I try to escape when damaged?
Range - Run Away!  -----  I fear Nothing!

Self Preservation - How worried about enemy damage am I?
Range - It's only a flesh wound  -----  It hurts! It really hurts!

Instead, they should look like this (matching the help documentation):
Bravery - How worried about enemy damage am I?
Range - I fear Nothing!  -----  Run Away!

Self Preservation - How quickly will I try to escape when damaged?
Range - It's only a flesh wound  -----  It hurts! It really hurts!

**Comment by SuperStucco** [comment]
Since princessBehaviors.xml is based around the displayed, rather than the help file/accurate settings, here's an updated version.

[princessBehaviors.txt](https://github.com/MegaMek/megamek/files/6758926/princessBehaviors.txt)

Odd that attaching XML isn't supported.  Extension should be changed from TXT to XML.

**Comment by BLR-IIC** [comment]
I upload stuff via zip file if GitHub gives me any trouble,.
