### ISSUE TITLE
Princess can't respond to 'unloading stranded units'

### ISSUE THREAD

**Issue by Menzius** [MegaMek/megamek#299]
I'd like to request a small addition to Princess in order to improve playability a bit.

During an AtB scenario against Princess I came into a situation in which I immobilised an enemy BA transport vehicle which was loaded with a point of Elementals. In the next round Megamek stopped with the message "Please wait for another player to unload their stranded units" and Princess did not react. I fixed the issue by connecting as computer player and answering the pop-up window, which asked whether I wanted to unload these units or not, for Princess. It would be very helpful if Princess were able to select "Yes" to this question itself. 

MekHQ 0.3.31/Megamek 0.41.21
attached are savegame, gamelog and mekhqlog.txt
[logs.gz](https://github.com/MegaMek/megamek/files/404491/logs.gz)

**Comment by arlith** [comment]
The issue here is that Princess client doesn't have a response for the "unload stranded units" dialog.  This is really more of a bug, since it will cause Princess to "get stuck."  I've updated the title to reflect this.

**Comment by dericpage** [comment]
Yeah, Princess has no knowledge of how to handle any sort of transported unit (infantry/BA in a transport, mechs in a dropship, etc).  Also, Princess is really bad at handling infantry and BA in general.

**Comment by BLOODWOLF333** [comment]
If the "auto abandon unit" option is on would that cause the BA to exit automatically as a work around or does that option only apply to mechs?

**Comment by arlith** [comment]
I don't think that option applies here.  Auto-abandon only affects ejection.  The problem here is that the unit being destroyed is carrying another unit on it.  Really, Princess needs to know what to do in this case.

**Comment by Menzius** [comment]
I have "Vehicles can be abandoned", "Ejected Pilots Flee" and "Auto Abandon Unit" enabled, as arlith said the issue is not the vehicle crew, which will abandon the vehicles just fine, but the dialog concerning the transported BA.

**Comment by scJazz2** [comment]
This keeps coming up any time that MM has a dialogue that needs responding. Princess is not capable of answering any of them. Arlith can you review the MM code for any dialogues? Give them all an answer for Princess.

**Comment by NickAragua** [comment]
Fixed with PR #722
