### ISSUE TITLE
Darkness + Gravity PSR 

### ISSUE THREAD

**Issue by Muddball** [MegaMek/megamek#2991]
What version of MegaMek does your issue apply to?  0.48.0 HQ's MegaMek.
What operating system are you using?  Windows
What java version are you using?  Open JDK 11

Tactical Operations p 55. You must make a PSR if there is high gravity to avoid damage if you jump. Pitch Black conditions apply a +2 modifier to any Piloting/Driving Skill Rolls (and Control Rolls) made if a unit used Running (Sprinting) or Flanking (Overdrive) movement, or used Maximum Thrust that turn.

RAW it works, as you are jumping not running, but this feels like a mistake.

**Comment by Windchild292** [comment]
MegaMek implements RAW. If you feel like this should be errata'd, please raise this to CGL on their forums.
