### ISSUE TITLE
Arctic Wolf II Prime and A configurations are swapped

### ISSUE THREAD

**Issue by scottboehmer** [MegaMek/megamek#2994]
While reading The Weight of a Name in Shrapnel 4, I wanted to check the Prime config of the Arctic Wolf II and found that the version I loaded didn't match the story's description. After some investigation, it looks like the Prime and A configurations are swapped in MegaMek's mech files.

### Environment
Noticed this in MegaMekLab 0.47 on Windows, and confirmed that the issue is present in the master branch version of the mech files.

### Description
The configurations for the Arctic Wolf II Prime and Arctic Wolf II A are swapped compared to the record sheets in RS3085 Cutting Edge. The Prime should have the LRM 15s and ER Medium Lasers while the A should have Stream SRM 4s. As far as I can tell, the other configuration files match the official record sheets.

### Files
- [Arctic Wolf II Prime](https://github.com/MegaMek/megamek/blob/master/megamek/data/mechfiles/mechs/3085u/Cutting%20Edge/Arctic%20Wolf%20II%20Prime.mtf)
- [Arctic Wolf II A](https://github.com/MegaMek/megamek/blob/master/megamek/data/mechfiles/mechs/3085u/Cutting%20Edge/Arctic%20Wolf%20II%20A.mtf)

**Comment by HammerGS** [comment]
Covered in this errata - https://bg.battletech.com/forums/errata/technical-readout-3085-supplemental/msg964568/#msg964568

**Comment by scottboehmer** [comment]
As far as I can tell, the MegaMek data files do not take that errata into account.

TRO 3085 Supplemental had the Prime config with Streak SRMs and the A config with LRMs which matches the MegaMek data files. The linked errata says to swap those so that the Prime config has LRMs and the A config has Streak SRMs (which will match RS3085 CE).

**Comment by AlphaSled** [comment]
Reopening, as the Arctic Wolf II Prime should, per the errata, have the LRMs.
The Arctic Wolf II A is the one with the Streaks.

**Comment by pheonixstorm** [comment]
This appears to have been fixed in [c433dfc](https://github.com/MegaMek/megamek/commit/c433dfc62119a60e2da384acd1cb8ac8c9154026)
