### ISSUE TITLE
Critical Hits not being applied 0.49.2

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#2995]
At first I thought it was a fluke with my game settings, but I'm not so sure now.  In the following report, my _Summoner_ scored a critical hit on the center torso of a _Crab_, but no critical hit was marked off for the unit:

>    LRM 15 ((Clan) Dead-Fire ammo) at Crab CRB-27 (Clan Goliath Scorpion Designated Target);  needs 7, rolls 10 :  - Direct Blow - 15 dead fire missile(s) hit (w/ +2 bonus).

        Crab CRB-27 (Clan Goliath Scorpion Designated Target) takes 2 damage to RA.
            6 Armor remaining.

        Crab CRB-27 (Clan Goliath Scorpion Designated Target) takes 2 damage to CT (critical).
             11 Internal Structure remaining.
            Critical hit on CT. Roll is (4+1) = 5; no effect.
            **Critical hit on CT. Roll is (9+1) = 10; 1 location.**

        Crab CRB-27 (Clan Goliath Scorpion Designated Target) takes 2 damage to RL.
            16 Armor remaining.

        Crab CRB-27 (Clan Goliath Scorpion Designated Target) takes 2 damage to RT.
            8 Armor remaining.

![image](https://user-images.githubusercontent.com/18338059/124691764-6083f780-deaa-11eb-99da-1453fa86fec9.png)

Game save and logs attached.  This happens a few more times in the last round of fire in the save file.

[game save and logs.zip](https://github.com/MegaMek/megamek/files/6773894/game.save.and.logs.zip)

**Comment by SuperStucco** [comment]
I can also report this.  Not common, but noticeable.

**Comment by MGM175** [comment]
Also had such a occurrence once, yesterday.

**Comment by BLR-IIC** [comment]
Happened again with a failed low-G PSR...

> 
 Puma (Adder) A (Clan Goliath Scorpion Primary Opfor) must make a piloting skill check (used more MPs than at 1G possible).
Needs 7 [5 (Base piloting skill) + 2 (Sprinting) + 0 (used more MPs than at 1G possible)], rolls 5 : fails.
        Puma (Adder) A (Clan Goliath Scorpion Primary Opfor) takes 2 damage to Internal Structure of RL.
             6 Internal Structure remaining.
            Critical hit on RL. Roll is 10; 1 location.

        Puma (Adder) A (Clan Goliath Scorpion Primary Opfor) takes 2 damage to Internal Structure of LL.
             6 Internal Structure remaining.
            Critical hit on LL. Roll is 8; no effect.
