### ISSUE TITLE
Ground to Air fire Causing Accidental Fire Check

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#300]
Couldn't find anything specific in the books, but it strikes me as odd that firing a laser from mech on the ground to an ASF would cause a check for a forest fire.  I could see Ammo based weapons causing it.

![image](https://cloud.githubusercontent.com/assets/13752452/17465890/18c195a0-5cbf-11e6-856e-818eef55e755.png)

**Comment by arlith** [comment]
The rules on this aren't 100% clear.  TO pg43 says this:

>If a weapon attack against a unit occupying a wooded/
>jungle hex misses its target, and the weapon can be used to
>start fires (see Intentional Fires, below), the attacking player
>rolls 2D6 to determine whether his attack accidentally set
>a fire.

I don't think that it makes sense to start an accidental fire when shooting at a unit flying about terrain features.  I updated the accidental fire check to not include Entity's that are airborne or airborne VTOL or WiGE.

**Comment by wildj79** [comment]
I've posted a rules question on the forums.

http://bg.battletech.com/forums/index.php?topic=53994.0

**Comment by HammerGS** [comment]
@arlith You guessed right :)

http://bg.battletech.com/forums/index.php?topic=53994.msg1255898#msg1255898

**Comment by arlith** [comment]
Clearly, I've been at this for too long.
