### ISSUE TITLE
Rules issue - TAG phase should not allow twisting

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#3002]
Per a [recent rules question thread](https://bg.battletech.com/forums/total-warfare/tag-torso-twistable/), the TAG designation phase should not allow torso/turret twisting, as this happens only during the Weapons Fire phase. 

Twisting during the TAG phase is allowed in Megamek as of versions 0.48 / 0.49.2

**Comment by jefga85** [comment]
Recommend that this be reopened as there was a change to the rules again through errata and forum posting. 

"The Newest Errata was posted up and states that TAG now has this new bit of wording (end of PAGE 21 for BMM, and 142 for TW)"

> Arm flipping (see p. 24) or torso-twisting (see p. 25) can be made immediately prior to firing TAG. This prevents any 
further use of such in that turn’s Weapon Attack Phase.

> Rotating the firing arcs (see p. 105) or arm flipping (see p. 106) can be performed immediately prior to firing TAG. This prevents any further use of such in that turn’s Weapon Attack Phase.

[Rules Question in 2023 reverting the old 2021 decision, response by Xotl](https://bg.battletech.com/forums/index.php/topic,82656.0.html)

[Errata Posting from Xotl](https://bg.battletech.com/forums/index.php/topic,33530.msg1962755.html#msg1962755)
