### ISSUE TITLE
[49.2] Firing Phase Freeze from Building IllegalArgumentException

### ISSUE THREAD

**Issue by K007** [MegaMek/megamek#3005]
### Environment
49.2 MHQ bundled MM

### Description
Firing phase freeze up's along with a number of other errors that are shown in the .log file

### Files
[megameklog.txt](https://github.com/MegaMek/megamek/files/6803323/megameklog.txt)
[quicksave.sav.gz](https://github.com/MegaMek/megamek/files/6803329/quicksave.sav.gz)
Playername is "June's Raiders"

**Comment by Windchild292** [comment]
We'll also need campaign and customs for the MekHQ-side of things, plus the mekhqlog.txt.

**Comment by Windchild292** [comment]
The three above are the issues found in the mekhqlog.txt. I've not opened megameklog.txt

**Comment by Windchild292** [comment]
And the Compute changes conclude what I'll be handling here. I'm not certain how the buildings stuff works, and it's above my MegaMek knowledge.

**Comment by Windchild292** [comment]
I'm actually going to close this based on the current issues, and let #3020 subsume the building issue.
