### ISSUE TITLE
[0.49.17] Battle armour plasma rifles not applying TacOps optional rule

### ISSUE THREAD

**Issue by Gribbly1** [MegaMek/megamek#3018]
Environment
Bundled HQ's MegaMek.
Windows 10
Java version 1.8.0_261

Description
With TacOps BA vs BA damage turned on, a damage value of 2 shouldn't be possible in the following screenshot:

![image](https://user-images.githubusercontent.com/55139229/126006371-2bc1f49e-20c3-43b2-bee5-441d00340b90.png)
![image](https://user-images.githubusercontent.com/55139229/126006431-1dd14408-2ba4-4431-a004-6d2bc57edd5e.png)

Files
[save.sav.gz](https://github.com/MegaMek/megamek/files/6833290/save.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/6833293/megameklog.txt)
[CC Plasma Rifle Platoon (foot).txt](https://github.com/MegaMek/megamek/files/6833296/CC.Plasma.Rifle.Platoon.foot.txt)

**Comment by pheonixstorm** [comment]
Rules reference (book and page) and name for the save.

**Comment by Gribbly1** [comment]
Save name: Forlorn Hope

TO: AR p107

**Comment by Gribbly1** [comment]
[plasma.sav.gz](https://github.com/MegaMek/megamek/files/11105381/plasma.sav.gz)
Save name: Forlorn Hope

![image](https://user-images.githubusercontent.com/55139229/228662831-3ed94a05-15ec-4945-bafc-90853acc419e.png)
Issue is still present in 0.49.12

From testing it seems the plasma rifle never inflicts 8 points of damage. Perhaps MM is using D6+1 instead of D6+2?

**Comment by Gribbly1** [comment]
Issue still present in 49.13. MM must be using D6+1 instead of D6+2 for plasma rifle damage against other BA, there are results of 2 damage and max of 7 damage after several turns.

[test2.sav.gz](https://github.com/MegaMek/megamek/files/11560167/test2.sav.gz)
name: test


![image](https://github.com/MegaMek/megamek/assets/55139229/b4442a65-c7ec-4529-86b2-2052195fe27d)

**Comment by Gribbly1** [comment]
Issue still present in 49.17. 

If using TO: AR p107 at least some damage rolls should result in 8 damage. Megamek is clearly using d6+1 instead of d6+2 damage for plasma rifles.
[save4.sav.gz](https://github.com/MegaMek/megamek/files/14231020/save4.sav.gz)
Player name: test

**Comment by Gribbly1** [comment]
![image](https://github.com/MegaMek/megamek/assets/55139229/54032b93-7d4a-44c8-be87-ee6bc11d118f)

Please amend the optional damage vs BA from d6+1 to **d6+2** as per the optional rule p107 TO: AR
![image](https://github.com/MegaMek/megamek/assets/55139229/f2df990e-6b46-4627-b397-79b5063bf143)

**Comment by Sleet01** [comment]
@Gribbly1 Do you happen to know if the rules specify that this value should be rolled once _per trooper_, or is the value rolled once per attack and then applied to all troopers?  As of right now, MM is making one roll and applying its result to all hits.

(N.B. I know nothing about this side of the ruleset)

**Comment by Gribbly1** [comment]
The value should be rolled once per trooper that hits. 

If there are four troopers and the cluster roll indicates three have hit, MM should randomly determine three separately rolled hits of d6+2 damage. 

I think MM is making separate rolls correctly, just with the wrong value:

![image](https://github.com/MegaMek/megamek/assets/55139229/91769c4f-102d-4dbe-8020-6e42aa0f0d4e)
