### ISSUE TITLE
[0.48.0, maybe others] Issue with Individual Camo and Player Camo interaction

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#3024]
MegaMek 0.48.0 standalone
Windows 10
Java 11

There is an odd interaction in the Lobby between the 'Player camo' setting and the 'Individual camo' setting. It appears that, if you set the 'Player camo', and then set the 'Individual camo' to the same camo, it is not saved to the unit, which means that when you change the unit's owner, the unit's camo changes to the new owner's camo.

To replicate:
1. Open a fresh session of MM and go into the Lobby.
2. Create a second 'player' (Princess will do nicely).
3. Change your 'player camo' to something nice and garish.
4. Add a unit (which will display in your 'player camo').
5. Change the unit's 'Individual camo' to the same camo scheme.
6. Use 'Change owner' to reallocate the unit to the other 'player'.
7. The unit's garish colour scheme will be replaced by the default 'player camo' of the other 'player'.

If you set the 'Individual camo' to any scheme other than your 'player camo', then it 'sticks' (or 'dries', perhaps), and remains on the unit when it is moved from one player to another.

(I suspect that this is because the unit is already in that scheme from the 'player camo', so the Lobby doesn't register a change, and it therefore isn't saved to the unit.)

(Issue discovered by user 'lastone' on the Discord. Thanks!)

**Comment by Windchild292** [comment]
Working as intended.

**Comment by SimonLandmine** [comment]
Working as intended, but not clear to users, as it means that it ignores attempts to set Individual Camo, if that happens to match what they have assigned as Player Camo, so it results in unexpected and unwanted behaviour.

**Comment by Windchild292** [comment]
I'm working on documenting how portraits and camouflage work, and hope to have the guides done today.

**Comment by SimonLandmine** [comment]
Because of course you're already on top of it! 😆  I'll keep quiet in future. 😆
