### ISSUE TITLE
RFE - Fieldwork Vehicles

### ISSUE THREAD

**Issue by Sliprunner** [MegaMek/megamek#3026]
The 'Fortify' action available to create a fortified position after a few turns is presently locked to infantry only.

Is it possible to expand this feature as per TacOps errata to include vehicles mounting appropriate Fieldworks equipment? (Ex: Bulldozer or Backhoe). This would apply to the following Cannon vehicles: Brunel, Buffel, 'Engineering Vehicle', Kallon, Lesseps, O-65/66 'Oppie', Hesiod , and Rhino FST EC; Ideally it would apply to any vehicles with Bulldozer (F_bulldozer) or Backhoe (F_backhoe)

If it assists, relevant code appears to be
MovementDisplay.Java, Lines 145 and 896-907 [Controls if the fortify button is visible and what conditions it's enabled]
MoveStep.Java, Lines 2121-2152 [Defines to Fortify MoveStep]
Infantry.Java, Lines 150-157 [Enum states], and Lines 1792-1809 [Ticking 'Dug In' state]
I am unsure where it is defined how a hex is updated to 'fortified' status from the fortify command.

I understand if this admittedly niche option is not desired, Thank you for your time and effort

**Comment by gsparks3** [comment]
Additional note: the ruling allowing vehicles to construct fieldworks is found in the TO (old version) Errata Document, and presumably the new TO as well, although I do not have access to that version. 

It is quite straightforward:
`Vehicles with a bulldozer, backhoe, or any piece of equipment ruled as equivalent may be considered to have the fieldworks ability, allowing them to construct field fortifications in a manner identical to Trench/Fieldworks Engineers (see p. 341).`

**Comment by pheonixstorm** [comment]
This would make for a good addition.

**Comment by pheonixstorm** [comment]
Adding, there is code that will update the map to change or add new terrain. It is mostly used for snow, ice, magma, and mud iirc. May be a few I haven't thought of.

**Comment by Sliprunner** [comment]
Given the recent snapshot, ended up looking at this again and can see how it could be implemented, I just don't have the build environment to do so. Everything is currently contained in GameManager.Java, MovementDisplay.java, and Tank.java; I may work on this if I find time to get things setup. What I'm seeing thus far is to do these potential changes:

Tank.Java: Add dugIn int's; copy 'dugIn' progress from Infantry.newRound to Tank.newRound; copy .isEligbleFor, .setDugIn, and .getDugIn from Infantry.Java to Tank.Java
MovementDisplay.Java: Edit MOVE_DIG_IN and MOVE_FORTIFY to add CMD_Tank as an option; Add 'isTank' boolean to .updateButtons then copy or edit the Infantry - Digging In and Infantry - Fortify for tanks with requirement of misc equipment of F_BULLDOZER or S_BACKHOE
GameManager.Java: Edit .resolveFortify with variant of the 'if' for tanks, making sure to clarify that needs to clear in the dig_in for tanks as well if there's others doing so.

**Comment by SJuliez** [comment]
Implemented.
