### ISSUE TITLE
0.49.2 right-clicking unit in lobby fails to produce dropdown menu

### ISSUE THREAD

**Issue by servo01** [MegaMek/megamek#3030]
0.49.2
Issue present in both MegaMek and HQ MegaMek
Linux Mint 20.2
openJDK 11.0.11 

Right-clicking units within the lobby fails to produce the dropdown menu (View, Config, Edit Damage, Load Onto, etc.) but will instead launch the Pop-Up for Pilot Information (Pilot Portrait, Name, Skills - see attached screenshot). Without being able to access the "load onto" command, it becomes impossible to load units onto APCs or Dropships.

This same issue was present on an older laptop (also running Linux with openJDK 11) I was unable to identify the cause and instead simply switched to running 0.49.2 on a Windows 10 system which worked find and had no issue accessing the right-click dropdown menu.

I currently have a fresh install of both 0.49.2 and Linux Mint 20.2 on a new laptop and the right-click dropdown menu has again become inaccessible. 

Issue remains present when accessing the lobby from both MegaMek and MekHQ
as well as:

MegaMek 49.1, 48, 47.14, 47.11
Linux Mint 20, Ubuntu 20.04 and 21.04
openJDK 14, openJDK 16 

Another oddity which may be related - 

Launching MegaMek from the folder icon (after making the .jar file executable) opens the start menu, but does not show the splash screen. Attempting to start a new game produces a "Fatal error could not initialize java.io file not found exception data/images/wrecks/wreckset.txt" message.

Launching from the terminal using "java -jar MegaMek.jar" gives the splash screen and boots into the lobby without issue. 

![screenshot](https://user-images.githubusercontent.com/30708294/127174148-ca4ceae7-a5ad-497f-965d-64d6b837e478.jpg)

**Comment by Windchild292** [comment]
Log files are missing and required for any potential fixes

**Comment by servo01** [comment]
[megameklog.txt](https://github.com/MegaMek/megamek/files/7019070/megameklog.txt)

I've been unable to access the right-click drop down menu for any unit in the lobby with any of the .49 development branch versions of MegaMek or MekHQ on a Linux system.  

The drop-down is produced without issue with the Windows version.

**Comment by HammerGS** [comment]
Closing as issue was opened again. 
https://github.com/MegaMek/megamek/issues/3102
