### ISSUE TITLE
Mud Sharing Hexes With Other Terrain

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#304]
Currently MM does not replace the base terrain with mud when there is a super-terrain sharing the same hex like with woods, roads, etc.  TO doesn't say that mud can or cannot occupy the same hex with other terrain types but, it does not look appealing.

![mudatmospheric](https://cloud.githubusercontent.com/assets/16950832/17502196/8cf59132-5dab-11e6-89f3-51193640ddb1.png)

TO pg. 51
Mud A quick and easy way to apply mud to a playing area is to make any Depth 0 water hex mud. As always, though, players can choose to add mud however they wish. Apply a +1 MP cost to enter a mud hex, as well as a +1 modifi er to all Driving Skill Rolls made while in that hex. Units entering a hex containing the Mud terrain modifi cation may also get stuck (see Bog Down Rules, p. 62) 
.......
Prohibited Conditions: Cannot be used with Vacuum Atmospheric Pressures, or with Extreme Temperatures of –30 degrees Celsius and below.

**Comment by mkerensky** [comment]
What tileset and/or weather or other options are you using?    I use rain quite a bit, and generally the hq_atmospheric tileset.  I get both the graphic and terrain effects for mud on wooded hexes when moderate rain or higher is in effect. I'm pretty sure it also applies to other hex types, like field, swamp and rough, but I'll have to do further research to be sure.  I have not played a muddy game under 0.41.21, but this has been working for me for the past several versions.

**Comment by BLOODWOLF333** [comment]
Thats the atmospheric tileset ^ it also does it with my personal tileset (moderate rain planetary conditions and using the generated terrain feature)
![image](https://cloud.githubusercontent.com/assets/16950832/17528848/8f1e5706-5e36-11e6-80e1-8f8b51ff74d8.png)

And with largetexture, I dont recall mud ever drawing under wood or road hexes but, have not tried it with the hq_atmosheric yet.
![image](https://cloud.githubusercontent.com/assets/16950832/17528887/be5d2876-5e36-11e6-8032-1e169977d4c4.png)

**Comment by arlith** [comment]
Have you confirmed that those road hexes do in fact have mud?  I think it's worth pointing out that you aren't creating a map with the mud terrain, but rather you are using the moderate rain planetary condition to add mud to every hex.  It's possible that it's not adding mud to those hexes, and this is maybe an issue with the planetary condition rather than the terrains.

**Comment by BLOODWOLF333** [comment]
Dont know, will test this further when i get home from work.  But, now that you said that Arlith makes me wonder if the same thing occurs with accumulated snow too which I will have to test and get back to you all.

**Comment by BLOODWOLF333** [comment]
Alright, accumulated snow works correctly when the weather is set to moderate + snowfall.
![github0](https://cloud.githubusercontent.com/assets/16950832/17540960/8a91d7f4-5e80-11e6-9b88-5fac27f013ca.png)

But mud does not get handled in the same way, it does not overwrite the base terrain that also contains a road or woods super.  Realistically and visually I think it should and theres nothing in the rules to say yes/no.
![github](https://cloud.githubusercontent.com/assets/16950832/17540962/906a97a6-5e80-11e6-89f4-aa02098c4f98.png)

**Comment by BLOODWOLF333** [comment]
Now in the board editor you can manually have mud and roads or woods in the same hex but, the terrain generator is what is not doing it.  I personally only use the random terrain and I believe AtB does as well?
![github1](https://cloud.githubusercontent.com/assets/16950832/17541037/49875e04-5e81-11e6-8c83-5a25380250de.png)

**Comment by arlith** [comment]
Ok, I think this is working as intended.  The rules for moderate rain are in TO pg 59.  Relevant text:

> Mud: Moderate rainfall automatically includes all modifiers
and effects of mud (see p. 50) in any clear, Depth 0 water or
dirt road hex on the playing area.

So, woods and roads hexes shouldn't be effected by mud.
