### ISSUE TITLE
Surtur SUR-T1 wrong name in megamek

### ISSUE THREAD

**Issue by AlvarOldebrecht** [MegaMek/megamek#3040]
The Hanseatic League Mech Surtur SUR-T1 is currently incorrectly named Surtur SUR-6H in Megamek. The correct file is attached. 

Source: http://www.masterunitlist.info/Unit/Details/7884/surtur-sur-t1
[Surtur SUR-T1.zip](https://github.com/MegaMek/megamek/files/6917031/Surtur.SUR-T1.zip)

**Comment by sandysimonton** [comment]
Greetings AlvarOldebrecht! 
I would love to change this, it seems pretty minor, however I don't have the resources to verify your claims - the MUL is pretty close to canon but it isn't guaranteed to be canon. Can you provide the reference and page number (not a screenshot) of the canonical publication in which the Surtur is featured? Thanks!

**Comment by HammerGS** [comment]
This has a fix pending that hasn’t been committed yet.

**Comment by AlvarOldebrecht** [comment]
The official source is "Operational Turning Points: Hanseatic Crusade" in the Random Assign Table on page 7 and the Battlemech Record Sheet on page 42, where the type identifier Surtur SUR-T1 is used in each case.

**Comment by HammerGS** [comment]
> Greetings AlvarOldebrecht!
> I would love to change this, it seems pretty minor, however I don't have the resources to verify your claims - the MUL is pretty close to canon but it isn't guaranteed to be canon. Can you provide the reference and page number (not a screenshot) of the canonical publication in which the Surtur is featured? Thanks!

Incorrect the MUL is canon.
