### ISSUE TITLE
RFE - TO Infantry movement on pavement

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#3054]
Total Warfare p. 61 describes a MP bonus for ground vehicles moving on pavement. This is explicitly noted as not affecting motorized or mechanized infantry. However, Tactical Operations: Advanced Rules p. 25 describes an optional rule that allows this bonus MP effect to apply to motorized and mechanized infantry.

Megamek does not currently implement this optional rule; this RFE requests that it be added.

**Comment by Windchild292** [comment]
Added in #4005
