### ISSUE TITLE
Inferno Bombs Non-Functional Against 'Mechs

### ISSUE THREAD

**Issue by pokefan548** [MegaMek/megamek#3061]
### Environment
0.48.0 Windows

### Description
'Mechs struck by multiple inferno bombs only gain heat as if struck by one.
![image](https://user-images.githubusercontent.com/36405715/128621461-204f6a84-5536-496f-a7da-3d232545a97e.png)

**Comment by gsparks3** [comment]
How much non-external heat did the SHD generate that turn? There's a cap of 15 heat from external sources per turn, which might be the reason.

**Comment by pokefan548** [comment]
> How much non-external heat did the SHD generate that turn? There's a cap of 15 heat from external sources per turn, which might be the reason.

Really? Source for that?

**Comment by pokefan548** [comment]
Ah, right, sorry.
