### ISSUE TITLE
Grounded DropShips and Weapon Ranges

### ISSUE THREAD

**Issue by strategoslevel3** [MegaMek/megamek#3063]
Grounded DropShips 

Firing Weapons P. 249 TW

“Resolve each individual weapon as a single attack, using ranges and damage values as found on pp. 303-304”

MegaMek doesn’t do this! This means in MegaMek grounded DropShips weapons have far shorter ranges when grounded than they should.

**Comment by NickAragua** [comment]
The assertion in this bug report is patently incorrect, here's an example of a grounded dropship and its firing arcs + displayed weapon ranges: 
![image](https://user-images.githubusercontent.com/29387808/128658107-9fb97f48-86df-4b79-b385-d26da6e3d16d.png)


However, if you can provide a save where dropship weapons have "weird" ranges, then we can take a look at it.

**Comment by Windchild292** [comment]
Closing based on @NickAragua's comment.
