### ISSUE TITLE
Persistant Auto-Flee check box

### ISSUE THREAD

**Issue by TheSilentK21** [MegaMek/megamek#3069]
### Environment
MekHQ v49.2
Win 10 Home
Java 11.0.11 2021-04-20

### Description
When adding a new bot, the default setting for the Auto-Flee option is enabled. Disabling the Auto-Flee option is ineffective, immediately configuring the bot shows the Auto-Flee check box checked again. This occurs in the lobby as well as when replacing a /kicked player. Completely unable to create a bot without it fleeing.

### Files
[PrincessAutoFlee.sav.gz](https://github.com/MegaMek/megamek/files/6958460/PrincessAutoFlee.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/6958464/megameklog.txt)

**Comment by NickAragua** [comment]
This UI has been changed since 49.2, so I don't think this is going to be relevant.

**Comment by TheSilentK21** [comment]
OK, cool. Guess I should be keeping up with the latest releases

**Comment by NickAragua** [comment]
As a workaround while you're on 49.2, you have to make sure to say "yes" when the bot dialog asks you if you "want to save changes to this configuration". Otherwise, for some reason, any behavior modification you make just don't "stick".

**Comment by SJuliez** [comment]
Eh, I believe this may already be the new UI, the fix for this was merged yesterday I think.
