### ISSUE TITLE
0.48.0 "Waiting for firing phase ..." message before movement phase.

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#3076]
MM Standalone 0.48.0
Windows 10
Java 11 (OpenJDK)

After clicking 'Done' on the Initiative Phase, the message "Waiting for Firing phase ..." is displayed in the status bar beneath the menu buttons, until it displays "It's your turn to move." or "It's Princess's turn to move."
(No Artillery in use, so no Artillery Phase.)

Suspect this message should read "Waiting for Movement phase ..."

**Comment by kuronekochomusuke** [comment]
this has been corrected
