### ISSUE TITLE
Very early introduction year units do not show up in early years

### ISSUE THREAD

**Issue by NorikSigma** [MegaMek/megamek#3080]
MekHQ 0.48
Windows 10

Basic, extremely early availability units such as foot platoons, ground car, motorized platoons, primitive Armored Personnel Carriers, wheeled APCs, and almost everything with intro date pre-2470 show up only as standard in 2505+ (presumably due to using a satndardised date template) instead of more reasonable dates. The only exception are the Mechanized Platoons which have Experimental 1950, Advanced 1950-2099 and Standard 2100+.
![footplatoon](https://user-images.githubusercontent.com/63631735/119758290-e179c780-bed8-11eb-87cd-9e24bde78db1.PNG)

All these means that these early-availability basic units such as foot platoons are classified standard only centuries after mechanized platoons, in the year 2505, and around the same time as the Mackie, despite intro-ing in 1950.

**Comment by Windchild292** [comment]
Transferring this to MegaMek because this is entirely MegaMek-side code.

**Comment by neoancient** [comment]
The dates reflect anti-mech capabilities.
