### ISSUE TITLE
Show possible moves does not account for heat penalties

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/megamek#309]
The enforcer pictured is at 6 heat with a move of 3/5/4. The show possible moves option does not reflect the heat penalty.
![spm_heat](https://cloud.githubusercontent.com/assets/1787879/17580295/88dee8f2-5f6b-11e6-9653-c7af23fb8235.png)

Not sure if this is the only place is does not correctly calculate move modifiers but will test others as they pop up.

**Comment by arlith** [comment]
You really should attach a saved game for issues like this.  Not only does it save me time in having to reproduce, but I can ensure I've got the same game options as you do.  Your movement envelope looks like it's for 3/5 to me.  The problem in your screenshot is that you're picking the wrong path: you've got R F F L F F which is 6MP.  Instead, you could go F F R F F and end up in 1108 in 5MP, which would be running, so the movement envelope is correct.  If you used the path planner to get this path, then I would guess you're using a slightly older version, as I made a fix a release or two ago that may affect this.  When I test, I get the proper path.

**Comment by arlith** [comment]
I don't think it's terribly important, but he's a screenshot showing my setup, and the path the planner gave me.
![screenshot-3](https://cloud.githubusercontent.com/assets/13815237/17645456/4024c2be-616c-11e6-8e53-b085fd81c005.png)

**Comment by pheonixstorm** [comment]
The issue I was showing is that the 6MP sprint is within the yellow running highlight instead of the area being correctly highlighted as a sprint. The path planner is correct but the option to show possible moves displays the highlighting incorrectly which is why I choose to post a pic and not the save game.  Will reproduce and provide a pic with and without movement as well as a save for it using one of the daily duilds.

**Comment by HammerGS** [comment]
You know...its nice to get the detail from your second post in the first report.  You've written enough of these bug reports.  We need specifics to the bugs, steps to reproduce, save games when ever possible.

A screen shot that says doesn't reflect the heat penalty is pretty generic, so Arlith spends time troubleshooting thinking its one thing and then get the additional information saying its extra.

Just saying.

**Comment by arlith** [comment]
Go back and read what I said again.  The movement envelope color indicates the existence of a path that can get you there with that movement mode, not that every path will get you there with that movement mode (otherwise everything would be yellow/purple, as you'd get the F R R R R R R R path).

You are giving a 6MP path: R F F L F F.  There exists a 5MP path to that exact same hex (F F R F F, unless 1309 has terrain in it; it's cut off but looks clear).  Because there exists a 5MP path to that hex, it should be colored yellow (as it is).
