### ISSUE TITLE
Jumped vehicle does not get to-hit modifier for being jumped

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megamek#3095]
### Environment
Ver 0.49.2
Windows 10
OpenJDK 11.0.11+9

### Description
As title says. If you had a vehicle with Vehicular Jump Jets(349.TO) and jump by use it, then target the same vehicle by the other unit, on To Hit report of weapon it does not gets to-hit modifier for target jumped. It still suffer the to-hit modifier on its own attack for 'attacker jumped', though.

For example, if both vehicle A and B - which has gunnery 4+ and vehicular jump jets -  are jumps 3 hex and has each other on the adjacent front hex, reports of the weapon attack(other than with minimum range) on both says needs 8 - 4(gunnery skill) + 3(attacker jumped) +1( target moved 3-4 hexes). But both of them are must have **+1 for target jumped** as well and it should be needs 9 instead.

I have only tested combat vehicle but it would be also possible that support vehicle has the same problem.

**Comment by NickAragua** [comment]
![image](https://user-images.githubusercontent.com/29387808/136699196-7a909a12-366c-4116-97cc-92a82d224b7c.png)
This does not appear to be happening any more.

**Comment by binaryspica** [comment]
It seems weird, for I have checked it right now and it still happens.

Perhaps the difference in the motive type is the problem? I have checked it with **WiGE** combat vehicle and its opponent still don't get the +1 to-hit modifier against it.

**Comment by NickAragua** [comment]
Will re-check with jump-capable WIGE (what a very low-use case, is there a canon unit like that?)

**Comment by binaryspica** [comment]
No, as far as I know there is no canon WiGE; although WiGE is legal to have vehicular jump jets and I did made a custom vehicle to test it.

**Comment by binaryspica** [comment]
Sure. Here you go. I have checked it again with this and still have the same result - it still don't get to-hit modifier for being jumped when attacked by the other units
[TestWiGE (custom).zip](https://github.com/MegaMek/megamek/files/7318339/TestWiGE.custom.zip)

**Comment by Sleet01** [comment]
I believe we now have cannon jump-capable WiGEs, and I've been doing some work in this area, so I'll see if I can repro and fix this.

**Comment by Sleet01** [comment]
> Sure. Here you go. I have checked it again with this and still have the same result - it still don't get to-hit modifier for being jumped when attacked by the other units [TestWiGE (custom).zip](https://github.com/MegaMek/megamek/files/7318339/TestWiGE.custom.zip)

I've done some testing and here are my results:

- a WiGE that was landed at the start of the turn and jumped _does_ get the +1 TMM modifier for jumping.
- a WiGE that was flying at the start of the turn and jumped does _not_ get the +1 TMM modifier for jumping.
- other vehicles such as wheeled or hover tanks that jump _do_ get the +1 TMM modifier for jumping.
- in all cases, the jumping vehicle _does_ get the +3 AMM for jumping.
- In the cases where a vehicle did get the +1 TMM for jumping, it still did not _display_ this TMM in e.g. the turn summary's attack roll mouse-over display.

Note, however, that the most recent PDF of Total Warfare states that Jumped _or_ Airborne non-ASF units get only a single +1 TMM; it does not appear that the total TMM for an airborne WiGE that jumped this turn should be (+1 + +1) = +2. 

Recommending that this issue be closed, unless it is vital that the +1 TMM for jumping vehicles be displayed in e.g. tooltips.
