### ISSUE TITLE
Frozen Princess

### ISSUE THREAD

**Issue by EngelNUL** [MegaMek/megamek#3098]
### Environment
HQ's MegaMek.
Windows
Java version 1.8.0_301

### Description
Princess froze in the closing rounds of a match. Drop downs still selectable and mouse over pop ups still work. 
Recreate able by loading the game and ending turn. 

### Files
Playername: EngelNUL
[1.sav.gz](https://github.com/MegaMek/megamek/files/7026499/1.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/7026500/megameklog.txt)

**Comment by Windchild292** [comment]
Nothing in the logs, nor recreatable based on the provided save (within which replace player gets Princess working immediately, with no issues)
