### ISSUE TITLE
Tripod Weight Calculations 

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#310]
Per this thread - 

http://bg.battletech.com/forums/index.php?topic=53882.msg1245287#msg1245287

Cockpits for Tripods should be 4ton or 5 ton.  See IO Rules Pg 165

also AES for Light and Medium Tripods should be allowed in Center Leg.  See TO pg 278 very bottom of page for details

**Comment by arlith** [comment]
Weights are properly computed for the tripod cockpit type, the problem was tripods weren't having their cockpit type set properly.  I fixed that.

I have also fixed the AES issue, but that is in MML code.
