### ISSUE TITLE
0.49.3 Tooltips clear after a time of 5 to 6 seconds whilst mousing over game rule options in Megamek and MekHQ game setups.

### ISSUE THREAD

**Issue by Admiral-Obvious-001** [MegaMek/megamek#3103]
### Environment
MegaMek and MekHQ 0.49.3 Operating System Windows 10, 
Java JDK 16.0.2

### Description
Tooltips for optional rules in MegaMek game setup (such as game rules) disappear after a set period of 5 to 6 seconds. I would expect the behavior to be that the tooltip remains open until the mouse is moved off of the item generating a tooltip.

### Files
Not Applicable

**Comment by Admiral-Obvious-001** [comment]
I should mention that this issue has been present as long as I've played with MegaMek and MekHQ back at around Version 43.

**Comment by Windchild292** [comment]
```ToolTipManager.sharedInstance().setDismissDelay(dismissDelay);```
Should be what needs to be added

**Comment by Windchild292** [comment]
This is a current client option, and will be applied throughout the suite in the future.
