### ISSUE TITLE
Inconsistent dialog keyboad okay/cancel behaviour

### ISSUE THREAD

**Issue by mjog** [MegaMek/megamek#3105]
Currently, MM dialogs seem to be pretty random in terms of their support for hitting Enter & Esc for triggering the default action and the cancel action, respectively. Try it in the lobby for example - half of the dialogs that show up there respond to escape, but another half don't.

Looking into it, there's at least two disjoint abstract dialog class hierarchies:

* JDialog  
  * AbstractDialog
    * AbstractButtonDialog
      * AbstractValidationButtonDialog (unused?)
      * AbstractIconChooserDialog
        * 2 concrete subclasses
      * 7 concrete subclasses
    * AbstractHelpDialog
      * 5 concrete subclasses
    * 2 concrete subclasses
  * ClientDialog
    * 8 concrete subclasses 
  * ~43 concrete subclasses

The `ClientDialog` seems to be getting used by a few newer dialogs (the new Edit Player and Planetary Conditions - which look great btw!)

**Comment by mjog** [comment]
[pressed submit too early]

.. but `ClientDialog` doesn't seem to support some of the polish that the `AbstractDialog` hierarchy has, including support for having Esc close the dialogs.

So it seems these might want to get cleaned up, probably in the direction of merging the `AbstractDialog` hierarchy into `ClientDialog` - does that sound a bit right?

**Comment by Windchild292** [comment]
It's the wrong way around. The Base Components are the new setup that I've coded to improve the GUI, although I've largely been focused on implementing it within MekHQ. Further, ClientDialog is isolated to MegaMek while the base components all have MekHQ versions that are in use (hence the seemingly unused AbstractValidationButtonDialog).

Also, this would best be discussed over Slack, not on GitHub.

**Comment by mjog** [comment]
Hmm, but `PlayerSettingsDialog` and `PlanetaryConditionsDialog` have both been revamped for 0.49, and both extend CientDialog? Sounds like the should be moved to AbstractButtonDialog from what you are saying?

> Also, this would best be discussed over Slack, not on GitHub.

Sorry, I don't do proprietary chat protocols, especially ones that only have Electron clients.

What's wrong with discussing it here though? At least it's publicly archived. If this is a conversation you've already had, I would have been able to find it if it was done on Github in the first place.

**Comment by Windchild292** [comment]
The Base Components are also new in 0.49, which can be easily search up.

GitHub is not designed for conversations and thus is not as good a place to discuss.

**Comment by Windchild292** [comment]
I'm closing this as it's not an issue nor project, but rather expanded functionality in a setup that will slowly be implemented over time as new components are added.
