### ISSUE TITLE
Update logging implementation

### ISSUE THREAD

**Issue by mjog** [MegaMek/megamek#3107]
MM is currently using a combination of Log4j 1.2 which is obsolete, no longer supported, and doesn't integrate with other logging frameworks, and a custom logging implementation that, from reading comments in the source, is supposed to be removed anyway at some point.

Any objections for pulling both out and switching over to a logging bridge like SLF4J or Log4j2? Any preferences? If not, I'll go with SLF4J since it's a pure bridge, based on the [advice in this article](https://www.marcobehler.com/guides/java-logging).

**Comment by Windchild292** [comment]
The custom logging implementation is legacy (System.out, System.err, and Exception::printStackTrace mainly). MegaMekLab and MekHQ are both fully swapped over, but nobody has gotten around to finishing it in MegaMek.

As for doing a swapover, that would be best to discuss on our Slack

**Comment by Windchild292** [comment]
This would have better been explained as:
"MegaMek is using an extremely outdated and unsupported logging library in Log4j 1.2, and would best be migrated to a more modern setup."

I've migrated everything Log4j1 and some of the legacy logging to Log4j2, after learning just how outdated Log4j1 is and the issues that it can cause. I'm now going to slowly handle the remaining legacy logging, with the goal of removing the legacy logger before our next stable release.
