### ISSUE TITLE
RFE - "Nobody here but us Princesses" - option to end game when all human-controlled players are down

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#3109]
It was noted on the Discord that, when victory checking is switched off and there's more than one Princess in play, once all human-controlled units are down, the bots can cycle through phases and turns too swiftly to interrupt them with a '/victory' command.

One suggestion was to add an option to Game Options that, once all remaining players with units (either on table, or due to arrive through delayed deployment) are bot-controlled, would require an interactive 'Done' from a human at the end of each turn to continue. This would mean that the game could then be ended with a console command at that point, or alternatively reinforcements could be loaded from a MUL (so e.g. the Princesses could continue fighting for a couple of turns before more human-controlled forces arrive). This would obviously require the server to be able to differentiate between human and bot players.

This would need to be a toggle option, so that @rjhancock (and others) could continue running the multi-Princess load testing, but should probably default to 'checked'.

**Comment by Windchild292** [comment]
Duplicates #2768
