### ISSUE TITLE
Rendering change for Depth 0 Water with other terrain between 0.48.0 and 0.49.3?

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#3126]
Windows 10
Java OpenJDK 11

It appears that there has been a change in the order of graphics rendering between 0.48.0 and 0.49.3.

In 0.48.0, Rough terrain combined with Water 0 would result in the the water being rendered 'above' the base terrain type, with the 'rocks' of the Rough terrain being rendered on top of the 'water', making it look like the rocks are protruding through the water. In 0.49.3, the 'water' is now rendered 'above' the 'rocks.

**0.48.0 Rough + Water 0**
![20210830-Rough+Water0-48 0](https://user-images.githubusercontent.com/26851644/131387997-2d90522d-a8c0-44b5-9d5f-8e5e97037397.png)

**0.49.3 Rough + Water 0**
![20210830-Rough+Water0-49 3](https://user-images.githubusercontent.com/26851644/131388025-fcaa26d3-e448-4c93-a357-0f31055c2336.png)

A similar rendering change has affected the combination of Swamp with Water 0 - in 0.48.0, the 'swamp' would render 'above' the 'water', resulting in green terrain with blue veins through it. In 0.49.3, the 'water' is rendered 'above' the 'swamp', obscuring it.
(See also the same effect on hexes that are Mud + Water 0 in the same screenshots.)

**0.48.0 Swamp + Water 0**
![20210830-Swamp+Water0-48 0](https://user-images.githubusercontent.com/26851644/131388195-f777fa75-c36a-4c85-be09-c09c62be7cd6.png)

**0.49.3 Swamp + Water 0**
![20210830-Swamp+Water0-49 3](https://user-images.githubusercontent.com/26851644/131388235-3ea06deb-5da7-47d9-b88b-04dded1e0ea5.png)

See examples above.

This makes it harder to distinguish Water 0 from Water 1+. (Additionally, I think the graphics looked better with the water rendering 'below' the superior terrain sprites.) If this is a side-effect of the new 'water edges' rendering, fair enough!

**Comment by Windchild292** [comment]
@SJuliez?

**Comment by SJuliez** [comment]
I believe this is because water is now added through a single include file rather than in the tileset itself, as it's now many images instead of one per depth. I can possibly recreate the old behavior but have to look into it.
