### ISSUE TITLE
[RFE] Add keybind for zooming map, please

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#3129]
At present, map zoom is handled with the mousewheel or the **View** menu.
There is no keyboard shortcut for zooming in and out quickly on the map.
The [CTRL]+[+] and [CTRL]+[-] combinations zoom the GUI font size in the menu bar, which makes sense for them being captured by the Java GUI handler.

Would it be possible to add a keyboard shortcut to zoom the map in and out, as an alternative to the mousewheel? (I use a trackball with my laptop, for example, and it would be a lot easier to be able to zoom the map in and out with the keyboard rather than using the drop-down menu.)

I'm not sure if [SHIFT]+[CTRL]+[+] and [SHIFT]+[CTRL]+[-] are reserved key combinations, but if not, they might be suitable?

(I had a look at Client Settings, but I couldn't see anything relevant. If I've missed it, apologies.)

**Comment by SJuliez** [comment]
Is part of one of my current PRs.

**Comment by SimonLandmine** [comment]
Woo-hoo!

**Comment by Windchild292** [comment]
Part of #3000
