### ISSUE TITLE
Altitude bombing: Cannot bomb more than one hex.

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/megamek#313]
Using the daily MekHQ build number 136. Related to the fix in #133
When trying to target a second adjacent hex I get 

> attack already declared against another target

user test
[altitudebombing.sav.gz](https://github.com/MegaMek/megamek/files/419681/altitudebombing.sav.gz)

**Comment by arlith** [comment]
Yes, fixing #133 made it so you couldn't attack multiple hexes.  I added an exception for altitude bombing.
