### ISSUE TITLE
RFE - Please add player's BV total in the Select Units screen in the lobby

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#3134]
With the Lobby changes in 0.49.3, it's no longer possible to see the player's BV total while selecting units.

Please can the player's BV total be shown next to the player name in the 'Player list' on the 'Select Units' screen - it's very usefull when putting forces together in MM, rather than importing them from MekHQ, and also means the total can be seen when saving an .mul file (helpful as I include the BV total in the file name).

(I appreciate that it can be seen on the **Team Overview** tab, but that is a) a click away and b) only works if you are the only player on your team.)

Thanks!

![image](https://user-images.githubusercontent.com/26851644/132092944-e75f3915-0adb-489b-91a0-eeb87188732c.png)

**Comment by sshagent** [comment]
Yes please Devs.  Greatly appreciate your time on megamek but the BV totals does seem like it should be a main 'in your face' number.  I realise its a click or other screen away but in the main focus would be great

**Comment by Windchild292** [comment]
Fixed by #3149.

**Comment by sshagent** [comment]
Much appreciated guys
