### ISSUE TITLE
0.49.3 - Shadow rendering darkening most buildings by rendering 'on top'

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#3135]
MegaMek 0.49.3 (MekHQ version)
Windows 10
Java OpenJDK 11

It appears that shadows on 0.49.3 are being rendered 'on top of' some buildings, making them appear very dark compared to previous versions of the game. This appears somewhat inconsistent, but appears to occur most often with Medium or heavier buildings, and with buildings of Height 3 or more - but also affects Light buildings adjacent to Medium buildings or Height 3 buildings.

With shadows ...
![image](https://user-images.githubusercontent.com/26851644/132093479-3ad66013-bc91-49c7-9b60-d4f9645faa74.png)

Without shadows ...
![image](https://user-images.githubusercontent.com/26851644/132093517-a975ddb6-3ac1-4f6e-9438-c32e25be18a5.png)

**Comment by HoneySkull** [comment]
Looks like from the pictures, it's buildings on top of pavement that are rendered incorrectly.

**Comment by SimonLandmine** [comment]
> Looks like from the pictures, it's buildings on top of pavement that are rendered incorrectly.

Ooh, good spot! [FX: Sound of an embarrassed man kicking himself]

**Comment by SJuliez** [comment]
Yes, that is the reason. The problem is (again) that I would need to upgrade the tileset image retrieval to be able to handle the images better when there is more than one terrain element in a hex. I could maybe find a solution with the current way of things but its all stopgap.
