### ISSUE TITLE
[0.41.21 : Error] Red Hot Molten Lava PSR

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#315]
Using a bridge to cross over Lava hexes causes PSR check message to appear. No rolls were actually made. Savegame attached.
[Red Hot Molten Lava PSR.sav.gz](https://github.com/MegaMek/megamek/files/424096/Red.Hot.Molten.Lava.PSR.sav.gz)

**Comment by arlith** [comment]
Man, I failed twice on properly putting the issue # in the commit message...  That was meant to be #316.

**Comment by arlith** [comment]
Looks like hte issue here is that some code got missed in a previous update.  It was using `Entity.getElevation` to determine if the Entity was above the lava or not.  The check for crust was properly using `MoveStep.getElevation`.  All I had to was change from `Entity` to `MoveStep`.
