### ISSUE TITLE
Weapon Selection Pane HiDPI Scaling Issue

### ISSUE THREAD

**Issue by Algebro7** [MegaMek/megamek#3151]
### Environment
0.49.3 (Bundled with MekHQ)

Arch Linux/KDE Plasma/X11

OpenJDK 11.0.12

4k monitor with 150% global scaling set in KDE system settings

### Description
The scrollable weapon list when choosing which weapons to fire does not expand properly with a 4k screen and 150% global scaling, at least on my machine. There is only enough vertical space in the pane to show 3 weapons at a time, which makes it difficult to see the weapons available and also scroll (it's easy to scroll past weapons accidentally). I've attached a screenshot below:

![weapon_list](https://user-images.githubusercontent.com/5447759/132992617-6434ac57-80ac-49e2-a330-aeec05d429cf.png)

I think it may have something to do with the font size/text being scaled by the system settings, but the actual box not adjusting for it. Ideally the box would adjust as well to accommodate the larger text.

**Comment by Algebro7** [comment]
Not sure if it's related, but here are some more graphical glitches from the battle record pane that I don't remember seeing on my old 1080p monitor:

![battle_record](https://user-images.githubusercontent.com/5447759/133001623-760b82bb-a214-4e65-aa60-5defde1123a8.png)

**Comment by Windchild292** [comment]
They are not related, and there's a MekHQ issue open for it.

**Comment by kuronekochomusuke** [comment]
corrected by #3983
