### ISSUE TITLE
Issue: Mini Map Graphics Errors and Repaint Glitch

### ISSUE THREAD

**Issue by HoneySkull** [MegaMek/megamek#3153]
### Environment
Starting MegaMek v0.49.3 ...
Today is 2021-09-13
Java vendor Eclipse Foundation
Java version 11.0.12
Platform Windows 10 10.0 (amd64)
Total memory available to MegaMek: 1,048,576 kB

### Description
Setting up a simple test scenario with an Archer and a VTOL on a single or double map, I bring up the mini map and start clicking the zoom + and zoom minus and center arrow button (green bar below the minimap).  Sometimes when clicking the green bar toward the left or right edge, the mini-map is replaced with some graphics from elsewhere on the screen.  You can click and scroll on the mini map, but instead of repainting the mini map, other background graphics are painted.

![MiniMap](https://user-images.githubusercontent.com/83041327/133176294-dfdeecba-dfd4-4f91-822f-ad4f3251bffd.png)
![MiniMap2](https://user-images.githubusercontent.com/83041327/133176302-55a94e76-6a0c-4996-9ccd-41bf24a722b3.png)
![MiniMap3](https://user-images.githubusercontent.com/83041327/133176303-4ca96486-2079-46f3-8b89-d5fdbbd51c05.png)

### Files
[megameklog.zip](https://github.com/MegaMek/mekhq/files/7158181/megameklog.zip)

**Comment by SuperStucco** [comment]
I've had this come up as well.  For reference, it seems to malfunction like this more when on the second monitor; I can drag it back to the primary monitor and it will repaint correctly.

I've also noted the bad graphics happen more frequently when the outline for the main window area would exceed the minimap bounds.  If that border is kept inside the minimap bounds, it usually repaints correctly.
