### ISSUE TITLE
0.49.3: Interaction with server in Lobby triggers "Done"

### ISSUE THREAD

**Issue by mhjacks** [MegaMek/megamek#3166]
### Environment
What version of MegaMek does your issue apply to?  0.49.3, bundled with mekhq
What operating system are you using?  Linux - Fedora 34
What java version are you using?  Java version 11.0.12

### Description
Interacting with the server in the Lobby (e.g. clicking on the text bar and typing "/who<enter>" triggers the Done button, which in my case started the game.  This is a problem when, for example, trying to load games in the lobby or kick players in the lobby

### Files
[megameklog.txt](https://github.com/MegaMek/megamek/files/7229904/megameklog.txt)

**Comment by HoneySkull** [comment]
Interesting.  Is your 'Done' button associated with any hot-key?  (i.e. when you type /who and hit 'enter')?   Wondering if hitting the enter key triggers 'Done' and the chat.... does it happen with any other commands?

**Comment by mhjacks** [comment]
It actually works this way whenever I hit "enter" in the bottom server text interaction space (e.g. /list, /load etc).  The command is not sent to the server (the text stays in the chat window) and the "Done" state is toggled instead.  I do not have Done associated with any hotkey that I'm aware of (I don't modify the default hotkeys)

**Comment by mhjacks** [comment]
I can get the expected behavior (sending text in the chat line to the server) by using Alt+Enter, which does not toggle the "Done" state (just checked this)

**Comment by mhjacks** [comment]
Actually it looks like any press of "Enter" while the lobby screen has focus toggles the "Done" state - I checked that against hovering over a unit in the unit list.  Is this by chance connected to #3102 in some way? (I get that they are different issues, but possibly have a common root cause in how the Lobby code has been refactored?)

**Comment by SuperStucco** [comment]
Side note - I've noticed something similar when editing hex notes while in game i.e. anything that's a hotkey will do that action, even though I'm trying to type in the notes box.

**Comment by SJuliez** [comment]
Please check if you have Enter bound to the "Done" action in View->Client Settings->Key Binds (you can do this in the main menu outside of a game) like this:
![image](https://user-images.githubusercontent.com/17069663/134985448-5e36f2dc-70e4-4a37-ba95-c43c417e489e.png)
If it is set like this it will indeed trigger the Done button all the time. It should be set to Ctrl-Enter by default but if it isn't, try changing it. Other than that I have no idea what could trigger that behavior, at least not if it happens consistently.

**Comment by mhjacks** [comment]
You are right, it was sent to bare "Enter" by default.  I've changed it to Ctrl+Enter.

**Comment by HammerGS** [comment]
@mhjacks safe to close this as fixed.

**Comment by mhjacks** [comment]
Agreed.
