### ISSUE TITLE
Feature Request: Force Icons and Unit Size

### ISSUE THREAD

**Issue by txsoldier94** [MegaMek/megamek#317]
Would it be possible to separate the echelon/unit size designator from the unit icons, and make that something that could be added on?  That would reduce the number of icons necessary for any given force.

Apologies if this has already been addressed.

**Comment by arlith** [comment]
You're referring to force icons in the TO&E screen in MHQ, yea?  I think this should be a MHQ feature request.

**Comment by txsoldier94** [comment]
Ah...yes. Should I resubmit there?

Sent from Yahoo Mail on Android 
 
  On Thu, Aug 18, 2016 at 20:09, Nicholas Walczak<notifications@github.com> wrote:   
You're referring to force icons in the TO&E screen in MHQ, yea? I think this should be a MHQ feature request.

**Comment by arlith** [comment]
Yea, that would be easiest.
