### ISSUE TITLE
[RFE] Allow AMS to engage Capital Missiles

### ISSUE THREAD

**Issue by LilyFromSangvisFerri** [MegaMek/megamek#3182]
According to StratOps page 97, under the Advanced Point Defense Weapons rule, AMS bays on DropShips, WarShips, JumpShips, and Space Stations are able to engage Capital Missiles, and if inflicting enough total damage either add a to-hit penalty or outright destroy the incoming Capital Missile. MegaMek doesn't seem to actually make use of this part of Advanced Point Defense Weapons, and even in testing with multiple bays of 30 AMS per bay, none even so much as engage the missiles at all (no entry in the game's 'log' of attacks nor any ammo expended).

Relevant Rules Excerpt (Page 97, Strat Ops):
"Capital Missiles: Capital (and sub-capital) missiles, whether standard or tele-operated, do not have their damage reduced by point defense bays. Instead, if not destroyed by point defense fire (which occurs when they sustain a number of points of capital scale damage equal to their own Attack Values), capital missiles suffer a +1 to-hit penalty for each point of capital-scale armor damage they sustain from passing through defended hexes of any point defense weapon/bay that engages them. Only an AMS bay can affect a capital missile; a single AMS has no effect. Once all the damage from an AMS bay has been determined, convert it to capital-scale damage and apply it to the missile to inflict the to-hit modifiers described above."

I'd very much appreciate it if this capability was added, as right now AMS on WarShips or even larger DropShips feels a bit useless given how little threat even massed LRM/SRM/ATM fire presents to the bigger and tougher units.

**Comment by gsparks3** [comment]
What version was this tested on? I have an example of this working in a 0.48.0 savegame (attached below). If this is a different version, probably something broke and needs to be fixed. If this is the same version, some careful comparison may be needed to determine what makes the difference.

[capitalAMS.sav.gz](https://github.com/MegaMek/megamek/files/8458055/capitalAMS.sav.gz)

Reproduction steps:
1. Open attached savegame, joining as "Ian Cameron"
2. Hit "Done" on all units (enemy units are already finished declaring fire)
3. Observe that in the firing phase, the enemy capital missiles are shot down by the AMS bays on the targeted unit

**Comment by Logion567** [comment]
i too was having the same issue. then I discovered that the issue was an unchecked rule
![Capital AMS rules](https://user-images.githubusercontent.com/98195429/162814534-623d3baa-3621-4fec-83e5-239d475deef8.png)

**Comment by Windchild292** [comment]
My bad on tagging this an enhancement, didn't know it was an option. Closing this as already implemented.
