### ISSUE TITLE
49.3 : Error saving games and when trying to load games

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#3184]
I was playing megamek through mekhq and i tried saving and loading a game.

No error message popped up in the client when i saved the game, but I noticed this in megamek.log : 

```
10:08:10,073 ERROR [megamek.server.Server] {Connection 0} 
saveGame(), line 1234 : Unable to save file: savegames\a.sav
com.thoughtworks.xstream.converters.ConversionException: No converter available
```
A similar error was created when I attempted to load the game through mekhq.

[megameklog.txt](https://github.com/MegaMek/megamek/files/7290372/megameklog.txt)

When loading the save game, the game doesnt load at the last turn, i just get brought to the lobby screen. The units in the lobby are not loaded correctly either. It does not load my units at all and it loads units that have been destroyed...all the units loaded in the lobby are at in mint condition at the very start of the game. Trying to load the autosave results in the same problem, i cannot actually load the save at the start of the last turn, it just brings me to the lobby.

If launching megamek standalone, i get the same issue when saving games and when trying to load the save game, it just tells me "error loading save game" (instead of bringing me to the lobby screen).

Example of a broken save file : 

[test.sav.gz](https://github.com/MegaMek/megamek/files/7290440/test.sav.gz)

**Comment by Windchild292** [comment]
The suite is only dev tested up to 11, and I've clarified our maximum supported version as 11 in our wiki.

We cannot currently test past 11 due to a Gradle recursion, so no support will be present until that is resolved
