### ISSUE TITLE
Skin-of-Teeth ejection allows ejection on a critical hit to the cockpit, despite TacOps saying otherwise

### ISSUE THREAD

**Issue by BlueNexus** [MegaMek/megamek#3227]
### Environment
0.48.0

### Description
Not first-hand information, but apparently Mishra noted that skin-of-teeth ejection currently allows the pilot to eject if the cockpit slot is critted. However, TacOps (2nd edition) states on **page 165, Destruction of Head Location** that the automated ejection rule on head destruction does not apply in the event of a crit to the cockpit slot, in which case the pilot is still killed.

**Comment by NickAragua** [comment]
Fixed with PR #3248
