### ISSUE TITLE
Corrected Valkyrie VLK-QW5 mtf

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#3234]
v.49.3

Fixed mtf as per errata posted here: https://bg.battletech.com/forums/errata/record-sheets-3085-unabridged/msg276085/#msg276085

[Valkyrie VLK-QW5.zip](https://github.com/MegaMek/megamek/files/7479464/Valkyrie.VLK-QW5.zip)

**Comment by HammerGS** [comment]
Fixed in 49.5
