### ISSUE TITLE
0.49.4: VTOLs can get stuck in swamp

### ISSUE THREAD

**Issue by mhjacks** [MegaMek/megamek#3237]
### Environment
Fedora Linux 35, openjdk 11.0.13, MegaMek (from MekHQ bundle) 0.49.4

### Description
VTOL gets stuck in swamp.  Seems like it should...not be able to get stuck.  (At least not flying over it)

**Comment by mhjacks** [comment]
[stuckvtol.sav.gz](https://github.com/MegaMek/megamek/files/7491258/stuckvtol.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/7491261/megameklog.txt)

**Comment by mhjacks** [comment]
Maybe an exclusion in getBogDownModifier in Entity.java for VTOL movement mode(s) might be better?  Or maybe the isHoverOrWIGE check should also include an isVTOL check?

**Comment by mhjacks** [comment]
OK, looking at TacOps p.51 and 62, my reading is that VTOLs that *end* their turn *on the ground* in a swamp hex are automatically bogged down (same with WIGEs).

That would suggest to me that a better adjustment would be something more like this:

If (Movement is VTOL or WiGE or Aero) AND (is last step) AND (elevation is 0) then
    auto-fail

Am I reading that right, do you think?

**Comment by NickAragua** [comment]
Yeah, that's about right. I was just regression testing the other "workflows" in a pull request I'm working on to address this.
