### ISSUE TITLE
3.32 Attack on Infantry crosses building Exterior Wall at Range 0

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#324]
At range 0, some infantry units were unable to attack other infantry in the same building. Other units had no problem attacking from range 0 or from adjacent hexes. Changing hexes did not alleviate the problem, so I don't think its a map artifact. I got this message "Attack on Infantry crosses building Exterior Wall." 

I've attached my game log and screenshots. 

[megameklog.txt](https://github.com/MegaMek/megamek/files/440766/megameklog.txt)
![mm infantry 3](https://cloud.githubusercontent.com/assets/19868605/18028973/cd0f78a8-6c58-11e6-959d-1e3e9df9adad.PNG)
![mm infantry 1](https://cloud.githubusercontent.com/assets/19868605/18028971/cd0ba9bc-6c58-11e6-977f-32add329eee3.PNG)
![mm infantry 2](https://cloud.githubusercontent.com/assets/19868605/18028972/cd0ecfa2-6c58-11e6-9734-4db4a7083913.PNG)

**Comment by arlith** [comment]
Could you attach the saved game that your screenshots are from?

**Comment by VampireSeraphin** [comment]
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/440772/autosave.sav.gz)

**Comment by arlith** [comment]
Thanks for the savedgame.  Turns out  this is working as intended.  The important bit of rules come from TW pg 175, first paragraph in *Combat within Buildings*:

>Units fighting in the same building (including units occupy-
>ing different hexes in a multi-hex building) must do so accord-
>ing to the following special rules. Units on a building’s roof use
>the rules given above under Attacking Units Inside Buildings.

The Jump Platoon (Rifle) is on the roof of the building, so they use the "attacking units inside buildings" rules, and hence can't shoot at the infantry directly.

**Comment by arlith** [comment]
I can see how this might be a bit confusing, but I also can't think of a great way to communicate this to the user.

**Comment by VampireSeraphin** [comment]
Whups, must have forgotten to have them move down inside the building after a jump somewhere.

I guess we know that feature works then.

**Comment by VampireSeraphin** [comment]
Can you add a check to change the message to "blocked by roof" or "blocked by wall" as appropriate?

**Comment by VampireSeraphin** [comment]
Or perhaps "target on different level of building"

**Comment by arlith** [comment]
I could easily change the message to be ""Attack on infantry crosses building exterior wall/roof."  I'm kind of reluctant to check if it's through a wall or roof, mostly because I'm lazy.  I don't immediately see a foolproof check for this situation.

**Comment by VampireSeraphin** [comment]
Changing the message to wall/roof would at least remind a user to check and see what level their unit is on if they can't see an exterior wall. You should make that change to the wording.

**Comment by arlith** [comment]
Change made in d7aaf4f.
