### ISSUE TITLE
Corrected Basilisk (Quad) B mtf

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#3242]
v.49.3

Unit had too much armor, even if underweight. No official errata for the unit exists at this time, so it should be using its armor value as presented in the WoRS record sheets.
Goes into the ProtoMechs/WoR folder.

[Basilisk ProtoMech (Quad) B.zip](https://github.com/MegaMek/megamek/files/7508888/Basilisk.ProtoMech.Quad.B.zip)

**Comment by HammerGS** [comment]
Our errata was based off DarkISI's comments here - https://bg.battletech.com/forums/errata/the-wars-of-reaving-supplemental/msg572389/#msg572389

**Comment by AlphaSled** [comment]
Only the overweight fixes were certified as official errata, as per this post here: https://bg.battletech.com/forums/ask-the-writers/protomechs-from-the-wars-of-reaving-supplimental/
