### ISSUE TITLE
Saved games cannot be loaded

### ISSUE THREAD

**Issue by kernhe** [MegaMek/megamek#3244]
[megameklog.txt](https://github.com/MegaMek/megamek/files/7514202/megameklog.txt)
### Environment
* MegaMek 0.49.5
* Linux x86_64
* openjdk 17 2021-09-14

### Description
I use mekhq to generate a battle. Any saved game cannot be loaded later. It just states: "Error: unable to load game file"

### Files
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/7514175/autosave.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/7514202/megameklog.txt)

**Comment by Windchild292** [comment]
JDK 17 is not supported, JDK 11 is our maximum supported version.

**Comment by kernhe** [comment]
Thanks for the fast response! My bad. ... will check and come back

**Comment by kernhe** [comment]
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/7514793/autosave.sav.gz)
Switched to openjdk 11.0.11 2021-04-20 and still have the same behavior. 

in the terminal mekhq states:
```
[megameklog.txt](https://github.com/MegaMek/megamek/files/7514788/megameklog.txt)
```
Attached log and save for same battle started from mekhq using jdk11

**Comment by Windchild292** [comment]
Reopening, and this is one I'm handling

**Comment by kernhe** [comment]
Checked myself. Thanks for fixing this bug!
