### ISSUE TITLE
Server::transmitPlayerUpdate ConMod

### ISSUE THREAD

**Issue by TalRaziid** [MegaMek/megamek#3245]
### Environment
0.49.5, MHQ MegaMek. Windows. Java vendor: Eclipse Adoptium, Java version: 11.0.13

### Description
When ending the turn for the "Taser Lion" custom Crab, MM will not advance, its stuck on 'your turn to move'. Have attempted several reloads to get around it but its always the same unit that it freezes on.

### Files
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/7517828/mekhqlog.txt)
[megameklog.txt](https://github.com/MegaMek/megamek/files/7517829/megameklog.txt)

**Comment by Windchild292** [comment]
Save file and customs are needed too Tal...

**Comment by TalRaziid** [comment]
> Save file and customs are needed too Tal...
Was leaving work at the time nerd 😛 
[customs.zip](https://github.com/MegaMek/megamek/files/7523288/customs.zip)
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/7523289/autosave.sav.gz)
[1.sav.gz](https://github.com/MegaMek/megamek/files/7523291/1.sav.gz)
