### ISSUE TITLE
[49.5] Battle map forced to the left when in fullscreen

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/megamek#3251]
Megamek 49.5 (started from MekHQ)
Win 10

When the unit display is undocked and you put the battle map in fullscreen mode, there's an empty area to the right and the map gets pushed left, like so:

![image](https://user-images.githubusercontent.com/67933202/141665572-1bb64d0d-40d4-4612-857c-671246bab547.png)

It's problematic because the empty space occupies more room than the docked version of the display, so simply moving stuff to the right doesn't completely solve the issue.

**Comment by Windchild292** [comment]
The default location is to the center now, as is preferable for any implementation of a dialog.

Further, this is based on the individual board setup, and not an issue when it comes to MegaMek.

This will not be handled for these reasons.
