### ISSUE TITLE
Request to add missing quirks to Torrent Heavy Bomber

### ISSUE THREAD

**Issue by Gribbly1** [MegaMek/megamek#3253]
The 'Torrent Heavy Bomber' unit is missing the quirks 'Atmospheric Flyer', 'Poor Performance' and 'Internal Bomb Bay' as per TRO Vehicle Annex Revised p124. Please can you add these.

Many thanks.

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/6aba8e3ed5b0ace2f5001389f68b2833a286d336
