### ISSUE TITLE
49.5 Random MM exiting mid battle (MHQ)

### ISSUE THREAD

**Issue by manstrokemole** [MegaMek/megamek#3254]
What version of MegaMek does your issue apply to?  **49.5** **DEFEND FACILITY FROM MEKHQ**
What operating system are you using?  Windows, Mac, or Linux? **WINDOWS**
What java version are you using?  If unsure it will state your java version at the top of the megameklog.txt file. **11.0.13**

### Description
**Will close down MM mid battle for no apparent reason, can happen in big battles with lots of units present, or, as in this case, very few units present**

### Files
I think the playername might be Damaged Goods?

[megameklog.txt](https://github.com/MegaMek/megamek/files/7538149/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/7538152/mekhqlog.txt)
[Damaged Goods30540523.cpnx.gz](https://github.com/MegaMek/megamek/files/7538153/Damaged.Goods30540523.cpnx.gz)

**Comment by Windchild292** [comment]
I believe we have a fix for 0.49.6.

In the meantime, increase your RAM assignment in the mekhq.l4j.ini to 2048, or 2GB
