### ISSUE TITLE
PPC Capacitors, Clan 'Mechs, and BV

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#3257]
v49.3

Clan 'Mechs with standard/XL engines appear to be counting as Inner Sphere 'Mechs for BV purposes when mounting PPC Capacitors---in other words, Clan CASE isn't being taken into account when this specific scenario is at play.

My short tests suggest that this might be a fringe case; other explosive weapons don't seem to have their BV affected in any strange ways when put on a Clan chassis.

**Comment by HammerGS** [comment]
Units in question are from Rec Guide 21 Kontio and Regent A. For any dev wanting to trouble shoot this I have the MTF files. For general use the files will be available after the 60 day moratorium.
