### ISSUE TITLE
Water tiles are not shown

### ISSUE THREAD

**Issue by Hagustalda** [MegaMek/megamek#3258]
### Environment
MegaMek v0.49.5
Platform Linux 5.14.17-xanmod1 (amd64)
openjdk 17 2021-09-14

### Description
Water tiles are not properly shown on maps. 
Seems like Megamek cannot load the image files for water.

log file snippet:

_Loading atlas: data/images/hexes/Incline/Default/Default_atlas.png
Trying to load image for a non-existent file! Path: data/images/hexes/Structured_water/SaxarbaWater_X_1_D1_45_result.png_

I checked the path and the folder name "Structured_**w**ater" is spelled like this on my system:
"Structured_**W**ater" (uppercase W in Water)
Since this is Linux, paths are case sensitive.

Renaming the folder to "Structured_water" (lower **w**) fixed the problem and the water tile was properly shown in the game again.

### File
[megameklog.txt](https://github.com/MegaMek/megamek/files/7547079/megameklog.txt)

**Comment by Windchild292** [comment]
The fix has been merged for our next release
