### ISSUE TITLE
Changing climb mode affects movement

### ISSUE THREAD

**Issue by ilmarsL** [MegaMek/megamek#326]
There are some inconsistencies in the way how climb mode affects movement. Changing climb mode makes it impossible to enter adjacent water hex unless you press Esc and re-plot the movement. I tested it only with water hexes but it might affect other hexes too.
Here is an example to better illustrate the problem (savegame is attached):

![climb_mode_problem](https://cloud.githubusercontent.com/assets/10614012/18082272/be71596a-6ea6-11e6-8713-c5fee93db20a.jpg)
[climb_mode_problem.sav.gz](https://github.com/MegaMek/megamek/files/444372/climb_mode_problem.sav.gz)

Steps to reproduce:
1. Try to enter hex 1204, path should be yellow (climb mode defaults to “Go Thru”).
2. Press Esc
3. Change climb mode to “Climb Up”.
4. Change climb mode back to “Go Thru”. Click to move to hex 1204, path is now grey.
5. Press Esc and then try to enter hex 1204 again, now it becomes yellow again.

**Comment by arlith** [comment]
Units should be allowed one forward movement regardless of MP, which can be
considered first-step amnesty.  Some move steps, such as changing the climb
mode, should not remove this first-step amnesty.  I added a clause into the
firstStep computation to consider this.
