### ISSUE TITLE
Request for Vector VTOL equipment slot corrections

### ISSUE THREAD

**Issue by Gribbly1** [MegaMek/megamek#3260]
The 'Vector (EW)' variant has TAG mounted in the rotor location. As per p71 Tactical Operations Errata v3.03, this is not allowed.

![image](https://user-images.githubusercontent.com/55139229/142140719-027a5372-b4ef-46fe-bc24-aa3122351dfa.png)

Please change the unit file so that the TAG is Front mounted.

The 'Vector (Scout)' variant has TAG mounted in the Body location. As per p107 Tech Manual, equipment with a firing arc may not be mounted in the Body location.

![image](https://user-images.githubusercontent.com/55139229/142141078-9d204011-1a11-4b23-9a48-d05a69407040.png)

Please also amend this so that the TAG is front mounted.

Many thanks.

**Comment by HammerGS** [comment]
Fixed with https://github.com/MegaMek/megamek/commit/7eb948c0ff9b3a977ac8ad0b20338300f5ae9151
