### ISSUE TITLE
[49.5] BattleArmorTROView NPE Reached from AbstractUnitSelectorDialog

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#3262]
### Environment
Standalone MML v49.5
Windows 10
Java 11.0.13

### Description
When using the MML unit search ("Load Existing Unit") and selecting certain units, logged NPEs and graphical glitches will occur. I specifically noticed this when viewing the Trinity Medium Battle Armor (Asterion Upgrade) [PPC], although it might affect other units as well.

Reproduction steps:
1. Open MML and click "Load an existing unit"
2. Select all unit types and enter "trinity" in the search box
3. Select the first of the search results (in my case the Asterion [MRR] variant)
4. Use the arrows keys to scroll down through the variants.
5. Observe the graphical glitch and logged NPE when reaching the variant specified above.
6. Continuing to scroll up and down, or manually clicking on the bugged variant, will cause further NPEs. 

### Files
[megameklablog.txt](https://github.com/MegaMek/megameklab/files/7560039/megameklablog.txt)

**Comment by Windchild292** [comment]
This can also occur in MegaMek, so I've transferred the issue

**Comment by Windchild292** [comment]
![image](https://user-images.githubusercontent.com/39067288/143138779-4cad4aee-0274-47e0-80e2-1da43e674a00.png)

I believe this is a data issue because of this, with changing the tech level of the BA so it isn't clan being the fix.

@HammerGS can you confirm.

**Comment by HammerGS** [comment]
I'd have to check the unit files but they are all older units, but showing as Clan BA Advanced is odd.

**Comment by gsparks3** [comment]
Did a quick sweep of battle armor designs to see if any others showed the bug - this or something similar appears to affect the Asterion Upgrade [PPC], the Oni [MRR], and Oni [PPC] variants, so check out the Oni suits as well as the Asterion. No other BA seemed to be affected.

**Comment by Windchild292** [comment]
https://github.com/MegaMek/megameklab/issues/1072, while a duplicate, has this logged using Log4j instead of System.out. I'd recommend using the logs from that over the log above.

**Comment by HammerGS** [comment]
Fixed the units in question and they don't cause the lock-up.  But the code causes a hard lock up and I suspect that will still need to be addressed.
