### ISSUE TITLE
Camo issues with ASF

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#327]
Camo does not seem to apply to ASF in 0.41.22 (MekHQ 0.3.32 package).  Attempted with set individual camo as well and same effect.  And also wonder if all the grey on that enforcer is a bug as well?

![image](https://cloud.githubusercontent.com/assets/16950832/18258876/eedc9db6-73a2-11e6-90b8-0b87c11cda17.png)

Player name: AFFSFSAC-2REG-2BN-ECO
[camobug.sav.gz](https://github.com/MegaMek/megamek/files/455752/camobug.sav.gz)

**Comment by arlith** [comment]
This is an issue in 41.22 but was fixed by the time of the experimental release.  It will be fixed for the next release as well (this is from unit icons not being true greyscale).

**Comment by scJazz2** [comment]
I swear to god I reviewed the reports before posting. I just missed it. Derp.
