### ISSUE TITLE
Super-Cooled Myomer not working

### ISSUE THREAD

**Issue by Flakanon** [MegaMek/megamek#3275]
### Environment
MegaMek v0.48.0 (launched as standalone)
Windows 10
Java version 1.8.0_311

### Description
**PREFACE:** I had started writing this note about SCM + XXL engines, but after testing, I could not even get it to work with Standard Engines (STD+SCM continues to produce 0/1/2 heat in testing, instead of 0/0/0)

**Original note:**
According to this answer from Xotl:
https://bg.battletech.com/forums/supplementary-rules/answered-io-super-cooled-myomers-and-xxl-engine
XXL Engines should have their extra movement heat negated by Super-Cooled Myomer.
In MegaMek, however, a unit with both items installed still causes 2/4/6 heat when Standing/Walking/Running.
These values should be 2/2/2.
(Or potentially 0/0/0 if "Standing Still" is considered a movement mode and therefore has it's heat negated... But that would not make as much lore sense since the first 2 heat is direct from the engine and not from the myomer.)

### Files
Reproduced in attached savegame with a custom Mek created with XXL+SCmyomer
(Turn 1: Standing, 2: Walking, 3: Running, producing 2/4/6 heat respectively)

Playername Joel
[XXL_and_SCmyomer_StillWalkRunTest_Example.sav.gz](https://github.com/MegaMek/megamek/files/7598629/XXL_and_SCmyomer_StillWalkRunTest_Example.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/7598635/megameklog.txt)

**Comment by HammerGS** [comment]
We only have these implemented for construction only.

**Comment by Flakanon** [comment]
Thanks for the quick reply.

**Comment by HammerGS** [comment]
Implemented with https://github.com/MegaMek/megamek/pull/4111
