### ISSUE TITLE
New public server

### ISSUE THREAD

**Issue by Delra** [MegaMek/megamek#3279]
Hello! I've just spun up a dedicated server and would like to have it added to the public server list. 
ipv4: 45.79.209.21
ipv6: 2600:3c02::f03c:92ff:fe3a:7803
port: 2346
version: 0.48.0
ram: 512
faction: magistracy of canopus

**Comment by HammerGS** [comment]
Thanks! We'll look at getting this added.

**Comment by rjhancock** [comment]
I'll try to get this added today. Thanks for helping get more public servers out there.

**Comment by rjhancock** [comment]
It's been added.

**Comment by Delra** [comment]
Thank you as well!
