### ISSUE TITLE
Illegal reflective access by com.thoughtworks.xstream.core.util.SerializationMembers

### ISSUE THREAD

**Issue by kernhe** [MegaMek/megamek#3280]
### Environment
Version: 0.49.6-SNAPSHOT
OS: Linux 64bit (Ubuntu)
Java: openjdk 11.0.11 2021-04-20

### Description
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.SerializationMembers (file:/[.......] /mekhq-0.49.6-SNAPSHOT/lib/**xstream-1.4.14.jar**) to method java.util.concurrent.CopyOnWriteArrayList.readObject(java.io.ObjectInputStream)
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.SerializationMembers
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by Windchild292** [comment]
This provides no information. I'd need the full logs (both MekHQ and MegaMek), MegaMek save, MekHQ campaign save, and customs.

I do have an idea, however. Are you trying to load a save from a previous version? That will cause a read error as we do not support migration in MegaMek.

**Comment by Delra** [comment]
This is a normal error when using XStream 1.4.14 in Java 9+, due to the changes with encapsulation.

**Comment by Windchild292** [comment]
Wait, I misread the message (there's two similar messages, one's actually an issue and the other is this)... it's a normal warning, no issues as described above.
