### ISSUE TITLE
0.49.5 Princess targeting unit rather than hex with Sniper cannon

### ISSUE THREAD

**Issue by Gribbly1** [MegaMek/megamek#3285]
Packaged MM version 0.49.5
Windows 10
Java version 11.0.13

![image](https://user-images.githubusercontent.com/55139229/144148544-ce04d3f6-638d-42c1-86a0-7b2400dc820a.png)

[megameklog.txt](https://github.com/MegaMek/megamek/files/7629675/megameklog.txt)

[autosave.sav.gz](https://github.com/MegaMek/megamek/files/7629676/autosave.sav.gz)

[fhcustom.zip](https://github.com/MegaMek/megamek/files/7629682/fhcustom.zip)

**Comment by Windchild292** [comment]
I'm not experienced with artillery, but either the message needs an update or there's a bug in targeting.

**Comment by Gribbly1** [comment]
What about snub cannons? It's hard to tell, as in that example Princess hit rather than missed.

**Comment by NickAragua** [comment]
Sniper Cannons are direct-fire weapons per TacOps:AUE page 97.
