### ISSUE TITLE
GUI "build custom RAT"

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#330]
I'd like to see a GUI system added that allows the user to create their own custom RATS. Something that builds and adds them automatically once you spec unit % weights + years, and lets AtB see the new RAT without having to get under the hood of the universe files.

**Comment by HammerGS** [comment]
Don't want to fully steal @neoancient thunder.  But he is working on very cool stuff.

https://github.com/neoancient/megamek/commit/27472d58bf4421ca96a7b6193692803b40542b6a

There have been previews posted in our https://megamek-public.slack.com site in the general discussion room.

**Comment by VampireSeraphin** [comment]
I don't have Slack fully setup yet. Can you give me the cliff notes?

**Comment by HammerGS** [comment]
@VampireSeraphin 

Log into Slack - https://megamek-public.slack.com join the general chat, after that it works like IRC.

**Comment by neoancient** [comment]
Custom RATs are pretty simple. Using them with AtB is more difficult, and a graphic interface would be helpful. I could see situations in which you might want to work with a specific set of units, and I plan to have my new dynamic generation system working side-by-side with the current one. But that's really a MHQ issue rather than MM.

**Comment by VampireSeraphin** [comment]
Yeah, I figured out how to write my own RATS, and getting them loaded in the universe file doesn't look to hard, just need to read through the instructions at the beginning of it. It's getting AtB to see them that I'm not sure about right now, so I'm contenting myself with modifying existing RATs since I know it can see the names properly.

Neo, Scjazz forwarded me a screenshot from Slack of what you've been working on. That looks pretty damn good. Can you manually adjust the weights or are they fixed is my only big question, the rest looked pretty clear.

**Comment by Dylan-M** [comment]
Closing, @neoancient I'm not sure what commit you added the RAT generator in... if you could tag it in here?
