### ISSUE TITLE
[49.5] Vehicle Lance Movement prevents full deployment of turrets

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#3306]
### Description
If the TacOps Vehicle Lance Movement game option is active, and a player attempts to deploy turrets at the beginning of the game, only a fraction of the turrets will successfully be deployed. The fraction seems to be related to the number chosen for "number of vehicles in a lance", e.g. if it is 4, only 1/4 turrets can be deployed, while if it is 2 then 1/2 of the turrets can be deployed.

Sometimes, in our campaign games, more turrets have become deployable later in the game, but I am uncertain of the cause of this. Possibly it is related to the previously deployed turrets being destroyed.

Reproduction steps:

1. Open the Megamek lobby and reset Game Options to defaults, then change Allowed Tech Level so turrets are available and activate TacOps Vehicle Lance Movement.
2. Add a number of turrets using the Unit Selector (I used 8 MG turrets).
3. Select a map with buildings to deploy the turrets on and Start Game.
4. Attempt to deploy all turrets. The game will end the deployment phase after a certain number of turrets have been deployed, but before all turrets have been deployed, and move to the next phase. No error appears in any of the logs.

**Comment by Tecmes** [comment]
Indeed I've had the same issue with 49.19. Can't say it's related to Vehicule LAnce moement though it WAS activated and the symptoms sounds exactly like the OP. 4 turrets, only 1 deployed; 8 turrets planned, 2 deployed. Then later again the same number, inexplicably as part of later deployement from  MY units.
