### ISSUE TITLE
[0.49.3] Infantry not able to make Swarm or Leg attack

### ISSUE THREAD

**Issue by mwberlindeu** [MegaMek/megamek#3318]
I was unable to order infantry on a swarm or leg attack although it should be possible of a mek and infantry is in the same hex. However I may also not enter the required commands properly.

**Environment**
Version 0.49.3
OS: Windows
JRE: 8 (Update 301)
Java version 15

Additional information: Java Version is taken from the log
CMD shows different version.

![image](https://user-images.githubusercontent.com/28268113/146251417-cea907dc-3d46-4b07-b951-414ea8a7ee5a.png)

**Files**
Game file for recreation of the problem
[Testgame.sav.gz](https://github.com/MegaMek/megamek/files/7722268/Testgame.sav.gz)

**Comment by Saklad5** [comment]
Conventional infantry needs anti-mech equipment to do that.

**Comment by Gribbly1** [comment]
No, they don't. Non anti-mech equipped conventional infantry can still make leg or swarm attacks with a skill of 8 as long as they aren't field gunners, mechanised or wearing encumbering armour.

**Comment by Saklad5** [comment]
> No, they don't. Non anti-mech equipped conventional infantry can still make leg or swarm attacks with a skill of 8 as long as they aren't field gunners, mechanised or wearing encumbering armour.

Ah, right.
