### ISSUE TITLE
[0.49.5] Pressing TAB no longer switches between direct and indirect fire mode

### ISSUE THREAD

**Issue by sshagent** [MegaMek/megamek#3322]
### Environment
Windows.  Megamek version = 0.49.5

### Description
TAB usually switches LRM between direct and indirect fire mode.  This vanished in one of the previous 0.49.x releases then returned...and now has gone again.  

### Files
This doesn't really need a save.  Fire up 0.49.5, deploy an Archer...in firing phase select LRM weapon and press TAB.  It does nothing.
The MODE button still works, but its no so efficient.

**Comment by Windchild292** [comment]
Won't fix, tab is reserved for accessibility.
