### ISSUE TITLE
Unit Window wont reopen

### ISSUE THREAD

**Issue by Krrast** [MegaMek/megamek#3324]
### Environment
MekHQ Megamek, nightly #613
Window
Java Version: 16.0.2

### Description
I closed the unit window, and was unable to reopen it. Typically I would reopen it by right clicking a unit and selecting View -> Unit. This does not bring up the unit window after closing. The window was not docked when closed. Saved the game, reloaded and the save game doesnt reload my units, I'll put that in another bug report. I've attached both the autosave and the Testing save games so you can see them both. Not sure if they will help the window issue or not.

### Files
Player Name: Black Hand
(Delete the above lines)
[megamek.log](https://github.com/MegaMek/megamek/files/7739812/megamek.log)
[Black Hand30760702.cpnx.gz](https://github.com/MegaMek/megamek/files/7739813/Black.Hand30760702.cpnx.gz)
[Testing.sav.gz](https://github.com/MegaMek/megamek/files/7739814/Testing.sav.gz)
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/7739815/autosave.sav.gz)

**Comment by Windchild292** [comment]
Java 16 is unsupported and may cause issues that we cannot otherwise find. Please immediately downgrade to Java 11 and retest to ensure this is valid

**Comment by Windchild292** [comment]
Given the bugfix for the unit window preferences since this point and the unsupported Java version, I'm closing this.
