### ISSUE TITLE
Saved game doesnt reload properly in MekHQs MegaMek

### ISSUE THREAD

**Issue by Krrast** [MegaMek/megamek#3325]
### Environment
MekHQ MegaMek
Windows 10
Java Version: 16.0.2

### Description
While working through another issue I saved my MegaMek game and attempted to reload.  I'm used to a loaded game going straight to the field of battle and having to reassign the bots.  This time it took me to the pre-drop lobby and loaded all the bot units but none of the player units. It did load me as the player. It also loaded a bot I had deleted (House Officer) since I took over the house officer unit, and assigned the unit to the bot. Attempted to reload the save a couple times, same issue. The log folder has MUL files for all the units except the player's.

### Files
[megamek.log](https://github.com/MegaMek/megamek/files/7739831/megamek.log)

Player Name: Black Hand
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/7739826/autosave.sav.gz)
[Testing.sav.gz](https://github.com/MegaMek/megamek/files/7739827/Testing.sav.gz)
[Black Hand30760702.cpnx.gz](https://github.com/MegaMek/megamek/files/7739829/Black.Hand30760702.cpnx.gz)

**Comment by Windchild292** [comment]
Java 16 is unsupported and the cause of this issue.
