### ISSUE TITLE
MegaMek closed log during review without input, then upon next interaction with UI it forced a disconnect, ending the game.

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/megamek#3327]
### Environment
0.49.5
Windows, Mac, or Linux? Windows 10
Java JDK 11.0.11.9-hots

### Description
MegaMek closed round log during end of round review without input, on next interaction with interface (attempting to pull log back up via menu), MegaMek disconnected me / closed that game. Occurred about round 3/4, slight sluggishness in this match.

### Files
[megameklog.txt](https://github.com/MegaMek/megamek/files/7741194/megameklog.txt)

**Comment by OrbMonky** [comment]
Interestingly, it didn't actually close the megamek client, just disconnected the game. I don't think I've seen that happen before.

**Comment by Windchild292** [comment]
Without a save and the remaining logs, the best I can do is fix the logged NPE around that time.... which I did in #3316.

There's a few other logged issues, but they are impossible to track down without the save.

Closing as fixed in #3316
