### ISSUE TITLE
Camo not being displayed on ASFs

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/megamek#333]
Attached is a MUL the 2 top entries are for Riever ASFs. Note how they are clear. The 2nd one has a specific camo selected but it does not display. If a game is started the ASFs will continue to be clear.

MHQ 0.3.32 and associated...

[New Sword.zip](https://github.com/MegaMek/megamek/files/467608/New.Sword.zip)

**Comment by BLOODWOLF333** [comment]
LIke this? https://github.com/MegaMek/megamek/issues/327
