### ISSUE TITLE
Torpedo Launchers not available for aerospace units

### ISSUE THREAD

**Issue by pokefan548** [MegaMek/megamek#3342]
### Environment
MegaMek Lab ver. 0.48.0, Windows 10

### Description
MegaMek Lab erroneously does not allow Torpedo Launchers (LRT/SRT) to be mounted on fighters (aerospace or conventional) or other aerospace units. Per TechManual p. 230-231, there is nothing precluding any aerospace unit from mounting Torpedo Launchers and, per Total Warfare p. 138, said weapons may be legally utilized so long as LOS is traced through at least Depth 1 water.

Fixed Wing Support Vehicles are exempt from this issue, and allow Torpedo Launchers to be added normally.

**Comment by pokefan548** [comment]
Exactly - torpedos may be fired _**into**_ a water hex of Depth 1 or greater. Torpedo bombs work similarly.

If at some point, LOS is traced through water of at least Depth 1, then the usage of Torpedo Launchers is valid. As far as the rules stipulate, this covers submerged to submerged, submerged to surface, and surface to submerged attacks. Or, essentially, if a Missile Launcher attack is invalid due to water, then the conditions are met for a valid Torpedo Launcher attack.

**Comment by HammerGS** [comment]
I think the key word is **_FROM_**, so the fighter will need to taxi into the water at depth 1 to fire.

**Comment by pokefan548** [comment]
"...Torpedoes may only be fired from _**or into**_ a water hex of Depth 1 or greater."

A unit outside of water may fire at another unit in water, so long as a body of at least Depth 1 water lies between the attacker and target.

**Comment by gsparks3** [comment]
Might be worth a rules forum thread to verify. All I found was this thread on [Multi-Purpose Missiles](https://bg.battletech.com/forums/total-warfare/answered-multi-purpose-missile-munitions/msg1466572/), where the question of "can a unit on land attack an underwater unit" has not yet been answered (and those are specifically designed to be used both above and below water).

**Comment by HammerGS** [comment]
Not sure what version off the rules your asking. This from 7th printing. But they will be enabled for ASF doing forward. You're welcome to direct a rules clarification to the rules team at https://bg.battletech.com/forums/rules-questions/

```
Torpedo Launcher
Torpedo launchers can be any size SRM or LRM launcher and are designed to function underwater; they use the same statistics
as any SRM or LRM launcher, as found on the Weapons and Equipment tables (see p. 303). Torpedoes may only be fired from
or into a water hex of Depth 1 or greater, and the attacker must trace LOS through water hexes of Depth 1 or greater. When using torpedo launchers, a submerged attacker may fire on a target on the surface of the water, or an attacker on the surface may fire at a submerged target, in exception to the normal rules on Intervening Terrain (see p. 100).
If a torpedo hits a location that is not submerged or in the water (a turret, for example), re-roll the location.
```

**Comment by pokefan548** [comment]
Also using 7th Printing here.
Created a [forum thread](https://bg.battletech.com/forums/total-warfare/torpedo-launchers-vs-landairborne-units/), will watch for an answer.

**Comment by Windchild292** [comment]
The other was also for 0.48.0... so closing this as fixed.

**Comment by HammerGS** [comment]
Re-open pending Rules committee ruling.

**Comment by HammerGS** [comment]
Ruling is in.

https://bg.battletech.com/forums/total-warfare/torpedo-launchers-vs-landairborne-units/

With the ruling LRT/SRT can be mounted on ASF but they won't be able to fire at submerged targets.

**Comment by SJuliez** [comment]
now at

https://bg.battletech.com/forums/index.php?topic=76165.0

**Comment by SJuliez** [comment]
In a test with an ASF with LRTs and SRTs, I was unable to fire any at a naval unit (neither from airborne status nor when grounded at the shore). I think this is implemented correctly. Therefore closing this.
