### ISSUE TITLE
[0.49.6] Typo in Game Options tooltip for skipping phases on forced victory

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#3343]
MM 0.49.6
Windows 10 64bit
Java 11.0.8

This has probably been around for a while, but on the tooltip for the "Skip all phases when forced victory occurs" checkbox on the "Victory Conditions" tab of the "Game Options" window, the wording is rather muddles and unclear.

![image](https://user-images.githubusercontent.com/26851644/147853259-c3f8765e-8b75-464f-be04-35455ded7b8b.png)

**Comment by Windchild292** [comment]
Fixed in a62e7c6ab0849a1dc625d68d424732c3a7a185b4
