### ISSUE TITLE
[0.49.6] Ammunition not fully loaded after starting MM game from MekHQ

### ISSUE THREAD

**Issue by mwberlindeu** [MegaMek/megamek#3351]
### Description
A game had been started as scenario from MekHQ's Briefing Room. All units has full ammo in MekHQ. However in MM ammunition appeared to be "low" with several shots already spent at the beginning of the game.

### Files
The attached screenshots show two examples.
![Screenshot ammo AC-20](https://user-images.githubusercontent.com/28268113/148083574-7af2c7fc-4d27-4c82-95c5-75970978b704.jpg)
![Screenshot ammo LRM](https://user-images.githubusercontent.com/28268113/148083594-5a8b04cd-7033-4d82-8f4e-4abe1aea2d85.png)

**Comment by HammerGS** [comment]
Would like to confirm a few things. 

-Version of MegaMek and MekHQ
-Are you playing AtB or Stratcon
-Do the units show as full ready to go in MekHQ.

**Comment by mwberlindeu** [comment]
-Version of MegaMek and MekHQ: 0.49.6
-Are you playing AtB or Stratcon: AtB
-Do the units show as full ready to go in MekHQ: Yes

I can provide campagin and game file if this is helpful.

**Comment by SuperStucco** [comment]
That looks correct to me - it states the count of the current bin '6' then the total count for that weapon type '12'.  Both of those are consistent with LRM20 bins.  Same thing with the AC20 on the Rommel.  The LRM5 on the Rommel is '23/23' because it only has one bin to draw from.

If you look in the Systems tab, it should let you see the counts for individual bins.

**Comment by mwberlindeu** [comment]
Thanks for the comment, I can confirm your observation. The "system" tab shows the ammo correctly and on the "weapon" tab the second number is showing the remaining shots.

![Marsden_Weapons](https://user-images.githubusercontent.com/28268113/148100629-7fda7449-d26c-49a6-b0cf-94eaf0cd69db.png)
![Marsden_Systems](https://user-images.githubusercontent.com/28268113/148100631-b9624d4d-29ab-45b0-9132-680ba38ff417.png)

However this representation at first glance appears counter-intuitive. During games I only rarely look at the "systems" tab (only when armor becomes thin, and I have to check if I should drop ammo), but I look regularly on the "weapons" tab during the firing phase. The numbers on the "weapons" tab (100/100 or 8/18) may be perceived very differently. Possibly a UI element that could be optimized.

**Comment by HammerGS** [comment]
Working as intended.
