### ISSUE TITLE
[0.49.6] Rail movement - Map issue (2 level steps) on 48x48 The train job

### ISSUE THREAD

**Issue by mwberlindeu** [MegaMek/megamek#3354]
### Environment
MegaMek version: 0.49.6 

### Description
Rail movement does not seem to have been implemented (properly):
- The train can leave the tracks (but it should not)
- The train cannot climb a 2 level step (propably a map issue on: 48x48 The train job)

### Files

Player Names: Enemy, Some
[samplegametrain.sav.gz](https://github.com/MegaMek/megamek/files/7809331/samplegametrain.sav.gz)

**Comment by HammerGS** [comment]
Rail movement is not implemented for MegaMek.
