### ISSUE TITLE
Missing mtfs

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#3355]
v.49.6

Missing mtfs for the Batu E and Hyena HYN-4B

The Batu E goes into the fighters/TRO3055U folder.
The Hyena HYN-4B goes into the mechs/3075 folder.

[Missing mtfs.zip](https://github.com/MegaMek/megamek/files/7809748/Missing.mtfs.zip)

**Comment by HammerGS** [comment]
Thanks!
