### ISSUE TITLE
49.6 Level changes in hexes adjacent to runway preventing takeoff

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#3360]
### Description
Aerospace units (conventional fighters, aerospace fighters, and aerodyne DropShips) seem to be having issues where level changes _adjacent_ to the path of their takeoff runway are preventing them from taking off (example below). This does not seem to match the rules for a horizontal takeoff in Total Warfare (page 88 in the 7th printing), where it is specified that there must be no level changes _in_ the takeoff path, but the conditions of the hexes around it are not mentioned. 
![image](https://user-images.githubusercontent.com/59574316/148622065-7d1db1a9-7537-4bd0-ac9d-907c65210c02.png)

While this issue was tested in 0.49.6, it is also present in version 0.48. Aerodyne DS require a three-hex-wide level path but have similar issues if any hexes adjacent to this wider path contain level changes.

Initial reproduction: load the attached savegame and attempt to take off with the Sparrowhawk shown in the image above. A second Sparrowhawk is also present without a level change adjacent to the hex to demonstrate normal takeoff.

### Files
[runwaytest.sav.gz](https://github.com/MegaMek/megamek/files/7832041/runwaytest.sav.gz)

**Comment by SimonLandmine** [comment]
(And there also appears to be a typo in the warning message, too, as it refers to landing when you're trying to take off.)
