### ISSUE TITLE
Infantry types not deploying when deployment is delayed

### ISSUE THREAD

**Issue by TigerShark** [MegaMek/megamek#338]
When deployment is set to "Deploy before round 2" or later, infantry (hover, wheeled, tracked, jump, but not foot) fail to deploy. This only occurs if the unofficial rule "infantry do not count toward deployment initiative" is checked.

**Comment by HammerGS** [comment]
I just tried to duplicate this with 4 phases of deployment with a two mechanized hover platoons each phase.  The game started with 1 infantry on the map.

each phase I was able to deploy both 2 infantry assigned to deploy in that phase.  The only init rules where as follows:
![image](https://cloud.githubusercontent.com/assets/13752452/20612271/5ca88d4e-b275-11e6-8805-8359b8452e6c.png)

Can you provide a save, or more details on the types of unit mix.

**Comment by arlith** [comment]
We haven't received anymore information on this and the issue can't be reproduced.  Without more information, there's not really anything we can do.
