### ISSUE TITLE
[0.49.6] [Bug] Unable to save file

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#3382]
### Environment
MegaMek Version 0.49.6 from
MekHQ 0.49.6

### Description
Cannot save game during play, then automatically disconnect.

Found this message:
13:42:36,571 ERROR [megamek.server.Server] {Connection 0}
megamek.server.Server.saveGame(Server.java:1183) - Unable to save file: savegames\Round_00.sav
com.thoughtworks.xstream.converters.ConversionException: No converter available

All files attached.

To replicate:
1. Load campaign
2. Briefing Room, select Mission #048
3. Select and start any available scenario
4. Start game
5. Try to safe

### Files
[megamek.log](https://github.com/MegaMek/megamek/files/7886476/megamek.log)
[Unable to save file_SirMegaV25110411-5 B4 2nd Scenario.cpnx.gz](https://github.com/MegaMek/megamek/files/7886489/Unable.to.save.file_SirMegaV25110411-5.B4.2nd.Scenario.cpnx.gz)
[Customs - SirMegaV - Mechfiles.zip](https://github.com/MegaMek/megamek/files/7886491/Customs.-.SirMegaV.-.Mechfiles.zip)

**Comment by Windchild292** [comment]
Java 17 is completely unsupported and the cause of this issue. Immediately downgrade to Java 11.
