### ISSUE TITLE
0.49.6: Clan fixed-wing support vehicles can take protomech SRMs, however these SRMs have zero weight and take no crit slots

### ISSUE THREAD

**Issue by BlueNexus** [MegaMek/megamek#3383]
### Environment
0.49.6
Windows
Java 11

### Description
Clan fixed-wing support vehicles are able to take protomech alt number missiles. However, for some reason, the SRM-1, SRM-3 and SRM-5 have zero weight and take no crit slots, so you can have as many as you want.
https://i.imgur.com/IpUDKpR.png

### Files
The following is a discord download link for a blueprint that illustrates this issue: https://discord.com/channels/458705327911731231/458706522739048458/933083481137897492

**Comment by HammerGS** [comment]
Was fixes as part of https://github.com/MegaMek/megamek/commit/b112ca7a813e772088ecb63252397deb63cd7d68
