### ISSUE TITLE
Swarm LRMs not available, but Swarm-I are

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#3384]
In 49.5, with the game year set to 3050 I can select Swarm-I LRMs but not standard Swarm.  If I advance the date to 3053 standard swarm LRMs become available.  Standard swarm LRMs are always available to Clan units.

This feels like a switch was swapped by mistake.

[NoSwarm.sav.gz](https://github.com/MegaMek/megamek/files/7892657/NoSwarm.sav.gz)
![No swarm](https://user-images.githubusercontent.com/70451747/150026684-075598df-7fd6-4f39-a0fc-7fe28c677f6e.png)

**Comment by HammerGS** [comment]
This is one of the weird things with Tech Progression.  Per IntOps pg 61.

Swarm get reintroduced in 3053.  But Swarm-I is invented between 3047-3052. So MegaMek is picking that up. Given the tables in IntOps are considered to have lots of errors and CGL hasn't posted errata. We don't have a lot of official options. 

I do some digging and see what can be done.

**Comment by HammerGS** [comment]
Fixed
