### ISSUE TITLE
Hellcat.gif

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#340]
![image](https://cloud.githubusercontent.com/assets/16950832/18803198/70a65404-81b3-11e6-9873-f9e46416b9a4.png)
[units.zip](https://github.com/MegaMek/megamek/files/490781/units.zip)

**Comment by HammerGS** [comment]
When you get me the shaded version I'll add it :)

**Comment by BLOODWOLF333** [comment]
IDK how to do that shaded stuff.

**Comment by HammerGS** [comment]
added - 24cd0ed820707b78451964644f4fb4c014987d9c

**Comment by pheonixstorm** [comment]
Who does? I have a custom mech icon that needs it
