### ISSUE TITLE
0.49.6 Server becomes Disconnected after deployment

### ISSUE THREAD

**Issue by buzzzz2138** [MegaMek/megamek#3407]
### Environment
Megamek Launched via MekHQ
Win 10
OpenJDK 11

### Description
The server owner becomes disconnected from server.  Then everyone is left without the ability to continue.
Start game and assign people, eventually disconnected.

### Files
[autosave_2022-01-25_21-30-10.sav.gz](https://github.com/MegaMek/megamek/files/7938801/autosave_2022-01-25_21-30-10.sav.gz)
[megamek.log_Error-01_25_2022.txt](https://github.com/MegaMek/megamek/files/7938804/megamek.log_Error-01_25_2022.txt)
[customs.zip](https://github.com/MegaMek/megamek/files/7938806/customs.zip)
[FireBugs30510408.cpnx.gz](https://github.com/MegaMek/megamek/files/7938807/FireBugs30510408.cpnx.gz)

Autosave is the file for the game launched from the FireBugs campaign file.  Customs Attached. 
User Jbamm disconnected and reconnected, but the same thing happened when everyone just connected without any disconnects.

**Comment by buzzzz2138** [comment]
Only the Feds are a Bot. The rest are users.  Except for the Observer which is ran on the same system as the MekHQ and the Original Firebugs.  

When we tried to start from MekHQ again to changes were made.  The Observer was left out, and the Kris client was changed to MekHQ version instead of just the Megamek version download.

**Comment by Windchild292** [comment]
Closing given the lack of further information.
