### ISSUE TITLE
Bug with patchwork armor with reflective on attacks

### ISSUE THREAD

**Issue by MarcJC** [MegaMek/megamek#341]
Attached a zip of Patches a custom with patchwork armor with reflective armor on the legs.

When kicked the damage that transfers from the leg to the torso is doubled as if the torso has reflective armor also even though it doesn't.

This occurs even if the armor is gone and you are kicking the internals only when it moves to the torso the overflow damage is doubled.

I assume the bug also effects other armor types like hardened armor based on the original locations armor type.

I also noticed that shooting a missing leg with a PPC the overflow damage moving to the center torso (side torso was destroyed also)  was halved as if the torso armor was reflective.

[Wolverine WVR-6P (Patches).zip](https://github.com/MegaMek/megamek/files/490836/Wolverine.WVR-6P.Patches.zip)

**Comment by HammerGS** [comment]
Tested this and can confirm the issue.
![image](https://cloud.githubusercontent.com/assets/13752452/20609017/b536f846-b244-11e6-9250-345a92d74b8f.png)

Save game attached.
[Post.sav.gz](https://github.com/MegaMek/megamek/files/612088/Post.sav.gz)

**Comment by arlith** [comment]
Armor properties, like reflective, reactive, hardened, etc were not updated
when damage transfered to a new location, meaning the armor properties from the
old location were applied.  I have fixed this.
