### ISSUE TITLE
Campaign  Unit Icon does not save

### ISSUE THREAD

**Issue by Daryl46** [MegaMek/megamek#3417]
playing Version 0.49.6
Have selected a custom Unit icon for my campaign. Every time I load a saved game to start playing, it does not store the Unit icon, I have to go in and reset it. 
I have tried saving my Campaign options as a preset but it also does not show my my Campaign options file if I select the load option.

**Comment by Windchild292** [comment]
This should have been opened on the MekHQ tracker, and has been fixed for next release in https://github.com/MegaMek/mekhq/pull/3041
