### ISSUE TITLE
Rapids and Torrent Implementation

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#342]
Asking this because of a post on the megamek.info forums which gave me the idea. http://bg.battletech.com/forums/index.php?topic=54739.0

pg.61-62 of TO

Strong Gale : Storm
.....
Water Hexes: All water hexes contain the Rapids terrain modification (see p. 50). 

Tornado F1-F3 : Tornado F4+
.....
Water Hexes: All water hexes contain the Torrent terrain modification (see p. 52).

We already have the overlays for rapids/torrents in MM and are listed in the tileset but, MM does not currently apply the terrain modification when the wind is at the appropriate level.

pg.50
Rapids For any water of Depth 1 or greater that contains rapids, apply a +1 MP cost to enter that hex, as well as a +2 modifier to all Piloting Skill Rolls made while in that hex.

pg.52
Torrent For any water hex of Depth 1 or deeper that contains torrents, apply a +2 MP cost to enter that hex, as well as a +3 modifier to all Piloting Skill Rolls made while in that hex.

**Comment by BLOODWOLF333** [comment]
Never mind this is already in MM I took somebody else's word for it.

**Comment by HammerGS** [comment]
Recording the follow-on for anyone who finds this issue later.

Everything asked for here is in: rapids and torrents are created by wind at the right thresholds, and both the movement cost (+1 and +2 MP) and the piloting modifier (+2 and +3) are applied, in `Terrain.getMovementCost` and `Terrain.applyPilotingModifier`. This was closed correctly.

The remaining half of the p.50 rules is Water Flow - the part that carries a fallen unit downstream, and makes a naval vessel spend MP to hold its position. None of that exists yet, and it is now tracked separately in #8787.
