### ISSUE TITLE
[49.6] Princess largely fails to move into a position where she can attack in low-altitude map combat

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#3429]
### Description
In the image below, I am moving first with a slow ASF, and Princess is moving second with four high-thrust ASF. By all accounts she should have me dead to rights. 

![image](https://user-images.githubusercontent.com/59574316/152476528-7dbb63b1-b13f-43da-9d57-5fd2ebfe4839.png)

However, she consistently fails to maneuver into a position that can attack me. This can be reproduced by loading the first provided savegame, using Replace Player to add a bot, moving, and observing her movement in response. Her movement depends on the movement declared by the player, but the majority of the time, she seems to simply maneuver into a position where I cannot shoot her, with no attempt to attack me, despite being easily capable of moving into a position where she can shoot me and I cannot shoot back. 

In a Princess vs Princess match of four Centurion-1Ds each, this did not apply _every_ round, but in 15 out of 20 rounds prior to one side being eliminated, no attacks were made by either side. A similar situation was actually where I first noticed the issue, in an attempt to test different models of ASF against each other in a bot-vs-bot game that took far longer to end than I expected due to a huge number of rounds where no attacks were made.

Interestingly, in some cases, she will maneuver into a position where she _could_ shoot me if she had not failed to account for the Dead Zone rules: 
![image](https://user-images.githubusercontent.com/59574316/152478775-0983bd29-9ddf-40a8-851c-ae6cfd821eeb.png)
Reproduction steps: load the second provided savegame, Replace Player, accelerate 1, and move one hex north. Interestingly, in such a case, if I make the same move but also Go Down to match _her_ altitude, she will successfully attack me. At no point does she attempt to match my altitude herself.

### Files
[princessVsPlayerASFtest.sav.gz](https://github.com/MegaMek/megamek/files/8000395/princessVsPlayerASFtest.sav.gz)
[princessDeadZoneTest.sav.gz](https://github.com/MegaMek/megamek/files/8000438/princessDeadZoneTest.sav.gz)

All non-empty log files are provided for the second savegame scenario, although I am uncertain if they contain anything of use.
[megamek.log](https://github.com/MegaMek/megamek/files/8000484/megamek.log)
[megameklablog.txt](https://github.com/MegaMek/megamek/files/8000485/megameklablog.txt)
[megameklog.txt](https://github.com/MegaMek/megamek/files/8000486/megameklog.txt)

**Comment by HammerGS** [comment]
Extensive work has been done. Multiple players on Discord confirm these is no longer an issue
