### ISSUE TITLE
Make unit tech level selection listbox a checklist to improve usability

### ISSUE THREAD

**Issue by markerikson** [MegaMek/megamek#343]
The listbox for selecting a tech level in the Add Unit dialog used to have options for "IS All" and "Clan All".  However, those appear to have been removed, which made some searching a bit confusing for me when I recently upgraded.  Per http://bg.battletech.com/forums/index.php?topic=54743.0 , that listbox apparently allows multi-selection to allow searching multiple categories at once, but that is not immediately obvious,  

If the listbox had checkboxes for each entry, it would be more obvious that multiple items can be selected at once.  There's also room for a "Select All" button in that dialog.  

As a related note, it might also be useful to display the currently selected game year and allowable unit levels values from the Game Options dialog, to help clarify what units are currently acceptable.

**Comment by HammerGS** [comment]
Too be honest, using a check box was discussed when this was implemented and going from memory it was determined that it was a big undertaking code wise.

Also the current Game Year and Tech Level are displayed in the lounge in the top right next to the compact display button.

**Comment by markerikson** [comment]
Hmm.  Okay, yeah, I see those labels up there now.

I'll admit that I haven't touched any Swing in several years, but any idea how using a checkbox was going to complicate things?

**Comment by HammerGS** [comment]
Arlith would have to give specifics, but from what I remember would have involved rebuilding the whole unit selector or something like that.

**Comment by markerikson** [comment]
Hmm.  Skimming through UnitSelectorDialog.java, I think the main changes would just be tweaking the usage and definition of `lstTechLevel`.  Primarily lines 108 and 219.

The examples at http://stackoverflow.com/questions/19766/how-do-i-make-a-list-with-checkboxes-in-java-swing and http://www.devx.com/tips/Tip/5342 make it sounds like you could basically just swap out the list type being used.

**Comment by HammerGS** [comment]
You welcome to look into coding it, and submitting a PR.  But @arlith is really the person provide the insights into why it was coded the way it is.

**Comment by arlith** [comment]
There's not technically difficult about it, I just really didn't feel like doing it around the time the changes were made, and I haven't really gotten back to it.  it would probably be good to have some visual indication that multi-select is possible.  I'm not sure that checkboxes are the right answer, as it will look more complicated.  I think instead what should happen is the selection model should change so that when you click on an item, it only affects the selection of that item, instead of deselecting all of the other items.  Essentially, it should act like shift is always held down.  in that case, it's much more clear that you can make multi selections just by clicking on an item or two.  This probably wouldn't be very difficult.

**Comment by Dylan-M** [comment]
I'm not excited about that suggestion, since it goes against standard GUI practice (which is the current behavior). There has to be a better way than that ;)

**Comment by arlith** [comment]
Well, standard GUI practice seems to be the problem in this case...

**Comment by Dylan-M** [comment]
That seems to be more about lack of user education about the change, and about standard GUI practices, rather than a real problem with the GUI. Any time one sees a listbox like that it has a good chance of being multi-selectable.

**Comment by arlith** [comment]
Yea, but making the UI more intuitive is far easier than educating the userbase...

If you take the approach of making it work like the shift button is held down (and then if you hold down shift, it works like shift isn't held down) makes it more intuitive for the user, and also functions close enough to the standard behavior that it wouldn't be hard to figure out.

**Comment by Dylan-M** [comment]
I disagree, I would _never_ want multi-select as the default. I hardly ever use it. Additionally, then we'd have to educate the userbase anyway, that you now have to hold shift to get what most people consider standard behavior. I don't find it intuitive at all, because no other GUI operates that way.

**Comment by Akjosch** [comment]
The general solution for this kind of "hierarchical checkboxes" is rather complicated and I'm not sure if Swing has a pre-defined component for it. Essentially, to have both the "all IS" and "all Clan" functionality as well as a clear indicator that you *should* be selecting more than one item, you need a hierarchy similar to what some installers provide: The checkboxes with "lower level" checkboxes under them have three states (all selected, some selected, none selected) and the "leaf" boxes just the usual two. And it all is displayed as a collapsible tree.

A link to check out: http://www.javaworld.com/article/2077762/core-java/swing-based-tree-layouts-with-checkboxtree.html

**Comment by arlith** [comment]
Going with that approach would require having more screen real estate for selecting the TL, which would basically require redesigning that whole dialog.  That's one of the issues I struggled with when working on the change originally: the old combo-box was very compact and the whole dialog was built around the "selection area" being fairly compact.

One subtle solution might be to make the default be a multi-selection.  I think that, if the user were shown once that multi-selection *is* possible, they might have an easier time figuring out how to do it (or they may look for a tooltip).

**Comment by markerikson** [comment]
In theory, a checklist or checkbox tree shouldn't take up significantly more space.  It's still one item per row, just with some extra width per item.  The current entries don't fill up the list space anyway (at least not in English and in default text sizing).

**Comment by BLOODWOLF333** [comment]
A "ctrl+click to select multiple" note or tooltip would be helpful because I had no idea you could do that.
![example](https://cloud.githubusercontent.com/assets/16950832/18855610/dc7acd64-8419-11e6-8daa-5cc80f936af7.png)

**Comment by SirMegaV** [comment]
I agrees with carr (bloodwolf?). Just a simple text message at the side as
shown on his attachment is sufficient to educate me. I didn't know it was
possible too.

**Comment by arlith** [comment]
There is actually already a tooltip.  It would appear that it's not effective, as it didn't prevent this discussion.

**Comment by Windchild292** [comment]
I'm going to expand the tooltip so that it covers both the label and the list, and then consider this issue closed. I believe the wider changes suggested would take away from the user experience, especially when working on smaller screens (where the screen space for the dialog is already limited.

**Comment by Windchild292** [comment]
Apparently I misremembered, and this has already been done. Closing as completed.
