### ISSUE TITLE
[0.49.7} Snapshot Array Index Out Of Bounds Exception

### ISSUE THREAD

**Issue by buzzzz2138** [MegaMek/megamek#3435]
### Environment
Megamek Snapshot by Windchild
WIn 10
JDK 11

### Description
21:21:11,639 ERROR [megamek.common.Report] {Packet Pump}
megamek.common.Report.addNewline(Report.java:550) - Cannot add a new line
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10

This is started from an ongoing campaign.  Start with Start_testing.sav.gz (Megamek)
It ends with End_Testing.sav.gz with a single autosave. 

Requirements is to have someone connect as the Merit user.  If this game is played solo then the error never occurs.  One the firing phase is reached and everyone player has fired the bot freezes up and the error pops up in the logs.
1. Load Start_Testing.sav.gz
2. Connect from external as Merit, replace all others as bots.
3. Continue to the rounds by moving/firing/done.  It'll locked up in a firing phase. 
4. See the logs for the error.

### Files
[autosave_2022-02-06_21-15-02.sav.gz](https://github.com/MegaMek/megamek/files/8012234/autosave_2022-02-06_21-15-02.sav.gz)
[End_testing.sav.gz](https://github.com/MegaMek/megamek/files/8012235/End_testing.sav.gz)
[START_TESTING.sav.gz](https://github.com/MegaMek/megamek/files/8012236/START_TESTING.sav.gz)
[megamek_Testing_Error.log](https://github.com/MegaMek/megamek/files/8012237/megamek_Testing_Error.log)

**Comment by NickAragua** [comment]
The good news is that if you save at the beginning of the firing phase then reload once the crash occurs, it doesn't occur. So at least there's a work around.

**Comment by Windchild292** [comment]
@NickAragua This was raised from the https://github.com/Windchild292/mekhq/pull/130 branch, which is the current testing branch (#3401) plus expanded logging to help me figure out #3424 and similar. No direct changes, just the testing Log4j logging.
