### ISSUE TITLE
[0.49.7] MegaMek logo on 'About Megamek' popup screen flickering

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#3453]
MegaMek 0.49.7 (MHQ flavour)
Windows 10 (with 1920x1080 monitor)
Java 11

When you click on 'About Megamek' from the 'Help' menu, the Megamek logo at the top of the popup screen is continually flickering, as if it's attempting to re-render upscaling?

**Comment by HammerGS** [comment]
As a side note looks like its using old copyright references.
![image](https://user-images.githubusercontent.com/13752452/154820124-be9fded4-4b54-4030-a73c-d3ca81002578.png)

**Comment by HoneySkull** [comment]
I noticed that too, but thought it was a 20 year anniversary easter egg.  I actually think it looks cool in a retro way.  :)
