### ISSUE TITLE
Issue with individual initiative and allowing vehicles to enter the physical phase

### ISSUE THREAD

**Issue by TigerShark** [MegaMek/megamek#347]
When Individual Initiative is enabled, the client occasionally will select a vehicle to make a physical attack during the Physical Phase. This hangs the game unless the /skip command is issued, which can freeze the client or kick the user.
[rpgfirebug.sav.gz](https://github.com/MegaMek/megamek/files/496546/rpgfirebug.sav.gz)

**Comment by BLOODWOLF333** [comment]
I cant load your save because I dont know the player name?  But if MM is asking for physicals from vees and your game is at night then its because it allows you to still aim your searchlights during the physical phase to assist other units with their physical attacks.

**Comment by TigerShark** [comment]
No, the game was during the daytime. Player name is probably Scia.
 

 

 

-----Original Message-----

**Comment by arlith** [comment]
Could you help give me an idea of what the closest MM version is for this saved game?  Saved games can't often be loaded across versions, but if I knew the version of MM you based your client on, I could set my repository to that point to load the game.  We've started embedding the version into the saved game, but it looks like your client is prior to that change.

**Comment by TigerShark** [comment]
41.16
 

 

 

-----Original Message-----

**Comment by arlith** [comment]
I was able to load the saved game by going back to the v0.41.15 release.  You must have created it from 0.41.16-git, which isn't actually the release version.  By the time the v0.41.16 release happened, some changes must have been added that make it so the saved game cannot be loaded.

Unfortunately, the save starts after the physical phase had begun, and I can't reproduce the issue by skipping through turns to the physical phase on the next round.

I did notice though that the 6th Arkab legion (which is the player with the turn he doesn't have a unit for) does have an immobile unit that gets a chance to unload at the start of the next movement phase.  Perhaps that has something to do with it.

**Comment by arlith** [comment]
It's not clear to me what would lead to this situation.  The methods involved would be `Server.prepareForPhase`, `Server.setIneligible(Phase)`, and `Server.determineTurnOrderIUI(Phase)`.

When the physical phase begins, `prepareForPhase` is what sets all the state up.  First it will determine if any units are ineligible for the phase, and those that are will have their `Entity.done` status set to true, making that unit not get a turn (`Entity.isSelectableThisTurn` will return false).

What's happening in this saved game is that the last turn in the Game's turn vector is a `SpecificEntityTurn` for entity id 35, which is "Striker Light Tank ID:35 (6th Arkab Legion)".  This unit should have had it's `Entity.done` state set to false in `Server.setIneligible(Phase)`.  The only relevant place for a `SpecificEntityTurn` to get created and added is in `Server.determineTurnOrderIUI`, which is called after `Server.setIneligible(Phase)`.  Either that strike should have it's done state set to true, or not.  If it wasn't set to true, it should get a turn and be selectable.  For some reason it's done state *is* set to true, so it's not selectable, but it also has gotten a turn.  There's no way this can happen in the code from what I can see.

Without a better idea of what lead to this, I don't really have any other ideas.

There is a unit that gets to unload stranded units, but it's not the Striker that's getting the physical turn, and that only adds an extra turn in the movement phase.  There's no way that turns from previous phases could get added, as the turn vector is created from scratch in `Server.determineTurnOrderIUI`.

From what I can see, this must be a rare occurrence.  I'm going to defer this until after the current stable release.

**Comment by Dylan-M** [comment]
I just did a minor cleanup of the `Server.determineTurnOrderIUI(Phase)` and `Server.determineTurnOrder(Phase)` methods for the section related to stranded entities so it doesn't perform unnecessary actions during non-movement phases in 82a191f. This also fixes the bug where stranded entities couldn't unload during deployment with individual initiative.

**Comment by neoancient** [comment]
Closing as stale.
