### ISSUE TITLE
[0.49.7] Error: Unable to load game file.

### ISSUE THREAD

**Issue by vipersbrood** [MegaMek/megamek#3470]
Attempting to load autosave.sav.gz pops up with the message "Error: Unable to load game file."
MegaMek 0.49.7
Java 17.0.1
[megamek.log](https://github.com/MegaMek/megamek/files/8145802/megamek.log)
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/8145803/autosave.sav.gz)

**Comment by Windchild292** [comment]
Java 17 is completely unsupported and does not work with the suite. Immediately downgrade to Java 11 to use the current dev release.
