### ISSUE TITLE
Princess freezes during deployment 0.41.23

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#348]
In conjunction with MekHQ 0.3.33, Princess freezes during deployment.  I have attached the log and the savegame.
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/504361/mekhqlog.txt)
[princessfreezedeploy.sav.gz](https://github.com/MegaMek/megamek/files/504362/princessfreezedeploy.sav.gz)

**Comment by HammerGS** [comment]
This is the NPE repeated in the log for reference:

`
java.lang.NullPointerException
	at megamek.client.bot.BotClient.getStartingCoordsArray(BotClient.java:467)
	at megamek.client.bot.princess.Princess.calculateDeployment(Princess.java:247)
	at megamek.client.bot.BotClient.calculateMyTurn(BotClient.java:401)
	at megamek.client.bot.BotClient$CalculateBotTurn.run(BotClient.java:98)
	at java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException
	at megamek.client.bot.BotClient.getStartingCoordsArray(BotClient.java:467)
	at megamek.client.bot.princess.Princess.calculateDeployment(Princess.java:247)
	at megamek.client.bot.BotClient.calculateMyTurn(BotClient.java:401)
	at megamek.client.bot.BotClient$CalculateBotTurn.run(BotClient.java:98)
	at java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException
	at megamek.client.bot.BotClient.getStartingCoordsArray(BotClient.java:467)
	at megamek.client.bot.princess.Princess.calculateDeployment(Princess.java:247)
	at megamek.client.bot.BotClient.calculateMyTurn(BotClient.java:401)
	at megamek.client.bot.BotClient$CalculateBotTurn.run(BotClient.java:98)
	at java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException
	at megamek.client.bot.BotClient.getStartingCoordsArray(BotClient.java:467)
	at megamek.client.bot.princess.Princess.calculateDeployment(Princess.java:247)
	at megamek.client.bot.BotClient.calculateMyTurn(BotClient.java:401)
	at megamek.client.bot.BotClient$CalculateBotTurn.run(BotClient.java:98)
	at java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException
	at megamek.client.bot.BotClient.getStartingCoordsArray(BotClient.java:467)
	at megamek.client.bot.princess.Princess.calculateDeployment(Princess.java:247)
	at megamek.client.bot.BotClient.calculateMyTurn(BotClient.java:401)
	at megamek.client.bot.BotClient$CalculateBotTurn.run(BotClient.java:98)
	at java.lang.Thread.run(Unknown Source)
`

**Comment by BLR-IIC** [comment]
Here are some more logs and savegames.
[princessbotdies2.sav.gz](https://github.com/MegaMek/megamek/files/504706/princessbotdies2.sav.gz)
[princessdied3.sav.gz](https://github.com/MegaMek/megamek/files/504707/princessdied3.sav.gz)
[mekhqlog-princessdies2.txt](https://github.com/MegaMek/megamek/files/504708/mekhqlog-princessdies2.txt)
[mekhqlog-princessdies3.txt](https://github.com/MegaMek/megamek/files/504709/mekhqlog-princessdies3.txt)

**Comment by BLR-IIC** [comment]
More Logs

[Uploading princessdies4atdeployment.sav.gz…]()
[mekhqlog-princessdies4.txt](https://github.com/MegaMek/megamek/files/504717/mekhqlog-princessdies4.txt)

**Comment by BLR-IIC** [comment]
Hammer suggested that I remove a couple units since this might be an issue with stacking.  I did that, and managed to deploy a couple of my 'mechs, but then Princess quit working again.  Here's another log and save.
[mekhqlog-princessdies5.txt](https://github.com/MegaMek/megamek/files/504718/mekhqlog-princessdies5.txt)
[princessdies5.sav.gz](https://github.com/MegaMek/megamek/files/504719/princessdies5.sav.gz)

**Comment by BLR-IIC** [comment]
I played around with this a bit more.  So a computer reboot doesn't solve the issue.  Neither does closing all of my Java applications.

I ended up setting all of the MegaMek game options to default, and that seemed to clear the error.  There's something with the game options I had that's causing the bot to die.

So I went through each tab and activated the options I wanted by tab, and didn't find anything I wanted that was causing the bot to die.  My solution therefore was to reset the options to default and reset them to how I wanted them.

**Comment by BLR-IIC** [comment]
After playing around with the settings more, it looks like it might be a problem with individual initiative.  As soon as I unchecked that option, the bot didn't have any more problems.

**Comment by mhjacks** [comment]
I have seen something very similar to this when starting the last two scenarios of 1st Somerset Strikers, with Princess as the Strikers team (not BlackVision or FalconsClaws, either MalthusAttacks or TheLiberationOfSMA).  I have seen Princess freeze while deploying in both.  I will do some testing tonight to see if I can get different results on 41.22 vs 41.23 and see if the log shows the same NPE as reported above.

**Comment by Akjosch** [comment]
@mhjacks That's just an issue with the scenario files having out-of-board coordinates in them. I fixed both.

**Comment by arlith** [comment]
The issue is partly related to individual initiative.  I can load up the saved game and get the crash.  When I start digging into it, I found what is happening, at least in `princessdied3` is that it's the Capellan Confederation's turn, and they are supposed to move the Scimitar tank, however that unit is already deployed.  What happens then is that they try to take their turn, but the turns for a unit that's already gone.  This then leads to trying to take a turn for no unit, which ultimately leads to the NPE.  However, it's not clear how or why this state gets reached.

**Comment by arlith** [comment]
Ah, I figured it out.  It's the combination of `Vehicle Lance Movement` and individual initiative.  These rules aren't really compatible.  The way it works is that we have turn that vector and different types of turns that specify what kinds of units can take that turn.  Individual initiative works by using `SpecificEntityTurn`s, which specify specifically what entity should move on a turn.  The lance movement rules then work by using `EntityClassTurn`s.  Once you move a unit of a certain class (like tank), then it adds in new turns for that specific entity type.  This causes problems with individual initiative, as units could have their turns taken early.

**Comment by Dylan-M** [comment]
@arlith These rules should be mutually exclusive, ie if individual init is on, then the others should be de-selected and disabled, and vice-versa.

**Comment by arlith** [comment]
Looks like individual init and lance movement is already known to be incompatible.  This is indicated in the tooltips for the options and if you click on individual init it disables the lance movement.

However, it appears that clicking the lance movement options does not disable individual init, so if you turn them on, then you can still turn on individual init.  That's a bug, and that's the bug I think needs to be fixed for this issue.  Doing that will prevent these incompatible options and prevent the reported issue.
