### ISSUE TITLE
[0.49.7] Client Settings for 'Default Weapon Sort Order' not respected

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#3489]
MegaMek 0.49.7 (MHQ flavour)
Windows 10 (with 1920x1080 monitor)
Java 11

The 'Default Weapon Sort Order' was set to "Range (High-Low)" in the Client Settings dialog. However, on the unit window, the weapons were still sorted by order "Default" (which was not "Range (High-Low)". It appears that the Client Settings setting for this may be being ignored.

(Additionally, with the use of 'Default' for both the setting name and one of the options, there might be room for confusion, as it might be thought that a showing of "Default" on the unit window refers to the setting made under 'Default Weapon Sort Order', rather than the "Default" weapon sort order. Suggest perhaps changing the name of the setting on 'Client Settings' to 'Preferred Weapon Sort Order', although that might require more discussion as to clear wording.)

**Comment by SJuliez** [comment]
I believe this issue is fixed by #4096
