### ISSUE TITLE
Units not making appropriate bog down checks

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#3499]
In the attached 49.7 game, Mechs at the south of the map are not making bog down checks walking through the level -1 swamp hexes, and are making checks when they climb onto the level 0 land next to them.  Additionally, a VTOL in the north of the map made (and failed) a bog down check when flying 1 level above a level 1 swamp hex.

[SwampyIssues.sav.gz](https://github.com/MegaMek/megamek/files/8200403/SwampyIssues.sav.gz)

Players are:
Green Strike Cluster (Team 1)
Clan Jade Falcon Integrated Allies (Team 1)
Rebels Primary Opfor (Team 2)
Rebels Designated Target (Team 2)
Clan Jade Falcon Allied Artillery (Team 1)
Clan Jade Falcon Allied Aircraft (Team 1)

Possibly not related, but this is heavy-g conditions (1.27g).

**Comment by SuperStucco** [comment]
After some investigation I found something interesting regarding this:

Take a map with multiple positive levels, no trees, and mud/swamp/bog down terrain on each of those levels.  Deploy a VTOL and fly it over the different levels at various differences in level.  When it flies over that terrain at an elevation difference equal to the elevation of that terrain, it calls for a bog down piloting check.  For example:

- Level 1: flying at level 2 (1 above level 1) calls for a check
- Level 2: flying at level 4 (2 above level 2) calls for a check, but flying at level 3 (1 above level 2) does not
- Level 3: flying at level 6 (3 above level 3) calls for a check, but flying at level 4 (1 above level 3) or 2 (2 above) does not

I suspect there's a wrong property name being called or the difference is being calculated incorrectly.

**Comment by LilyFromSangvisFerri** [comment]
The above also applies to VTOLs flying over Heavy Snow under the same parameters as above.

**Comment by HammerGS** [comment]
Related
https://github.com/MegaMek/megamek/issues/3618

**Comment by HammerGS** [comment]
I've been trying to work out a fix for this but also noticing that elevation on VTOLs isn't consistent. 

As referenced in this forum post. 
https://bg.battletech.com/forums/megamek-games/vtol-movement-issue-gaining-altitude-when-going-backwards
