### ISSUE TITLE
Solitaire/Easier Hotseat Mode

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#350]
Instead of alternating between separate open MegaMek windows to move units for both teams, I think MegaMek should get a hotseat mode.  Players should be able to move the units of both teams from a single window.

**Comment by MGM175** [comment]
I've also encountered this problem when I wanted to play MM with my buddy, which I've tried to introduce to BattleTech.

It would be nice to see the true hotseat mode :)

**Comment by SJuliez** [comment]
I understand the issue but MegaMek is organized with the assumption that the client window is for this client only. This would be so difficult to implement that I don't see anyone ever trying this. Therefore closing it.
