### ISSUE TITLE
Add Objects That Can Be Captured

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#353]
Requesting to be able to add objects like supply crates that could be captured or picked-up in MM using the picking up objects rules from TO.  And that can be later linked to rewards in HQ after completing a scenario.
![slack](https://cloud.githubusercontent.com/assets/16950832/19166261/7aef4b8c-8bcc-11e6-8172-417ae751744c.png)

I know @hammer also suggested the idea of designating buildings that could be scanned to fulfill victory conditions during a recon scenario for example.  Also goes into AJ's victory conditions project.

And also the ability to place human beings on the map that can be picked up and captured by other units like mechs, similar to how the mechwarrior pilot is treated after ejecting.

**Comment by mkerensky** [comment]
+1 to all 3 of these options. It would allow for the play of recon and extraction raid type scenarios that are so much a part of the BT universe.

**Comment by Dylan-M** [comment]
On the MHQ side, we should also add to this that selections of parts should be able to be stashed as supply dumps. Also, Mechs/Tanks/Etc.. without pilots/crews should allow be allowed to be there as stationary units.

**Comment by HammerGS** [comment]
As an extension of this would be nice to have "scramble" mode where pilots need to get to their units and power them up

**Comment by BLOODWOLF333** [comment]
![example](https://cloud.githubusercontent.com/assets/16950832/19588036/9c3f1fee-9728-11e6-8369-aade04b49b3d.png)

And then I accidentally closed the MM window instead of this MS paint window and lost an hours worth of play time..........dang it.
