### ISSUE TITLE
[0.48.0] Battle value calculation including anti mech cost for infantry wearing armour that precludes those attacks

### ISSUE THREAD

**Issue by Gribbly1** [MegaMek/megamek#3532]
Environment
Bundled HQ's MegaMekLab.
Windows 10
Java version 1.8.0_261

![antimek](https://user-images.githubusercontent.com/55139229/126025130-e2aa4e73-b7a7-4f90-ac99-93355d23fd30.png)

All units using encumbering infantry armour are still evaluated as having anti mech BV in the calculation (despite being unable to make those attacks).

**Comment by SJuliez** [comment]
Closing this as it's a duplicate of #3748
