### ISSUE TITLE
Stone Rhino 4 has Single Heat Sinks Currently

### ISSUE THREAD

**Issue by WildKadabra** [MegaMek/megamek#3543]
The current Stone Rhino 4 has single heat sinks in the game instead of double heat sinks.

**Comment by AlphaSled** [comment]
Is there a record sheet product that points towards it having double heat sinks?

**Comment by WildKadabra** [comment]
Plz disregard this, my source was incorrect. Upon revising the ilClan Rec. Guide #2, it is indeed single heat sinks.
