### ISSUE TITLE
Artillery Cannon with Fuel-Air ammunition uses standard ammunition's damage value

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megamek#3546]
### Environment
Ver 0.49.7
Windows 10

### Description
As title says. For example, Fuel-Air ammunition of Long Tom Cannon's damage value(166, IO) is 30/20/10/5, but in MegaMek it uses same value as standard ammunition(20/10). I haven't tested Fuel-Air ammunition of the other artillery cannon, though.

**Comment by PhoenixHeart512** [comment]
Confirmed to still be a bug in 49.10

Savegame:
[FAM-LTC_Alacorn_Ammo_Bug.sav.gz](https://github.com/MegaMek/megamek/files/9862655/FAM-LTC_Alacorn_Ammo_Bug.sav.gz)
(Player name: Tempest Marauders, unit with LTC: Alacorn)


![LTC FAM Weapon Details](https://user-images.githubusercontent.com/101755917/197846020-385c9675-1de9-4da9-bb03-c3d330760611.png)
![LTC FAM EOR Report](https://user-images.githubusercontent.com/101755917/197846028-df12a7b9-74b5-4eff-adfe-dfa00b969b10.png)

Sample unit that can be used for testing:
[Alacorn Heavy Tank IS-Ph FALTC Mk II.zip](https://github.com/MegaMek/megamek/files/9862701/Alacorn.Heavy.Tank.IS-Ph.FALTC.Mk.II.zip)

**Comment by Sleet01** [comment]
Checking...

**Comment by Sleet01** [comment]
Artillery Cannons just need to call the Fuel-Air Explosive handler when ammo is FAE, everything already works like clockwork.
Clockwork that is on _FIRE_...
