### ISSUE TITLE
[49.6] LAM movement in Airmech mode curtailed

### ISSUE THREAD

**Issue by mwberlindeu** [MegaMek/megamek#3559]
**Environment**
MegaMek version: 49.6

**Description**
It appears that LAM movement in Airmech mode is curtailed. Apparently every hex traveled after an elevation change counts as three movement points.

![LAM movement Airmech mode](https://user-images.githubusercontent.com/28268113/162568547-d4c0ddde-29d7-4170-ac01-f1a592aa9984.png)

**Files**
[LAM.sav.gz](https://github.com/MegaMek/megamek/files/8456751/LAM.sav.gz)

**Comment by SimonLandmine** [comment]
Looks from the screenshot like the LAM didn't choose to drop down (at no cost) to the AirMech cruising height of one level above the desert after it left the higher level, but remained at the higher elevation.
As per the WiGE movement rules (pp.55-56, TW), which apply to AirMechs, this is entirely valid, but a WiGE (or AirMech) choosing to maintain elevation has to expend an additional 2 MP per hex to do so - which is what is happening in the screenshot.
This isn't a bug, but a case of the WiGE movement rules being implemented correctly.

**Comment by mwberlindeu** [comment]
Thanks for the reply. I retestested and indeed if the LAM follows the terrain there is no movement penalty. Thus issue can be closed.

**Comment by SimonLandmine** [comment]
Happy to help! It's just (like many AirMech/WiGE things) not entirely obvious! :-D
