### ISSUE TITLE
Almost all dropships have 2/3 movement

### ISSUE THREAD

**Issue by crazys1** [MegaMek/megamek#356]
MegaMek version 0.41.24-git

Description:

Almost all dropships have 2/3 movement, when in reality the movement values should be much more varied. For example, the Achilles (3088) has a safe thrust of 8 (8/12 movement), but in MegaMek it has 2/3 movement.

To Duplicate the Bug:

1. Open MegaMek.
2. Click "Add a Combat Unit...".
3. For the Unit Type, choose "Dropship".
4. For the Type, choose all of the categories.
5. In the list of dropships, choose any one of them and notice that they all have 2/3 movement. The only exception is the Vampire (Standard), which has 3/5 movement.

[megameklog.txt](https://github.com/MegaMek/megamek/files/517816/megameklog.txt)

**Comment by HammerGS** [comment]
I've confirmed that the BLK files are correct and don't see any errors in the log.  I can duplicate the bug with the steps above.

**Comment by pheonixstorm** [comment]
Is this also happening in the lobby or in a game or only in the unit selector dialog?

**Comment by crazys1** [comment]
In-game and in the lobby. A dropship moving on the ground map has the incorrect 2/3 movement.

You also see the bug in the MekHQ, whether you are purchasing a dropship or you already own one.
