### ISSUE TITLE
[49.8-SNAPSHOT]  NPE when Enemy Aero tries to Declare Indirect Attack.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/megamek#3568]
20:42:17,145 INFO  [megamek.MegaMek] {main}
megamek.MegaMek.initializeLogging(MegaMek.java:122) - Starting MegaMek v0.49.8-SNAPSHOT
	Build Date: 2022-04-03T01:39:41.469496400
	Release Date: 2022-02-18
	Today: 2022-04-06
	Origin Project: MekHQ
	Java Vendor: AdoptOpenJDK
	Java Version: 11.0.10
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 4 GB

### Description
Happened twice.  I closed client, restarted scenario and it repeated.  I THINK its an enemy Thunderbird with an Air Launched Arrow missile that flew off of the map.  He launched them successfully turn 1, but then flew off map before next turn, and I got the exception while its his turn to declare indirect attacks.

Thought this might be a MM issue but the message says to post it here...

EDIT: DELETED EDIT ON CONTROL ROLLS.  MY MISTAKE.

### Files
[The Bluecoats30600604.cpnx.gz](https://github.com/MegaMek/mekhq/files/8439251/The.Bluecoats30600604.cpnx.gz)
[mekhq.log](https://github.com/MegaMek/mekhq/files/8439252/mekhq.log)
[megamek.log](https://github.com/MegaMek/mekhq/files/8439253/megamek.log)
[autosave.sav.gz](https://github.com/MegaMek/mekhq/files/8439257/autosave.sav.gz)
![Screenshot (362)](https://user-images.githubusercontent.com/23645569/162110653-098b9a26-f3f8-4e66-893a-ce47050a3820.png)

**Comment by Windchild292** [comment]
Transferring to MegaMek, as it's a MegaMek uncaught exception
