### ISSUE TITLE
Mass Configure Allows mechs to be deployed off board

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#357]
If an artillery unit & a mech are selected at the same time with the mass configure option mechs can be deployed off board as if they were artillery.

So far I've only seen this in the lobby, I'm concerned if I launch the game it will crash.

**Comment by arlith** [comment]
The `eligibleForOffBoard` boolean was being set for just the first entity in the list.  It needed to be moved to the code that considers all selected entities.  Now, the "deploy offboard" option is only available if it is applicable to all selected entities.
