### ISSUE TITLE
[49.7] Ailette Zero-G Engineering Exoskeleton unit file incorrect

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#3571]
Megamek lists the Ailette Zero-G Engineering Exoskeleton as having 0 armor per suit. Per both TRO: Vehicle Annex and Record Sheets: Vehicle Annex - Industrialmechs and Exoskeletons, it should have 1 armor per suit.

A unit file saved after correcting this in MML (with no other modifications) is attached. The unit file to be replaced is found in `data\mechfiles\battlearmor.zip\TRO VA`
[Ailette Zero-G Engineering Exoskeleton (Standard).zip](https://github.com/MegaMek/megamek/files/8477082/Ailette.Zero-G.Engineering.Exoskeleton.Standard.zip)

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/0a67591998d715c281c6e02f81505753979ea171
