### ISSUE TITLE
[0.49.8-734] An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by kernhe** [MegaMek/megamek#3586]
### Environment
V: 0.49.8-734
O: Linux 5.4.0-104-generic x86_64
J: openjdk version "11.0.14.1" 2022-02-08

### Description
When I start a game (press "Done") the shell tells me the following:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.SerializationMembers (file:/media/Privat/MEGA/mekhq-0.49.8-734/lib/xstream-1.4.14.jar) to method java.util.concurrent.CopyOnWriteArrayList.readObject(java.io.ObjectInputStream)
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.SerializationMembers
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Server Started at XXXXXX:2346 : Password disabled

```
I noticed this first while I started a game from MHQ, but it is definitely an issue with mm.

### Files
[megamek.log](https://github.com/MegaMek/megamek/files/8523113/megamek.log)

**Comment by Windchild292** [comment]
This will be handled as part of migrating away from XStream as part of supporting Java 17, and doesn't need an issue. Thus, I'm closing this.

**Comment by kernhe** [comment]
OK, thanks for the update and the upcoming mitigation.
