### ISSUE TITLE
0.49.7 Bot sometimes ignores set deployment turns.

### ISSUE THREAD

**Issue by EvilAtlas** [MegaMek/megamek#3590]
### Environment
I'm using MekHQ 0.49.7, running on Windows, and using Java 11.0.14.1.

### Description

I'm running a pursuit battle generated by and launched through MekHQ. I adjusted the deployment settings in the lobby so I deploy at start of game and the bot's units deploy on turn 3, but when I start the game, the bot's units all ignore the deployment setting and deploy at start of game as well. I've repeatedly closed the game without saving, restarted it from MekHQ, and tried to set things properly and try again, but the issue recurs. I've tried setting it so a single enemy unit (a helicopter) deploys at start of game and everything else deploys on turn 3, just in case the bot's units were getting pushed forward until at least _something_ would be deployed, but everything deployed at start of game anyway.

I also tried saving my game in the lobby so I could restart from there rather than having to set everything again, but when I loaded the save, all the enemy units in the lobby were set to deploy at start of game. (This issue may recur with the save I sent you.)

![image](https://user-images.githubusercontent.com/94950654/164506803-f4a5fc8d-fb14-42d7-9b87-7a59b09c7f13.png)
![image](https://user-images.githubusercontent.com/94950654/164506852-e3ccb8c8-381b-4eea-a20e-26b75a65775c.png)
![image](https://user-images.githubusercontent.com/94950654/164506998-7aeac4bf-7992-483f-8ce2-e98dddc8fc4d.png)

### Files
[bugged_deployment.zip](https://github.com/MegaMek/megamek/files/8532774/bugged_deployment.zip)
Player name is Iron Titans. I _think_ I provided all relevant files, but if anything's missing, let me know and I'll add it!

**Comment by EvilAtlas** [comment]
Update: Regenerating the OpFor in MekHQ does fix (or at least bypass) the issue.

**Comment by SuperStucco** [comment]
When you change the deployment turn, do you do it from the Configure Unit dialog (the one where you can change ammo types, pilot skill, etc.) or through the right-click nested context menu in the lobby?  Anecdotal only, but I've periodically seen this with the latter (context menu) but not the former (dialog).

**Comment by EvilAtlas** [comment]
I do it from the Configure Unit dialogue. I think in every case I've selected multiple units at once and used Configure Units from there?

**Comment by AQGadget** [comment]
I'm noticing this problem in 0.49.10. Had to manually create the game and enemy forces for a harass mission that generate without a map size or enemies.


[HARASS2.sav.gz](https://github.com/MegaMek/megamek/files/9953116/HARASS2.sav.gz)

save attached. the save refuses to retain the deployRound tag for most of the bot units as well. They're almost all zero despite being set to 1-4 for everything but the Assassin before saving

**Comment by jslater89** [comment]
Still happening in 0.49.17. Maybe I'll take a look, if nobody else has...

**Comment by Tecmes** [comment]
Still happening in 0.49.19. I'll investigate whether one of the two methods to set it works.
