### ISSUE TITLE
(0.49.7) Mek fleeing while swarmed causes crash

### ISSUE THREAD

**Issue by benjaminjdowell** [MegaMek/megamek#3607]
### Environment
Version 0.49.7
Windows 7 Professional
Java version 11.0.14.1

### Description
![megamek hq error message](https://user-images.githubusercontent.com/104769942/166234910-5df4fa28-18fa-476a-8fe9-2b3929488f40.jpg)

I have a mek being swarmed by enemy power armor. I'm at the edge of the board and want to flee, taking the enemy power armor with me. However, every time I use the Flee command, I get a Java.lang.NullPointerException dialog box and can't continue the game. I have saved the game just before this unit's turn and have an autosave file, the error happens each time I attempt this action.

### Files
[Murder Hornet Brigade30770921.cpnx.gz](https://github.com/MegaMek/mekhq/files/8602886/Murder.Hornet.Brigade30770921.cpnx.gz)

[mechs.zip](https://github.com/MegaMek/mekhq/files/8602898/mechs.zip)

[megamek.log](https://github.com/MegaMek/mekhq/files/8602917/megamek.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/8602921/mekhq.log)

**Comment by HammerGS** [comment]
Lots of these

```
mekhq.MekHQ.lambda$main$0(MekHQ.java:269) - Uncaught Exception Detected
java.lang.NullPointerException
	at megamek.client.ui.swing.tooltip.UnitToolTip.inGameValues(UnitToolTip.java:676)
	at megamek.client.ui.swing.tooltip.UnitToolTip.getEntityTip(UnitToolTip.java:89)
	at megamek.client.ui.swing.tooltip.UnitToolTip.getEntityTipGame(UnitToolTip.java:55)
	at megamek.client.ui.swing.boardview.BoardView.getHexTooltip(BoardView.java:5712)
	at megamek.client.ui.swing.boardview.BoardView$2.mouseMoved(BoardView.java:526)
```

**Comment by Windchild292** [comment]
Princess fled with the battle armour first, but the swarm attacker id wasn't cleared as part of that action... which leads me to the rules question as to whether you can flee while swarming a 'Mech.

**Comment by Windchild292** [comment]
I mean the opposite side of things, so can you flee while swarming a 'Mech (the BA fled the board while swarming)

**Comment by Windchild292** [comment]
I've got a fix for the NPE ready (we need to add null protection there regardless of the rules query above), and will handle the other fix as part of a second branch.

**Comment by HammerGS** [comment]
Per TW - "During the Movement Phase of the following turn, infantry units that have not been knocked off travel with the ’Mech."

So once on board the infantry/BA move with the mech. They "flee" by first ending the swarm.

**Comment by benjaminjdowell** [comment]
The power armor would have to end its swarming before it could move. I don’t remember if that’s during the move phase or attack phase but that should be all it could have done that turn, if that’s what it was doing.

**Comment by Windchild292** [comment]
This has led to #3608, #3610, and #3613, to handle the initial cause, origin cause, and add the support to Princess respectively. I'm going to close this given the multiple PRs and a new issue for the Princess gap are open.
