### ISSUE TITLE
[49.8 Test Branch] New MM GUI Issues with Unit Window

### ISSUE THREAD

**Issue by Thom293** [MegaMek/megamek#3616]
23:00:13,261 INFO  [megamek.MegaMek] {main}
megamek.MegaMek.initializeLogging(MegaMek.java:115) - Starting MegaMek v0.49.8-SNAPSHOT
	Build Date: 2022-05-03T01:13:29.469020
	Release Date: 2022-02-18
	Today: 2022-05-02
	Origin Project: MekHQ
	Java Vendor: AdoptOpenJDK
	Java Version: 11.0.10
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 2 GB

Very strange.  Im on the test branch.  Upgraded from a very recent nightly build.  Screenshots below.  

Edit2:  I guess this has turned into a "general spacing issues" post that is highlighted by the one-third screen docked window.  Ill just add any new edits in comments.

Edit:  Added another screenshot to bring up a spacing issue on armor tab that existed before, but is exacerbated by using the window undocked.  Also, I cannot get the floating button issue to replicate.  Ive tried to duplicate it numerous ways.

3 issues:

1. The Unit screen now defaults to takes up almost a third of the screen.  Before it took up about a quarter.  I preferred the old way.  ;)  Doesnt seem draggable to the right to reduce its size.  
2. When I detached the window, because it was too big, when I changed tabs on the detached window, got a strange appearance where the buttons went about an inch below the top of the detached window, and they covered the pilots face.  This happened on all tabs.  (Closing and relaunching MM did make the lower button issue go away).  EDIT: Added a close up.
3. Also with the detached window - it now does not minimize when you switch to another program, and always stays on top unless manually minimized.  I dont think this is correct.  Its been a while since I played with it detached, but I recall that it used to minimize with the rest of the program?  You can see its on the front screen with me as I type this.  EDIT:  Now that I think about it, the floating mini-map pop up correctly minimizes with the program, and does not show up as its on separate window when hovering over the game icon on the taskbar.  So perhaps the unit window needs the same setting as the minimap?

And thank you for the turret pop up!

[mekhq.log](https://github.com/MegaMek/megamek/files/8608495/mekhq.log)
[The Bluecoats30621106A.cpnx.gz](https://github.com/MegaMek/megamek/files/8608496/The.Bluecoats30621106A.cpnx.gz)
[megamek.log](https://github.com/MegaMek/megamek/files/8608500/megamek.log)

![Screenshot (413)_LI](https://user-images.githubusercontent.com/23645569/166411638-d5d40da6-2c25-442d-9147-5c8ece9df8a3.jpg)

![Screenshot 2022-05-03 001642_LI](https://user-images.githubusercontent.com/23645569/166411616-8f6f6255-42a3-4638-b5f5-648f0e57e27d.jpg)

![Screenshot 2022-05-03 003226](https://user-images.githubusercontent.com/23645569/166411126-668d66c1-32a6-448d-b400-90271f239f24.png)
![Screenshot (422)](https://user-images.githubusercontent.com/23645569/166411209-cc500dad-2ee5-4db8-89e6-2041ab6fa8c2.png)
Edit:
Close up of split.
![Screenshot 2022-05-03 011039](https://user-images.githubusercontent.com/23645569/166569751-6bc8231a-e31a-407f-a96b-7a363836837b.png)

**Comment by Thom293** [comment]
Also related, there is a huge amount of space at the top of the screen on the armor tab.  I looked at old screenshots and this was present before, but it wasnt a big deal when the window was docked.  But now that I have to use it undocked that particular tab makes the whole thing unwieldy. 
![Screenshot 2022-05-03 163759](https://user-images.githubusercontent.com/23645569/166571301-76d40626-8e7a-45f1-88a5-657b4122b47d.png)

**Comment by Thom293** [comment]
Sorry - another.  Only notice now that the docked window is so large.  When docked, some panes appear to be aligned to top left. e.g. the first pane.   Other panes, like the armor (center), and systems, weapons and status pane (expand to fit), seem to be "aligned center" or "expand to fit".  See screens for examples. 
![Screenshot 2022-05-03 165250](https://user-images.githubusercontent.com/23645569/166574179-b4fd9dbf-23ca-45bc-a073-ccf041f2978f.png)
![Screenshot 2022-05-03 165220](https://user-images.githubusercontent.com/23645569/166574204-4e4608dc-99e6-428b-8909-efe56dd0e041.png)
![Screenshot 2022-05-03 165113](https://user-images.githubusercontent.com/23645569/166574462-c0c6dcee-92aa-48a2-9830-1923201c8e77.png)
![Screenshot 2022-05-03 170803](https://user-images.githubusercontent.com/23645569/166574475-564eadc9-cf04-45d2-afe6-4edc09f5913e.png)

**Comment by JonhyBurner** [comment]
I realized that although my unit panel also grows with time, it doesn't grow nearly as large as this. Since @Thom293 has a high resolution screen, it probably has something to do with it.

**Comment by Thom293** [comment]
Yeah it seems resolution related.  But it was a reasonable size in the last version.  Now its a bit oppressive.  :)
