### ISSUE TITLE
Flying VTOL must do piloting roll to avoid bugging down in mud

### ISSUE THREAD

**Issue by mwberlindeu** [MegaMek/megamek#3618]
###Environment
MekHQ version: 49.6

###Description
A piloting check was requested for a flying VTOL to avoid bogging down in mud 

![grafik](https://user-images.githubusercontent.com/28268113/166811037-0e413768-47b2-4d3c-b2eb-de65a3f678d6.png)
### Files
(Files of the battle were to complex for the case. If someone can point me to a muddy map (I could not recreate the mud condition), I can create a test file.)

**Comment by HammerGS** [comment]
Duplicate and related too https://github.com/MegaMek/megamek/issues/3499
