### ISSUE TITLE
MechSet Errors

### ISSUE THREAD

**Issue by Dylan-M** [MegaMek/megamek#363]
I had mentioned to @HammerGS that the included sample campaigns were having issues, I've discovered why. Someone ;) is being a "Windows User" again, and not watching the case matching in MechSet edits. The BattleMaster is a great example.

MechSet Entries:

> chassis "Battlemaster" "mechs/Battlemaster.gif"
> 
> exact "Battlemaster BLR-1D" "mechs/Battlemaster BLR-1D.gif"
> exact "Battlemaster BLR-1Gb" "mechs/Battlemaster BLR-1Gb.gif"
> exact "Battlemaster BLR-1Gbc" "mechs/Battlemaster BLR-1Gb.gif"
> exact "Battlemaster BLR-1Gc" "mechs/Battlemaster BLR-1Gc.gif"
> exact "Battlemaster BLR-1S" "mechs/Battlemaster BLR-1S.gif"
> exact "Battlemaster BLR-2C" "mechs/Battlemaster BLR-2C.gif"
> exact "Battlemaster BLR-3S" "mechs/Battlemaster BLR-3S.gif"
> exact "Battlemaster BLR-4L" "mechs/Battlemaster BLR-4L.gif"
> exact "Battlemaster BLR-4S" "mechs/Battlemaster BLR-4S.gif"
> exact "Battlemaster BLR-5M" "mechs/Battlemaster BLR-5M.gif"
> exact "Battlemaster BLR-6X" "mechs/Battlemaster BLR-6X.gif"
> exact "Battlemaster BLR-10S" "mechs/Battlemaster BLR-10S.gif"
> exact "Battlemaster BLR-10S2" "mechs/Battlemaster BLR-10S2.gif"
> exact "Battlemaster BLR-CM" "mechs/Battlemaster BLR-CM.gif"
> exact "Battlemaster BLR-K3" "mechs/Battlemaster BLR-K3.gif"
> exact "Battlemaster BLR-K4" "mechs/Battlemaster BLR-K4.gif"
> exact "Battlemaster BLR-M3" "mechs/Battlemaster BLR-M3.gif"
> exact "Battlemaster C" "mechs/Battlemaster C.gif"
> exact "BattleMaster BLR-4S (Calvin)" "mechs/Battlemaster BLR-4S.gif"
> exact "BattleMaster BLR-4S (Calvin II)" "mechs/Battlemaster BLR-4S.gif"
> exact "BattleMaster BLR-1G (Red Corsair)" "mechs/Battlemaster BLR-1Gb.gif"

All of which have "Battlemaster" with a lowercase "m".

When files are examined, we find instead:

> BattleMaster BLR-10S2.gif
> BattleMaster BLR-10S.gif
> BattleMaster BLR-1D.gif
> BattleMaster BLR-1Gb.gif
> BattleMaster BLR-1S.gif
> BattleMaster BLR-2C.gif
> BattleMaster BLR-3S.gif
> BattleMaster BLR-4L.gif
> BattleMaster BLR-4S.gif
> BattleMaster BLR-5M.gif
> BattleMaster BLR-6X.gif
> BattleMaster BLR-CM.gif
> BattleMaster BLR-K3.gif
> BattleMaster BLR-K4.gif
> BattleMaster BLR-M3.gif
> BattleMaster C.gif
> BattleMaster.gif

All of which have a uppercase "M". Windows may not give a shit, but Linux and OSX definitely do.

There are many more of these errors, but I just happened to find the BattleMaster one tonight while messing around. This affects 2 of our sample campaigns. I'm not sure if there are other issues, but I'm going to write a script that finds any discrepancies... actually just finished it and here's the output (shows my localclient_mechset.txt errors as well:

``` bash
$ ./test_mechset.sh 
Testing Official Mechset
File 'defaults/default_umu.gif' does not exist.
File 'AC/2 Carrier" "vehicles/ac2carrier.gif' does not exist.
File 'defaults/default_wheeled_heavy.gif"' does not exist.
File 'mechs/Battlemaster.gif' does not exist.
File 'mechs/Battlemaster BLR-1D.gif' does not exist.
File 'mechs/Battlemaster BLR-1Gb.gif' does not exist.
File 'mechs/Battlemaster BLR-1Gb.gif' does not exist.
File 'mechs/Battlemaster BLR-1S.gif' does not exist.
File 'mechs/Battlemaster BLR-2C.gif' does not exist.
File 'mechs/Battlemaster BLR-3S.gif' does not exist.
File 'mechs/Battlemaster BLR-4L.gif' does not exist.
File 'mechs/Battlemaster BLR-4S.gif' does not exist.
File 'mechs/Battlemaster BLR-5M.gif' does not exist.
File 'mechs/Battlemaster BLR-6X.gif' does not exist.
File 'mechs/Battlemaster BLR-10S.gif' does not exist.
File 'mechs/Battlemaster BLR-10S2.gif' does not exist.
File 'mechs/Battlemaster BLR-CM.gif' does not exist.
File 'mechs/Battlemaster BLR-K3.gif' does not exist.
File 'mechs/Battlemaster BLR-K4.gif' does not exist.
File 'mechs/Battlemaster BLR-M3.gif' does not exist.
File 'mechs/Battlemaster C.gif' does not exist.
File 'mechs/Battlemaster BLR-4S.gif' does not exist.
File 'mechs/Battlemaster BLR-4S.gif' does not exist.
File 'mechs/Battlemaster BLR-1Gb.gif' does not exist.
File 'mechs/Dola.gif' does not exist.
File 'mechs/Hellstar.gif' does not exist.
File 'mechs/Nightwolf.gif' does not exist.
File 'mechs/Onager.gif' does not exist.


Testing Local Client Mechset
File 'mechs/Phoenixhawk.gif' does not exist.
File 'mechs/phoenixhawk3.gif' does not exist.
File 'mechs/phoenixhawk3.gif' does not exist.
File 'unused/Wolfhound WLF-3S.gif' does not exist.
File 'unused/Wolfhound WLF-4WA.gif' does not exist.
File 'unused/Wolfhound WLF-3M.gif' does not exist.
File 'unused/Wolfhound WLF-4WA.gif' does not exist.
File 'unused/Wolfhound WLF-2H.gif' does not exist.
File 'unused/Wolfhound WLF-4W.gif' does not exist.
File 'unused/Wolfhound WLF-3S.gif' does not exist.
File 'mechs/deva_infernus.gif' does not exist.
File 'mechs/Rifleman RFL-8D' does not exist.
File 'mechs/Rifleman RFL-7X' does not exist.
File 'mechs/mKoshi (Mist Lynx) Z.gif' does not exist.
File 'mechs/Wolverine WVR-7D.gif' does not exist.
File 'mechs/shadowhawk5.gif' does not exist.
File 'vehicles/cyrano.gif' does not exist.


Testing Local Server Mechset
```

**Comment by Dylan-M** [comment]
Oh, this was tested against MekHQ 0.3.31, so it's possible that it's just an issue with files not being synced into MHQ correctly. I'll be looking into that after the release tomorrow morning.

**Comment by Dylan-M** [comment]
Oh, this one is fun:
```bash
File 'defaults/default_wheeled_heavy.png"' does not exist.
```
Simply has an extra quote on the end, and the double-double quotes breaks it.

**Comment by HammerGS** [comment]
Someone might want to check his repo, or check to see if MekHQ is pulling data correctly. Cause this "Windows" user runs the mechsettest on a regular basis to ensure that doesn't happen.

See image for current repo status
![image](https://cloud.githubusercontent.com/assets/13752452/19335494/0f0bfd44-90c1-11e6-8fde-4292fe192f45.png)

These where fixed here - Aug 10th.
https://github.com/MegaMek/megamek/commit/ee289c396c3339ce03a9890a20ebe6369637f81f#diff-0c71f679595a6420fd198b9d02ab7be9

**Comment by Dylan-M** [comment]
I just pulled MegaMek and ran my external test script, and it found more than the single one you're showing ;)
```bash
$ ./test_mechset.sh 
Testing Official Mechset
File 'defaults/default_umu.png' does not exist.
File 'AC/2 Carrier" "vehicles/ac2carrier.png' does not exist.
File 'defaults/default_wheeled_heavy.png"' does not exist.
```

**Comment by Dylan-M** [comment]
Actually, that middle one is an error in my script parsing picking up the AC/2 Carrier incorrectly. So, there are just the 2 outstanding. I'll look into MHQ syncing tomorrow.

**Comment by HammerGS** [comment]
The default umu has never worked in fact we don't even have an image for it and....

![image](https://cloud.githubusercontent.com/assets/13752452/19335722/9fd10256-90c2-11e6-931f-a964b09d8e31.png)

the other was fixed in MM.

**Comment by HammerGS** [comment]
Please check the MekHQ packaging.

**Comment by Dylan-M** [comment]
@HammerGS I did say I _just_ pulled the _MegaMek_ repo fresh and it's showing the one for the wheeled heavy. My script may have another issue that's causing it to print the " even if it isn't doubled, but I'm pretty tired so I'll have to look at it with fresh eyes in the morning.

**Comment by Dylan-M** [comment]
So, I found the wheeled_heavy issue, and there actually is an issue:
```bash
chassis "Teppo Artillery Vehicle" "defaults/default_wheeled_heavy.png""
```

My script didn't return a false positive there after all.

**Comment by Dylan-M** [comment]
Adjusting my script to output the unit name as well. Wee...!

**Comment by arlith** [comment]
The purpose of the `MechSetTest` app is to find things that cause problems with the mechset.  The double quote doesn't cause any issues with the way the code is written (the way the parsing is written, it handles this just fine), so I'm not inclined to do anything further with this.
