### ISSUE TITLE
RFE:  Docked Unit window - 2 separate window option.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/megamek#3639]
This was Discussed in Discord and Windchild asked me to post it here.

The "dockable" unit window was removed because of an issue with size (it had grown to take up a third of the screen) and perhaps some other issues.  It is my belief that it was 1 window that served two purposes (docked and undocked).

Instead, perhaps 2 mutually exclusive windows that serve 1 purpose each.  This should provide the same functionality by a different means.  And perhaps it would be eaiser to control each individual window.

So, instead of having a single "on the fly" dockable or undockable window.  Just have a menu option that says:  Docked unit window, or undocked unit window.  One or the other.  That way it could be two different windows, and hopefully easier to control the size of the docked version.  The docked version could be a finite size, and the undocked version could be just like the one we have now.  So perhaps splitting them would make it easier to control the size of the docked version.

Dont know if its even possible, but I do miss the docked window a lot because it provided a map edge on that side that was not occluded by the unit window at all.

Thank you.

**Comment by kuronekochomusuke** [comment]
implemented in #4030
