### ISSUE TITLE
LAMs register weapons incorrectly 

### ISSUE THREAD

**Issue by insanebotv21** [MegaMek/megamek#3646]
version 0.49.2
An ASF unit in fighter mode registers the weapon as it were one weapon. in this case 2 larges are represented as one bay that fires both for 16 heat but only does 8 damage.
[Introtech ASF TEST  Mek.zip](https://github.com/MegaMek/megamek/files/8720720/Introtech.ASF.TEST.Mek.zip)

**Comment by BLR-IIC** [comment]
Do you have the capital fighters option enabled for the aerospace rules?  What you describe sounds like that option is enabled and making this happen.

**Comment by insanebotv21** [comment]
yes i had the capital fighters option selected sorry for not noticing it sooner; disabling that option fixes the issue.
