### ISSUE TITLE
BadMatch (invalid parameter attributes) after battle, no salvage.mul created

### ISSUE THREAD

**Issue by jarniefjin** [MegaMek/megamek#365]
I did combat, got victory. After declared victory, and game asked that do I make salvage-file, where I answered yes, like I always do, megamek crashed. And I was back at commandline.
`$ cd Desktop/mekhq-0.3.31/;java -jar MekHQ.jar`
`Redirecting output to mekhqlog.txt`

`The program 'java' received an X Window System error.`
`This probably reflects a bug in the program.`
`The error was 'BadMatch (invalid parameter attributes)'.`
`(Details: serial 31875679 error_code 8 request_code 42 minor_code 0)`
`(Note to programmers: normally, X errors are reported asynchronously;`
`that is, you will receive the error a while after causing it.`
`To debug your program, run it with the --sync command line`
`option to change this behavior. You can then get a meaningful`
`backtrace from your debugger if you break on the gdk_x_error() function.)`
no salvage.mul created - timestamp was from previous game.
Because that was untouched, I concluded that crash was at megamek, not at mekHQ.

**Comment by jarniefjin** [comment]
I have these files saved, now I try to figure out how to upload: entitystatus.txt  gamelog.html  mekhqlog.txt

**Comment by pheonixstorm** [comment]
the txt should upload fine, not sure if it handles html files. You can always attach a zip file of them though including the save.
 |
 |
\/

**Comment by Dylan-M** [comment]
I'm not even sure this is an issue with MegaMek. It looks more like an issue with your X11 to me. Or an issue with whatever Java you're using. Information on exact OS, Java version, etc... will be useful.

**Comment by jarniefjin** [comment]
Again same ... I get these quite rarely, might be around every 20-30 MegaMek games.
`Redirecting output to mekhqlog.txt
The program 'java' received an X Window System error.
This probably reflects a bug in the program.
The error was 'RenderBadPicture (invalid Picture parameter)'.
  (Details: serial 36057638 error_code 143 request_code 139 minor_code 7)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
`
on `error`folder `entitystatus.txt  gamelog.html  mekhqlog.txt` are from previous games, according timestamps.

`$ java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)`

-----

`$ X -version

X.Org X Server 1.18.3
Release Date: 2016-04-04
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.13.0-92-generic x86_64 Ubuntu
Current Operating System: Linux jin-desktop 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.4.0-45-generic root=UUID=b65e33ef-e6d3-4329-9358-3176368cbd13 ro quiet splash
Build Date: 22 July 2016  07:50:34AM
xorg-server 2:1.18.3-1ubuntu2.3 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
`

-----

And yes, it might be just X11/OpenJava problem.
Maybe I have to put Oracle Java back to my system.

**Comment by Dylan-M** [comment]
It isn't likely to be an OpenJDK problem, unless it's an incompatibility between OpenJDK and your X11. I say that because both myself and @arlith are using OpenJDK on Linux. In fact, MegaMek is compiled with OpenJDK 8.

**Comment by arlith** [comment]
Did you try with the Oracle JRE? Have you updated graphics drivers since this happened?  Honestly, I don't really know what to do with this.  You could try looking in the logs/megameklog.txt or logs/mekhqlog.txt after this happens to see if anything is printed there.  Right now, all I can see is that something happened, but there's not any info that really tells me what.  I would hope our log files had more information, but I suspect they won't and there would be some other log you need to check, or some flag to set to get more logged info, but I don't really know what it is.

**Comment by Dylan-M** [comment]
A good flag to pass for this, to get actual logging info, is: `-Dsun.awt.noisyerrorhandler`

Which is probably something one of us should add to the wiki, but I'm on my way to bed.

**Comment by Dylan-M** [comment]
Oh, but from everything I've read, both when the was originally reported and now, this is an error in X and doesn't usually have anything to do with Java code unless you're calling X11 libs directly (we don't). That said, my opinion is to close it, and if the OP wants to to post with more info we can always re-open and re-evaluate.
