### ISSUE TITLE
[49.8 Testing Branch] NPE and CME after I manually closed MM session on round 1.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/megamek#3658]
00:13:31,752 INFO  [megamek.MegaMek] {main}
megamek.MegaMek.initializeLogging(MegaMek.java:115) - Starting MegaMek v0.49.8-SNAPSHOT
	Build Date: 2022-05-16T01:41:50.033873500
	Release Date: 2022-02-18
	Today: 2022-05-27
	Origin Project: MekHQ
	Java Vendor: AdoptOpenJDK
	Java Version: 11.0.10
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 2 GB

As title.  Again not certain if MM or MHQ issue.

[megamek.log](https://github.com/MegaMek/megamek/files/8784180/megamek.log)
[mekhq.log](https://github.com/MegaMek/megamek/files/8784181/mekhq.log)
[The Bluecoats30660127.cpnx.gz](https://github.com/MegaMek/megamek/files/8784190/The.Bluecoats30660127.cpnx.gz)
![Screenshot (453)](https://user-images.githubusercontent.com/23645569/170636321-7b3af41c-a3fe-43ac-925f-4d7cf970bdfa.png)

**Comment by Thom293** [comment]
Closed game, reloaded, started new MM session with same battle.  Arrow keys would not work to move around map.  Saved in MM and closed.  Got 3 Errors this time.  

I attach the MM save below.  MHQ save is same as above.

I think I will just manually resolve this one and move on.

[megamek.log](https://github.com/MegaMek/megamek/files/8784246/megamek.log)
[mekhq.log](https://github.com/MegaMek/megamek/files/8784248/mekhq.log)
[R1.sav.gz](https://github.com/MegaMek/megamek/files/8784249/R1.sav.gz)

**Comment by Thom293** [comment]
It just occurred to me - I had a player controlled allied unit on this mission and I assigned him some rockets in the lobby both times.  May not be related but its the only other oddity I can think of.

**Comment by Windchild292** [comment]
This has been resolved.
