### ISSUE TITLE
Game crash on Save/Load in Windows 10, but not Windows 8.1, MMHQ: 48.0, 49.6, 49.7, Adoptium: 17.0.2, 17.0.3

### ISSUE THREAD

**Issue by C337Skymaster** [MegaMek/megamek#3659]
Windows 10 crashes: Megamek HQ versions 48.0, 49.6, and 49.7, Eclipse Adoptium 17.0.2 +8 & 17.0.3 +7

Windows 8.1 non-crash: Megamek HQ version 49.7, Eclipse Adoptium 17.0.2 +8

In the setup page, any time I attempt to "load" or "export to MUL" a 'mech unit, the game crashes. I have multiple log files for 49.7, as well as one for each of the others. 48.0 worked well enough on Java 8 (whatever was the latest on the Oracle website), except for Princess getting hung on her movement phase at Company and Regimental sized battles, which didn't seem to happen anymore on 49.7, despite the Win8.1 computer being a much lower-powered laptop, so I'm trying to upgrade. :)
Once the crash exhibited itself on all three versions with the latest Adoptium, I attempted to copy the install file from my laptop to my desktop and roll back to that version, with the same end result.

Desktop (Homebuilt)
Windows 10 version 1803
i7-8700
GTX 1070 Ti
Samsung SSD, RAID1 (Mirror)

Laptop (Alienware/Dell)
Windows 8.1 
i7-4780MQ
GTX 765M
Samsung SSD (no raid at the moment, but supposed to be in Raid 1, mirror)

[hs_err_pid3124.log](https://github.com/MegaMek/megamek/files/8786573/hs_err_pid3124.log)
[hs_err_pid19360.log](https://github.com/MegaMek/megamek/files/8786574/hs_err_pid19360.log)
[hs_err_pid24656.log](https://github.com/MegaMek/megamek/files/8786575/hs_err_pid24656.log)
[hs_err_pid24732.log](https://github.com/MegaMek/megamek/files/8786576/hs_err_pid24732.log)
[hs_err_pid30852.log](https://github.com/MegaMek/megamek/files/8786577/hs_err_pid30852.log)
[hs_err_pid31416.log](https://github.com/MegaMek/megamek/files/8786578/hs_err_pid31416.log)
(All above from 49.7, both Adoptium versions)
[hs_err_pid33060.log](https://github.com/MegaMek/megamek/files/8786579/hs_err_pid33060.log)
(Above from 49.6, Adoptium 17.0.3)
[hs_err_pid32208.log](https://github.com/MegaMek/megamek/files/8786581/hs_err_pid32208.log)
(Above from 48.0, Adoptium 17.0.3)

Attempted "load" from non-Raid OS drive, same result: instant game crash. (No error report generated this time, though). Samsung NVME, 49.7, 17.0.2

**Comment by HammerGS** [comment]
We don’t support Java 17 only Java 11.

**Comment by C337Skymaster** [comment]
Ahhhh, maybe that's what I'm doing wrong. I just followed the link from your website. I'll go hunt around for Java 11, but if you have specific pointers, they're appreciated.

Thanks!

**Comment by Windchild292** [comment]
Can I get our logs (/logs/megamek.log and /logs/legacy.log primarily) for this? I don't have any MUL issues on the list for Java 17 at this point and could use the additional info.

**Comment by C337Skymaster** [comment]
[legacy.log](https://github.com/MegaMek/megamek/files/8787983/legacy.log)
[megamek.log](https://github.com/MegaMek/megamek/files/8787984/megamek.log)
49.7
[megamek.log](https://github.com/MegaMek/megamek/files/8787986/megamek.log)
49.6
[megameklog.txt](https://github.com/MegaMek/megamek/files/8787988/megameklog.txt)
48.0

Happy to help!

**Comment by C337Skymaster** [comment]
Came back to say: downgrading to Adoptium 11 fixed the issue. Thanks!

**Comment by Windchild292** [comment]
Closing based on the above, and thanks for the logs
