### ISSUE TITLE
[49.8 Testing Branch] If MM is manually closed before game end, MHQ Freezes and requires Taskmanager Close

### ISSUE THREAD

**Issue by Thom293** [MegaMek/megamek#3665]
15:10:33,331 INFO  [megamek.MegaMek] {main}
megamek.MegaMek.initializeLogging(MegaMek.java:115) - Starting MegaMek v0.49.8-SNAPSHOT
	Build Date: 2022-05-16T01:41:50.033873500
	Release Date: 2022-02-18
	Today: 2022-05-27
	Origin Project: MekHQ
	Java Vendor: AdoptOpenJDK
	Java Version: 11.0.10
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 2 GB

Again - hard to tell whether this is MM or MHQ issue.

As title.  Seems to be happening pretty often now.  Not every time.  But often.  Dont ever recall it doing it on previous builds.

Also - may be unrelated, but this is another situation where I loaded bombs on my fighters in the MM lobby.

![Screenshot 2022-05-27 173855](https://user-images.githubusercontent.com/23645569/170797216-2fc0fd37-0d3b-4fc4-919d-d56b18189a48.png)

[megamek.log](https://github.com/MegaMek/megamek/files/8790001/megamek.log)
[mekhq.log](https://github.com/MegaMek/megamek/files/8790002/mekhq.log)
[The Bluecoats30660129C.cpnx.gz](https://github.com/MegaMek/megamek/files/8790004/The.Bluecoats30660129C.cpnx.gz)

**Comment by Thom293** [comment]
Sorry - for the record was running the "Air Support" mission.  Space and Azure air lance and Blueshift arty lance.

**Comment by Thom293** [comment]
Just tried it again from a fresh restart.  This time I got 3 errors.  MHQ did not freeze though.  Could it be Aero/Bomb related?  That is what happened on bug report from yesterday too..
![Screenshot (454)](https://user-images.githubusercontent.com/23645569/170797868-1864174c-caa2-4874-b814-ec6af18a6863.png)
.

**Comment by Thom293** [comment]
Ok - just did it again but did not load bombs onto my fighters.  Closed MM with no issues, no errors.  Worked normally.

Bomb-ish?

**Comment by Thom293** [comment]
Tried to test again.  MHQ freeze even if I just close from MM lobby before making any changes at all.  Dunno.  Maybe it doesnt like one of my units or something.  They are all stock designs.

**Comment by Windchild292** [comment]
I'm pretty sure it's because of the connection race condition, as I've not been able to recreate with the fix.

**Comment by Windchild292** [comment]
The bomb one is unrelated and open on one of the trackers.

**Comment by Windchild292** [comment]
This has been resolved.
