### ISSUE TITLE
RFE Show unit tooltip summary in UnitDisplay

### ISSUE THREAD

**Issue by pakfront** [MegaMek/megamek#3695]
The unit tooltip is a great summary of a unit, would be nice to have the same info shown in the UnitDisplay to avoid having to page through the Tabs.

**Comment by pakfront** [comment]
I did a quick test and the simplest path to this is to replace the existing "SUMMARY" tab with the tooltip. We could also add the hex terrain tooltip here too, which would give elevation and other useful info.

I can add missing info to the tooltip and/or move it to another tabs. I thhik the missing info is Auto Eject, Current Sensors, Max Visual range. Woul those be neeed in the tooltip or can they be moved elsewhere?

old vs new
![old_display](https://user-images.githubusercontent.com/1423800/173255579-09dc3ef8-8253-4ebb-8e97-b1be836eb853.PNG)
![tooltip_display](https://user-images.githubusercontent.com/1423800/173255581-17e641f1-32f5-4053-aa69-1d6b3e865bc5.PNG)
.

**Comment by pakfront** [comment]
Or I could do a bit more work, move the current "General" tab to the end and call it "Details" or similar.

**Comment by Thom293** [comment]
Ok - I love this.  Formatting aside, a change like this would be very good.

If the pilots portrait could be added that would be even better.  Might take up too much room though.

**Comment by gsparks3** [comment]
I believe the current General tab in the unit display also shows unit quirks, if present. Would be good to verify if there's anything else it sometimes shows (depending on game options, etc).

**Comment by HammerGS** [comment]
Love this. Change the name of the tab to summary and it would capture it.

**Comment by pakfront** [comment]
I added portrait and confirmed relevant info is listed.
<img width="306" alt="Screen Shot 2022-06-19 at 9 53 12 AM" src="https://user-images.githubusercontent.com/1423800/174491954-46e7938a-0f03-4347-801b-5e1f2f40e325.png">

**Comment by pakfront** [comment]
Turns out renaming the tabs is a larger project as they are not just text labels, but are images in the skin packages. So it will remain "General" for the time being.

**Comment by HammerGS** [comment]
Without or without name changes this is a huge improvement and looking forward to seeing it in. Cheers!

**Comment by Thom293** [comment]
Yes.  Agreed.  Me wanty.  Very very nice.
