### ISSUE TITLE
Deadfire LRMs and SRMs have incorrect range brackets 0.49.8

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#3699]
I don't have my copy of IO on me, but at least according to Sarna.net, the deadfire LRMs and SRMs in MegaMek have the wrong range brackets.  MegaMek has the deadfire missiles as having the same range brackets and minimum range penalties as the regular missiles, while Sarna shows the following range brackets:

![image](https://user-images.githubusercontent.com/18338059/172277931-c30f305a-ef3a-4891-807a-ae401e5d9536.png)

**Comment by SuperStucco** [comment]
In earlier versions as well.  Confirming those are the ranges in IO first printing.

**Comment by gsparks3** [comment]
IO:AE (the most recent printing) page 212 gives dead-fire SRMs a minimum range of 0, but otherwise agrees with these range bands, damage values, and cluster sizes.
