### ISSUE TITLE
Incorrect passing of MegaMek options from MekHQ

### ISSUE THREAD

**Issue by monbvol** [MegaMek/megamek#37]
Campaign started fine but a few fights back for some reason when starting a fight in an AtB campaign the tech level under allowed units and equipment has been getting set to standard instead of experimental in MegaMek despite the MekHQ campaign having the same option set to experimental.

[mekhqlog.txt](https://github.com/MegaMek/megamek/files/141844/mekhqlog.txt)

[gamelog.zip](https://github.com/MegaMek/megamek/files/141848/gamelog.zip)
[Monbvol.zip](https://github.com/MegaMek/megamek/files/141849/Monbvol.zip)

[Tweek's Linemen.zip](https://github.com/MegaMek/megamek/files/141851/Tweek.s.Linemen.zip)

**Comment by Dylan-M** [comment]
Is this a MegaMek option in MekHQ, or is it a Campaign Option? (I'm at work, so I can't just fire it up and look)

**Comment by pheonixstorm** [comment]
Megamek option in HQ. Happened to me today (maybe yesterday but didn't notice. Mine is from the latest code and not the current release.

**Comment by Dylan-M** [comment]
This issue was moved to MegaMek/mekhq#21
