### ISSUE TITLE
[49.8] Heavy Medium Laser Requires 2 Weapon Slots on Aerospace Fighter ASF

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megamek#3700]
### Environment
	Build Date: 2022-05-27T12:45:51.888427300
	Release Date: 2022-02-18
	Today: 2022-06-07
	Origin Project: MegaMekLab
	Java Vendor: Eclipse Adoptium
	Java Version: 11.0.14.1
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMekLab: 8 GB

### Description
MegaMekLab shows that the Heavy Medium Laser requires 2 weapon slots on Aerospace fighters, but TechManual says it only requires 1 slot (TM p. 343).

### Files
Screenshot:
![HML ASF](https://user-images.githubusercontent.com/101755917/172405239-8b8a8b64-ed90-4935-9889-93d8262e2555.PNG)

**Comment by HammerGS** [comment]
Doing some digging (and don't remember seeing this before) but looks like ASF's pull the Mechslots. I think we need an AeroSlots like our Tank and SV Slots. If I'm missing something please point it out. (It's before the morning caffeine has kicked in)

**Comment by PhoenixHeart512** [comment]
This one appears to have been fixed with all the mechlab changes that have occurred between 49.8 and 49.19 and can probably be closed @HammerGS
