### ISSUE TITLE
[49.8] iATM Launchers Have Separate iATM Ammo For Standard Ammo Types

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megamek#3701]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
megamek.MegaMek.initializeLogging(MegaMek.java:115) - Starting MegaMek v0.49.8
	Build Date: 2022-05-27T12:45:51.888427300
	Release Date: 2022-02-18
	Today: 2022-06-07
	Origin Project: MegaMekLab
	Java Vendor: Eclipse Adoptium
	Java Version: 11.0.14.1
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 8 GB

### Description
(Submitting at the request of and as a result of discussions with Hammer)
improved ATM's (iATM's) according to the Interstellar Operations book (p. 60) use normal ATM ammo types in addition to the two "improved" ATM ammo types (inferno/magpulse). In the table on p. 55, it does not have a separate "iATM Standard/HE/ER" listing, just the normal ATM ammo plus the two iATM ammo.

MegaMek has separate "iATM Standard/HE/ER" ammo for the iATM launchers, which we are pretty sure is just because MegaMek doesn't know how to share one ammo entry with multiple different weapons, so iATM ammo was created for the iATM launchers as a workaround.

**Comment by Saklad5** [comment]
I think I have a fix for this, actually.
