### ISSUE TITLE
Some bombs not changing BV of certain aerospace units 0.49.8

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#3704]
When bombs are added to aerospace units (including LAMs) in the lobby, the unit's BV doesn't change accordingly.

**Comment by HammerGS** [comment]
Is it all bomb types or specific ones.

**Comment by BLR-IIC** [comment]
I played around with it more and found there are a few weapons that don't seem to affect BV on aerospace fighters that should, and other unit types are treated differently.  I'll provide some more details next week when I get more time to play around.

**Comment by BLR-IIC** [comment]
That's a very good question!  I assumed it was all of them after trying a couple I regularly use.  I did some further testing and found the BV calculation is affected depending on unit type.  For aerospace fighters, the following bombs don't recalculate BV:

- TAG pod
- Arrow IV Homing Missile
- Thunder bomb


For LAMs, the following don't recalculate BV:

- All external (bomb bay) ordnance


For conventional fighters, the following don't recalculate BV:

- TAG pod
- Arrow IV Homing Missile
- Thunder bomb


For VTOLs, the following don't recalculate BV:

- All external ordnance
