### ISSUE TITLE
49.8 - Corrected Nightshade mtf

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#3717]
Undertonned by 5 tons; had incorrect speed and missing cargo space.
Goes into the vehicles/3050U folder.

[Nightshade ECM VTOL (Standard).zip](https://github.com/MegaMek/megamek/files/8886857/Nightshade.ECM.VTOL.Standard.zip)

**Comment by HammerGS** [comment]
Fixed as part of https://github.com/MegaMek/megamek/commit/03601f8bdcc0e4ac9042378237c6d9040cb08ebd
