### ISSUE TITLE
[49.6] Stuck Mech able to kick

### ISSUE THREAD

**Issue by mwberlindeu** [MegaMek/megamek#3719]
**Environment**
MegaMek version: 49.6

**Description**
In our last match we had a "stuck" Mech (in mud) who was nevertheless able to "kick" in the physical combat phase which is propably counter intuitive (and propably against the rules). Unfortunately I do not have a savegame to share, and the condition is difficult to replicate.

**Comment by gsparks3** [comment]
The Bog Down rules on page 60 of Tactical Operations: Advanced Rules give no indication that kicks or any other physical attacks are prohibited, or otherwise affected in any way, so this is operating per the rules.

**Comment by HammerGS** [comment]
We've confirmed with CGL and errata is pending.

**Comment by gsparks3** [comment]
Ah, that works then.
