### ISSUE TITLE
[MHQ 49.9 Nightly #793] Princess hangs when prompted to unload stranded infantry

### ISSUE THREAD

**Issue by StowGnar** [MegaMek/megamek#3724]
This is occurring in the version of MegaMek bundled with multiple MHQ nightly builds, most recently Nightly # 793. I'm running Windows 10 Pro with Java version 11.0.13.

### Description
When an OpFor troop transport controlled by Princess becomes immobilized or otherwise stranded, the next turn begins with the usual prompt of:
"Please wait for another player to unload their stranded units..."
However, this prompt never ends. Princess does not seem to be responding in any way. Kicking the owner of the troop transports and using the "/replacePlayer -b:Princess" chat command can be done, but the prompt for Princess to unload the units remains there. The "/skip" command being sent at this stage seems to reliably generate uncaught exception popups as well.

To reproduce:
Using MHQ, load included campaign save. Navigate to Briefing Room, select 5/23 Breakthrough mission, select Load Saved Game, and load included savegame. This can also be reproduced by playing the mission proper, and immobilizing any troop-containing vehicle. One should be able to reproduce this anywhere, as I've experienced this hang in multiple missions.

### Files
[Princess Wont Unload.zip](https://github.com/MegaMek/megamek/files/8928889/Princess.Wont.Unload.zip)

**Comment by IllianiCBT** [comment]
I've also run into this issue in #794. The below archive includes a mid-game save where this issue has occurred. My experiences are identical to OP.

[Princess is Stranded.zip](https://github.com/MegaMek/megamek/files/8931167/Princess.is.Stranded.zip)
.

**Comment by IllianiCBT** [comment]
Is there any specific information that can be provided to assist investigating this issue?
