### ISSUE TITLE
[49.7] Magma crust breakthrough and liquid magma damage not working as expected

### ISSUE THREAD

**Issue by Gribbly1** [MegaMek/megamek#3727]
Bundled Megamek with MekHQ 0.49.7
Windows 10, Java Version: 11.0.13

[save1.sav.gz](https://github.com/MegaMek/megamek/files/8959816/save1.sav.gz)
![image](https://user-images.githubusercontent.com/55139229/175093778-167eaf42-9fac-4391-8316-d56a9fc9d599.png)

![image](https://user-images.githubusercontent.com/55139229/175093971-8cd41904-d6ae-4e54-8c42-4a9dbdac5557.png)

![image](https://user-images.githubusercontent.com/55139229/175094152-7034e1e9-78e6-4a11-889f-54a5716b1f33.png)

**A)** MM seems to check for breaking through a magma crust when turning in that hex, when it should only check upon entering the hex.

[save2.sav.gz](https://github.com/MegaMek/megamek/files/8959874/save2.sav.gz)

![image](https://user-images.githubusercontent.com/55139229/175094627-6ba7084b-1a1c-415b-b1a5-940d74dc3b0b.png)

**B)** No damage is being applied for breaking through the crust until leaving the hex the following turn. If the crust breaks and converts to liquid magma the exposed locations should take damage immediately in the movement phase where that occurs. 

The wording of the rule (TacOps advanced ground movement) is that damage should be caused when starting a movement phase in liquid magma or if entering the hex. I guess this might be an issue with the order of movement and determining when the hex becomes magma - strictly the unit enters a crust hex first, which then changes. 

**C)** Also the additional second damage amount is not being applied for starting and ending the movement phase in liquid magma.

**Comment by pheonixstorm** [comment]
Additionally the heat effect of moving over the magma crust is not applied correctly. It is not counting moving into the first crust hex. In my test I moved 3 hexes, all of them were crust hexes starting from a non crust hex.
![crust_walk](https://user-images.githubusercontent.com/1787879/178098649-d83d7a10-728f-45d1-991e-4d4bd5854b0a.png)

Also, end of turn an extra 5 heat was added for magma. Crust didn't break, so where did the magma come from??
![magma](https://user-images.githubusercontent.com/1787879/178101538-59911165-a9b1-4fc6-acfc-275e788d1ea1.png)

Next pic shows move from round one (above heat) and this rounds move
![turns](https://user-images.githubusercontent.com/1787879/178101711-7dee9a48-fb45-4715-aa18-0471d7022e02.png)

Next pic end of movement phase shows the crust breaks and becomes magma. No damage or heat for first two movement and the unit becomes stuck. Unless the rules have changed (I do not have the current TO rules book), the unit should only become stuck if it had jumped (TO pg 37, 62 magma and bogdown sections). 
![crust_break](https://user-images.githubusercontent.com/1787879/178101991-594a1570-bb4f-4758-9b69-66366484fe12.png)

Save
[magma.sav.gz](https://github.com/MegaMek/megamek/files/9076376/magma.sav.gz)

**Comment by Gribbly1** [comment]
Excellent, thanks very much.
