### ISSUE TITLE
Change Lobby Map selection from right click to left click. 

### ISSUE THREAD

**Issue by pakfront** [MegaMek/megamek#3729]
### Environment
Starting MegaMek v0.49.9-SNAPSHOT
	Build Date: N/A
	Today: 2022-06-22
	Origin Project: MegaMek
	Java Vendor: Homebrew
	Java Version: 11.0.15
	Platform: Mac OS X 12.4 (aarch64)
	System Locale: en_US
	Total memory available to MegaMek: 4 GB

### Description
on macOS, it seems impossible to trigger a right-click in the map selection tab of the lobby on a trackpad. In addition, even on PC, the right click is counter-intuitive and trips me and others up pretty often. Changing it to left-click for the popup would be more robust and, I think, more intuitive.

**Comment by Windchild292** [comment]
Transferred to the MegaMek tracker, as this is a MM issue. Reassigned and labelled it
