### ISSUE TITLE
LargeTexture.tileset completion

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#373]
Added Jungle:1-3 terrain back into tilesets (my bad).
Changed jungle theme to tropical which makes more sense.
New tropical/jungle pngs for bw_atmospheric and largetexture tilesets.
Added bldg_basement_type:* terrain for issue #390 
Made new gifs for pavement_6:8(were solid dark colors with no texture like 0-5)
Flipped the pavement images light/dark for bw_atmospheric and largetexture.
Added @SirMegaV 's singlehex buildings into the singlehex folder and into the standard buildings
Reordered the pavement lines to -3 : 10 like how all other terrain types are written in the tilesets.
Switch positions of lunar and mars themes in standardthemes so that when a base terrain is not found it will display redish mars plains (more obvious when theres a problem).
Updated contributors file (for largetexture images)
Changed largetexture woods to the isometric woods.
https://drive.google.com/open?id=0Bz2R9oe3rM_bSXJyUkQ4alBrSVE

No theme
![image](https://cloud.githubusercontent.com/assets/16950832/19991534/31d57266-a204-11e6-8289-dc634c1dbc45.png)

Grass
![grass](https://cloud.githubusercontent.com/assets/16950832/19465636/5450482a-94cb-11e6-80bc-759b796035e8.png)

Snow
![snow](https://cloud.githubusercontent.com/assets/16950832/19465641/5a8597cc-94cb-11e6-8344-9424f44026bc.png)

Lunar
![lunar](https://cloud.githubusercontent.com/assets/16950832/19465648/6380efc0-94cb-11e6-86e6-7b2b44c2c7d6.png)

Mars
![mars](https://cloud.githubusercontent.com/assets/16950832/19465652/67f99304-94cb-11e6-83f7-8f052f581f0a.png)

Volcano
![volcano](https://cloud.githubusercontent.com/assets/16950832/19465657/6de7909a-94cb-11e6-813d-e60c0d8a7fbb.png)

**Comment by BLOODWOLF333** [comment]
Alternate water idea? .....meh

![grass](https://cloud.githubusercontent.com/assets/16950832/19500362/fe1de6dc-9561-11e6-9038-ec777aa07bbc.png)

**Comment by BLOODWOLF333** [comment]
This one is better

![grass](https://cloud.githubusercontent.com/assets/16950832/19500546/eb2ab634-9563-11e6-8d1b-485b22f52ac6.png)

https://drive.google.com/open?id=0Bz2R9oe3rM_bSkhaTEFNOVRFQUU

**Comment by SirMegaV** [comment]
Smoothen/blur the image? I find it a bit 'hard'.

**Comment by VampireSeraphin** [comment]
Blood, your no theme set is more red than your mars set. Whats up with that?

**Comment by BLOODWOLF333** [comment]
No theme doesnt look to have a red tint at all to me, thats all brown.  I like it........does anyone even use the largeTexture.tileset?

**Comment by BLOODWOLF333** [comment]
Now im thinking about changing the notheme plains on my tileset to brown as well and then jungle for both sets would have a more sand color/looking base tile to represent tropical regions on planet while notheme would be for temperate.  Going for realism.

**Comment by VampireSeraphin** [comment]
No theme should probably been more light tan, similar to the simple theme. But with much more variance than the Hq_atmospheric, which is so repetitive it looks like cloth.

**Comment by BLOODWOLF333** [comment]
More of a tan dirt NoTheme
![example](https://cloud.githubusercontent.com/assets/16950832/19541611/2ccd28e6-962d-11e6-863b-3ac6b8577fbb.png)

More of a sand NoTheme
![github](https://cloud.githubusercontent.com/assets/16950832/19541622/3d1318c8-962d-11e6-8845-17787b123299.png)

**Comment by VampireSeraphin** [comment]
That looks much better. How does it look with your original water?

**Comment by BLOODWOLF333** [comment]
AJ didnt like the original water so.....


________________________________

**Comment by VampireSeraphin** [comment]
Really? Interesting. The first is much more natural looking.

**Comment by BLOODWOLF333** [comment]
Less BLUE second version of the water, going with the sand texture for notheme plains
![example](https://cloud.githubusercontent.com/assets/16950832/19544241/358504fc-9643-11e6-89cd-9a216f2246b3.png)

Original water and what I like.  Im going with this one sorry @akjosch it will be ok.
![github](https://cloud.githubusercontent.com/assets/16950832/19544253/4ae89bce-9643-11e6-8ee1-a005dab59757.png)

**Comment by BLOODWOLF333** [comment]
Jungle woods largetexture
![example](https://cloud.githubusercontent.com/assets/16950832/19545502/7d833130-964c-11e6-8af5-1dc43bbde1e7.png)

Jungle woods bw_atmospheric
![github](https://cloud.githubusercontent.com/assets/16950832/19545509/86acd36a-964c-11e6-8a74-2a679c59b704.png)

https://drive.google.com/open?id=0Bz2R9oe3rM_bSkhaTEFNOVRFQUU

**Comment by VampireSeraphin** [comment]
large texture looks good with the original water+toned down dirt bw.

**Comment by BLOODWOLF333** [comment]
Bigger "tropical woods" couldnt fight mechs in an 'actual" jungle anyways since there wouldnt be enough room right?
![example](https://cloud.githubusercontent.com/assets/16950832/19581659/45336e00-96f4-11e6-8427-1857b37f820e.png)

![github](https://cloud.githubusercontent.com/assets/16950832/19581662/4de09ce4-96f4-11e6-9dae-cd810da6a395.png)

https://drive.google.com/open?id=0Bz2R9oe3rM_bSkhaTEFNOVRFQUU

This is finished.

**Comment by BLOODWOLF333** [comment]
https://drive.google.com/open?id=0Bz2R9oe3rM_bSkhaTEFNOVRFQUU
@VampireSeraphin made a good suggestion.  Iso woods match the largeTexture look better.
![example](https://cloud.githubusercontent.com/assets/16950832/19615685/bed32eb0-97c8-11e6-9ec5-ec708792b6ef.png)

**Comment by BLOODWOLF333** [comment]
Fixed tilesets with jungle:1-3 put back into them.

[jungle.zip](https://github.com/MegaMek/megamek/files/552136/jungle.zip)

**Comment by BLOODWOLF333** [comment]
https://drive.google.com/open?id=0Bz2R9oe3rM_bSkhaTEFNOVRFQUU
That has everything

**Comment by BLOODWOLF333** [comment]
https://drive.google.com/open?id=0Bz2R9oe3rM_bSkhaTEFNOVRFQUU

Put Jungle:1-3 back in all tilesets.
Changed ThemeJungle to ThemeTropical for all tilesets and the standardincludes
Completed largetexture tileset.

**Comment by BLOODWOLF333** [comment]
How pavement looks when flipped with the bw_atmospheric and largeTexture.tilesets.  Also some of sirmegav's buildings.
![example](https://cloud.githubusercontent.com/assets/16950832/20040308/5578d15a-a41a-11e6-910f-da12ef18c217.png)
