### ISSUE TITLE
Savegame from lobby does not save MapSettings

### ISSUE THREAD

**Issue by pakfront** [MegaMek/megamek#3731]
### Environment
MegaMek v0.49.9-SNAPSHOT

### Description
When a game is saved from the lobby, the map choice is not saved. This is because MapSettings are in the ChatLounge, not in the Game.  Moving the MapSettings to Game and serializing them into the savegame may fix this.

This bug may also affect GameOptions

**Comment by Windchild292** [comment]
Resolved in #3751
