### ISSUE TITLE
0.49.7 ArrayIndexOutOfBoundsException on starting new MegaMek game

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#3738]
(Doing what the error message told me to!)

MegaMek 0.49.7 from the MHQ bundle version.
Windows 10
Java 11 (Eclipse Adoptium 11.0.14.1)

Fired up MegaMek, clicked 'Start New Game', filled in the pop-up, and this error message appeared on an empty window, without the lobby loading.

![image](https://user-images.githubusercontent.com/26851644/175828949-51aa6d4a-91dd-453e-82c7-d434eed46ab2.png)

No save.gz file because the game hadn't started - the lobby hadn't loaded at this point, just a white screen.

[logs 20220626-1933.zip](https://github.com/MegaMek/megamek/files/8987259/logs.20220626-1933.zip)

**Comment by Windchild292** [comment]
Duplicates https://github.com/MegaMek/mekhq/issues/3167, fixed in #3605
