### ISSUE TITLE
[Newest Version] TMM message in pop-up tooltip is yellow and very difficult to read.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/megamek#3743]
Posting as requested by pakfront.

I was running some tests on Princess not using the search behavior through my IDE and ran across this super new feature.  It is fantastic.  Thank you.

However, the new TMM message in the pop up was unreadable at least on default settings.  I think it is intended to change it to a color readable in all themes.  Here is the screen.

EDIT:  Im running MM through IDE.  So I presume this is the default theme.  Not 100% certain though.

![Screenshot 2022-06-28 014913](https://user-images.githubusercontent.com/23645569/176207038-d20d3af3-5f45-48ee-beb2-9f4dd7f9a758.png)

**Comment by Thom293** [comment]
FYI this yellow color also seems to change the "Seen by X" text also.  Not sure if that was the prior behavior
![Screenshot 2022-06-29 202903](https://user-images.githubusercontent.com/23645569/176573360-c37441b3-bc7f-428a-a2d4-96ef656aff37.png)

**Comment by Windchild292** [comment]
Resolved in #3755
