### ISSUE TITLE
Popup unit overview requires line wrapping for 'seen by' with large numbers of forces

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#3747]
In a 49.7 game with a lot of different forces, the 'seen by' line ends up blowing out the width of the unit popup:

![Seen-by line wrap](https://user-images.githubusercontent.com/70451747/176510088-b44445ec-0423-44bc-aefb-0d9f7d683809.png)

Good line wrapping would help keep this at a reasonable width.

**Comment by SuperStucco** [comment]
That's a good point.  The list as it is, looks like it stays constant throughout the game i.e. once spotted the team is added to the list.  Personally I wouldn't mind having it changed to a dynamic list of who can see it that round.  The green U (for unseen units) and H (for currently hidden units) text next to each unit means the 'seen by' list, of any type, somewhat redundant.

**Comment by Thom293** [comment]
I ran into this this morning.

I believe the list is dynamic already.  When i was testing singleblind, Princess would show up as a spotter.  and when I disabled it she would disappear.  It doesnt refresh until you hit  "done" for a step though.

Maybe:

Seen by Player: 1, 3, 5.

That should shorten it enough and you could get the name of the player by /who if it was important.

**Comment by cam-smith** [comment]
Showed up in Joker's stream (2022-09-09 discussed at ~1:30:00)

**Comment by JonhyBurner** [comment]
Can I suggest that it shows "Seen by Team X - Player Y, etc."? More informative, and still short. Gives more information when multiple players are around without the need to keep spamming /who.

**Comment by kuronekochomusuke** [comment]
is this still an issue?

**Comment by SuperStucco** [comment]
> is this still an issue?

Haven't tried it in post 49.7 releases, as I'm holding off on upgrading a bit longer.

**Comment by HammerGS** [comment]
> is this still an issue?

I believe it is as I don’t recall anyone touching this.

**Comment by kuronekochomusuke** [comment]
this is what it shows for me in 0.49.10

![image](https://user-images.githubusercontent.com/116095479/200972250-b090e678-be18-46f5-ae97-1d013d152f4f.png)

**Comment by HammerGS** [comment]
I think it shows with a lot of units.

**Comment by gsparks3** [comment]
It lists each "player" that can see the unit (including distinct bots), not each unit. Try it with 12 differently named bots.

**Comment by kuronekochomusuke** [comment]
so it is probably still an issue

**Comment by Thom293** [comment]
My MHQ computer is dead right now, but the way to test if it is still there is to play double blind with multiple enemies, and do /singleblind for each bot.  That will populate the list fully.

**Comment by kuronekochomusuke** [comment]
i can now reproduce it.

**Comment by kuronekochomusuke** [comment]
corrected by #3971
