### ISSUE TITLE
[49.7] Infantry BV calculation for encumbering armour

### ISSUE THREAD

**Issue by Gribbly1** [MegaMek/megamek#3748]
Bundled Megamek with MekHQ 0.49.7
Windows 10, Java Version: 11.0.13

Megamek currently calculates infantry BV incorrectly for infantry wearing encumbering armour. 

Infantry incapable of making anti mek attacks don't pay the BV for the anti mek step in the calculation.
https://bg.battletech.com/forums/techmanual/anti-mech-bv-questions/msg1845225/#msg1845225

None of the infantry wearing ballistic plate on the MUL match the BV in megamek, for example:
http://www.masterunitlist.info/Unit/Details/1449/heavy-support-infantry-irian-technologies-swat-team
![e bv](https://user-images.githubusercontent.com/55139229/176518152-6511b963-7235-43e3-a91d-3e024dc35f1f.PNG)

**Comment by IllianiCBT** [comment]
Can you confirm whether this is an issue *just* in MM, or whether the issue also exists in MML for these units?

**Comment by Gribbly1** [comment]
It's in both.

**Comment by Gribbly1** [comment]
Looks like anti-mech BV is being added for Field Gun platoons too, which can't make anti-mech attacks.

**Comment by Gribbly1** [comment]
BV calculations for 4/8 infantry in general (not anti-mech trained, but capable) are also incorrect. Gunnery 4, anti mech 8 units should have 85% BV.

![image](https://user-images.githubusercontent.com/55139229/181935441-8a6b5c70-cabc-4f3d-a340-631bb2999f5e.png)
