### ISSUE TITLE
RFE - Make /Seeall work for non-observers or have option to force Princess as an observer.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/megamek#3749]
Pursuant to a discussion on discord, one or both of the following options:

Option 1, suggested by Look-Busy Loop, Pakfront and Illiani:

- remove requirement from seeall that person must be an observer
- add consent requirement to seeall, copying code from /defeat
- if consent is given seeall fires, else it throws up a chat box error saying it failed due to lack of consent

Option 2:  EDIT: I DONT THINK THIS ONE WILL WORK.  I tried to set her as an observer while she had units, and she could not deploy.

Make princess have a tick box to give her a flag so she can be set as an observer by the game manager, or force-set her as an observer-with-units in the lobby.  

Then the current /Seeall command might work to give her vision of the whole map.

Perhaps making Princess an observer-with-units and then using the /seeall command on her would give the single-blind effect.  Or, making her an observer-with-units MIGHT break a bunch of stuff.  Dont know.

**Comment by IllianiCBT** [comment]
Related to: https://github.com/MegaMek/megamek/issues/203

**Comment by Thom293** [comment]
The first /Seeall option appears to roughly work.  

Look-Busy Loop was kind enough to point me to a salient section of code.  I deleted some things.  Tested twice and appears to work.  

Tested vs 2 princess bots on same team.  A and B.  I waited 10 turns, and they never approached.  On turn 10 gave PrincessA the /seeall 1 command, and a few turns later she pops over the hill coming for me.  Princess B did not immediately approach, but eventually she did.  I assumed if I gave seeall to A and the share vision option is enabled, B would have seen me immediately too?  

Anyway - here is the code Look-Busy Loop showed me, and the 2nd shows what I deleted.  No idea if  I over-deleted or if anything else was broken as a result.  Id have no idea how or where to add any consent code.

From megamek\common\Player.java file.

![Screenshot 2022-06-29 221108](https://user-images.githubusercontent.com/23645569/176586425-6d99f185-74d1-451a-9d43-e97d652e1d2d.png)

![Screenshot 2022-06-29 215150](https://user-images.githubusercontent.com/23645569/176586450-41b469cd-9365-4077-98d0-c3c93a22715f.png)

**Comment by IllianiCBT** [comment]
This definitely looks like it has potential. My biggest, and only, concern is whether there is interactions with other systems that aren’t immediately obvious.

Without looking at the code myself, I won’t even guess.

**Comment by Thom293** [comment]
Yes.  I honestly have no idea how to actually read the code.  I just took a machete to the part I was directed, and I would guess a machete probably broke something.  Someone that actually knows what they are doing should look at it.  I make no representations as to its usefulness beyond the above.  :)

But you guys came up with an idea that seems to work for single-blind, at least on its face.  Maybe someone can make it work.
