### ISSUE TITLE
LAM Actuator Validation

### ISSUE THREAD

**Issue by XanKortal** [MegaMek/megamek#3765]
### Environment
What version of MegaMek does your issue apply to?  0.48.0 megameklab
What operating system are you using?  Windows
What java version are you using?  Java 17

### Description
LAM construction requires lower arm actuators for validation in megameklab

Under Interstellar Operations: Alternate Eras construction rules (pages 108 and 109), no such requirements exist in construction, and no such limitation is mentioned in the official errata.

The gameplay rules explain what happens as a result of having lower arm actuators critically hit - cannot convert to/from battlemech mode (pages 101 and 104) - but not having a lower arm actuator during construction does not count as a critical hit for any penalties suffered (Total Warfare page 127)

For an official sheet comparison: Champion LAM (from XTRO Boondoggles) is missing its Lower Arm Actuators, but has no Illegal Design quirk associated with it. It only has Illegal Design for being a 60 ton LAM.
(For comparison, in the same book, the BSE X2 Banshee does list multiple Illegal Design quirks, each for the respective illegal aspect - the "Dual Engine", and the "VTOL equipment on Aerospace unit" are two seperate instances of Illegal Design)

**Comment by HammerGS** [comment]
This was actually errata from the upcoming IntOps reprints. 

https://bg.battletech.com/forums/errata/interstellar-operations-alternate-eras/msg1846780/#msg1846780
