### ISSUE TITLE
Are You Sure You Want To Quit MegaMek?

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#377]
May we please have a "are you sure you want to quit MM" pop up......i just accidently closed my MM game because I thought I was in the MS paint window which I pasted a screenshot into (honest mistake).  HQ does it and is more forgiving for the players.

**Comment by Qwertronix** [comment]
I would also add the option to save the current game/MUL to the prompt. Basically the usual "Would you like to save <blah> before quitting MegaMek? Yes/No/Cancel".

**Comment by MGM175** [comment]
Definitely the second option would be better.
