### ISSUE TITLE
fluff not rendering under Sax or HQ Sax

### ISSUE THREAD

**Issue by sshagent** [MegaMek/megamek#3775]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
MekHQ's megamek.  0.49.9 snapshot nightly build 813 
Win 10
Java Vendor: Eclipse Adoptium
Java Version: 11.0.15

### Description
Open up "Select Map".  Browse 64x68 and select "Snow Hill Fort Logistics"
![image](https://user-images.githubusercontent.com/1290412/177973156-3a81e31f-ef3d-4447-9447-69ff1032278f.png)

The default tileset looks like the image above.  if you switch to HQ sax it is the same.  Iso and Atmos, plus HQ are all fine.  Like this.
![image](https://user-images.githubusercontent.com/1290412/177973374-e8f6f6d4-c08d-4234-b368-bcd400857b54.png)

Here is what those tiles look like in the .board file
james-pa@stimpy:/mnt/e/Games/mekhq-0.49.9_snapshot_813/data/boards/unofficial/UlyssesMaps$ grep ";fluff:80" 64x68\ -\ Snow\ -\ Hill\ Fort\ Logistics\ Hub.board
hex 1714 0 "woods:1;pavement:1;foliage_elev:2;fluff:80:16" "snow"
hex 2015 0 "woods:1;pavement:1;foliage_elev:2;fluff:80:19" "snow"
hex 1316 0 "woods:1;pavement:1;foliage_elev:2;fluff:80:22" "snow"
hex 1217 0 "woods:1;pavement:1;foliage_elev:2;fluff:80:12" "snow"
hex 1617 0 "woods:1;pavement:1;foliage_elev:2;fluff:80:21" "snow"
hex 1118 0 "woods:1;pavement:1;foliage_elev:2;fluff:80:11" "snow"
hex 1919 0 "woods:1;pavement:1;foliage_elev:2;fluff:80:20" "snow"

I originally found this for some newer maps in the discord channel which were using fluff:80:4 and had the same issue.
A lot of other fluff:XX numbers seem to render in okay.  So perhaps point to fluff:80 being weird.

Lastly i can confirm that i 7zip extracted the snapshot, so this isn't an extraction error.  

My previous 0.49.8 snapshot version didn't suffer this issue.  I'm not sure which snapshot i got from that, but if that is important let me know how to figure that out from my files/directories and i'll report back.

Anyway i hope thats enough info.

**Comment by SJuliez** [comment]
It renders fine for me in the current repo version:

![image](https://user-images.githubusercontent.com/17069663/179387580-d0ae0b72-0f00-4f8c-bd59-b56cd1633ccb.png)

**Comment by sshagent** [comment]
Which one do you mean but "current repo version"?  
I've just tried nightly 826 and thats still an issue.

**Comment by HoneySkull** [comment]
I'm curious if this works when run from a MekHQ distribution vs. a strait MegaMek distribution.

**Comment by sshagent** [comment]
I am using the mekhq, megamek releases.  
I was told that we the best way to utilise megamek, and have mentioned mekhq build above. 
This is my first qa thing, so feedback on my opening issue Creaton is welcomed. 

Happy to test a detect megamek release, if needed?

**Comment by SJuliez** [comment]
The current repo version means the version that is fully up to date, opened in the Java IDE. This looks like it's a problem of packaging the images for the mekhq build.

**Comment by sshagent** [comment]
This is still an issue with mekhq nightly snapshot #862

**Comment by sshagent** [comment]
With todays 0.49.10 release, this is actually fixed.  Thanks guys.
