### ISSUE TITLE
[RFE] Add 0 (zero) as a selectable weapon/equipment quantity in Open unit, advanced search

### ISSUE THREAD

**Issue by rickremer** [MegaMek/megamek#3776]
MegaMek & MegaMekLab v 0.48.0
(not going thru MMHQ)
Windows 10 Home
Java v 8 upd 311

![Screenshot 2022-07-08 083024](https://user-images.githubusercontent.com/47697445/178001974-36952838-507d-4a44-9390-5bc69f30259c.png)
[screencap shows 'Mech Mortar 4 with no 'zero' at top of quantity pulldown]

Please add 0 (zero) as a selectable weapon/equipment quantity in Open unit, advanced search.  For example, one might wish to look for units with no SRM type weapons, criteria might be "0 SRM 6 And 0 SRM 4 And 0 SRM 2".

**Comment by Seosaidh** [comment]
I would like to second this feature.

**Comment by Seosaidh** [comment]
PR #3901 opened.

**Comment by SJuliez** [comment]
Implemented. Therefore closing this.
