### ISSUE TITLE
BattleMaster BLR-1GHE missing from IS TW Non-Box Set selection 0.49.8

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#3779]
The BattleMaster BLR-1GHE is missing from the unit selection for IS TW Non-Box Set.  Per the MUL it's considered "Standard" rules level.

![image](https://user-images.githubusercontent.com/18338059/178282301-8725390b-98d8-4dfe-8dfc-80de6cfd25e0.png)

![image](https://user-images.githubusercontent.com/18338059/178282530-abfa27d7-62a5-409b-a71e-743efe0a8158.png)

**Comment by HammerGS** [comment]
It is in MegaMek under Experimental tech. 
![image](https://user-images.githubusercontent.com/13752452/178291162-38941fc3-11d7-4534-87d7-6e53aec16deb.png)

The unit is from ERA Report 2750 and doesn't have a record sheet or intro date. So we have approximated the units stats and intro date. I've updated it to an advanced unit but until we have a RS and more official (canon) information on it not much else can be done.
