### ISSUE TITLE
TacOps rule for AMS being used as a weapon

### ISSUE THREAD

**Issue by TigerShark** [MegaMek/megamek#378]
As per TacOps, p. 100, the Anti-Missile System can be used as a 1-hex-ranged machine gun (2 damage, 0 heat). A few developers remember including thiscode, but it is either not functioning or was misremembered as being already-implemented.

**Comment by TigerShark** [comment]
Any progress on this one?

**Comment by mkerensky** [comment]
It can be assigned to me. I work with AMS and weapon modes a fair amount.   Still might be a while before I get to it.

It might be fairly simple, and it might require an update to all the AMS code to account for a new 'manual' state.

**Comment by mkerensky** [comment]
This has been written. You should see it in the next development release.
