### ISSUE TITLE
Artillery may not be using double and single blind correctly in some cases

### ISSUE THREAD

**Issue by pakfront** [MegaMek/megamek#3784]
MegaMek v0.49.9-SNAPSHOT
In GameManager,createArtilleryPacket there is a test against getSingleBlind and getSeeAll that probably should be against isSingleBlind and canSeeAll. The former (get) does not check if the modes are valid, only if they are set, the latter does the check for validity.

```
                if ((aaa.getPlayerId() == p.getId())
                        || ((team != Player.TEAM_NONE)
                        && (team == game.getPlayer(aaa.getPlayerId()).getTeam()))
                        || p.getSingleBlind() || p.getSeeAll()) {
                    v.addElement(aaa);
                }
```

**Comment by Thom293** [comment]
I trust you completely on the matter.  I simply tried to copy the seeall format exactly, so if it had underlying oddities, then singleblind probably does too.
