### ISSUE TITLE
RAT Generator Intermittently Does Not Populate Faction List

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#379]
Was working the last time I loaded this save. Now doesnt populate, makhqlog has a whole block of listening for clients nullx1,000. Then a: 
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
at megamek.client.ratgenerator.UnitTable.generateTable(UnitTable.java:97) 
On this second time of attempting to load my save I just created tonight.
![image](https://cloud.githubusercontent.com/assets/16950832/19612267/39ca7fe2-97ab-11e6-80d2-19ebc1f21e4b.png)

AFFS-FSAC-2REG-2BN-ECO
[RATgeninop.zip](https://github.com/MegaMek/megamek/files/545271/RATgeninop.zip)

**Comment by BLOODWOLF333** [comment]
I have been able to reliably reproduce this.  Create random army>RAT generator> change year to 3016(why does this not auto set to whatever the game year is?) and then faction, command, and unit rating fields will all be empty until i check the box for show minor factions to get it to wake up.

**Comment by neoancient** [comment]
I couldn't reproduce it.

**Comment by BLOODWOLF333** [comment]
Yeah I may have spoke too soon.  It did it about three times in a row for me then had to restart HQ because of the "not deploying a unit that ejected last scenario" bug and then it started working again.  Had been playing HQ all day long before that.

**Comment by BLOODWOLF333** [comment]
I see this every now and then in 0.42.0 but the work around is just to click one of the other options thats a check box and not a dropdown to get everything to repopulate.
