### ISSUE TITLE
RAT Generators don't generate units in their introduction year.

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#3791]
From the post.

https://bg.battletech.com/forums/megamek-games/not-understanding-the-rat-generator

I vaguely recall a conversation with @neoancient when this was being developed around intro year and units appearing. Not sure if its something to reconsider or an actual bug. 

Based on what I've seen of the ilClan factions some have pretty short lifes combined with new units from Rec Guides I'm thinking it might make sense to have units appear in the Generator during their intro year.

**Comment by neoancient** [comment]
I'm pretty sure they can appear during their intro year, but at a reduced availability. If they're not appearing the number may be too low.

**Comment by HammerGS** [comment]
Just ran a test in 2439 with the Mackies (5S and 6S). Boosted the TH ratings to 10 for both model and chassis and tried to generate in MM. 
![image](https://user-images.githubusercontent.com/13752452/179545327-890f8260-9d28-4624-a102-84844600245b.png)

Boosted the year to 2440
![image](https://user-images.githubusercontent.com/13752452/179545457-e576db57-2563-459d-b461-add43f9232ca.png)

Tried looking in the code but not sure where it generates based on year specifically. Also tested with Lyrans same results.

**Comment by neoancient** [comment]
The code that reduces availability in the first couple years assumes that the introductory year is valid, but the code that checks the intro year against the requested one is disallowing it. It's been so long since I wrote it that I don't know whether that was just a mistake or if I was of two minds about it, but I've just posted a fix.
