### ISSUE TITLE
41.25 : HE ammo type missing in battle round report

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#381]
ATM 9 **( ammo)** at Puma (Adder) C (Clan Wolf); needs 2, rolls 5 : 9 high-explosive missile(s) hit (using Above table) (w/ +6 bonus).

There's a strange space in the bracket, im guessing that its supposed to say (HE ammo) but for some reason the round report isnt displaying the ammo type in the bracket, so its only displaying an empty space there.

If you want a save with ATM mechs to check it out, there's one here : https://github.com/MegaMek/megamek/issues/380

**Comment by arlith** [comment]
AmmoType has submunitionStart and submunitionLength that the reports use to determine where the submunition name is within the AmmoType's shortname.  These weren't set for ATM and iATM ammos.  This has been fixed.
