### ISSUE TITLE
Bug: 49.8 Repeating TSEMP does not repeat

### ISSUE THREAD

**Issue by MarcJC** [MegaMek/megamek#3813]
[CWS Bugged.zip](https://github.com/MegaMek/megamek/files/9184809/CWS.Bugged.zip)
(EDIT - fixed zip to include legacy log with actual data)

I played a game of MM where I had a custom mech with a repeating TSEMP 
The weapon should be usable each round (as it repeats - and also blows up on a 2) but the weapon only fired every other turn as it had to recharge like the standard TSEMP cannon

**Comment by Saklad5** [comment]
Any progress on fixing this? It shouldn't be that hard: perhaps I could take a stab at it?

**Comment by Saklad5** [comment]
@HammerGS I think I've fixed this specific issue, though I'd like to add the downside too before merging.

I should be able to model this off the code for PPC capacitors, right?

**Comment by Saklad5** [comment]
This should be closed, right?
