### ISSUE TITLE
Airborne Aerospace Units Unaffected By Extreme Temperatures

### ISSUE THREAD

**Issue by pokefan548** [MegaMek/megamek#3818]
### Environment
MegaMek v0.49.8

### Description
Airborne aerospace units do not have their heat modified by extreme temperatures (less than 0C or more than 50C).

**Comment by HammerGS** [comment]
Rules reference please.

**Comment by pokefan548** [comment]
_TO:AR_ p. 60, **Extreme Temperatures**

**Comment by Windchild292** [comment]
Fixed in #4000
