### ISSUE TITLE
Show Building CF in Damage Line

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/megamek#382]
For example...
Hardened Standard Building #231562771 absorbs 4 points of damage **CF 116**

**Comment by HammerGS** [comment]
I would help to have a save game even for a RFE.  That way we can load the save and test the code quickly as opposed to set up a game.  Also not 100% sure what you mean. Is it:

Hardened Standard Building #231562771 absorbs 4 points of damage remaining is CF 116.

or something else?

**Comment by scJazz2** [comment]
Your example is correct.

**Comment by HammerGS** [comment]
and the save game to go with the RFE.....

**Comment by NickAragua** [comment]
I've got an implementation of this in the pipeline.

**Comment by NickAragua** [comment]
Added in PR #852
