### ISSUE TITLE
[49.9] Unit Info UI tabs show the wrong tab selected when clicked

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megamek#3820]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
megamek.MegaMek.initializeLogging(MegaMek.java:115) - Starting MegaMek v0.49.9-SNAPSHOT
	Build Date: 2022-07-25T03:37:09.738933400
	Today: 2022-07-28
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 11.0.14.1
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 8 GB

### Description
When clicking the tabs on the unit info window (such as weapons, extras, armor, systems) the Systems and Weapons tabs are visually reversed, meaning if you click the weapons tab, it looks like the Systems tab is the one that is showing.

Issue also occurs with the double "Extras" tab.

The actual content of the window is correct, this is purely a visual bug on the tabs themselves.

Since a picture is worth a thousand words, a video must be worth a million, and this really is easier to show than tell:
https://drive.google.com/file/d/1KrSf1LteXPbGfy_HfZMyx3uK_a77mw4_/view?usp=sharing

Issue has occurred 100% of the time for me, in both MegaMek and MekHQ-sourced MegaMek battles, so you should be able to see this just by starting a new game.

**Comment by kuronekochomusuke** [comment]
is this still an issue?

**Comment by PhoenixHeart512** [comment]
No, this is resolved in 49.10, issue can be closed.

**Comment by kuronekochomusuke** [comment]
closed resolved in 49.10
