### ISSUE TITLE
Disable Reroll button for Tactical Genius if you have already won Initiative

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/megamek#383]
There is no reason to have the button enabled if you have won Init. Please disable it when you have won.

**Comment by VampireSeraphin** [comment]
There is actually. If you are playing on a team, such as with a bot ally in atb, your team can win init, but you don't get last move because you rolled lower than your ally. In that case it is still useful, even though you won.

**Comment by scJazz2** [comment]
With Vamps comments... if you are a Team of One player... disable reroll

**Comment by arlith** [comment]
I'm inclined to mark this as `wontfix`.  You could potentially concoct some reason for wanting to fail init (RPG reasons or something, I dunno).  If we try to disable it, I feel like we'll end up chasing odd cases of, "well, I actually wanted it enabled in <insert incredibly obscure situation>, but it was disabled."  Essentially, we're creating more potential for bug reports, just to prevent the button from being accidentally pushed.  The button is in an odd location, far away from other buttons, so I feel like accidentally pressing the button isn't a huge issue.
