### ISSUE TITLE
RAT Generator doesn't appear to save faction information

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#3833]
I've been working on trying to add some more of the ilClan data to the generator and running into a couple of issues.

The information in the yellow areas won't save
![image](https://user-images.githubusercontent.com/13752452/182293214-8cb5a3ac-7023-4160-b219-08cc7175f412.png)
 If I manually edit them into the file they will. I've tried all types of tab and enter then save. But that section doesn't update.

I've also noticed I can increase the date in GUIPreferences to 3155 (a safe date to extend our years too) and the the RAT Generator and Formation Builder will work out to 3155 but the Force Generator is locked at 3150. 

I just want to confirm the save should word for those allocation sections, as I have know have some accurate data for them. 

### Environment
What version of MegaMek does your issue apply to? MegaMek from the Repo
What operating system are you using?  Windows

**Comment by SJuliez** [comment]
@Windchild292 you aren't looking into this right now, are you?

**Comment by HammerGS** [comment]
Actually I think this can close. I talked to Neo and figured out how it works.
