### ISSUE TITLE
RFE: ilClan era for Force Generator

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#3848]
Currently the MUL is in a Beta for the ilClan era. The files support to 3150 but if I try and add factions or unit with a date later than 3151 they don't save.

Could we get a date extension like the MUL has listed http://www.masterunitlist.info/Era/Details/257/ilclan

As I work on the files I'll add specific data.

**Comment by neoancient** [comment]
Fixed by a30bc80
