### ISSUE TITLE
Militarized Space Stations turning

### ISSUE THREAD

**Issue by Logion567** [MegaMek/megamek#3861]
Mega Mek 0.49.7 on Windows 10

When using a Space Station Marked as Militarized in MegaMekLab (such as the 3091 "Bastion" System Defense Station) they are unable to make a facing change after every turn as described in "Strategic Operations Pg. 51" one can see this issue in the attached save file

[SPACE.sav.gz](https://github.com/MegaMek/megamek/files/9389028/SPACE.sav.gz)

**Comment by HammerGS** [comment]
Poking around the code, it appears everything related to the facing is referencing the old isBattleStation and not design type.
