### ISSUE TITLE
[49.8] Stuka K5b / K5b2 data update

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#3862]
These two units had a bit of a mess involving errata of the TRO and creation of the K5b2 designation. After said updates, the MUL now specifies that the [Stuka STU-K5b2](http://www.masterunitlist.info/Unit/Details/6764/stuka-stu-k5b2) has an introduction date of 2709 and uses standard PPCs (and eventually went extinct after the STU-K5b was introduced), while the [Stuka STU-K5b](http://www.masterunitlist.info/Unit/Details/3111/stuka-stu-k5b) has an introduction date of 2751 and uses ERPPCs.

Megamek currently has this the other way around (K5b as the earlier model with standard PPCs and K5b2 as the later model with ERPPCs), which should be corrected.

(As to why the K5b2 was created earlier, I'm going to wave my hands and assume that the in-universe historian writing the TRO learned about the K5b model first, and only discovered the earlier version afterward).

**Comment by HammerGS** [comment]
Already have fixes pending just not pushed yet. :)

**Comment by HammerGS** [comment]
Fixed with https://github.com/MegaMek/megamek/commit/41f3680bb60b163f1749c461707f5b2f9a62d6ec
