### ISSUE TITLE
[49.7] Bug: Warships with slightly incorrect armour values

### ISSUE THREAD

**Issue by Gribbly1** [MegaMek/megamek#3867]
Bundled Megamek with MekHQ 0.49.7
Windows 10, Java Version: 11.0.13

The 'Congress Frigate (2542)' and 'Essex II (2711)' have minor armour value transpositions between Aft and Aft Left Side.
![image](https://user-images.githubusercontent.com/55139229/187029308-9e6952e1-82f6-459f-8642-c3ca7ca20fa5.png)
![image](https://user-images.githubusercontent.com/55139229/187029327-678ee56e-2bc4-4262-a350-938a1fe0c10d.png)

Ref pages 138 and 146 'TRO: 3057r'
![image](https://user-images.githubusercontent.com/55139229/187029367-3483bde2-ccbb-4566-b683-959c61e11d6e.png)
![image](https://user-images.githubusercontent.com/55139229/187029394-5a3b1b6f-f355-49c5-8bcb-aee0a7427713.png)

**Comment by Gribbly1** [comment]
Also the 'Davion Destroyer Block II', 'Whirlwind Destroyer (2606)', 'Volga Transport (2709'), 'Luxor Heavy Cruiser (2727)', 'Kyushu Frigate (3057)' and 'Kirishima Cruiser (3061)' have aft/ALS transpositions.

The 'Fox Corvette (3057)', 'Impavido Destroyer (3058)', 'Tharkad Battlecruiser (WoB)' and 'Suffren Destroyer (3062)' have similar issues but with the Aft Right side.

The 'Carrack Transport' might have the same issue, but I can't find a TRO with the relevant armour values.

**Comment by Gribbly1** [comment]
I think I adjusted these files correctly
[ships.zip](https://github.com/MegaMek/megamek/files/9463909/ships.zip)

**Comment by HammerGS** [comment]
Setting these up as a check list.

- [ ] Congress Frigate (2542)
- [ ] Essex II (2711)' 
- [ ] Davion Destroyer Block II
- [ ] Whirlwind Destroyer (2606)
- [ ] Volga Transport (2709')
- [ ] Luxor Heavy Cruiser (2727)
- [ ] Kyushu Frigate (3057)
- [ ] Kirishima Cruiser (3061)
- [ ] Fox Corvette (3057)
- [ ] Impavido Destroyer (3058)
- [ ] Tharkad Battlecruiser (WoB)
- [ ] Suffren Destroyer (3062)
- [ ] Carrack Transport (Clan)
