### ISSUE TITLE
Anti-Aircraft Targeting Quirk not properly accounted for during Flak Attacks with Artillery

### ISSUE THREAD

**Issue by JoeJohnJordan** [MegaMek/megamek#3870]
MegaMek Version 49.8, Windows, Java version 16.0.1

Arrow IV being unaffected by the Anti-Aircraft Targeting Quirk while firing at airborne targets as a Flak Attack even though there is nothing stating that the quirk should not affect Arrow IV during Flak Attacks. 

Campaign Operations, Page 225 for Anti-Aircraft Targeting Quirk
Total Warfare, Page 114 for General Flak Rules 
Tactical Operations (Single Book), Page 185 for Artillery Flak rules
Tactical Operations (Split book, Advanced Rules segment), Page 153 for Artillery Flak rules

First two images below outline Tactical Operations Flak Rules and Table of Artillery muntions (Which yield no objection to the quirk co-operating with Arrow IV on a Flak Attack.
![Screenshot_20220828-160813_Drive](https://user-images.githubusercontent.com/112347372/187092673-2b3769f8-c429-4e29-b484-a71c22fd406e.jpg)
![image1](https://user-images.githubusercontent.com/112347372/187092683-42f3c865-6ef6-4cea-a4af-1bec4f064388.jpg) 

Image clipped of Anti-Aircraft Targeting Quirk rules from Campaign Operations, Page 225
![Screenshot_20220828-161359_Drive](https://user-images.githubusercontent.com/112347372/187092914-d4dec322-cccc-40e7-999c-791649c2f61d.jpg)

**Comment by pheonixstorm** [comment]
@JoeJohnJordan Need to know what units you are using and if they have the AA quirk

**Comment by JoeJohnJordan** [comment]
Longbow-8V, And yes it has the quirk.

**Comment by Sleet01** [comment]
It looks like there may be two issues:
1) there's no check for this quirk in the artillery attack handling path;
2) for some reason I can't set the StratOps quirk handling on

Even after fixing #1 I'm still seeing #2 as an issue.  I'll investigate further.

**Comment by Sleet01** [comment]
My problem 2 is PEBCAK: I wasn't providing the proper password when changing game settings -_-;
I think I can fix this issue and #4524 at the same time; testing the fix now.
