### ISSUE TITLE
Snow require extremely cold temperatures (in celcius?) 

### ISSUE THREAD

**Issue by SaerdnaLessah** [MegaMek/megamek#3884]
### Environment
HQ's MegaMek 49.9. Reproduced at standalone MegaMek 49.9, MegaMek 48.0

(As it may matter; northern european computer preset aka if temperatures are converted from F to °C?)

### Description
The various "Snow" weather conditions require extremely cold temperatures which kills Conventional Infantry. While I lack the TacOps-Advanced Rules access at this moment to double check, but it seems unreasonable that the weather provides mild penalties for a unit type that just dies in it.

Light Snow can't be selected at temperatures hotter then -40°C for example. 

To reproduce: open up a MegaMek battle, flip over to Planetary Conditions and attempt to set a moderately cold temperature + snow. 

![snowselect](https://user-images.githubusercontent.com/113114755/189133106-c64f0549-f201-4b90-b95c-5d483dcb2d6a.png)

**Comment by Windchild292** [comment]
This is RAW
