### ISSUE TITLE
Show number of possible targets

### ISSUE THREAD

**Issue by kipstafoo** [MegaMek/megamek#389]
Often when playing AtB fights from MHQ I'm fighting in the dark. It would be nice to have a line in the weapon display showing the number of visible targets. Yes, you can hunt and peck with the 'Next Target' button but if you can't see anything, then no sense in bothering to hunt and peck, just move on with life.

Additionally, a configuration option that 'Next Target' goes to the next target you can actually see would be nice, or even a new button for 'Next Visible Target'. I can see how 'Next Target' would be useful, even if you can't see it (artillery, knowing what target is nearest to you, etc...).

**Comment by SirMegaV** [comment]
Made a similar request to add a button for 'next valid/shootable target'
sometime ago.

**Comment by arlith** [comment]
I think that there are better ways to handle this.  The firing solutions should already largely handle this, as it will indicate what units can be hit or not.  I think the best way to handle this would be incorporating firing solutions information into the minimap.  Additionally, modifiers to the next target button were requested in #164, and that has now been implemented.  Given all of this, I'm going to mark this ticket as wontfix and close it.
