### ISSUE TITLE
Princess PacketCommand Errors in log 0.49.10

### ISSUE THREAD

**Issue by cam-smith** [MegaMek/megamek#3899]
02:40:36,955 INFO  [megamek.MegaMek] {main}
megamek.MegaMek.initializeLogging(MegaMek.java:115) - Starting MegaMek v0.49.10
	Build Date: 2022-09-12T09:06:00.333851300
	Today: 2022-09-13
	Origin Project: MegaMek
	Java Vendor: AdoptOpenJDK
	Java Version: 11.0.8
	Platform: Mac OS X 10.16 (x86_64)
	System Locale: en_AU
	Total memory available to MegaMek: 4 GB

### Description
Princess throwing errors about unknown packetcommand, but game doesn't crash.  Was just a dumb game between player and bot, no save game I'm afraid.  Just reviewing logs after the game.
ie. 
`ERROR [megamek.client.bot.princess.Precognition] {AWT-EventQueue-0}
megamek.client.bot.princess.Precognition.handlePacket(Precognition.java:271) - Attempted to parse unknown PacketCommand of ENTITY_MULTIUPDATE`

### Files

[megamek.log](https://github.com/MegaMek/megamek/files/9550796/megamek.log)

**Comment by Windchild292** [comment]
It's not an error, just a testing log I forgot to remove.
