### ISSUE TITLE
Unit Display with many advantages in 49.9

### ISSUE THREAD

**Issue by adamantsteel90** [MegaMek/megamek#3902]
### Environment
49.9 MegaMek/MekHQ (Same in 49.10)
Windows 7 6.1 (amd64)
Eclipse Temurin JDK with Hotspot 11.0.15.10 (x64)

### Description
![MegaMek49 9UnitDisplay3](https://user-images.githubusercontent.com/113563165/190282726-c5b5bdfb-4cea-4560-830d-9b6776e3e7ae.png)

Unit Display window need rearrange.
Basic unit info need go up over advantage/edge etc.

Or add scrollbar?

**Comment by NickAragua** [comment]
Fixed with PR #3957
