### ISSUE TITLE
49.10 Data error for the Lee dropship

### ISSUE THREAD

**Issue by mwberlindeu** [MegaMek/megamek#3909]
The entry for the bay personal of the Lee dropship is most likely wrong

![grafik](https://user-images.githubusercontent.com/28268113/191579816-7694ee6b-e9b2-4019-87d0-bbd233436f0a.png)

**Comment by HammerGS** [comment]
This is Armor Carrier which is described in Fluff. It's carrying 68 vehicles and crews, 27 Platoons of Infantry so it's highly likely the Bay Personnel would be that high.

**Comment by Gribbly1** [comment]
![image](https://user-images.githubusercontent.com/55139229/191582538-8de35c74-5eb7-43bc-b510-bb805b70f1c2.png)

Looks fine to me, based upon the table in the Tech Manual.

**Comment by mwberlindeu** [comment]
Thanks for checking. It looked a factor 10 to high at first glance.

**Comment by Gribbly1** [comment]
If you think something's wrong it's better to quote rulebook references and state what you think the correct number is.

**Comment by mwberlindeu** [comment]
Will do next time, I did not have the original book available that contained the Lee dropship.
