### ISSUE TITLE
Camo not applied to all ASFs

### ISSUE THREAD

**Issue by kipstafoo** [MegaMek/megamek#392]
I have a few ASFs I use from my MekHQ campaign. When I launch a fight with them in MM, 4 of the 6 don't have the camo applied and even manually applying it doesn't work. Within MekHQ the camo applies fine to these units.

Works: Thunderbird
Doesn't work: Reiver, Lucifer, Slayer, Stingray

**Comment by ObviousTech** [comment]
Possibly related:
https://github.com/MegaMek/megamek/issues/327

**Comment by BLOODWOLF333** [comment]
What version are you using?  In the current releases (that use .pngs) they all should be true grey-scale already and this fixed.

**Comment by kipstafoo** [comment]
Latest git version, so 0.41.26

**Comment by BLOODWOLF333** [comment]
:( Guess I found my next project.  I start redoing all these that colsanders script didnt work on.

**Comment by BLOODWOLF333** [comment]
Am not able to duplicate your concern with a clean DL of 0.41.26(just MM).
![slack](https://cloud.githubusercontent.com/assets/16950832/20074275/2d859f30-a4f5-11e6-8f0d-ebb90fe74a71.png)

Maybe this is HQ specific?  Something didnt get transferred over to HQ(Devs?).

**Comment by kipstafoo** [comment]
![image](https://cloud.githubusercontent.com/assets/506522/20074644/180f3abc-a4ff-11e6-8770-10883d314bd0.png)

![image](https://cloud.githubusercontent.com/assets/506522/20074658/2830b128-a4ff-11e6-898f-a7e5d20f2cb3.png)

**Comment by BLOODWOLF333** [comment]
Yeah thats definitely the not true grey-scale issue.  Um, could try to DL just the 0.41.26 Megamek only release and then copy and paste all the .pngs in the ASF folder into your HQ one since we know the MM-only icons work.

**Comment by HammerGS** [comment]
I can't duplicate it as well.  
![image](https://cloud.githubusercontent.com/assets/13752452/20078897/9deb3ffa-a4ff-11e6-9277-a6faf3a484e2.png)

But those Lucifer's above don't look like they've had the shading script.

**Comment by BLOODWOLF333** [comment]
Yours do @hammer, they have that fuzzy shadow around the edges of the fighter.  Kip's are all sharp like theyre still .gif though it looks like.

**Comment by kipstafoo** [comment]
Are you guys trying straight-up MM or MM through MHQ? Straight-up seems to work, launched via MHQ does not.

There's an obvious difference  between the images (as you can see below). Maybe MHQ isn't getting all the images from MM when the build is being done?

![image](https://cloud.githubusercontent.com/assets/506522/20080274/caa36380-a516-11e6-9f16-fba56fe28f40.png)

**Comment by BLOODWOLF333** [comment]
Ah ha HQ did not get the shaded ASF sprites it looks like. (I only tested with just the MM download on my work laptop).

**Comment by Dylan-M** [comment]
Are you downloading MHQ or building it yourself? The download has all the correct png images. If you build it yourself, you will **_not_** get the correct images unless you _package_ it. Much of the "data" folder in MHQ isn't actually used, it's there as a sample, and not always kept up to date with MM's data folder. @BLOODWOLF333 is wrong, MHQ definitely did get it _if_ you download rather than build.

**Comment by Dylan-M** [comment]
And just to add to my previous message: I've looked at all 4 of the downloadable files, including the packages sources rather than the auto-added source. They're _all_ using the correct images. And yes, this is MHQ I'm referencing. Unless there's something I'm completely missing, I believe this is PEBKAC and can be closed. Sorry Kip! :D

**Comment by arlith** [comment]
This is probably an issue with using the data that's within MHQ repository, as I recall, it's not really updated (and it doesn't really seem necessary to update it, except maybe some examples for testing).  It might be a good idea to reduce the data in MHQ down to just a testing set, to make it clearer that the data in there is only to be used for testing.

**Comment by Dylan-M** [comment]
Yes, we don't support building directly from the repo, if you want to actually **use** MHQ from git, you have to **_package_** it.
