### ISSUE TITLE
Motorized/Mechanized Infantry BV Calculation Error

### ISSUE THREAD

**Issue by bpbenedicto** [MegaMek/megamek#3931]
### Description
TW pg 309, Infantry do not get a unit type modifier. Currently, motorized infantry gets a unit-type multiplier as if they were wheeled. This also carries over to mechanized infantry I believe, as the way the standard TechManual calculates infantry BV does not distinguish infantry by unit type but solely based on Defensive Factor for differences.
![image](https://user-images.githubusercontent.com/64341386/194969138-ddc0517e-a447-403a-bc31-79f694f70e0c.png)

This error makes foot infantry of the same size and equipment sometimes more expensive or equal to motorized infantry, their only benefit is that have lower tonnage for transports. After this change motorized should be slightly under jump infantry in cost because of a different defensive factor, but otherwise, that is it.

**Comment by SJuliez** [comment]
TO AUE p.193 lists unit type mods for CI.

**Comment by SJuliez** [comment]
Closing this as I believe there is no error.
