### ISSUE TITLE
Deadfire LRM range brackets incorrect 0.49.10

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#3934]
This was reported as fixed earlier this year, but it seems that something broke again.  I'm not sure if the Deadfire SRMs are also affected.

![image](https://user-images.githubusercontent.com/18338059/195481456-08edf567-1c68-4bf3-89ff-b8ba3a67a65e.png)

**Comment by BLR-IIC** [comment]
After playing around with the unit carrying Deadfire LRMs, it seems that MegaMek is calculating to-hit numbers correctly, but just isn't displaying them on the unit display.

**Comment by HammerGS** [comment]
I'm not sure how to fix this. When I tried my first fix it wasn't 100%. I think the problem is in weapontype with it confusing LRM ammo and assuming it's always normal LRM ammo.

**Comment by pheonixstorm** [comment]
If anyone happens to know when it was fixed or have a PR/commit handy I can look at it. Probably won't be able to fix it, but an extra set of eyes never hurts.

**Comment by pheonixstorm** [comment]
Found the related PR #3713 

I will start looking into it on Monday. Glancing over the PR not sure why it isn't showing correctly though.
