### ISSUE TITLE
PSR Roll With Specialty Armor

### ISSUE THREAD

**Issue by WildKadabra** [MegaMek/megamek#3936]
Not really a bug but an outdated rule.

Since the latest version of the revised TRO, PSR for mechs with specialty armor (Ferro-Lamellor, Hardened, Reflective, etc.) should be calculated AFTER damage reductions. Currently the game calculates them before damage reduction. 

BBM 5th edition page 114

https://bg.battletech.com/forums/total-warfare/psrs-against-specialized-armor/msg1808890/#msg1808890 official response for reference.

**Comment by AlphaSled** [comment]
Closing as a duplicate. Previous/related tickets can be found here:

https://github.com/MegaMek/megamek/issues/2032
https://github.com/MegaMek/megamek/issues/1377
https://github.com/MegaMek/megamek/issues/3396
