### ISSUE TITLE
RFE: Add Ability to Filter Via Weapon Groups/Types/Classes (i.e. All Mechs With Any Type of LRM)

### ISSUE THREAD

**Issue by Seosaidh** [MegaMek/megamek#3938]
### Environment
N/A

### Description
It would be nice to be able to filter out units based on entire classes of weapons in the advanced filter screen instead of having to select every single instance of a weapon. For example, if I wanted to get all units that mount LRMs, and I'm playing advanced tech in 3080, there are a _lot_ of weapons from the weapons table I have to add to the filter. It would be nice to just have to add one item.

**Comment by Seosaidh** [comment]
This was attempted in PR #3932. However, the approach taken there mistakenly used the Aero weapon class, which doesn't correspond to what the average person would understand for weapon types in non-aero units. The main example being that gauss weapons are classified as auto-cannons, while the only "gauss weapon" is the gauss bay.

**Comment by SJuliez** [comment]
I believe this function is present.
