### ISSUE TITLE
Mini map icons

### ISSUE THREAD

**Issue by mchapman1970** [MegaMek/megamek#395]
Is it possible to change a mechwarrior icon from infantry to something else.

**Comment by arlith** [comment]
Examples of new icons.  With default icons, a smaller circle is drawn.  With SO symbology, I enhanced the infantry icon with a dot.

![screenshot at 2016-11-23 11-05-39](https://cloud.githubusercontent.com/assets/13815237/20572405/f14189a2-b170-11e6-8ee8-a709be3991c0.png)

![screenshot at 2016-11-23 11-35-18](https://cloud.githubusercontent.com/assets/13815237/20572408/f4099cba-b170-11e6-81d6-a6cd533e2d9e.png)

**Comment by pheonixstorm** [comment]
that will be confusing since SO would label that as Field Artillery Infantry. Can't really think of an alternative though.
