### ISSUE TITLE
Minor Spelling Errors

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#3952]
v49.11

The summary tab currently shows "Endo-Steel" instead of "Endo Steel" (no hyphen). Errata will be pushed to the TechManual and other erroneous products to reflect this as well.

In the summary tab, on record sheets, and in the filter section, "MagShot" should be replaced with "Magshot".

**Comment by HammerGS** [comment]
Not sure if the Endo Steel fix is something I can do. Worried about breaking things.

**Comment by HammerGS** [comment]
I’ve got a fix I’m testing.
