### ISSUE TITLE
First Succession Wars Rats seem incorrect

### ISSUE THREAD

**Issue by epic76** [MegaMek/megamek#3956]
(Delete the above lines)

### Environment
What version of MegaMek ?  49.10
operating system  Windows,
Java Version: 11.0.15

### Description
Describe the issue and provide screenshots ingame if able.  
RATs for First Succession War seem to be drawing from some other table somehow (getting mechs from eras beyond the 1SW, such as the Cataphract, for Cap Con, or Falconer for the FS).  The files themselves are correct based on 1SW from page 148 in the 1SW, so it has to be something done afterwards.  When I tried, it seemed like the A lists were all drawing correctly.  It's the B-F lists that aren't working.  Quickly ran through all 5 Great Houses, the MoC, Taurian and same issues for all of them; the A list was correct, the B-F lists were incorrect.  I didn't see that the Outworlds Alliance had odd results, after a few tests.  SLDF list also seemed ok when I tested.
![image](https://user-images.githubusercontent.com/28692297/199622306-ef16909a-d06c-4e6e-9b6d-61edc1dd1bff.png)

[megamek.log](https://github.com/MegaMek/megamek/files/9924807/megamek.log)

**Comment by sldfgunslinger2766** [comment]
I've seen this issue pop up in some versions too. I'll dig up my original file and open a pull request to get the correct version in the next dev release/nightly build.
