### ISSUE TITLE
Thumper Field of Fire Overlay

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#397]
For the turret, doesnt list a min range for the thumper but the overlay draws one.  This looks wrong.
![example](https://cloud.githubusercontent.com/assets/16950832/20041019/f2534250-a427-11e6-94fb-3fa8d0a1068c.png)

Player Name: AFFS-FSAC-2REG-2BN-ECO
[FieldofFire.sav.gz](https://github.com/MegaMek/megamek/files/574063/FieldofFire.sav.gz)

**Comment by VampireSeraphin** [comment]
Thats the range under which direct fire attacks are not allowed. Seems to be working as intended.

**Comment by BLOODWOLF333** [comment]
Hm too bad princess doesnt understand :( she doesnt do anything with the arty turrets.

**Comment by VampireSeraphin** [comment]
Princess doesn't use artillery period, either for direct or indirect fire.

**Comment by Dylan-M** [comment]
WAD.
