### ISSUE TITLE
[49.10] Mek MTFs are displayed twice in the "Select Unit" window

### ISSUE THREAD

**Issue by Jenbak5** [MegaMek/megamek#3973]
### Environment
49.10, HQ's MegaMek
	Build Date: 2022-09-12T09:06:00.345851400
	Today: 2022-11-11
	Origin Project: MegaMekLab
	Java Vendor: Eclipse Adoptium
	Java Version: 11.0.14.1
	Platform: Windows 10 10.0 (amd64)
	Total memory available to MegaMek: 1 GB

### Description
Every mek mtf in the "Select Unit" window are displayed twice as if the respective mek's model list is added again.
Like:
Commando COM-1D 
Commando COM-2D
Commando COM-3A
Commando COM-1B
Commando COM-1C
Commando COM-1A
Commando COM-1D 
Commando COM-2D  
Commando COM-3A
Commando COM-1B
Commando COM-1C
Commando COM-1A

Not quite sure how to replicate this.
What I did was customizing my own Centurion in MekLab
Specific equipment shouldn't matter for this issue, what I did was accidentally saving the mtf without suffix (so an invalid file) in the mechfiles folder as CN6-AJ. Couldn't use it so I made another one and called it CN6-AJ2 and saved it in the same place.
Then I noticed what was wrong, added the suffix to original CN6-AJ, put it into mechfiles -> mechs and deleted the other one.

My intention was to change the model version to CN6-AJ for the Unit List but I only named the file that and nothing else. And so I think the issue is simply that because I added a duplicate model version that just has slightly different equipment, it caused the other mtf files to be read twice to keep everything balanced or something of the sort.

The mtf files themselves in mechfiles -> mechs are not duplicated. They are just being listed twice in the list.

**Comment by Jenbak5** [comment]
I did have to open mechs.zip in order to put my mech there but I did not extract it I think, just double clicked on the zip. 
![image](https://user-images.githubusercontent.com/60224265/201308312-e748009c-8ab7-4775-ba40-96f514b4cc03.png)
I don't see them together

**Comment by Jenbak5** [comment]
![image](https://user-images.githubusercontent.com/60224265/201308508-72d061b4-df9b-44ed-96e0-f41531bb5a14.png)

**Comment by pheonixstorm** [comment]
You really shouldn't add anything to the zipped folders. Use customs or add an empty mechs folder.

But, try deleting the units.cache and see if you still get the same result.

**Comment by Jenbak5** [comment]
There we go, easy fix and lesson learned. Thanks for the help!
Hope this helps other people making the same mistake
