### ISSUE TITLE
Missing skin

### ISSUE THREAD

**Issue by kipstafoo** [MegaMek/megamek#398]
In the 0.41.26, I no longer see the border around the map and the log is filled with:

ERROR: Bad skin specification file: file doesn't exist!  File name: BW - Default.xml

If I go to 'View -> Client Settings -> Graphics' the 'Skin File' dropdown is empty.

**Comment by BLOODWOLF333** [comment]
I've had this happen before.  Have to go into the clientsettings.xml and manually type in Default for the skin specification to fix it.  Then will be able to change skins normally.

**Comment by kipstafoo** [comment]
I think we need some sort of check on MM to verify that we have data.

**Comment by BLOODWOLF333** [comment]
This is in 0.41.21 or 0.41.26?  I havent updated yet but, havent seen this bug for maybe five versions now.

**Comment by kipstafoo** [comment]
0.41.26... I now see that I had too many digits in the original post.

**Comment by arlith** [comment]
Based on #392, are you running this from within the MHQ repository?  It seems your suggestion for checking whether there is data is really only pertinent for packaging, and we don't seem to have had problems with the data in the packages we release.  There are checks at some places that can handle some no data cases, so I guess you'd have to be more specific.

**Comment by Dylan-M** [comment]
And... as mentioned on #392, we don't support running directly from the git repo since the data present there is only a subset for testing.

**Comment by Dylan-M** [comment]
Closing as invalid, unsupported run configuration.
