### ISSUE TITLE
Princess deploys multiple units in/on top of one building

### ISSUE THREAD

**Issue by kipstafoo** [MegaMek/megamek#401]
Thanks for the assist, princess.

As you can see from the screen shot, princess put multiple units in/on one building at deployment and collapsed the building on top of itself.

![2016-11-09](https://cloud.githubusercontent.com/assets/506522/20138652/7c441b78-a64f-11e6-87f8-b3c917603f9c.png)

**Comment by VampireSeraphin** [comment]
I've seen that happen mid game before to.

**Comment by dericpage** [comment]
Change has been merged.  This should be fixed with the next release.
