### ISSUE TITLE
"Go Through" climb mode is not working if the mech can climb the building

### ISSUE THREAD

**Issue by mangofeet** [MegaMek/megamek#4018]
tested on version 0.49.10 

When switching to "Go Through" climb mode for a mech, it only actually enters the building if it's not able to climb it (so level 3+ with standard rules). If the building is level 1 or 2, the mech will instead climb the building.

**Comment by HammerGS** [comment]
If you have a save that would be a big help.

**Comment by mangofeet** [comment]
At what point would you want the save? After walking through/onto buildings, or the setup to do so to replicate?

**Comment by mangofeet** [comment]
Hm, when I set up a contrived test scenario (blank map with just four buildings and four mechm) it's not happening.

The game that caused me to open this was a scenario generated by mekhq with the experimental AtB stuff, but I didn't think that would make a difference when it came to stuff happening in megamek.
