### ISSUE TITLE
Mech can stand after falling from failed jump into rubble on road.

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#402]
[StandAfterJump.sav.gz](https://github.com/MegaMek/megamek/files/582265/StandAfterJump.sav.gz)

I had a vulcan that was allowed 2 attempts to stand after falling from a failed landing jumping into rubble. I've attached the save game.

**Comment by Dylan-M** [comment]
I'm going to guess the option for "Falling doesn't end movement" or whatever is set to allow this. But, that setting shouldn't apply to jumps... maybe...

**Comment by arlith** [comment]
The `continueTurnFromFall` boolean in `Server.processMovement` didn't check for jumping, and it should.  I added a condition that the overall movement mode isn't jumping, and that fixes the issue.
