### ISSUE TITLE
Airmech Level Changes expending extra MP when changing level

### ISSUE THREAD

**Issue by Logion567** [MegaMek/megamek#4020]
MegaMek version 0.49.10

The issue seems to stem from the fact that LAMs can keep elevation when the ground they're flying over changes. by default it seems Megamek has the LAM stay at said elevation and consequently winds up spending MP it shouldn't.
![image](https://user-images.githubusercontent.com/98195429/205422921-42b116fb-a3ab-413b-9c16-e561d019fe95.png)
in this image you see it's expending 1MP even going up a slope as normal. however when going over a 2 level high cliff it suddenly finds itself expending 3MP per hex. no option I can find is given to continue following the earth and conserve MP. and no MP is "refunded" when going down to elevation 1.
For how it's supposed to work check Page 103 of IO:AE, specifically the first half of the last paragraph near the bottom. 

Username is _Logion567_ 

this save has the full lobby from that picture, no Princess to worry about. plenty of varied terrain to test with. 
[LAM.sav.gz](https://github.com/MegaMek/megamek/files/10145646/LAM.sav.gz)

**Comment by Logion567** [comment]
found that this issue also applies to Basic WiGE units. 
![image](https://user-images.githubusercontent.com/98195429/213945023-f435e44f-f5a9-4a70-992c-4fdd655f1b75.png)

for those unaware when i entered Hex 1027 i did so at elevation 2 for that hex, which costs 2 more MP than normal (total of 3 MP) however i elected to go down to elevation 1 in that hex which according to the rules example in Page 55-56 of Total Warfare that move should've only cost 1 MP to enter that hex

![image](https://user-images.githubusercontent.com/98195429/213945038-5451b165-779a-4bb5-b735-4be3123bc7e3.png)
![image](https://user-images.githubusercontent.com/98195429/213945044-fa2891cc-41d5-4bc4-85dd-b7d2afefebd4.png)

Username for the Save with the first image example is *Logion567*
[WiGE.sav.gz](https://github.com/MegaMek/megamek/files/10475708/WiGE.sav.gz)

**Comment by mikerob** [comment]
v0.49.11: Have you tried changing the "Climb Mode" using the buttons at the bottom?  I thought that fixed it for me.

"Keep Elev" holds you at whatever elevation you leave a piece of terrain (the behaviour you're describing)
"End Keep Elev" follows terrain until the end of your move (the behaviour you want / expect)

Keep Elev:
![image](https://user-images.githubusercontent.com/6381849/215743217-05387513-e20f-4ff1-bc9a-081a224ff7a3.png)

End keep elev, following terrain
![image](https://user-images.githubusercontent.com/6381849/215742603-6540e546-ba14-4eba-b0c1-189c35109939.png)

End keep elev, pop up at the end

![image](https://user-images.githubusercontent.com/6381849/215742870-7d3310d4-fd38-4990-9aed-af0d33fd71f5.png)

**Comment by Logion567** [comment]
oh my lord
my apologies I never noticed that was a thing.

**Comment by mikerob** [comment]
I probably shouldn’t turn this into too much of a chat, but I want to look into a couple other things - I think the to hit modifier for firing on the same turn you change modes is missing, and there’s no way to get up when you fall in air mech mode. 


Sent from Yahoo Mail for iPhone


On Wednesday, February 1, 2023, 00:19, Logion567 ***@***.***> wrote:




Closed #4020 as completed.

**Comment by Logion567** [comment]
I can confirm the "no penalty from shooting and converting in the same turn"

you can "get up" in Airmech mode
it just uses the "walking MP" of airmech mode to do it (.333 Walking MP, recalculate running as normal)
though the rules in IntoOps:AE make it seem it dosen't "go prone" at all after a crash? i'd make new bug reports for both of these

**Comment by mikerob** [comment]
What's the process in MegaMek to stand up?  Do you have to select "walk" first" I've never seen the option to "Get Up" available when my Airmechs have been knocked down.

You're right - iaw TW:AE 107, the crashing rules talk about damage but nothing about whether you are prone.

TW 68 says this about WiGE and VTOL crashes:

"If the vehicle is still functional after taking damage from the crash and it can normally land in the terrain of the hex in which it
crashed, the vehicle is considered to have landed in the hex and can move as normal in the next turn. Otherwise, the vehicle is
considered destroyed."

Seems to imply that you DON'T go prone, and you should be fine to take off and move again (or transform, or walk in AirMech mode).

**Comment by Logion567** [comment]
> What's the process in MegaMek to stand up? Do you have to select "walk" first" I've never seen the option to "Get Up" available when my Airmechs have been knocked down.

just try and move, it'll use the airmech walking MP
