### ISSUE TITLE
49.10 LB-X hit 1 point damage to conventional aircraft not transfering to SI

### ISSUE THREAD

**Issue by mwberlindeu** [MegaMek/megamek#4027]
**Environment**

MegaMek version: 49.10

**Description**

LB-X hits making 1 point of damage do not transfer to SI on conventional aircraft.

**Log Extracts**

Weapons fire for Partisan Heavy Tank
    LB 5-X AC ( ammo) at Guardian Fighter (Standard) (Enemy);  needs 6, rolls 11 :  - Direct Blow - 5 pellet(s) hit (using Right Side table) (w/ +2 bonus).
        Guardian Fighter (Standard) (Enemy) takes 1 damage to NOS.
 0 damage transfers to the SI. 5 SI remaining.
        Guardian Fighter (Standard) (Enemy) takes 1 damage to NOS.
 0 damage transfers to the SI. 5 SI remaining.

22:44:18,693 ERROR [megamek.server.GameManager] {Packet Pump}
megamek.server.GameManager.receiveAttack(GameManager.java:12766) - Server got invalid attack packet from Connection 0, Entity null, invalid Turn

Note: I do not know if their is a relation between the game log, and the error log.

**Comment by SuperStucco** [comment]
Total Warfare indicates damage to SI is halved (round down), so LBX cluster hits from ground attackers will do no direct damage to SI.

**Comment by mwberlindeu** [comment]
Thanks for the clarification. Thus an LB-X can never totally destroy an aircraft. Sorry that I did not know the rules this well.
