### ISSUE TITLE
Mechs Cannot Cross Magma

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#403]
[NoMagmaCrossing.sav.gz](https://github.com/MegaMek/megamek/files/582268/NoMagmaCrossing.sav.gz)

In this game I had mechs that were unable to cross the magma, even while the bot was walking on it. I've never seen this bug before.

**Comment by pheonixstorm** [comment]
have a user name for the save?

Can you reproduce it?

**Comment by VampireSeraphin** [comment]
The Infamous Dust & First Kittery Borderers

I have not tried to reproduce it yet.

**Comment by arlith** [comment]
Attaching a saved game that's in the physical phase right  before the game is won, isn't terribly helpful...

**Comment by arlith** [comment]
This is a bug in the board file.  It's using magma:0.  This is an issue that will be aided by the board validator mentioned in #411.  We will have to go through and fix up some maps in some of the map packs.  I'm going to mark this as closed.
