### ISSUE TITLE
[Request] Dynamic Pavement edges

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#405]
Can we get dynamic pavement edges similar to the way MM handles buildings and roads for the map editor? Right now if you drop a pavement tile down, the edges are extremely sharp and unnatural looking. I'd like to see the pavement trail off at the edges similar to the way the dynamic road ends if you don't set any exits.

**Comment by BLOODWOLF333** [comment]
When I erased the edges of the pavement.gif and then saved them.  It does not show the underlying terrain (dirt or grass etc) where the edges were erased.  The BG behind the board shows through.  So for right now we would have to create a pavement hex for every theme to get that to work since pavements are base images and not supers.  Havent tried changing pavement to a super yet.

**Comment by VampireSeraphin** [comment]
You'd also need to have multiple images so you can set exits, like a building. Otherwise you'd get a honeycomb pattern.

**Comment by BLOODWOLF333** [comment]
Exactly, I can make those images but, Im not going to spend the time to build a map with them. I only use the generated map settings and thats all I like.  I doubt the devs will be willing to create the building and road linker code for pavement but, I can make the images for those who are willing to do it manually.

**Comment by VampireSeraphin** [comment]
You don't get things if you never ask for them ;)

**Comment by arlith** [comment]
Pavement gets defined as a base, not a super.  Roads get defined as supers.  That is, some images are the "base" they are the "background" of the hex, and then various images get superimposed on top of them (hence, supers).  That is the reason why if your pavement image doesn't take up the whole hex surface, you can see the background behind it (or you'd probably see some default gray color, if it weren't transparent).

With respect to exits, the difference between how exits work for buildings and roads and pavement is that, the pavement would be dependent upon neighboring hexes (aka, if you had an exit between a pavement and clear hex, vs a clear and forest hex, you'd probably want to draw the pavement differently).

I think that this would require a lot of additional art and some good design.

**Comment by VampireSeraphin** [comment]
You could probably convert the pavement to a super with some different edge patterns and get it to work fine for new maps. It would be a horror show updating old maps though because as you say, anything pavement suddenly would not have a base tile.

**Comment by SJuliez** [comment]
I believe this implemented in 0.49.2.
