### ISSUE TITLE
[Fluff] no (fluff) mech images shown in HQ

### ISSUE THREAD

**Issue by kernhe** [MegaMek/megamek#4058]
### Environment
V: 0.49.9 Snapshot
O: linux (Ubuntu 20.04.4)
J: openjdk 11.0.15 2022-04-19

### Description
I have plenty of (fluff) images for various mechs, but they are no longer displayed in HQ.
Is the file name now case sensitive (known linux issue)?

**Comment by Windchild292** [comment]
Resolved in latest.
