### ISSUE TITLE
Oo-Suzumebachi not legal

### ISSUE THREAD

**Issue by Jellico123** [MegaMek/megamek#4063]
### Environment
What version of MegaMek does your issue apply to?  Note whether it is the stand alone MegaMek or HQ's MegaMek.
dev 0.49.10

What operating system are you using?  Windows, 

Oo-Suzumebachi is showing up as Level F in unit selection. I am guessing a problem with the .blk given it isn't that complex a unit.

I would rebuild and provide the .blk myself but I am a long way out of modern standards. 

Jellico

**Comment by HammerGS** [comment]
When we build this in MML it comes in overweight. If I had to guess the TRO entry doesn't include the weight of the crew quarters, which is a common issue we've seen with ships built. I don't have access to the spreadsheet used to build these ships. 

Since our policy is to always follow the RS/TRO entry the ship would remain invalid. 

![image](https://user-images.githubusercontent.com/13752452/209369649-f2202923-eb51-4dd8-afac-17eba664e23b.png)

**Comment by Jellico123** [comment]
Okay. Finally cracked open MekLab to have a look. I think I see the problem. 

The Carleon and Oo-Suzumebachi use BA Compartments like an APC, rather than BA Bays. Both are using Bays in their .blks. Carleon just got lucky that the weights matched. 

Looks like the fix is to change the BA Bays to 12 tons of Infantry Compartment. (12 BA) 
Same for the Carleon, except it is 20 tons of Infantry Compartment. (20 BA)

Jellico

**Comment by Jellico123** [comment]
And I think that I have spotted another problem. This effects the Oo-Suzumebachi and Wurger. Possibly because Small Craft have DropShip DNA in MegaMek.

The wing/side AMS doesn't have ammunition when you load it in game. I suspect the reason is because all the ammo is in the nose. With DropShip .blks ammo had to be assigned to the arc with the weapon bay, rather than a central location like in an ASF or Vehicle .blk.

**Comment by HammerGS** [comment]
Which version of MML are you using?

**Comment by Jellico123** [comment]
I just downloaded the latest dev today to check out the Small Craft.

**Comment by HammerGS** [comment]
Thanks got a fix for those units pending. Let me know if you stumble over anymore. The TRO reference to "Bays" is what created the transport issue.
