### ISSUE TITLE
Dropship mounting artillery can be deployed off board but cannot fire artillery weapons from off board

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#407]
Pretty much what it says on the tin. We discovered this one tonight. No save game, but should be easy to replicate.

**Comment by pheonixstorm** [comment]
I think this is a known issue and may have a ticket on sourceforge

**Comment by Dylan-M** [comment]
It's also incorrect. There's just some prerequisites to making it work:
Must be at Altitude 0
Must have "Grounded Dropships Use Individual Weapons" rule on

I know it works just fine, because I have a Fortress in one of my campaigns.
