### ISSUE TITLE
49.11: Alpha Strike Conversion: Jumpship front arc is not including front left and right sides into the formula

### ISSUE THREAD

**Issue by Morkath** [MegaMek/megamek#4072]
### Environment
Windows
Java 11

### Description
When converting a Jump Ship with the new Alpha Strike conversion process, the front arc values do not include the halfed values for the front left and front right sides.

The calculation for a JumpShip should be;
Front Arc = Nose + 1/2 FLS + 1/2 FRS 
Side Arcs = 1/2 FL(R)S + 1/2 AL(R)S 
Rear Arc = Aft + 1/2 ALS + 1/2 ARS

The side and rear arcs appear to be calculating correctly.

In the attached AS card image, the front and rear arcs should be identical.

### Files
[message.txt](https://github.com/MegaMek/megameklab/files/10300633/message.txt)
[Comitatus JumpShip Sleipnir.zip](https://github.com/MegaMek/megameklab/files/10300638/Comitatus.JumpShip.Sleipnir.zip)
![sleipnir_as](https://user-images.githubusercontent.com/33232503/209482393-f5b9fe82-4bb7-4ff6-9824-3d04147b1906.png)

**Comment by HammerGS** [comment]
Feedback from AS Team on Discord. Related to #3961
