### ISSUE TITLE
Some mechs missing their images in MM.

### ISSUE THREAD

**Issue by BTSS88** [MegaMek/megamek#4075]
0.49.11

Win11

Many mech variants are missing their image files so you get a blob with a red cross instead of a mech. 

The issue seems to be mekset file calling for the png image files using incorrect file name or png files that don't exist. Some variants aren't even listed in the mekset file like the Hermes II 2S to begin with. 

If I go "add a unit" in the MM lobby and scroll down the list, you can see which ones show up as blobs. Once the correct png file name is called in the mekset.txt, the issue is fixed. 

Attached image as example
![Screenshot (9)](https://user-images.githubusercontent.com/119979347/209674718-e028e4f8-6064-482c-bef8-c6553a53d5ea.png)
![Screenshot (11)](https://user-images.githubusercontent.com/119979347/209674753-63e810f9-92d5-409b-a16f-67d4acf14785.png)

![Screenshot (10)](https://user-images.githubusercontent.com/119979347/209674740-349df296-d521-4170-addb-bc9822772dc2.png)

**Comment by HammerGS** [comment]
I've just tested all the above units in 49.11 and they are all working. It could be a couple of things.

1) Did you use the Windows default unzipper if so it's likely this - https://github.com/MegaMek/megamek/wiki/Slow-Unzipping-or-Errors-Unzipping

2) You had previous custom units and you'd added them to the mechset.txt file which is overwritten every release. So if you copied an older version over it would not have the updates and the sprites wouldn't work.

**Comment by BTSS88** [comment]
I used 7-zip as recommended and I didn't copy anything from the previous
version (49.10) other than the save file.

I'll do a fresh install.

Thanks.

**Comment by HammerGS** [comment]
No further comment so closing.
