### ISSUE TITLE
Unsealed Vehicles are not breached in trace atmo if deployed off board

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#408]
I assume this also applies to deploying them in a vacuum.

My opponent had some mobile longtoms that as I understand it would have been destroyed by the trace atmosphere if deployed on board.

**Comment by Dylan-M** [comment]
Need rules clarification from TPTB

**Comment by arlith** [comment]
The rules aren't explicit either way, but the doomed conditions are generally considered planetary conditions, which logically should apply to the whole planet.  I don't think it's a leap of logic to think that if the map is a vacuum then the offboard artillery is going to be deployed in a vacuum.  It's also an easy fix, so I'm going to go ahead and include offboard units in the conditional death check.

**Comment by pheonixstorm** [comment]
I asked about this on the forums and the reply was atmospheric effects affect ALL units, weather effects only affect the play area unless agreed upon by the gaming group. Once the forums are back up I will look up the thread if either of you wish to review the information.
