### ISSUE TITLE
RFE: ammunition templates

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#4091]
I spend a lot of time adjusting ammunition loads on OpFor and allied units generated from MekHQ - reducing counts by 1/4 to 1/2 (e.g. pirates, convoys), switching a bin or two from standard SRMs to infernos (e.g. Harrasser and Bulldog tanks), or from standard AC to tracer for low light conditions, and so on.  I would like to see something implemented to mass adjust a selection of units in the lobby to meet a saved template of ammunition types and amounts.

From a selected number of units in the MegaMek lobby, an additional right-click context menu item would be added e.g. "Ammo Templates", with two additional sub-items, one for "Apply" and another for "Save as...".  Saving the template would create a user-named XML file containing all the selected units, by chassis and model, with the currently set ammunition type and count.  I would want to create multiple possible templates to handle different circumstances e.g. "Marik anti-vehicle" "Pirate standard" "Air defense" and so on.  Applying would prompt the user to select the template file and then match chassis and model between the template and selected units to apply the changes to ammunition.

Bonus points if this could be ported to MekHQ and set the same way Princess controls can be applied, so that OpFor unit ammo can be configured blindly without the player seeing what is deployed using the blind drop/real blind drop options.

**Comment by HammerGS** [comment]
related: https://github.com/MegaMek/megamek/pull/5340

**Comment by Sleet01** [comment]
I hadn't planned on adjusting per-bin round counts in the Munition Loadout Generator but it makes sense...

**Comment by Sleet01** [comment]
Saving munitions loadouts, loading loadouts, and auto-configuration are in MM.
The initial work will only automatically reduce ammo fill percent for Pirate (and unknown third party, in MHQ) faction forces, but now that this functionality is incorporated, making it fully user-controlled is much easier.
As part of the 0.50.1 errata work, I'm planning to:
- store ammo fill ratio in the existing munitions autoconfig file format (.adf file)
- add UI elements for controlling fill percent.
