### ISSUE TITLE
TRO Display missing Jump Jet info

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#4124]
The TRO entry is missing the Jump Jet information. It it tracked in the various files. 

![image](https://user-images.githubusercontent.com/13752452/213765257-e9e5d478-efc7-4e6c-a334-2f2ad5a35938.png)

compared to the actual TRO

![image](https://user-images.githubusercontent.com/13752452/213765379-7421ad7a-f5d8-4a26-a7e8-7e53b2c867a5.png)

### Environment
What version of MegaMek does your issue apply to?  49.12
What operating system are you using?  Windows and Java 11

**Comment by SJuliez** [comment]
Interesting... This is what I get:

![image](https://user-images.githubusercontent.com/17069663/222987104-2fb8bb7e-371a-4e04-832b-5191e56cb5c9.png)

**Comment by HammerGS** [comment]
Opps....I um.... opened and then played around and got a fix in.
