### ISSUE TITLE
advance search spacing issue

### ISSUE THREAD

**Issue by kuronekochomusuke** [MegaMek/megamek#4143]
Starting MegaMek v0.49.11
	Build Date: 2022-12-22T10:48:03.564757800
	Today: 2023-01-28
	Origin Project: MegaMek
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 11 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 8 GB

on the Add A Combat Unit - advance search 

repeatedly opening the advance search causes the spacing to grow between the items.    looks like it is impacting the button panel also.

here is a screen shot after about 10 reopens
![image](https://user-images.githubusercontent.com/116095479/215271519-8dd43ae6-cfc6-4acd-8ddd-7a7902d77162.png)

**Comment by Windchild292** [comment]
Fixed by #4144
