### ISSUE TITLE
Screen cascading in Megamek following mouse cursor

### ISSUE THREAD

**Issue by Dreadcrustacean** [MegaMek/megamek#4153]
### Environment
My issue occurs consistently in both the current standard release of Megamek (0.48.0) and the current development release at the time of posting. (0.49.11)
I am running on Windows 10, current using Java 8 Update 361 (build 1.8.0_361-b09)

OS: Windows 10 Home Edition
Processor: 11th Gen Intel i7-11700F 2.50 GhZ 8 Core
GPU: Nvidia Geforce GTX 1660 Ti
Motherboard: Alienware 0P0JWX A00
RAM: 16 Gb DDR4

### Description
Any version of Megamek, MekHQ, or Meklab I've run on this computer suffers from a strange bug nobody else seems to have seen before. Essentially, upon selecting any kind of sub menu or drop down, the entire window will break and begin cascading on top of itself following the mouse cursor (Its hard to describe exactly, but the attached images should speak for themselves.) I've tried running both the stable and developer versions, reinstalling my Java, reinstalling my graphics display drivers, I've trawled through a Shellex viewer after reading over [this thread](https://github.com/MegaMek/mekhq/issues/125) which seemed to be discussing a similar issue, but nothing has yielded results. 

###Files
https://user-images.githubusercontent.com/124335815/216524102-eeeae1f5-9f8e-40dd-b1dc-c10528397270.mp4

https://user-images.githubusercontent.com/124335815/216524108-6cd6b0bb-76ab-4101-a788-6d680446a757.mp4

https://user-images.githubusercontent.com/124335815/216524111-b33aab41-07df-4e43-95b0-5d99f40b54aa.mp4

**Comment by HammerGS** [comment]
Please try the fixes under Visual artifacts. 

https://github.com/MegaMek/megamek/wiki/Known-Issues-and-Workarounds

**Comment by Dreadcrustacean** [comment]
Well, I feel silly. I skimmed right past that in my search without seeing it, but that worked like a charm. Thanks, and sorry for wasting time.
