### ISSUE TITLE
MM-J17: NPE at End of MM game

### ISSUE THREAD

**Issue by Thom293** [MegaMek/megamek#4171]
23:12:16,954 INFO  [megamek.MegaMek] {main}
megamek.MegaMek.initializeLogging(MegaMek.java:115) - Starting MegaMek v0.49.12-SNAPSHOT
	Build Date: 2023-02-12T01:37:41.488322900
	Today: 2023-02-11
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 2 GB

As title.  No obvious reason from my end.

NPE popped up like 4 times and then MM closed.  I had to resolve manually with Mul.
Not sure if related, but the Ostol listed in the Salvage report was friendly.  I dont think he should appear as salvage.
![Screenshot 2023-02-12 005301](https://user-images.githubusercontent.com/23645569/218297500-93ddd1bf-7aec-4a7d-a8ad-ce3436ce173e.png)

[megamek.log](https://github.com/MegaMek/megamek/files/10715432/megamek.log)
[mekhq.log](https://github.com/MegaMek/megamek/files/10715433/mekhq.log)
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/10715462/autosave.sav.gz)

**Comment by Windchild292** [comment]
Closing as resolved, this was a MM-side break.
