### ISSUE TITLE
MM Turn Sound?

### ISSUE THREAD

**Issue by jason-mehmel** [MegaMek/megamek#4188]
### Environment

4.8

Linux

	Java vendor Debian
	Java version 11.0.18
	Platform Linux 5.10.0-21-amd64 (amd64)

### Description
I've been away from MegaMek for quite a few years and just came back recently. The last version I played, there was a chime between turns, that I don't notice now. I can't find any notes indicating it was removed. (Though I just may not have found them!)

Either reporting that there is no chime, or asking if that chime has been removed!

### Files

n/a

**Comment by HammerGS** [comment]
We turned turned it off by default. But starting in 0.49.12 it’s been updated. 

You can reenable it in the game settings.
