### ISSUE TITLE
Battle Armor Weights Not Adjusted for Weight Class/Damage?

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/megamek#42]
Aren't Battle Armor squads supposed to weigh different amounts depending on the class of suit?  Right now it seems that all squads weigh 1 ton per member and retain their full weight values even when squad members are lost.

**Comment by arlith** [comment]
Those are the TW rules.  What you have in mind is an advanced option for TO.  Pretty sure there's an RFE for that optional rule.

**Comment by mkerensky** [comment]
Ok, thanks

**Comment by pheonixstorm** [comment]
Actually I have had that working for awhile MM forum post here http://megamek.info/forums/index.php?topic=2054.msg13357#msg13357

Working branch https://github.com/pheonixstorm/megamek-storm/tree/TacOps-BAWeights

There are a few things that were brought up I still need to work on but for the most part it works. Once it is complete I will put up a pull request for the devs.

**Comment by arlith** [comment]
Meant to close this before.  It's a TO option, and will get implemented soon.  It's not really a bug, and there's a PR, so I don't think we need this issue.
