### ISSUE TITLE
Jumping Mech is Not Bogged Down in Swamp Automatically After Sucessful DFA

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#420]
[NotBoggedDown.sav.gz](https://github.com/MegaMek/megamek/files/600597/NotBoggedDown.sav.gz)

Hit a Wyvern with a DFA which landed my jumping Vulcan into a swamp hex. Normally a jumping mech is automatically bogged down in swamp. The Vulcan did not get bogged down, and does not appear to have even made a check for it.

**Comment by Dylan-M** [comment]
And do the rules specifically state if it includes a DFAing unit or not?

**Comment by VampireSeraphin** [comment]
I'll try and look.

**Comment by wildj79** [comment]
So, the Bog Down Rules in TO (p. 62-63), don't specifically state that a 'Mech that is attempting a DFA gets stuck on landing, but it does say that _"A jumping 'Mech that **lands** in such a hex automatically gets stuck."_ The DFA rules in TW (p. 149-150) also clearly state that _"At the end of a death from above attack, the attacker **lands** in the target's hex."_ From those two sentences, I would make a case that a jumping 'Mech landing in a swamp hex after conducting a death from above attack **does** automatically get stuck. But, we might need a rules clarification.

**Comment by HammerGS** [comment]
Checked with the rules team.  Per the rules on 63-63, it DOES become bogged down.
