### ISSUE TITLE
Toughness Text In Pilot Tab Spacing Issue

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#421]
Under the pilot tab in MM the toughness value looks like its smushed up against the last "s" of the word toughness.  So, if it was a value of 1 it appears like the s is written over the 1. Windows 7-8.1

![slack](https://cloud.githubusercontent.com/assets/16950832/20492380/2053414c-afda-11e6-949e-fb1f5b8956a4.png)

**Comment by BLOODWOLF333** [comment]
````        toughBL = createLabel(Messages.getString("PilotMapSet.toughBL"), fm, pilotL.getSize().width + 75, getYCoord()); //$NON-NLS-1$
        content.addArea(toughBL);
        toughBR = createLabel(STAR3, fm, pilotL.getSize().width + 75 + initBL.getSize().width + 25, getYCoord());
        content.addArea(toughBR);````
I dont know how to submit this yet but it works.

**Comment by BLOODWOLF333** [comment]
![image](https://cloud.githubusercontent.com/assets/16950832/21990885/11506f8a-dbd6-11e6-92d9-1a8636ec060e.png)

**Comment by arlith** [comment]
There were some issues with PR #477, particularly the file had its contents doubled.  I was able to figure out what the code changes were and get them applied.
