### ISSUE TITLE
MegaMek Canon Mech Quirk Errors

### ISSUE THREAD

**Issue by AotrsCommander** [MegaMek/megamek#4210]
### Environment
MegaMek, starting from Snapshot 0.49.11.

### Description
Attached is a compiled list of quirk errors or issues discovered, i.e. mechs with no quirks that should have them, quirks they shouldn't have etc.

The quirks in MM for the canon mechs (i.e. everything but unofficial variants) I examined have been checked against BMM, BMM errata 5.0 and the TRO Primitives as appropriate. In addition, there are a couple of possible issues which I could not verify (as I dont have access to TRO Prototypes).

(Note: this not comprehensive across the entire list of MM, as it was started as I was going through the subset of mechs and variants I have models of, while I checked to note which mechs had weapon quirks that wouldn't print on the record sheets for TT. I would hazard it is still a fairly a significant chunk, however, and covers a fair amount of the most common mechs. I did check probably around 2400-2450 or so (give or take the amount of customs I inputted at the same time).  

Compiled List of discovered Quirk issues.

All others have been checked verses BMM, BMM errata 5.0 and the TRO Primitives as appropriate. 

In the latter case, some mechs have primitive versions with ONLY the quirks in TRO Primitive (which is what I believe would be correct) and some have their standard BMM quirks as well (which I believe is in error). I have reported the latter. Which approach is to be taken is in the programmer's hands; I can only report that as it stands, it's not consistent.)

- [x] Executioner-B: No quirks. Should have Distracting, Poor Performance.
- [x] Icestorm: should have Improved Sensors as well as Rugged (1). (cf BMM)
- [x] Katana: In MM, it's got Easy to Pilot. No quirk listed for it specifically in BMM (or Sarna); if it defaults to the Crockett, that also has poor Life Support.
- [x] Marauder: Missing quirks: Marauder Bounty Hunter (3138), MAD-2T, 5CS, 7C, 7M. 7R, 7S, 11D 
- [x] Unclear: MAD-9M has directional torso mount for Streak SRM-6, MAD-9M2 does not; RAW methodology suggests the latter is an omission.
- [ ] Mercury C 2: ER SL not listed as Stabilised.
- [x] Orion ON1-H: Should not have AA targeting and Rugged (from TRO Primatives Vol 5); may need Obsolete (2525).
- [x] Phoenix Hawk: No versions have Jettison capable weapon (Large Laser); should be present on at least on versions with LL and maybe ER LL.
- [x] Raijin (101-A, 101-B, 101-C, 101-X, 301-B): No quirks, should have Directional Torso Mount (LT/RT), Extended Torso Twist, Bad Reputation (cf BMM)
- [x] Raven II: Should not have No/Minimal Arms quirks (according to TRO 3150 and it's not a variant of the base Raven, though it's probably being picked up as such; means having to redo all the Ravens by chassis, unfortunately).
- [x] Rifleman IIC shouldn't have Cowl (according the BMM, no errata found).
- [x] Rifleman 5CS, 7N, 7N2: No quirks. Should have Rifleman standard Rifleman quirks (Anti-Aircraft Targeting, Improved Communications, Searchlight, Ubiquitous)
- [x] Shadow Cat III: Has Narrow/Low Profile, can't verify this is correct, recommend check Ilclan vol 3.
- [x] Shadow Hawk C, 5R, 5S, 6D, 7H: No quirks, should have standard Shadow Hawk quirks (Battlefists, Improved Life Support, Rugged (1), Ubiquitous).
- [x] Snow Fox Omni: No quirks. Uncertain whether this is oversight or not.
- [x] Thunderbolt TDR-1C: Should not have Rugged (2) or Ubiquitous (from TRO Primatives Vol 3)
- [x] Warhammer: Should have Ubiquitous (cf BMM)
- [x] Wasp: WSP-1 should only have Hard to Pilot, Weak Legs (cf TRO Primatives vol 2)
- [x] Trebuchet 9N: No quirks, should have standard Trebuchet quirks (Easy to Maintain, Fast Reload (torso weapons)
- [x] SuburbanMech: No quirks, should have standard UrbanMech quirks Extended Torso Twist, Narrow/Low Profile, No/Minimal Arms (despite the name, a variant of UrbanMech)
- [x] Ursus: Ursus 3 and PR potentially should not have distracting (check TRO Prototypes/XTRO Clans to confirm).
- [x] Vanquisher: Should have Bad Reputation (IS), No/Minimal Arms (cff BMM)
- [x] Wolf Trap: WFT-2B has both Easy to Maintain and Easy to Pilot; recommend checking TRO Prototypes to check it should indeed have the latter, as it seems like it could be a mis click.
- [x] Wolfhound: 2H has no additional quirks; recommend check TRO Prototypes to see if it should have Cooling System Flaws and Easy to Maintain (or whether the 2X should have those, since that also has only standard Wolfhound quirks)
- [x] Wolverine: WVR-9R, 10D, 10R, 10V2, 11M: No quirks, should have standard Wolverine quirks: Command ’Mech, Extended Torso Twist, Improved Communications, (no Jettison-Capable Weapon (AC/5) because no AC/5s), Protected Actuators, Ubiquitous; Cramped Cockpit.
- [x] Xanthos: XNS-2O should not have Improved Life Support (TRO Primitives vol 4)
- [x] Zeus: Recommend check ZEU-6Y in TRO Prototypes to see whether it should have Barrel Fist.

**Comment by HammerGS** [comment]
Fixed the check ones. 

Mercury C 2: ER SL not listed as Stabilised. (No such official unit in MegaMek or the MUL)
Snow Fox Omni: No quirks. Uncertain whether this is oversight or not. - No data so leaving with out.

**Comment by AotrsCommander** [comment]
*headdesk*

 

That's 'cos I'm a dunce and I didn't mean the Mercury C 2 (which as you say
is Not A Thing), I meant the Mongoose C 2. (Mongoose just so happening to
come first after "mercury" in my personal list and the 2 C of which is the
first Mongoose in alphabetical order, so this muppet over here wrote the
wrong name down on his list.!)

 

Sorry!
