### ISSUE TITLE
Spotted units are highlighted

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#422]
Can we get an indicator similar to the targeting modifiers, that gets attached to a unit when it is spotted for indirect fire?

**Comment by arlith** [comment]
I have updated the firing solutions so that they highlight the hex border with a red/yellow striped line for units that are spotted.  Also, the tooltips for spotting units now display which unit they are spotting.

**Comment by arlith** [comment]
Sorry, I had intended to attach a screenshot, but then forgot.  Here it is:

![screenshot at 2016-11-23 10-07-36](https://cloud.githubusercontent.com/assets/13815237/20570455/420a69c4-b169-11e6-930c-ea2badc7f446.png)
