### ISSUE TITLE
[0.49.12] Illegal/overweight BA units

### ISSUE THREAD

**Issue by Gribbly1** [MegaMek/megamek#4223]
Bundled Megamek with MekHQ 0.49.12
Windows 10, Java Version: 11.0.13

- [x] The SRM variant of the Callisto is overweight due to the ammo not being included in the SSW mount.
[callisto srm.zip](https://github.com/MegaMek/megamek/files/10890765/callisto.srm.zip)

- [x] The AP Gauss variant of the Elemental III is illegal due to excess right arm crit slots (presumably due to a correction to AP Gauss size in 49.12?) [elemental iii apg.zip](https://github.com/MegaMek/megamek/files/10890766/elemental.iii.apg.zip)

- [x] All of the non-Support variants of the Fa Shih suit have two mine dispensers where they should have one. Each dispenser can drop two mines as per To AUE p137 (this is correctly implemented in MM). Fa Shih should only be able to drop two mines, not four. The extra equipment has made some variants illegal in MM due to weight.
TRO 3058U p21 lists a single 50kg dispenser, RS 3058 unabridged (p25?) confirms two mines per suit.

**Comment by HammerGS** [comment]
Thanks for the fixes, the mine thing will need some additional work. Also if you submit files could you keep the file naming conventions the same. We are trying to keep names short to prevent issues with Windows unzipping.

**Comment by HammerGS** [comment]
I've got a fix for the Fa Shih. 
https://github.com/MegaMek/megamek/commit/590c74c2c637af0d7669996fc7413b789ca2f951
