### ISSUE TITLE
RFE: Show TRO Tab in Game in the Unit Information. 

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#4242]
Not sure how hard this would be, but the ability to view the TRO tab from the Unit Selector would be a useful addition. It would serve as a "Warbook" and let players see and read fluff and TRO presented data in game. 

This would help new players learn about other units information versus strictly seeing a Record sheet type information.

**Comment by BullseyeSmith** [comment]
No copywrite issues with this?

**Comment by HammerGS** [comment]
We don’t use direct copy and paste from the books. Fluff data is based on Sarna.
