### ISSUE TITLE
0.49.12 Error when saving custom weapon order

### ISSUE THREAD

**Issue by EvilAtlas** [MegaMek/megamek#4283]
### Environment
MekHQ 0.49.12, on Windows 11, using Java 11.0.14.1.

### Description
When I try to save a unit's weapon order in a game of MegaMek (which mostly comes up in AtB campaign games, but I think this still happens in standalone games), I get a NullPointerException error and the weapon order fails to save. I don't think this always happens, but I have no idea what conditions cause it to _not_ happen, since I don't remember the last time it didn't.
![Screenshot 2023-04-01 115435](https://user-images.githubusercontent.com/94950654/229309366-0b8d6b68-8075-426a-b8d4-a29820d7115a.png)

### Files
[custom_weapon_order_error.zip](https://github.com/MegaMek/mekhq/files/11130366/custom_weapon_order_error.zip)
The current mission it's failing on is the recon mission on the 18th, but as mentioned above, it happens in pretty much any scenario.

**Comment by HammerGS** [comment]
```
megamek.common.WeaponOrderHandler.getWeaponOrder(WeaponOrderHandler.java:256) - Failed to load custom weapon order file
java.io.IOException: java.lang.IllegalArgumentException: No enum constant megamek.common.enums.WeaponSortOrder.Range (High-Low)
	at megamek.common.WeaponOrderHandler.loadWeaponOrderFile(WeaponOrderHandler.java:235)
	at megamek.common.WeaponOrderHandler.getWeaponOrder(WeaponOrderHandler.java:253)
	at megamek.common.Entity.loadDefaultCustomWeaponOrder(Entity.java:14171)
	at megamek.common.MechFileParser.postLoadInit(MechFileParser.java:165)
	at megamek.common.MechFileParser.parse(MechFileParser.java:155)
	at megamek.common.MechFileParser.<init>(MechFileParser.java:57)
```

@kuronekochomusuke I think you worked on this last any ideas?
