### ISSUE TITLE
MASH vehicle unit rename not reflected in AtB civilian RATs

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#4299]
The generic MASH trucks have been renamed from "M.A.S.H." to "MASH" (no periods) somewhere between 49.7 and 49.12.  However, the civilian RATs used in AtB unit generation have not been updated.

MegaMekLab:
![image](https://user-images.githubusercontent.com/70451747/230782780-c1fe07f9-24e7-40e8-b286-a116f8ab11b8.png)

CivilianUnits.txt, CivilianUnits_CivVeh.txt (inside rat_default.zip):
`
M.A.S.H. Truck (Standard),18
M.A.S.H. Truck (Small),9
M.A.S.H. Truck (ICE),27
`
Might be an idea to have a review of the contents of the civilian units RAT files against the actual names present in MML to catch any other spelling changes.

**Comment by HammerGS** [comment]
Fixed with https://github.com/MegaMek/megamek/commit/2e6e239243d2718b4493fa6368dffd7ed4b94f7b
