### ISSUE TITLE
Conflicting rules on Rubble unit restrictions (errata, use TW terrain restrictions)

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/megamek#43]
After following along Weirdos happiness over another fringe ruling I brought up the fact that TacOps does not show wheeled units being restricted from Rubble hexes even though they ARE restricted from entering based on the Total Warfare rules. There is a pending question in the rules forum to get this straightened out here http://bg.battletech.com/forums/index.php?topic=51221.0

Based on how rough terrain is handled (no wheeled lvl1, no vees lvl 2) I would guess Rubble should be the same but...

**Comment by pheonixstorm** [comment]
This has now been answered. TO is getting an errata to match TW
http://bg.battletech.com/forums/index.php?topic=51221.0
No wheeled for rubble

**Comment by pheonixstorm** [comment]
@arlith I will be doing a bugfix PR for this and the Bog Down and maybe a few other bugs (if I can find any easy enough for my skills) over the next few days.

**Comment by arlith** [comment]
Fixed with PR #183.
