### ISSUE TITLE
No Help Available: error reading readme.txt

### ISSUE THREAD

**Issue by arthurljones** [MegaMek/megamek#4301]
### Environment
Version: MegaMek.jar v0.49.12
OS: Linux, Pop!_OS 22.04 LTS
Java: openjdk 11.0.18

### Description
I get a "Help Not Available" whenever attempting to view the docs:
![screenshot](https://user-images.githubusercontent.com/145591/230795679-486d676a-1954-4249-9964-f6e396f6fcf0.png)

I searched open and closed issues on github and in the old sourceforge tracker and could find nothing recent enough to seem directly relevant. I suspect the issue is that the backslashes in the path are invalid path separators on Linux. A tangentially related recent PR to fix the loading of the ai docs (#4149) seems to support this suspicion - path separators were changed to forward slashes, and I confirmed that the notes load correctly when adding a bot to a game and accepting the dialog.

My repro steps:
- I extracted the latest development build from https://megamek.org/downloads.html into a new directory.
- I started MegaMek using `java - jar MegaMek.jar`
- I got a dialog suggesting I read the docs, and opted to do so
- The error dialog was shown

The dialog is shown when accepting the dialog on subsequent launches, and also shows when using the Help > Contents menu item.

Here's the contents of my `docs/1-Readme` directory:
![screenshot](https://user-images.githubusercontent.com/145591/230795820-26e8420a-c0ef-40b5-8336-bd66625dfcc9.png)

This issue is reproducible every time.

### Files
[megamek.log](https://github.com/MegaMek/megamek/files/11186278/megamek.log)

**Comment by Mr-ZenoUK** [comment]
MegaMek: 49.19
I'm adding to this as it is a very similar issue (missing documentation) with MegaMek Map Editor.
The error message when saying "yes" you would like to read the documentation is:

Error reading help file: F:\mekhq-windows-0.49.19\docs\Boards Stuff\Map Editor-readme.txt (The system cannot find the path specified)

**Comment by Sleet01** [comment]
I saw this as well.  It looks like we have mixed path separators (a combination of Linux / OS agnostic "/" and Windows-specific "\") in the generated path.

**Comment by ShadowDragon8685** [comment]
I just saw this when trying to use the readme for the Map Editor, but the error in that case seems much more fundamental; instead of `/Map Stuff`, the documentation is now in the `/Map and Board Stuff` folder.

**Comment by Sleet01** [comment]
So looks like we need to fix:
```Error reading help file: /home/<user>/bin/MegaMek/MekHQ-0.50.0-SNAPSHOT/docs\1-Readme\readme.txt (No such file or directory)```
```Error reading help file: /home/<user>/bin/MegaMek/MekHQ-0.50.0-SNAPSHOT/docs\Boards Stuff\Map Editor-readme.txt (No such file or directory)```

Princess Notes.txt seems to load correctly.
