### ISSUE TITLE
49.12 - Corrected Partisan mtf

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#4316]
Corrected Partisan Hull Defense mtf. Unit was missing its reflective armor.
Goes into vehicles/XTRs/Corporations.

[Partisan Hull Defense (Standard).zip](https://github.com/MegaMek/megamek/files/11211784/Partisan.Hull.Defense.Standard.zip)

**Comment by HammerGS** [comment]
Fix with https://github.com/MegaMek/megamek/commit/8bc12aa98cb3a8358beb622aa74db95e3864a6d5
