### ISSUE TITLE
RFE: IndustrialMech critical hit locations

### ISSUE THREAD

**Issue by TigerShark** [MegaMek/megamek#432]
Currently, if an IndustrialMech takes physical or falling damage, they roll for a random critical hit. So a kick to their leg could crit the cockpit, feasibly.

I'd like an option which limits the crit to the location being hit. i.e.: you get punched in the RT, the crit shouldn't occur in the RA; it should be rolled in the RT. Seems like it should already work that way with floating crits anyhow, no?

**Comment by NickAragua** [comment]
This is unlikely to happen as it is not an official rule and the team's bandwidth for implementing non-official rules is very limited.
