### ISSUE TITLE
Last eligible unit in fire phase being skipped to end the Weapons Fire phase.

### ISSUE THREAD

**Issue by FlameDraken84** [MegaMek/megamek#4326]
MegaMek with MekHQ 0.49.12
Windows
Java 11.0.11

I am having a recurring issue where the last unit in the weapons fire phase is being skipped and ending the turn when that unit is eligible to fire weapons.  The issue is inconsistent when it appears as it can happen several turns back to back but then not occur in the next turn.  It is also not consistent between games.  Some games I won't have the issue, then a game right after I will see the issue pop up again.

In detail, I will have my second to last unit fire its weapons and click on done.  The game will not switch over to the final unit in the fire phase but will end the turn instead.

The save file attached has my second to last unit ready to fire.  Firing either the Commando or Strider's weapons will skip the other mech's fire phase.  All other units have fired at this time.

The log is from a load of the save just before the error.

[megamek.log](https://github.com/MegaMek/megamek/files/11239254/megamek.log)

[Bug WF Phase.sav.gz](https://github.com/MegaMek/megamek/files/11239232/Bug.WF.Phase.sav.gz)

**Comment by HammerGS** [comment]
Are you using any of Sim options like Sim Fire, Sim Physical?

If so we’ve know the issue is related to that and they shouldn’t be used.

**Comment by FlameDraken84** [comment]
I am using sim targeting, fire and physical.  

I also use skip ineligible physical but not firing if that helps.

**Comment by HammerGS** [comment]
As mentioned, the sim options shouldn't be used as they are unofficial and giving issues. We'll attempt to track things down with the save provided. But other saves have proven impossible to duplicate.

**Comment by HammerGS** [comment]
Only error in log

```
megamek.client.ui.preferences.SuitePreferences.readPreferencesNode(SuitePreferences.java:184) - No class with name mekhq.gui.dialog.nagDialogs.UnresolvedStratConContactsNagDialog found
java.lang.ClassNotFoundException: mekhq.gui.dialog.nagDialogs.UnresolvedStratConContactsNagDialog
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at megamek.client.ui.preferences.SuitePreferences.readPreferencesNode(SuitePreferences.java:180)
	at megamek.client.ui.preferences.SuitePreferences.loadFromFile(SuitePreferences.java:133)
	at megamek.MegaMek.main(MegaMek.java:84)
```

**Comment by kuronekochomusuke** [comment]
#3304
