### ISSUE TITLE
RFE: Ability to search a Map Board by Name/Size/Features

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#433]
As the RFE says.

Would be nice to be able to search a map by things like:

Name
Size
What features it has.

**Comment by repligator** [comment]
As of 50.00 snapshot (https://github.com/MegaMek/megamek/commit/3dbf18d1df372276179edce2e96857c9ac835901), this has sort of/kind of been partially implemented. Maps can be sorted by size in hexes, and then these maps be filtered by a set of feature based keywords. However there is no way to sort through all maps by features, nor to search for a map by name.
