### ISSUE TITLE
[49.12] Tarantula ZPH-1A should be ZPH-1

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#4335]
Currently Megamek has the earliest Tarantula variant listed with ZPH-1A as the model number. Per the [MUL entry](http://www.masterunitlist.info/Unit/Details/3160/tarantula-zph-1), it should be ZPH-1.

**Comment by HammerGS** [comment]
Fix with https://github.com/MegaMek/megamek/commit/8bc12aa98cb3a8358beb622aa74db95e3864a6d5
