### ISSUE TITLE
[Dev env] Intellij Idea Community Edition 2023 no longer includes "Settings Repository" plugin by default

### ISSUE THREAD

**Issue by Sleet01** [MegaMek/megamek#4342]
Wiki page "Complete Development Environment Setup using Intellij Idea" ([here](https://github.com/MegaMek/megamek/wiki/Complete-Development-Environment-Setup-using-IntelliJ-Idea)) needs to be updated to include a step directing devs to install the "Settings Repository" plugin.

### Environment
MM: 49.12
OS: Ubuntu 22.04 (Linux)
Java: 17.0.6

### Description
Step 9 of the above page cannot be completed as written; the user needs to install the "Settings Repository" plugin manually now.

### Files
N/A

**Comment by Thom293** [comment]
These steps just need to be typed into the page. 

![Screenshot_2023-02-26_212203-1](https://user-images.githubusercontent.com/23645569/233217745-8aba936a-b4c9-482b-9017-12d4d95b9234.png)

**Comment by SJuliez** [comment]
Done.
