### ISSUE TITLE
Princess Help text opens constantly. 

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#4345]
Getting lots of reports and seeing this myself. Nothing in the logs. Started in 49.12

I'm getting the bot help text every time I add one now. Is that intended or did I accidentally turn a setting on?

### Environment
What version of MegaMek does your issue apply to?  49.12
What operating system are you using?  Windows

**Comment by BLR-IIC** [comment]
I've actually experienced this before 0.49.12 but never bothered to report it as it didn't bother me that much.  This bug has been around for a long time, at least since 0.49.0 I believe.
