### ISSUE TITLE
[49.12] ER Micro Lasers don't count for medium range damage during the alpha strike conversion on non-BA units

### ISSUE THREAD

**Issue by Morkath** [MegaMek/megamek#4347]
### Description
ER Micro Lasers don't count for medium range damage calculation on non-battle armor units.  Other 4 range weapons such as the Heavy Flamer do count on these unit types.

1) Load the Elemental Battle Armor [ER Laser]
2) Swap to the AS card tab
3) Press the conversion report button

ER Micro Laser is listed under the medium damage conversion section.

1) Load the Piranha 3
2) Swap to the AS card tab
3) Press the conversion report button

ER Micro Lasers are only listed under the short range damage conversion section.

Repeat with the Pouncer F.  The Heavy Flamer is listed under both short and medium range damage conversion, while also having a max range of 4.

**Comment by HammerGS** [comment]
Official Comment from NCKestrel. 

For AS conversions, 'Mechs are counting ER Micro Lasers as short only (Piranha 3 for example), as listed in AS Companion.  Battle Armor are including them in medium (Elemental ER Micro version).

**Comment by SJuliez** [comment]
@HammerGS So, MM's conversion is correct, is it?

**Comment by HammerGS** [comment]
> @HammerGS So, MM's conversion is correct, is it?

We seem to have an issue with the BA. 

Our Card
![image](https://user-images.githubusercontent.com/13752452/235362784-a1e63f9c-25b3-46ee-9b5a-aa39096e66e4.png)

MUL Card
![image](https://user-images.githubusercontent.com/13752452/235362799-e660cb69-dcda-45e0-851b-82d08796d0cd.png)

**Comment by SJuliez** [comment]
@HammerGS This confuses me. ASC has no ER Micro Laser entry other than the one on p.109 that says 0.2/0/0 damage. In MM, we have a BA ER Micro Laser which act as 0.2/0.2/0 damage. This sounds like what you wrote above but (again) ASC is silent on that. Since the SRM 2 of this BA also is 0.2/0.2/0 I can't see how the S and M values could be different. So... where is the mistake?

**Comment by HammerGS** [comment]
I asked the AS gurus and they explained this. 

The same weapon ER Micro Laser should not be short only for 'mechs and short/medium for battle arrmor.  they both have the same range.  ASC only lists 0.2/0/0 (what is being used by MM for 'mechs).  BA should also be 0.2/0/0.
