### ISSUE TITLE
0.49.13 - Artillery Cannons Not Giving Flak Modifier

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megamek#4359]
### Environment
megamek.MegaMek.initializeLogging(MegaMek.java:116) - Starting MegaMek v0.49.13-SNAPSHOT
	Build Date: 2023-04-20T01:18:11.498730800
	Today: 2023-04-25
	Origin Project: MegaMekLab
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 4 GB

### Description
TW p.114 lists "Flak" as "When used against a unit that presently has an Altitude or Elevation, or that expended any VTOL or WiGE MP or Thrust Points that turn (even if it landed at the end of that Movement Phase), apply a –2 to-hit modifier in addition to any other modifiers such weapons might convey."

TO:AUE p.216 explicitly lists Artillery Cannons as having the Flak property

When using a Long Tom Cannon mounted on a tank to shoot at an airborne VTOL, the flak modifier is not being applied (screenshot below).

Savegame included for testing as well as the particular units used in my test, though the Rommel (Howitzer) and any VTOL can be substituted to get the same results.

### Files
[ArtyCannon_vs_VTOL.zip](https://github.com/MegaMek/megamek/files/11327665/ArtyCannon_vs_VTOL.zip)

![LTCvsVTOL](https://user-images.githubusercontent.com/101755917/234433113-e01cf444-62c4-4ad7-bdcd-6330d037ae12.png)

**Comment by Saklad5** [comment]
I can confirm that this extends to other units using VTOL MP: 
<img width="391" alt="image" src="https://user-images.githubusercontent.com/4258823/234434375-decffaa5-18a7-4453-a949-7e56c3864c79.png">

**Comment by PhoenixHeart512** [comment]
Also affects Aerospace, so it's more likely that the issue is actually "Artillery cannons missing the Flak modifier" entirely.

**Comment by PhoenixHeart512** [comment]
Edited title to reflect that it's not just against VTOLs

**Comment by PhoenixHeart512** [comment]
Firing phase report shows "FLAK" rounds but does not actually give the modifier
![image](https://user-images.githubusercontent.com/101755917/236117143-ea0fd7e7-d2a5-4c8d-b9d0-aa53ec9e4165.png)

**Comment by Sleet01** [comment]
Checking...

**Comment by Sleet01** [comment]
Apologies, I think I added the "close" line for this issue to my commitment message but have not yet gotten the -2 Flak bonus added.  Currently artillery Flak is only getting the stock +3 (vs +4 indirect).

I'll fix this up forthwith.
