### ISSUE TITLE
[0.49.12] Bug: Fuel usage for ASF/CF is no longer tracked with the Fuel Consumption option enabled

### ISSUE THREAD

**Issue by Gribbly1** [MegaMek/megamek#4373]
Bundled Megamek with MekHQ 0.49.12
Windows 10, Java Version: 11.0.13

![Capture](https://user-images.githubusercontent.com/55139229/235322256-20103380-b9b6-4674-a9cd-daadce6c3419.PNG)

[test.sav.gz](https://github.com/MegaMek/megamek/files/11359999/test.sav.gz)
save name: test

Fuel isn't being reduced with thrust in 49.12. Please can you reinstate this with the option enabled.
SO:AA p32/33

**Comment by SJuliez** [comment]
This is already fixed in 0.49.13
