### ISSUE TITLE
MTF Files:  Beowulf C appears to be non-canon

### ISSUE THREAD

**Issue by RexPearce** [MegaMek/megamek#4375]
Beowulf C appears to be a non-canon unit. It's not mentioned on Sarna and doesn't exist in the MUL:
http://masterunitlist.info/Unit/Filter?Name=Beowulf

Some discuss on the forums from 8 years ago:
https://bg.battletech.com/forums/general-discussion/the-mystery-of-the-beowulf-c/
https://bg.battletech.com/forums/ask-the-writers/the-mystery-of-the-beowulf-c-45538/

Affected file: "megamek/data/mechfiles/mechs/3085u/ONN/Beowulf C.mtf"

Should be deleted or moved to "data/mechfiles/unofficial"?

**Comment by HammerGS** [comment]
Per note in PR
