### ISSUE TITLE
SBF Conversions Do Not Account For MHQ Specials Derived From Nova

### ISSUE THREAD

**Issue by pokefan548** [MegaMek/megamek#4381]
### Environment
MegaMek Version 0.49.12 Snapshot

### Description
When attempting to convert a force to a Strategic BattleForce Formation, MHQ specials derived from Nova CEWS do not seem to be factored into the conversion process.

### Files
[A39_SBF.pdf](https://github.com/MegaMek/megamek/files/11361038/A39_SBF.pdf)
Alpha-39 should have MHQ3. Each 'Mech as one Nova CEWS, and Pariah (Septicemia) (Michael) has 6 tons of Communications Equipment, for a total of 9 MHQ points. However, the conversion report lists the three 'Mechs as only providing 6+0+0 levels of MHQ instead of 7+1+1.

**Comment by SJuliez** [comment]
If I remember and read the rules correctly (but this is very much off the top of my head) there is actually a rule that says to use MHQ - 1.

**Comment by pokefan548** [comment]
Ah, right. Didn't catch that. Very well then.
