### ISSUE TITLE
Bug: Repeating TSEMP Cannon not available for all compatible units

### ISSUE THREAD

**Issue by Saklad5** [MegaMek/megamek#4385]
### Environment
MegaMek Version: MekHQ v0.49.12 Development Snapshot
Operating System: Mac
Java Version: 19.0.2

### Description

The Repeating TSEMP Cannon is not shown as an option for aerospace fighters and other units, even though it is explicitly listed[^1] as being usable with quite a few.

[^1]: Page 88 of *Interstellar Operations: Alternate Eras*

It is currently missing from the following unit types:

* Aerospace fighters
* Conventional fighters
* Small craft

It's also compatible with mobile structures, but those aren't implemented yet anyway.

**Comment by SJuliez** [comment]
What is your game year? It is only available between 3133 and 3138 as per IO:AE p.39

**Comment by Saklad5** [comment]
That's irrelevant: even if it is extinct, it should be possible to mount it.

**Comment by SJuliez** [comment]
Such harsh words when I was just happy I could finally get it to be available in MML...
But true on Aeros it isn't even shown as unavailable.

**Comment by SJuliez** [comment]
Sadly already midnight again... this will be for another day

**Comment by Saklad5** [comment]
> Such harsh words when I was just happy I could finally get it to be available in MML...

You could also go to File → Options → Configuration, click the Tech Progression tab, and check "Show extinct equipment".
