### ISSUE TITLE
Cannot give pilots natural aptitude: gunnery or natural aptitude: piloting

### ISSUE THREAD

**Issue by crazys1** [MegaMek/megamek#439]
Version 0.41.27

Description:

Natural aptitude: gunnery and natural aptitude: piloting are not in the list of SPAs when you configure a pilot, and therefore you cannot choose them.

This issue is also true in the MekHQ, but I'm guessing that fixing here will probably fix it there, too, so I opened this bug only for MegaMek.

To reproduce:

1. Start MegaMek.
2. Add a 'Mech (any will do).
3. Double-click the 'Mech to open the configuration dialog.
4. Under the Pilot tab, scroll down and try to find natural aptitude: gunnery and natural aptitude: piloting. They are not there.

**Comment by HammerGS** [comment]
Fixed with https://github.com/MegaMek/megamek/commit/278f37a

When the Literal constants conversion was done I moved the natural
aptitudes to reorder the other SPAs.  I forgot to put them back in.
