### ISSUE TITLE
[Bug/Data] Ares Superheavy does not have generic sprite assigned

### ISSUE THREAD

**Issue by stonewall072** [MegaMek/megamek#4409]
Present as of 0.49.12

Noticed this with the Ares Apollo which as of noted release does not have a variant sprite. There is a generic Ares sprite in the Units/Mechs folder, but it is not assigned as a chassis sprite in mechset.txt. Assigning this would cover the Apollo configuration until a variant sprite is made and cover any customized configuration a player might create.

**Comment by HammerGS** [comment]
This has been fixed in Dev. At the time of release the Apollo was still under moratorium and waiting art.

If the unit is published by CGL after release it won't have sprite, or data until 60 days from the release of the CGL product.
