### ISSUE TITLE
Fled units not being saved at the end of the game

### ISSUE THREAD

**Issue by mnmib1** [MegaMek/megamek#441]
MegMek v41.27 windows

Units that flee the field are not being saved at the end of the game.  At the end of the game it asks if you want to save the units.  The units that fled are not saved in this .mul.  I checked to see if they were in the salvage but they are not.  I am attaching the endgame .mul, salvage .mul, gamelog.html, and the megameklog.txt.  The end game .mul is Lyons' Legion.mul

**Comment by mnmib1** [comment]
I have posted the attachment at the link below:

http://bg.battletech.com/forums/index.php?topic=55691.msg1282019#msg1282019

**Comment by arlith** [comment]
You should be able to attach files to GitHub.  It's not terribly intuitive, imo, but you can just "drag and drop" files onto the comments section to attach.  Also, at the bottom of the comment box is a message that reads, "Attach files by dragging & dropping or selecting them."  That "selecting them" bit is a hyperlink that opens up a file dialog.

**Comment by mnmib1** [comment]
Yes I'm aware of both methods.  However, just as I can't download from Github, neither can I seem to upload.  I'm not a moron.  I've attached files plenty of times to SF and obviously the BT forums.

I regards to the bug, it appears to save my units, but not the bot units which have fled.

**Comment by mnmib1** [comment]
More information.  If you connect as a computer player the fled unit is saved.  But if you add a bot through the 1st instance of MM it is not.

**Comment by HammerGS** [comment]
Attaching file from Forum.
[Fled units not saved.txt](https://github.com/MegaMek/megamek/files/657505/Fled.units.not.saved.txt)

**Comment by arlith** [comment]
Without a saved game, the rest of the files won't really help me out.  I looked at the code, and there is code to save units that flee.  It looks like it should trigger to me.  Without a saved game, I can't really tell why it it didn't save your fled units in this particular case.

Also, the attachments on the forum is a text file that has the same text as this bug ticket, but it doesn't seem to have any of the additional files.

**Comment by mnmib1** [comment]
This is a easily repeatable error.  Start new game.  Add bot.  Tell princess to flee immediately.  Game ends.  Fled 'Mech not saved.

**Comment by neoancient** [comment]
Any retreated units belonging to the player or an ally are saved, but retreated enemy units are not. While the owner's units and allied units are grouped with other survivors, the retreated enemy units need to be separated because they should not be available for salvage. I've created a "retreated" section for them.
