### ISSUE TITLE
Tooltip colors still not quite right for firing vectors

### ISSUE THREAD

**Issue by ralterd** [MegaMek/megamek#442]
Issue #437 seems to have mostly worked to have contrasting font and background colors, but still have light font on light background during firing phase when hovering over some previously selected firing selection vectors in newly released megamek-0.41.28

![tooltip-colors-still-not-quite-right](https://cloud.githubusercontent.com/assets/24481390/21299473/01859800-c56a-11e6-9dee-5c3c980c6e9a.png)

Two lines of "Large Laser; needs 5" are in white, with pink background in the above screenshot.

System information:

megamek-0.41.28

Ubuntu 16.04 LTS

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

**Comment by arlith** [comment]
Same fix as in #437, I just missed two tables.
