### ISSUE TITLE
issue with escape key reset when jumping 

### ISSUE THREAD

**Issue by kuronekochomusuke** [MegaMek/megamek#4422]
MegaMek v0.49.13-SNAPSHOT
	Build Date: N/A
	Today: 2023-05-12
	Origin Project: MegaMek
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 11 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 8 GB

looks like something has stepped on clearing movement with the Escape key in the nightly build.   it is switching the movement mode partially back to walk, but  leaving the possible jump location ring active.

in 0.49.12 hitting the Escape key leaves you in jump mode.

select a jump location 
![image](https://github.com/MegaMek/megamek/assets/116095479/3b0408e5-52e6-4e5f-bb00-0ba004604e1d)
then hit escape and select a location again
![image](https://github.com/MegaMek/megamek/assets/116095479/d80fa990-0cd1-4390-b48b-df1e248ad6a9)

**Comment by pakfront** [comment]
Possibly related to some changes I made, and I've been in this code recently anyway, so I can take a look.

**Comment by kuronekochomusuke** [comment]
it looks like doPSRCheck has side effects, that may be causing it.  commenting it out and the issue goes away.

```
    protected void updateDonePanel() {
        if (cmd == null || cmd.length() == 0) {
            updateDonePanelButtons( Messages.getString("MovementDisplay.Move"), Messages.getString("MovementDisplay.Skip"), false);
        } else {
            boolean psrCheck = // (!SharedUtility.doPSRCheck(cmd).isBlank())
                   // ||
             (!SharedUtility.doThrustCheck(cmd, clientgui.getClient()).isBlank());
            boolean damageCheck = cmd.shouldMechanicalJumpCauseFallDamage()
                    || cmd.hasActiveMASC()
                    || (!(ce() instanceof VTOL) && cmd.hasActiveSupercharger())
                    || cmd.willCrushBuildings();

            String moveMsg =  Messages.getString("MovementDisplay.Move")
                    + (psrCheck ? "*" : "")
                    + (damageCheck ? " !" : "");
            updateDonePanelButtons(moveMsg, Messages.getString("MovementDisplay.Skip"), true);
        }
    }
```
