### ISSUE TITLE
Client dies during the fire phase

### ISSUE THREAD

**Issue by crazys1** [MegaMek/megamek#444]
Version: v0.41.28

I am attempting to play an AtB battle, and the client keeps dying during the fire phase. If I load the autosave (which is from the movement phase of the same turn) and try again, the client dies again in the fire phase.

If I replace myself with a bot, then the bot is able to proceed. The client only seems to die on a player's turn.

I have experienced the client dying three times now with this latest MegaMek version. The previous two times, I was able to continue after forcing MegaMek to close using the task manager and loading the saved game. However, in the attached save, even after loading the game, the client still dies.

[megameklog.txt](https://github.com/MegaMek/megamek/files/665129/megameklog.txt)
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/665134/autosave.sav.gz)

**Comment by crazys1** [comment]
I tried a game with a friend against the bot, and the game crashed then, too. Unfortunately, I didn't save the log file. However, I narrowed down the cause to being the next valid target (and maybe previous valid target) feature in the fire phase. When I used only the next target feature, I did not encounter any crashes.

**Comment by arlith** [comment]
There's got to be an exception in the log then.  I don't see one in your first log file, so it would be super helpful if you could get a logfile with the exception in it.

**Comment by neoancient** [comment]
If you started it from MekHQ, it will be in the mekhqlog.txt file.

**Comment by crazys1** [comment]
I just did a battle from MegaMek (only; no MekHQ), and got the crash in the 3rd fire phase. I attached the megameklog file. I don't see any exception in it, though.

[megameklog.txt](https://github.com/MegaMek/megamek/files/668148/megameklog.txt)

After the crash, I loaded the autosave, and I was able to proceed without any further issues with the "next valid target" feature.. So, as per my original comments, sometimes loading the game after a crash works, and sometimes the game will continually crash at the same spot when using "next valid target."

You should be able to reproduce this bug fairly easily.

1. Start a game.
2. Give yourself one or more units.
3. Add a bot.
4. Give the bot multiple units (it might work with just one; I'm not sure).
5. Play the game, and always use "next valid target" or "previous valid target" to select your target. For good measure, try cycling through all possible targets before you finally choose one at which to shoot. The client should die within a few turns of cycling through the targets.

**Comment by neoancient** [comment]
For me the client stops responding. It gets stuck in a loop in `FiringDisplay`, lines 1090-1119 when there is a visible target which is impossible to hit. There's a lot of MM code that is still unfamiliar to me and I'm reluctant to mess with it, but it appears to me that either keeping a count of units that were checked or checking whether the index is back to the starting position should fix it.
