### ISSUE TITLE
issue on movement phase, unit display and done button are not displaying correcrtly

### ISSUE THREAD

**Issue by kuronekochomusuke** [MegaMek/megamek#4444]
Starting MegaMek v0.49.13-SNAPSHOT
	Build Date: N/A
	Today: 2023-05-20
	Origin Project: MegaMek
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 11 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 8 GB

I have been getting this issue on the movement phase, the unit display and done button are not displaying correctly.

if i hide the unit display, it shows correctly once i show the unit display again.   also works fine if I reload the autosave. 

this seems to be something with html text in a label, it happening to the summary tab, sensor info on extra tab, and done buttons.  all these use html text

![image](https://github.com/MegaMek/megamek/assets/116095479/9385c355-1b97-48ea-a527-4df1ec90bcf7)
![image](https://github.com/MegaMek/megamek/assets/116095479/f13e349f-dfe3-406c-91ec-8a6d5bca4958)

[megamek.log](https://github.com/MegaMek/megamek/files/11522439/megamek.log)

**Comment by HammerGS** [comment]
I was going to be working on 49.13 this weekend. Would you consider this a blocker for release?

**Comment by kuronekochomusuke** [comment]
it is annoying, but you can work around it.  think i may have gotten it with 0.49.12 also.

**Comment by HoneySkull** [comment]
As a note for replicating this issue - set the skin to "plainSkin.xml".   I haven't been able to replicate in other skin settings.
