### ISSUE TITLE
OSX Versions don't work

### ISSUE THREAD

**Issue by r4dian** [MegaMek/megamek#445]
Steps to Reproduce:
---

- Download v0.41.28 (v0.42.0 RC2) 
- Extract the archive
- Run the .app
- Click _Start New Game..._, enter a name and click _okay_

Result
---

The following error is shown, although this file does exist in the given location

```sh
Could not initialise:
java.io.FileNotFoundException: data/images/units/mechset.txt (No such file or directory)
```

This also occurs in at least the previous two releases (0.42.0 RC1 and 0.41.26)

Expected
---

Game continues to set up screen.

System Info
---

MacOS version `10.12.1`
Java version: 
```sh
$ java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```

**Comment by Dylan-M** [comment]
There are known issues with the OSX versions. Blame Apple for deciding to mess everything up when they dropped Java after 6. Anyway, you can work around this by using the Linux version.

**Comment by Alarantalara** [comment]
As I recall, I was able to get it to run successfully by opening Terminal, navigating to the containing folder and running the app in the Terminal from there.
e.g.
`java -jar MekHQ.app/Contents/Resources/Java/MekHQ.jar` for MekHQ and similar for the other apps.

It seems very likely that the download places the files in one place, while the working directory when opening the app from the Finder is different, thus causing files to not be found.

i.e. This is a packaging problem and there is nothing intrinsically wrong with the build.

**Comment by Dylan-M** [comment]
@Alarantalara Yes, this is all known to me. But that doesn't make it at all easy to _fix_, sadly.  What is weird is that it works on some versions of OSX, but not at all on others.

**Comment by Dylan-M** [comment]
Changed to wontfix due to this being an a Apple security issue. You'll have to follow the following wiki entry.

https://github.com/MegaMek/megamek/wiki/OSX-Permissions
