### ISSUE TITLE
Skipped Last Unit in Firing Phase

### ISSUE THREAD

**Issue by Membooo** [MegaMek/megamek#4457]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
What version of MegaMek does your issue apply to?  Note whether it is the stand alone MegaMek or HQ's MegaMek.
What operating system are you using?  Windows, Mac, or Linux?
What java version are you using?  If unsure, it will state your java version at the top of the megamek.log file.
(Delete the above lines)

HQ´s MegaMek 0.49.13 
	Origin Project: MegaMek
	Java Vendor: Eclipse Adoptium
	Java Version: 11.0.15
	Platform: Windows 11 10.0 (amd64)
	System Locale: de_DE
	Total memory available to MegaMek: 4 GB

[autosave.sav.gz](https://github.com/MegaMek/megamek/files/11575141/autosave.sav.gz)
[megamek CLIENT MEMO.log](https://github.com/MegaMek/megamek/files/11575142/megamek.CLIENT.MEMO.log)
[megamek DEDICATED SERVER.log](https://github.com/MegaMek/megamek/files/11575143/megamek.DEDICATED.SERVER.log)

### Description
Skipped last Unit in firing Phase! Firing Phase ended, before last Mech declared his shot!

### Files
[megamek CLIENT MEMO.log](https://github.com/MegaMek/megamek/files/11575137/megamek.CLIENT.MEMO.log)
[megamek DEDICATED SERVER.log](https://github.com/MegaMek/megamek/files/11575138/megamek.DEDICATED.SERVER.log)
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/11575139/autosave.sav.gz)

**Comment by kuronekochomusuke** [comment]
#3304

**Comment by PhoenixHeart512** [comment]
Save file attached that replicates the issue for me 100% of the time.

Unzip this whole folder on top of an existing MHQ installation. The folder structure is matched to the MHQ directory, so all subfolders should get placed in the correct locations all at once as long as the root folder is correctly lined up. Overwrite any file conflicts that pop up.

There will be 2 Cardinals still left to fire. 

Use Cardinal ID:106 and fire both LRM15's at the enemy Lineholder ID:127. (north-east adjacent hex)

If it works, the second cardinal should get skipped.

The zip file includes:
1. save game named "atb1" which is in the state described above
2. All of the autosaves from today (I have paranoid autosave enabled)
3. Megamek.log (though there wasn't diddly squat in there)
4. mmconf contents, preferences, l4j.ini's (8MB memory for MM and MHQ, 4MB for MML)
5. My full MHQ campaign save (including all mechfiles, mmconf, gameoptions, portraits, camo, custom " - heavy" scenariodefinitions, and force icons just to make sure it matches 100%.)

File size too large to attach directly, so this is a link to the upload on my google drive: https://drive.google.com/file/d/175Fs_wKKJTEcanteyX5d4U3nkP8q2KDn/view?usp=sharing
