### ISSUE TITLE
Errata : Semi-Guided LRM Clarification

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#4459]
Recently there was a discussion on Discord around SG LRM's using IDF and terrain. As of this issue I'm not sure what MegaMek is going but opening an issue not to lose the clarification. 

This was the example provided:

A mech attacks a designated target indirectly with SG LRMs.  The target has been successfully TAG'd this turn but the tagging unit is  designating the target through two light woods.  

- The unit firing the SG LRM's indirectly would NOT get a penalty from terrain. 
- The tagging unit would need to tag the unit with full terrain penalties (and any others as applicable). 

In this case. 

The SG LRM's ignores all terrain in its way.  The spotter designated the target through two light woods that would be a +2 terrain modifier.

**Comment by ShadowDragon8685** [comment]
Ah, I'm sorry, that was me.
The version we were using and having this issue with is **49.12**.

Noteworthily, .48 does _not_ have this issue; SAG LRMs engaging a TAGged target _did not care_ about visibility-affecting terrain intervening between the TAGger and the target.
