### ISSUE TITLE
[49.13] Lag with High Quality Graphics active

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#4462]
A number of players have observed severe lag with the High Quality Graphics option active (including one pre-release tester, which is why there is a toggle at all). We have not yet managed to isolate the cause of the issue. It does not appear to occur for every user, and really shouldn't be happening at all; the calculations required for the option are not difficult for any modern graphics processor.

If you experience improved performance with the HQG toggle off, please post a comment with as many details on the software and hardware of the system as you are comfortable sharing, in the hopes of us finding some common denominator. Examples: OS version, Java version, CPU used, GPU used, graphics driver type and version, antivirus software, UI scaling/monitor resolution, etc.

**Comment by XT-19** [comment]
Got this informatin form dxdiag

------------------
System Information
------------------
Time of this report: 5/27/2023, 20:35:41
Operating System: Windows 11 Home 64-bit (10.0, Build 22621) (22621.ni_release.220506-1250)
Language: German (Regional Setting: German)
System Manufacturer: MEDION
System Model: BEAST X30
Processor: 12th Gen Intel(R) Core(TM) i7-12700H (20 CPUs), ~2.3GHz
Memory: 32768MB RAM
Available OS Memory: 32508MB RAM
DirectX Version: DirectX 12
User DPI Setting: 168 DPI (175 percent)
System DPI Setting: 144 DPI (150 percent)
DirectX Database Version: 1.4.6
DxDiag Version: 10.00.22621.0001 64bit Unicode
           
---------------
Display Devices
---------------

Card name: NVIDIA GeForce RTX 3070 Ti Laptop GPU
Manufacturer: NVIDIA
Chip type: NVIDIA GeForce RTX 3070 Ti Laptop GPU
DAC type: Integrated RAMDAC
Display Memory: 24286 MB
Dedicated Memory: 8032 MB
Shared Memory: 16254 MB

For Antivirus I only use the default windows firewall and Microsoft Defender.


If you need anything more feel free to ping me.

**Comment by Thom293** [comment]
Ok - so I experienced this during testing.  I tested it on 3 different computers all with windows 10 Professional.  A brand new computer 1 month old, a year old laptop with a 16gb 3090 and a 7 year old desktop that had a 12gb 3080 upgrade.  ALL of them were hit by this.  I tested and isolated all I could think of and could isolate nothing that was the cause.  The only things I can think of that I did not specifically control for is screen refresh rate and antivirus. 

My screen refresh is 60hz at 3840x2160 on a TV (but it also happened on laptop screen).  I have Webroot antivirus and windows defender.  I guess I also have forticlient on my system for a VPN for work.  I have no screen recording software.

If you have other ideas of what the possible cause could be, please post so we can hopefully figure it out.

Here is my new system.

![image](https://github.com/MegaMek/megamek/assets/23645569/e57ef507-c070-4b9c-b301-bdb51409fe6f)

![image](https://github.com/MegaMek/megamek/assets/23645569/d950c0b3-8ba9-4037-85cf-c9bd949d1718)

![image](https://github.com/MegaMek/megamek/assets/23645569/b8a88ea6-b0d7-4502-8aca-adf2254ecad2)

**Comment by gsparks3** [comment]
Hmm. Thom, for your testing, what was your Display Scaling under Display Settings? Both on the big display and laptop screen.

**Comment by Thom293** [comment]
Scale is 175% on the TV and 200% on the laptop.  The old desktop isnt hooked up right now but it was 175% too I think.

![image](https://github.com/MegaMek/megamek/assets/23645569/5dec1a7a-4890-42a4-a2e5-282a3b5998fc)

**Comment by gsparks3** [comment]
XT's system details also noted a DPI scaling of over 100%. I wonder if this is the key? We've had some previous issues that also depended heavily on that UI Scaling variable ...

**Comment by Thom293** [comment]
could be.  Mind editing their OP to ask for DPI?  That sounds the most plausible honestly.

**Comment by manstrokemole** [comment]
Hi all, I've had the same issue and it was solved by unticking the High Quality graphics.

My DPI scaling is at 125%

![Screenshot 2023-06-01 121954](https://github.com/MegaMek/megamek/assets/84518328/61828850-99a5-4f58-b5ec-1efffdd2fdc4)
![Screenshot 2023-06-01 122105](https://github.com/MegaMek/megamek/assets/84518328/c90d5772-4fe0-47f6-94d1-fcdaf9d04c3c)
![Screenshot 2023-06-01 122123](https://github.com/MegaMek/megamek/assets/84518328/ecfec9d6-9d28-4fae-8241-86c2ba47e341)

Let me know if you need any more info, you may have to explain it in simple terms as I'm a bit of a luddite!

**Comment by SJuliez** [comment]
Scaling is the key. Somehow, java's internal bicubic interpolation and windows' scaling other than 100% don't like each other.

**Comment by SJuliez** [comment]
Thanks all for researching that. I wouldn't have thought of windows scaling anytime soon.
