### ISSUE TITLE
[0.49.13] Lag when using large craft and TacOps Sensor Rules

### ISSUE THREAD

**Issue by stonewall072** [MegaMek/megamek#4467]
0.49.13
Windows 11
Java 11

When using large craft such as WarShips and DropShips with the TacOps Sensors rule enabled the program experiences significant lag and delays responding to input. I originally thought only the space map was affected, but additional testing this morning presented issues on the low altitude and ground maps as well. Toggling this rule off returns to the program to expected behavior. On the ground map, the lag seems to only persist through the initial deployment phase, but afterwards the program continues to run normally. On space and low altitude maps the lag continues through all following phases and turns.

This does not seem to be directly related to #4462, as this problem exists whether High Quality Graphics are on or off.

**Comment by kuronekochomusuke** [comment]
do you have a save for this where it is reproducible?  

it is probably related to the visual/sensor display, with a unit with a really long sensor range.

**Comment by stonewall072** [comment]
I can provide a save file, though it should be easily reproducible by setting that rule and deploying any DropShip or WarShip onto a space map. 
[LagTest.sav.gz](https://github.com/MegaMek/megamek/files/11593879/LagTest.sav.gz)
