### ISSUE TITLE
[0.49.13] GUI Readability issues with button height and naming concerns during firing phase "Fire" button

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megamek#4473]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
0.49.13

### Description
Current GUI has readability issues:

1. buttons too tall and wasting space, maybe make an option to toggle or adjust button height
2. "commit action" button is too close and difficult to visually distinguish between the other buttons (the button that ends movement/firing/etc and commits the actions for that unit)
3. the Firing Phase "commit action" button has the same name as the button that selects individual weapons to be fired at a target (both are named "fire")

Since I prefer to offer suggestions when reporting a problem instead of just saying what's wrong, here are my proposed fixes or adjustments:
1. Add checkbox in Client Settings for short/tall buttons (or a text entry box for height in pixels, etc)
2. Screenshots below, easier shown than described, but basically: 
      a. use the two BIG confirm buttons side by side next to short-height regular buttons (differing button sizes helps readability). That way you don't have empty space with two big buttons stacked on top of each other while using shorter regular buttons (and 2 rows is enough, IMO, does not need to be 3/4 rows of short height buttons)
      b. For big regular buttons, add a blank space between them and the big commit buttons to make a clearer distinction between "buttons to do things" and "this button will end your turn if you click it"
3. Rename the "commit action" button back to "done" or something that indicates "I've made my selections and am done with this unit's turn"

Short buttons combined with tall "commit action" buttons suggestion:
![Short With 2 Big Confirm Buttons](https://github.com/MegaMek/megamek/assets/101755917/799ab35b-bfb6-4740-bf38-a87afd42430a)

Tall buttons for all, but with added empty space separating the types:
![Tall Buttons With Spacing](https://github.com/MegaMek/megamek/assets/101755917/91f352be-9306-4df5-b02b-6852a5db4175)

**Comment by Thom293** [comment]
I'm out of town for a week and don't have a computer, so I'll will tack on here:

if you have a fallen mech, you can't just hit "get up" and then click move. It's grayed out. You have to get up and move or it stays Grey unless you do random clicking. Stated another way:  if you get up but don't leave your hex, the move button is grayed out.

**Comment by manstrokemole** [comment]
As an addition, changing the "Done" button to "Fire", leads to the odd situation where if you twist a torso, the skip firing button becomes greyed out, so you have to click "Fire" to end that unit's turn, even though it hasn't fired.

**Comment by pakfront** [comment]
> if you have a fallen mech, you can't just hit "get up" and then click move.
> As an addition, changing the "Done" button to "Fire", leads to the odd situation where if you twist a torso ...

Both these are unrelated to the UI layout issues and will be covered in another issue and bug fix.
