### ISSUE TITLE
Some Unicode Characters Improperly Displayed On AS Cards

### ISSUE THREAD

**Issue by pokefan548** [MegaMek/megamek#4475]
### Environment
MegaMek 0.9.12 Snapshot

### Description
Some Unicode characters depicting non-English letters or unusual diacritic combinations do not print correctly on Alpha Strike cards specifically.

### Files
![image](https://github.com/MegaMek/megamek/assets/36405715/1a81acb6-5912-4060-bf94-b80b068a685c)

**Comment by SJuliez** [comment]
Both are the icelandic eth, the capital letter on the as card. Http://en.m.wikipedia.org/wiki/Icelandic_orthography

**Comment by Thom293** [comment]
Isn't this the character that caused the vehicle bug?

**Comment by pokefan548** [comment]
After further research, the capitalized character is actually correct. Sincerest apologies.

**Comment by pokefan548** [comment]
After further research, the capitalized character is actually correct. Sincerest apologies.
