### ISSUE TITLE
Done and Skip Turn buttons do not accurately reflect command state.

### ISSUE THREAD

**Issue by pakfront** [MegaMek/megamek#4479]
### Environment
0.49.13

### Description
if you have a fallen mech, you can't just hit "get up" and then click move. It's grayed out. You have to get up and move or it stays Grey unless you do random clicking. Stated another way: if you get up but don't leave your hex, the move button is grayed out.

As an addition, changing the "Done" button to "Fire", leads to the odd situation where if you twist a torso, the skip firing button becomes greyed out, so you have to click "Fire" to end that unit's turn, even though it hasn't fired.

Note: this is currently using the exact same logic that the nag screen used, but clearly this is not correct.

**Comment by SimonLandmine** [comment]
Additionally, if you turn on the spot using keyboard commands, it does not recognise that as a Move, so the 'Skip Movement' button remains highlighted rather than the 'Move' button. This is probably a linked issue, which is why I'm raising in this bug.
