### ISSUE TITLE
Sort Units in Lobby by Name/BV/Tonnage/etc...

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#448]
http://bg.battletech.com/forums/index.php?topic=55804.msg1283982#msg1283982

Yer really killing me Smalls. You and Hammer both asked for ideas on the first page of the thread. 

Anyways, pretty self explanatory, the ability to sort units in the lobby view panel by Type/BV/Tonnage/Name.

**Comment by Dylan-M** [comment]
Actually, we asked what you'd like to see to get an idea of what interests the community. Things still need a report to get worked on 😝
