### ISSUE TITLE
Incorrect availability ratings for Clan electronic warfare equipment

### ISSUE THREAD

**Issue by Saklad5** [MegaMek/megamek#4481]
### Environment
MegaMek Version: MekHQ v0.49.13 Development Snapshot
Operating System: Mac
Java Version: 20.0.1

### Description

Various pieces of electronic warfare equipment are currently classified as more exotic than they actually are, especially in the Dark Age era.

All references for the following may be found on page 34 of the third printing of _Interstellar Operations: Alternate Eras_.

|Item|Current (Incorrect)|Actual (Correct)|
|:--|:-:|:-:|
|Active Probe (Clan)|X-X-E-D|X-E-D-C|
|Watchdog CEWS|X-X-F*-F|X-X-F-E|
|Light Active Probe (Clan)|X-X-F-E|X-X-E-D|
|ECM Suite (Clan)|X-X-E-D|X-E-D-C|

**Comment by HammerGS** [comment]
Checking in the misctype these are set correctly. No idea why they are showing wrong in MML

**Comment by Saklad5** [comment]
Can you reproduce it?

**Comment by HammerGS** [comment]
Yep, I can see it in MML, but the code matches the correct version.

**Comment by Saklad5** [comment]
> Yep, I can see it in MML, but the code matches the correct version.

Is it possible the rules for Inner Sphere factions trying to acquire Clan technology are getting applied somehow? That'd result in the discrepancy.

**Comment by HammerGS** [comment]
Got a fix pending that looks like it resolves it. 

![image](https://github.com/MegaMek/megamek/assets/13752452/3992e559-ce6a-42a2-9f87-1e3bd3c892f3)

**Comment by Saklad5** [comment]
What was the issue, precisely? Hard to tell from the commit.

**Comment by HammerGS** [comment]
From what I could see it was using a wrong flag. Once I cleaned that up things started reporting correctly.
