### ISSUE TITLE
Typo in name_change.txt

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#4483]
Having a quick check looking for something else, saw this in ...\data\mechfiles\name_changes.txt in the 49.12 files:

Sprite Ultraheavy ProtoMech|(Standard) Sprite (Standard)

As I understand the syntax, the separator bar is misplaced, and it should look like this:

Sprite Ultraheavy ProtoMech (Standard)|Sprite (Standard)

Link: https://github.com/MegaMek/megamek/blob/4cc763dc83ffacd1af9a0b8c928390d855aadddb/megamek/data/mechfiles/name_changes.txt#LL711C1-L711C57

**Comment by HammerGS** [comment]
Fixed
