### ISSUE TITLE
Incorrect tech base for Naval Tug Adaptor

### ISSUE THREAD

**Issue by Saklad5** [MegaMek/megamek#4485]
### Environment
MegaMek Version: MekHQ v0.49.13 Development Snapshot
Operating System: Mac
Java Version: 20.0.1

### Description
The Naval Tug Adaptor, found on page 147 of the sixth printing of _Tactical Operations: Advanced Units & Equipment_, is currently marked as IS-only. It's actually supposed to be available to both tech bases.

**Comment by HammerGS** [comment]
Fixed as part of - https://github.com/MegaMek/megamek/commit/9f48d87f630b53d3d7c3820a795a2264914f63b5
