### ISSUE TITLE
RFE: Add Standard Modular Weapon Mount

### ISSUE THREAD

**Issue by Saklad5** [MegaMek/megamek#4508]
The standard Modular Weapon Mount, found on page 262 of the sixth printing of _TechManual_, is currently missing from the MegaMek suite entirely. This is problematic, as *many* battle armor designs utilize it, including the classic Elemental.

While a fully-fledged implementation that allows for swapping manipulators like ammunition might be difficult, it should be trivial to follow the same approach used for the Modular Equipment Adaptor: simply add a 10kg 1-slot piece of equipment, without any specific functionality, then add it to the appropriate designs. This won't affect gameplay, but it will reserve the slot and weight for the mount, and it'll make the record sheets more accurate.

**Comment by Saklad5** [comment]
Duplicate of MegaMek/megameklab#911.

**Comment by NickAragua** [comment]
Closed as duplicate.
