### ISSUE TITLE
[49.12] Hex not in sensor range tooltip renders "Hex notin sensor range."

### ISSUE THREAD

**Issue by ShadowDragon8685** [MegaMek/megamek#4518]
### Environment
MegaMek 49.12; Windows 10; Java 11.

### Description
The tooltip for a hex which is not in sensor range is missing the space between "not" and "in", thus rendering "Hex notin sensor range."

![Hex_is_notin_sensor_range](https://github.com/MegaMek/megamek/assets/3993090/83c053d3-2bbd-4089-ada5-1f5b55b3adf7)

**Comment by jauby** [comment]
Verified this is fixed in the latest snapshot
![sns](https://github.com/MegaMek/megamek/assets/134733938/2c204ad4-c236-4409-bde0-3600183786e0)
