### ISSUE TITLE
Feature Request: Single Blind

### ISSUE THREAD

**Issue by mnmib1** [MegaMek/megamek#452]
Single blind.  Another old request of mine from SF.  Since the bot can't function with double blind, but the double blind rules are in there,  use single blind.  The same rules, but they only apply to the player.  This would make the bot a bit more challenging, and I would not think it would be too hard to implement since the rules are in place, they just need to be applied to the human player only.

**Comment by BLOODWOLF333** [comment]
Duplicate https://github.com/MegaMek/megamek/issues/203
