### ISSUE TITLE
Princess never uses other weapons if TAG pod is loaded or present on aircraft

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#4520]
If Princess is given control of a fighter, conventional or aerospace, that is equipped with TAG it will only use TAG and never make any other attacks.  Aircraft using TAG cannot make weapon attacks, so there should be some kind of decision making between the TAG and it's other weapons.

Under ideal circumstances, Princess would take into account incoming precision weapons (e.g. homing Arrow IV artillery) and LRM-armed ground units within a certain range of the TAG'd target when deciding whether to use TAG on a target or make a standard weapon attack (e.g. no friendly LRMs within 14 hexes for indirect fire, don't bother with the TAG).

Attached 49.12 save game for demonstration and testing:
[Princess_air_TAG.sav.gz](https://github.com/MegaMek/megamek/files/11717907/Princess_air_TAG.sav.gz)

The Thunderbird for Unknown Hostiles has a TAG pod, weapons (obviously) and several air-launched Arrow IV.  It will never use anything but the TAG despite mothing to take advantage of .

**Comment by Sleet01** [comment]
I'm in this code right now, looking at the internal bomb bay implementation.  I'll see if I can tease this one out as well.

**Comment by Sleet01** [comment]
Finally have time to look at this.

My initial supposition is that Princess doesn't actually know anything about TAG specifically, and just processes it as a normal energy weapon when prompted during the Indirect phase.  Unfortunately this would disqualify TAG-carrying Aerospace units from firing any other weapons later in the turn, as Aeros can _either_ TAG _or_ fire other weapons, but not both.  An initial cursory examination of the code seems to support this view.

I think the best approach is to give Aero TAGs a strong disutility unless A) incoming / on-board guided  (or indirect-fire) weapon damage could exceed the unit's own; or B) the unit is out of ammo, weapons, and/or bombs/munitions.

If there are other instances where we might want Princess to prioritize tagging a valid target over using a unit's other weapons, please let me know.

**Comment by HammerGS** [comment]
I agree with the logic on this.
