### ISSUE TITLE
Physical attacks : may select friendly unit as melee target even when friendly fire is off

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#454]
If you have a friendly vehicle in the same hex as a enemy mech, you get a drop down list to select which to target. The problem is that the list seems to default to the friendly vehicle (not sure how this is determined, alphabetical order maybe?), even when friendly fire is off.

You can select the friendly vehicle as the target of a melee attack, but megamek wont allow you to actually perform any melee attacks on it. With friendly fire off, when you click on a hex with an enemy mech and a friendly vehicle, megamek should automatically target the enemy mech as the friendly vehicle is an invalid target anyway.

With friendly fire on, the drop down list should default to the enemy mech instead of the friendly vehicle (as it is the more likely target).

[comguards.sav.gz](https://github.com/MegaMek/megamek/files/674222/comguards.sav.gz)
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/674223/mekhqlog.txt)

If you want a save with an enemy mech and a friendly vehicle in the same hex within melee range, try the above save.

**Comment by Dylan-M** [comment]
I've seen this behavior as well, and the order is based on who entered the hex when. It's a minor annoyance, but should also be a relatively easy thing to fix.

**Comment by arlith** [comment]
I made it so the choices for the dialog will adhere to the friendly fire option (ie, friendly units won't be added if friendly fire is not on).  I also added a comparator that sorts the units based on whether they are enemies or not, so enemy units always appear first.
