### ISSUE TITLE
[49.14 - SNAPSHOT] Post Physical Attack Report IllegalStateException 

### ISSUE THREAD

**Issue by ArneHD** [MegaMek/megamek#4548]
### Environment
MegaMek 0.49-14 - SNAPSHOT (17-06-2023), lightly modded, modded files and mechfiles in attached zip
Origin Project: MekHQ
Platform: Windows 10 10.0 (amd64)
Java Vendor: Eclipse Adoptium
Java Version: 11.0.19

### Description
Either when or after resolving the physical attack report on Round 5 the game gives an IllegalStateException error and will not proceed further in the game, though the game itself does not appear to crash, client settings and other non-game related functions appear to work.

Have run battle twice and both times the Scorpion battlemech will report "Crew Dead" despite A.) The Pilot being alive and B.) "Crew dead" not being a condition that a 'mech can be in.

Issue appears to be related to the Scorpion Battlemech, in games in which the Scorpion dies quickly the bug does not occur.

### Files
[battletech bug report.zip](https://github.com/MegaMek/megamek/files/11816452/battletech.bug.report.zip)

**Comment by kuronekochomusuke** [comment]
are you using the latest nightly?

**Comment by ArneHD** [comment]
> are you using the latest nightly?

No, I'm using an earlier one from the 17th of June, has this problem been fixed in the latest nightly? I could update and test again if that would give more information.

**Comment by kuronekochomusuke** [comment]
there was a fix merged on the 18th.  #4528  #4523

see if that fixes it, the fix was for the case when an ejected pilot is picked up

**Comment by ArneHD** [comment]
> 

I tried it and I got another bug; it appears to be an entity that "does not know its position".
[logs.zip](https://github.com/MegaMek/megamek/files/11835494/logs.zip)
