### ISSUE TITLE
Princess hangs indefenitely if Zero legal deployment hexes. 

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#455]
This probably falls under the "no shit" kind of situation. 

I rolled up a random game where I gave princess a wheeled tank (a demon) and the random map generated was 100% covered by woods, no clear spaces at all. Princess just sat there chewing on it (as expected when I saw the map).

Under these circumstances (ie princess unable to deploy all of her units), the game should return to the lobby or put up a prompt asking the player if they wish to return to the lobby. If a prompt is used, it should explain to the player in the pop-up what happened.

**Comment by arlith** [comment]
This should be fixed in PR #640.  Code was added to remove the entity if there are no legal deployment hexes found.
