### ISSUE TITLE
Princess should not deploy units underwater that cannot survive there

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#4550]
From a 49.12 game:

End Phase
-------------------
*** Lumberjack LM4/C (Lyran Commonwealth Convoy) DESTROYED by being in water without environmental shielding! ***

IndustrialMech without sealing was deployed in depth 3 water when there was dry land available.

**Comment by pheonixstorm** [comment]
This type of deployment bug should be weeded out by isLocationProhibited(), or at least it is for other unit types.

**Comment by SuperStucco** [comment]
Might be a relevant point - double blind and sensor contact optional rules are in play.  There's some issues with overlapping deployment zones and stacking violations, so it might also apply to this e.g. it might be bypassing that method altogether.
