### ISSUE TITLE
0.49.13 offboard artillery Disengage causes uncaught nullpointer exception

### ISSUE THREAD

**Issue by TiresomeCube34** [MegaMek/megamek#4553]
Ver. 0.49.13, MekHQ campaign MegaMek
Windows 10
JAVA 20.0.1

Disengaging any of my off-board artillery causes a null pointer exception.

Load save file for Irregular forces scenario. replace players with AI. disengage any arty and then finish the arty phase. ending of arty phase should trigger bug.

Is Replicable without loading the game through the mekHQ save. 

Player name: Golden Kashicks
[Arty Disengage Bug.zip](https://github.com/MegaMek/megamek/files/11840825/Arty.Disengage.Bug.zip)

**Comment by HammerGS** [comment]
We don't support Java 20, and have only just implemented some support for Java 17.  Downgrade to Java 11 or 17 and see if the error persists.

**Comment by TiresomeCube34** [comment]
Bug persists with JAVA 17.0.7

new logs included
[megamek.log](https://github.com/MegaMek/megamek/files/11841086/megamek.log)

**Comment by kuronekochomusuke** [comment]
are you running a mission from mekhq?  if so can you post the also mekhq.log some times the error ends up in there.
