### ISSUE TITLE
Null pointer error when attempting to fire heavy flamer

### ISSUE THREAD

**Issue by Rmn003** [MegaMek/megamek#4554]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
MekHQ Megamek Version 49.13
Windows 10
Unsure

### Description
Null pointer error when attempting to fire heavy flamer.

### Files

(Delete the above lines)
[SchrekFlamer.sav.gz](https://github.com/MegaMek/megamek/files/11842018/SchrekFlamer.sav.gz)

**Comment by HammerGS** [comment]
We also need logs.

**Comment by Rmn003** [comment]
I'll try to find them.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Rmn003** [comment]
[megamek.log](https://github.com/MegaMek/megamek/files/11847189/megamek.log)

**Comment by neoancient** [comment]
The Schrek has no ammo for the heavy flamers. You should not have been able to give a fire order.

**Comment by Rmn003** [comment]
> 

The Heavy Flamer is an energy weapon.

**Comment by gsparks3** [comment]
It's an energy weapon that requires ammunition; see the sourcebooks (most recently Tactical Operations: Advanced Units and Equipment).

**Comment by neoancient** [comment]
I'm going to close this as the illegal state results from an illegal unit, and it's unlikely that we'll be able to figure out how it got into that state with the information here.
