### ISSUE TITLE
Cannot cancel hotloading of LRMs during battle

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#456]
Tested this with standard LRM carriers. If you set an ammo bin to hotload, you cannot cancel the hotloading. You get a weird message where it will say that "ammo will switch to at end of turn" (see screenshot), but next turn the ammo bin will still be hot loaded.

If you attempt to switch the ammo bin to normal ammo instead of hotloaded LRMs, it will say the same thing again but the next turn the ammo bin will still be hot loaded.

![megamek](https://cloud.githubusercontent.com/assets/1191378/21576838/a88676e6-cf93-11e6-907e-a75bfdfa2c63.jpg)

[test.sav.gz](https://github.com/MegaMek/megamek/files/679541/test.sav.gz)

[megameklog.txt](https://github.com/MegaMek/megamek/files/679542/megameklog.txt)

**Comment by BLOODWOLF333** [comment]
Previously MM was allowing you switch LRMs hotloading on/off during battle which was incorrect and should only be for vehicles.  Which @arlith fixed but, your saying with vees hotloading now doesnt switch at all the next turn (take one turn to switch is correct though)?

**Comment by Question2** [comment]
@BLOODWOLF333 This ticket is regarding the bug with not being able to cancel hot loading and not being able to change hot load to normal LRMs.

**Comment by neoancient** [comment]
The mode change is also used for scheduling ammo dumps. When the mode was set to 0, the server understood it as canceling a scheduled ammo dump and took no further action. I changed it to cancel the ammo dump only if one is pending (but not in the process) and otherwise interpret it as canceling hotloading.
