### ISSUE TITLE
Hot loaded LRMs not working properly

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#457]
Last turn, i set the first two LRM bins to hot loaded LRMs. This turn, they are set to hot loaded, but there are two problems with this : 

1. They still get the minimum range modifier despite being hot loaded

2. Although i only set the first two LRM bins to hot loaded, the LRMs are marked as hot loaded even if i select the non-hot loaded LRM bins.

![megamek](https://cloud.githubusercontent.com/assets/1191378/21576944/dc7bea38-cf9a-11e6-9f37-a464f2a5cb83.jpg)

When firing, the battle report also doesnt display any indication that they are rolling 3d6 take two lowest for the cluster table, so im not sure if the hot loaded penalty is working either.

You can use the save and log file here : https://github.com/MegaMek/megamek/issues/456

**Comment by neoancient** [comment]
The problem was that the ammo being selected was not necessarily the one that was used.
