### ISSUE TITLE
Mortar turret ammo selection dropdown is empty

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#4574]
In the attached 49.12 save, there is a mortar turret.  When customizing, the ammo type dropdown is completely blank:

![Mortar turret ammo selection](https://github.com/MegaMek/megamek/assets/70451747/a4cface9-593b-42a6-badb-37ad56efd934)

The game date is 3010, so the only ammo type currently available is the standard shaped charge.  But there should still be _something_ in the dropdown as a single selectable item rather than leaving it blank.

[Mortar_turret_ammo.sav.gz](https://github.com/MegaMek/megamek/files/11910590/Mortar_turret_ammo.sav.gz)

**Comment by neoancient** [comment]
The 'Mech Mortar is extinct between 2819 and 3043, so no ammo is available. I submitted a fix that adds an option to ignore extinction dates in configuring equipment.
