### ISSUE TITLE
Aerospace AS Conversion Does Not Add PV For Extreme Range

### ISSUE THREAD

**Issue by pokefan548** [MegaMek/megamek#4575]
### Environment
0.49.12 (Personal Snapshot)

### Description
When converting an aerospace unit to Alpha Strike, Extreme Range damage does not appear to be factored into PV calculations. This is clearly visible by the 1-PV discrepancy on the Batu Prime.

**Comment by SJuliez** [comment]
That's according to the AS conversion rules, ASC p.142.
