### ISSUE TITLE
Tap on a clip to paste it in the text box.Use the edit icon to pin, add or delete clips.

### ISSUE THREAD

**Issue by Cocboi99** [MegaMek/megamek#4583]
JavaScript 11

**Comment by Cocboi99** [comment]
> JavaScript 11

**Comment by pheonixstorm** [comment]
Please read https://github.com/MegaMek/megamek/wiki/Creating-an-Issue-%28Bug-Report%2C-Request-for-Enhancement%2C-Errata%29

Please do not spam tickets that amount to gibberish.
