### ISSUE TITLE
RFE - Allow units to load onto carriers controlled by allied player.

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#4592]
At present units can only be loaded (in the lobby, at least - harder to check solo in battle) onto carrier units controlled by the same player. Would it be possible to expand this to enable units to be loaded onto carrier units controlled by an allied player (e.g. if one player is controlling Elementals and other units and their ally is controlling the OmniMechs).
(I appreciate that this could cause an issue with triggering the Unload command, as that would be in the hands of the carrier-controller.)

**Comment by SJuliez** [comment]
I'm surprised. Would have sworn I spent time on this when working on the lobby overhaul.

**Comment by SimonLandmine** [comment]
Let me check again, then - I might have messed it up. Apologies in advance if so!

**Comment by SimonLandmine** [comment]
Oops, my mistake. They auto-unloaded when the carrying unit owner was changed, but yes, they can be reloaded. Sorry for wasting your time, and thanks again.

**Comment by SJuliez** [comment]
No worries :) Happy that it works
