### ISSUE TITLE
Version 41.26 Field of Fire not updated after unit move if viewed during opponents move. 

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#460]
https://files.slack.com/files-pri/T1DCN26SY-F3KL52P1P/pasted_image_at_2017_01_01_06_54_pm.png

This was pretty niche, but I checked the field of fire on my unit after moving it, during my opponent's move, and the field of fire was still from my start position instead of my final position.

**Comment by VampireSeraphin** [comment]
[firingarcupdatefail.sav.gz](https://github.com/MegaMek/megamek/files/681372/firingarcupdatefail.sav.gz)

**Comment by arlith** [comment]
The firing arc sprites weren't being cleared in `MovementDisplay.endMyTurn` like they were with `FiringDisplay` and `TargetingPhaseDisplay`.  I think this is what is causing the issue as the sprites could be drawn with stale information.  If you reselect the unit, it must draw the right arc.
