### ISSUE TITLE
Fixed-wing support vehicles with the STOL chassis modification should have the VSTOL special in Alpha Strike

### ISSUE THREAD

**Issue by pavelbraginskiy** [MegaMek/megamek#4603]
Vehicles with the STOL chassis modification, such as the Boomerang Spotter Plane, are not given the VSTOL special by MegaMek's AlphaStrike conversion:

![image](https://github.com/MegaMek/megamek/assets/29113974/1d4c1023-7056-4ff6-90d8-595488256fb4)

The unit does have the VSTOL special in the Master Unit List: 
![image](https://github.com/MegaMek/megamek/assets/29113974/9154be51-2cc8-4517-ad85-7546277779e8)

Per this ruling, the STOL chassis mod is sufficient to receive the VSTOL special: https://bg.battletech.com/forums/errata/master-unit-list-mul-feedback-thread-iv-read-the-first-post/msg1945850/#msg1945850

**Comment by pavelbraginskiy** [comment]
It should also not have ENE, per https://bg.battletech.com/forums/errata/master-unit-list-mul-feedback-thread-iv-read-the-first-post/msg1946091/#msg1946091

**Comment by SJuliez** [comment]
Correction for ENE is done; for the VSTOL thing, I will need a ruling which units get it.

**Comment by pavelbraginskiy** [comment]
>  It just needs to note VSTOL or STOL.

I think it's clear that this means the relevant passage in AS:C just needs to have "VSTOL" replaced with "VSTOL or STOL".

> An aerospace unit or fixed-wing support
vehicle unit receives this special ability if it indicates that it has
the VSTOL ***or STOL*** chassis and controls modification in its Technical
Readout entry, or if it is an aerospace fighter, Small Craft, or
DropShip unit that has the aerodyne movement code (a).

**Comment by SJuliez** [comment]
These days page 6 in https://bg.battletech.com/forums/index.php/topic,80685.150.html
