### ISSUE TITLE
Friendly bot refuses to shoot enemy bot's archer

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#461]
After an enemy archer was immobilized, my bot ally surrounded it with several vehicles with functional weapons, but all of them refused to shoot it. For the next several rounds, they just kept surrounding the archer but refused to shoot it. When the pilot woke up and tried to retreat, my bot ally kept following the archer with the vehicles, but again, refused to shoot it.

[comguards.gz](https://github.com/MegaMek/megamek/files/684365/comguards.gz)

**Comment by VampireSeraphin** [comment]
This is related to the forced withdrawal settings. Princess sometimes does not engage units which have been set to "crippled and withdrawing."

**Comment by dericpage** [comment]
This is correct.  There were several 'honor' changes made to Princess back in 0.39.2.  From the history.txt file:
+ Princess will no longer attack Crippled units when the Forced Withdrawal rule is turned on.  However, if a fleeing
    unit fires on one of her units, the controlling player is flagged as 'dishonored' and his units will become
    regular targets again.  Likewise, the Priority Targets list overrides this new behavior.
+ If Forced Withdrawal is turned on Princess's Crippled units will no longer fire as they attempt to retreat unless
    they are fired on first.  Also, firing on such a unit, will get the attacking player flagged as 'dishonored'.
+ Princess now de-prioritizes civilian units until they fire on one of her units or unless they are on the Priority
    Targets list.

**Comment by VampireSeraphin** [comment]
This can cause the game to get locked up however. If all player units are killed, thus reverting them to observer while bot allies and enemies duke it out, the bot can go into an endless loop if it cripples but does not kill the last enemy unit.

The player can exit the game, but they cannot claim victory or defeat and get their salvage mul.

**Comment by dericpage** [comment]
You can issue commands to bot allies to place units on the priority target list and override this behavior if you feel it necessary (see the Princess help doc for how to issue commands).

However, crippled should be attempting to retreat under the Forced Withdrawal rules, so will eventually escape the board.  If a crippled unit is also immobilized, the pilot/crew should end up ejecting if possible (i.e. not unconscious).

Finally, you also have the option of using the /victory command to end the scenario.

**Comment by Question2** [comment]
Well in this case, the friendly bot could have switchd targets to the other enemy units that weren't retreating, instead of getting stuck on the immobilized one...

**Comment by Xeno426** [comment]
Would honestly be interesting to add an "honor" slider to Princess to control how "dishonorable" she will act, going from "strict Zellbringen" to "pirates".

**Comment by NickAragua** [comment]
This particular behavior (where a bot's units surround a "crippled" enemy bot unit but don't fire on it) is unlikely to occur as of PR #688, which was done in early October of last year. Now they'll simply ignore it.

Note that they'll extend no such courtesy to player-owned units.
