### ISSUE TITLE
[49.13] If MegaMek is maximized, there is a tiny border on the right side

### ISSUE THREAD

**Issue by WarWolfen** [MegaMek/megamek#4616]
When MegaMek is maximized while using Darcula, there is a tiny area on the right edge of the window where the background comes through. So, the maximized window is too small. See image:

![image](https://github.com/MegaMek/megamek/assets/16292643/d634fd72-2527-4d5a-8e7d-73e80c4dc8a7)

The image needs to be viewed against a dark background in order to see the issue!

**Comment by SJuliez** [comment]
This is very likely outside our control (in other words, OS issue). Therefore closing it.
