### ISSUE TITLE
[0.49.13] [Bug/Data] SM Tank Destroyer misnamed

### ISSUE THREAD

**Issue by stonewall072** [MegaMek/megamek#4619]
According to the MUL, the base chassis is 'SM Tank Destroyer' and model names are SM1, SM1A, SM3, etc.

Currently MegaMek uses the SM1, SM1A... in both the Chassis and Model field.

**Comment by HammerGS** [comment]
I'm in the middle of significant work on unit files for the next few months. So if using our data you'll see numerous changes and tweaks. It's part of a larger project in early stages.
