### ISSUE TITLE
RFE: Add "movement type" filter to the 'Advanced Search' on Unit Selector

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#4629]
It would be useful to be able to filter vehicles by 'movement type' (i.e. wheeled/tracked/hover/etc) in the upgraded Advanced Search filter window.

**Comment by SJuliez** [comment]
You can do this in the Alpha Strike tab. But I understand it's not the most self-evident place to look for it.

**Comment by SimonLandmine** [comment]
I had a look on the Alpha Strike tab, but it looked as if the 'movement' filter on that tap was merely for selecting movement speed, rather than motive type. Now I look again, I can see there's a drop-down in front of the speed boxes in the AS 'movement' filter, but not being used to AS terminology, it still wouldn't have been immediately obvious that you could filter by motive type there.

**Comment by PhoenixHeart512** [comment]
the AS search can't further filter by weapon/equipment, and it also doesn't do Dropships (it would be nice to be able to filter between Spheroid and Aerodyne)
