### ISSUE TITLE
Megamek sometimes fails to show the * symbol to warn that movement will require a PSR

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#463]
![megamek](https://cloud.githubusercontent.com/assets/1191378/21711536/8068fef4-d443-11e6-9962-745d302bc4e5.jpg)

Basically, if you do a facing change while the movement numbers are still blue but then continue to use run/flanking movement, you still need to take a PSR (as the popup warns) but megamek fails to display the * symbol along the path to warn that you need to make a PSR.

The easiest way to test it is to just take hovers on pretty much any map, but mechs on pavement have the same issue.

[comguards.sav.gz](https://github.com/MegaMek/megamek/files/689342/comguards.sav.gz)
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/689343/mekhqlog.txt)

Try using this savegame to test if you like, unfortunately i dont have the log file anymore.

**Comment by neoancient** [comment]
The step is marked as dangerous when it's plotted. In this case it's not dangerous at that point. The code for TacOps advanced vehicle maneuvers actually reviews the entire path to mark hexes where a PSR is required, and that functionality could be expanded to include other situations like this one.

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/34809720-5f95dc9c-f65c-11e7-9bcb-1470214eca4e.png)

Now displays the * but it seems to be drawing the indicator on the hex "after" the PSR.  Better than what we had.

MegaMek 0.43.7-betaJan2
[PSRIndicator.sav.gz](https://github.com/MegaMek/megamek/files/1621324/PSRIndicator.sav.gz)

**Comment by neoancient** [comment]
That behavior is unchanged.
