### ISSUE TITLE
Guided Ammo and BV Cost

### ISSUE THREAD

**Issue by strategoslevel3** [MegaMek/megamek#4639]
0.49.13

Guided Ammo (SemiGuided LRMs/Arrow IV homing) are not following the correct rules for BV.

You should add all the BV of all guided ammo and the add that value to each unit that has TAG. (And not to the unit carrying the guided ammo - as it does now)

**Comment by HammerGS** [comment]
Related. https://github.com/MegaMek/megamek/issues/4638

**Comment by SJuliez** [comment]
Related #3385

**Comment by SJuliez** [comment]
Closing this as fixed in 0.49.14 with #4474
