### ISSUE TITLE
C3 units showing as Advanced Tech Level

### ISSUE THREAD

**Issue by strategoslevel3** [MegaMek/megamek#4640]
0.49.13

Sunder SD1-OB and other C3 units are showing as Advanced Tech and not Standard. Variable Tech Level is turned off

![IMG_4792](https://github.com/MegaMek/megamek/assets/67537490/8ad882c7-3eda-4295-b7b3-9482f631c003)
<img width="1661" alt="Screenshot_2023-07-17_at_23 29 37" src="https://github.com/MegaMek/megamek/assets/67537490/f44bbe31-a8d6-4e56-a584-3964d745408b">

**Comment by neoancient** [comment]
I'm only seeing them in IS TW non-box set. Try deleting the date/mechfiles/units.cache file. If that doesn't work, it may be an interaction with another game setting. Upload the mmconf/gameoptions.xml file.
