### ISSUE TITLE
this board works with 0.40.1, but not with 0.42.0

### ISSUE THREAD

**Issue by seem8** [MegaMek/megamek#465]
#My friend made a board, that is not working with 0.42.0. Could you help me track the problem? I was trying to delete some complex hexes, like buildings and fuel. No luck so far.

http://pastebin.com/k5jtmZi3

**Comment by BLOODWOLF333** [comment]
There have been a lot of boards with uncovered errors now either from people making buildings without defining all the required items for a building or adding terrain that doesnt exist like woods:0 or woods:4, if you look in data/images/hexes/atmospheric.tileset(or any of the tilesets) and hexes/standardincludes those files when opened with a text editor will list every terrain supported by MM and list the images used for them.  I can look at your board when i get home but, really if theres terrain in the board file that doesnt exist in the tileset then MM will not load it correctly or display the reddish mars_plains terrain in the hex when it cannot find an image.

**Comment by HammerGS** [comment]
Ran the board test against this file.  The following errors have been found.

Found Invalid Board! Board: data\boards\megamek_broken.board

Hex 1232 is invalid!
	Incomplete building!  Missing terrain(s): building
Hex 1332 is invalid!
	Incomplete building!  Missing terrain(s): building
Hex 1431 is invalid!
	Incomplete building!  Missing terrain(s): building
Hex 1432 is invalid!
	Incomplete building!  Missing terrain(s): building

**Comment by HammerGS** [comment]
Its been a couple of weeks without any reply from the original poster. Closing this.
