### ISSUE TITLE
Awesome 11H invalid

### ISSUE THREAD

**Issue by SJuliez** [MegaMek/megamek#4657]
In 0.49.14, with validation updated to check the number of crit slots for internal structure, the Awesome 11H registers as invalid. It clearly has Clan Endo Steel, but seems to think it's using IS Endo Steel after being loaded. My guess is that this is due to it being a Mixed Base IS unit. So we can maybe rework the unit to Base Clan (if that doesnt add other issues) or (probably better) change the loader to correctly load the structure type.

![image](https://github.com/MegaMek/megamek/assets/17069663/7603fbfb-9d72-4e9c-974f-da7f009bcc5a)

![image](https://github.com/MegaMek/megamek/assets/17069663/e03696b6-c02e-4a1c-a89f-4181809a7999)

**Comment by mhjacks** [comment]
Thanks for looking into this!  It looks like this same issue might affect some other units as well:

![image](https://github.com/MegaMek/megamek/assets/7352852/21af92f3-8240-46d9-9173-4cb59ce72a9a)

They seem to have a common IS Chassis and Clan Endo Steel - not a common combination, it seems

**Comment by HammerGS** [comment]
I hate to say it. But change the loader would be my vote. Going forward we will see almost every unit being mixed tech.

**Comment by mhjacks** [comment]
In the data directory of current mechfiles, I get the following matches:

```
./mechs/3055U/Prometheus.mtf
./mechs/3145/Davion/Templar III TLR2-OD.mtf
./mechs/3145/NTNU RS/Dasher II 4.mtf
./mechs/3145/NTNU RS/Mangonel MNL-4S.mtf
./mechs/3145/NTNU RS/Templar TLR1-OR.mtf
./mechs/Golden Century/Fox CS-1.mtf
./mechs/Golden Century/Vision Quest VQ-1NC.mtf
./mechs/XTRs/Caveat Emptor/Omni-Marauder A.mtf
./mechs/XTRs/Caveat Emptor/Omni-Marauder Prime.mtf
./mechs/XTRs/Davion/Enforcer III ENF-7X MUSE COMPACT.mtf
./mechs/XTRs/Royal Fantasy/Hunchback HBK-LGN-Pin _Anastasia_.mtf
./mechs/XTRs/Royal Fantasy/Hunchback HBK-LGN-Pin _Drizella_.mtf
./mechs/Rec Guides ilClan/Vol 24/Annihilator ANH-5W.mtf
./mechs/Rec Guides ilClan/Vol 26/Quickdraw QKD-9G.mtf
./mechs/Rec Guides ilClan/Vol 4/Awesome AWS-11H.mtf
```

This was done using the (admitted ugly) Python script:

```
#!/bin/python

import os
import re
import sys

def grep(regex, file):
    with open(file, 'rt') as f:
        for l in f.readlines():
            if regex.match(l):
                f.close()
                return True
    
    return False

IS_BASE = re.compile("""techbase:.*IS Chassis""", re.IGNORECASE)
CLAN_ES = re.compile("""structure:\s*Clan\s+Endo[-\s]?Steel""", re.IGNORECASE)

if __name__ == '__main__':
    for (path, dirs, files) in os.walk(sys.argv[1]):
        for f in files:
            if f.endswith('.mtf') or f.endswith('.blk'):
                fname = os.path.join(path, f)
                x = grep(IS_BASE, fname)
                if x:
                    #print(f"{fname} matches {IS_BASE}")
                    y = grep(CLAN_ES, fname)
                    if y:
                        print(f"{fname}")
            else:
                continue
```
