### ISSUE TITLE
Princess bot NPEs in physical attacks phase

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#467]
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/691973/mekhqlog.txt)
[comguards.sav.gz](https://github.com/MegaMek/megamek/files/691974/comguards.sav.gz)

**Comment by neoancient** [comment]
`fireControl` was null, indicated that `initialize()` had not been called. This appears to be a game that was saved and reloaded during the physical attacks phase.
