### ISSUE TITLE
[49.13] Mousing over hexes can reveal hidden units

### ISSUE THREAD

**Issue by buzzzz2138** [MegaMek/megamek#4670]
### Environment
MekHQ
Windows 10
Java 11

### Description
![image](https://github.com/MegaMek/megamek/assets/3680372/9328bdbb-713e-4c09-b080-9ab5f7cd5ea7)
![image](https://github.com/MegaMek/megamek/assets/3680372/56fc190b-37fd-4a38-b865-c8025b87729f)
![image](https://github.com/MegaMek/megamek/assets/3680372/88f5184c-df97-45c0-97de-fca569395645)

First 2 screen shots are from an observer/opposing team. Last one is from a team member of the hidden units.  

### Files
[autosave_2023-07-25_23-13-19.sav.gz](https://github.com/MegaMek/megamek/files/12167883/autosave_2023-07-25_23-13-19.sav.gz)

**Comment by vipersbrood** [comment]
![image](https://github.com/MegaMek/megamek/assets/64331766/efbb26c0-14ce-41e9-b5fd-fd44c1d42857)
[autosave_2024-02-14_17-16-51.sav.gz](https://github.com/MegaMek/megamek/files/14289231/autosave_2024-02-14_17-16-51.sav.gz)
This bug is still present in 0.49.17

**Comment by Sleet01** [comment]
Confirmed still broken in 0.49.18 dev.  Turning on Double Blind fixes it, but that should not be required...
I think I have a quick fix.

**Comment by Sleet01** [comment]
Fix is to make the entity-querying parts of `BoardView.getHexTooltip` cognizant of the local player's ability to see the units when filling in that part of the tooltip.  This will use the same check utilized for drawing the icons so if you can see an icon, you'll see the stat block, and vice-versa.

<img width="1920" alt="image" src="https://github.com/MegaMek/megamek/assets/22018319/b683cf77-94e9-4104-907e-2db0e1b36926">
