### ISSUE TITLE
TAC was transferred to the LT, but no crit roll was made

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#468]
SRM 6 at Firestarter FS9-H (Independent (Periphery)); needs 3, rolls 11 : 3 missile(s) hit.

        **Firestarter FS9-H (Independent (Periphery)) takes 2 damage to LA (critical).
        2 damage transfers to LT (critical).
        Firestarter FS9-H (Independent (Periphery)) takes 2 damage to LT (critical).
            0 Armor remaining.**

        Firestarter FS9-H (Independent (Periphery)) takes 2 damage to CT.
             4 Internal Structure remaining.
            Critical hit on CT. Roll is 7; no effect.

        Firestarter FS9-H (Independent (Periphery)) takes 2 damage to CT.
             2 Internal Structure remaining.
            Critical hit on CT. Roll is 7; no effect.

The TAC was transferred to the LT, but no crit roll was made?

[mekhqlog.txt](https://github.com/MegaMek/megamek/files/691987/mekhqlog.txt)

[comguards.sav.gz](https://github.com/MegaMek/megamek/files/691985/comguards.sav.gz)

**Comment by HammerGS** [comment]
per TW pg 124

_**Every time the internal structure of a ’Mech, ProtoMech, or aerospace unit takes damage** (from a weapon attack, physical attack, falling, ammo explosions and so on), an internal component may take critical damage; vehicles determine critical damage differently (see Critical Damage, p. 192, in Combat Vehicles)._

So in this case nothing transferred to the IS so no crit would be rolled.

![image](https://cloud.githubusercontent.com/assets/13752452/21751639/9d621d34-d587-11e6-90e0-f0710b1de17a.png)

**Comment by Question2** [comment]
@HammerGS But this is a TAC. The LA was destroyed and then received a TAC. The TAC was transferred to the LT as the LA was destroyed (it even says (critical) ) but megamek didnt treat roll for the TAC crit chance.

**Comment by beerockxs** [comment]
Was the LA destroyed in that phase or in a previous phase? TACs only transfer if the location was destroyed in a previous phase.

**Comment by Question2** [comment]
@beerockxs Just checked, the LA was destroyed in that phase.
