### ISSUE TITLE
[QUESTION] What wqould be an easy way of exporting weapon properties from MegaMek?

### ISSUE THREAD

**Issue by Darker** [MegaMek/megamek#4689]
With friends, we're working on a project that should, if complete, be an electronic board that tracks the basic mech status such as damage, ammo and components. Currently, it's just a console application.

I'd like to make sure I can parse MegaMek files for most normal 'Mechs. I wrote some ad hoc parser manually, but I'd like to at least have a registry of weapons with their properties. All that is already written in `WeaponType` implementations. I was wondering what would be the simplest way to export all this information to something like JSON.

Could you provide any hint where should I look so that if I edit MegaMek main() I can print out this info?

**Comment by NickAragua** [comment]
I would just use the command line to export the extended equipment database.

java -jar MegaMek.jar -eqedb or MegaMek -eqedb if you're using the executable.
