### ISSUE TITLE
Would like my MegaMek server listed...

### ISSUE THREAD

**Issue by fstltna** [MegaMek/megamek#4698]
### Environment
dedicated MegaMek server
Ubuntu OS
Java version 1.8.0_382

### Description
Would like my server listed

My host name is mekwars.mekcity.com
port is 2346
MekHQ is running 0.48 - latest stable
name "MekWars @ MekCity.com"
I suppose Steiner for faction...

**Comment by rjhancock** [comment]
We appreciate your interest how this is the wrong place for it. Requests must be made either on the official Discord or via the appropriate repository https://github.com/rjhancock/megamek-games and it will be looked at at that time.
