### ISSUE TITLE
Feature Request: Range brackets for TAG visualized

### ISSUE THREAD

**Issue by svetpavel** [MegaMek/megamek#470]
Can we have the range brackets for TAG visualized during the designation phase as for a usual weapon?

**Comment by BLOODWOLF333** [comment]
![note](https://cloud.githubusercontent.com/assets/16950832/26029683/3ada0adc-3801-11e7-8661-1d01774237c7.png)

**Comment by mhjacks** [comment]
+ 1 for this.  It would be a nifty enhancement.
