### ISSUE TITLE
TacOps zip-lines rules implemented incorrectly

### ISSUE THREAD

**Issue by svetpavel** [MegaMek/megamek#471]
As of now the only modifiers for deploying BA and infantry via zip-lines are the anti-mech skill and the landing modifier for the type of the terrain. As per this (old) thread http://bg.battletech.com/forums/index.php?topic=25751.msg582462#msg582462, there also should be the modifier the elevation.

**Comment by arlith** [comment]
It looks like what was said in that thread never triggered any errata that was added, so when I implemented zip-lines, I wasn't aware that elevation should be factored in.  I've noticed Xotl that some errata should probably be issued.  I've also added code to factor in elevation to the PSR.
