### ISSUE TITLE
[0.49.14] Naval cannot move under bridge to the other side

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#4712]
### Environment
Megamek 0.49.14

### Description
Naval cannot move under bridge to the other side

### Files
Save file attached.

[Round99.sav.gz](https://github.com/MegaMek/megamek/files/12367158/Round99.sav.gz)

**Comment by SirMegaV** [comment]
Forgot to mention, "climb mode" disabled.

**Comment by neoancient** [comment]
The bridge is at the surface level of the water, which blocks any naval vessels.
