### ISSUE TITLE
Mechs can climb onto buildings without expending additional MP or requiring a PSR

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#472]
Page 22 of tacops includes rules for mechs climbing buildings and stuff like cliffs.

In short, you can only use walking MP, each level change costs 2 MP or 3 if the mech has only one undamaged hand, and it requires a PSR per level change at a +1 modifier or an additional +2 modifier (for a total of +3) if the mech only has one undamaged hand.

The Ostol in this save was in hex 1414 at the start of this round but managed to climb onto the roof of the adjacent level 2 building by spending only one walking MP and without requiring any PSR checks (see round report). This should be impossible, as the Ostol only has one undamaged hand and it would require 6 MP in total and require two PSR checks at a +3 modifier each.

[comguards.sav.gz](https://github.com/MegaMek/megamek/files/700983/comguards.sav.gz)

[mekhqlog.txt](https://github.com/MegaMek/megamek/files/700985/mekhqlog.txt)

**Comment by ObviousTech** [comment]
The paragraph immediately before that:

> "The Climbing rules enable a ’Mech to enter a hex that is 3 or more levels higher or lower than the hex it occupies."

Because the Ostsol is only going up 2 levels, it does not need to use the climbing rules and thus does not need to make these checks.

TacOps Climbing is not implemented in MegaMek currently.  Leaping, however, is, so with the proper options enabled you can jump off a cliff (but not climb one).

**Comment by Question2** [comment]
Good point, someone on IRC told me the climb function uses the tacops climb rules so I thought the ostol used it to climb onto the building roof.
