### ISSUE TITLE
[49.13] Starting a mech that deployed shutdown allows firing in the turn it restarts

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/megamek#4723]
Megamek 49.13
Windows
OpenJDK 11

This concerns an optional unofficial rule that allows deploying a mech shutdown, but I haven't tested if this also occurs if the mech shuts down from excessive heat.

If a shutdown mech starts, it can't move the turn it does, but in the fire phase, when you're not supposed to be able to fire, you can.

Attached are a couple of battle saves, one from before the units are deployed, the other after they started the engines.
[ingame2.sav.gz](https://github.com/MegaMek/megamek/files/12432980/ingame2.sav.gz)
[ingame3.sav.gz](https://github.com/MegaMek/megamek/files/12432982/ingame3.sav.gz)

P.S.: Are logs necessary for this?

**Comment by neoancient** [comment]
Using official rules, startup and shutdown occur during the heat phase, and units are able to move and fire normally the next turn. The manual startup and shutdown options are an unofficial rule and were implemented to take place durin the movement phase and end movement. This is working as intended.
