### ISSUE TITLE
[0.49.15] Nightly Build - Clan Dropships with BA bays have the bay weight and type set to (IS) when opened in MegaMekLab

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megamek#4724]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
12:56:13,780 INFO  [megamek.MegaMek] {main}
megamek.MegaMek.initializeLogging(MegaMek.java:116) - Starting MegaMek v0.49.15-SNAPSHOT
	Build Date: 2023-08-24T01:05:07.079769100
	Today: 2023-08-24
	Origin Project: MegaMekLab
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 1 GB

### Description
Submitting issue in MegaMek project instead of MML per Sleet01's direction, as it is an underlying MegaMek loader issue

Issue is specific to units that exist prior to the nightly build listed above and related to https://github.com/MegaMek/megamek/pull/4709

If a Clan dropship (Outpost (Defender) was used for testing purposes) is opened in MegaMek lab, the Battle Armor bay is listed as (IS) and the weight of the bay uses the inner sphere values. This results in the Outpost (Defender) dropship in question being 10 tons underweight with the vanilla .blk files

### Files
No saves involved, as this issue can be seen entirely with stock units included with the build. Including screenshots below for the issue in the Nightly build, as well as the issue NOT being present in a previous nightly build

Build Date: 2023-08-24T01:05:07.079769100 (HAS ISSUE)

![outpost bad 1](https://github.com/MegaMek/megamek/assets/101755917/81ae8b7e-60de-4ea4-ab82-d356146633ad)
![outpost bad 2](https://github.com/MegaMek/megamek/assets/101755917/30111833-e55c-4525-91da-781809d5124f)

---------------------------------------------

Build Date: Build Date: 2023-08-17T01:03:44.107179900 (DOES NOT HAVE ISSUE)

![outpost good 1](https://github.com/MegaMek/megamek/assets/101755917/86612e6c-22b2-4010-85c1-a82daea2e92d)
![outpost good 2](https://github.com/MegaMek/megamek/assets/101755917/78f288df-f43d-4038-aebe-14f250f6e63a)

**Comment by Sleet01** [comment]
This was a test matrix miss on my part: loading a pre-update IS dropship worked correctly, but I didn't confirm pre-update Clan dropship did _not_ get IS BA bays.

The issue is that we previously got the BA bay tech level from the carrying entity itself - the root of the problem we were trying to fix! - but in the case where:

1. the entity is non-IS,
2. the BLK file is in the old format,
3. we load the old-style bay and then normalize it to the new format,

we are losing that context and just defaulting to "IS" as the bay tech base.
