### ISSUE TITLE
MegaMek does not populate ProtoMech Transport bays in custom dropships.

### ISSUE THREAD

**Issue by Screech48** [MegaMek/megamek#4739]
### Environment
MekHQ 49.14
Windows 10
Java 11.0.14

### Description
Loaded the Aurora dropship into MM Lab.  Removed 1 Mech Bay in favor of a protomech Bay with a 9 PM capacity and 3 doors.  Altered escape pods to meet new evacuation requirements and adjusted cargo to reflect remaining free tonnage.  Gave a distinct Model type  (Society) and saved into a custom folder in the MechFiles directory.  Exported to PDF (enclosed.)

Exported PDF shows the PM bay.  When selecting and loading the custom dropship into MegaMek for play, the Protomech Bay does not populate, either in the selection screen or in the lobby environment.

However, the following cannon dropships DO display their protomech transport bays properly:
Outpost (3070)
Arcadia (3066)
Arcadia (3080)

### Files

This is the .blk produced by MM Lab for the custom unit.
[Aurora (Society).zip](https://github.com/MegaMek/megamek/files/12502615/Aurora.Society.zip)

This is the PDF Export
[Aurora (Society).pdf](https://github.com/MegaMek/megamek/files/12502473/Aurora.Society.pdf)

This is a screenshot of the unit selection window
![DS PM Bay Aurora](https://github.com/MegaMek/megamek/assets/25867171/338607b8-c805-44fa-93fa-41a34fe85bea)

This is a screenshot of the lobby, attempting to load a protomech into the dropship (the load is grayed out due to 0 viable bays)
![DS PM Bay Aurora Lobby](https://github.com/MegaMek/megamek/assets/25867171/41da5421-bc17-4704-a72c-73e178400765)

**Comment by Sleet01** [comment]
This is likely the result of the new bay format missing some information when saving, but loading the previous format correctly.  I'll take it, for my sins.

**Comment by Sleet01** [comment]
Correction: this issue predates my rework of the bay format.  Investigating...

**Comment by Sleet01** [comment]
Issue appears to be that the bay in the saved file is "ProtoMekBay" but our code is now looking for "ProtoMechBay", which occurs in all the stock dropships listed above.  Checking the history of changes to the 49.14 BLK file save format...

**Comment by Sleet01** [comment]
The issue is that somebody (jrbowen24@gmail.com) went through and replaced "ProtoMech" / "protomech" with "ProtoMek" _in the ProtoMechBay.java file_ but not _in the BLKFile.java_ file.  So any versions of MML from after March 2022 save the relevant block as a "ProtoMekBay" but only read "ProtoMechBay" lines.

This has been broken for approximately a year and a half.

The simplest fix is to accept both strings when reading a BLK file, but this is probably broken for any units that can contain ProtoMech bays yet do not use BLK files (if they exist).

**Comment by Sleet01** [comment]
@Screech48 FYI the workaround for you is to find and replace any instance of "ProtoMekBay" in your BLK files with "ProtoMechBay"; I've confirmed this works with 49.14 (and should work with any MML going back to last year).

**Comment by Screech48** [comment]
This workaround DOES function.  However, it causes ANOTHER problem, in that the displayed bay now displays as a ProtoMek bay, which Protomechs do not qualify for (thanks to K and CH spelling differences.) 
![ProtoMech bay listed as ProtoMek bay](https://github.com/MegaMek/megamek/assets/25867171/4a51afc1-0290-4291-bc53-38c61dd63908)
![ProtoMech bay listed as ProtoMek bay  Arcadia](https://github.com/MegaMek/megamek/assets/25867171/eb7cfacb-2fda-43f0-a26e-a8e8a899be56)


This is true even with the stock Cannon units such as the Arcadia.  The spelling mismatch somewhere in the coding is deeper than changing the unit .blk to enable the display of the bay.

**Comment by Sleet01** [comment]
> This workaround DOES function. However, it causes ANOTHER problem, in that the displayed bay now displays as a ProtoMek bay, which Protomechs do not qualify for (thanks to K and CH spelling differences.) 

Oh bother.
In that case, I'll update my PR to also revert the original change.  Especially given that we still have stock units using the original entry format, and that the MML UI and unit itself still use it...

**Comment by Sleet01** [comment]
> This is true even with the stock Cannon units such as the Arcadia. The spelling mismatch somewhere in the coding is deeper than changing the unit .blk to enable the display of the bay.

Sorry, I'm a complete MekHQ neophyte.  Are you seeing the new issue (ProtoMechs can't load into ProtoMek bay) within MekHQ, like in the TO&E tab or something, or is the issue occurring withing MegaMek after launching a mission?

**Comment by Screech48** [comment]
All of my issues have been in MegaMek itself.  I mentioned the Lab in the initial post because I had crafted a custom unit.  I also mentioned the version as MekHQ because the Report a New Issue tooltip indicated that I should specify if I was using a MekHQ package or a standalone download.


So, here's the sequence of events I follow:
Download and unpackage MekHQ49.14 (I do this because I only have 1 set of files when modding and using customs.)
Craft something in MegaMek Lab
Open MegaMek and use it in a stand-alone game.  The screenshots listed above were from a game session earlier today.  

Open MegaMek 49.14, Add an Arcadia or Outpost that has ProtoMek bays, add a protomech of your choice, and you'll find that the dropship will not accept the proto as a valid carried unit.

As an aside: I never run MekHQ.  I don't have the patience to put all the details together to run my own unit.

**Comment by Screech48** [comment]
Here is a fresh example.  I just opened MegaMek 49.14, loaded an Outpost and a Roc Protomech.  You can see the following information:
The dropship's Protomech bay;
The protomech pop-up tooltip;
The dropdown menu showing that loading the protomech into the dropship is invalid;
The text box at the bottom showing version number.
![Fresh Example](https://github.com/MegaMek/megamek/assets/25867171/25d193f7-166c-4206-b606-ec3385fa5023)

**Comment by Sleet01** [comment]
It looks like the issue with loading Protos into dropships in MegaMek is a separate logic issue, unrelated to the ProtoMek/Mech strings.  I'm testing the fix and adding some tests to validate this path, should be good to go soon.
