### ISSUE TITLE
Incorrect movement cost/no PSR required to move into hardened buildings

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#474]
![megamek](https://cloud.githubusercontent.com/assets/1191378/21931177/1fe83760-d9ee-11e6-92ab-800b31f3dba1.jpg)

Mechs only seem to need to pay 2 MP to move into hardened buildings now annd do not require a PSR, this seems to have only occured in the last few versions. MP cost for hardened buildings should be +4 and require a PSR according to the movement costs table on page 52 of TW.

[comguards.sav.gz](https://github.com/MegaMek/megamek/files/704372/comguards.sav.gz)
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/704373/mekhqlog.txt)

**Comment by wildj79** [comment]
This isn't a bug.  The default behavior has been changed in recent versions.  Units will default to climb mode instead of move thru now.  What's going on here is that the unit is climbing on top of the building, instead of moving thru it.

**Comment by neoancient** [comment]
With climb mode changed:
![building mp](https://cloud.githubusercontent.com/assets/16927464/21943199/c42618b4-d995-11e6-834e-45f0dba1451b.png)

**Comment by Question2** [comment]
@wildj79 Shouldnt there be some kind of indicator that the unit is going to climb rather than walk into a building then? Also climbing a building should require a PSR, but megamek is not requiring it.

Maybe change the color of the MP to indicate it is going to climb, rather than move into a building?

**Comment by Question2** [comment]
@wildj79 Also the gullotine does not have any hand actuators so it shouldnt default to climb mode in the first place (as you need hand actuators to climb).

**Comment by wildj79** [comment]
@Question2 The climbing rules from TO don't apply in this case.  

> The Climbing rules enable a 'Mech to enter a hex that is 3 or more levels higher or lower than the hex it occupies.
_- TO p.22_

The Gullotine is moving on top of a height 1 building.  In this case you use the standard rules when entering a hex that is 1 level higher than the currently occupied hex.
