### ISSUE TITLE
[0.49.13] Java Exception before firing phase after reenforce from mul

### ISSUE THREAD

**Issue by mwberlindeu** [MegaMek/megamek#4741]
I have reenforce from mul in a running game. Movement phase went normal but I got a java exception before the firing phase, apparantely the connected clients were not in sync any more on the game phases. I could replicate the issue twice. When I ran the same game without reenforcing from mul the issue did not appear, firing phase was running as normal.

As the game has many units I have not attached this. A recreation of this bug will take some time (clicking through). I will check the issue again in a more recent version of the game, and will come back if the bug reappears again.

**Comment by HammerGS** [comment]
We need logs. 

https://github.com/MegaMek/megamek/wiki/Creating-an-Issue-%28Bug-Report%2C-Request-for-Enhancement%2C-Errata%29

**Comment by neoancient** [comment]
I'm closing this since the requested log file hasn't been provided and there's nothing we can do without it.
