### ISSUE TITLE
Various Aerospace Issues - Aero V-Landing Does Not Apply Modifiers Correctly, Addtl issue with water.

### ISSUE THREAD

**Issue by Sierra-Invenio** [MegaMek/megamek#4743]
Megamek 0.49.14, Win 10, Java

First Issue: V-LAND modifiers:

Per TW P87: "Units making vertical landings reduce by half (round down) the terrain modifiers..."

![image](https://github.com/MegaMek/megamek/assets/58146674/9df5b874-0cac-4c43-b810-30ed97f1e13d) shows full value being applied. This is consistent across rough, light trees, heavy trees, and water hexes.

Landing in rough additionally does not apply landing gear damage (P86 table foot note), which would apply on future land checks as well.

![image](https://github.com/MegaMek/megamek/assets/58146674/67058eb1-8cda-417f-b20f-adca1ad38413)

Water also has some fun things: this is not a clear hex as noted in the dialogue, and this modifier is not correct. (Should either be 3 or 1. 3 for a regular landing, 1 for a v-land)

Additionally: if the vehicle lands in water, it is unable to move, and falls into a stationary movement loop rather than being destroyed (as a fighter would be for entering water, see P82 which is referenced by 87 "for landing in water, see crash rules") Similarly, woods are undamaged by a fighter which lands in them, but the wording in TW is very unclear if this is what should take place.

Save file attached: to replicate: simply deploy the 0/0 fighter anywhere on board and attempt a V-Land or regular land as desired.

[Aerodyne.sav.gz](https://github.com/MegaMek/megamek/files/12505005/Aerodyne.sav.gz)

**Comment by Sierra-Invenio** [comment]
Additional:

you can land without using all of your velocity, which MM does not allow you to do. Same page for rules citations (P86 TW)

**Comment by HammerGS** [comment]
I'm going to rename this, and you can add other Aerospace issues to one report.

**Comment by Sierra-Invenio** [comment]
Understood.

**Comment by Sierra-Invenio** [comment]
Attempting to recover from the turn of an ASF into a DS that already launched from the same door produced this:

![image](https://github.com/MegaMek/megamek/assets/58146674/08bbaa03-743a-4034-bb80-03128360c661)

I was attempting to test whether or not you could launch 2 and recover 2 from the same door in the same turn, save file and logs attached to this post.

Java Version: 18.0.1.1
[megamek.log](https://github.com/MegaMek/megamek/files/12543394/megamek.log)
[Recover.sav.gz](https://github.com/MegaMek/megamek/files/12543396/Recover.sav.gz)

to reproduce: attempt to recover either of the ASFs standing on top of the DS, which has already "launched", but the units have not taken the field yet I believe.

**Comment by Sierra-Invenio** [comment]
![image](https://github.com/MegaMek/megamek/assets/58146674/05c2d2b6-fb2d-4cb4-8a5d-3d87ba8b63cd)

Per SO P50/51 - Jumpships: "mount attitude jets that allow them to change facing by one hexside per turn... a jumpship cannot use its attitude jets (that is, make a facing cange) in the same turn it changes its velocity, no can it expend thrust in that turn."

The movement shown in graphic is therefore impossible legally, but it will execute.

**Comment by neoancient** [comment]
Disregard Hammer's statement above. Unrelated issues should never be put in the same report.

**Comment by Sierra-Invenio** [comment]
Understood, have subscribed to the other threads, let me know if you need any additional information.
