### ISSUE TITLE
Quirk "VTOL Rotor Arrangement"

### ISSUE THREAD

**Issue by SJuliez** [MegaMek/megamek#4756]
The quirk "VTOL Rotor Arrangement" should be called "VTOL Rotor Arrangement (Co-Axial)"
see DI Multipurpose VTOL
![image](https://github.com/MegaMek/megamek/assets/17069663/4272b95f-e418-47d1-a2c2-787be85e3bef)

**Comment by Saklad5** [comment]
There are actually two quirks here: "VTOL Rotor Arrangement (Co-Axial)" and "VTOL Rotor Arrangement (Dual)".

**Comment by gsparks3** [comment]
For further reference, the Karnov UR Transport is a good example of a VTOL that should have the latter quirk, while the Warrior Attack Helicopter is another example of a VTOL that should have the former quirk.
