### ISSUE TITLE
VTOL armor diagram changes color incorrectly?

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#476]
![megamek](https://cloud.githubusercontent.com/assets/1191378/21954819/a3922da6-dab0-11e6-9f1f-6aeac49ea696.jpg)

The rear IS is listed as yellow, which means it should be damaged, but it is not (there is still rear armor left). The other VTOL has the same amount of rear IS, but its not colored yellow. Im guessing the part that is supposed to be colored yellow is the rear armor, not the rear IS? As the rear armor is damaged (5/7 armor).

[comguards.sav.gz](https://github.com/MegaMek/megamek/files/705925/comguards.sav.gz)
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/705930/mekhqlog.txt)

**Comment by BLOODWOLF333** [comment]
That FCE is a custom unit?

**Comment by BLOODWOLF333** [comment]
VTOLMapSet.java
`    public void setEntity(Entity e) {
     ......
                      WidgetUtils.setAreaColor(areas[i], vLabels[i],
                    (double) armor / (double) originalArmor);`
There is nothing wrong with that code (says Armor but also the value for IS) so issue is that custom FCE unit.
