### ISSUE TITLE
Estevez MBT has wrong BAR

### ISSUE THREAD

**Issue by neoancient** [MegaMek/megamek#4772]
According to Era Digest: Age of War, p. 25, the Estevez MBT has BAR 8 armor, not BAR 7.

**Comment by pheonixstorm** [comment]
ED Age of War is incorrect. Per Tech Manual p134 TR C cannot have a BAR of 8, only D or higher.

Also, this was posted in the errata forum: https://bg.battletech.com/forums/index.php/topic,6618.msg981926.html#msg981926
As well as my own for the AA variant: https://bg.battletech.com/forums/index.php/topic,6618.msg1226129.html#msg1226129

**Comment by HammerGS** [comment]
Per errata we should be correct
