### ISSUE TITLE
Nullpointexception error

### ISSUE THREAD

**Issue by BTSS88** [MegaMek/megamek#4789]
49.14
Windows 11
Java Version: 11.0.17

nullexception error on AI turn. Hangs the AI, needing kick/reapply AI to fix but occurs again the following turn.

[autos
![Screenshot 2023-09-17 121650](https://github.com/MegaMek/mekhq/assets/119979347/2048844e-3576-4b55-acb4-47d7e9ce7b17)
ave.sav.gz](https://github.com/MegaMek/mekhq/files/12641914/autosave.sav.gz)
[megamek.log](https://github.com/MegaMek/mekhq/files/12641910/megamek.log)
[Legion30521027.cpnx.gz](https://github.com/MegaMek/mekhq/files/12641911/Legion30521027.cpnx.gz)

**Comment by NickAragua** [comment]
This is a megamek issue, moving it there.

**Comment by HammerGS** [comment]
From the log

```
12:16:25,020 ERROR [megamek.client.bot.princess.Precognition] {AWT-EventQueue-0}
megamek.client.bot.princess.Precognition.handlePacket(Precognition.java:276) - 
java.lang.NullPointerException
	at megamek.common.Board.setHexes(Board.java:698)
	at megamek.client.bot.princess.Precognition.handlePacket(Precognition.java:175)
	at megamek.client.bot.princess.Princess.handlePacket(Princess.java:1796)
	at megamek.client.Client$1.lambda$packetReceived$0(Client.java:174)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
```

**Comment by Sleet01** [comment]
Issue appears to be that, during processing of a CHANGE_HEXES packet, we get a list of coords whose matching hexes list has one `null` element.  When `board.java:setHexes()` tries to call `currHex.hasExitableTerrain()`, we get the root NPE.

@HammerGS I can safety that call and maybe leave the null hex out of the LinkedHashSet of coordinates that need updating when processing this packet, but it seems like we want to avoid sending any `null` hexes in this packet type; what do you think?

**Comment by HammerGS** [comment]
> Issue appears to be that, during processing of a CHANGE_HEXES packet, we get a list of coords whose matching hexes list has one `null` element. When `board.java:setHexes()` tries to call `currHex.hasExitableTerrain()`, we get the root NPE.
> 
> @HammerGS I can safety that call and maybe leave the null hex out of the LinkedHashSet of coordinates that need updating when processing this packet, but it seems like we want to avoid sending any `null` hexes in this packet type; what do you think?

Not a coder, but anything that adds safety to a call works for me. Perhaps @NickAragua or @SJuliez should comment.

**Comment by Sleet01** [comment]
It looks like this occurs specifically when 
A) there is fire or smoke on the very edge of the board,
B) conditions cause the smoke to spread to an off-board hex that doesn't need to be tracked,
C) there is a Princess process trying to use packets for Precognition (which uses rougher processing than the main game).

So I'd say it's fine to skip updating the affected hexes since they aren't being tracked by the main game (which is what causes the hexes to be null in the first place).

I'll filter out null hexes when creating the packet, but also skip updating null hexes or hexes outside the board when processing this specific type of packet (other packet types may need to continue using them).
