### ISSUE TITLE
Feature Request: Tooltip BV

### ISSUE THREAD

**Issue by ThomasMarik** [MegaMek/megamek#479]
When playing games that have BV victory conidtions, such as ATB games,  I am finding myself constantly wanting to check the current BV of both enemy and my own units.  I would like to request that this information be put on the tooltip of the unit for easy access.

**Comment by SJuliez** [comment]
BV victory conditions check the team BV, don't they? Wouldn't the team BV then be more interesting than the individual unit BV?

**Comment by ThomasMarik** [comment]
checkbv will give me the total team BV.  I am wanting individual BVs so I can easily assess priority targets on the map.
