### ISSUE TITLE
Flame Based Infantry Bugs

### ISSUE THREAD

**Issue by Logajam** [MegaMek/megamek#4793]
### Environment
MM49.14

### Description
A:  Flamer (Man portable) (Used by most Flamer Infantry platoons or points), despite having a mode function to toggle between damage or heat, only does damage.  As does Mortar (heavy) Inferno.  Which implies there is a bigger problem.  Wonder if its secondary weapon based.  I know that a "Rifle (Federated-Barrett M42B)(Inferno)" did apply heat instead of damage when it was the weapon used to determine range.

B: If you turn on the game  option "Flamers per Battlemech manual" the option to toggle between damage and heat modes on infantry flame based weapons is removed, leaving only damage.

C: Infantry Inferno LRM and Inferno Mortar need additional mode options of heat, indirect, and indirect heat. (If CI mortars even work with IF yet.  Don't think they do.)

D: If an infantry unit's primary or secondary weapon have the F Flame-based special ability, the unit receives the F Flame-based ability.

Currently megamek seems to be deciding to only use the weapon that supplies the range brackets  Which is true for the N Non penetrating weapon special ability, But Flame based weapons have this foot note: "*Platoon special feature applies if one or more weapons assigned"  (TM pg 148, or pg 9 of the TM errata document.)

**Comment by Logajam** [comment]
Ok.  Scratch that.  The Federated blah blah blah....  Did an actual heat attack once,  and now I cant get it to do it again.  Its just doing damage when its in heat mode.

**Comment by pheonixstorm** [comment]
CI mortars currently dont work as IDF. I already have a ticket open for this so eventually it will happen.

Don't know if LRM infantry can make IDF attacks, never tried. In fact, didn't know there was a toggle for flamer infantry as I rarely use them.
