### ISSUE TITLE
[0.49.15] (Minor Visual Bug) Sensor Range Bands Not Showing Until Unit Movement Begins

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megamek#4795]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
megamek.MegaMek.initializeLogging(MegaMek.java:118) - Starting MegaMek v0.49.15-SNAPSHOT
	Build Date: 2023-09-18T01:07:34.461102200
	Today: 2023-09-18
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 8 GB

### Description
During movement phase, the light blue sensor range bands are not showing up until I actually make a move with a unit (even if it's just changing facing).

Included are my MM preferences and gameoptions, I have double blind/TacOps Sensor Rules both enabled. Issue occurs while using the ctrl-Q movement envelope, as well as when not using ctrl-Q.

Once I move a unit to get them to show up, if I then click to a different unit and back the sensor bands disappear until the unit is moved again.

They are clearly functional, as I am able to detect units with sensors even when they're not in LOS, this is purely a visual indication of the detection range of my units.

### Files
[Sensor Bands Movement Phase.zip](https://github.com/MegaMek/megamek/files/12651683/Sensor.Bands.Movement.Phase.zip)

Prior to moving the unit:
![Sensor_Bands_Missing](https://github.com/MegaMek/megamek/assets/101755917/2dc78dd5-f192-4528-8c55-e3ea42b173bc)

After changing facing 1 hexside to the left:
![Sensor_Bands_Showing](https://github.com/MegaMek/megamek/assets/101755917/0d1b6f3e-ba6e-4f72-a7e0-ee7990446679)

(edited to remove blank space on screenshot and re-upload zip)

**Comment by Sleet01** [comment]
@PhoenixHeart512 Would it be possible to provide an MM version number where this works as expected, for comparison?  I tried 0.48.0 but it doesn't appear to have this functionality.

There has been some churn in the code that handles drawing sensor ranges within the last couple quarters, so I'd like to take a look at a version that works correctly and compare code.

**Comment by PhoenixHeart512** [comment]
I still have all my old builds, I'll see if I can dig through and find one. Do you remember which version specifically they were added in? Ideally which nightly build date, since I have a bunch

**Comment by Sleet01** [comment]
@PhoenixHeart512 I was just hoping to get a version number from you, like "0.49.9" or something, from the last time that you saw the sensor overlay working correctly.

It appears that a bunch of changes went in around May of 2023; if you have something from April/May of this year that should work.  If not, I can trawl through the commit messages and try to pinpoint where stuff changed.

**Comment by PhoenixHeart512** [comment]
It looks like May 30th is when I noticed the sensor bands change, so ill check that build when I get home

**Comment by PhoenixHeart512** [comment]
I should have that build still, I'll zip it up and send it to you when I get home from work

**Comment by HoneySkull** [comment]
I provided a fix for this bug according to how it _should_ work.  

1.  When an entity is selected and sensor ranges is enabled, the ranges should be rendered for the selected entity and be updated when a new entity is selected for that selected entity.
2. Toggling sensor ranges should show and hide sensor ranges.   (There was bug that if you turned off sensor ranges then selected a different entity and then enabled sensor ranges, the ranges would not display until some GUI event triggered the re-calculating of ranges.)
