### ISSUE TITLE
[0.49.15] NPE during Artillery Phase Preventing Princess From Firing Offboard Artillery

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megamek#4796]
### Environment
megamek.MegaMek.initializeLogging(MegaMek.java:118) - Starting MegaMek v0.49.15-SNAPSHOT
	Build Date: 2023-09-18T01:07:34.461102200
	Today: 2023-09-18
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 8 GB

### Description
Princess not firing offboard artillery units (not sure if this would also affect a player or not). NPE found in the log that occurs during the artillery firing phase.

It might also affect players but I did not have any offboard artillery to test.

### Files
Paranoid autosaves were enabled so I just included a bundle of the autosaves from the beginning of the game. The logging state is also set to "info" so it's possible to see which phase the NPE occurs.

I've also included a manual save at the end of turn 1 firing phase so that the game can be easily loaded and cycled through to the Artillery phase as needed.
Player name: Tempest Marauders

[Offboard Artillery NPE.zip](https://github.com/MegaMek/megamek/files/12654344/Offboard.Artillery.NPE.zip)

**Comment by Sleet01** [comment]
@PhoenixHeart512 I'll take a look at this.  I don't see the manual save in the .zip; can you add that separately?

**Comment by Sleet01** [comment]
> Odd, I must have accidentally attached the wrong ZIP, the first one had the incorrect set of saves.
> 
> [Offboard Artillery NPE.zip](https://github.com/MegaMek/megamek/files/12664407/Offboard.Artillery.NPE.zip)

That got me the repro immediately, thanks.  It's as I suspected; the check for ADA availability is iterating _all_ weapons, even if they're not valid for off-board attacks, and energy weapons never have linked ammo so we get an NPE there.
Simple fix, should be up soon.
