### ISSUE TITLE
[0.49.15] Silent NPE during Princess Movement Phase for Wraith BA

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megamek#4801]
### Environment
megamek.MegaMek.initializeLogging(MegaMek.java:118) - Starting MegaMek v0.49.15-SNAPSHOT
	Build Date: 2023-09-18T01:07:34.414229700
	Today: 2023-09-22
	Origin Project: MegaMek
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 8 GB

### Description
- Silent NPE when Princess tries to move her Wraith BA squad. From the player's view she just hangs and never takes her turn.
- When I kicked the bot and joined a second client as a player, I was able to move the BA squad without issue, it seems to be specific to the Princess AI.
- Kicking and replacing Princess does not resolve the issue
- Battle Armor dismounted from the Linebacker on the previous turn, so this is the first turn where Princess is able to attempt to move the BA

> 10:52:40,662 ERROR [megamek.client.bot.BotClient] {Republic of the Sphere Primary Opfor Turn 6 Calc Thread}
megamek.client.bot.BotClient.calculateMyTurnWorker(BotClient.java:557) - 
java.lang.NullPointerException: Cannot invoke "megamek.common.MovePath.getEntity()" because "mp" is null
	at megamek.client.bot.BotClient.calculateMyTurnWorker(BotClient.java:523)
	at megamek.client.bot.BotClient.calculateMyTurn(BotClient.java:483)
	at megamek.client.bot.BotClient$CalculateBotTurn.run(BotClient.java:62)
	at java.base/java.lang.Thread.run(Unknown Source)

Save file included at the beginning of the move phase. Paranoid autosaves and "info" logging level (from log4j2.xml) are enabled on my client.

### Files
[Pre-error_save.sav.gz](https://github.com/MegaMek/megamek/files/12702575/Pre-error_save.sav.gz)

[megamek.log](https://github.com/MegaMek/megamek/files/12702583/megamek.log)

**Comment by Sleet01** [comment]
I think I got bit by this while debugging Princess's ADA selection logic; I'll take a look.

**Comment by Sleet01** [comment]
Turns out this is the result of a deeper Exception, somewhere in the equipment or transport code.  That exception gets caught in the path planning code, causing a null movement path object to be returned, leading to this NPE.
I'll try to ferret out the exact cause, but I'd bet it's due to some of the recent changes I made - either in the transport typing, or ammo/munitions type comparisons.

**Comment by Sleet01** [comment]
T'was the ADA / Field Weapon changes!  Mea culpa.
