### ISSUE TITLE
Bugged target view when targeting immobile enemy

### ISSUE THREAD

**Issue by BTSS88** [MegaMek/megamek#4809]
49.14
Windows 11
Java Version: 11.0.17

The screen is bugged with all details missing. Asked around on discord and everyone is seeing that screen so easily reproducible. 

![Screenshot 2023-09-28 154004](https://github.com/MegaMek/megamek/assets/119979347/88ca5ec0-1b4b-4753-bf8a-7d000201cf17)

**Comment by kuronekochomusuke** [comment]
#4733

**Comment by HoneySkull** [comment]
Trying to reproduce this - there must be some property of the target besides being immobile or prone that causes this:  
![image](https://github.com/MegaMek/megamek/assets/83041327/e71c1fbc-d653-4cfe-912f-f10f6693ab24)

**Comment by HoneySkull** [comment]
When I switch to "Metal" Swing theme, I see this with the same game save, I wonder if this is a font that is matching the background color: 
![image](https://github.com/MegaMek/megamek/assets/83041327/708bfb5f-4712-4d2b-be8b-5a08a150f505)

**Comment by HoneySkull** [comment]
Windows Classic Theme:  
![image](https://github.com/MegaMek/megamek/assets/83041327/d9ecbd64-30d6-42cd-babf-c6e00f871b74)
