### ISSUE TITLE
VTOL unable to fly over bridge

### ISSUE THREAD

**Issue by elementx54** [MegaMek/megamek#481]
I was flying a VTOL up a river which has a bridge crossing it. I could not fly over the bridge and continue up the river no matter what elevation I raised or lowered the VTOL to. Each time I tried I got grayed out movement numbers.  

I'm wondering if the VTOL is stuck on trying to "Go Through" or some other movement mode which doesn't make sense for VTOLs. I was using MegaMek 0.42.0. I did have many (more than not) advance options on.  

If you like I can provide a save file, when I get home.

**Comment by neoancient** [comment]
It's an unintended consequence of changing the default climb mode. If you change it to false in the advanced client options it will work as intended.

**Comment by pheonixstorm** [comment]
Possibly, but why would it have any affect on VTOLs?

**Comment by neoancient** [comment]
I know this is the cause because I tested it with default climb mode set both to true and to false. I would have to look at the code to be sure, but my guess is that any move entering a bridge hex with climb mode on is given the elevation of the bridge without checking whether it''s a ground unit first.

**Comment by elementx54** [comment]
Can an air unit purposefully go into/through a building in the BattleTech rules? If so then you would like to keep the climb mode there but add the button or maybe make climb up into go over. If not then ya, have them ignore the mode and just check to see if their elevation is high enough to fly over it (unless they are already on it and landing or following the road), or low enough to fly under it.

There is my two cents worth.

**Comment by wildj79** [comment]
Relevant rules from TW:

>VTOLs cannot fly at or below the tops of trees while in wooded
>hexes (2 levels high), and cannot fly at or below the building’s
>level in a building hex unless they are landing on the building.
> TW p.54

From that, I would say, no, they cannot purposefully enter or move through a building.  VTOL units should probably just ignore the climb mode.

**Comment by elementx54** [comment]
@neoancient is correct. I just tried the changing the default climb mode to `false` in the advance client options and the VTOL can now fly over the bridge. Since this is a pretty easy workaround, I'm going to move this bug from stable to post stable, as I don't think it is a priority now, but it still is a bug.
