### ISSUE TITLE
Release 0.42.1 on Linux identifies itself as 0.43.1-git

### ISSUE THREAD

**Issue by mhjacks** [MegaMek/megamek#482]
![screenshot from 2017-02-14 20-40-56](https://cloud.githubusercontent.com/assets/7352852/22958607/f30188f2-f2f5-11e6-8641-88abae37126e.png)

This appears to be completely cosmetic, but may indicate a problem with packaging tools or build scripts.

**Comment by MGM175** [comment]
I'm getting this as well on my Ubuntu MATE 16.10.
![zrzut ekranu w 2017-02-18 22-02-33](https://cloud.githubusercontent.com/assets/20325180/23096867/f9793ecc-f625-11e6-8985-54e72807b0c2.png)

**Comment by neoancient** [comment]
This is something that is updated as part of the procedure to build the release. There is nothing to be fixed here, as the procedure will be repeated with each new release or snapshot.

**Comment by pheonixstorm** [comment]
The 0.42.1 release is actually the 0.43 dev release. 0.42 needs to be repackaged using the correct branch/tag

**Comment by pheonixstorm** [comment]
Not trying to, but so far MML and HQ stable are 0.43 not 0.42

I have tested both and code from 0.43 is in them. MM might not be, but it is highly likely to be 0.43 as well. I wouldn't have posted otherwise.
