### ISSUE TITLE
Request to toggle Round Report formatting--Formatting improvement

### ISSUE THREAD

**Issue by Eruhin** [MegaMek/megamek#4825]
From 0.49.12 and on, the Round Report in MegaMek is floating, whereas 0.49.11 and before, the Round Report was a full screen display that the game would switch to, then press "Done" and continue with the game.

Is it possible to add an option to use the 0.49.11 Round Report window format, rather than floating window?  The floating window actually bothers me due to the color differences between the map and the window.  A way to re-size the round report, and have it keep the re-sizing, would be great.  For instance, the Windows button at the top right of the main mega-mek screen allows full screen or not-full screen, which is Microsoft standard, would be great.

Or a way to select the Round Report screen size (full or window) in the MegaMek options would also be great.

Thanks!

**Comment by Eruhin** [comment]
I forgot to mention I can manually re-size the window by dragging the sides of the window, but options as originally described are definitely preferable.  Thanks!

**Comment by HammerGS** [comment]
See comments here

https://github.com/MegaMek/megamek/issues/4826
