### ISSUE TITLE
MegaMek Player List Popup Window--requested improvement

### ISSUE THREAD

**Issue by Eruhin** [MegaMek/megamek#4826]
I have not been able to find in the latest MegaMek versions a way to disable the "Player List" popup.  I see where it can be toggled.  

The "Player List" popup does not add value (in my view) and, depending how I size the Round Report, gets in the way.

Is there a way to add an option to the MegaMek Options where someone can disable the player list pop-up, unless manually selected by the "Player List" button?

Thanks!

**Comment by gsparks3** [comment]
Client Settings menu (Alt+C), Auto Display tab, uncheck the player list for all phases.

**Comment by Eruhin** [comment]
Thanks!  That's what I needed.

    On Thursday, October 12, 2023 at 10:22:32 AM CDT, gsparks3 ***@***.***> wrote:  
 
 


Client Settings menu (Alt+C), Auto Display tab, uncheck the player list for all phases.

**Comment by HammerGS** [comment]
There are numerous options under that Auto Display Tab

![image](https://github.com/MegaMek/megamek/assets/13752452/80b55349-a537-4751-9c5c-c9b861893ab3)

There are also  docking options here

![image](https://github.com/MegaMek/megamek/assets/13752452/fdc50800-5a98-4f96-a890-0c3477624376)
