### ISSUE TITLE
BUG: Personnel keep trying to fake their death

### ISSUE THREAD

**Issue by ThomasMarik** [MegaMek/megamek#483]
when resolving a battle in mekHQ after doing the megamek match you have the opportunity to review and alter damage taken by your personnel.   If someone has taken 6 points of damage ad you reduce it to 5 the game still considers him dead and sets him KIA.  This is incorrect as a person with 5 hits is not dead unless a Lost head result is rolled.

**Comment by pheonixstorm** [comment]
This is a MekHQ issue and needs a ticket there.
