### ISSUE TITLE
WiGEs jump to bottom of water hex rather than remaining airborne

### ISSUE THREAD

**Issue by Saklad5** [MegaMek/megamek#4830]
### Environment
MegaMek Version: MekHQ v0.49.14 Development Snapshot
Operating System: Mac
Java Version: 20.0.1

### Description
WiGEs are allowed to mount Vehicular Jump Jets, as described on page 160 of the sixth printing of _Tactical Operations: Advanced Units & Equipment_. This allows them to perform jumps while airborne.

While this is currently implemented in MegaMek, jumping to a water hex somehow results in the WiGE being placed one elevation above the terrain _under_ the water, rather than above the surface of the water as expected.

**Comment by Sleet01** [comment]
I took a look: fixing the jump level part is relatively simple (just adding the WIGE movement type to an existing check).

There are a couple of other questions, though:
1. are WIGE supposed to take a pilot check when jumping onto water?  Currently MM requires this.
2. are WIGE supposed to have a chance to take damage when jumping while in flight?  Currently MM does this check.
3. are WIGE supposed to sink and be destroyed IN A WATERY GRAVE [sic] when they are rendered immobile on water?  I'd argue "no" by dint of the now-innate floatation hull, but this definitely happens in MM right now :)

**Comment by gsparks3** [comment]
TO:AUE page 160 says that WiGE may _only_ use their JJ while airborne, and still gives a modifier for the motive system damage check required after jumping, so it seems they are supposed to have a chance to take damage while airborne.

The PSR doesn't seem right, I suspect that is a holdover from mechs jumping over a water hex needing to making a PSR to land safely on the bottom. WiGE simply drop to 1 level above the terrain and are vehicles anyway, so no PSR to remain standing would be necessary. The code for mechs doing this is probably why they jump to the bottom of the water hex in the first place.

**Comment by Sleet01** [comment]
Okay, when I get back to the computer I'll confirm that everything is working per the rules, then put up the PR.
