### ISSUE TITLE
RFE: BA Cargo Lifters able to define lifting Capacity

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#4833]
Per TM pg 166

Cargo lifter manipulators weigh 30 kilograms each for every half-ton (rounded up) of desired lifting capability

Could we get a way to indicate this during construction and on the BA Record Sheet

**Comment by Saklad5** [comment]
This is implemented, actually. It just can't be done in the GUI yet.

**Comment by Saklad5** [comment]
It does work with record sheets, which is presumably the bit CGL really cares about.
[Guest [Cargo] (Sqd6).pdf](https://github.com/MegaMek/megamek/files/12897431/Guest.Cargo.Sqd6.pdf)
