### ISSUE TITLE
Stefan Amaris class Battleship Entry Typos

### ISSUE THREAD

**Issue by Wpmz** [MegaMek/megamek#4836]
### Environment
MekHQ v0.49.14
Java Vendor: Eclipse Adoptium
Java Version: 11.0.16.1
Windows 10 21h2

### Description
Megameklab lists Stefan Amaris class Battleship as having 0 Docking Hardpoints. Historical Liberation of Terra Volume 2 page 150 says it has 4 Docking Hardpoints and the record sheet found on the very last (unnumbered) page also says 4 Docking Hardpoints. Also the door configuration is wrong. Each fighter/small craft bay should have 2 doors and the Cargo bay should have 4. Also the Cargo is listed as 97,600 tons, which would make this Warship underweight according to Megameklab but that's what the record sheet says.

**Comment by HammerGS** [comment]
I can fix everything except the cargo weight, per our notes on Large craft.

**Comment by HammerGS** [comment]
Currently in the Repo everything matches except cargo, which per our Large Craft isn't something we'll change.
