### ISSUE TITLE
Game cannot progress past report phases / report phase is blank after skipping turns with disconnected clients.

### ISSUE THREAD

**Issue by VictorMorson** [MegaMek/megamek#4847]
### Environment
Windows 10, Megamek 49.15

### Description
I have been encountering an error when progressing through turns with disconnected players via /Skip, that has caused the report phase to semi-softlock the game (requiring saving and reloading to unjam it, often skipping phases).  Once the problem had started, the save later suffered the same issues when all clients were connected.  Also once this error starts, the report itself becomes blank.

### Files
I am including two saves in which this error has occurred, where progress is halted at the progress report.  Sometimes this can be advanced by disconnecting all clients then connecting a client (it seems random each time which one triggers it).

Player names:  OpFor, Atham, Fred, Foster, McCloud, Starlancer, Turrets

There are no crash logs because the game doesn't seem to crash, it just cannot progress further past the blank report.

(Delete the above lines)
[EntirelyBorked.sav.gz](https://github.com/MegaMek/megamek/files/13066378/EntirelyBorked.sav.gz)
[StuckInitativeReport.sav.gz](https://github.com/MegaMek/megamek/files/13066379/StuckInitativeReport.sav.gz)

**Comment by kuronekochomusuke** [comment]
to work around this issue until next release, you can hide the unit tooltip in the report log in game options.   this issue happens when it tries to display an pilot image in the report log, unit tooltip for a killed unit.

![image](https://github.com/MegaMek/megamek/assets/116095479/be8a64fd-054a-4a61-9cd0-19194efab669)
