### ISSUE TITLE
Nimbus Font is White on White for Unit Overview hit information

### ISSUE THREAD

**Issue by VictorMorson** [MegaMek/megamek#4848]
### Environment
Windows 10, 49.15

### Description
The text color is pure white and very light gray on a white backdrop when using the Nimbus theme on the Unit Overview to-hit calculation box.  This seems like it might just be an oversight with font color choices.

### Files
![Nimbus](https://github.com/MegaMek/megamek/assets/17623808/f8784511-7ebb-4388-a7ad-c48b0f467018)

**Comment by neoancient** [comment]
This is a bug in Java: https://bugs.openjdk.org/browse/JDK-8058704
It's fixed in Java 18. I recommend against using Nimbus with earlier version of Java.
