### ISSUE TITLE
Missing phases in round report revolving around an aerospace fighter. Blank round report on save game load.

### ISSUE THREAD

**Issue by Leafback** [MegaMek/megamek#4863]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
Using v 49.15
Windows 10
Java Version: 11.0.16.1

### Description
I have played up to 5-6 rounds of a MegaMek game. 

On round 2, I attempted to use bombs from my aerospace fighter. The fighter rightfully lost 2 altitude, but there was never a report for the bombs themselves.

On round 4, my fighter was hit on the nose. In the round report, you can see the damage applied to it, but at the end there was no pilot rolls. Nor was the heat phase, end phase, nor the new report of showing active units still shown. On round 5, I noticed the fighter was crash landed and the pilot dismounted. I'm assuming that there was a failed pilot roll here, but it wasn't displayed in the round report.

On all the other rounds, pilot rolls, the heat and end phased, and the active unit report were all visible. These were only missing in the round 4 report. 

I was not able to reproduce this issue as the savegame itself appeared bugged. When loading up the save, the round report is completely blank.

In describing my issue on the MM Discord (linked here: https://discord.com/channels/458705327911731231/458706493659807801/1167993751545860156), I snipped a few screenshots. These are the only things I can see from the game at the moment because of the blank round report. 

![image](https://github.com/MegaMek/megamek/assets/105673647/b19d04d4-dcd9-4576-8267-0eab95813b7c)

The above image is the only appearance of the fighter outside of the initiative phase. 

![image-1](https://github.com/MegaMek/megamek/assets/105673647/04a2ad86-0ad9-4ed9-a15c-3e937faa00e3)

The image above is the very bottom of the round 4 report while viewed in the middle of round 5. 

### Files
Player name: Sable Sparrows LLC
[megamek.log](https://github.com/MegaMek/megamek/files/13198940/megamek.log)
[BuggedSabre.sav.gz](https://github.com/MegaMek/megamek/files/13198941/BuggedSabre.sav.gz)
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/13198945/autosave.sav.gz)

I've included the autosave, but I'm not sure if this will help since I stepped through a few phases the next day trying to reproduce.

**Comment by Leafback** [comment]
I just noticed that I still had the notepad opened from when I Ctrl+C/P the round 2 report with the missing bomb attack. I'm not sure of it's worth, but I'm including it just in case. 

[Round 2 Report.txt](https://github.com/MegaMek/megamek/files/13198955/Round.2.Report.txt)

**Comment by kuronekochomusuke** [comment]
This is the same issue as #4850

11:25:45,523 ERROR [megamek.client.Client] {AWT-EventQueue-0}
megamek.client.Client.handlePacket(Client.java:1709) - Failed to parse Packet command SENDING_REPORTS_ALL
java.lang.NullPointerException
	at megamek.client.Client.receiveReport(Client.java:1262)

to work around this issue until next release, you can hide the unit tooltip in the report log in game options.   this issue happens when it tries to display an pilot image in the report log, unit tooltip for a killed unit.  will need to restart the mission for the option change to take effect.

![image](https://github.com/MegaMek/megamek/assets/116095479/be8a64fd-054a-4a61-9cd0-19194efab669)
