### ISSUE TITLE
Error while launching the game: /startup.sh: 25: ./startup.sh: Bad substitution

### ISSUE THREAD

**Issue by MGM175** [MegaMek/megamek#487]
After I've downloaded both 0.43.0 and 0.42.1 (or Dev & Stable respectively), and of course applying:

`chmod +x startup.sh`

on both versions, I'm getting this error:

`./startup.sh: 25: ./startup.sh: Bad substitution
Could not find the MegaMek JAR file.  Exiting.`

Managed to fix this by editing:

`#!/bin/sh`

into

`#!/bin/bash`.

Any chance to apply both 'chmod +x' and '#!/bin/bash' while packaging the new versions?

**Comment by arlith** [comment]
It took way longer to add that execute permission than it should have.  I guess Ant doesn't preserve file permissions, because Java IO doesn't have a way for setting file permissions.  Initially, I noticed a problem when copying the files for packaging (the script has proper permissions in the repo).  But, it also drops permissions when creating the tar file.  There's a magic way in ant to set the permissions, which I ended up using.

**Comment by Dylan-M** [comment]
That's not true at all, it doesn't drop permissions in any way shape or form. It never has. You just have to untar it with the preserve permissions flag. I've always done this, and never had an issue.

**Comment by arlith** [comment]
https://ant.apache.org/manual/Tasks/copy.html
Particularly:

>**Unix Note**: File permissions are not retained when files are copied; they end up with the default UMASK permissions instead. This is caused by the lack of any means to query or set file permissions in the current Java runtimes. If you need a permission-preserving copy function, use <exec executable="cp" ... > instead. 
```

This applies to the `tar` task as well.  I mean, I just tested it.  The `startup.sh` script in the repository is 755.  When it gets copied (for the local packaging), it loses those permissions.  That can be fixed with a `chmod` task, but the permissions are **also** lost in the `tar` task.  It is necessary to explicitly handle permissions for files where permissions are necessary.

**Comment by arlith** [comment]
Perhaps if you use `tar` at the command line you get the proper permissions, but if you use the archive manager tool from the file manager, I did not.  And apparently someone else hasn't either.  This is fixed with the changes I made, so it seems necessary to me.

**Comment by MGM175** [comment]
Sorry for interrupting, but why you're using Windows new-line system instead of the unix one?

`./startup.sh: 25: ./startup.sh: Bad substitution
Could not find the MegaMek JAR file.  Exiting.`

**Comment by arlith** [comment]
I don't see any carriage returns in the version in the repository.  This is likely an issue introduced by packaging the release in windows.  I'll dig into it later when I have time.
