### ISSUE TITLE
C key cannot be used to type in chat while targeting offmap artillery attacks

### ISSUE THREAD

**Issue by Tamren** [MegaMek/megamek#488]
Normally you can open the chat box at any time during a match and type whatever you want. The C key by default is bound to "select next target" but this command is disabled when the chat window is open. However if you are targeting offmap arty like Arrow IV launchers or Long Toms you will be unable to type C in chat during that phase. This does NOT happen when in the non-offmap weapon targeting phase. I tested this on the versions of Megamek bundled with MekHQ 42 and 43, both have the same issue.

This is a very minor bug but it results in at least one problem. If you can't type C in the chat you will be unable to enter the /victory command to end a game. If megamek is set to not check for win conditions this can effectively trap you in a match if you don't know what the problem is. As well as fixing this it would be helpful to take some of the server slash-commands like /victory and add them as buttons on the UI.

**Comment by arlith** [comment]
Looks like an issue copy/pasting code apparently.  Every other hotkey define for the targeting phase display is properly disabled when the chat  box is open, except for next/prev target.
