### ISSUE TITLE
BV of Support PPC likely incorrect

### ISSUE THREAD

**Issue by shopsmartBT** [MegaMek/megamek#4889]
Simple errata to be applied or updated.  Support PPC for battle armor is listed at 12 battle value in MegaMek.  Per the techmanual reprint page 317.  Should be 14.  Older pdfs also list it at 14.  Have tried to looking for errata entries BV and found nothing.

**Comment by HammerGS** [comment]
Fixed as part of https://github.com/MegaMek/megamek/commit/3ae86eb17eeac107d9672edf57d356d9c20f20dd
