### ISSUE TITLE
Option to exempt VTOLs that move "too fast" on low-gravity worlds from taking internal damage.

### ISSUE THREAD

**Issue by Tamren** [MegaMek/megamek#489]
On page 55 of TacOps it describes the rules for movement on low gravity worlds. If a mech or combat vehicle exceeds it's normal running speed it may take internal leg/motive damage. However I discovered that this also applies to VTOLs, which doesn't make any sense. VTOLs do not touch the ground while moving and neither do Aerospace/Conventional Fighters.

Was this ever clarified in a rules errata? If not maybe you could add an unofficial rule to the movement settings that prevents VTOLs from taking movement damage on low gravity worlds.

**Comment by neoancient** [comment]
I checked the errata and rules question on the forums and I find nothing that indicates that this only applies to vehicles in contact with the ground. The rules specifically state that the damage occurs from the suspension systems operating outside the conditions they're designed for, which would not exclude any vehicle type.

**Comment by pheonixstorm** [comment]
Probably best to post a rules question on this.

**Comment by neoancient** [comment]
Lacking any information to the contrary, closing this since it functions according to the rules as written.
