### ISSUE TITLE
49.16 - Beast Infantry - Princess Cannot Move Branth Flying infantry

### ISSUE THREAD

**Issue by Thom293** [MegaMek/megamek#4901]
Tested Beast Infantry.  All of the Land units seem to work, and are extremely fun.  

Princess cannot use the Branth however,  I tried deploying at both altitude 0 and 1, and they just stay in their starting hex.  They will fire their weapons if something approaches.  But she cannot move them for some reason.  Chom tested them under player control and they seemed to work ok (but they did have the jump button for some reason).  But Princess cannot move them.

Sample scenario attached.  Just assign a bot behaviour and hit done and she will play the whole battle.  Screen shows them still in starting hex.
[beasts.sav.gz](https://github.com/MegaMek/megamek/files/13402509/beasts.sav.gz)

![Screenshot (79)](https://github.com/MegaMek/megamek/assets/23645569/337dbbfe-6529-4829-ac0e-cf9409fdad3d)

**Comment by Sleet01** [comment]
It looks like they have the jump button because they only have Jump movement.  I'll compare them with the Sylph BA, which is supposed to have VTOL movement...

**Comment by HammerGS** [comment]
@neoancient Going to assign these to you, but feel free to reassign if needed.
