### ISSUE TITLE
When Firing Ultra AC/10 in "UACs fire twice in ultra mode" It doesn't say HIT when you hit an enemy unit

### ISSUE THREAD

**Issue by demster42** [MegaMek/megamek#4904]
### Environment
MegaMek 49.15
Window 11
MegaMek.java:118

### Description
When firing a Ultra AC/10 in "UACs fire twice in ultra mode" It doesn't say HIT when you hit an enemy unit

**Comment by HammerGS** [comment]
Is this on the first shot or second shot. Can you post a screenshot

**Comment by neoancient** [comment]
I don't see a problem.
![Screenshot from 2023-12-05 10-49-47](https://github.com/MegaMek/megamek/assets/16927464/b83ff0ce-bfa1-4351-a043-f1b670b5a5cb)

**Comment by HammerGS** [comment]
Based on the discord conversation when using the Ultra Fire twice with each getting a roll. It’s only showing one roll.

**Comment by HammerGS** [comment]
I’m on my phone and can’t test or post screen shoots confirming this.

**Comment by RaozSpaz** [comment]
![image](https://github.com/MegaMek/megamek/assets/132851640/5b5c4570-fe19-42ef-be2f-05fec35a9b92)

I got home a little early and was able to do this in a quick test. The Ultra doesn't have the Hit result after either hit. 

![image](https://github.com/MegaMek/megamek/assets/132851640/34a9fa82-17db-4db2-8487-7a89a8aa41a1)

It does still show misses and also shows Glancing hits from Quirks.

![image](https://github.com/MegaMek/megamek/assets/132851640/b9d7ce77-f0e3-4c4b-a9e4-902ccd8f4f74)

And just to show its not a general 'lack of hits' bug, there are two MLs still showing their hit result.

**Comment by neoancient** [comment]
Once I found the problem I realized this would also happen in single mode regardless of the fire-twice option.
