### ISSUE TITLE
Incorrect iNarc ammo BV?

### ISSUE THREAD

**Issue by IanBellomy** [MegaMek/megamek#4905]
In MM iNarc ammo bv is 15. 
In TM it is 0. 
The BV for OS iNarc launchers _is_ 15 though... 🤔

**Comment by HammerGS** [comment]
What version? Looking at 49.15 I see the iNarc Launcher are 75, the OS is 15 and all ammo's are 0.

**Comment by IanBellomy** [comment]
(Lays down) 
Apologies, I was looking at the -15bv per slot discount for having explosive ammo on board. Sorry for the noise!
