### ISSUE TITLE
Megamek tacops ammo BV error

### ISSUE THREAD

**Issue by DevianID** [MegaMek/megamek#4933]
Howdy all.  So this probably was mentioned before, but I didnt see any current threads with ammo BV.

In Tac Ops::AUE (pg 198), weapons with a BV adjustment are listed as +100% bv, such as on Acid, or +20% bv on Swarm I.  Instead of adding this % to ammo, increasing the BV of a unit, megamek is multiplying the ammo BV by this value.  Thus, swapping to and from acid costs the same bv, while swapping to the +20% bv swarm-I lowers the BV of the mech by 80% of the ammo bv, instead of increasing it by 20%.

![image](https://github.com/MegaMek/megamek/assets/73900413/44a78905-8764-4568-baa4-fdfebe2defdd)

**Comment by HammerGS** [comment]
What version of MegaMek.

**Comment by DevianID** [comment]
49.15 and 48 and presuming the versions in between

**Comment by HammerGS** [comment]
I'm not sure what I'm missing here. Here is a Archer with a normal loadout. 

<HTML><BODY><TABLE CELLPADDING=0 CELLSPACING=0 BORDER=0><TR><TD COLSPAN=6><FONT SIZE=+2><U>Battle Value Calculation for Archer ARC-2S</U></FONT></TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD></TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD></TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT></TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>Effective MP:</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>R: 6, J: 0, U: 0</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT></TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD></TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD></TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT></TD></TR><TR><TD COLSPAN=6>Defensive Battle Rating:</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>Armor:</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>208 x 2.5</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 520</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>Internal Structure:</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>+ 107 x 1.5</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 680.5</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>Gyro:</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>+ 70 x 0.5</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 715.5</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>Explosive Equipment:</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD></TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT></TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- LRM 15 Ammo</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>- 15</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 700.5</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- LRM 15 Ammo</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>- 15</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 685.5</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- SRM 4 Ammo</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>- 15</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 670.5</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- LRM 15 Ammo</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>- 15</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 655.5</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- LRM 15 Ammo</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>- 15</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 640.5</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- SRM 4 Ammo</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>- 15</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 625.5</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>TMMs:</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>2 (R), 0 (J), 0 (U)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT></TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>Defensive Factor:</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>625.5 x 1.2</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 750.6</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD></TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD></TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT></TD></TR><TR><TD COLSPAN=6>Offensive Battle Rating:</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>Weapons:</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD></TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT></TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>Heat Efficiency:</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>6 + 10 - 2 (Run) = 14</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT></TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- LRM 15 (LT)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>+ 136 (Heat: 5)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 136</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- LRM 15 (RT)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>+ 136 (Heat: 10)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 272</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- Medium Laser (LA)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>+ 46 (Heat: 13)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 318</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- Medium Laser (RA)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>+ 46 (Heat: 16)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 364</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- SRM 4 (LT)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>+ 39 x 0.5 (Overheat)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 383.5</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- SRM 4 (RT)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>+ 39 x 0.5 (Overheat)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 403</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- Medium Laser (CT) (R)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>+ 46 x 0.5 (R) x 0.5 (Overheat)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 414.5</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- Medium Laser (CT) (R)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>+ 46 x 0.5 (R) x 0.5 (Overheat)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 426</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>Ammo:</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD></TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT></TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- LRM 15 Ammo</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>+ 68</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 494</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- SRM 4 Ammo</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>+ 10</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 504</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>Weight:</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>+ 70</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 574</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>Speed Factor:</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>574 x 1.12</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 642.88</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD></TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD></TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT></TD></TR><TR><TD COLSPAN=6>Battle Value:</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>--- Base Unit BV:</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>750.6 + 642.88, rn</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 1393</TD></TR></TABLE></BODY></HTML>

### Here is the Archer with one ton of Acid and Swarm-I

<HTML><BODY><TABLE CELLPADDING=0 CELLSPACING=0 BORDER=0><TR><TD COLSPAN=6><FONT SIZE=+2><U>Battle Value Calculation for Archer ARC-2S</U></FONT></TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD></TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD></TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT></TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>Effective MP:</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>R: 6, J: 0, U: 0</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT></TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD></TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD></TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT></TD></TR><TR><TD COLSPAN=6>Defensive Battle Rating:</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>Armor:</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>208 x 2.5</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 520</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>Internal Structure:</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>+ 107 x 1.5</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 680.5</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>Gyro:</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>+ 70 x 0.5</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 715.5</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>Explosive Equipment:</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD></TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT></TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- LRM 15 Swarm-I Ammo</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>- 15</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 700.5</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- LRM 15 Ammo</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>- 15</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 685.5</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- SRM 4 Acid Ammo</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>- 15</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 670.5</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- LRM 15 Ammo</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>- 15</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 655.5</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- LRM 15 Ammo</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>- 15</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 640.5</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- SRM 4 Ammo</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>- 15</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 625.5</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>TMMs:</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>2 (R), 0 (J), 0 (U)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT></TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>Defensive Factor:</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>625.5 x 1.2</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 750.6</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD></TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD></TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT></TD></TR><TR><TD COLSPAN=6>Offensive Battle Rating:</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>Weapons:</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD></TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT></TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>Heat Efficiency:</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>6 + 10 - 2 (Run) = 14</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT></TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- LRM 15 (LT)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>+ 136 (Heat: 5)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 136</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- LRM 15 (RT)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>+ 136 (Heat: 10)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 272</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- Medium Laser (LA)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>+ 46 (Heat: 13)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 318</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- Medium Laser (RA)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>+ 46 (Heat: 16)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 364</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- SRM 4 (LT)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>+ 39 x 0.5 (Overheat)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 383.5</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- SRM 4 (RT)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>+ 39 x 0.5 (Overheat)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 403</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- Medium Laser (CT) (R)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>+ 46 x 0.5 (R) x 0.5 (Overheat)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 414.5</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- Medium Laser (CT) (R)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>+ 46 x 0.5 (R) x 0.5 (Overheat)</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 426</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>Ammo:</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD></TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT></TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- LRM 15 Swarm-I Ammo</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>+ 54.4</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 480.4</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>- SRM 4 Acid Ammo</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>+ 10</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 490.4</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>Weight:</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>+ 70</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 560.4</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>Speed Factor:</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>560.4 x 1.12</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 627.648</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD></TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD></TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT></TD></TR><TR><TD COLSPAN=6>Battle Value:</TD></TR><TR><TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD></TD><TD>--- Base Unit BV:</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>750.6 + 627.648, rn</TD><TD>&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD ALIGN=RIGHT>= 1378</TD></TR></TABLE></BODY></HTML>

**Comment by HammerGS** [comment]
Ok, chatted with the CGL BV guru. I can confirm we are doing it wrong. The key wording is "multiplier... Additional base BV" everything on the table above should be 1 + table value. The table in TO is different than the traditional approach which is to show the total multiplier. 

I'll take a crack at a fix.

**Comment by HammerGS** [comment]
CGL has issued some clarify errata on this. 
https://bg.battletech.com/forums/index.php/topic,70413.msg1980376.html#msg1980376

So far my fixes aren't working as certain ammo types (Tandem Charge) aren't being captured in the calculation.

**Comment by HammerGS** [comment]
Both Dead fire and LK have the BV for ammo based on the launcher size. Still need fixes for those,

Pg IntOps:Alternate Eras - pg 189 and 190 for values.

**Comment by HammerGS** [comment]
Also https://github.com/MegaMek/megamek/commit/f0f1518755984fb2531a7f84e153a570b3b7f5f9
