### ISSUE TITLE
pfarland Princess Tweaks princessBehaviors.xml

### ISSUE THREAD

**Issue by xStormforgex** [MegaMek/megamek#494]
Modified princessBehaviors.xml attached with new behaviors added on after the default behavior. Nothing is overwritten.

[pPT.zip](https://github.com/MegaMek/megamek/files/801806/pPT.zip)

**Comment by HammerGS** [comment]
I'll arrange to get this added.  Thanks.

**Comment by HammerGS** [comment]
Added in https://github.com/MegaMek/megamek/commit/6fb458b46fa5d66d0c2fe2258850dfa8c6bd49c4
