### ISSUE TITLE
Unit Summary shows an empty ammo block for some units (minor UI issue)

### ISSUE THREAD

**Issue by SJuliez** [MegaMek/megamek#4941]
49.15:
With the Crossbow T, an empty ammo block shows up. I guess it's because it only has one-shot weapons.

![image](https://github.com/MegaMek/megamek/assets/17069663/9481028b-8a4f-4bb2-b7f1-81d3bee3d022)

**Comment by HoneySkull** [comment]
I think this is technically correct - the one-shot SRMs are ammo-based weapons, but there are no ammo bins.   A unit with only energy weapons will not have the ammo block - but I feel like this is okay.
