### ISSUE TITLE
[0.43] problem with loading ssw files

### ISSUE THREAD

**Issue by seem8** [MegaMek/megamek#495]
My friend have a problem with his 'Mechs, created with Solars Skunk Werks. They are loading fine on 0.42.
[megameklog.txt](https://github.com/MegaMek/megamek/files/802293/megameklog.txt)

**Comment by neoancient** [comment]
It would be helpful to have a sample ssw file for testing. You will probably have to zip it or otherwise archive it for Github to accept it as an attachment.

**Comment by HammerGS** [comment]
Are you trying to load the ssw files? or have you exported them to MTF files (under the Fluff tab).

We don't support the loading of the ssw files.  If they are MTF files we would need samples of those files.

But I will caution you, SSW stopped development in 2014 and as the development of MegaMek continues its likely that compatibility issues could continue to develop between the two programs.

**Comment by seem8** [comment]
Of course. Thanks for a fast reply.
[ssw_files.zip](https://github.com/MegaMek/megamek/files/802327/ssw_files.zip)

**Comment by HammerGS** [comment]
Trying removing the .ssw files from the zip as well as the .saw file.  When I remove those files and try to load the attached zip I have no errors and the first units appear in the unit selector.

![image](https://cloud.githubusercontent.com/assets/13752452/23344237/03cef680-fc36-11e6-9ccd-25e15cb65d09.png)

**Comment by seem8** [comment]
Thank you.
