### ISSUE TITLE
[0.49.16-SNAPSHOT] Unit Loading Failures - Von Luckner Heavy Tank VNL-K65W

### ISSUE THREAD

**Issue by HoneySkull** [MegaMek/megamek#4962]
### Environment
Starting MegaMek v0.49.16-SNAPSHOT
	Build Date: 2023-12-16T01:10:46.304979900
	Today: 2023-12-16
	Origin Project: MegaMek
	Java Vendor: Eclipse Adoptium
	Java Version: 11.0.20.1
	Platform: Windows 11 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 2 GB

### Description
When starting a new game or refreshing the unit cache, the following "Unit Loading Failures" window pops up displaying an error loading the Von Luckner Heavy Tank.  

![image](https://github.com/MegaMek/megamek/assets/83041327/ff5df93c-5a8b-42f2-b9fd-1b8ff3bfede3)

![image](https://github.com/MegaMek/megamek/assets/83041327/60a6eb58-7bd5-411c-a321-778ef8a16f23)

**Comment by HoneySkull** [comment]
![image](https://github.com/MegaMek/megamek/assets/83041327/bfe424c7-68a6-4f78-b614-c8cf5f3f3bb9)

**Comment by HammerGS** [comment]
Should be fixed now.

**Comment by HoneySkull** [comment]
Confirmed.
