### ISSUE TITLE
[0.49.15] Merkava Mk VII Record Sheet lists BAR 9 armor - errata is BAR 7

### ISSUE THREAD

**Issue by dxz6228** [MegaMek/megamek#4979]
### Environment
Running Megamek 0.49.15.
Java version is 11.0.19, from Oracle.
Running on Windows.

### Description
Merkava Mk. VII in MegaMekLab erroneously has BAR 9 armor; errata'd record sheet [from this thread](https://bg.battletech.com/forums/index.php/topic,5938.0.html), available [here](https://www.dropbox.com/s/716xffasvpi365f/Merkava%20Mk%20VII%20-%20Errata%20Sheet.pdf?dl=0), lists BAR 7 armor. Turret armor in MML is also 2 points lower.

### Files
[Merkava Heavy Tank Mk VII mml.pdf](https://github.com/MegaMek/megameklab/files/13415747/Merkava.Heavy.Tank.Mk.VII.mml.pdf)
[Merkava Mk VII - Errata Sheet.pdf](https://github.com/MegaMek/megameklab/files/13415749/Merkava.Mk.VII.-.Errata.Sheet.pdf)

**Comment by pheonixstorm** [comment]
@HammerGS The commit still has the Merkava with BAR 9 instead of BAR 7
