### ISSUE TITLE
RFE: Princess should skip all and just press done with Forced Victory

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/megamek#5]
Rather than calculate moves or firing or physicals, etc. Princess should just hit DONE when forced victory occurs.

**Comment by Dylan-M** [comment]
Perhaps. But this isn't always true with players either. Perhaps a better thing would be to have skip-all IF skip-all phases option is turned on.

**Comment by scJazz2** [comment]
There are some edge cases regarding artillery and other stuff that your suggestion works better.

**Comment by arlith** [comment]
This is a duplicate of [feature #1414](https://sourceforge.net/p/megamek/feature-requests/1414/) on the SF tracker.  My suggestion there would be to have this be a behavior setting for the bot.
