### ISSUE TITLE
[Feature Request] Loan Unit or "Owned By" flag

### ISSUE THREAD

**Issue by GraalOtonami** [MegaMek/megamek#502]
Adding the ability to loan control of mechs to other players and have control returned at the end of the game would give the ability for a GM to have records of all mechs in play, and would allow them to use MekHQ to play Op4 while players use the mechs of the actual unit and still keep a unified list of parts/personnel available on one program.

**Comment by neoancient** [comment]
Please post MekHQ issues on the MekHQ issue tracker: https://github.com/MegaMek/mekhq/issues
