### ISSUE TITLE
[J17 - 49.18 Nightly] - Double Click Player Settings Window is Sticky, potentially forcing hard close.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/megamek#5026]
18:18:36,243 INFO  [megamek.MegaMek] {main}
megamek.MegaMek.initializeLogging(MegaMek.java:118) - Starting MegaMek v0.49.18-SNAPSHOT
	Build Date: 2024-01-07T01:17:28.662841800
	Today: 2024-01-07
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.7
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 8 GB

Will post a couple of screens, but if you double click on a force on the left, it will open the player settings window.  If you then click bot settings at top, the bot settings dialogue appears behind the player settings window, but if you click on it, it will not promote to the front.  This is new behaviour.    I think its a potential serious issue because if the player cant reach the "cancel" button on the bot settings pop-up, behind the player settings window, if will require a hard shutdown to regain control of the program, because you cant click anything else until you deal with the bot settings window.

Screens:

![image](https://github.com/MegaMek/megamek/assets/23645569/752591bd-cf79-4dfb-b4ee-6a61f48c2af2)
 
It is so sticky it stays on top of every window on your machine.

![image](https://github.com/MegaMek/megamek/assets/23645569/4c78d58e-7d3f-4b9e-b663-a5f73d57bb6a)

in 49.16, it did not do this:

![image](https://github.com/MegaMek/megamek/assets/23645569/59829c2e-5862-4334-945c-937b4068397c)

Save:

[Sticky.sav.gz](https://github.com/MegaMek/megamek/files/13864290/Sticky.sav.gz)

**Comment by HoneySkull** [comment]
This is the commit that introduced this behavior.  I located it using `git bisect`.   

![image](https://github.com/MegaMek/megamek/assets/83041327/e109a426-7ee8-4906-a1b6-8a76294d9b81)

ab56dc63ccbbd43836fa4173e72d49a49fe10826

**Comment by HoneySkull** [comment]
I find that if you keep double clicking on the player - multiple modal player setting dialogs will also pop up at the same time.

**Comment by Thom293** [comment]
I did learn that you can grab the top of the bot settings window and move it until you can see the button, so there is a workaround for a hard-close.  But that was not apparant to me until I messed with it mutlitple times.

**Comment by HoneySkull** [comment]
![image](https://github.com/MegaMek/megamek/assets/83041327/636edbc6-ba23-4805-b557-7cc75e6a0e9d)

I think this is it.

**Comment by HoneySkull** [comment]
> I did learn that you can grab the top of the bot settings window and move it until you can see the button, so there is a workaround for a hard-close. But that was not apparant to me until I messed with it mutlitple times.

It's possible to get a smaller pop-up window behind the player config window that's modal that you can't move.  I think it was the pop-up saying "Do you want to read this Princess stuff?".
