### ISSUE TITLE
BUG: Field artillery lost all ammo

### ISSUE THREAD

**Issue by ThomasMarik** [MegaMek/megamek#505]
I recently did a battle with the mechanized field artillery.  It comes with 20 ammo and I only fired 9 shots during the match.   When it was returned it said it was completely out of ammo.  I had deployed it off board.

The following are the muls I saved after the battle and the gamesave itself from Megamek.  I can make the mekHQ save available as well if needed.

[Artillary problem.zip](https://github.com/MegaMek/megamek/files/833534/Artillary.problem.zip)

[artillary.sav.gz](https://github.com/MegaMek/megamek/files/833526/artillary.sav.gz)

**Comment by neoancient** [comment]
The mul file shows 12 shots remaining, so it looks like the problem is in the MHQ resolution.

**Comment by neoancient** [comment]
No problem found here.
