### ISSUE TITLE
Image atlas map has cross-platform issues

### ISSUE THREAD

**Issue by arlith** [MegaMek/megamek#507]
We end up using `File.toString` to generate path strings for files, both to get written into the atlas map xml and to compare to entries written in the xml file.  This causes problems when the map is written in one OS and then utilized in another.  Since we are comparing path strings, if different path separators are used, mismatches will occur.

For instance, when we package a release in Linux, and a window user tries to run it, none of the image files match, because the windows paths use `\` and the paths written in the atlas xml use `/`.

**Comment by pheonixstorm** [comment]
With Vega Strike the paths are written with / in a lot of places but we never had any complaints about things not working under windows and most of the devs there were using Linux. Is this OS related or language related? VS is mostly C++ and Python is why I ask and is sometimes cross compiled off a linux machine. Just trying to understand why it works for one app and not the other.

**Comment by arlith** [comment]
The problem is string comparison.  Java IO is able to accept paths in any OS's format and know what to do with it.  The problem is, we are writing path *strings* to files and then using `java.io.File` to take a path and convert it to a string and compare those strings.  Unfortunately, there's no way (without writing custom code) to change how `java.io.File` outputs the path string.  We could write code to ensure this, but I'm not very keen on that, because it can be error prone (aka, if the programmer doesn't know about the special code and doesn't use it, the problem can crop up again).

I think the solution I will go with is to have some additional code in `ImageUtils.TileMapImageLoader` that checks to see if the client OS is windows, and if so it will find/replace all `\` with `/'.  I think this is an acceptable solution, however it has the problems of requiring that the image atlas xml map is *also* always formatted with UNIX style slashes, which is an additional thing I will need to add.

**Comment by Dylan-M** [comment]
@arlith Are you sure isn't it possible to set the path separator for the output of File? I swear I've seen that elsewhere...

**Comment by Dylan-M** [comment]
In fact, check out:
https://docs.oracle.com/javase/tutorial/essential/io/pathOps.html

**Comment by arlith** [comment]
The first entry in the first table describes precisely the problem we are having.  Both `Path.toString` and `File.toString` return an OS-specific path string.  So, if we generate path strings in Linux, and then compare them to path strings generated in Windows, they are wrong.

Yes, we could use `Path` to iterate over the path elements and generate our own path string.  The problem is, this means we can't pass just any old string into `ImageUtils.loadImage`, instead we need to pass a specially generated string, which is error prone.  I'm not comfortable passing in `File`, because for the image atlas and other tiled images, we path in a string that includes the path along with location within the atlas.  We could encapsulate this data in our own class, but that also adds complexity.

I guess we could load the atlas as a `Map<Path, String>` instead of as a `Map<String, String>`.

**Comment by arlith** [comment]
I had been reluctant to use a `File` in the past, but I guess I could also just use a `File` for the image atlas map.  It looks like a `File` instance isn't much more memory overhead compared to a `String` and for serialization it's hardly much more.  The only downside is we have to construct a new `File` instance every time an image is loaded.  It's not a huge deal, but it is some overhead.

**Comment by arlith** [comment]
Ironically, `File` is actually more efficient to serialize with `XStream` than `String`.  For example:

```
  <entry>
    <file>data/images/units/unused/units_original/mechs/wotan_A_original.gif</file>
    <string>data/images/units/unused/units_original/mechs/mechs_atlas.png(336,14832-84,72)</string>
  </entry>
```

**Comment by arlith** [comment]
Fixed by using a `Map<File, String>` instead.

**Comment by Dylan-M** [comment]
Actually for Path, I was suggesting that you read the strings from the Atlas into Path.get(String), which will take the String of a UNIX path and return the correct Path for the OS it's running on. At least, that's how I read it originally.

I may be wrong in that upon re-reading, however you can pass it a UNIX path string, and then iterate over the path elements and rebuild it as a Windows path if the conversion isn't automatic.

Also, per StackOverflow, using the UNIX path should work just fine:
A "/path/to/some/file" actually works under Windows Vista and XP.
new java.io.File("/path/to/some/file").getAbsoluteFile()
> C:\path\to\some\file

Source:
http://stackoverflow.com/a/1697362

Still, if your current solution really is better, I'm fine with it ;)
