### ISSUE TITLE
49.17 not all quirks are available for combat/support vehicles

### ISSUE THREAD

**Issue by servo01** [MegaMek/megamek#5073]
49.17

List of available quirks for vehicles is missing several quirks that are available when working with other unit types.
![quirks](https://github.com/MegaMek/megameklab/assets/30708294/7711a5ac-2dc7-4cd2-9ea3-55439ca9af8d)

**Comment by HammerGS** [comment]
I'll find some time to review the quirks against the canon list in Campaign Ops.
