### ISSUE TITLE
[0.49.17] BA LB-X should get flak bonus against airborne targets.

### ISSUE THREAD

**Issue by stonewall072** [MegaMek/megamek#5078]
According to the table on page 224 of _Tactical Operations: Advanced Units and Equipment_ BA LB-X has the "F" weapon type, denoting that it can make a flak attack against airborne targets. Currently MegaMek does not apply the flak bonus when using BA LB-X against airborne targets, instead only giving the -1 cluster bonus.

![Screenshot 2024-01-23 163305](https://github.com/MegaMek/megamek/assets/8825923/6622ddcf-2770-4970-8d53-67a207f2ba63)

**Comment by Sleet01** [comment]
@stonewall072 Can you confirm if the subsequent combat report shows the same calculation in its mouse-over for that roll?

There are two possibilities:
1) only the To Hit projection box is missing the Flak modifier;
2) both the To Hit projection box _and_ the actual calculation are missing the Flak modifier.

Neither should be very difficult to fix, but it would be good to confirm.

**Comment by stonewall072** [comment]
Looks like it's the actual calculation.

![Screenshot 2024-01-23 172636](https://github.com/MegaMek/megamek/assets/8825923/f1d2451a-0e03-4fad-b41a-a7899008a9cf)

**Comment by Sleet01** [comment]
@stonewall072 Awesome, thanks!  I think I see the issue; it looks like BA LBX is not technically treated as LBX in the code, just sort of special-cased to act similar.  I'll review the rules and see if that can be cleaned up.

**Comment by Sleet01** [comment]
Also BA LB-X attacks don't appear to be getting their automatic max cluster size when Swarming the target, I'll add that.

**Comment by Sleet01** [comment]
There's an additional wrinkle: as Infantry, BAs can't shoot at Aerospace except with dedicated AA weapons, which the BA LB-X does not count as: https://bg.battletech.com/forums/index.php?topic=43797.0

While I don't think this will change how we want to resolve this issue, it may require some extra checks to ensure that BA LB-X gets Flak vs VTOLs and WiGEs, but can't attack actual Aerospace in flight.
