### ISSUE TITLE
Cannot Configure LAM in the MM Lobby

### ISSUE THREAD

**Issue by BairdEC** [MegaMek/megamek#5085]
### Environment
0.49.17
Win10
Java Version: 11.0.11

### Description
In the MegaMek lobby, I tried to configure a LAM, but I received the error below.  I was able to configure the other units without error.
The last lines of megamek.log are several instances of "20:25:32,882 ERROR [megamek.client.bot.princess.Precognition] {AWT-EventQueue-0}
megamek.client.bot.princess.Precognition.handlePacket(Precognition.java:271) - Attempted to parse unknown PacketCommand of ENTITY_MULTIUPDATE".

![LAM Config](https://github.com/MegaMek/megamek/assets/38081112/ccfe9424-27d5-4b7e-908e-d81a888785ce)

### Files
[megamek.log](https://github.com/MegaMek/megamek/files/14046476/megamek.log)

[Autosave-1-Metal Mayhem-30280321.cpnx.gz](https://github.com/MegaMek/megamek/files/14046486/Autosave-1-Metal.Mayhem-30280321.cpnx.gz)
No customs meks in this campaign yet.

[lamconfig.sav.gz](https://github.com/MegaMek/megamek/files/14046483/lamconfig.sav.gz)

[Autosave-1-Metal Mayhem-30280321.cpnx.gz](https://github.com/MegaMek/megamek/files/14046486/Autosave-1-Metal.Mayhem-30280321.cpnx.gz)

**Comment by kuronekochomusuke** [comment]
A fix for this is in the next release

#5004
#5005
