### ISSUE TITLE
[0.49.17] Acid SRMs doing incorrect damage against units with ferro-lamellor armor.

### ISSUE THREAD

**Issue by stonewall072** [MegaMek/megamek#5086]
Rules for AX SRMs on page 179 of _Tactical Operations: Advanced Units and Equipment_ state that "AX SRMs inflict a base 3 points of damage per missile against units using any form of Ferro-Fibrous, Ferro-Lamellor, Laser-Reflective or Reactive
armor, as well as any unit that has a BAR value of 5 or less. **(This damage is not reduced by special armor rules.)**"

However, in MegaMek, the ferro-lamellor damage reduction is being applied, with attacks by acid warheads only doing two points of damage.

![Screenshot 2024-01-25 183558](https://github.com/MegaMek/megamek/assets/8825923/8011b45b-e994-4658-b313-865b87942d79)

**Comment by stonewall072** [comment]
Just a note on this: after reviewing the errata documents, this appears to have been a change from the combined TacOps volume which allowed specialty armors to reduce AX damage to the split volume with the current wording and should also be tagged as errata.

**Comment by Xotl-IIC** [comment]
For what it's worth, this change is recorded in the single-volume TO errata (v3.03): it was made in the third and final "printing" of that book (which never saw a physical release).  That is why the change does not appear in the split-volume errata: those documents do not record anything changed during the original print run.
