### ISSUE TITLE
Oblique Attacker and artillery

### ISSUE THREAD

**Issue by TigerShark** [MegaMek/megamek#509]
Although this ruling is re.: Alpha Strike, I would say it also affects Classic BT rules:
http://bg.battletech.com/forums/index.php?topic=56166.0;topicseen

i.e.: Oblique Attacker should give the direct fire arty shots a bonus as well.

**Comment by pheonixstorm** [comment]
Oblique Artilleryman doesn't give any tohit modifiers in CamOps so that would be a big difference ther.

Oblique Attacker is also rather specific about its modifier. If you can get a ruling for CamOps SPAs similar to that of AS then I see no reason why it couldn't be changed for Oblique Attacker.

**Comment by arlith** [comment]
The CO rules are quite specific (pg 78) that Oblique Attacker only applies to indirect fire.  Here's the text:

> In addition to receiving a –1 To-Hit Modifier to their attack when firing indirectly...

I'm going to need a ruling specific to TW-scale in order to change this.
