### ISSUE TITLE
Can't change game year from options search

### ISSUE THREAD

**Issue by KaiserFalk** [MegaMek/megamek#5090]
### Environment
Standalone MM, did not test with mekHQ version
Windows 10
Java 11

### Description
Game year does not change when filled in from options search, have to do it from "Allowed Units and Equipment" tab. Reproduced on both 49.15 and 49.17, Mishra had it happen as well

### Files
![image](https://github.com/MegaMek/megamek/assets/11843379/14c398c9-8a50-403f-a536-78b14439731d)

**Comment by Sleet01** [comment]
Please be certain that this is not a password-protected server, or that the password was properly set at the bottom of the Server Options dialog.  I've noticed similar behavior when the password was not input or was incorrect.
Another indicator is if you can't change the year directly, but you _can_ change it by:

1. Updating the field,
2. Saving the server settings to a file,
3. Loading the file.

**Comment by repligator** [comment]
It looks likes this extends to other text based options such as 'How Many CF will burn down' as well.

**Comment by SJuliez** [comment]
Fixed.
