### ISSUE TITLE
[HQ49.17] The Sprinting advanced movement rule is causing unexpected benefits when under low gravity planetary conditions.

### ISSUE THREAD

**Issue by Nehvar** [MegaMek/megamek#5093]
If you play under low gravity settings with Sprinting enabled, MegaMek is currently allowing you to use extra low-grav running MP's up to your normal-grav sprinting MPs without a PSR.

To better explain:  my current campaign is on a planet with 0.7G and my entire force is made up of 4/6 'mechs which become a pseudo-6/9 under those conditions.  Normally I'd have to pass a PSR to avoid leg damage whenever I exceed my normal-grav maximum running movement of 6 MPs.  However, I have consistently been able to spend up to 8 running MP's without a PSR while Sprinting is enabled.

With both Sprinting and low-grav advanced rules in effect, if I'm reading TacOps correctly, my 4/6 'mechs should be 6/9 with a maximum safe "running" MP's of 6 and a maximum safe sprinting MP's of 8.  Running for 8 MP's, even though it is safe to sprint that distance, should be requiring a PSR to avoid leg damage.

There really is no point to a screenshot for this one.  Nothing to show.

**Comment by gsparks3** [comment]
This is correct behavior; the "safe" movement speed is whatever your maximum safe movement speed would be in 1g under the rules currently in use, so having Sprinting active increases the maximum MP you can use before needing to make a PSR to avoid damage. See the rules forums: https://bg.battletech.com/forums/index.php/topic,71766

With sufficiently low gravity, you can _walk_ as fast as you would sprint in 1g, with no issues.

**Comment by Nehvar** [comment]
"When Sprinting in lower gravity (see p. 53), the maximum safe speed remains twice walking speed."

That statement seems like it applies only when using sprinting movement though.  Wouldn't walking/running units still have the maximum safe speed described on p.53?

I failed to mention it above but my 'mechs are not sprinting.

**Comment by gsparks3** [comment]
Honestly, the forum ruling is a bit unclear and could maybe use another question thread asking for clarification. I don't think the actual movement mode declared affects anything - given sufficiently low gravity, you can exceed your normal running (or even sprinting) MP while walking, and would presumably still have to make a PSR to avoid damage from excessive speed.
