### ISSUE TITLE
RFE: Infantry Improvements to Advanced Search

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#5096]
With the recent addition of Anti-Mek gear would it be possible to add two things to the equipment search:

Ability to search for AM Gear
Ability to search for Specific Infantry armor

**Comment by kuronekochomusuke** [comment]
this looks to be already there

![image](https://github.com/MegaMek/megamek/assets/116095479/166139eb-04c3-4912-b64d-859d856885a1)
