### ISSUE TITLE
Archer 2K skin issue

### ISSUE THREAD

**Issue by PeterRomulus** [MegaMek/megamek#5098]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
MegaMek 0.48.0
HQ's MegaMek.
Windows, 
No skin for Archer 2k
![image](https://github.com/MegaMek/megamek/assets/158086280/9d497090-5846-48d5-a46c-a34e3b2c74e7)
compare with 2r
![image](https://github.com/MegaMek/megamek/assets/158086280/ea21e102-5a6a-4ca3-b60f-48fb95de9fba)

Just a silly one 

Peter

**Comment by HammerGS** [comment]
Fixed in the latest releases.
