### ISSUE TITLE
Missing i18n entry: BoardView1.

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/megamek#51]
The title is all I get in the log. I am attaching the savegame as well as the log. To reproduce.. well, I attacked some tanks with inferno bombs and the title shows up in the log as well as floating above the tanks after the weapons phase is resolved. Could be related to one of the new pulls as I have need recieved this report before
[savegames.zip](https://github.com/MegaMek/megamek/files/154188/savegames.zip)

![boardview](https://cloud.githubusercontent.com/assets/1787879/13452035/36d75496-e012-11e5-8b45-b224e7433535.png)

**Comment by pheonixstorm** [comment]
It popped up on another vehicle that was attacked. Appears to be from a Crew Stunned crit.

**Comment by arlith** [comment]
Fixed in 237f1f4
