### ISSUE TITLE
[0.49.17] To-hit calculation bugs re dusk/dawn searchlights and TacOps BAP option

### ISSUE THREAD

**Issue by Gribbly1** [MegaMek/megamek#5103]
Bundled Megamek with MekHQ 0.49.17
Windows 10, Java Version: 11.0.13

Searchlights should not counteract to hit penalties for dusk/dawn. Units without BAP should not have reduced TN vs units in woods. This WHM-6R does not actually have BAP.

Player name: test

[save1.sav.gz](https://github.com/MegaMek/megamek/files/14104770/save1.sav.gz)

![image](https://github.com/MegaMek/megamek/assets/55139229/c6ec8aa6-ee04-4ca1-90af-5ae0badc922a)

**Comment by kuronekochomusuke** [comment]
similar BAP issues
#5072
#5030

**Comment by RaozSpaz** [comment]
![image](https://github.com/MegaMek/megamek/assets/132851640/7923a7a7-5b55-4205-b68f-0cf1138649b2)
So just to be certain I went in and turned off the BAP TOps rule and still got the modifier. Also it does effect enemies too
![image](https://github.com/MegaMek/megamek/assets/132851640/88188c98-1b70-4409-8a25-069443af1020)
