### ISSUE TITLE
[0.49.17] To-hit calculation bug when shooting at VTOLs

### ISSUE THREAD

**Issue by Gribbly1** [MegaMek/megamek#5104]
Bundled Megamek with MekHQ 0.49.17
Windows 10, Java Version: 11.0.13

Player name: test
[save2.sav.gz](https://github.com/MegaMek/megamek/files/14105076/save2.sav.gz)

To hit calculation isn't including the +1 from target expending VTOL MP's.

![image](https://github.com/MegaMek/megamek/assets/55139229/8a6a4ce3-46e5-4e74-8e1e-e5de98050174)

**Comment by RaozSpaz** [comment]
Can confirm.
![image](https://github.com/MegaMek/megamek/assets/132851640/2d7d9844-3d7b-4220-a20a-bed7aebb15e8)

![image](https://github.com/MegaMek/megamek/assets/132851640/d6044ad1-b750-4f9c-8ddc-847f29ca3848)

**Comment by Sleet01** [comment]
I've been poking around in there, might have broken something.  I'll take a look.

**Comment by Sleet01** [comment]
Yep, it me.  Made a logic bug in the check for jumping _or_ VTOL (but supposedly not both).  PR incoming.
