### ISSUE TITLE
Allow editing pilot hits in the lobby

### ISSUE THREAD

**Issue by SJuliez** [MegaMek/megamek#5112]
Damage to the unit can be customized in the lobby, but not damage to the crew. This should be added.

**Comment by Kdskeitaro** [comment]
Such a feature will be deeply appreciated. Especially for certain scenarios and overall customization. (especially setting pilots to unconscious or just with some lingering damage)

**Comment by Sleet01** [comment]
I'm going to start looking at this, see if I can slip it under the wire...
