### ISSUE TITLE
Princess will not deploy ASF at altitudes other than 5

### ISSUE THREAD

**Issue by KaiserFalk** [MegaMek/megamek#5118]
Currently princess will reset the altitude of any ASF she controls when deploying to be altitude 5 regardless of what is set in the lobby

**Comment by KaiserFalk** [comment]
While that's certainly a funny solution, it doesn't really solve wanting princess to fight at higher altitudes in low-atmo battles

**Comment by Sleet01** [comment]
Conceivably we might want Princess to deploy higher or lower for specific MHQ missions like reconnaissance overflights or NOE jump troop insertions, stuff like that.  As of right now I don't think that works at all.

**Comment by SuperStucco** [comment]
In 49.12 I've deployed Princess controlled fighters in Low Atmo scenarios at different altitudes.  It will generally keep them there if your own aircraft are at similar altitudes e.g. if you deploy at 8, and set them at 7 or 8, it will keep them there; if you set them at 5 or less they will eventually rise up.  Same if you deploy at 2 or 3, they will eventually drop down to something similar, or at least until they are within range.

**Comment by KaiserFalk** [comment]
Definitely not my experience

![image](https://github.com/MegaMek/megamek/assets/11843379/6749f8f6-359f-4063-963d-8eb162f40a2c)

![image](https://github.com/MegaMek/megamek/assets/11843379/7895809e-3bcd-44aa-ad97-23c7ecb153ec)

![image](https://github.com/MegaMek/megamek/assets/11843379/ae3b1a4e-2fe6-4997-b902-5eab6983452b)

**Comment by KaiserFalk** [comment]
Did some more testing, the previous was a mekHQ low atmo scenario. Campaign file with save before scenario start attached for testing.

[My Campaign30450625.cpnx.gz](https://github.com/MegaMek/megamek/files/14146733/My.Campaign30450625.cpnx.gz)

Doesn't seem to happen in stand alone MM low atmo scenarios

![image](https://github.com/MegaMek/megamek/assets/11843379/606bf40f-7e61-494c-afe2-5e0f1e432dfe)

![image](https://github.com/MegaMek/megamek/assets/11843379/9153bca1-2d98-4155-9434-a45725989137)

**Comment by PhoenixHeart512** [comment]
I'm not sure if something has changed, or if it's just due to the AI settings, but I found that when using the 49.19 nightly build that if I have princess set to the Berserker v2 AI profile, she regularly flew her ASF's anywhere between altitude 4-9 on her own, instead of just staying at altitude 5 all the time.

![image](https://github.com/MegaMek/megamek/assets/101755917/a0b51d70-bbba-49f3-9b4d-e8a45a3f1343)

**Comment by SJuliez** [comment]
This should no longer occur. Princess can now deploy at the altitude that is given in the lobby, unless the altitude is illegal
