### ISSUE TITLE
[0.49.18] Nightly - Whoops No Entity Message on MekHQ Scenario Resolution

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megamek#5143]
### Environment
14:26:50,218 INFO  [megamek.MegaMek] {main}
megamek.MegaMek.initializeLogging(MegaMek.java:118) - Starting MegaMek v0.49.18-SNAPSHOT
	Build Date: 2024-02-09T01:06:06.158121400
	Today: 2024-02-09
	Origin Project: MegaMekLab
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 4 GB

### Description
When resolving a scenario generated from MekHQ, some of the units are failing to load in the salvage picker screen, and showing up as "Whoops, no entity!"

Screenshot:
![image](https://github.com/MegaMek/megamek/assets/101755917/db5c4e25-10ee-4e37-8170-a3d3e69cbe99)

May be related to clan names, as the log indicates the error is in the "extradata=" field

Issue occurs even if I load an autosave and re-finish the scenario, the error is present on a freshly generated salvage mul with the exact same units having the issue.

List of all 10 mechs and good/bad with their extraData lines:
bad extraData="phenotype=MECHWARRIOR|surname=|bloodname=Lassenerra|givenName=Chrissie" (mad cat)
bad extraData="phenotype=MECHWARRIOR|surname=|bloodname=Ravenwater|givenName=Aniz" (vulture IV)
bad extraData="surname=|givenName=Davi" (gladiator)
bad extraData="surname=|givenName=Salma" (Ebon Jaguar)
bad extraData="phenotype=MECHWARRIOR|surname=|bloodname=Lassenerra|givenName=Ramón" (Loki Mk II)

good extraData="phenotype=MECHWARRIOR|surname=|bloodname=Mitchell|givenName=Wambua" (Ryoken Mk II)
good extraData="surname=|givenName=Norbert" (Turkina H)
good extraData="phenotype=MECHWARRIOR|surname=|bloodname=Amirault|givenName=Arganjan" (turkina B)
good extraData="surname=|givenName=Daisuke" (Xanthos)
good extraData="surname=|givenName=Dan" (Viking IIC)

### Files
Attached files match the folder structure of a clean MekHQ installation, so extracting the zip on top of a clean installation should place all customs and saves in the correct location.

I GM deleted all of the customs from my hangar that were not involved in the scenario to cut down on the number of customs that needed to be included. If the full save and full customs list is needed just let me know and I will attach it separately.

[NoEntity.zip](https://github.com/MegaMek/megamek/files/14226433/NoEntity.zip)

**Comment by HammerGS** [comment]
@SJuliez I think these are related to the Clan name stuff?

**Comment by PhoenixHeart512** [comment]
I was able to confirm that if I load a previous nightly build and manually resolve the same mission with the same .mul salvage file, everything shows properly.

Build used:
megamek.MegaMek.initializeLogging(MegaMek.java:118) - Starting MegaMek v0.49.18-SNAPSHOT
	Build Date: 2024-01-16T01:12:19.818682600
	Today: 2024-02-12
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 8 GB

**Comment by PhoenixHeart512** [comment]
Adding a new example mission. I believe that the issue is caused by the recent separation of Clan/IS mech names, such as "Cauldron-Born (Ebon Jaguar)".

I checked an old salvage .mul from a previous version, and the syntax inside the .mul appears to be the same as the old version, so I suspect that mekHQ was updated to look for the new "clan name" field, but MegaMek was not updated to include that field in the salvage output.

In the new set of attached logs, the campaign save is on mission day, the "buggedVersion" is the salvage file from today's game, and the "oldVersionExample" mul is the one I pulled from an old build to compare it against.

The new version has Fenris (Ice Ferret) on line 428
The old version example file has Hellhound (Conjurer) on line 455

I'll leave the original post as-is, but I no longer believe the issue is related to the "extradata" field at all, and instead is related to the separation of the clan/IS mech names.

[WhoopsNoEntity2.zip](https://github.com/MegaMek/megamek/files/14271068/WhoopsNoEntity2.zip)

**Comment by kuronekochomusuke** [comment]
was this fixed?

**Comment by HammerGS** [comment]
I'm not sure, I think we have fixes for name stuff in. @Sleet01 or @SJuliez might now

**Comment by Sleet01** [comment]
I'll check this with the latest name fixes.

**Comment by PhoenixHeart512** [comment]
Just going through my old issues, this one can be closed as it was successfully fixed

**Comment by IllianiCBT** [comment]
Closing as resolved
