### ISSUE TITLE
[0.49.17] Null pointer exception after targeted aerospace unit flies off map

### ISSUE THREAD

**Issue by azhais** [MegaMek/megamek#5152]
### Environment
What version of MegaMek does your issue apply to?  Discovered in MekHQ's megamek.   Can reproduce in the standalone download as well.
What operating system are you using?  Windows 11
What java version are you using?  
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.7

### Description
If you've fired at an aerospace unit that then flies off the map, there's a null pointer exception thrown when selecting weapons on the unit the next round.    This also removes all target numbers from other units on the map (which I forgot to include in my test save) and disables torso twisting on the unit for the rest of the match.

Reproduction steps:
Team 1 with an aerospace fighter
Team 2 with a mek
Round 1: Shoot the aerospace fighter
Round 2: Have the aerospace fighter fly off the map (I also selected for it to return, unsure if that's required to reproduce)
Round 2: Selecting any weapon on the mek will result in a null pointer exception
note: the torso twist vanishing always occurs, but the null pointer exception only pops up if you select the weapon before you target something.  If you click the target first there's no null pointer

### Files
![Screenshot 2024-02-11 152947](https://github.com/MegaMek/megamek/assets/46464401/a26c1b03-579e-4e37-8bbc-ce5c4790be3e)
[aerospacebug.sav.gz](https://github.com/MegaMek/megamek/files/14234106/aerospacebug.sav.gz)
[aerospacebug.log](https://github.com/MegaMek/megamek/files/14234117/aerospacebug.log)

**Comment by Sleet01** [comment]
I've been cleaning up NPEs so I'll try to clean this up.

**Comment by Sleet01** [comment]
Unable to repro in 0.50.0-SNAPSHOT; I believe this has been fixed by the extensive targeting display rework since the bug was filed.
