### ISSUE TITLE
RFE: Advanced search my motive types

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#5163]
Was raised on another Discord.  Would it be to filter by all the supported Vehicle movement types.

**Comment by kuronekochomusuke** [comment]
#4629

**Comment by pavelbraginskiy** [comment]
[Just use Alpha Strike search](https://bg.battletech.com/forums/index.php?topic=80420.msg1907350#msg1907350)

**Comment by PhoenixHeart512** [comment]
the AS search can't further filter by weapon/equipment, and it also doesn't do Dropships (it would be nice to be able to filter between Spheroid and Aerodyne)
