### ISSUE TITLE
artillery flak attack should not include flak -2 modifier

### ISSUE THREAD

**Issue by Jetsky82** [MegaMek/megamek#5164]
Megamek 49.17 Giving direct shot artillery flak bonus when it should not be giving flak bonus against vtol.  

TACOPS p153 Flak says Apply a +3 to-hit modifier. Ignore the regular modifiers for using Type “F” weapons or making a direct-fire attack; the only other modifiers applied are for the firing unit’s movement and current damage, as well as woods/jungle, if any are 
intervening.
Megamek is calculating the to-hit of flak arrow IV against a VTOL as follows:  Gunnery skill +3 Artillery flak attack -2 (flak to hit modifier).  However, the rules say "ignore the regular modifier for using Type F weapons" so the -2 should not be there. 

![image](https://github.com/MegaMek/megamek/assets/155403076/3a3d379e-1997-48c7-9ded-c922ce32c1f2)

**Comment by gsparks3** [comment]
As of the most recent printing, that line has been changed in errata. 

>"Apply a +3 to-hit modifier. Ignore the regular modifier for making a direct-fire attack; the only other modifiers applied are for using Type “F” weapons, [...]"
