### ISSUE TITLE
artillery adding wrong modifier under 17 hexes. 

### ISSUE THREAD

**Issue by Jetsky82** [MegaMek/megamek#5168]
Megamek 49.17 is applying a +7 modifier for indirect fire at 17 and under hexes when it should be applying a +4 modifier.  This was clarified as a rules question by XOTL and PAUL on bg.battletech.com

More detail. 
TacOPs modifier for indirect fire over 17 hexes is +7 (pg150) and then it moves to targeting under 17 hexes and provides a +4 modifier for direct firing.  Then on page 153 it discusses indirect fire at 17 or less distance, and fails to give a specific modifier.  This was clarified on the official BG.Battletech.com site : 
https://bg.battletech.com/forums/index.php?topic=60931.msg1399754#msg1399754
**It's too bad neither of us found that post sooner! :p

This is correct:

https://bg.battletech.com/forums/index.php?topic=21537.msg526757#msg526757

So the +7 modifier is for targets at 18+ hexes, the +4 for targets at 17 or less, contrary to the prior post.**

and 
https://bg.battletech.com/forums/index.php?topic=21537.msg526757#msg526757
![image](https://github.com/MegaMek/megamek/assets/155403076/753522f3-10b9-40f0-bd0d-63b37513371d)

**Comment by Sleet01** [comment]
Confirmed, this matches the wording in the latest published rules as well (not that I doubt the links, but they're several years old now).

**Comment by Sleet01** [comment]
I'll do this up real quick.

**Comment by Jetsky82** [comment]
exciting! thanks!!!
