### ISSUE TITLE
Uncaught java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by jimtheviking** [MegaMek/megamek#5178]
### Environment
Standalone MegaMek 49.18, but also in 49.17
OS: Windows 11
Java: Oracle 17.0.2

### Description
Standalone MegaMek will not load, returning an Uncaught java.lang.IndexOutOfBoundsException error. Screenshot attached.

### Files
Logfile attached, as is screenshot
[megamek.log](https://github.com/MegaMek/megamek/files/14321505/megamek.log)
![image](https://github.com/MegaMek/megamek/assets/7865014/dbc455fd-659d-4a72-abb7-cba4a1700e57)

**Comment by HammerGS** [comment]
When you installed did you use the Windows unzip?

**Comment by jimtheviking** [comment]
I used WinRAR, actually, but yeah.

**Comment by HammerGS** [comment]
We sometimes see those errors, with the use of Windows Unzip or a bad download.

**Comment by jimtheviking** [comment]
Sorry about the slow response; I've tried several re-downloads, and I'm no longer experiencing this particular issue, but the uncaught exception is now occurring in MML when I open Small Craft. I'll open a bug report there.

Thanks.
