### ISSUE TITLE
[49.18] Canon units excluded from 'Canon Units Only' setting

### ISSUE THREAD

**Issue by mandalorewise01** [MegaMek/megamek#5191]
### Environment
MekHQ v0.49.18
Java Vendor: Oracle Corporation
Java Version: 19.0.2
Platform: Windows 10 10.0 (amd64)

### Description
I discovered that a large number of Canon units do not appear when the "Canon Units Only" setting is enabled in the "Allowed Units and Equipment" portion of the Game options. attached is images of the unit search window, with the only change made between the two being the changed state of the Canon Units setting.

### Files
![image](https://github.com/MegaMek/megamek/assets/29016804/5792e792-5081-4479-ac6f-8a9933659a44)
![image](https://github.com/MegaMek/megamek/assets/29016804/5a930047-9638-4976-b587-f359bda75ff5)

also attached is the Game Settings File I used to quickly import my game options from the v0.49.15 build and the Logs folder
[Game Options File and Logs.zip](https://github.com/MegaMek/megamek/files/14377378/Game.Options.File.and.Logs.zip)

**Comment by HammerGS** [comment]
I should add we don't support Java 19 and that could be a potential cause. You'd need to test with Java 11 or 17

**Comment by mandalorewise01** [comment]
Got it, I'll try to switch to Java 17 and test it again

**Comment by HammerGS** [comment]
Update on this.  When we introduced the Clan name changes, the method that updates the canon unit list was broken and will need fixing. Workaround at this point is keeping the option off for now.

**Comment by mandalorewise01** [comment]
Got it, I'll try that as well.
