### ISSUE TITLE
RFE: Add missing mechset references for unit sprites

### ISSUE THREAD

**Issue by Gribbly1** [MegaMek/megamek#5194]
Please add the following lines to mechset:

chassis "Riga II Destroyer-Carrier" "warships/Riga Frigate.png"
chassis "Black Lion I Battlecruiser" "warships/Black Lion I Battlecruiser.png"
chassis "Black Lion II Battlecruiser" "warships/Black Lion II Battlecruiser.png"
exact "Black Lion II Battlecruiser (2843)" "warships/black_lion.png"
chassis "Essex II Destroyer" "warships/Essex Destroyer.png"
chassis "Monsoon Battleship (LF)" "warships/Monsoon Battleship.png"
chassis "Capital Drone" "warships/Lola II Destroyer.png"
chassis "York Destroyer-Carrier" "warships/york.png"
exact "Congress Frigate (2542)" "warships/Congress Frigate.png"
chassis "Fredasa (Corvette-Raider)" "warships/fredasa.png"
chassis "Conqueror Battlecruiser Carrier" "warships/conqueror.png"
chassis "Liberator Cruiser" "warships/avatar.png"
chassis "Wusun" "fighter/Wusun.png"

**Comment by Gribbly1** [comment]
Looks like several of these are still missing or wrong. Was this implemented?

**Comment by HammerGS** [comment]
It was but with all the issues might have been a regression.
