### ISSUE TITLE
search for IS but not clan Angel ECM yields clan ECM units

### ISSUE THREAD

**Issue by Jetsky82** [MegaMek/megamek#5197]
megamek 49.17
The cave lion and the cauldron born x are both clan mechs with angel ECM, presumably it would be clan angel ecm.  However, when i search for angel ECM (Clan) it comes up with no mechs at all.  When I search for Angel ECM (Inner sphere) it comes up with both of the above.

**Comment by HammerGS** [comment]
Working in 0.50.0
