### ISSUE TITLE
(49.18) BV doesnt update in the lobby until you double click on your player name and select ok,in addition BV blanks when previewing a map.

### ISSUE THREAD

**Issue by BiggestBoss1** [MegaMek/megamek#5206]
Windows,
49.18.
64 bit system.

When first loading into the lobby and add units,the BV value will remain blank (-) until you select click on your name and click ok in the
deployment zone screen.The BV will also reset back to blank if you preview a map and return to the unit list.

![εικόνα](https://github.com/MegaMek/megamek/assets/78164933/8a17029b-02fa-4147-93eb-e17acc3cbec1)

![εικόνα](https://github.com/MegaMek/megamek/assets/78164933/7f3b8126-353f-4bd9-8182-ee3f415ee1f3)

![εικόνα](https://github.com/MegaMek/megamek/assets/78164933/968171e2-d396-46a5-bd55-926ddb7d4035)

**Comment by Sleet01** [comment]
I'd seen this happen a couple times but wasn't able to reproduce it.  This is definitely a bug.
