### ISSUE TITLE
[0.49.19] Lexan Support VTOL's marked as invalid with invalid equipment

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megamek#5207]
### Environment
megamek.MegaMek.initializeLogging(MegaMek.java:118) - Starting MegaMek v0.49.19-SNAPSHOT
	Build Date: 2024-02-26T01:08:44.509075800
	Today: 2024-02-26
	Origin Project: MegaMek
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 2 GB

### Description
The following units are showing as invalid in MegaMek:
Lexan Oceanic Personal VTOL Series II
Lexan Surveillance Helo
Lexan Oceanic Luxury VTOL Series VI

Showing as "Not enough item slots available" (likely due to Armor taking up 14 slots) and possible related to https://github.com/MegaMek/megamek/pull/5186

![image](https://github.com/MegaMek/megamek/assets/101755917/31981322-241d-4421-b15e-7b70e64c36c6)

**Comment by HammerGS** [comment]
Fixed with https://github.com/MegaMek/megamek/pull/5186
