### ISSUE TITLE
Submarine cannot pass under bridges in a turn when their elevation changes.

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#521]
[Water.sav.gz](https://github.com/MegaMek/megamek/files/888021/Water.sav.gz)

The neptune submarine in this save can freely pass under the bridge the turn after it changes its elevation to -2, but cannot pass under in a single move if it requires an elevation change.

**Comment by VampireSeraphin** [comment]
This is a different issue from the linked tickets. Please re-open or link to the fix.


Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone
-------- Original message --------From: neoancient <notifications@github.com> Date: 11/9/17  1:32 PM  (GMT-05:00) To: MegaMek/megamek <megamek@noreply.github.com> Cc: VampireSeraphin <buttardc@gmail.com>, Author <author@noreply.github.com> Subject: Re: [MegaMek/megamek] Submarine cannot pass under bridges in a turn
  when their elevation changes. (#521) 
Closed #521 via fdff413.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MegaMek/megamek","title":"MegaMek/megamek","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/MegaMek/megamek"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #521 via fdff4134af2e7fb75917437e51d48a53c1a82180."}],"action":{"name":"View Issue","url":"https://github.com/MegaMek/megamek/issues/521#event-1334586477"}}}

**Comment by neoancient** [comment]
There is a link to the fix in my closing note. The other issue linked here is irrelevant.
