### ISSUE TITLE
0.49.19 Nightly from 2/27/2024 - Uncaught Exception when loading saved game causing soft lock

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#5214]
I tried loading a saved game which I loaded before earlier in the game without a problem.  I saved it last night before the movement phase began and tried loading it tonight and got repeated Uncaught Exceptions.  I click OK on an Uncaught Exception box and another one popped up.  This wouldn't stop and the board never loaded, even though the unit display was on a friendly bot-controlled off-board Ballista.  I had to close the Java process via Task Manager.  Log and savegame attached.

[megamek.log](https://github.com/MegaMek/megamek/files/14471320/megamek.log)
[CompanyGame1.sav.gz](https://github.com/MegaMek/megamek/files/14471321/CompanyGame1.sav.gz)

![image](https://github.com/MegaMek/megamek/assets/18338059/871b5bbe-3510-4e2f-9a08-fffd2fb5538a)

**Comment by Sleet01** [comment]
It looks like the board is trying to update and querying the off-board unit for its elevation, probably in order to draw its shadow or position it for isometric representation - despite this being unnecessary for an off-board unit.

Definitely a bug.

**Comment by Sleet01** [comment]
Actually, @BLR-IIC , do you have the HTML log for this game as well?  The recurring IllegalStateException in the `megamek.log` file refers to entity 57, which appears to have been a pilot named "Ruhiye Zand"; it would be helpful to see what happened with that pilot during this game.

It may be that this pilot ejected in an indeterminate state, but it looks like the Ballista was the last unit to load _correctly_, not the unit that caused the exception you saw.

**Comment by BLR-IIC** [comment]
Here's the HTML log:

[gamelog.zip](https://github.com/MegaMek/megamek/files/14475757/gamelog.zip)

**Comment by SJuliez** [comment]
I'd say this is caused by the unit shadows. Will deal with it.
