### ISSUE TITLE
[49.18] Secondary turret firing arc display does not reflect turret rotation

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#5215]
On a multi-turret vehicle (such as the Gulltoppr OmniMonitor), rotation of the FT (front turret) using the turret twist mini-menu does not visually update the firing arcs for the weapon. The primary turret updates as normal. 

In this image, the turret was rotated to point northeast prior to re-opening the FT rotation menu:
![image](https://github.com/MegaMek/megamek/assets/59574316/0b172ab4-c15a-4f9d-9a7a-e7b322b49539)

While the visual display is incorrect, the actual turret rotation appears to be correct.
![image](https://github.com/MegaMek/megamek/assets/59574316/61b585e4-6a18-407e-90d3-9668cdab897d)

This is likely related to #2659 , as the FT here uses the same rotation menu as the mech turrets there.

**Comment by HoneySkull** [comment]
If TacOps Vehicle Firing Arcs is enabled, should the second turret also have the same arc width as the main turret?

**Comment by gsparks3** [comment]
TO:AUE page 159 says they both follow the standard turret rules except that the forward turret can't fire through the rear hexside, so seems like that is correct.

**Comment by HoneySkull** [comment]
Okay - that's what I thought,  in the code the 2nd turret is hard coded to a forward arc regardless of the tacOps setting - I think this should be the same logic as the main turret.  (note:  This is the arc type not facing)

![image](https://github.com/MegaMek/megamek/assets/83041327/0d9dbe8d-6944-4fdd-abcd-0483406522ff)
