### ISSUE TITLE
[0.50] Structure Collapse Warning Appearing Beneath Objects

### ISSUE THREAD

**Issue by IllianiCBT** [MegaMek/megamek#5219]
### Environment
HQ MegaMek
Mac Ventura 13.6.4
Java Homebrew 11.0.16.1

### Description
Structure collapse warning symbols appear beneath bridges, when isometric view is enabled.

Isometric View _On_
<img width="217" alt="image" src="https://github.com/MegaMek/megamek/assets/103902653/8e4fa5b0-90be-49ac-a9fe-74426e9a6105">

Isometric View _Off_
<img width="202" alt="image" src="https://github.com/MegaMek/megamek/assets/103902653/3cf97f75-e5a4-4d4b-b0f5-24aeb1529ca4">

**Comment by IllianiCBT** [comment]
Player: The Oddballs
[IllianiCBT_#5219.sav.gz](https://github.com/MegaMek/megamek/files/14489684/IllianiCBT_.5219.sav.gz)

**Comment by IllianiCBT** [comment]
This is also true for buildings with turrets:

Isometric view _on_:
<img width="159" alt="image" src="https://github.com/MegaMek/megamek/assets/103902653/15e5c38c-9706-4d6f-90c4-3557988b90ca">

Isometric view _off_:
<img width="202" alt="image" src="https://github.com/MegaMek/megamek/assets/103902653/c7fc294b-2149-43a8-bcc7-0e119b35fe47">

**Comment by IllianiCBT** [comment]
This appears to have suffered a regression :(

**Comment by HoneySkull** [comment]
This regression appears to have occurred after the sprite refactoring that separated sprite logic from BoardView.java and is broke in 0.49.20.  It's working as expected in 0.49.19.1
