### ISSUE TITLE
Ammo bins not automatically switching. Alpha strikes only partially fire

### ISSUE THREAD

**Issue by EnbyMyu** [MegaMek/megamek#5227]
### Environment
MekHQ/MegaMek 0.49.18
Java Vendor: Eclipse Adoptium
Java Version: 21
Win11 23H2

### Description
A Bane 3 that had previously only fired four LRM 15s for its first shot of combat. The ammo bin the missiles were drawing from had 4 shots remaining. The next turn, I fired an alpha strike of all eight launchers, and only four launchers fired.

This can be reproduced with a Bane 3 by firing four shots in one turn, then more than four shots on another turn. Only the remaining ammunition in the first bin will be used, the rest will not fire.

![Bane 3-1](https://github.com/MegaMek/megamek/assets/159649649/98554648-c717-4d2f-b86a-9e9ed0251b9e) 

Note the number of launchers fired in the lower right.

![image](https://github.com/MegaMek/megamek/assets/159649649/6edf7953-9892-4a55-8ed3-0473ba3b578a)

Final results of salvo. Only four launches before moving to another unit.

![Bane 3-2](https://github.com/MegaMek/megamek/assets/159649649/e2697ecf-4a50-42aa-898f-69eafbfdbafa)

### Files
[Bane.sav.gz](https://github.com/MegaMek/megamek/files/14517307/Bane.sav.gz)

Team name is "The Wrecking Belles"

**Comment by PhoenixHeart512** [comment]
This issue is resolved in the latest nightly, by https://github.com/MegaMek/megamek/pull/5190 @Sleet01 , just tested and confirmed that it no longer occurs on yesterday's build.

**Comment by Sleet01** [comment]
@PhoenixHeart512 Good lookin' out!  I'll close this as fixed.
