### ISSUE TITLE
Vtol Cannot Pass Under Bridge

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#523]
![image](https://cloud.githubusercontent.com/assets/19868605/24582837/681ba15c-1706-11e7-8b28-b29ddc964ebc.png)

[VtolBridge.sav.gz](https://github.com/MegaMek/megamek/files/888029/VtolBridge.sav.gz)

On a whim, I checked this, other units can pass under bridges, but Vtols cannot.

**Comment by BLOODWOLF333** [comment]
#481 is related to this I believe.

**Comment by neoancient** [comment]
Note that VTOLs will need the same clearance below the bridge that they need above the terrain, so a standard VTOL requires the bridge to be at least three levels of elevation above the terrain and a superheavy requires four.
