### ISSUE TITLE
[49.19 Nightly] Overlord Dropship Sprite Shadow Bugged

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megamek#5245]
### Environment
megamek.MegaMek.initializeLogging(MegaMek.java:118) - Starting MegaMek v0.49.19-SNAPSHOT
	Build Date: 2024-03-12T01:07:05.468231
	Today: 2024-03-13
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 8 GB

### Description
The sprite shadow for the Overlord dropship (and maybe dropships in general) appears to be bugged. It may just be large and offset due to dropships on the map using a 7-hex multi sprite?

(Dropship is grounded and not flying)
Each individual sprite hex on the multi-sprite also seems to have the same weird shadow as well

![image](https://github.com/MegaMek/megamek/assets/101755917/7d16bffc-a54e-40a4-8272-d738a39c0117)

![image](https://github.com/MegaMek/megamek/assets/101755917/81e97e03-b21a-404a-914a-89d2e1f3226a)

Attached save file as an example

### Files
[SpriteShadowBug.sav.gz](https://github.com/MegaMek/megamek/files/14589225/SpriteShadowBug.sav.gz)

**Comment by SJuliez** [comment]
Fixed (sorta) with #5246
