### ISSUE TITLE
[0.49.19 Nightly] Ballistic and Energy ammo missing the "ammo" word in equipment and crit assignment screens in MML

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megamek#5252]
### Environment
megameklab.MegaMekLab.initializeLogging(MegaMekLab.java:53) - Starting MegaMekLab v0.49.19-SNAPSHOT
	Build Date: 2024-03-14T01:06:51.822114300
	Today: 2024-03-15
	Origin Project: MegaMekLab
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMekLab: 8 GB

### Description
Many of the ballistic weapons (and some energy) ammunition bins don't have the word "ammo" when viewed in the equipment list and crit assignment screen. This could lead to confusion on whether a given item is the weapon or the ammo bin for the weapon, especially if the user is not using color coded equipment types. Screenshots below showing the affected ballistic and energy weapons

Additionally, the MG ammo bins do not say "half" on the half-ton versions in the equipment and crit slot lists.

Lastly, the CLAN machine gun full ammo bin is incorrectly listed as [Half] in the right-hand equipment list pane.

### Files

![Ballistic Ammo](https://github.com/MegaMek/megamek/assets/101755917/3a514388-8998-4e06-8175-f6fb8fdaf3be)

![Energy Ammo](https://github.com/MegaMek/megamek/assets/101755917/8f4f7411-cbcc-4ddc-a896-06e8026270b2)

![Clan MG Ammo Typo](https://github.com/MegaMek/megamek/assets/101755917/2666fff7-fcb7-4e12-9263-195d75295574)

**Comment by HammerGS** [comment]
Going to tag @Sleet01 into this for comment

<img width="526" alt="image" src="https://github.com/MegaMek/megamek/assets/13752452/5d266f7b-51ac-49b2-b713-2380ab41e948">

**Comment by Sleet01** [comment]
I'll try to take a look this weekend.

**Comment by Sleet01** [comment]
I did not actually get a chance to look at this yet.

**Comment by Sleet01** [comment]
This actually appears to be resolved in the Equipment list, but not in the Crit Assignment listing.
