### ISSUE TITLE
Potential Mechfile quirk errors (Mar 2024)

### ISSUE THREAD

**Issue by AotrsCommander** [MegaMek/megamek#5253]
Reporting potential quirk Mechfile errors (discovered as I parsed through the mech to sort my own mech list out).

### Environment
These will be from MML 0.49.16 (when I made my personal fork); you may have already fixed them, since, but as I dutifully logged these as I went though, (Given as it took me about ten hours to go through about 750 mechs, though, I figure they could easily have slipped through! Hope this helps.

### Description
List of mechs with missing quirks

### Files

- [x] Fennec FEC-1CM; missing no/minimal arms
- [x] Longbow 8C; no quirks
- [x] Man 'o War (Gargoyle); F, I, J, K, P, X no quirks
- [x] Maruader Bounty Hunter 3015, 3044, 3118, C, 1R, Red Hunter, Red Hunter 3146; no quirks
- [x] Loki Mk 2 (Hel) C, D, E, F, T no quirks; F, T missing (Hel) from mech name (breaks image path)
- [x] Nightsky NGS-7S; no quirks
- [x] Orion C, C 2; no quirks
- [x] Phoenix Hawk C, C 2; no quirks
- [x] Vanquisher VQR-2A (Pravuil); no quirks

Less concretely:
Viking IIC (Standard) no quirks (??) File name shanigans? I had both a Viking IIC and Viking IIC (Standard)) file, though the latter seemed to be the recent one.

Wolf Trap WFT-2B; Sarna cites RS Prototypes saying this variant has Easy to Maintain; can't source it myself.

**Comment by HammerGS** [comment]
According to BMM and the RecGuide 33, the Loki Mk 2 doesn't have quirks. Current versions have no issues with Loki Mk 2 Names.
