### ISSUE TITLE
Vibrabomb early detonation ends movement.

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#527]
I was able to duplicate an error another player was having in version 4.30. A mech detonating a vibrabomb early by being to heavy ends that mechs movement, without giving it a chance to plot a new move with leftover MPs. Save attached.

[VibraBombError.sav.gz](https://github.com/MegaMek/megamek/files/888753/VibraBombError.sav.gz)

**Comment by arlith** [comment]
Closing as duplicate of #529.
