### ISSUE TITLE
[49.19-Snapshot #1437] Unit Loading Failures Thunderbolt TDR-9T

### ISSUE THREAD

**Issue by IllianiCBT** [MegaMek/megamek#5271]
### Environment
Origin Project: MekHQ
Java Vendor: Eclipse Adoptium
Java Version: 11.0.22
Platform: Mac OS X 13.6.4 (x86_64)

### Description
<img width="581" alt="image" src="https://github.com/MegaMek/megamek/assets/103902653/777fd734-8b87-4f95-9806-876f696555d6">

Load into mission 'Irregular Forces' to be presented with error. It's late, local, so I'm not capable of more thoroughly testing at this time. Will pick this back up tomorrow.

### Files
[IllianiCBT_#5271.zip](https://github.com/MegaMek/megamek/files/14691241/IllianiCBT_.5271.zip)

**Comment by pavelbraginskiy** [comment]
That'd be because its engine rating got removed: https://github.com/MegaMek/megamek/commit/7e5105c19c6529e442e4119187bff8471e415c26#diff-0348a872bbe95dc99083bff441a9aa160d2473f37de5a88604ab28e0d872118dR20
