### ISSUE TITLE
Inferno SRMs do not set buildings on fire when using collapse or ignite attack options

### ISSUE THREAD

**Issue by KaiserFalk** [MegaMek/megamek#5287]
Seen in multiple MM versions, screenshot from 49.15.

Using "Clear" on a building with inferno SRMs will ignite it, using "Collapse" or "Ignite" will not, and only does damage. This is counterintuitive since the "Ignite" attack is used to set fire to hexes with most other weapons.

Additionally it seems like infernos do not deal double damage to terrain using the latter two attack types, unlike the "Clear" attack. All 4 attacks hit with 4 inferno missiles.

![image](https://github.com/MegaMek/megamek/assets/11843379/00f6bbf4-1abe-4fda-b3c6-cc88d5dc3563)

**Comment by IllianiCBT** [comment]
This appears to still be an issue in 50.0
