### ISSUE TITLE
Movement Interruption with Dialog Box Ends Turn

### ISSUE THREAD

**Issue by ObviousTech** [MegaMek/megamek#529]
When a unit's movement is interrupted by something, like a skid or a minefield.

What previously happened:
- a popup describing the interruption
- if the unit has MP left after the movement ends, it can select new movement

Currently (0.42.0-0.43.0):
- no popup
- the unit is not allowed to select further movement
- the unit's turn ends

Examples of actions that appear to trigger this:
-vtol or hover tank skids.  (Probably mech skids, too, but haven't tested yet)
-minefield exploding. (at least vibromines appear to cause it, have not tested further yet).

To reproduce, see the attached saves.  Move any of the hovers in a circle, triggering lots of PSRs to avoid sideslipping/skidding.  Eventually, one will fail its PSR early in its movement and its turn will end.

There are no errors in the megamek logs.

Problem occurs in 43.0, 42.0.  Worked correctly in 41.26.

43.0 (play as 'obvious'): [dialoginteruptmovement.sav.gz](https://github.com/MegaMek/megamek/files/907907/dialoginteruptmovement.sav.gz)
42.0 (play as 'test'): [autosave_2017-04-08_20-02-07.sav.gz](https://github.com/MegaMek/megamek/files/907908/autosave_2017-04-08_20-02-07.sav.gz)

Possibly directly related to https://github.com/MegaMek/megamek/issues/527

**Comment by ObviousTech** [comment]
To narrow is down more, this appears to have broke between 41.26 and 41.27.

**Comment by ObviousTech** [comment]
However, interruption by a hidden unit still gives a popup and allows you to select more movement (in 43.0).

**Comment by arlith** [comment]
This bug was introduced in d0c2ccd81.  I thought I could simplify the conditional, but turns out it broke things.
