### ISSUE TITLE
Blue Flame BLF-40 is missing

### ISSUE THREAD

**Issue by Inspirational-sausage-dog** [MegaMek/megamek#5290]
Development MegaMek 0.49.18 Linux JDK 11

BLF-40 variant is missing from the roster.

http://masterunitlist.info/Unit/Details/5672

**Comment by HammerGS** [comment]
Nope.  Its right here

<img width="1148" alt="image" src="https://github.com/MegaMek/megamek/assets/13752452/ced726b5-a372-42ee-9158-46aec58f1bc5">

**Comment by Inspirational-sausage-dog** [comment]
Yeah, it appears that I mistook it for standart tech in my era. Thank you for clearing this up.
