### ISSUE TITLE
MegaMek Help->Contents Does Not Point At Readme.txt

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#530]
It's been like this for a few versions now but, I never said anything.
![untitled](https://cloud.githubusercontent.com/assets/16950832/24928058/aa749f00-1ec6-11e7-8dca-1a875b80d8d1.png)

**Comment by BLOODWOLF333** [comment]
Should probably be docs/docs-mm/readme.txt (I am using HQ 0.42.1).

**Comment by wildj79** [comment]
Worked for me.

![image](https://cloud.githubusercontent.com/assets/2126857/24928531/5c18e396-1ec8-11e7-883e-8a174973a327.png)

**Comment by arlith** [comment]
Based on the first comment, I bet this is a MM that is packaged with MHQ, which may be putting the docs in a different location.  This might be a MHQ packaging issue, and the MHQ version of MM may need to have the locations of docs updated.

**Comment by Dylan-M** [comment]
One fix for this is to have MM check multiple locations for the file, because we package the docs in sub-folders on purpose. Another is to make it a variable that can be updated, but then it still wouldn't work unless MM was launched from MHQ.

**Comment by BLOODWOLF333** [comment]
So can for HQ only this file path be changed to point at docs\docs-mm\readme.txt or....?  I guess I can download the HQ project into eclipse and fix this later.

**Comment by NickAragua** [comment]
Fixed with PR #731
