### ISSUE TITLE
Pirate "Raid" Contracts not following AtB rules

### ISSUE THREAD

**Issue by contrails19** [MegaMek/megamek#531]
Under the current AtB rules Pirate "raid" contracts are supposed to only provide 100% salvage, however as of the current stable release generated "raid" contracts seem to be providing income and other costs. 
![untitled](https://cloud.githubusercontent.com/assets/26807655/25017726/cf98a1e0-2052-11e7-8464-4955576b8bf0.png)

I'm not sure if this is a fixable thing, but I thought I should bring it up

Thank you

**Comment by neoancient** [comment]
AtB is part of MekHQ. Please post any AtB-related issues to the MekHQ tracker: https://github.com/MegaMek/mekhq/issues
