### ISSUE TITLE
incorrect unit stats for Chevalier Light Tank (speed)

### ISSUE THREAD

**Issue by alien10000** [MegaMek/megamek#5310]
### Environment
Development: 0.49.18

### Description
the speed variant is suppose to have only 1 streak SRM 2 but as currently implemented it has an extra ER laser 
Technical Readout 3060 page 18 under variants
TRO: 3060 page 35-36

**Comment by HammerGS** [comment]
See errata - https://bg.battletech.com/forums/index.php?topic=4021.msg433686#msg433686
