### ISSUE TITLE
HS not registering

### ISSUE THREAD

**Issue by kipstafoo** [MegaMek/megamek#532]
Playing an AtB fight and I have a mint AWS-8Q that only registers 25 HS. It has no damage and there's no env effects because I have another AWS that registers the proper 28 HS.

Save game attached

[AWS.sav.gz](https://github.com/MegaMek/megamek/files/924393/AWS.sav.gz)

**Comment by Question2** [comment]
Thats a mekhq bug, the unit itself becomes bugged because mekhq thinsk it has less HS than it really has, you can fix it by adding a new AWS-8Q to your hangar.

**Comment by neoancient** [comment]
The mech had three heat sinks turned off. I could find no way to set that value other than the extras tab in MegaMek.

![image](https://user-images.githubusercontent.com/16927464/34370678-9db70eb0-ea8b-11e7-8121-9d4fa1f3fd0f.png)
