### ISSUE TITLE
RFE:  Enable Edge Triggers by default0

### ISSUE THREAD

**Issue by Thom293** [MegaMek/megamek#5328]
Title.
For characters under bot control,  If edge is enabled you want them enabled.  If it isn't, they don't appear.  

I think you want to exclude MHQ player units since they will have their own settings.  But for bot units or generated in MM should be on by default I think.  

Will do a companion MHQ issue.  

Thank you.

**Comment by Thom293** [comment]
Related: https://github.com/MegaMek/mekhq/issues/3984

**Comment by repligator** [comment]
As of latest master (https://github.com/MegaMek/megamek/pull/5944), units added to bot or player forces while edge is enabled will automatically have all edge triggers set to on (checked). Closing as completed.
