### ISSUE TITLE
49.19 Direct Fire Flak Attacks not supposed to receive standard Flak modifiers

### ISSUE THREAD

**Issue by RaozSpaz** [MegaMek/megamek#5329]
### Environment
49.19 MegaMek
Windows
Java 11

### Description
![image](https://github.com/MegaMek/megamek/assets/132851640/c21432ed-ae01-4f37-813e-9136efa13b13)
Was reading various artillery rules for a question on another server and decided to read over the Flak rules on page 153 of the TO:AR. In the second paragraph when it begins to talk about the various modifiers applied to the attack. It states "Apply a +3 to hit modifier. _Ignore the regular modifiers for using type "F" weapons or making a direct fire attack_"
Reading this section I don't think the -2 modifier from the Flak keyword should be applied to the attack.

ADAs specifically seem to state they use the rules for Standard Flak Attacks so I believe they are still supposed to receive the bonus.

### Files
This can be replicated by adding various artillery and VTOLs to any random battle so no saves are really required.

**Comment by Gribbly1** [comment]
Apply a +3 to-hit modifier. Ignore the regular modifier for
making a direct-fire attack; the only other modifiers applied
are for using Type “F” weapons, the firing unit’s movement and
current damage, as well as woods/jungle, if any are intervening.

Which printing do you have?

**Comment by RaozSpaz** [comment]
Yeah. Its 4th edition. I failed to notice its an older version and the rule has since been erratad.
