### ISSUE TITLE
RFE: Have the add unit dialog reflect and enter Pilot/Gunnery skill.

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#5333]
This is a CGL request from Xotl. 

_Right now the "Add a Combat Unit" list can be filtered in all sorts of useful ways.  But the one thing I can't seem to make it do is to alter the P/G ratings in a universal way and then have the list's BV column reflect that change.  The display is always 4/5._

_I'm trying to build a ton of Clan Stars, and I can't find any way of getting a modified filter list.  Which means I have to click on every unit I want to consider, see the result, go back..._

**Comment by TenkawaBC** [comment]
This needs changes to AbstractUnitSelectorDialog.java to implement.

This is where it loads the bvColumn.

It would need to have UI elements added for P/G, a lookup to the P/G table to get the associated multiplier, and then apply this value to the column without changing the underlying MechTableModel data in memory.

Line 221:   bvColumn = tableUnits.getColumnModel().getColumn(MechTableModel.COL_BV);

**Comment by SJuliez** [comment]
Fixed
