### ISSUE TITLE
[0.49.19 Nightly] (UI Bug) Damage boxes not showing red when displaying multiples of damage

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megamek#5343]
### Environment
megamek.MegaMek.initializeLogging(MegaMek.java:118) - Starting MegaMek v0.49.19-SNAPSHOT
	Build Date: 2024-04-09T01:08:56.721120
	Today: 2024-04-10
	Origin Project: MegaMek
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 8 GB

### Description
When a unit has more armor than can be displayed with individual boxes, MegaMek uses groupings, such as showing "[]x20"

When doing this for damaged armor boxes, they show green instead of red. When only showing individuals, the boxes show red as expected, this only occurs when they are grouped (such as having a large amount of damage on a dropship, as seen in the screenshot below)

### Files

![DamageBoxesBug](https://github.com/MegaMek/megamek/assets/101755917/e98a529d-6435-444e-bf2e-0f3dbabe49ca)

[DamageBoxesBug.sav.gz](https://github.com/MegaMek/megamek/files/14934822/DamageBoxesBug.sav.gz)

**Comment by Sleet01** [comment]
BTW, I note that this DropShip is showing the "5/8 ・2/2 ・ Wheeled" bug as well.

**Comment by gsparks3** [comment]
You can see the multihex graphic, which means it's landed.

**Comment by Sleet01** [comment]
> You can see the multihex graphic, which means it's landed.

You're giving my tired old view-orbs too much credit, but after reviewing the picture I see what you mean :)

**Comment by Sleet01** [comment]
@PhoenixHeart512 Okay, I was finally able to repro the issue by setting "Armor Units per Block" in Client Settings -> Unit Tooltip / Unit Display to "5" (half its default value of "10").

...dangit, I thought there would be an esoteric math error but it's just using the wrong variable in one place -_-;

<img width="421" alt="image" src="https://github.com/MegaMek/megamek/assets/22018319/67e44133-d674-4fef-ab9b-ff119521d677">
