### ISSUE TITLE
Jump-mode backspace past beginning of move queue locks game

### ISSUE THREAD

**Issue by WeaverThree** [MegaMek/megamek#5348]
### Environment
Megamek 0.49.18

Tested under Adoptium Java 11 and 17 on Windows 10, and OpenJDK 11 and Adoptum 17 on current Fedora Linux, problem persists in all cases.

### Description
When you're in movement phase with a mek and in jump mode and backspace past the beginning of the movement list, the game completely freezes and needs to be task killed to close. This can be done just be pressing the 'jump' button and backspace once. 

### Files
[megamek.log](https://github.com/MegaMek/megamek/files/14938673/megamek.log) - doesn't appear to have anything from this problem
[jump-backspace-to-crash-0.49.18.sav.gz](https://github.com/MegaMek/megamek/files/14938674/jump-backspace-to-crash-0.49.18.sav.gz) - playername Weaver - this is just a pxh-1 by itself ready to move on turn one, so select 'jump' and hit backspace to crash it.

**Comment by kuronekochomusuke** [comment]
looks like it gets into an infinite loop here in MovementDisplay

```
        // Keep removing last step until it's a valid movement step.
        while (cmd.getLastStepMovementType() == EntityMovementType.MOVE_ILLEGAL) {
            removeLastStep();
            removed = true;
        }
```

**Comment by Lu9us** [comment]
It looks like this is due to an issue in `MovementDisplay.removeIllegalSteps()` as stated as it treats the start of the jump as Illegal since you can't end a jump without moving then when it is in the `MovementDisplay.removeLastStep()` this will call `cmd.removeLastStep()` which clears cmd's steps as expected  but when `MovementDisplay,clear()` is called it will re-add a `JumpStart` step because the UI is in jump mode which is once again deemed illegal causing an infinite loop.

**Comment by gsparks3** [comment]
Interestingly, that makes this related to #4970 - jumping into your starting hex *shouldn't* be illegal for non-infantry units. Although it would still be illegal for infantry, so you can't just use that as the fix instead, have to do both.

**Comment by Lu9us** [comment]
So this is pretty explictily excluded in `MoveStep.isLegalEndPos`: 

```
... 
else if (isJumping() && (distance == 0)) {
            // Can't jump zero hexes.
            legal = false;
}....
```

Not sure if the rules have changed since this code was written or I'm missing something.

**Comment by HoneySkull** [comment]
Thank you for the bug report @WeaverThree and for the fix @Lu9us.  I definitely did not anticipate removing move steps would also create move steps in the case of jump mode.  I feel like the fix by @Lu9us is consistent with the intent of the "undo" nature of the backspace key.
