### ISSUE TITLE
[49.19] - Damage Decals seems wrong

### ISSUE THREAD

**Issue by Thom293** [MegaMek/megamek#5355]
They just do.  These are all dead vehicles.  But they still look alive. Somthing has changed.  Honeyskull says looks like the crater decal is being rendered under the vehicle sprite.

![image](https://github.com/MegaMek/megamek/assets/23645569/96035485-d0fc-47fa-ad48-92acf3f59baa)

**Comment by HoneySkull** [comment]
I wasn't able to re-produce this effect - I wonder if it's related to specific vehicle sprites?

**Comment by Thom293** [comment]
Hmm. let me see if I have a save before this battle.

**Comment by Thom293** [comment]
Here you go.  Should just be able to hit start battle on the irregular forces battle.  Units are already assigned.  I just gave all of my units to princess and let it run a while.

[Crazed Profanity30700212.cpnx.gz](https://github.com/MegaMek/megamek/files/14968506/Crazed.Profanity30700212.cpnx.gz)
[Customs.zip](https://github.com/MegaMek/megamek/files/14968510/Customs.zip)

**Comment by Thom293** [comment]
Just ran the same battle again with same result.  For the record the dead units here are:

The dead vehicles that still look alive are - APCx2, Mash Truck, Heavy Battlemech Recovery Vehicle, Brunel Dumptruck, Flatbed Truck - So mostly civilian vehicles.

The craters are: Harvester, Crosscut, Pompier, J27 Ordinance Vehicle, Coolant Truck, 

There are dead mechs on other parts of the map, and they all look correctly damaged.

Does it randomly roll a "destroyed" decal?  Perhaps if there are more than one, maybe only one of them is messed up?

![image](https://github.com/MegaMek/megamek/assets/23645569/f69d1ee0-1528-48c0-97e6-d341b02555a8)

**Comment by HammerGS** [comment]
Some destroyed equipment is handled by the wreckset, other by the decals with the crater being a default.

Some of the decals are also linked to the type of damage the vehicles take.   Per this https://github.com/MegaMek/megamek/pull/2103

Things look right to me.

**Comment by Thom293** [comment]
Seems like they are missing the fire decal on top of them, but I guess I just remembered wrong.  Will close.
