### ISSUE TITLE
MekHQ 49.7 Stinger LAM STG-A5 is an Illegal Unit

### ISSUE THREAD

**Issue by Mr-ZenoUK** [MegaMek/megamek#5362]
### Environment
MekHQ 49.7
Windows 10
Java Vendor: Eclipse Adoptium
Java Version: 11.0.22

### Description
An illegal unit is added as an ally for a Planetary Assault campaign, FC v DC
I've looked at the unit in MegaMekLab and it validates ok.
If I continue no enemy forces are deployed and I automatically "win"

### Files
[Suffering Rolls30420524.cpnx.gz](https://github.com/MegaMek/megamek/files/14968637/Suffering.Rolls30420524.cpnx.gz)

[megamek.log](https://github.com/MegaMek/megamek/files/14968639/megamek.log)
[mekhq.log](https://github.com/MegaMek/megamek/files/14968640/mekhq.log)

![Illegal Unit Message](https://github.com/MegaMek/megamek/assets/161900868/f7e0e364-b05f-4448-ac77-c1added9a83e)
![Illegal Unit](https://github.com/MegaMek/megamek/assets/161900868/9d0f4485-0a5e-4400-9f4f-df1339578198)

**Comment by HoneySkull** [comment]
Saw this in the logs for future debugging info:

![image](https://github.com/MegaMek/megamek/assets/83041327/9e9677f5-c354-4edf-80ae-c4225ae99695)

**Comment by Sleet01** [comment]
The Stinger LAM STG-A5 is valid going back as far as 0.49.11 (the earliest I currently have installed) so I'm wondering if there might have been a miscalc due to gravity, or possibly damaged components?

Regardless, 0.49.7 is pretty long in the tooth now, and there have been a number of updates to the entire codebase.

@Mr-ZenoUK Can you load your campaign in a more recent MekHQ version, like 0.49.15 or .16, and see if the same issue occurs?

**Comment by Mr-ZenoUK** [comment]
> The Stinger LAM STG-A5 is valid going back as far as 0.49.11 (the earliest I currently have installed) so I'm wondering if there might have been a miscalc due to gravity, or possibly damaged components?
> 
> Regardless, 0.49.7 is pretty long in the tooth now, and there have been a number of updates to the entire codebase.
> 
> @Mr-ZenoUK Can you load your campaign in a more recent MekHQ version, like 0.49.15 or .16, and see if the same issue occurs?

I've just loaded the campaign into 49.18 and the same message has appeared.

**Comment by HammerGS** [comment]
I'm showing it valid in 0.49.7

**Comment by HammerGS** [comment]
> Two things come to mind. The first is the old bogus/illegal LAM designs in the Unofficial folder, with exactly matching chassis/model names with the proper ones causing problems in MekHQ OpFor generation. I remember fixing this by pulling the ...\data\mechfiles\Unofficial.zip file from the program directory. Later releases fixed these duplicate units.
> 

Bingo!
<img width="417" alt="image" src="https://github.com/MegaMek/megamek/assets/13752452/093eb4a4-ecbe-45cd-8f15-8cc6d164724f">
