### ISSUE TITLE
Turning throws an error message

### ISSUE THREAD

**Issue by DynamicWorlds** [MegaMek/megamek#5365]
### Environment
version 49.18 only (version 49.17 does not throw error)
Windows 10
Java Version: 11.0.18

### Description
When using Shift+A or Shift+D to turn, an error message is thrown up.
Does not seem to occur on first turn or first turn after loading.
To reproduce, load file, skip until next movement phase, and try turning with keyboard commands.
[Bug1.sav.gz](https://github.com/MegaMek/megamek/files/14984797/Bug1.sav.gz)
[megamek.log](https://github.com/MegaMek/megamek/files/14984798/megamek.log)
![Temp](https://github.com/MegaMek/megamek/assets/155043132/f0e67379-dce7-4abd-8015-e84e39d8fbbb)
Butte's Dragoons

**Comment by HammerGS** [comment]
Very likely fixed with https://github.com/MegaMek/megamek/pull/5351

**Comment by DynamicWorlds** [comment]
sorry, did a search for "shift" and it didn't turn up.  NM then
