### ISSUE TITLE
Princess error during fight

### ISSUE THREAD

**Issue by kipstafoo** [MegaMek/megamek#537]
Getting error below during fight deployed from MHQ:

java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    megamek/client/bot/princess/BotGeometry.debugSelfTest(Lmegamek/client/bot/princess/Princess;)V @113: aload_2
  Reason:
    Type top (current frame, locals[2]) is not assignable to reference type
  Current Frame:
    bci: @113
    flags: { }
    locals: { 'megamek/client/bot/princess/Princess', top, top, top, 'java/lang/StringBuilder', 'megamek/common/Coords', '[Lmegamek/client/bot/princess/BotGeometry$HexLine;', integer }
    stack: { 'java/lang/StringBuilder' }
  Bytecode:
    0x0000000: bb00 0259 1203 b700 043a 04bb 0005 5907
    0x0000010: 1006 b700 063a 0510 06bd 0007 3a06 0336
    0x0000020: 0715 0710 06a2 001a 1906 1507 bb00 0759
    0x0000030: 1905 1507 2ab7 0008 5384 0701 a7ff e519
    0x0000040: 0412 09b6 000a 5704 3607 0336 0815 0810
    0x0000050: 06a2 0019 1906 1508 3219 05b6 000b 9900
    0x0000060: 0603 3607 8408 01a7 ffe6 1904 1507 9900
    0x0000070: 072c a700 042d b600 0a57 1904 120c b600
    0x0000080: 0a57 0436 0703 3608 1508 1006 a200 3519
    0x0000090: 0615 0832 1905 1508 b600 0db6 000b 9a00
    0x00000a0: 1a19 0615 0832 1905 1508 0660 1006 70b6
    0x00000b0: 000d b600 0b99 0006 0336 0784 0801 a7ff
    0x00000c0: ca19 0415 0799 0007 2ca7 0004 2db6 000a
    0x00000d0: 5704 3607 1904 120e b600 0a57 0336 0815
    0x00000e0: 0810 06a2 0075 0219 0615 0832 1905 1508
    0x00000f0: 0860 1006 70b6 000d b600 0b9f 0006 0336
    0x0000100: 0702 1906 1508 3219 0515 0807 6010 0670
    0x0000110: b600 0db6 000b 9f00 0603 3607 0419 0615
    0x0000120: 0832 1905 1508 0460 1006 70b6 000d b600
    0x0000130: 0b9f 0006 0336 0704 1906 1508 3219 0515
    0x0000140: 0805 6010 0670 b600 0db6 000b 9f00 0603
    0x0000150: 3607 8408 01a7 ff8a 1904 1507 9900 072c
    0x0000160: a700 042d b600 0a57 0436 07bb 0005 5904
    0x0000170: 04b7 0006 3a08 bb00 0559 0604 b700 063a
    0x0000180: 09bb 0005 5905 06b7 0006 3a0a bb00 0f59
    0x0000190: 2ab7 0010 3a0b 190b 1908 b600 1119 0b19
    0x00001a0: 09b6 0011 190b 190a b600 112a 1212 1213
    0x00001b0: 1214 b600 1519 0412 16b6 000a 5719 0bbb
    0x00001c0: 0005 5904 04b7 0006 b600 179a 0006 0336
    0x00001d0: 0719 0bbb 0005 5905 04b7 0006 b600 179a
    0x00001e0: 0006 0336 0719 0bbb 0005 5906 04b7 0006
    0x00001f0: b600 179a 0006 0336 0719 0bbb 0005 5904
    0x0000200: 05b7 0006 b600 179a 0006 0336 0719 0bbb
    0x0000210: 0005 5905 05b7 0006 b600 179a 0006 0336
    0x0000220: 0719 0bbb 0005 5906 05b7 0006 b600 179a
    0x0000230: 0006 0336 0719 0bbb 0005 5905 06b7 0006
    0x0000240: b600 179a 0006 0336 0719 0415 0799 0007
    0x0000250: 2ca7 0004 2db6 000a 5704 3607 1904 1218
    0x0000260: b600 0a57 190b bb00 0559 0304 b700 06b6
    0x0000270: 0017 9900 0603 3607 190b bb00 0559 0403
    0x0000280: b700 06b6 0017 9900 0603 3607 190b bb00
    0x0000290: 0559 0503 b700 06b6 0017 9900 0603 3607
    0x00002a0: 190b bb00 0559 0603 b700 06b6 0017 9900
    0x00002b0: 0603 3607 190b bb00 0559 0704 b700 06b6
    0x00002c0: 0017 9900 0603 3607 190b bb00 0559 0705
    0x00002d0: b700 06b6 0017 9900 0603 3607 190b bb00
    0x00002e0: 0559 0706 b700 06b6 0017 9900 0603 3607
    0x00002f0: 190b bb00 0559 0606 b700 06b6 0017 9900
    0x0000300: 0603 3607 190b bb00 0559 0507 b700 06b6
    0x0000310: 0017 9900 0603 3607 190b bb00 0559 0406
    0x0000320: b700 06b6 0017 9900 0603 3607 190b bb00
    0x0000330: 0559 0306 b700 06b6 0017 9900 0603 3607
    0x0000340: 190b bb00 0559 0305 b700 06b6 0017 9900
    0x0000350: 0603 3607 1904 1507 9900 072c a700 042d
    0x0000360: b600 0a57 2a12 1212 13b2 0019 1904 b600
    0x0000370: 1aa7 0015 3a0c 2a12 1212 13b2 0019 1904
    0x0000380: b600 1a19 0cbf b1                      
  Exception Handler Table:
    bci [11, 868] => handler: 884
    bci [884, 886] => handler: 884
  Stackmap Table:
    full_frame(@33,{Object[#40],Top,Top,Top,Object[#41],Object[#42],Object[#43],Integer},{})
    chop_frame(@63,1)
    append_frame(@77,Integer,Integer)
    same_frame(@100)
    chop_frame(@106,1)
    same_locals_1_stack_item_frame(@117,Object[#41])
    full_frame(@118,{Object[#40],Top,Top,Top,Object[#41],Object[#42],Object[#43],Integer},{Object[#41],Object[#44]})
    append_frame(@136,Integer)
    same_frame(@184)
    same_frame(@187)
    chop_frame(@193,1)
    same_locals_1_stack_item_frame(@204,Object[#41])
    full_frame(@205,{Object[#40],Top,Top,Top,Object[#41],Object[#42],Object[#43],Integer},{Object[#41],Object[#44]})
    append_frame(@223,Integer)
    same_frame(@257)
    same_frame(@284)
    same_frame(@311)
    same_frame(@338)
    chop_frame(@344,1)
    same_locals_1_stack_item_frame(@355,Object[#41])
    full_frame(@356,{Object[#40],Top,Top,Top,Object[#41],Object[#42],Object[#43],Integer},{Object[#41],Object[#44]})
    full_frame(@465,{Object[#40],Top,Top,Top,Object[#41],Object[#42],Object[#43],Integer,Object[#42],Object[#42],Object[#42],Object[#45]},{})
    same_frame(@485)
    same_frame(@505)
    same_frame(@525)
    same_frame(@545)
    same_frame(@565)
    same_frame(@585)
    same_locals_1_stack_item_frame(@596,Object[#41])
    full_frame(@597,{Object[#40],Top,Top,Top,Object[#41],Object[#42],Object[#43],Integer,Object[#42],Object[#42],Object[#42],Object[#45]},{Object[#41],Object[#44]})
    same_frame(@632)
    same_frame(@652)
    same_frame(@672)
    same_frame(@692)
    same_frame(@712)
    same_frame(@732)
    same_frame(@752)
    same_frame(@772)
    same_frame(@792)
    same_frame(@812)
    same_frame(@832)
    same_frame(@852)
    same_locals_1_stack_item_frame(@863,Object[#41])
    full_frame(@864,{Object[#40],Top,Top,Top,Object[#41],Object[#42],Object[#43],Integer,Object[#42],Object[#42],Object[#42],Object[#45]},{Object[#41],Object[#44]})
    full_frame(@884,{Object[#40],Top,Top,Top,Object[#41]},{Object[#46]})
    same_frame(@902)

	at megamek.client.bot.princess.Princess.initialize(Princess.java:1123)
	at megamek.client.bot.BotClient.toggleStealth(BotClient.java:913)
	at megamek.client.bot.BotClient.changePhase(BotClient.java:299)
	at megamek.client.Client.handlePacket(Client.java:1301)
	at megamek.client.bot.princess.Princess.handlePacket(Princess.java:1265)
	at megamek.client.Client$1$2.run(Client.java:219)

[GG-Princess-Bug.sav.gz](https://github.com/MegaMek/megamek/files/943064/GG-Princess-Bug.sav.gz)

**Comment by pjfarland** [comment]
The error has continued for turns afterward. Each turn Princes freezes up partway through the turn.
[Bug2.zip](https://github.com/MegaMek/megamek/files/1294112/Bug2.zip)

**Comment by pjfarland** [comment]
Again: I've been playing through, /skip on the errors; now it's failing on the /skip command. Tried kicking the bot and replacing it and /skipping again. No dice.
[Bug3.zip](https://github.com/MegaMek/megamek/files/1294167/Bug3.zip)

**Comment by pjfarland** [comment]
I don't know how mine got switched to this issue. Sorry, my issue has nothing to do with pavement.

**Comment by neoancient** [comment]
This appears to be an error with Java.
