### ISSUE TITLE
Princess GE AI

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#539]
I tested what people were reporting on the forums and it is true that princess does not rotate the turret on gun emplacements.  If you walk into her firing arc she will fire at you like she has done to me but, right now turrets might as well be static emplacements to her.

Requiring the player to deploy her turrets we can live with but, can her AI code for operating a vee's turret be copied for use when firing a gun emplacement?  Obviously she still will not do anything with arty turrets and will require a human player for that case but, getting her to operate the turrets right now would be great and I wont feel like I wasted so much time making all those new turret icons lol.

**Comment by NickAragua** [comment]
This code for this is in pull request #578.

**Comment by BLOODWOLF333** [comment]
Thank you we were needing that.
