### ISSUE TITLE
Infantry/Battle Armor interior fights (or inside buildings) are not calculating damage correctly

### ISSUE THREAD

**Issue by VictorMorson** [MegaMek/megamek#54]
Infantry when inside the same multi-hex building are supposed to be able to engage and damage each other.  Megamek seems to be taking the interior conditions (or being up/down a level in the building) into account properly, adding difficulties to the shot and even referencing damage the building takes relative to what the rival infantry/BA take for damage; it also references debris falling on them.

However, 0 damage is dealt to the BA/Infantry unit, instead the building soaking the entire amount of damage.  This may also be an extension of an issue where shooting a hex of a building with infantry unit will also trigger debris messages, but still result in 0 damage (building absorbs it all).  It seems as if the building damage-absorption may be overriding the proper effects, leaving infantry in a very strong building impossible to harm until the entire building is destroyed.

Steps to repro:
1) Place an infantry unit in the 2nd floor of a CF155 4-hex building.
2) Place other infantry units below them and 1 hex away, as well as on the same floor 1 hex away.
3) Place a 'mech outside of the hex.
4) All infantry units and the 'mech should attempt to attack the hex with the first infantry unit placed.
5) Note that Megamek mentions the cover and debris, and seems to calculate these shots, but will deal 100% damage to the building instead.

**Comment by pheonixstorm** [comment]
What class building is it. Certain building types soak up greater amounts of damage before it gets to the infantry.

**Comment by arlith** [comment]
There's already a bug ticket for this on the SourceForge tracker: https://sourceforge.net/p/megamek/bugs/4186/.

**Comment by VictorMorson** [comment]
Are there any plans to update the issue?  It unfortunately renders infantry unplayable in urban environments, as they are entirely immune to counter-attack.
