### ISSUE TITLE
LTV-4 tank in force generator files doesn't match unit name

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#5407]
The force generator XML files in ...\data\forcegenerator\ list the LTV-4 as:
https://github.com/MegaMek/megamek/blob/a0ed7c0ad75589d86f887b5d309b67a53348c687/megamek/data/forcegenerator/2460.xml#L604-L606

(also note the model element is missing)
This is typical for all eras.

The unit name in MML is listed as:
Chassis - Hawk Hover Tank
Model - (LTV-4)

... which matches the MUL.

**Comment by SJuliez** [comment]
This is true but the LTV4 is covered by the name changes list and appears to work (no force generator log messages). Therefore closing this.
