### ISSUE TITLE
iATMs do not work correctly in weapon bays

### ISSUE THREAD

**Issue by Saklad5** [MegaMek/megamek#5419]
### Environment
MegaMek Version: MekHQ v0.49.19 Development Snapshot
Operating System: Mac
Java Version: 20.0.1

### Description

iATMs do not work correctly in ATM Bays, being limited to Medium range and allowing a choice of ammo within those brackets. Curiously, the original ATMs _do_ work correctly. This can be demonstrated in the attached screenshots, using the attached designs and save file.
![image](https://github.com/MegaMek/megamek/assets/4258823/df2aea1c-62d8-4a3b-8fb4-6a013346b45c)
![image-2](https://github.com/MegaMek/megamek/assets/4258823/8d5e7e15-dd2c-440c-afa9-dbec07a8582f)
[atmBayRangeExample.sav.gz](https://github.com/MegaMek/megamek/files/15114710/atmBayRangeExample.sav.gz)
[Union_C_C-Ph_Mk_IV.blk](https://github.com/MegaMek/megamek/files/15114756/Union_C_C-Ph_Mk_IV.blk.txt)

**Comment by Sleet01** [comment]
Tragically, it looks like Large Craft arcs and some parts of ammo selection have also been broken by recent commits, so this is taking a little longer to fix than I expected.
