### ISSUE TITLE
[49.19] Soft lock when attempting to fire Arrow IV from airborne Dropship.

### ISSUE THREAD

**Issue by Nehvar** [MegaMek/megamek#5427]
Attempting to fire an Arrow IV from an airborne Dropship (Aerodyne, if that matters.) results in a "NullPointerException" and the inability to continue the game.

![01](https://github.com/MegaMek/megamek/assets/59345488/4bcac2ba-96bf-40d7-8308-d4165ff38d08)

The "Skip Firing" button, while not grayed out, is unusable.  Also, using the /reset command after this soft lock will take me back to the lobby but leave me unable to add units to the game.

EDIT:

Here is a save from the lobby, a save from after the bug, a log from immediately after the test and a .blk for the test dropship (no canon aerodyne dropships have Arrow IV's).

[DropshipAIV.zip](https://github.com/MegaMek/megamek/files/15140479/DropshipAIV.zip)

**Comment by HammerGS** [comment]
Do you have logs and a save game. Logs would be critical.

**Comment by Nehvar** [comment]
Thought I had uploaded one.  I'll update the first post with a newer log.

**Comment by Sleet01** [comment]
@Nehvar this is AIVs from an Artillery Bay as opposed to IBB, correct?

**Comment by Nehvar** [comment]
Correct.
