### ISSUE TITLE
[49.19] [Quirk] Internal Bomb Bay does not fully function on a Dropship.

### ISSUE THREAD

**Issue by Nehvar** [MegaMek/megamek#5428]
A Dropship with the Internal Bomb Bay quirk can select bombs in the MegaMek lobby but has no options to use them in-game.  The weapons lists does not display IBB Arrow IV's during the artillery phase nor does it have entries for "Dive Bomb" or "Altitude Bomb" options during the weapon attack phase.

EDIT:

Selecting bombs in the lobby...

![02](https://github.com/MegaMek/megamek/assets/59345488/d53bd8c1-6fc8-4150-a215-d65d60695320)

Bombs appearing in-game under the general tab.

![03](https://github.com/MegaMek/megamek/assets/59345488/64d90610-94d7-41eb-933b-54ec362a29d8)

No right-click option to target a hex for bombing during the weapon attack phase nor a "Dive Bomb" or "Altitude Bomb" option in weapons list.

![04](https://github.com/MegaMek/megamek/assets/59345488/9cba7a4b-7020-481c-b453-b458ddfacc08)

It's just a Leopard configured with the IBB quirk but here's a log and save too.

[megamek.log](https://github.com/MegaMek/megamek/files/15140258/megamek.log)
[BombLeopardMMSave.sav.gz](https://github.com/MegaMek/megamek/files/15140262/BombLeopardMMSave.sav.gz)

**Comment by Sleet01** [comment]
Please post your game logs, and if possible a picture of your game board and a save game or .mul file containing your teams or units

**Comment by Sleet01** [comment]
@Nehvar I would have sworn on my life that this was working from the beginning of the IBB work, but it looks like Large Craft bombs, while loadable, are not usable in-game (as you discovered).

There's currently an issue with our dev branch so it may take a little while to get this fix done and checked in, but I'll get it done.

**Comment by Sleet01** [comment]
Currently blocked by #5569
