### ISSUE TITLE
Text Entry box issues on High DPI monitors (4K)

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#543]
Post this from a Facebook question.

A java question... i am using a Surface Book with resolution at default (3000 x 2000). Text entry fields in Mega Mek appear as slits. I have adjusted resolution and text sizes in windows with no improvement. Is there a java setting that I can adjust?

I've experienced this as well on my laptop (4k screen).  I found a workaround on google but didn't have the link anymore.

Edit...

Think this might have been the link
https://superuser.com/questions/988379/how-do-i-run-java-apps-upscaled-on-a-high-dpi-display

**Comment by BruthaB** [comment]
snip1 shows squished text on game setup screen.  snip2 shows minimized text boxes during Random Army generation.
![snip1](https://cloud.githubusercontent.com/assets/28353093/25665795/423ebda6-2fe4-11e7-9a4e-7c7b7084b2f1.PNG)
![snip2](https://cloud.githubusercontent.com/assets/28353093/25665798/43657e5e-2fe4-11e7-9cfa-879e7905936d.PNG)

**Comment by HammerGS** [comment]
Their is another game I play with similar issues. This is their work around and has worked for me in past.

1) On your OS display settings, set the resolution to 1920x1080, and the "size if text, apps and other items" (a.k.a. DPI setting) to 100% (or 125% if you want to experiment). 

2) Log off your Windows session and log-in back again (This is essential! Windows 10 allows changing the DPI settings without forcing you to log-off, but many apps and indeed even many Windows UI elements will be distorted if you don't. ) 

3) Start up game. The revised DPI settings will be detected and java will adjust itself to them. The UI elements should now render properly and without issues.

**Comment by kuronekochomusuke** [comment]
#3983 should fix this

**Comment by Windchild292** [comment]
Resolved in #3983
