### ISSUE TITLE
Hover over tooltip displays BV?

### ISSUE THREAD

**Issue by molemanBT** [MegaMek/megamek#544]
Hi, any chance we can include the BV in the hover over tool tip when in battle? When I have to hit 50% of enemy destroyed and I know that I need 1000 more BV to hit it, it would be great to easily check whether the guy I'm targeting will hit the magic number.

Had a quick look and couldn't find this requested elsewhere.

Thanks!

**Comment by BLOODWOLF333** [comment]
Thomas Marik requested this already #479
