### ISSUE TITLE
Can get bogged down on pavement

### ISSUE THREAD

**Issue by kipstafoo** [MegaMek/megamek#546]
Terrain: Heavy Urban
Map: Town-concrete
Weather: Torrential Downpour

So... everything other than pavement is shown as mud. The issue is that there is apparently mud under the pavement because mechs are getting bogged down jumping on to pavement.

Unless this is some sort of new quicksand-pavement, me thinks this here be a bug. :)

**Comment by kipstafoo** [comment]
After further review, there's other issues. Notably, if you stay on the pavement, you don't need to make bogged-down rolls, but if you transition off/on pavement, then you need to make rolls for every pavement hex.

**Comment by arlith** [comment]
A saved game would be super helpful for this.  At the very least, a map.

**Comment by pheonixstorm** [comment]
TO p59

> A torrential downpour automatically includes all modifiers and effects of mud (see p. 50); mud occurs in every hex across the playing area except for water hexes of Depth 1+, standard roads and building hexes. Additionally, all Depth 0 water hexes become swamp hexes (see p. 51). Torrent: A torrential downpour automatically includes all modifiers and effects of torrents (see p. 52) for any Depth 1 or deeper water hexes on the playing area.

While the rules say nothing of pavement they do mention Roads so I would think that pavement should not be affected either. @arlith do you think this may need a rules clarification?

I tested this out on the City Ruins map. Round one, Wasp jumps into pavement hex and gets stuck. Wolverine runs from pavement to road and requires PSR for turning while running. None for bog-down. Turn two Wasp jumps onto road, no bog down check while Wolverine jumps from road to pavement and gets stuck.

MM v0.43.2
[savegame.sav.gz](https://github.com/MegaMek/megamek/files/999029/savegame.sav.gz)

**Comment by arlith** [comment]
I think that pavement counts as a road.  To my knowledge, pavement generally gets treated as a road in the rest of the MM code.
