### ISSUE TITLE
Prowler Multi-Terrain Vehicle is overweight/misconfigured in 49.19

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#5460]
The Prowler Multi-Terrain Vehicle has cargo allocated both from the Transport box on the Structure/Armor tab as well as equipment under the Equipment tab.  This results in an overweight design.  Additionally, the cargo allocated under the Equipment tab is added in separate 1-ton/half-ton pieces rather than a unitary 4.5 ton bay.

This can be fixed by removed the cargo entries from the Equipment list.  It also requires tweaking the transport bay weight on the Structure/Equipment tab up/down, likely to force some kind of data rebuild, otherwise the weight is accurate but is still in discrete 1- or half-ton pieces on the preview.

This applies to the following models:

- 'Standard'/blank
- (ECM)
- (Succession Wars)
- (Sealed)

**Comment by Gribbly1** [comment]
Same issue with all of these units:
![image](https://github.com/MegaMek/megamek/assets/55139229/06d5ee25-99c2-4bf6-8e1d-999a4e1a97a0)
