### ISSUE TITLE
[Nightly] Bay does not have the minimum 10 shots of ammo for each weapon

### ISSUE THREAD

**Issue by repligator** [MegaMek/megamek#5471]
### Environment
v0.49.20-SNAPSHOT Build Date: 2024-05-14T01:10:55.921805912, Linux, Java 17.0.10

### Description
All drop-ships that use weapon bays which require ammo (ballistic and missile) are currently invalid because "bay (insert bay here) Bay does not have the minimum 10 shots of ammo for each weapon. They are all fine in .19. I've tried manually removing and reinserting the ammo in Meklab, which does not solve the problem.

**Comment by SJuliez** [comment]
I think was fixed by #5465. Therefore closing it.
