### ISSUE TITLE
[49.19.1] Incorrect range for Pulse Laser Rifle (Clan)

### ISSUE THREAD

**Issue by Nehvar** [MegaMek/megamek#5474]
The infantry weapon "Pulse Laser Rifle [Clan]" is set to a base range of 0 instead of the 2 that it should be.

![Untitled](https://github.com/MegaMek/megamek/assets/59345488/ca96a3fb-8a8b-4964-87bc-8e1f40f73eae)

**Comment by HammerGS** [comment]
Fixed with https://github.com/MegaMek/megamek/commit/c619365f0815a0e161f1cc89febf5ee91a38af97
