### ISSUE TITLE
[0.49.19.1] Bug/errata: Support vehicle armour critical slots

### ISSUE THREAD

**Issue by Gribbly1** [MegaMek/megamek#5476]
Bundled Megamek with MekHQ 0.49.19.1
Windows 10, Java Version: 11.0.13

Related to this forum question: https://bg.battletech.com/forums/index.php?topic=84165.0

Support vehicles with tech level E or F BAR 10 armour are currently determining equipment slot usage using mech critical spaces, eg 14 for IS ferro fibrous equivalent.

It's likely BAR 10 armour slots should be based upon combat vehicle equipment slots, p105 TM.

Alternatively the wording on p134 Tech manual suggests that armour might not use any equipment slots in support vehicles.

![image](https://github.com/MegaMek/megamek/assets/55139229/c2bb7de4-d8bb-40f6-b636-316f2966fe4b)

Please adjust the implementation when this is clarified.

**Comment by HammerGS** [comment]
Errata has been issued.

https://bg.battletech.com/forums/index.php?topic=84165.msg1993603#msg1993603

We've been asked to update our code so any SV impacted can issue errata for any impacted units. 


```
Tech Manual, pg 134

Under Space Section:

Replace:
"Under these rules, no armor type available to Support Vehicles reduces their equipment slot space"

With:

"Except for Tech Level E-BAR 10 and Tech Level F-BAR 10, no armor type available to Support Vehicles reduces their equipment slot space."

Replace the footnote on the SUPPORT VEHICLE ARMOR TABLE:

From:
"†At Tech Ratings E and F, BAR 10 Armor occupies slot space equal to that of Inner Sphere and Clan Ferro-Fibrous Armor types (respectively)."

To:
"At Tech Ratings E and F, BAR 10 Armor occupies slot space equal to that of Inner Sphere and Clan Ferro-Fibrous Armor types (respectively). See COMBAT VEHICLE ARMOR TABLE pg 105."

Also in  Tac Ops: AUE pg 189
Under the PATCHWORK ARMOR TABLE under Vehicular Stealth.

add the following to the table
"BAR 10 TL E = 2/1”
“BAR 10 TL F = 1/1"
```
