### ISSUE TITLE
Cannot load protomechs with any weapon quirks

### ISSUE THREAD

**Issue by Xeno426** [MegaMek/megamek#5482]
### Environment
megameklab.MegaMekLab.initializeLogging(MegaMekLab.java:53) - Starting MegaMekLab v0.49.19.1
	Build Date: 2024-05-10T20:11:07.453164161
	Today: 2024-05-17
	Origin Project: MegaMekLab
	Java Vendor: Eclipse Adoptium
	Java Version: 11.0.14
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMekLab: 1 GB

### Description
Attempting to load a protomech that uses any weapon quirk creates the error in the attached image. In 0.49.19, such units would appear in the load unit cache, but selecting them would show a blank preview screen. In 0.49.19.1, the unit does not even show up in the load from cache dialog box.

I've attached an example protomech as well.

### Files
![MML error protomech accurate weapon quirk](https://github.com/MegaMek/megamek/assets/3220418/188b05b9-a5b9-41f3-8011-24fdb0973fe5)
[Nixie Ultraheavy Omni-Proto Prime-SC.zip](https://github.com/MegaMek/megamek/files/15355604/Nixie.Ultraheavy.Omni-Proto.Prime-SC.zip)

**Comment by Xeno426** [comment]
As an update, I'm getting the same error if I use *any* weapon quirk on a protomech.

**Comment by HammerGS** [comment]
12:32:26,786 ERROR [megamek.common.MechFileParser] {AWT-EventQueue-0}
megamek.common.MechFileParser.<init>(MechFileParser.java:50) - 
```
megamek.common.loaders.EntityLoadingException: Error loading unit quirks!
	at megamek.common.loaders.BLKFile.loadQuirks(BLKFile.java:140)
	at megamek.common.loaders.BLKProtoFile.getEntity(BLKProtoFile.java:123)
	at megamek.common.MechFileParser.parse(MechFileParser.java:159)
	at megamek.common.MechFileParser.<init>(MechFileParser.java:48)
	at megamek.common.MechFileParser.<init>(MechFileParser.java:41)
	at megameklab.ui.MenuBar.loadUnitFromFile(MenuBar.java:1162)
	at megameklab.ui.MenuBar.lambda$createLoadMenu$15(MenuBar.java:305)
```
