### ISSUE TITLE
StackOverflowError Hex.java When Changing Tileset Theme

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#549]
Started game with BW - Default skin and atmospheric tileset.  Changed skin to BW - Federated Suns and then BW atmospheric tileset.  Noticed no problems during gameplay testing DancefloorLandmine's new map.  But log shows a stockoverflow so, not sure if its the map or my changing of the tileset that caused this?

Exception in thread "AWT-EventQueue-0" java.lang.StackOverflowError

Player Name: BLOODWOLF
custom map included
[StackcOverflow.zip](https://github.com/MegaMek/megamek/files/998894/StackcOverflow.zip)

**Comment by arlith** [comment]
Can you reproduce this?

**Comment by BLOODWOLF333** [comment]
Tried to duplicate on a standard one map sheet map and changing the tileset, no errors.
Tried on the drop port map on home laptop Win8.1 HQ 0.42.0 and just mechs this time and changing the tileset and skin, no errors.
....Gremlins.
