### ISSUE TITLE
Aerospace Atmopsheric Ranges incorrect

### ISSUE THREAD

**Issue by VictorMorson** [MegaMek/megamek#55]
It seems that Aerospace weapons ranges inside of an atmosphere are calculating incorrectly; I would guess they may be using the space range conversion on board.  A medium laser will be within short range at over 32 hexes away.

Steps to reproduce:
1) Add an Aerospace Fighter and deploy it onto a large map
2) Add a second Aerospace fighter to target
3) Proceed to the firing phase and note the extreme weapon ranges

**Comment by HammerGS** [comment]
Pretty sure this rule is in play...

Aerospace Units on Ground Mapsheets - TW 4th Ed pg 242
_If players are using the Aerospace Units on Ground Mapsheets rules (p. 91) and an airborne aerospace unit launches an attack against another airborne aerospace unit, keep in mind that the
ranges for such weapon attacks must be multiplied by 16 to fall into line with the necessary changes of scale. For example, the standard-scale short range bracket would extend to 96 hexes, while the standard-scale medium range bracket would extend to 192 hexes, and so on. Likewise, players would need to multiply the capital-scale ranges by 16._

**Comment by HammerGS** [comment]
Closing as invalid

**Comment by VictorMorson** [comment]
I'm looking up some info with Cataylst on this; it seems like it may be a bug after all.  I am near positive now that the 16x range modifier is intended for a "zoomed out" flight level, and not when the unit is FL 8 or below; right now the result is that an small laser can shoot anywhere in the map at FL2, which seems incredibly off.

How would I re-open the issue once I have confirmation from Cataylst this is inaccurate?  (I am concerned because ASF is ridiculous right now ; you cannot get into the long range bracket even on massive maps on-board.)

**Comment by arlith** [comment]
I'm not sure if you can re-open it, but if you request it be reopened, we can.  Can it wait to hear back from CGL?
