### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by Logajam** [MegaMek/megamek#5502]
### Environment
49.19
### Description
nullpointer exception.

Created a custom unit.  Testing to see what happens with infantry weapons on small support vehicles.
Used a wasp as target practice.  The game broke.  See attached files.

Incidentally github doesn't like .blk files.

### Files

[megamek.log](https://github.com/MegaMek/megamek/files/15424517/megamek.log)
[Test Drone Swarm.zip](https://github.com/MegaMek/megamek/files/15424547/Test.Drone.Swarm.zip)
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/15424552/autosave.sav.gz)

**Comment by Sleet01** [comment]
Quick question, are you using the Milestone release (should say "0.49.19.**1**" in logs) or the pre-Milestone 0.49.19 release?  There are a number of bug fixes in the former that might get around this issue... although to be honest, we are unlikely to support manually-created units.

**Comment by gsparks3** [comment]
Infantry weapons on _small_ support vehicles (the sub-5-ton ones built in kg scale) are valid under the existing rules, and should therefore get support. I wonder if this is another one of those "CI ammo"-related bugs?

**Comment by Sleet01** [comment]
> Infantry weapons on _small_ support vehicles (the sub-5-ton ones built in kg scale) are valid under the existing rules, and should therefore get support. I wonder if this is another one of those "CI ammo"-related bugs?

Ah, I see.  I read that as a manual edit, but you're right, it's supported in MML.
It likely is related to how CI weapons have "ammo" but not Ammo; the Exception in the logs is just our code trying to get the linked Ammo Equipment and getting a null instead.
