### ISSUE TITLE
[49.20] Issue : Firing angles no longer dynamically adapts

### ISSUE THREAD

**Issue by RaozSpaz** [MegaMek/megamek#5507]
### Environment
49.20
Windows
Java 11

### Description
![image](https://github.com/MegaMek/megamek/assets/132851640/f9b2310f-a353-4b6f-97f8-315aa277fa20)
In prior versions of megamek, whenever you rotated a mech's torso or a tank's turret, the firing angles would dynamically adjust to the new direction giving you immediate feedback on what was now in your targeting ranges. In 49.20 this feature has seemed to been removed or broken [most likely broken]. As shown in the picture the Rifleman is facing downwards, but the firing angle is still showing based on its forward view. Clicking skip or changing to a different weapon will fix the issue, but having it do so dynamically again would be a great QoL.

### Files
No files needed. This should be repeatable in any instance of megamek with extreme ease. Load the game, deploy units, and try to switch your firing angle.

**Comment by Sleet01** [comment]
I've been seeing this in my testing as well.  Not sure if I broke this but I've touched the code recently so I'll take a look.

**Comment by Sleet01** [comment]
Marking "Blocker" as it's a pretty bad UX regression.

**Comment by Sleet01** [comment]
From `git bisect`:

```
99b0bff2c9306c62e7609f9d97161fba388c4808 is the first bad commit
commit 99b0bff2c9306c62e7609f9d97161fba388c4808
Author: Simon <juliez@outlook.de>
Date:   Sun May 12 10:42:43 2024 +0200

    remove unnecessary code from WeaponPanel, comments

 megamek/src/megamek/client/ui/swing/ClientGUI.java |  38 +-
 .../megamek/client/ui/swing/DeploymentDisplay.java |  10 +-
 .../src/megamek/client/ui/swing/FiringDisplay.java |   4 +-
 .../megamek/client/ui/swing/MovementDisplay.java   |  32 +-
 .../client/ui/swing/PointblankShotDisplay.java     |   4 +-
 .../megamek/client/ui/swing/PrephaseDisplay.java   |   4 +-
 .../client/ui/swing/StatusBarPhaseDisplay.java     |  22 --
 .../client/ui/swing/TargetingPhaseDisplay.java     |   4 +-
 .../client/ui/swing/boardview/BoardView.java       | 193 ----------
 .../ui/swing/boardview/FiringArcSpriteHandler.java | 408 +++++++++++++++++++++
 .../client/ui/swing/unitDisplay/UnitDisplay.java   |   5 +-
 .../client/ui/swing/unitDisplay/WeaponPanel.java   | 168 +--------
 megamek/src/megamek/common/Mounted.java            |  34 +-
 13 files changed, 485 insertions(+), 441 deletions(-)
 create mode 100644 megamek/src/megamek/client/ui/swing/boardview/FiringArcSpriteHandler.java
 ```
