### ISSUE TITLE
BA Experience no Fatigue Penalties

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#552]
I played a very long game against some elementals. Pfarland, my opponent, tells me he never suffered a fatigue penalty. I am attaching a save game from 40ish rounds into the game. Fatigue was enabled and my mechs were suffering from it. 

[BAnoFatigue.sav.gz](https://github.com/MegaMek/megamek/files/1008626/BAnoFatigue.sav.gz)

**Comment by arlith** [comment]
If I load the saved game up, the BA are getting the fatigue penalty when firing.
