### ISSUE TITLE
[0.49.19.1] Squadrons only fire energy weapons

### ISSUE THREAD

**Issue by EvilAtlas** [MegaMek/megamek#5523]
### Environment
HQ's MegaMek 0.49.19.1
Windows 11
Java 11.0.14.1

### Description
When I fire at a warship (and probably other things) with a squadron, the only weapons that appear as firing in the firing report are the energy weapons. The other weapons use ammunition but don't roll to hit or (as far as I can tell) do damage.
The included saves are from multiple turns in the battle where this issue cropped up. Any shots taken at the Concordat should have this issue.

### Files
[squadron_shooting_bug.zip](https://github.com/MegaMek/megamek/files/15480807/squadron_shooting_bug.zip)
Player name: Evil Atlas

**Comment by repligator** [comment]
024-05-26T01:18:15.080647720
Linux
Java 17.0.10

I've had similar issues with attacks vanishing.
[megamek.log](https://github.com/MegaMek/megamek/files/15488754/megamek.log)
[where.sav.gz](https://github.com/MegaMek/megamek/files/15488760/where.sav.gz)
![Screenshot_20240529_133017](https://github.com/MegaMek/megamek/assets/114337591/504d100a-e2b5-4aac-9908-52b9763acc20)
