### ISSUE TITLE
[0.43.2-git : Bug] Dropship Cannot Unload

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#553]
Load save game, dropship unload units at either 3528 or 3930 (only 2 available space). Nothing happens after unload, unit failed to exit the dropship. No error in log file. Savegame attached.

[DropshipCannotUnload.sav.gz](https://github.com/MegaMek/megamek/files/1015867/DropshipCannotUnload.sav.gz)

**Comment by neoancient** [comment]
This fixes the problem of being unable to load a unit, but it doesn't fix the problem that the movement immediately ends. A dropship should be able to unload one unit per working door.

**Comment by SJuliez** [comment]
Unloading from DS has been addressed multiple times since. I don't believe this issue is valid anymore. Therefore closing this.
