### ISSUE TITLE
RLWeapon returning as indirect fire

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#5538]
Method here should probably return false:

https://github.com/MegaMek/megamek/blob/242b2280e8ca014f6aeec853b1ff8baff81533d8/megamek/src/megamek/common/weapons/missiles/RLWeapon.java#L65-L68

**Comment by SJuliez** [comment]
Hmm true, BMM p103 says so.

**Comment by ramgarden** [comment]
This is a very simple fix.  I can take a look at this today.
