### ISSUE TITLE
[Nightly] Game never progresses beyond round 7

### ISSUE THREAD

**Issue by repligator** [MegaMek/megamek#5542]
### Environment
2024-05-31T01:13:33.430985946
Linux
17.0.10

### Description
I was playing a game, which was progressing as normal, until the end of round 7. Round 8 never began. Instead round 7 happened again. Then again. The game state progressed, things that were dead stayed dead etc., but round 8 never started. According to the logs, round 7 happened multiple times. I probably wouldn't have noticed if I didn't have reinforcements arriving on round 8 (who never arrived). The manual save is from after the 3rd or 4th round 7.

### Files
[megamek.log](https://github.com/user-attachments/files/15526550/megamek.log)
[autosave.sav.gz](https://github.com/user-attachments/files/15526554/autosave.sav.gz)
[Round-5-autosave_2024-06-02_14-34-59.sav.gz](https://github.com/user-attachments/files/15526558/Round-5-autosave_2024-06-02_14-34-59.sav.gz)
[Round-6-autosave_2024-06-02_14-38-52.sav.gz](https://github.com/user-attachments/files/15526560/Round-6-autosave_2024-06-02_14-38-52.sav.gz)
[Round-7-autosave_2024-06-02_14-42-54.sav.gz](https://github.com/user-attachments/files/15526562/Round-7-autosave_2024-06-02_14-42-54.sav.gz)
[stuck.sav.gz](https://github.com/user-attachments/files/15526564/stuck.sav.gz)

**Comment by IllianiCBT** [comment]
Which version did this occur on?

**Comment by repligator** [comment]
Happened again, but this time on round 10.
[megamek.log](https://github.com/user-attachments/files/15527574/megamek.log)
[stuck10.sav.gz](https://github.com/user-attachments/files/15527578/stuck10.sav.gz)

**Comment by IllianiCBT** [comment]
From the most recent log. I imagine some of these are unrelated, but they should probably be investigated:


These appear a lot...
```
15:25:50,454 ERROR [megamek.client.ratgenerator.RATGenerator] {AWT-EventQueue-0}
megamek.client.ratgenerator.RATGenerator.findModelAvailabilityRecord(RATGenerator.java:176) - Trying to find record for unknown model Cascatelle Firefighting VTOL

15:31:24,333 ERROR [megamek.client.ratgenerator.RATGenerator] {AWT-EventQueue-0}
megamek.client.ratgenerator.RATGenerator.findModelAvailabilityRecord(RATGenerator.java:176) - Trying to find record for unknown model Comet Airliner ACL-800
```


Only one instance of these...
```
19:46:48,413 ERROR [megamek.client.ui.swing.unitDisplay.ArmorPanel] {AWT-EventQueue-0}
megamek.client.ui.swing.unitDisplay.ArmorPanel.displayMech(ArmorPanel.java:262) - The armor panel is null
```


A bunch of these errors are also present...
```
19:49:06,211 ERROR [megamek.common.pathfinder.AbstractPathFinder] {Princess-precognition (Rebels Primary Opfor)}
megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:285) - 
java.lang.IllegalArgumentException: Entity invalid. ID 28
	at megamek.common.Compute.isPilotingSkillNeeded(Compute.java:577)
	at megamek.common.MovePath.addStep(MovePath.java:371)
	at megamek.common.MovePath.addStep(MovePath.java:263)
	at megamek.common.MovePath.addStep(MovePath.java:175)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:270)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:233)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:270)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:295)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesForWorker(PathEnumerator.java:245)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:127)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:397)
	at java.base/java.lang.Thread.run(Thread.java:840)
```


And these...
```
20:01:57,976 ERROR [megamek.server.GameManager] {Packet Pump}
megamek.server.GameManager.filterReport(GameManager.java:29306) - Attempting to filter a Report object that is not public yet but has no subject.
		messageId: 7600
```

**Comment by SJuliez** [comment]
That sounds like the game's HAL 9000 moment. No Dave, I can't give you reinforcements. You know that they'll only arrive in round 8. And, sorry, it's round 7 again.

**Comment by repligator** [comment]
Here is a log from a game where the rounds progressed as intended (the bug did _not_ occur). All the errors [IllianiCBT](https://github.com/IllianiCBT) mentioned occur here as well.
[megamek.log](https://github.com/user-attachments/files/15537154/megamek.log)
