### ISSUE TITLE
[Nightly] Round 3 NPE spam

### ISSUE THREAD

**Issue by repligator** [MegaMek/megamek#5547]
### Environment
2024-05-31T01:13:33.430985946
Linux
17.0.10

### Description
I was playing MHQ, when a scenario rolled that featured offboard artillery for both friendly princess and enemy princess. In the MM lobby, I took possession of the friendly princesses artillery, because I know from experience she likes to drop it directly on top of my position. Everything was fine until round, when NPE popups started appearing rapidly. I had to close 30 NPE windows in order to save the game. I'm investigating the cause now. I've attached two logs, a MM save file, and the MHQ save file.

### Files
[megamek(2).log](https://github.com/user-attachments/files/15539966/megamek.2.log)
[megamek.log](https://github.com/user-attachments/files/15539967/megamek.log)
[test.sav.gz](https://github.com/user-attachments/files/15539970/test.sav.gz)
[reload_here.RD307030950415.cpnx.gz](https://github.com/user-attachments/files/15539974/reload_here.RD307030950415.cpnx.gz)

**Comment by repligator** [comment]
I am now 99% sure it's off board vs. off board issue. It can be replicated in MM by assigning both the human player and princess off board artillery. I'd post a save file, but there seems to be some strangeness with off board things not staying off board when they are loaded from a save in the lobby.

**Comment by repligator** [comment]
MM seems to throw different errors into the log when it isn't an MHQ scenario for some reason.

`ERROR [megamek.MegaMek] {AWT-EventQueue-0}
megamek.MegaMek.lambda$main$0(MegaMek.java:63) - Uncaught Exception Detected
java.lang.NullPointerException: Cannot invoke "megamek.client.ui.swing.TargetingPhaseDisplay.ce()" because "this.targetingPhaseDisplay" is null`

[megamek.log](https://github.com/user-attachments/files/15540227/megamek.log)

**Comment by SJuliez** [comment]
@repligator Do you have a way to reproduce this from a plain MM start and lobby (no game load)? I can't seem to, not even with two offboard arty for me and Princess.

**Comment by repligator** [comment]
> @repligator Do you have a way to reproduce this from a plain MM start and lobby (no game load)? I can't seem to, not even with two offboard arty for me and Princess.
This save should do it.
[arty_test_2.sav.gz](https://github.com/user-attachments/files/15571237/arty_test_2.sav.gz)
