### ISSUE TITLE
Introduction/extinction dates for laser guided bombs incorrect

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#5554]
Laser guided bombs are defined like this:

https://github.com/MegaMek/megamek/blob/8d78c5ce7de1e68a4cdb9d0e667dfe7ff7cf074f/megamek/src/megamek/common/BombType.java#L567-L576

While conventional laser spot tracking is certainly 'early spaceflight', the TAG homing version is different and much later.  Given the TAG external ordnance version looks like this:
https://github.com/MegaMek/megamek/blob/8d78c5ce7de1e68a4cdb9d0e667dfe7ff7cf074f/megamek/src/megamek/common/BombType.java#L657
... the laser guided bomb should have similar dates.  Or at least, dates similar to standard mounted equipment TAG.

**Comment by HammerGS** [comment]
That is something for CGL to sort out. We implement things RAW
