### ISSUE TITLE
[0.49.19.1] Dragon Fire Nameplate Truncated Incorrectly

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megamek#5556]
### Environment
15:55:50,015 INFO  [megamek.MegaMek] {main}
megamek.MegaMek.initializeLogging(MegaMek.java:118) - Starting MegaMek v0.49.19.1
	Build Date: 2024-05-10T20:11:07.453164161
	Today: 2024-06-07
	Origin Project: MegaMekLab
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 4 GB

### Description
Dragon Fire nameplate is getting truncated to "Dragon" incorrectly. Other units on the board have spaces in their names and are not getting truncated.

### Files
![image](https://github.com/MegaMek/megamek/assets/101755917/ea5db298-497a-4ea5-8522-03f8300ce220)

![image](https://github.com/MegaMek/megamek/assets/101755917/0155598b-764f-4f0c-ac66-63824274457b)

[DragonFireNameplate.sav.gz](https://github.com/user-attachments/files/15745493/DragonFireNameplate.sav.gz)

**Comment by HammerGS** [comment]
I've pushed updated unit files but it still persists. The where rebuilt and saved in MML
