### ISSUE TITLE
[49.20-SNAPSHOT] ClassCastException from squadrons firing external ordnance

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#5569]
### Environment
MekHQ Windows JDK 11 build artifact from: https://github.com/MegaMek/mekhq/actions/runs/9492053037
Standalone Megamek

### Description
There was a known issue with aerospace squadron ammo weapons in 0.49.19, which was since fixed (hence why I was testing this using the nightly build). However, external ordnance on squadrons (currently only tested with RL pods) seem to still have issues. Firing the RL pods followed by another ammunition-using weapon will result in a ClassCastException popup:
![image](https://github.com/MegaMek/megamek/assets/59574316/8243e3c7-ba7e-4d10-aa86-25c0ed65bd98)

Firing _only_ the RL pods, or only the RL pods and non-ammo-using weapons, will work as expected. However, the next time you try to fire an ammo-using weapon that game, the error will occur.

Also tested on 49.19.1, where both ammo-using weapons and external ordnance can be declared for firing, and their ammunition is consumed with no errors being thrown, but the weapon attacks simply fail to appear in the Weapon Attack Phase report or to have any effect on the target. 

### Files

Savegame for reproduction: [Round-1-autosave_2024-06-12_22-57-34.sav.gz](https://github.com/user-attachments/files/15813212/Round-1-autosave_2024-06-12_22-57-34.sav.gz)
Log: [megamek.log](https://github.com/user-attachments/files/15813197/megamek.log) (no data in other logs)

**Comment by Sleet01** [comment]
@neoancient adding you as I haven't got the expertise to make the BombMounted / AmmoMounted / Mounted <T> stuff work the way it needs to.
I have a few other bugs that are blocked because I can't actually fire any bomb munitions, so your assistance would be greatly appreciated.

**Comment by neoancient** [comment]
The issue here is that the weapon is a weapon group of the squadron, but the ammo is on an individual fighter. The equipmentNum of the ammo is 7 on the individual fighter, and that's the value assigned to the ammoId in the WeaponAttackAction. When it uses that to compute the to-hit mod, it uses the index on the individual fighter to find the ammo equipment on the squadron, which has only weapons. In this case the index 7 corresponds to the RL pod.
