### ISSUE TITLE
[0.49.19.1] Issues modifying deployment time/location for stratcon generated forces (offboard arty, ASF)

### ISSUE THREAD

**Issue by DeniedExistence31** [MegaMek/megamek#5575]
### Environment
Megamek/MekHQ Version: 0.49.19.1 milestone
OS: Windows 10
Java Version: Adoptium 11.0.23.9

### Description
When launching a Dropship Assault mission generated by MekHQ via Stratcon with an offboard artillery and asf opfor modifiers, changes to deployment time for the ASF and offboard location for the artillery do not stick. The ASF want to deploy SouthEast at game start, and I can set them in lobby to deploy later in the lobby, but once the match is launched they always will deploy at game start instead of the dictated deployment round. I can however alter their deployment location without issue. The artillery I similarly can tell to deploy offboard anywhere in the lobby, but once the match is launched they will always deploy offboard East at 34 distance. Possibly other deployment time/locations do not stick, but I haven't tested other permutations.

### Files
Here is the mekhq campaign file with the mission pending.
[DragonclawsBuggedDropshipMission.cpnx.gz](https://github.com/user-attachments/files/15855661/DragonclawsBuggedDropshipMission.cpnx.gz)
Except for a few custom mech files (none of which are partaking in this mission), and my various saves and saved presets, my mekhq folder is otherwise stock.

**Comment by repligator** [comment]
The save file can't be opened without your custom unit _Javelin JVN-MERC-10FN_.

**Comment by DeniedExistence31** [comment]
> The save file can't be opened without your custom unit _Javelin JVN-MERC-10FN_.

Ah, wasn't aware of that requirement, here's the zipped mechfile folder for good measure
[mechfiles.zip](https://github.com/user-attachments/files/15855820/mechfiles.zip)

**Comment by repligator** [comment]
Alright. Under the latest nightly for MHQ (1524) I can replicate the issue.

Here's the weird part. If I select each individual unit, and change deployment zone or turn, everything works fine. When I select more than one at a time and try to change the same things, it doesn't work.

**Comment by kuronekochomusuke** [comment]
#3590
