### ISSUE TITLE
RFE: Saving Quirks

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/megamek#559]
Version MHQ 0.43.2

The commands... Save Quirks for Model and Save Quirks for Model/Chassis, do not write to file until MM has been QUIT entirely. Note, not exiting from lobby but entirely QUIT from the SplashScreen.

Please write to file immediately on using the Save Model or Model/Chassis.

Reproduction: Open UnitQuirksOverride.xml in an editor, Open MM, add a unit and edit the quirks, hit the Save Model or Model/Chassis commands. Refresh the UnitQuirksOverride.xml file in your editor. You will see no change. Close Lobby, Quit MM. Refresh the UnitQuirksOverride.xml file in your editor again. Changes are now saved.

**Comment by HammerGS** [comment]
When this was written I ask about it and if I recall its a limit to how things are down in either MM or Java.

**Comment by scJazz2** [comment]
I fully expected the above response... still had to ask. TY.
