### ISSUE TITLE
[Nightly] Infantry has seemingly unlimited shots with a one-shot SRM.

### ISSUE THREAD

**Issue by repligator** [MegaMek/megamek#5597]
### Environment
2024-06-18T01:16:24.948066258
Java Version: 17.0.11
Linux

### Description
Using a single Mechanized Tracked Squad (SRM), which consists of 6 troopers, with SRM Launcher (Hvy, One-Shoot) [TPRS]'s, I''ve been able to fire for over 30 turns in a single game. I can confirm the shots are dealing damage from the collapsed building.

### Files
[unlimited_srm.sav.gz](https://github.com/user-attachments/files/15892317/unlimited_srm.sav.gz)

**Comment by gsparks3** [comment]
This is just a name oddity. The "One-shot" label means you get one shot before reloading it, to distinguish it from the "Two-shot" man-portable SRM that lets you fire twice before reloading. Neither track ammo at TW scale and can fire indefinitely, being abstractly reloaded by the troopers from abstract, non-tracked ammo supplies as necessary.

Looking at the table in TechManual page 352, the sourcebook doesn't actually include "One-shot" text in the name of the Heavy or Light SRM Launchers, so it might be possible to have the weapon name altered so it stops confusing people. 

Note that this is different from _disposable_ weapons, which can genuinely only be used once in a scenario. I don't believe those are currently implemented in Megamek.

**Comment by repligator** [comment]
Ah, thanks. Closing issue.
