### ISSUE TITLE
49.20 Nightly - MM no longer shows targets selected for physical attacks.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/megamek#5612]
In the screenshot, the WH is active unit.  It is standing on a Manticore and in front of a Falcon Hawk.  I can click on them and click kick and it will give me the kick dialogue pop up, but it no longer shows them as a targeted unit in the unit pane.  So right now there is no visual indicater that you have either of them selected.

![image](https://github.com/MegaMek/megamek/assets/23645569/c5b076c4-9957-4dd0-aa47-68b2d213bbed)
[Round-2-autosave_2024-06-21_00-05-53.sav.gz](https://github.com/user-attachments/files/15923079/Round-2-autosave_2024-06-21_00-05-53.sav.gz)

[CustomsThom6.10.24b.zip](https://github.com/user-attachments/files/15923083/CustomsThom6.10.24b.zip)

**Comment by SJuliez** [comment]
I just checked a few back versions, including 0.48, and it seems like it never showed the target of a physical attack. Has there been a version where it did?

**Comment by Thom293** [comment]
I have to check.  I swear there was some sort of indicator when something was targeted with a physical attack. Maybe I'm wrong. I will check tomorrow.

**Comment by Thom293** [comment]
Ok - so something seemed different, and it is, but not for the reasons I thought. I did used to have a display in the targeting panel, but it was old data from the shooty phase. So the current version is technically more accurate. Sorry.

![image](https://github.com/MegaMek/megamek/assets/23645569/a3d05182-369b-46f9-bf01-194a92ba084b)

**Comment by Thom293** [comment]
closing.
