### ISSUE TITLE
[0.43.2-git : Possible Bug] SRM and LRM Carriers' Weights

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#563]
Might not be noticeable in later years, but if the year is set to 2500, the RAT Generator will generate SRM/LRM carriers more than 50% or higher every time. If I generate a battalion of armor, it will most probably generate 2 companies of SRM/LRM carrier with 1 company of other vehicles.

**Comment by neoancient** [comment]
There are some units, like SRM/LRM carriers and APCs that have the same weight across all eras. This is a problem in the AoW era because there just aren't very many tanks, so I need to reduce the weight there.

**Comment by neoancient** [comment]
After some adjustments the LRM/SRM carriers are roughly half of all tanks, depending on faction. That's about the best I can do with the limited number of units.

**Comment by SirMegaV** [comment]
Thanks a lot.
