### ISSUE TITLE
[0.49.20-SNAPSHOT] Players cannot use bombs in any way.

### ISSUE THREAD

**Issue by Sleet01** [MegaMek/megamek#5635]
### Environment
MegaMek v0.49.20-SNAPSHOT from code repos, ca. 2024/06/26 
Kubuntu Linux 22.04
Java Vendor: Eclipse Adoptium
Java Version: 17.0.8.1

### Description
It is not currently possible for human players to utilize bombs or bomb weapons due to the BombMounted refactoring.
As BombMounted items are not AmmoMounted items, they are not counted as ammo for the "weapon" bombs (such as RL10 pods, Arrow IV Air-Launched bombs, Anti-Ship Missiles, AAA Missiles, Alamo Missiles, etc.) and thus any such weapons are shown as having 0 ammo.

<img width="1920" alt="no_ammo_for_AIV_bombs" src="https://github.com/MegaMek/megamek/assets/22018319/02995ad8-e737-4ff9-80a2-77bb252a8ff9">

This also impacts Dive Bomb and Altitude Bomb attacks:

<img width="1919" alt="no_ammo_for_altitude_bombs" src="https://github.com/MegaMek/megamek/assets/22018319/ab6f3b4e-a68d-44fd-9352-54f3c0da98c6">

### Files

[saved_game_and_custom_IBB_unit.tar.gz](https://github.com/user-attachments/files/15984119/saved_game_and_custom_IBB_unit.tar.gz)
Save game with various player- and bot-controlled ground and ASF forces.
Use "Sleet01" for name.

Note: bot can drop bombs just fine, as the bot code looks at actually installed equipment rather than the WeaponPanel list with its ammo check restrictions.

**Comment by neoancient** [comment]
![Screenshot from 2024-06-27 15-13-56](https://github.com/MegaMek/megamek/assets/16927464/2f6b5f4a-69b3-4195-90eb-ff9d5e634622)
![Screenshot from 2024-06-27 15-17-11](https://github.com/MegaMek/megamek/assets/16927464/52619934-397b-4115-9029-670710a40180)

**Comment by Sleet01** [comment]
Looks like this has already been resolved; closing.
