### ISSUE TITLE
Can't get homebrewed scenarios to run

### ISSUE THREAD

**Issue by psyberduck** [MegaMek/megamek#5639]
### Environment
0.49.19.1, in the MekHQ suite
Windows 11 Home
Eclipse Adoptium 17

### Description
I am attempting to write scenario files for MegaMek. I worked from the two example files in the docs and scenarios folders. I've created from scratch using Notepad, Notepad++, and then using the later to simply tweak one of those scernario files and patch my own code in. All produce an error message reading: “Uncaught java.lang.NoClassDefFoundError detected. Please open up an issue containing all logs, the game save file, and customs at https://github.com/MegaMek/megamek/issues”

![Screenshot 2024-06-27 111548](https://github.com/MegaMek/megamek/assets/98470/113c7daf-8ea3-470d-97fa-acc3a770ecc7)

### Files
[megamek.log](https://github.com/user-attachments/files/16018644/megamek.log)
Can't seem to upload the .mms file, but here's the code:
`#  A MegaMek Scenario file by David Mullins
MMSVersion=1
Name=Divided We Fall
Description=The Plains of Despair pit brothers against each other
BoardWidth=2
BoardHeight=1
Maps=rotate:Map Set 2/16x17 BattleTech,Map Set 2/16x17 BattleTech
Factions=FreeWorlds,Andurien
Location_FreeWorlds=CTR
Location_Andurien=R
Unit_FreeWorlds_1=Banshee BNC-3E,Elsa Sullivan,3,3
Unit_FreeWorlds_2=Awesome AWS-8Q,Paul Weiss,3,4
Unit_FreeWorlds_3=Hunchback HBK-4G,Tara Lemke,4,4
Unit_FreeWorlds_4=Hunchback HBK-4G,Gerrard LeBlanc,4,4
Unit_FreeWorlds_5=Zeus ZEU-6S,Richard Carter,3,4
Unit_FreeWorlds_6=Quickdraw QKD-4G,Alex Hale,4,4
Unit_FreeWorlds_7=Trebuchet TBT-5N,Poly Reardon,4,5
Unit_FreeWorlds_8=Whitworth WHT-1,Ophelia Inez,4,5
Unit_Andurien_1=Awesome AWS-8Q,Michael Griffith,2,3
Unit_Andurien_2=Grasshopper GHR-5H,Reginald Mulcahy,3,4
Unit_Andurien_3=Catapult CPLT-C1,Uri Samsonov,3,4
Unit_Andurien_4=JagerMech JM6-S,Elijah Masters,3,4
Unit_Andurien_5=Dervish DV-6M,Wanda Mills,3,4
Unit_Andurien_6=Vindicator VND-1R,Louis Roland,3,3
Unit_Andurien_7=Hermes HER-2S,Brian Solomon,4,5
Unit_Andurien_8=Enforcer ENF-4R,Oliver Tibbs,4,5
Unit_Andurien_9=Cicada CDA-2A,Howard Jones,3,4
Unit_Andurien_10=Spider SDR-5V,Caleb Hughes,4,4
Unit_Andurien_11=Clint CLNT-2-3T,Luc LeBlanc,4,5
Unit_Andurien_12=Clint CLNT-2-3T,Sarah Uberoth,4,5
Unit_Andurien_9_DeploymentRound=1
Unit_Andurien_10_DeploymentRound=1
Unit_Andurien_11_DeploymentRound=1
Unit_Andurien_12_DeploymentRound=1
Unit_Andurien_5_DeploymentRound=3
Unit_Andurien_6_DeploymentRound=3
Unit_Andurien_7_DeploymentRound=3
Unit_Andurien_8_DeploymentRound=3
Unit_Andurien_1_DeploymentRound=5
Unit_Andurien_2_DeploymentRound=5
Unit_Andurien_3_DeploymentRound=5
Unit_Andurien_4_DeploymentRound=5
Camo_Andurien=Free Worlds League/Andurien/Defenders of Andurien.jpg
Camo_FreeWorlds=Free Worlds League/Free Worlds Guards/Free Worlds Guards.jpg`

**Comment by panssystem** [comment]
I did some investigating into this one, and it seems to be a problem with megamek.server.Messages. As far as I can tell, ScenarioLoader.java is the only place it's used, and it is failing (probably the RESOURCE_BUNDLE failing to load?).

**Comment by psyberduck** [comment]
Is that a problem on my end? How would I address it? Other scenarios are loading fine, so I assume it's my code, I just can't see the difference between them. I've also tried saving copies of working scenarios with this editor, and they run fine.

I'm working my way through pasting my code into an existing scenario, and it only freaks out when I add in my factions and units. Is there a particular syntax I'm using wrong to define factions?

It's done it with this version as well as 0.49.19 under Java 11 (I just updated both this morning to make sure that wasn't the issue).

**Comment by panssystem** [comment]
No, it's a code problem. Not directly related to your problem, but if it were fixed, it would make it easier to figure out what's going on in your issue. I was just sharing it so whoever actually looks into your issue may get a little head start by fixing this.

**Comment by psyberduck** [comment]
OK thanks! In trying to slowly convert a working scenario file into my code, it seems that my units are the tipping point right now. Not sure what I did wrong there. Gonna take a break, and then slowly convert those over as well.

**Comment by psyberduck** [comment]
Ugh. The whole thing was one bad abbreviation. WHT vs WTH. Sorry to bother y'all.
