### ISSUE TITLE
Artillery Cannon Deals Incorrect Damage.

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#564]
I'm playing around with artillery cannons and they appear to only be doing 1/2 damage on a direct hit. As if the victim were one hex away. For example:

Weapons fire for Manticore Snapping Turtle III (Vamp)
    Sniper Cannon at Bulldog Medium Tank (Standard) (Princess); needs 6, rolls 9 : hits the intended hex 0402.
Bulldog Medium Tank (Standard) (Princess) hit for 10 damage.
        Bulldog Medium Tank (Standard) (Princess) takes 5 damage to LS.
            15 Armor remaining.
            Chance for motive system damage. Roll is 6; (w/ +0 bonus)
             Minor damage, +1 to driving skill rolls.
        Bulldog Medium Tank (Standard) (Princess) takes 5 damage to FR.
            19 Armor remaining.

[ArtyCannonDmgBug.sav.gz](https://github.com/MegaMek/megamek/files/1089681/ArtyCannonDmgBug.sav.gz)

**Comment by VampireSeraphin** [comment]
Nevermind, this appears to be working as intended, The values I recalled were different from tacops.

**Comment by HammerGS** [comment]
Per posters request
