### ISSUE TITLE
Quirk: Modular Weapons applies to Chassis not specific Weapon

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/megamek#565]
MHQ and etc: 0.43.2

Modify quirks on any Mech in MM... notice Modular Weapons is a Chassis Quirk.

Rules from BT:BMM(Open Beta) pg 85
MODULAR WEAPONS (1 POINT)
Though lacking the flexibility of an OmniMech, a ’Mech with
Modular Weapons such as the O-Bakemono or Mercury can be
repaired or customized more easily. Equipment can be replaced in
half the normal time (though repairs in-place take the usual amount
of time). When using the Customization Rules (see p. 188, SO), half
the time is required.
On some ’Mechs, only certain weapons or equipment are
modular. In this case, the specific gear with the modular quality
must be noted, but this does not reduce the quirk’s cost.

The above indicates that the quirk should be based on Weapons not the whole Chassis.

**Comment by pheonixstorm** [comment]
No, it means it should be both.

**Comment by HammerGS** [comment]
This has been addressed here
https://github.com/MegaMek/megamek/commit/3971fdf3c0cb5314cd23adfad065d410b360a2b7
