### ISSUE TITLE
0.49.20 Dev. Weapons unselect after twisting the unit.

### ISSUE THREAD

**Issue by Gadehos** [MegaMek/megamek#5650]
Whenever I "twist" unit in the combat, the mekamek deselcts every weapon.
Its a minorr yes, but didn't happen before and after talk in discord. Found others dont like it either.

### Environment
HQ's Mekamek,
Java Vendor: Eclipse Adoptium
Java Version: 11.0.21

### Description
Whenever I "twist" unit in the combat, the mekamek deselcts every weapon.
Its a minorr yes, but didn't happen before and after talk in discord. Found others dont like it either.
It has happened on every scenario I have done in 49.20 now (6 battles)
This happens with any unit that can "twist". I noticed this as I play with "fields of fire" visible. and they 
dissapear everytime I use twist in the mekamek.

### Files
[megamek.log](https://github.com/user-attachments/files/16043350/megamek.log)
[autosave.sav.gz](https://github.com/user-attachments/files/16043359/autosave.sav.gz)
[Round-6-autosave_2024-06-29_22-19-03.sav.gz](https://github.com/user-attachments/files/16043360/Round-6-autosave_2024-06-29_22-19-03.sav.gz)
[Round-7-autosave_2024-06-29_22-21-45.sav.gz](https://github.com/user-attachments/files/16043361/Round-7-autosave_2024-06-29_22-21-45.sav.gz)
[Round-8-autosave_2024-06-29_22-26-01.sav.gz](https://github.com/user-attachments/files/16043362/Round-8-autosave_2024-06-29_22-26-01.sav.gz)
Playername: Bombshells (I think, as thats my campaign name/unit name in the campaign)

**Comment by HoneySkull** [comment]
Working correctly as of June 16th nightly build.  (by correctly, I mean as per usual of selecting the first weapon on a twist instead of un-selecting.)

Taking a look to see if there is a way to "remember" the selected weapon on a non-turret twist.

**Comment by HoneySkull** [comment]
@Gadehos - do you run on Windows, Mac, or *nix?

**Comment by HoneySkull** [comment]
Confirmed issue as described on Windows with 0.49.20 released version.

**Comment by Gadehos** [comment]
> @Gadehos - do you run on Windows, Mac, or *nix?

Windows.

**Comment by HoneySkull** [comment]
@SJuliez - this behavior started with 6cda321e as determined by `git bisect`

**Comment by sshagent** [comment]
The most recent nightly certainly shows this is fixed.  Thanks for your time on this guys

**Comment by HoneySkull** [comment]
This was broken by #5910
