### ISSUE TITLE
Sprite (including camo) swap in the phase report/log

### ISSUE THREAD

**Issue by repligator** [MegaMek/megamek#5661]
### Environment
Master (latest PR MegaMek#5784)
Java 17
Linux

### Description
I started and finished a game in MM with 4 blue Annihilators vs. 4 red Atlases. The game ran without incident. Then I started another game with 5 Ghost Bear Kodiak II's vs 5 Jade Falcon Turkina's. The mech's and camo are those from the first game. The facing is however correct, and is not carried over from the first game.

![sprite_swap_1](https://github.com/MegaMek/megamek/assets/114337591/0440b1c9-8730-4371-adcd-208cd73051c5)

Interesting to note: The 5th Kodiak II uses the camo/sprite from the 1st Atlas, and the 4th and 5th Turkina's use the correct camo.
![sprite_swap_2](https://github.com/MegaMek/megamek/assets/114337591/41271428-7dc1-4f8d-8301-636b5882f7ee)

**Comment by Sleet01** [comment]
My initial guess is that we're no longer properly clearing the sprite cache at the end of the game, which would be supported by the last two 'mechs using the correct graphics: those unit ids weren't in the first game, so there were no cached graphics for them.

**Comment by repligator** [comment]
Those are my thoughts as well. I tried smashing out some breakpoints last night, but they all either showed the correct sprite loading, or weren't triggered at all.

**Comment by Thom293** [comment]
A similar thing used to happen with pilot portraits before it was fixed.

**Comment by repligator** [comment]
After smashing some breakpoints in `megamek/client/Client.java`, it looks like Client never gets the correct sprite and camo. I'm puzzled in regards to how the board is showing the correct one while the phase report doesn't.

**Comment by Sleet01** [comment]
> After smashing some breakpoints in `megamek/client/Client.java`, it looks like Client never gets the correct sprite and camo. I'm puzzled in regards to how the board is showing the correct one while the phase report doesn't.



Look at the icon cache, iirc in the game server?

**Comment by repligator** [comment]
Progress! Sort of...
`public static BufferedImage getScaledImage` of `megamek/common/util/ImageUtil.java` will return the correct sprite, with the correct camo, while still in the lobby. As soon as the game starts, it begins to use the wrong sprite and wrong camo.

> > After smashing some breakpoints in `megamek/client/Client.java`, it looks like Client never gets the correct sprite and camo. I'm puzzled in regards to how the board is showing the correct one while the phase report doesn't.
> 
> Look at the icon cache, iirc in the game server?

Sorry, I'm not sure where/which/what you are referring to.

**Comment by repligator** [comment]
This bug is not limited to mechs, or even units of the same type. See screenshot, where a mech has acquired a drop-ship sprite.
![Screenshot_20240708_110101](https://github.com/MegaMek/megamek/assets/114337591/83dcfe8e-7599-4bdf-949d-fe57cf255b30)

**Comment by IllianiCBT** [comment]
See also: #5769

**Comment by repligator** [comment]
Game 1 = Blue Akuma
Game 2= Red Archer
Game 3= Green Atlas II
Red Archer appears as a Blue Akuma in all the round reports for game 2.
![Screenshot_20240722_124446](https://github.com/user-attachments/assets/2f819e0c-1a4c-486f-ae3c-74b9df2350d8)
But as soon as reset() happens, it briefly changes back to the Red Archer it should be.
![Screenshot_20240722_125245](https://github.com/user-attachments/assets/1ace7e0e-2a11-4791-aee2-e41d5467d750)
But the Green Atlass II becomes a Blue Akuma again in game 3.
![Screenshot_20240722_125725](https://github.com/user-attachments/assets/cb7cd2a3-1021-4a08-8ea2-19f997d6d072)
And then a Green Atlas II again during reset()
![Screenshot_20240722_130117](https://github.com/user-attachments/assets/277706b2-711f-43e3-bed0-9a98852a32ae)

Here's something else interesting. The log only shows the Blue Akuma "Loading image on the fly"ing, the other two mechs are absent.
I started a 4th game, added two pink mechs, and ID 2 got "Loading image on the fly"ed, in the log, which makes sense, because there was nothing occupying ID 2 in any of the previous games.

[megamek.log](https://github.com/user-attachments/files/16337631/megamek.log)

**Comment by repligator** [comment]
Further testing - In a new game I added two Blue Riflemen (ID 1 and 2). I then deleted them from the lobby, and added two Red Piranhas (ID 3 and 4). The Piranhas displayed correctly. After finishing the game with the Red Piranhas, I added two Green Highlanders (ID 1 and 2). The Highlanders became Blue Riflemen in the round reports, and never got "Loading image on the fly"ed. The Blue Riflemen 'stuck' in ID slots 1 and 2, even though they were deleted while in the lobby, and therefor were never displayed in a round report.

[megamek.log](https://github.com/user-attachments/files/16340372/megamek.log)

**Comment by gsparks3** [comment]
> Further testing - In a new game I added two Blue Riflemen (ID 1 and 2). I then deleted them from the lobby, and added two Red Piranhas (ID 3 and 4). The Piranhas displayed correctly. After finishing the game with the Red Piranhas, I added two Green Highlanders (ID 1 and 2). The Highlanders became Blue Riflemen in the round reports, and never got "Loading image on the fly"ed. The Blue Riflemen 'stuck' in ID slots 1 and 2, even though they were deleted while in the lobby, and therefor were never displayed in a round report.

This matches some of the similar experiences I've had, where reinforced units would sometimes take on the sprites of units that were added and then removed from the lobby, as opposed to wreck sprites.

**Comment by mmetke-qumulo** [comment]
It should be noted that the image cache is a separate store from the list of units in the Lobby, and the image cache is not cleared (nor are cached images delete) when a given unit is deleted.

We need to, at the very least, clear the `mechImages` cache after every game.  We should probably _also_ remove the cached images of every unit that is removed from the Lobby list.

**Comment by Sleet01** [comment]
It should be noted that the image cache is a separate store from the list of units in the Lobby, and the image cache is not cleared (nor are cached images delete) when a given unit is deleted.

We need to, at the very least, clear the mechImages cache after every game. We should probably also remove the cached images of every unit that is removed from the Lobby list.

**Comment by repligator** [comment]
Progress! Sort of...
![Screenshot_20240723_110359](https://github.com/user-attachments/assets/be6cb46e-9eb9-4c92-98fb-f7d851ec96e2)
By adding the two lines (highlighted in red) the issue no longer occurs. Bad news is emptying the cache every single time getFromCache is run kind of invalidates the entire point of the cache existing in the first point. See log.

[megamek.log](https://github.com/user-attachments/files/16350852/megamek.log)


I've tried adding the lines elsewhere, for example here:
![Screenshot_20240723_110800](https://github.com/user-attachments/assets/dcac9b11-4b62-49bf-b6b4-f9cd82a3464f)
But the issue persists.

**Comment by repligator** [comment]
So I inserted `getBoardView().getTilesetManager().reset();` under `case FILE_REFRESH_CACHE:` . This allows reset() to run whenever the Refresh Cache menu option is. I play the first game. Reset() runs naturally when the phase shift occurs. Then I run Refresh Cache from the menu while in an empty lobby. IDEA shows that the mechImageList and mechImages are both empty. I start the second game. The issue still occurs.
