### ISSUE TITLE
Princess instance hanging following point-blank attack.

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#567]
Playing MM game against multiple Princess instances (using the Princess roles). (Pure MM, not MekHQ.)

Game hung partway through round 3, after hidden player unit conducted point-blank attack on passing Princess unit.

[megameklog.zip](https://github.com/MegaMek/megamek/files/1132464/megameklog.zip)
[autosave-20170705-223823.sav.zip](https://github.com/MegaMek/megamek/files/1132466/autosave-20170705-223823.sav.zip)
[gamelog-20170706-153028.zip](https://github.com/MegaMek/megamek/files/1132463/gamelog-20170706-153028.zip)

To replicate:
1. Load autosave.
2. Assign Princess roles to ghosts as follows - St = Striker, Sc = Scout, Mi = Missile Boat, Br = Brawler, Sn = Sniper.
3. Do not move any of player forces (they're almost all hidden, and the two Ferrets at the north are there as bait to stop the Princesses loitering at the bottom edge).
4. A couple of moves into the Opfor movements phase, the surviving Saladin LB-X passes the Grenadier BA squad in the single woods in hex column 08.
5. The Grenadiers take up the option of the point-blank attack ... and then the game seems to hang.

(A point-blank attack on the other Saladin LB-X from another Grenadier squad worked perfectly in round 2.)

(I managed to replicate exactly the same sequence of events twice before giving up this battle as a bad job.)

**Comment by HammerGS** [comment]
Checking the log I have 4880 lines of RAT errors not sure what the issue is there.

Only error I can find is on line 4924 of the log:

Exception in thread "Mech Cache Loader" java.lang.IllegalMonitorStateException
	at java.lang.Object.notifyAll(Native Method)
	at megamek.common.MechSummaryCache.done(MechSummaryCache.java:316)
	at megamek.common.MechSummaryCache.loadMechData(MechSummaryCache.java:311)
	at megamek.common.MechSummaryCache$1.run(MechSummaryCache.java:95)
	at java.lang.Thread.run(Unknown Source)
Loaded Rats in: 31287ms.

**Comment by neoancient** [comment]
I thought you would want to see what happened when I tested the fix:
![screenshot from 2017-07-08 20-40-25](https://user-images.githubusercontent.com/16927464/27990507-045515ac-641f-11e7-9b3b-af4a1317a69f.png)

**Comment by SimonLandmine** [comment]
No idea what is going on with the RAT errors logged - not encountered any there, AFAIK, though I've not used them that much, I confess.

Thanks for the screenshot! Unit "detects a hidden unit" may be a slight understatement there. [grin] Think I'll keep that save and finish the battle off when the next release comes out!

(Out of mere nosiness and curiosity, what was the summary of the issue - was St failing to handover from that unit to the next 'player' after the ambush interrupt, or was it something else?)

**Comment by neoancient** [comment]
Saves aren't necessaruly compatible between versions, and this is one of the cases where games from previous versions don't work.

The issue was that the server thread was put to sleep to wait for client feedback but did not check for a packet from the client before going to sleep or whether the notification that woke it up was what it was waiting for. Somewhere in the loop it the thread went to sleep when it already had the info it needed and there was nothing to wake it up.

**Comment by SimonLandmine** [comment]
Ah well. That would make sense. Ta! I'll just have to remember the landscape with Saladin redecoration! (And restart the battle from scratch. [grin])

Ah ... a Sleeping Beauty thread. Thanks!
