### ISSUE TITLE
RFE: 0.49.20 Princess not using ammo base weapons

### ISSUE THREAD

**Issue by kgibbs22** [MegaMek/megamek#5670]
HQ Megamek and normal Megamek
  Windows
 Java 17

I first noticed in Megamek games loaded from the MekHQ that units weren't using their ballistic weapons, and then had another game where it wouldn't use any weapons with ammo.  I then loaded up a game in normal megamek pitting an ac carrier against a stationary target and it refused to fire for multiple rounds.  This game I tried switching princess to beserker to see if it would change anything, but it acted the same as I saw it on default.

[test.sav.gz](https://github.com/user-attachments/files/16076399/test.sav.gz)
Knights of Corvus is the host name

**Comment by gsparks3** [comment]
Fixed for the next release by https://github.com/MegaMek/megamek/pull/5652, but good to leave the issue open until said release to make people aware of the problem.
