### ISSUE TITLE
gamelog.html missing pre tag

### ISSUE THREAD

**Issue by kuronekochomusuke** [MegaMek/megamek#5686]
megamek.MegaMek.initializeLogging(MegaMek.java:118) - Starting MegaMek v0.49.20
	Build Date: 2024-06-28T16:03:18.972741300
	Today: 2024-07-01
	Origin Project: MegaMek
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 11 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 8 GB
	MM Code Revision: Unknown
	MML Code Revision: Unknown
	MHQ Code Revision: Unknown

post game gamelog.html is missing pre tag, this cause the display of the html file to be garbled.

[gamelog.zip](https://github.com/user-attachments/files/16112776/gamelog.zip)

![image](https://github.com/MegaMek/megamek/assets/116095479/3a57c643-d501-469a-b9a3-90914509d416)

**Comment by Sleet01** [comment]
@kuronekochomusuke any indication of how this got broken in the first place?

**Comment by kuronekochomusuke** [comment]
PR 5448
