### ISSUE TITLE
NPE when cancelling loading a unit onto another unit

### ISSUE THREAD

**Issue by repligator** [MegaMek/megamek#5691]
### Environment
Master (latest PR https://github.com/MegaMek/megamek/pull/5784)
Linux
Java 17

### Description
Load saved game, the space station should deploy first, press load, press cancel, receive NPE.

`20:23:54,481 ERROR [megamek.MegaMek] {AWT-EventQueue-0}
megamek.MegaMek.lambda$main$0(MegaMek.java:63) - Uncaught Exception Detected
java.lang.NullPointerException: Cannot invoke "megamek.common.Entity.isFighter()" because "unit" is null`

### Files
[megamek.log](https://github.com/user-attachments/files/16114496/megamek.log)
[load_npe.sav.gz](https://github.com/user-attachments/files/16114498/load_npe.sav.gz)

**Comment by repligator** [comment]
Note: After further testing, it appears this bug is not limited to space-stations. I was able to replicate with an Omni-mech and a point of elementals.

**Comment by Sleet01** [comment]
I need some more information.  What exactly are the steps for loading fighter into a space station?  Please be as detailed as possible.

Re: Omni + Elementals, do you have a save game that I could test with?

**Comment by repligator** [comment]
Gosh, looking back on it now, that initial report was really vague. Sorry about that. During the deploy phase, while deploying a unit that can hold other units, the load button can be pressed.
![Screenshot_20240728_060215](https://github.com/user-attachments/assets/bf810537-6c32-430f-9e7d-34264d9c156f)
If instead of loading a unit, the cancel button is pressed, an NPE is thrown.
![Screenshot_20240728_060249](https://github.com/user-attachments/assets/f066f816-3e59-414a-b545-75466e312683)
The same setup works for Omni's and Elementals.
[omni-save.sav.gz](https://github.com/user-attachments/files/16402872/omni-save.sav.gz)

**Comment by Sleet01** [comment]
Today I learned!  I've exclusively loaded stuff in the lobby until today!

Looks like there was no handling for the <Cancel> option, whatsoever.
Adding that makes this work a lot better.

**Comment by Sleet01** [comment]
Thanks, the extra info was super-helpful!
