### ISSUE TITLE
[49.20] "Show best possible modifiers" overlay not removed on pressing Escape

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#5700]
Standalone Megamek
Java 17.0.11
Windows 10

### Description
Megamek includes a very handy overlay that indicates the best possible TMM achievable in any hex and facing the unit can reach.
![image](https://github.com/MegaMek/megamek/assets/59574316/5659b01c-076d-4bd2-a7c7-ef1ff27c62ba)

In all previous versions that I know of (including 0.49.19.1), this overlay is removed on pressing Escape. In version 0.49.20, this overlay is _not_ removed on pressing Escape. This is extremely inconvenient, as the overlay significantly obstructs the view of the map, especially for very fast units. There does not seem to be any other way to remove the overlay, at least that I could locate. 

### Reproduction steps
1. Launch Megamek 0.49.20 and Start Game.
2. Add a combat unit in the lobby (any will do).
3. Start the game, deploy your unit, and advance to the movement phase.
4. Press Ctrl+W to bring up the overlay.
5. Press Escape and observe that the overlay is not removed.

**Comment by HoneySkull** [comment]
This currently is an issue with movement envelope as well and may be related.  Essentially, it cannot be toggled off.

**Comment by HoneySkull** [comment]
If you have move modifiers enabled, and you select a different unit, the move modifier stay will the original unit.
![image](https://github.com/MegaMek/megamek/assets/83041327/8c528fb6-7f09-483b-801f-3eaa3063f42f)

**Comment by HoneySkull** [comment]
This and the stale move envelope was introduced in commit:  99b0bff2
