### ISSUE TITLE
Czar Dropship (Mech Carrier) and Czar Dropship (Armored Carrier) don't seem to be real variants of the Czar Dropship.

### ISSUE THREAD

**Issue by pavelbraginskiy** [MegaMek/megamek#5722]
Both the Czar Dropship (Mech Carrier) and Czar Dropship (Armored Carrier) list XTRO:Primitives 3 as their source, but XTRO:Primitives 3 only includes data for the (illegally constructed) Czar Dropship. 

The Mech Carrier and Armored Carrier "variants" don't exist on the MUL, and in MM's data they share a MUL id with the standard Czar Dropship. 

There is a sentence in XTRO:Primitives 3 mentioning that some Czars were refit to carry mechs, but since no stats were provided for any such refit, I believe the variants as included in MM are not canonical and should be removed from MegaMek.

**Comment by gsparks3** [comment]
This is the "Megamek Large Craft Data" issue; MM deliberately does not follow the MUL (or TROs, for that matter) for Large Craft.

Reference: https://bg.battletech.com/forums/index.php?topic=62796

> Going forward we are going to consider these redesign ships as “Our Fixed Canon Ships”. This will be one of those very rare times we won't match the MUL or the TRO. If CGL ever decides to update the ship designs we'll be certain to update the designs to those stats.
