### ISSUE TITLE
Autoconfig Ammunition provides ASF with bombs on low altitude maps

### ISSUE THREAD

**Issue by repligator** [MegaMek/megamek#5730]
### Environment
Developmental
Linux
Java 17

### Description
I just hit autoconfig in MM for a low altitude map and my first Thunderbird has 5 cluster bombs, 3 inferno bombs, and a thunder bomb. On average bombs seem to be equipped for about half the fighters, with the other half getting proper AA ammo.

### Files
[bombs.sav.gz](https://github.com/user-attachments/files/16182727/bombs.sav.gz)

**Comment by Sleet01** [comment]
@repligator Quick q, were you going through the context menu or the Player Config dialog?
If the former, did you select all units or just the ASF?

**Comment by repligator** [comment]
I went through Configure Player.

**Comment by Sleet01** [comment]
It looks like this is actually a Random Map generator bug: it doesn't set its onGround state correctly unless actual maps are selected manually.
