### ISSUE TITLE
Heat differes between Armor and Weapon view

### ISSUE THREAD

**Issue by repligator** [MegaMek/megamek#5736]
### Environment
Master (Latest PR https://github.com/MegaMek/megamek/pull/5784)
Java 17
Linux

### Description
The heat for each mech differs between the Weapon and Armor view. FYI the battlefield temperature is 8 degrees Celsius.

![Screenshot_20240714_142649](https://github.com/user-attachments/assets/04a497c6-6988-4614-903d-08127167aa4d)
![Screenshot_20240714_142700](https://github.com/user-attachments/assets/0808421b-6005-4614-bff7-ba8a60000ad8)

### Files
[megamek.log](https://github.com/user-attachments/files/16228416/megamek.log)
[different_heat.sav.gz](https://github.com/user-attachments/files/16228417/different_heat.sav.gz)

**Comment by repligator** [comment]
See also #2188

**Comment by Sleet01** [comment]
I've also noticed that the generated Heat Buildup line is not getting cleared when a set of weapons are set to fire and then cleared.

**Comment by repligator** [comment]
Same here. It looks likes it clears if you press delete to undo things weapon by weapon, but sticks if you press escape.

**Comment by repligator** [comment]
Fixed by https://github.com/MegaMek/megamek/pull/5910 . Closing.
