### ISSUE TITLE
43.3 BA not loading corretly

### ISSUE THREAD

**Issue by pjfarland** [MegaMek/megamek#575]
Trying to play WoB 3075.  Loading up 20+ BA using the RAT Generator.  Causes them to load invisibly, freeze MM, appear over top of one another.

**Comment by neoancient** [comment]
Please refer to the bug submission guidelines when making a bug report. You have been asked to do this repeatedly.
https://github.com/MegaMek/megamek/wiki/Making-a-Bug-Report
