### ISSUE TITLE
[49.20] Units reinforced from MUL sometimes swap sprites with other unit sprites

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#5769]
I have seen this issue as far back as 0.48 or even earlier, but it has been difficult to deliberately reproduce. However, I currently have a saved game that appears to at least partially demonstrate the issue, as well as some documentation from in-game experience. 

Sometimes, when reinforcing from a MUL, the sprites of the reinforced units will be replaced with sprites of other units, especially previously destroyed units. Here, you can see that the Hunchback sprite is actually that of a destroyed Ontos, and the one Cheetah sprite is actually from a destroyed Drillson Heavy Hover Tank.
![image](https://github.com/user-attachments/assets/9cb681a7-72ec-452e-bb9d-c0f14b0aba7a)

Interestingly, I found that the Cheetah sprite was actually _swapped_ for the sprite of the destroyed Drillson Heavy Hover Tank, showing up in the hex where the tank was destroyed. I was not able to confirm whether the Ontos wreck sprite was swapped for the Hunchback sprite.
![image](https://github.com/user-attachments/assets/481d188b-1ca5-48b9-8089-84ae42c7294e)

Whenever this bug occurs, turning the client setting "Show damage to units on the unit icon" off and on again will generally reset the sprites to their correct state, as seen below.
![image](https://github.com/user-attachments/assets/e0764d79-1a36-42d3-8715-f13cc6e04b1b)

This led me to believe that it would not reproduce from a saved game, but here it appears to do so at least partially. In particular, the save game was after movement and firing, at which point the Cheetah was destroyed, and _its_ wreck sprite in hex 2743 has remained as the Drillson sprite. 
![image](https://github.com/user-attachments/assets/24d99722-dd30-4724-b9b3-5937e9df449e)

Interestingly, the original Drillson wreck in hex 3841 is now displayed correctly after loading the savegame. 
![image](https://github.com/user-attachments/assets/0d658533-e2fd-4de4-b05c-a185dde762a8)

I note that I actually had two clients connected to the game server for this game; on one client I had flipped the setting off and on to correct the sprite glitch (prior to the Cheetah moving), but on the other client I did not, and the sprite switch persisted through the end of the movement phase for that client, into the firing phase, as seen below.
![image](https://github.com/user-attachments/assets/a2beb470-9241-4a14-945c-0c510c60555c)

Going back through my autosaves from Paranoid Autosave, I managed to locate the save from immediately after deployment of the reinforced units. Loading this autosave also appears to partially reproduce the sprite bug. Interestingly, the Cheetah is now displayed with the correct sprite, but the Drillson wreck in hex 3841 is still the Cheetah sprite. It seems only the incorrect wreck sprites persist through a save and reload, and then only sometimes.

Savegames:
[bigGameDay4end.sav.gz](https://github.com/user-attachments/files/16327432/bigGameDay4end.sav.gz)
[autosave_2024-07-21_15-12-01.sav.gz](https://github.com/user-attachments/files/16327547/autosave_2024-07-21_15-12-01.sav.gz)

**Comment by IllianiCBT** [comment]
Probably the same issue as #5661

**Comment by gsparks3** [comment]
I'm not so sure it's the same root cause, although the effect is similar. Worth noting the possibility, at least.

**Comment by repligator** [comment]
When loading [autosave_2024-07-21_15-12-01.sav.gz](https://github.com/user-attachments/files/16327547/autosave_2024-07-21_15-12-01.sav.gz) on 49.20, I also see the Drillson wreck as a Cheetah.
I tried to reinforce from a random post-battle MUL I had laying around. I tried actually playing the game but replacing all the players with bots ate my RAM almost instantly. The log does seem to indicate that it loaded the correct sprites from the MUL.

When looking at the other recent sprite issue, I experimented with adding `mechImageList.clear()` and `mechImages.clear()` to `case FILE_REFRESH_CACHE:` so that every time the user selected Game -> Refresh Unit Cache, the sprites would be refreshed as well. I wonder if that would be useful, (or even effect) this issue?

[megamek-mul-load.log](https://github.com/user-attachments/files/16393055/megamek-mul-load.log)
[Ghost Bears.mul.zip](https://github.com/user-attachments/files/16393023/Ghost.Bears.mul.zip)

**Comment by SJuliez** [comment]
@gsparks3 Does the MUL you reinforced from include unit IDs? This looks like overlapping unit IDs leading to icon cache retrieval errors. Which is what happened in #5661 where the old cache entries persisted over a game /reset.

**Comment by gsparks3** [comment]
I'd have to check, but it's very likely that it did - most of us play with Show Unit IDs enabled, and I believe having that active causes unit IDs to be saved to MULs?

**Comment by gsparks3** [comment]
Attached is the MUL, which does appear to contain saved unit IDs.

[2nd FWL 3rd Company.zip](https://github.com/user-attachments/files/16400370/2nd.FWL.3rd.Company.zip)

**Comment by gsparks3** [comment]
Hah - in the screenshots in the first post, you can see that the wreck of the Drillson and the reinforced Cheetah have the same unit IDs listed. That's definitely it.
