### ISSUE TITLE
[Bug] [0.49.19.1] BMM Flamers and Partial Cover

### ISSUE THREAD

**Issue by stonewall072** [MegaMek/megamek#5777]
It appears that flamers are not interacting correctly with partial cover when the "BMM Flamers" rule is turned on. With that rule enabled, heat is being applied to the target, regardless if the hit actually strikes the mech or strikes the cover.

![Screenshot 2024-07-23 120132](https://github.com/user-attachments/assets/ea06e057-011c-483e-82f0-9000b06542d7)
Here the BMM rule is turned off and the flamers are set to heat mode. The shot hits, but because it strikes the leg behind cover, no heat is applied.

![Screenshot 2024-07-23 120822](https://github.com/user-attachments/assets/2bb294f2-3a22-4734-baa6-ea965be0c45d)
Here the BMM flamer rule is turned on.  The attack again strikes a leg behind cover, and no damage is applied, but heat is.

And some references showing this shouldn't be the case: 

https://bg.battletech.com/forums/index.php?topic=64189.0
https://bg.battletech.com/forums/index.php?topic=64121.0

**Comment by stonewall072** [comment]
Whoops, didn't realize another post was in the works when I did this. This can be merged/marked as duplicate with #5778.

**Comment by HammerGS** [comment]
We can leave this open and close it when a fix is eventually sorted.
