### ISSUE TITLE
Dropship Line of Sight Issue - Megamek 0.49.15.1

### ISSUE THREAD

**Issue by Gumbivalence** [MegaMek/megamek#5785]
### Environment

This issue applies to the 0.49.19.1 release of MegaMek, and has been reliably replicated in both standalone and MekHQ's megamek apps. 

I am currently running the apps on Windows 10 AMD 64-bit.

Java Version: 21.0.2

### Description

It appears that grounded dropships are blocking their own line of sight. All grounded dropships appears to have no line of site to any space outside of their own hull. I suspect that this is because line of sight is being drawn from the hex within the center of the dropship, but is being blocked by the hexes composing the dropship's hull, like other unit's LOS are supposed to be. 

The attached save file is using a Union-class to demonstrate, but this problem has persisted among all spheroid and aerodyne dropships

 I've tested. The instant the unit's sprite becomes the seven-hex version used for ground maps, the unit goes blind. I've also tested launching dropships back to the air, and the instant they revert to their one-hex, in-flight sprite, their LOS returns. 

This issue persists through the movement and shooting phases. However I have to report that, counter to my previous reports, I've discovered that this bug may be mostly graphical. On further testing, I can still select and target any valid units within valid firing arcs on the ship and attack them - there's just no way to tell which enemy units are in LOS before clicking on them, cycling to a valid weapon group, and seeing if they're actually targetable. Which is a bit clunky. 

### Files

Here's a save game to help demonstrate, on wide-open terrain. The dropship is currently at 1 altitude, so it can easily be demonstrated that this is an issue with grounded ships, only. 
[Dropship-Error.sav.gz](https://github.com/user-attachments/files/16362341/Dropship-Error.sav.gz)

**Comment by repligator** [comment]
All the following screenshots were taken on the latest master (as of this post at least). 

The intruder is direct firing on the trees despite them being grayed out.
![Screenshot_20240724_091607](https://github.com/user-attachments/assets/6a0e7eda-91bd-4e23-a2c9-ca975af63087)

I've attached further screenshots in a zip. Correct LOS is displayed during deployment. It is also displayed during the movement phase, but only if the dropship attempts to move, even if it isn't capable of moving.
[Pictures.zip](https://github.com/user-attachments/files/16362710/Pictures.zip)
