### ISSUE TITLE
Combat Computer Quirk malfunction in MM (49.19.1)

### ISSUE THREAD

**Issue by Desertdream2** [MegaMek/megamek#5787]
### Environment
MegaMek 49.19.1
Windows
Java Vendor: Eclipse Adoptium
Java Version: 11.0.17
Platform: Windows 10 10.0 (amd64)

### Description
Screenshots below. Issue is, when using Quirks and Combat Computer, the Combat Computer is not applying the lowering of heat by four until AFTER the next movement phase.

Example below, I overheat by 8 during the firing phase, expecting the combat computer to lower that by 4, so I am only +4 heat on the heat scale. But come the movement phase, I am still at +8 heat and so suffer the movement penalty. I did attempt to stand, causing another 2 heat during the movement phase, which is why when I get to 2nd firing phase, I am now at 6 heat (+8 prior shooting, -4 from combat computer, now applied, and +2 from movement = 6).

![image](https://github.com/user-attachments/assets/7efdf2c8-f7dc-448d-b025-8c1d2e4713f8)
![image](https://github.com/user-attachments/assets/089be680-26f8-4640-a351-09de9aa270b3)
![image](https://github.com/user-attachments/assets/a3ecc46f-f5b3-4654-8723-1fac7bbe1d92)
![image](https://github.com/user-attachments/assets/1e40f886-4146-4b92-b82f-80347dc2d7cd)

### Files
[gamelog.zip](https://github.com/user-attachments/files/16367239/gamelog.zip)

[megamek.zip](https://github.com/user-attachments/files/16367244/megamek.zip)

**Comment by kuronekochomusuke** [comment]
what did you fire in the first round to get to the 28 heat?

**Comment by Desertdream2** [comment]
I fired 2xLarge Lasers (2x8=16), 4xMedium Lasers (4x3=12), and 1 SRM 6 (1x4), so my heat should have been 32 (not 28 like I originally assumed). So then it is subtracting out the 4 heat for the Combat Computer (nice catch). So then the combat computer is removing the 4 heat between the movement phase and the firing phase? I just recreated it, but without the SRM 6 and so went to 24 heat (even though I should have been 28), and the next movement phase I am at 4 (makes sense, sinking 20 from 24 leaves 4), but then once the firing phase begins, I am now at 0.

**Comment by kuronekochomusuke** [comment]
the weapon display factors in the combat computer for the current turn.   This is to make it easier to control heat for TSM etc.

0 is the lowest value so it is not included until you have some heat applied.

**Comment by Desertdream2** [comment]
That makes sense, but that is a change from a previous version, right? I do not recall that being the case in an earlier version (but maybe I am just misremembering). And should I now mark this closed?

**Comment by kuronekochomusuke** [comment]
It was changed #4924 last year.  so can close it

**Comment by Desertdream2** [comment]
Thank you.
