### ISSUE TITLE
Reflective armor takes strange damage from falls V43.1

### ISSUE THREAD

**Issue by MarcJC** [MegaMek/megamek#579]
On round 8 firing by the Daikyu on the Kamakiri. 
The engine is critted and it falls out of the sky. 
The damage it takes from the fall is just wacky.  
I think I had noticed reflective armor taking strange damage from all physical attacks but I never thought to check the logs.  

Log is attached along with the custom configs in the attached zip.  
Load the Sins.mul to get all the quirks used.
[logs.zip](https://github.com/MegaMek/megamek/files/1185417/logs.zip)

It is also related to issue 341 
https://github.com/MegaMek/megamek/commit/ed02e14d473d8301216ef52513c1d9cc86cc715c
and more info can be found on the boards at 
http://bg.battletech.com/forums/index.php?topic=58134.0  

Let me know if you need more information.

**Comment by beerockxs** [comment]
Here's the relevant part of the log:
Kamakiri Attack VTOL (Standard) (Princess) has lost its movement and crashes.  It plummets 1 levels to the ground.
      Kamakiri Attack VTOL (Standard) (Princess) falls on its front, suffering 12 damage.         Kamakiri Attack VTOL (Standard) (Princess) takes 5 damage to FR (critical).              Reflective armor takes double damage from physical damage: 35 armor doubles 17 damage to 34, for 22 total damage.             13 Armor remaining.             Critical hit on FR. Roll is 2; no effect.         Kamakiri Attack VTOL (Standard) (Princess) takes 5 damage to FR.              Reflective armor takes double damage from physical damage: 13 armor doubles 6 damage to 12, for 11 total damage.             2 Armor remaining.         Kamakiri Attack VTOL (Standard) (Princess) takes 2 damage to FR.              Reflective armor takes double damage from physical damage: 2 armor doubles 1 damage to 2, for 3 total damage.             Armor destroyed.              5 Internal Structure remaining.             Critical hit on FR. Roll is 9; Sensors Hit! Kamakiri Attack VTOL (Standard) (Princess) takes internal damage from a fall and explodes. The VTOL has a fusion engine, so the explosion doesn't have any effect.

**Comment by arlith** [comment]
This bug is actually a direct result of this commit: e83843181

The intent of that commit is to fix a bug where you should only double the damage that applies to the armor.  For instance, if you have 6 armor left and 8 physical damage is dealt, the total damage should be 11, not 16, since only 3 points of damage should be doubled, since there is only 6 points of armor left.

The code that was added works... but only if the amount of armor is less than the total amount of damage.  If the armor is higher (or much higher in this case) than the damage, things get goofy.

**Comment by arlith** [comment]
Instead of the damage increase being `Math.max(0, currArmor / 2)`, I changed it to `Math.min(damage, currArmor/2)`.  That means it will take the smallest of the current amount of damage or half the armor.  

I also changed the report to this:

Reflective armor takes double damage from physical damage:  <data> armor increases <data> damage by <data>, for <data> total damage.

In addition to reporting the right numbers, this makes it clear what's happening in the case when damage > armor, but it's also not as weird when damage < armor.

**Comment by MarcJC** [comment]
I don't think this is the answer though.  

I think that in the case where a 100 mech kicks another mech it should do 20 damage.  
If the location kicked (leg) is covered in reflective the damage would be doubled to 40.  

Lets do this math on a target that has 10 armor and 5 structure on the hit location.  

20 doubled but limited by double armor is still 20 (10 *2)  leading to a breach and then 10 damage to the IS.  
That takes 5 dmg and 5 is passed along to the torso.  
In case A the torso is regular armor and 5 more damage are taken.  
Total damage is 10+5+5=20 != 40 
In case B the torso is reflective and the remaining 5 is doubled to 10 (or less depending on the remaining armor).  
Total damage is 10+5+10=25 != 40  
In case C the torso is impact resistant or ferro L and well I forget some of the damage calcs but it will be less than 5  
Still the damage is not correct even if it should be less than 40 now.  

I think what is needed is a flag for patchwork armor and a variable to record the previous armor location.  
Then the remaining damage pool can be adjusted when the armor switches between locations.  

I have to run so I can't post the rest of my psuedo code, but this may hinge on a rules question of does the IS take double damage when reflective armor is hit.

**Comment by arlith** [comment]
It's not just a flat doubling of damage.  It's, physical damage done to a pip of of reflective armor takes up an additional pip of armor.  So, if you deal 20 physical damage to 10 points of reflective armor, you definitely don't do 40 points of damage.  That was the way things were done originally, and it's wrong.

You cannot just take the incoming damage and double it.

**Comment by MarcJC** [comment]
Ok I can see what you are saying about it not just doubling (I am not sure if I agree, but that is not the issue)  
Will this then effect various armor's abilities to halve damage taken, so that they only halve enough damage to go through the armor?  
Example Reflective armor on a limb has 5 points left and is hit by an Clan ER PPC for 15.  
Now it should take 10 points of damage to break the armor and 5 points would be done to the IS.  
Previously it would just round the 15 down to 7 and do 2 to the IS.  
Special question for Ferro-L  
Lets say 10 points of Ferro-L are on a limb which is hit by an AC 20.  
Right now it would take 4 away from the hit, and do 16, 6 of which go to the IS.  
But it only takes 15 of the 20 dmg to break all the Ferro-L so should the last cluster of 5 points not be reduced because there is no longer armor to apply it's reduction?

**Comment by arlith** [comment]
The code in question is only for reflective armor against area saturation artillery and physical attacks.

**Comment by arlith** [comment]
Here is the blurb from BMM pg 114 that indicates the doubled damage from the armor doesn't transfer:

> Remaining points of damage that were created as a result of
> the damage-doubling effect do not transfer to internal structure. For
> example, a 5-point hit would be doubled to 10 points of damage. A
> location with 9 points of armor would lose all 9 points to this hit, but
> the remaining single point would be lost, with no damage transfer.

**Comment by MarcJC** [comment]
Thanks for the BMM blurb, I guess I was remembering an older rule set.  
Since this effects only the two damage types on reflective, do you want me to open a bug report for the various halving effects of armor overflowing?  
Also if I remember correctly composite structure also takes double damage, does that code need to be updated as well, and would you like me to open a bug report for that also?  

Thanks for all the hard work.

**Comment by arlith** [comment]
If you have saved games that reproduce the issue, it makes it a lot easier to fix.  To be honest, I don't know if the other armor types handle it correctly or not.  If you test it (the saved game needs to be saved before the firing phase is resolved, preferably on the last unit so I just need to hit done and then see the report) and find the values are incorrect, create a bug report and attach the saved game and I can look into fixing it.
