### ISSUE TITLE
Low-altitude Map Terrain not Obstructing Fire

### ISSUE THREAD

**Issue by pokefan548** [MegaMek/megamek#5795]
### Environment
0.49.19 & 0.49.19.1

### Description
Terrain on the low-altitude map is not obstructing line-of-sight for attacks, as described on _TW_ p. 242

### Files
Image provided by RaozSpaz.
![image-48](https://github.com/user-attachments/assets/633f3de3-2fc1-4694-9fcd-be3a40686f23)

**Comment by pokefan548** [comment]
Additional note, per p. 81, bear in mind that woods only extend one altitude above the underlying ground, and other terrain types such as buildings are typically ignored on the low-alt map unless attempting to land. This will need to be accounted for when fixing LOS for attacks.

**Comment by Sleet01** [comment]
> Additional note, per p. 81, bear in mind that woods only extend one altitude above the underlying ground, and other terrain types such as buildings are typically ignored on the low-alt map unless attempting to land. This will need to be accounted for when fixing LOS for attacks.

You are lucky that GitHub does not support the full gamut of crying-face emojis!
