### ISSUE TITLE
Naval Missiles with Nuclear warheads are not factored into BV

### ISSUE THREAD

**Issue by repligator** [MegaMek/megamek#5799]
### Environment
Master (Latest PR https://github.com/MegaMek/megamek/pull/5792)
Linux
Java 17

### Description
Loading a missile bay with nuclear equipped missiles (Peacemaker, Santa Anna) will not alter the the BV of a ship. It will continue to display the BV of a ship armed with traditional missiles (Killer Whale, White Shark).

![Screenshot_20240726_123348](https://github.com/user-attachments/assets/01469d22-20cd-4d99-931a-fb182c04cf76)
![Screenshot_20240726_123417](https://github.com/user-attachments/assets/652e723a-bf93-480e-b15f-cbb4b9e9f4b5)

### Files
[nuclear_warheads.sav.gz](https://github.com/user-attachments/files/16394395/nuclear_warheads.sav.gz)

**Comment by pavelbraginskiy** [comment]
Nukes aren't covered by BV at all AFAIK. Unless there are different rules for aerospace nukes?

**Comment by repligator** [comment]
I assumed they had BV in the rules because they have an `ammo.bv` value in `megamek/common/AmmoType.java` . However, upon actually consulting BT:IO:AE "...nuclear and biological weapons receive no Battle Value to speak of." Closing.
