### ISSUE TITLE
"Allow Terrain Changes" button does not seem to function

### ISSUE THREAD

**Issue by VictorMorson** [MegaMek/megamek#58]
The Allow Terrain Changes button, even if left unchecked, has no impact on Moderate or greater rain or snow from filling a hex board, resulting most often in mud fields.

Steps to reproduce:
1) Pick a map with grass or standard terrain hexes.
2) Set heavy rain.
3) Uncheck "Allow terrain changes"
4) Continue into the map and witness the mud

**Comment by SJuliez** [comment]
Witnessed.

It appears that the setting was not checked at all. Created a fix, placed with the EntitySprite stuff.

**Comment by arlith** [comment]
Fixed in 0420b0.
