### ISSUE TITLE
[0.43.2-git : Bug] VTOL Cannot Fly Over Bridge

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#580]
VTOL cannot fly over bridge even when its elevation = 6 while the bridge elevation = 2. Savegame attached.

[VTOLCannotFlyOverBridge.sav.gz](https://github.com/MegaMek/megamek/files/1186332/VTOLCannotFlyOverBridge.sav.gz)

**Comment by neoancient** [comment]
This is a duplicate of #483, which was fixed and is working in 0.43.3.
