### ISSUE TITLE
Validation accepts Heavy Gauss Rifle with ICE

### ISSUE THREAD

**Issue by pavelbraginskiy** [MegaMek/megamek#5811]
### Environment
MML from master branch

### Description
Units with an ICE rather than a nuclear engine can mount a heavy gauss rifle without being marked invalid, despite this being forbidden (TechManual p219).

Notably, the Gauss-Buster is a canonical unit with the Illegal Design quirk for violating this rule, but it passes validation. 

![image](https://github.com/user-attachments/assets/6779d2ec-fe04-4890-b12f-82ebbeeff03e)

**Comment by stonewall072** [comment]
This is also an issue with the Hyper Laser.
