### ISSUE TITLE
[0.50.0-SNAPSHOT] NPE During Counterbattery Fire

### ISSUE THREAD

**Issue by stonewall072** [MegaMek/megamek#5821]
### Environment
0.50.0 (Nightly from 7/28)
Java Vendor: Eclipse Adoptium
Java Version: 17.0.11
Windows 11

An NPE occurred when pressing the counterbattery fire icon. The action had worked previously several times during the match. Log and save attached.

[CounterBatteryNPE.sav.gz](https://github.com/user-attachments/files/16416944/CounterBatteryNPE.sav.gz)
[megamek.log](https://github.com/user-attachments/files/16416946/megamek.log)

**Comment by repligator** [comment]
```
13:34:45,127 ERROR [megamek.client.AbstractClient] {AWT-EventQueue-0}
megamek.client.AbstractClient.handlePacket(AbstractClient.java:346) - Failed to parse Packet command ENTITY_ATTACK
java.lang.NullPointerException: Cannot invoke "megamek.common.Hex.containsTerrain(int)" because the return value of "megamek.common.Board.getHex(megamek.common.Coords)" is null
```

**Comment by Sleet01** [comment]
This looks like an issue with SerialKiller, which has since been replaced.

Testing with on-board and off-board artillery on more recent code does not show this issue; closing.
