### ISSUE TITLE
LAMs in fighter mode throwing java.lang.ClassCastExceptions when accelerating or going down >1 altitude

### ISSUE THREAD

**Issue by A-Distinguished-Axolotl** [MegaMek/megamek#5826]
### Environment
Megamek w/ Mek HQ 49.19.1
Windows
Java Version: 17.0.2

### Description
There are two errors:
The first is when a LAM in fighter mode attempts to accelerate. Doing so produces a java.lang.ClassCastException but still adds the velocity to the unit as expected, and so while annoying, does not actually prevent any game mechanic from occurring
The second is when a LAM in fighter mode attempts to go down 2 or more altitudess. It can go down 1 altitude perfectly fine, but upon trying to go down a second altitude a java.lang.ClassCastException is thrown. Even stranger is that each time this "go down" fails, it adds one velocity, stacking without any limit I can find myself (presumably due to the fact that it would be going down the second altitude, which would add 1 to an ASF fighter's velocity, but who knows). In this case, going down more than 1 altitude is dysfunctional and has a gameplay effect.

Below are images of the errors and their results.

![LAM_Accel_Error](https://github.com/user-attachments/assets/d0eb8549-04ad-4927-ab75-fcf433df4eba)
![LAM_Accel_Error_Result](https://github.com/user-attachments/assets/70756ba3-1369-47af-aa46-5d937f6c06c1)
![LAM_go_down_error](https://github.com/user-attachments/assets/f292153c-fbbb-47d0-ba72-f291174cbb84)
![Lam_Go_Down_Error_Result](https://github.com/user-attachments/assets/9eb949ce-618b-46a1-813c-2003fe99d95a)

Replicating the error should be easy enough - just load a LAM into a low altitude map in fighter mode and try accelerating or going down at least 2 altitudes.

Of potential note is that this error also occurs in exactly the same way on ground maps as far as I am aware.

### Files
Name: Axo
[megamek.log](https://github.com/user-attachments/files/16422810/megamek.log)

**Comment by Sleet01** [comment]
Should already be fixed by https://github.com/MegaMek/megamek/commit/c37b4d20a495db8d153e45dc6ed5059ac342a4b4

Closing.
