### ISSUE TITLE
Validation accepts RISC Hyper Laser with ICE on vehicles

### ISSUE THREAD

**Issue by pavelbraginskiy** [MegaMek/megamek#5831]
MegaMekLab, latest master.

See also #5828 and #5811.

While industrialmeks are marked as invalid if they have both a nonnuclear engine and an RHL, tanks with ICEs (and possibly other unit types?) can mount an RHL and pass validation, despite this being illegal.

**Comment by SJuliez** [comment]
Yes, this test must be moved out of TestMech
