### ISSUE TITLE
Meks always crash into buildings when jumping

### ISSUE THREAD

**Issue by servo01** [MegaMek/megamek#584]
Meks crash into buildings while jumping regardless of building height.

[Building.sav.gz](https://github.com/MegaMek/megamek/files/1198918/Building.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/1198919/megameklog.txt)

**Comment by HammerGS** [comment]
Already been fixed for the next release
https://github.com/MegaMek/megamek/issues/573
