### ISSUE TITLE
[0.49.19.1] Spacing in unit right-click menu options needs correcting

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#5849]
MegaMek 0.49.19.1 suite version
Windows 10
Java 11

When a unit is right-clicked during a battle, the menus are missing a space between the 'fixed text' (e.g. 'Target' and the unit name, as per these images.

![image](https://github.com/user-attachments/assets/4d3b96d0-f873-46ce-8c3f-ea6b94268f10)

![image](https://github.com/user-attachments/assets/ed91fec5-007a-4455-83d4-ad66ff62a726)

![image](https://github.com/user-attachments/assets/2f19edd9-71ca-4082-9e55-4c1680e5c719)

**Comment by repligator** [comment]
Fixed for version 50, see PR https://github.com/MegaMek/megamek/pull/5791 . Closing as completed.
