### ISSUE TITLE
[0.49.19.1] Default f-key hotkeys for Unit Display tabs in wrong order

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#5851]
MM 0.49.19.1 Bundled
Windows 10
Java 11

The default f-key hotkeys for the tabs in the Unit Display are out of order.

General tab - f1
Pilot tab - f2
Armor tab - f3
Weapon tab - f5
Systems tab - f4
Extra tab - f6

They're listed on the Client Settings 'Key Binds' tab in a different order from the display order on the Unit Display, which might have contributed ...

![image](https://github.com/user-attachments/assets/62263785-7cdb-49a4-b62a-c525c7547874)

![image](https://github.com/user-attachments/assets/ee24cfc2-c09d-49d8-9abc-1c89c00f07a1)

**Comment by Sleet01** [comment]
I have the auto-switch work done, so I'll update the hotkeys and put the PR up later today.

**Comment by SimonLandmine** [comment]
@Sleet01 And to think I'd not even got around to writing the RFE for the auto-switch bit! That was quick work.
