### ISSUE TITLE
RFE - Sentry Changes or Clarificaitons

### ISSUE THREAD

**Issue by Thom293** [MegaMek/megamek#5872]
It has been stated that sentry defaults to OFF.  However, it was explained to me tonight that even when off, it will still gather data but just discard it and not send it anywhere.  If I have misunderstood how it works, I apologize but I believe that to be it.  (There is an issue with this that I have reported).  

However, going forward, I would request:
1.  When its off, it should actually be off.  Intentions aside, if something odd happens and it accidentally prints data somewhere and people find out that it was not actually off when described to be off, they might be a bit concerned; or
2. If 1 is not accepted, then the description of off mode should be changed to more accurately reflect what is happening, so people are not surprised.  

Thank you.

**Comment by Thom293** [comment]
Maybe an old version, but I found this on the google.

https://github.com/getsentry/sentry-java/issues/574

**Comment by gsparks3** [comment]
Collecting information and not sending it anywhere except your own hard drive is not functionally different than not collecting it in the first place.
