### ISSUE TITLE
[0.50.0-SNAPSHOT] Edge anomalously keeps rerolling until failed for conscious check. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/megamek#5874]
### Environment
04:12:25,599 INFO  [megamek.MegaMek] {main}
megamek.MegaMek.initializeLogging(MegaMek.java:143) - Starting MegaMek v0.50.0-SNAPSHOT
    Build Date: 2024-08-08T01:18:30.430912410
    Today: 2024-08-08
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 21.0.3
    Platform: Windows 11 10.0 (amd64)
    System Locale: en_GB
    Total memory available to MegaMek: 8 GB
    MM Code Revision: b354eed76272d62456151d7641702603a26077a6
    MML Code Revision: 35aa5ce66ca59272c0d1e05c3d174cd4c0335b3c
    MHQ Code Revision: 35f7eba88bb72e5ae7f2a0e1b0c414a89cf3b628
    
### Description
![image](https://github.com/user-attachments/assets/be7702e0-9a7e-43d1-9829-8889982c010a)

Following a fall, above occurred.
EDIT: interestingly he is still awake afterwards.

### Files
[quicksave.sav.gz.zip](https://github.com/user-attachments/files/16537378/quicksave.sav.gz.zip)
[megamek.log](https://github.com/user-attachments/files/16537382/megamek.log)
[CustomUnit.zip](https://github.com/user-attachments/files/16537403/CustomUnit.zip)

**Comment by Sleet01** [comment]
@Algebro7 this looks like a new version of the bug you fixed earlier.

**Comment by IllianiCBT** [comment]
Not directly related to the issue, but the issue did prompt something in my noggin:

We've semi-frequently received requests to have Edge to only fire once per trigger. Is this something we could incorporate into the fix? Or, potentially, Algebro's earlier work.

**Comment by Algebro7** [comment]
> We've semi-frequently received requests to have Edge to only fire once per trigger. Is this something we could incorporate into the fix? Or, potentially, Algebro's earlier work.

That's possible but since I already introduced a bug once I'm kind of afraid to roll more changes into this one :sweat:
