### ISSUE TITLE
v0.50.0-SNAPSHOT NPE while deploying units

### ISSUE THREAD

**Issue by DynamicWorlds** [MegaMek/megamek#5878]
v0.50.0-SNAPSHOT
Win 10
Java Vendor: Eclipse Adoptium
    Java Version: 17.0.11

### Description
Partway through deploying units at the start of the game, I keep running into a recurring npe that keeps coming back when I hit OK.
Unsure what the specific trigger is as it doesn't start until a number of units into the deployment phase.

### Files
[Trond's Dragoons30250219C.cpnx.gz](https://github.com/user-attachments/files/16554544/Trond.s.Dragoons30250219C.cpnx.gz)
[Bug1.sav.gz](https://github.com/user-attachments/files/16554546/Bug1.sav.gz)
[mekhq.log](https://github.com/user-attachments/files/16554547/mekhq.log)
[megamek.log](https://github.com/user-attachments/files/16554548/megamek.log)
[customs.zip](https://github.com/user-attachments/files/16554560/customs.zip)

**Comment by repligator** [comment]
@DynamicWorlds 
Can you confirm that you posted the correct save file? The errors are referencing a VTOL unit, but [Bug1.sav.gz](https://github.com/user-attachments/files/16554546/Bug1.sav.gz) has no VTOL units. I was able to load it and deploy everything just fine. You have quite a few cool (and complicated rules wise) custom VTOL units, I'm guessing the parser is failing to parse one of them.

**Comment by DynamicWorlds** [comment]
> @DynamicWorlds Can you confirm that you posted the correct save file? The errors are referencing a VTOL unit, but [Bug1.sav.gz](https://github.com/user-attachments/files/16554546/Bug1.sav.gz) has no VTOL units. I was able to load it and deploy everything just fine. You have quite a few cool (and complicated rules wise) custom VTOL units, I'm guessing the parser is failing to parse one of them.

Confirmed that it is the right save files.  None of my custom vtol units should be involved, though, as the only vtol involved would be 1 SOAR VTOL (stock) and 2 vtol infantry (custom) in the lance that's not being deployed to the scenario. o.O
There shouldn't be any vtols in Bug1 at all on either side.

Just tested again and it seems that if I put a unit on the board without clicking deploy and then click on a different undeployed unit, then the error is being thrown.  If I just deploy them all in default order, however, the error message is not being thrown.

Let me know if there's any other way(s) I can help.

oh forgot this last time
![Temp](https://github.com/user-attachments/assets/187b25d7-f4c8-46e7-b1de-2dd41d8d026a)

**Comment by Sleet01** [comment]
That is likely a UI bug.  I would guess we're trying to swap the unit in the currently-selected hex and getting confused somehow.

**Comment by NickAragua** [comment]
I suspect this has been fixed with PR 5880/5881

**Comment by SJuliez** [comment]
Some of the customs load with the exceptions shown above, e.g. the Command Chopper CC-3085F-C3I
They seem to have patchwork armor on a support vtol. At a quick glance I was unable to create something like that in MML.

**Comment by DynamicWorlds** [comment]
> I suspect this has been fixed with PR 5880/5881

Confirmed.  As far as I can tell from testing, the latest nightly no longer has this problem

**Comment by DynamicWorlds** [comment]
> Some of the customs load with the exceptions shown above, e.g. the Command Chopper CC-3085F-C3I They seem to have patchwork armor on a support vtol. At a quick glance I was unable to create something like that in MML.

Getting off topic as that unit shouldn't even be in the scenario, but...

While I can no longer load the design in earlier MML versions (as I no longer have Java 11 installed) and while there are problems with that design for some unknown reason (now currently registering as having too many used slots, when it didn't when created, possibly due to an update changing how many slots were used by armor), you should be able to create a support vehicle with patchwork armor in MML by putting the armored chassis modification on and then going to the armor tab (the checkbox doesn't appear until armored chassis is checked)

Idk if the change to the number of slots taken up by the armor is correct now, or was correct before, but I'll leave creating an issue on that to someone who knows the construction rules well enough to tell if the current version is correct or not and just readjust the design to not throw an exception.

As far as the original issue goes, this seems to be a solved issue as Nick suspected.

**Comment by SJuliez** [comment]
Closing this, as it appears to be fixed

**Comment by DynamicWorlds** [comment]
I'm getting this error again.  Unsure what changed

v0.50.0-SNAPSHOT (2024-08-12 evening's nightly)
Win 10
Java Vendor: Eclipse Adoptium
Java Version: 17.0.11

[megamek.log](https://github.com/user-attachments/files/16654597/megamek.log)
[mekhq.log](https://github.com/user-attachments/files/16654598/mekhq.log)
[Round-0-autosave_2024-08-18_21-57-18.sav.gz](https://github.com/user-attachments/files/16654600/Round-0-autosave_2024-08-18_21-57-18.sav.gz)
[Trond's Dragoons30250225D.cpnx.gz](https://github.com/user-attachments/files/16654601/Trond.s.Dragoons30250225D.cpnx.gz)
[customs.zip](https://github.com/user-attachments/files/16654603/customs.zip)

**Comment by DynamicWorlds** [comment]
Confirmed fixed with https://github.com/MegaMek/megamek/issues/5903 by https://github.com/MegaMek/megamek/pull/5936
