### ISSUE TITLE
Split equipment on Super heavies

### ISSUE THREAD

**Issue by arekP64** [MegaMek/megamek#588]
[Daishi II Type A.txt](https://github.com/MegaMek/megamek/files/1204996/Daishi.II.Type.A.txt)

While designing variant of my 130t Daishi II ive came across bug with Thumpers (maybe other arty to), when fiting 3 thumpers to LT RT and CT/LT ive noticed that by some reasons the third CT/LT thumper dissapears.

first image is how its loaded in, second is how it should be
http://imgur.com/a/zi175

**Comment by HammerGS** [comment]
Also referenced here - https://github.com/MegaMek/megameklab/issues/68

**Comment by neoancient** [comment]
This should have been reported on the MegamekLab tracker.

**Comment by neoancient** [comment]
So it turns out this is a problem with loading after all. When loading split equipment MM was only counting a single slot for each in the file instead of a superheavy double slot.
