### ISSUE TITLE
UI breaks and errors thrown when trying to load a save, carried objects related?

### ISSUE THREAD

**Issue by repligator** [MegaMek/megamek#5882]
### Environment
Java 17
Linux
Master (Latest PR https://github.com/MegaMek/megamek/commit/af9d24f9d2da6a2051b42d582c19e74a667b3d9b )

### Description
When trying to load "old" (and by old I mean a week or so) saves, the whole user interface breaks. It's hard to describe, but things don't appear to update properly, old panels are still drawn on top of new ones, etc. See attached screenshot.

```
megamek.client.AbstractClient.handlePacket(AbstractClient.java:347) - Failed to parse Packet command SENDING_PLANETARY_CONDITIONS
java.lang.NullPointerException: Cannot invoke "java.util.Map.values()" because "this.carriedObjects" is null
```

![Screenshot_20240809_150344](https://github.com/user-attachments/assets/8c5fc782-28b3-44d1-976d-c26bc9cd6736)

### Files
[megamek.log](https://github.com/user-attachments/files/16565833/megamek.log)
[another.megamek.log](https://github.com/user-attachments/files/16565834/another.megamek.log)

**Comment by HammerGS** [comment]
That would be expected given the changes in the nightlies.

**Comment by repligator** [comment]
Normal incompatibility between different nightly builds, closing.
