### ISSUE TITLE
Battle Armor Units using the wrong sprite for their squad size

### ISSUE THREAD

**Issue by repligator** [MegaMek/megamek#5884]
### Environment
Java 17
Linux
Checked against last nights MML nightly, posting under MM because it affects all 3 projects.

### Description
The following BA units have the wrong number of soldiers in their sprite relative to their squad size. For example, Stormbird Battle Armor | (Jade Falcon)(**Sqd4**) shows 5 soldiers.

Stormbird Battle Armor | (Jade Falcon)(Sqd4)
Tornado PA(L) | P17 'Hurricane'(Sqd4)
Dragoon Battle Armor | (Advanced)(Sqd5)
Ailette Zero-G Engineering Exoskeleton | (Sqd5)
Achileus Light Battle Armor | (WoB)(Sqd5)
Grenadier Battle Armor | [SRM/SL](Sqd5)
Tornado PA(L) | P17 'Hurricane'(Sqd5)
Dragoon Battle Armor | (Advanced)(Sqd6)
Stormbird Battle Armor | (Jade Falcon)(Sqd6)
Ailette Zero-G Engineering Exoskeleton | (Sqd6)
Grenadier Battle Armor | [SRM/SL](Sqd6)

**Comment by HammerGS** [comment]
That would be great. But make sure that any fix is against MegaMek.
