### ISSUE TITLE
50.00 - Increased AC damage rule seems to be on by Default, even though it is turned off.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/megamek#5885]
Simply, option shows it is turned off, but AC2 and AC5 show they are doing 1 more damage each.  Seems like it is somehow turned on in the background?

Just thinking out loud - but I do have rapid fire AC and kinder rapid fire AC rule on.  Maybe this other alternate rule became entangled with them somehow?  

Also begs the question - what other options might be accidentally on without us knowing?  

![image](https://github.com/user-attachments/assets/0dcd1ea0-73b7-42a6-9225-1ccd30c8dd49)

![image](https://github.com/user-attachments/assets/26568a64-8682-4c24-8098-d898cc42bb50)

![image](https://github.com/user-attachments/assets/6f3ab874-2eb1-4ea9-8140-40bdb8daf8eb)

**Comment by Sleet01** [comment]
@Thom293 If you have a chance, could you check to see:

A) if you use the options search bar to search for "Increased AC Damage", does it show up as checked or unchecked?
B) does disabling both Rapidfire and Kinder Rapidfire change the effect on AC damage?

I will take a look at the code side.

**Comment by Sleet01** [comment]
It looks like a damage boost was added to ACs, that only activates when Rapid Fire is enabled.  Investigating.

**Comment by Thom293** [comment]
> It looks like a damage boost was added to ACs, that only activates when Rapid Fire is enabled. Investigating.

Confirmed.  Turning off RF sets damage back to normal.  
![image](https://github.com/user-attachments/assets/86a988f7-f701-4496-b2fd-ea9a55119894)

**Comment by Thom293** [comment]
And turning on both RF, KF and Increased AC damage doesnt add another.  ie. AC2s dont do 4 damage and 5s dont do 7.  They do 3 and 6 as expected.   

![image](https://github.com/user-attachments/assets/2392ebe4-d1c4-4c6a-b931-5083171f5eb3)

![image](https://github.com/user-attachments/assets/f84c94b0-06f3-4099-bc36-7cf941b51303)
