### ISSUE TITLE
v0.50.0-SNAPSHOT unloading infantry bug

### ISSUE THREAD

**Issue by DynamicWorlds** [MegaMek/megamek#5893]
### Environment
v0.50.0-SNAPSHOT (2024-08-12 evening's nightly) both standalone and mekqh megamek
Win 10
Java Vendor: Eclipse Adoptium
Java Version: 17.0.11

### Description
My 50ton infantry carrier is dismounting/unloading infantry into adjacent hexes as a large support vehicle when it is a medium vehicle with the following exceptions:
1-can't dismount infantry to occupied hex even when stacking limit is not met
2-only 1 infantry dismount in a turn instead of 2 as per the rules for large support vehicles
3-infantry cannot mount vehicle from adjacent hex as per the rules for large support vehicles

Tech manual pg 11:
"Wheeled: Wheeled Support Vehicles weigh from 0.100 to 4.999 tons at the Small size, 5 to 80 tons at Medium size and 80.5 to 160 tons at the Large size."

to reproduce, simply unload infantry from provided save

### Files
[Test1.sav.gz](https://github.com/user-attachments/files/16605267/Test1.sav.gz)
[megamek.log](https://github.com/user-attachments/files/16605269/megamek.log)
Trond's Dragoons
[customs.zip](https://github.com/user-attachments/files/16605283/customs.zip)

**Comment by RaozSpaz** [comment]
I was able to replicate this in 49.19.1
For whatever reason the medium support vehicle seems to be using Large Support vehicle rules in relation to unloading. And even then it is ignoring the part where it can't unload on a different level.
