### ISSUE TITLE
v0.50.0-SNAPSHOT Offroad and Bicycle chassis modifications not working

### ISSUE THREAD

**Issue by DynamicWorlds** [MegaMek/megamek#5895]
### Environment
v0.50.0-SNAPSHOT (2024-08-12 evening's nightly) both standalone and mekqh megamek
Win 10
Java Vendor: Eclipse Adoptium
Java Version: 17.0.11

### Description
wheeled vehicles with offroad unable to enter or deploy to rough terrain
wheeled vehicles with bicycle unable to enter or deploy to light woods

### Files
[Test2.sav.gz](https://github.com/user-attachments/files/16605517/Test2.sav.gz)
Trond's Dragoons
[customs.zip](https://github.com/user-attachments/files/16605532/customs.zip)

**Comment by RaozSpaz** [comment]
I can confirm that Bicycles chassis modification does not work at least back on 49.19.1 So the issue has been present since at least then
