### ISSUE TITLE
NPE on next weapon cycle for ejected pilots. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/megamek#5901]
### Environment
06:15:09,377 INFO  [megamek.MegaMek] {main}
megamek.MegaMek.initializeLogging(MegaMek.java:146) - Starting MegaMek v0.50.0-SNAPSHOT
    Build Date: 2024-08-13T01:20:20.322515318
    Today: 2024-08-14
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 21.0.3
    Platform: Windows 11 10.0 (amd64)
    System Locale: en_GB
    Total memory available to MegaMek: 8 GB
    MM Code Revision: 8b0a9892f4419b03d76a29ecbfcf22233e2a8fd7
    MML Code Revision: fc321e451b068ba6292e43ecc1f6ce80345d79cb
    MHQ Code Revision: 156e2f11ee630330d7917873ee2ad73127985576

### Description
I use keyboard shortcuts to cycle through next and previous weapons when making firing solutions. 
Doing this on an ejected pilot (who of course has no weapons) causes an NPE. Ideally this should do nothing. 
This can be replicated easily enough by ejecting a pilot, and then attempting to weapon cycle with the kayboard shortcut during their firing phase. Note that the optional rule which provides sidearms for MechWarriors might interfere. 
This is thankfully a very minor bug.

**Comment by repligator** [comment]
This bug will actually effect units other then pilots. As long as it has no weapons, the NPE will be thrown.
```
megamek.MegaMek.lambda$main$1(MegaMek.java:95) - Uncaught java.lang.IndexOutOfBoundsException detected. Please open up an issue containing all logs, the game save file, and customs at https://github.com/MegaMek/megamek/issues . If Sentry is enabled, the error has also been logged.
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
```
[megamek.log](https://github.com/user-attachments/files/16619366/megamek.log)
