### ISSUE TITLE
[0.50.0-SNAPSHOT] Predicted heat values not updating when attack selections are cancelled during firing phase until new weapon is fired

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megamek#5902]
### Environment
megamek.MegaMek.initializeLogging(MegaMek.java:146) - Starting MegaMek v0.50.0-SNAPSHOT
    Build Date: 2024-08-14T01:19:21.935476675
    Today: 2024-08-14
    Origin Project: MegaMek
    Java Vendor: Eclipse Adoptium
    Java Version: 17.0.6
    Platform: Windows 10 10.0 (amd64)
    System Locale: en_US
    Total memory available to MegaMek: 8 GB
    MM Code Revision: 73b326a9d0279583593f95e4a786452171085e4e
    MML Code Revision: fc321e451b068ba6292e43ecc1f6ce80345d79cb
    MHQ Code Revision: 97bfe2272ed3dd97837249f987f8617facdf82ac

### Description
When selecting weapons for an attack, if you hit ESC to cancel attack selections, the predicted heat values do not update until a new weapon is fired. This issue does NOT occur if you use backspace to cancel individual attack declarations.

![1](https://github.com/user-attachments/assets/14b949eb-470e-4038-acb4-d28e5213a7d3)

![2](https://github.com/user-attachments/assets/43358801-0c36-4423-a343-2efaabbc01db)

![3](https://github.com/user-attachments/assets/7c2daa35-00c0-4c40-8a1f-d12f90853820)

### Files
[WeaponDeclarationsUpdate.zip](https://github.com/user-attachments/files/16616767/WeaponDeclarationsUpdate.zip)

**Comment by repligator** [comment]
See also https://github.com/MegaMek/megamek/issues/5736

**Comment by HoneySkull** [comment]
This fix breaks torso twisting by deselecting the weapon on a torso twist.  This fix as is re-introduces #5650
