### ISSUE TITLE
[0.50.0-SNAPSHOT] NPE during deployment phase if a unit is placed on the board and another unit is selected before confirming the first deployment

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megamek#5903]
### Environment
megamek.MegaMek.initializeLogging(MegaMek.java:146) - Starting MegaMek v0.50.0-SNAPSHOT
    Build Date: 2024-08-14T01:19:21.935476675
    Today: 2024-08-14
    Origin Project: MegaMek
    Java Vendor: Eclipse Adoptium
    Java Version: 17.0.6
    Platform: Windows 10 10.0 (amd64)
    System Locale: en_US
    Total memory available to MegaMek: 8 GB
    MM Code Revision: 73b326a9d0279583593f95e4a786452171085e4e
    MML Code Revision: fc321e451b068ba6292e43ecc1f6ce80345d79cb
    MHQ Code Revision: 97bfe2272ed3dd97837249f987f8617facdf82ac

### Description
(Updated to include new information about issue being specific to the Isometric View client setting)

NPE occurs if I perform the following steps:
1. load autosave_2024-08-14_14-15-17.sav.gz
2. hit T to enable "isometric view"
3. select warhammer for deployment
4. Place warhammer into hex 2533 but DO NOT click "deploy" to confirm the selection
5. click on the unit list on the right and select the next unit (Stinger), NPE should occur at this step

This NPE pops up any time you interact with the UI of megamek in any way, including attempting to save or close the game, I have to use task manager to end the process to escape.

The NPE also pops up again if I alt tab to the mekHQ window and attempt to interact with the interface there as well.

Sentry is enabled and should have a record of this NPE (probably several hundred)

### Files
I included my mekHQ campaign that the scenario was launched from but should not be necessary to reproduce the issue, I was able to repro it just by loading the save directly in a fresh MegaMek client

[DeploymentNPE.zip](https://github.com/user-attachments/files/16617996/DeploymentNPE.zip)

**Comment by repligator** [comment]
Using the latest master (https://github.com/MegaMek/megamek/commit/f33d7a95b57ec014dd816d02534eb018aca13256) I can't reproduce the NPE, even when using the attached save. Selecting a unit without finishing deploying the first will temporarily teleport them up to hex 0101 where they will ignore stacking limits until properly deployed.
![Screenshot_20240814_180935](https://github.com/user-attachments/assets/3dd690a1-5dd6-4b2b-94d0-f75e4ede551a)

**Comment by PhoenixHeart512** [comment]
I'm still seeing it 100% of the time with my save file. I'll zip up my entire mekHQ folder so that you can test it with the exact installation I am using, including the config files, in case any of those are affecting it. Due to file size I'll upload it to google drive and post a link, since github restricts attachment file size.

**Comment by repligator** [comment]
@PhoenixHeart512 Just post your MM config file. If you can reproduce inside MM that should be all we need. Also MM client settings.

**Comment by PhoenixHeart512** [comment]
https://drive.google.com/file/d/1AO_wqjjXZcGfZxbAKxzIF0ZZTY2wHx-O/view?usp=drive_link

Also, in case it matters, try launching the scenario from MM by using the Load Scenario button on the briefing tab to start the scenario.

**Comment by repligator** [comment]
I've loaded your MHQ save, loaded your save game, followed your steps exactly, but I still can't replicate the NPE. Have you tried with a different nightly?

**Comment by PhoenixHeart512** [comment]
This was done with the nightly from night before last. I can try to repro again with last night's build, but this was happening on what was considered the latest build until 12 hours ago

**Comment by PhoenixHeart512** [comment]
It does seem to be something related to the stuff in my mmconf folder. I loaded the same nightly build I was seeing this on but made zero changes and simply loaded the game and could NOT replicate the issue. I then copy-pasted my entire mmconf folder from my main installation (same day's nightly build) and tested again and was able to repro the issue.

I was able to narrow it down to my "clientsettings.xml" file with the following process:
1. copy ONLY the clientsettings.xml file to a completely fresh unmodified installation of the same nightly build
2. issue occurs
3. reset to a completely fresh unmodified installation
4. copy everything EXCEPT clientsettings.xml to the mmconf folder from my main installation
5. issue does NOT occur

[clientsettings.zip](https://github.com/user-attachments/files/16628394/clientsettings.zip)

**Comment by PhoenixHeart512** [comment]
I figured out which setting it is, it's the "isometric view" or whatever it's name is, (T hotkey by default).

Issue DOES occur on the latest nightly if I hit T and then follow the same steps of putting a unit on the map and then changing to a new unit.
