### ISSUE TITLE
Board not showing

### ISSUE THREAD

**Issue by SJuliez** [MegaMek/megamek#5905]
In the current master, the whole board and reports and all never show up when the following settings are used:

![image](https://github.com/user-attachments/assets/2bfedca1-2e49-42e4-b0c8-cbce06c3474f)

I haven't looked any further, it is maybe just one of these settings. When Show instead of Manual is used, the board shows.

Edit: looking further, the Round Report settings are responsible.

This setting also does not work:
![image](https://github.com/user-attachments/assets/769e6271-6548-4af6-80da-48ba72d95f6f)

**Comment by kuronekochomusuke** [comment]
with manual you need to maunally show/hide with the hot keys or menu.   It does not do any automated processing, is that working?

Hide should always try to hide them, so you can manually turn it on then when you go into the phase it will hide it.

**Comment by SJuliez** [comment]
Yes. The *board* is not showing when I start a game with those settings. I get a big gray window, although the game itself does run.
