### ISSUE TITLE
Princess not firing ammunition using weapons - v0.49.20-Development

### ISSUE THREAD

**Issue by TonicArtos** [MegaMek/megamek#5907]
Princess is not firing LRMs, SRMs, ACs in release v0.49.20-Development. I checked the previous release (v0.49.19.1 Milestone) and behaviour is as expected.

I noticed this behaviour in my MMHQ campaign, and also verified in MM standalone with 1v1 against Princess running an AC/20 Hetzer. In v0.49.20-Development Princess does not shoot ever.

**Comment by HammerGS** [comment]
Known issue and fixed. 

https://bg.battletech.com/forums/index.php?topic=85357.msg2017662#msg2017662
