### ISSUE TITLE
PSR triggered (and failed!) mid-jump on 0.43.3

### ISSUE THREAD

**Issue by mhjacks** [MegaMek/megamek#592]
In round 4, my Stealth was jumping over a building that collapsed due to enemy movement.  This triggered a PSR on the Stealth, and it fell.

**Comment by mhjacks** [comment]
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/1210024/autosave.sav.gz)

**Comment by HammerGS** [comment]
This might be related to the WiGE building issue fixed here - https://github.com/MegaMek/megamek/issues/584

**Comment by arlith** [comment]
This is a duplicate of #573.
