### ISSUE TITLE
[Dev 43.3] Wrong destroyed unit icon for Centurion aerospace fighter

### ISSUE THREAD

**Issue by NickAragua** [MegaMek/megamek#593]
[centurionoops.sav.gz](https://github.com/MegaMek/megamek/files/1213461/centurionoops.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/1213462/megameklog.txt)

Load up the saved game and take a look at the icon for the destroyed Centurion fighter (it's in the middle of the map). Something seems a little off about it, must be one of those new LAMs.

**Comment by neoancient** [comment]
None of the LAM support is in the master branch yet. That's probably a Centurion mech.

**Comment by NickAragua** [comment]
Sorry, was being slightly sarcastic. :)

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/407a716028ca2bfdee4ab0d96b43d61e5eca3d7c
