### ISSUE TITLE
49.19.1 - Game crash on custom princess settings

### ISSUE THREAD

**Issue by PirateofMRC** [MegaMek/megamek#5940]
### Environment
49.19.1 - Win 10, Home PC

### Description
Game froze turn 2- using Princess v princess with custom settings on both princesses (bot setting turned all the way to left, except Berzerker which is all the way to right). Savegame attached. Princess v Princess, unable to make decision? Sim fire, targeting and physical turned on. 

![round_002_016_Firing](https://github.com/user-attachments/assets/b3dacc2e-6e46-4035-bf8a-e72080a10e3b)
[crashed_princess_sliders.sav.gz](https://github.com/user-attachments/files/16732242/crashed_princess_sliders.sav.gz)

**Comment by Sleet01** [comment]
@PirateofMRC Do you happen to have the `megamek.log` file for this game?  That would help narrow down the issue.

**Comment by Sleet01** [comment]
I've been unable to repro this issue with the above save game.  I did notice one or two units taking longer to process their turns than others, so perhaps it was a slowdown rather than a crash.

Closing until we get a better repro.

**Comment by PirateofMRC** [comment]
sorry @Sleet01  i didn't have notifications turned on in the email associated here. Thanks for looking into it.
