### ISSUE TITLE
[0.49.19.1] Movement with Water & Ice

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#5956]
Windows 10
Java 17
Megamek 0.49.19.1

Edit: Issue 1 is fixed

[Fixed] 1. It is not currently possible to deploy a unit on the surface of frozen water. (I.e. if a hex has depth 3 water with ice on top, units will deploy at the bottom of the water, rather than giving an option to deploy on the ice surface.)
[Open Issue] 2. If a mech in depth 2 water with ice on top moves one hex (remaining in frozen depth 2 water), it is treated as both a) breaking through ice from below in the initial hex, and then b) at risk of falling through ice in the second hex. It does not appear possible to remain underwater and move beneath the ice.

Attached  are autosaves and logs of little test I ran.

[savegames.zip](https://github.com/user-attachments/files/16803770/savegames.zip)
[logs.zip](https://github.com/user-attachments/files/16803791/logs.zip)

Attached is the little 8x8 board I made for testing these, in case it will help with fixing.

[8x8 IceTest.zip](https://github.com/user-attachments/files/16803716/8x8.IceTest.zip)

**Comment by Jagatai** [comment]
Probably related to 2. - you currently can't break through ice if you try to reach land from below it. If you are in depth 2 water with ice on top, you can't move onto a level 0 clear terrain next to it, but you can try to move onto neighboring ice with depth 2 water under it, which will require piloting checks as if you were standing on top of the origin ice hex.

**Comment by SimonLandmine** [comment]
Err ... not sure. I may not get a chance to test it for a few days, I'm afraid. Sorry!

**Comment by SJuliez** [comment]
Also, one can safely deploy tanks into water provided its covered with ice :)

**Comment by SJuliez** [comment]
Edited text and title, deployment should be much better now
