### ISSUE TITLE
NPE in Server$PacketPump.run after recovering a launched ASF or SmallCraft

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/megamek#597]
I am using my own build of 0.43.4 off of the IOTech branch, run through eclipse. I'll be curious to know if this can be reproduced in other versions. 
I recall that recovering a launched ship caused MM to hang in an earlier version in the 0.4x tree, before I had the ability to track it in more detail, so I don't think it's my version.
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/1231780/autosave.sav.gz)

Steps to reproduce:
Load the attached save as 'test'
Do not move either dropship.
Skip Princess. She was only there to deploy the enemy ship for me so I wouldn't automatically win the game after round 1. I kicked her out after deployment. 
Recover either an ASF or Smallcraft in the same hex as the first dropship. 

I tried my hand at debugging this one, but I wasn't able to figure it out. I had a breakpoint in Server at line 8614 and watched the recovery process. It seemed to complete just fine. The NPE doesn't happen until much closer to the end of the recovering unit's action (I think).

**Comment by mkerensky** [comment]
Oops. Forgot the log. 
[megameklog.txt](https://github.com/MegaMek/megamek/files/1231830/megameklog.txt)

**Comment by mkerensky** [comment]
I think I found and fixed this. There was an NPE in Game where it was trying to calculate illumination on  the space map against a newly recovered unit. This only happened when the recovery took place within the 70 hex visual range of an enemy.

**Comment by arlith** [comment]
This was fixed in PR #642
