### ISSUE TITLE
RFE: add Sherpa Armored Truck "Mobile Canteen" variant

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#5978]
Now that Fatigue rules have been added to MekHQ, units with Field Kitchens are important. Canon units with Field Kitchens are very rare, but the Sherpa Armored Truck is explicitly noted to have [such a variant](http://www.masterunitlist.info/Unit/Details/5049/sherpa-armored-truck-mobile-canteen) on the MUL, and it is available very early in the timeline. This RFE requests that this unit be added to the default unit list to help avoid the need to create custom Field Kitchen units.

It will need a note (similar to the currently-existing MASH Sherpa variant) that it does not actually have official stats, as only the primary (cargo-only) variant is given stats in TRO: Vehicle Annex.

**Comment by IllianiCBT** [comment]
Given the volume of people asking after Field Kitchen units, this would be well received.
