### ISSUE TITLE
[0.50 - Release]: Map Editor - Sea Port Woods Fluff No Longer Loads the Sprite

### ISSUE THREAD

**Issue by UlyssesSockdrawer** [MegaMek/megamek#5980]
### Environment
Version: 0.50 release - MekHQ version
OS: Windows 11 10.0 (amd64)
Java Vendor: Eclipse Adoptium
Java Version: 17.0.12

### Description
The Sea Port fluff, in 0.50, is converted to an atlas.

When attempting to apply the fluff to a map in the editor, the blank error sprite is loaded instead.

![image](https://github.com/user-attachments/assets/52dcfcd7-ac0f-4ebe-8f85-cbf2e6a8f99d)

![image](https://github.com/user-attachments/assets/61598bc2-40ca-452f-8ec9-d4f21b7458f4)

Issue identified after conversation with @HammerGS in the map-making channel of the Discord.

To reproduce the issue, apply Fluff 80, Exits 1 + Light Woods + Woods Elevation 2 to a hex, and try to place it on a board in the map editor.

### Files
N/A

**Comment by SJuliez** [comment]
In the dev environment, it still works.

**Comment by UlyssesSockdrawer** [comment]
![image](https://github.com/user-attachments/assets/a0d01319-ab5b-4b9f-ad10-afc491e9a9f8)

I suspect that's because in the dev environment (this screenshot from my fork of MM) all of the sprites are included individually.

In the release version, the sprites are compressed into an atlas:

![image](https://github.com/user-attachments/assets/70295e09-41a8-43f9-8851-d72ad85a7603)

I think the compression into the atlas might be the culprit for these hexes not displaying.

**Comment by BiggestBoss1** [comment]
Found a map that suffers from the lack of sea port fluff
![image](https://github.com/user-attachments/assets/072afaf4-1701-470c-887c-8fe1b9d06f11)
