### ISSUE TITLE
[0.50.0] HVAC Field Guns can explode on a roll of 2 (and should not be able to)

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megamek#5995]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

Currently, field guns using HVAC autocannons will explode if they roll a 2:
![image](https://github.com/user-attachments/assets/acf1c9e2-d5ff-4337-8c45-64b2ed932358)

Based on previous discussions around field guns in discord, as well as the following forums post, they should NOT explode:
https://bg.battletech.com/forums/index.php?topic=67473.msg1642029#msg1642029

### Steps to Reproduce

1. Fire enough field guns until someone rolls a 2 (save file included during firing phase to assist with troubleshooting)
2. Observe detonation and subsequent death of the infantry platoon

### Operating System *

Windows 11

### Java Version *

Java Version: 17.0.6

### MegaMek Suite Version *

v0.50.0

### Attach Files

[HVAC Field Gun Misfire.zip](https://github.com/user-attachments/files/16998920/HVAC.Field.Gun.Misfire.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by DM0000** [comment]
Thought the thing with HVAC's is that they are big and blow up on 2?

**Comment by gsparks3** [comment]
See this errata for Tactical Operations: Advanced Units and Equipment (which apparently didn't make it into the actual printing?):
![image](https://github.com/user-attachments/assets/36bc0f9f-c349-4ff2-8857-913563e39fbe)

As such, field-gun HVACs should not explode.
