### ISSUE TITLE
LRM Indirect Fire issues in 43.3

### ISSUE THREAD

**Issue by Kelnoth** [MegaMek/megamek#600]
Switched to indirect fire mode on an Archer 2R. Couldn't fire the missiles, got error messages saying that I had line of sight and that line of sight was blocked, and MegaMek crashed shortly after.

**Comment by HammerGS** [comment]
We need the MegaMek log for this

**Comment by pheonixstorm** [comment]
A copy of the game save wouldn't hurt either for arlith.

**Comment by arlith** [comment]
Without further information we can't do anything with it.  LRM IDF works for others; we can't reproduce without more details.
