### ISSUE TITLE
[RFE] Additions and changes to Issue tags

### ISSUE THREAD

**Issue by repligator** [MegaMek/megamek#6020]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

I've posted this to the MM issue tracker even though it applies to MM and MHQ as MM is the master project.

### MM
**Outdated (Test Against Milestone)**
Change title to simply "Outdated", and clarify the description to reflect that it should be tested against milestone _or_ the latest nightly as applicable. Issues reported during 49.20 may be out of date, but testing them against the latest milestone (49.19.1, which is older than they are) isn't going to help.

**Wrong tracker - should be Megamek**
This is the MegaMek tracker. This should either be removed, or changed to "Wrong tracker - should be MML or MHQ".

**Stable Backport Candidate**
Given the move away from a the stable/development release style documented in https://megamek.org/2024/01/19/State-of-the-Universe!.html , it would make sense to change stable to milestone, or simply remove the tag all together if backports are no longer going to be common.

### MHQ
**Stable Backport Candidate and Outdated (Test Against Milestone)**
See above

**Stratcon**
Remove the word alpha from description.

**Vees/Dropships/Infantry/BA**
There a quite a few issues that apply only to units with multiple crew, and not to the 99% of ASF and meks that are single crew. MML has individual tags for each, but in the interest of keeping the number of tags reasonably low, I think adding a single tag for all of them would suffice.

### MegaMekLab Suite Version *

N/A

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by SJuliez** [comment]
Done.
