### ISSUE TITLE
Locked Torso Twist

### ISSUE THREAD

**Issue by demster42** [MegaMek/megamek#6027]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

Mechs will be locked into a torso twist for the firing round

### Steps to Reproduce

I don't know.  I have a save with the mech locked.

### Operating System *

Windows 11

### Java Version *

17.0.12

### MegaMek Suite Version *

v0.50.0

### Attach Files

[TorsoTwist.sav.gz](https://github.com/user-attachments/files/17084742/TorsoTwist.sav.gz)
[megamek.log](https://github.com/user-attachments/files/17084740/megamek.log)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by UlyssesSockdrawer** [comment]
Did your mek torso twist in the TAG phase to direct its TAG at a different target?

**Comment by demster42** [comment]
It did not twist during TAG.

**Comment by BTSS88** [comment]
I also ran into something similar. My Warhammer couldn't torso twist during fire phase while standing in rubble tiles. Once it moved to normal ground tiles, I could torso twist again.

**Comment by demster42** [comment]
I have been watching the torso twist more closely and it could be that I twisted during TAG and then I am locked.  I have not seen an issue where this wasn't true since you mentioned it.
