### ISSUE TITLE
New Data: Wars of the Republic Era RATs

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/megamek#603]
[(3099-3113) - Wars of the Republic Era.zip](https://github.com/MegaMek/megamek/files/1247248/3099-3113.-.Wars.of.the.Republic.Era.zip)

**Comment by HammerGS** [comment]
I'll have a look. For future reference you can create a PR for them.

**Comment by HammerGS** [comment]
Added - https://github.com/MegaMek/megamek/commit/6fe0e05b369bf850b61b310b7cc8f94cd3202864
