### ISSUE TITLE
Graphical artefacts/glitches in the Round Report window, even with increased memory allocation. 0.50 nightly.

### ISSUE THREAD

**Issue by CX1237** [MegaMek/megamek#6032]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

I've noticed vertical lines coming from the text in the Round Report window. I have increased the memory allocation as specified in the guide and I have tried using both d3d=true and d3d=false to no avail.

![Screenshot at 2024-09-21 18-33-11](https://github.com/user-attachments/assets/8a77cb89-c098-46ef-8a5e-7876d2176e96)

### Steps to Reproduce

1. open mekhq with `bop@battlestation:~/Games/MekHQ-0.50.0$ java -jar -Xmx8192m MekHQ.jar `
2. Load latest savefile
3. start the current mission.

### Operating System *

Linux

### Java Version *

17.0.12

### MegaMek Suite Version *

v0.50.0

### Attach Files

[megamek.log](https://github.com/user-attachments/files/17089815/megamek.log)
[megameklab.log](https://github.com/user-attachments/files/17089817/megameklab.log)
[mekhq.log](https://github.com/user-attachments/files/17089818/mekhq.log)
[Stallion Three30211012.cpnx.gz](https://github.com/user-attachments/files/17089824/Stallion.Three30211012.cpnx.gz)
[custom.tar.gz](https://github.com/user-attachments/files/17089827/custom.tar.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by Sleet01** [comment]
This is a font issue.  Try choosing a different font for the report window; I like the fixed-width ones.

**Comment by Sleet01** [comment]
Follow-up: if this is fixed by changing fonts, please comment with the font that was set originally.

**Comment by CX1237** [comment]
Thanks Sleet01.

Font was aakar and is now courier 10p. No artifacts.

**Comment by Sleet01** [comment]
> Thanks Sleet01.
> 
> Font was aakar and is now courier 10p. No artifacts.

I also had issues with Aakar.  I'll see if I can figure out a way to disable, or at least not default to, that font.

**Comment by HammerGS** [comment]
Just tested on my Windows machine (I don't normally use) and had the same issue when I switched to it.

**Comment by DM0000** [comment]
Was this fixed?  I don't even see Aakar onlist  ->
![image](https://github.com/user-attachments/assets/f371774a-8053-4830-b657-7c009614a3c1)

**Comment by HammerGS** [comment]
I think you can add the fonts manually in the fonts folder and from system fonts

**Comment by DM0000** [comment]
on fresh install does it still go to aakar though? looks like default is already set to Segoe.
in ReportDisplay-
 setDefault(MINI_REPORT_FONT_TYPE, "Segoe UI");

**Comment by DM0000** [comment]
Maybe if your font folder doesn't contain "Segoe UI" it defaults to Aakar due to first on list?
