### ISSUE TITLE
[Data] Ferret Light Scout VTOL 'Fermi' has incorrect stealth armor type

### ISSUE THREAD

**Issue by stonewall072** [MegaMek/megamek#6039]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

_Discussed on the Discord, but wanted to add here for tracking purposes_

The Ferret Light Scout VTOL 'Fermi' unit file appears to have been built using the wrong kind of stealth armor (mech instead of vehicular). So it shows up correctly on the unit display, but is non-functional in game. A simple tweak to the file corrects the issue.

### Steps to Reproduce

Load a game with the Ferret Light Scout VTOL 'Fermi'. Observe that the stealth armor does not appear under the unit's equipment in the unit panel and cannot be toggled on.

### Operating System *

Windows 11

### Java Version *

17.0.11

### MegaMek Suite Version *

v0.50.0

### Attach Files

[Corrected - Ferret Light Scout VTOL (Fermi).zip](https://github.com/user-attachments/files/17149728/Corrected.-.Ferret.Light.Scout.VTOL.Fermi.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by HammerGS** [comment]
Closing as I fixed it last week.
