### ISSUE TITLE
[0.43.3] Packrat LRPV PKR-T5 unable to carry 1 ton of troops

### ISSUE THREAD

**Issue by Da-Nuker** [MegaMek/megamek#604]
The Packrat LRPV PKR-T5 is currently unable to carry any troops in Megamek as it has 1 ton of cargo space instead of 1 ton of fixed troop space.

As per the RS:3039U and TRO:3039 description, it should have the troop space instead.

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/df36ca4c586a4143d1fe649d827b90aad7458a38
