### ISSUE TITLE
Coolant Truck (Hover) wrong MP in version 0.50?

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#6047]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

Unit appears to have changed MP between versions. Fairly certain this is incorrect (compare vs. the record sheet in RS:3039u), but does need a check to see if it was already fixed in the nightly builds. 

Version 0.49.20: 
![image](https://github.com/user-attachments/assets/0b6da077-ade1-4083-9ad7-923cd9008980)

Version 0.50:
![image](https://github.com/user-attachments/assets/ec08547e-bb95-4d08-b701-80b817d5fd96)

### Operating System *

Windows 10

### Java Version *

17

### MegaMek Suite Version *

v0.50.0

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by HammerGS** [comment]
I might have an answer related to the pending KS Record sheets. But must double check.

**Comment by gsparks3** [comment]
I will note that due to the minimum motive system weight for Hover units, 4 cruise MP is the same weight as 7 cruise MP, with 8 being very slightly heavier. IIRC you _are_ allowed to simply "waste" the weight and have less MP, but it would be unusual - I'm not sure any other canon unit does that.
