### ISSUE TITLE
Ammo Does Not Load Properly In Some Large Craft

### ISSUE THREAD

**Issue by BrandonSmith16** [MegaMek/megamek#6050]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [x] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

Ammunition is displayed as present in megamek lab and megamek hq as well as the "view unit" in megamek. However, when you try to swap ammo in megamek hq, you cannot swap or fill the bins of the affected weapons. In addition, the bins cannot be filled with ammo of any  type in megamek. Some ammunition types such as missiles can occasionally be loaded manually despite being imported with empty bins. The affected weapons will have no ammo in their bins when deployed.

This affects all large craft (jump ships, dropships, and warships) but not every ship in each class. This affects primarily ballistic weapons like HAG, gauss, uac5, lbx10 and even sometimes naval weapons like naval gauss. It can also affect missile weapons but does so rarely. _It almost always affects anti-missile systems._

### Steps to Reproduce

Load a unit into megamek or megamek hq and check the ammo bins. Affected units will have no ammo for some or all of their weapons.

### Operating System *

Windows 10

### Java Version *

Java Version 17.0.7

### MegaMek Suite Version *

v0.50.0

### Attach Files

[Ammo.sav.gz](https://github.com/user-attachments/files/17192454/Ammo.sav.gz)
[megamek.log](https://github.com/user-attachments/files/17192662/megamek.log)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by PhoenixHeart512** [comment]
I can confirm this is still present in the nightly build from 9/30/2024, and affects standalone megamek games too. Adding an "Overlord C" dropship into a megamek lobby and the attempting to configure it's ammunition shows all ammo bins at 0. Some of the bins can be increased (LRM's in the screenshot) but the Ultra AC/5's cannot.

![image](https://github.com/user-attachments/assets/b2b24638-bd79-43bc-b217-298473f77c7f)

**Comment by PhoenixHeart512** [comment]
Update, this may be only a visual bug, because the Overlord very definitely 100% just killed one of my units with its Ultra AC/20's that supposedly had no ammo. Needs further testing.

**Comment by PhoenixHeart512** [comment]
Based on what I've seen so far, it looks like if a dropship is added to the lobby by a mekHQ scenario, it will have ammo in game. If you view the unit in the lobby it will appear to have zero ammo, but as long as you don't configure the unit it will actually have its ammo once the game loads.

If you manually add a dropship to the megamek lobby, or if you right click -> configure the dropship in the lobby and save the changes (instead of hitting cancel, even if you don't change anything) it will delete the ammo and teh dropship will not have ammo once the game starts.
