### ISSUE TITLE
[RFE] Teach Princess to not always unjam RAC's immediately

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megamek#6052]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

Sometimes it's better to just fire all the un-jammed weapons than waste an entire turn unjamming a single RAC/5. It would be good if Princess could analyze the weapons she has available and determine if it would be better to unjam the weapon or just fire all the weapons that aren't jammed.

This is particularly noticeable when attacking grounded dropships. I recently had an Overlord-C spend its turn unjamming a UAC/5 (I use the unofficial unjam UAC's rule) instead of firing and killing another one of my units with the remaining full arsenal of weapons at that dropship's disposal.

### MegaMekLab Suite Version *

0.50.01-SNAPSHOT

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by RaozSpaz** [comment]
I would like to second this RFE. I use the Rapid Fire AC rules, and with the prevalence of ACs, even with the Kinder rules active you see lots of jammed autocannons, and she will 100% waste her turn trying to unjam rather than firing.

**Comment by DM0000** [comment]
unjamming ACs occurs in movementphase but should occur in endPhase.   If I move it to weapon fire phase could have it not auto unjam if its targeting enemy(looks like someone already added logic just not doing anything).         Currently it auto unjams if it has a  jammed AC and has not jumped or sprinted.
I can leave it in movement phase and do a check if jammed ac >= 50% firepower to unjam or maybe unjam if jammed is 100% of remaining firepower  || Random
