### ISSUE TITLE
Aerodyne DSs Dropping Units on Ground Map Have Issues

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/megamek#606]
MHQ 0.43.3

An Aerodyne DS can not drop units on the ground map if they move. The Units simply will not exit. The only way to get the units to drop is to not move the Aerodyne DS and let it stall for PSR.

See attached Save for quick reproduction. No errors in Log.

[DropShip.sav.gz](https://github.com/MegaMek/megamek/files/1252706/DropShip.sav.gz)

Fix? Aerodyne's drop units at the end of their turn? Or the beginning? Or in order of the commands clicked? Drop Troops then Move, vice versa.

**Comment by scJazz2** [comment]
Related to... https://github.com/MegaMek/megamek/issues/553

**Comment by neoancient** [comment]
It's possible to drop units at the end of movement. I have found nothing in the rules for unloading from aerospace units either airborne (SO, 22) or on the ground (TW, 91) that states that it has to be at the end of the unit's turn, but it is true that infantry carriers can only dismount infantry at the end of the carrier's turn (TW, 224). I see no particular reason it would have to be that way for airborne drops, but then I don't see a good reason why infantry carriers would have to wait until the end of movement.

**Comment by scJazz2** [comment]
ahhh my mistake was in the fact that I often "over move" ASF type units. So instead of clicking the correct 16th hex I might click the 17th, 18th etc. Which I suppose is why my Drop Troops command did not work at all.

**Comment by neoancient** [comment]
But we've now received confirmation from TPTB that it should be legal to drop anywhere along the flight path.
