### ISSUE TITLE
[0.50.01-SNAPSHOT] Aerospace fighter deployment errors in low-altitude maps. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/megamek#6061]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

When deploying Aerospace Fighters in Low Altitude maps, one of the options for altitude deployments it to deploy grounded. This is causing two strange effects to occur: 
- Aerospace fighters cannot deploy over tiles they cannot enter when grounded, even if their altitude is above 0. This is very noticeable when the deployment zone covers trees or foliage. 
- Princess-controlled ASF can deploy grounded. When this occurs, Princess will stall indefinitely during the movement phase. This is current occuring in the attached quicksave. 

This is likely related to the DropShip issues mentioned in #6060. 

### Operating System *

Windows 11

### Java Version *

21.0.3

### MegaMek Suite Version *

None

### Custom MegaMek Version

Nightly v0.50.1-SNAPSHOT - Rev. a53044ee0763666eba74cdeaf511e150d291b1f0

### Attach Files

[megamek.log](https://github.com/user-attachments/files/17252442/megamek.log)
[quicksave.sav.gz](https://github.com/user-attachments/files/17252443/quicksave.sav.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by SJuliez** [comment]
I am trying to reproduce this. On a low altitude map, I do not seem to get the option to deploy grounded, see screen. Also, I can deploy in hexes that the unit couldnt land in, although the marked hexes suggest otherwise (this is indeed a GUI issue, but it does not seem to be what you're describing). 
Also, in the last screen note that this is really a low altitude map and not a ground map.

![image](https://github.com/user-attachments/assets/70d3d45e-560a-45a2-abf7-bfbd13e73b86)
![image](https://github.com/user-attachments/assets/9ad8a777-5f7c-4e62-aced-1ab0971ee2b9)

**Comment by SJuliez** [comment]
forgot to add the last screen
![image](https://github.com/user-attachments/assets/5ae9e4da-5361-4aee-bec4-2bc5024aa10e)

**Comment by Tzahr** [comment]
I absolutely enountered a grounded WoB fighter that seemed to have deployed at altitude 0, but through fumbling with tracking down another bug, I've lost the quicksave of it occuring, and now cannot replicate it either even on the same MekHQ scenario that caused it to happen. 
I am fairly sure I had the oppertunity to deploy at `altitude: 0` for that one as well, but there's a degree of doubt there. 

I'm kicking myself for not more diligently documenting it. 
I'll append if I encounter it again.

**Comment by Tzahr** [comment]
Actually - no, I just realised I did attach a quicksave to the report. It includes the grounded WoB fighter with altitude 0 on a low-altitude map. 
I just can't replicate it again.

**Comment by SJuliez** [comment]
OK and the Gotha was player-deployed?

**Comment by Tzahr** [comment]
No, princess-deployed.

**Comment by Thom293** [comment]
I too have seen this and posted a screenshot and save in the QA channel 2 days ago.  It was my units but conteolled by princess.

**Comment by Tzahr** [comment]
Unfortunately, I had Princess deploy another altitutde 0 Cheetah during a Low-Athmosphere mission in a Nightly that includes the merge. 
Rev. 693da04da9749225b408d26b424b80f9e9dce570

![image](https://github.com/user-attachments/assets/fd34cc54-7625-4f7a-875d-7582d8cc488a)
[quicksave.sav.gz](https://github.com/user-attachments/files/17286289/quicksave.sav.gz)
[megamek.log](https://github.com/user-attachments/files/17286288/megamek.log)

**Comment by SJuliez** [comment]
I have another fix for that, #6080 
The problem is probably the negative hex levels. I am still not sure why Princess would deploy at alt 0 though as she should respect the altitude set in the lobby which is normally 5. Unless this was changed or other values came from MHQ. I'll leave this open for further reports, for now.
