### ISSUE TITLE
[0.50.01-SNAPSHOT] Grammar: A/An issue in damage report for dropship cargo bay doors

### ISSUE THREAD

**Issue by WeaverThree** [MegaMek/megamek#6079]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

The wrong article is used when cargo bay doors on a dropship are critted:

![AnCargoBayDoor](https://github.com/user-attachments/assets/4151ef86-8a28-4488-ae29-93bc8f312497)

### Steps to Reproduce

1. Create a match with a dropship on one side
2. Shoot dropship a lot

### Operating System *

Linux

### Java Version *

17.0.12

### MegaMek Suite Version *

Free Text (type manually)

### Custom MegaMek Version

v0.50.01-SNAPSHOT 2024-10-05

### Attach Files

megamek.MegaMek.initializeLogging(MegaMek.java:146) - Starting MegaMek v0.50.1-SNAPSHOT
    Build Date: 2024-10-06T03:25:24.214306127
    Today: 2024-10-08
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 17.0.12
    Platform: Linux 6.11.2-202.fsync.fc40.x86_64 (amd64)
    System Locale: en_US
    Total memory available to MegaMek: 8 GB
    MM Code Revision: 82fc89ceba5bfdb40670ba90bdc3e3ca1027a07b
    MML Code Revision: 446bd8d9c7e28bfdf49d35f312d838c44e16941a
    MHQ Code Revision: 976204bfa54b995b2d45159b080d13dba8a16ee5

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by psikomonkie** [comment]
I reworded this in the fix, I attached a screenshot to the PR with what it will look like in the future: https://github.com/MegaMek/megamek/pull/6285#issue-2748216022
