### ISSUE TITLE
[0.50] NPE when selecting CI-scale LRM on small SV in Weapons panel

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#6101]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

NPE popup appears while selecting a specific weapon as described in the title. Clicking past the popup has gameplay appear unaffected, except that the visual range-bands display will not display correctly for the bugged weapon. Relatively few people play with Small SV units, likely explaining why this bug was not reported previously.

### Steps to Reproduce

1. Load the provided save as "Kingstone Mercenaries".
2. Select the "Icaro" unit (4 ton small SV VTOL)
3. Go to the Weapon panel in the Unit Display. Switch back and forth between selecting one of its two weapons until a NPE popup appears (appeared on the first try for me).

### Operating System *

Windows 10

### Java Version *

17.0.11

### MegaMek Suite Version *

v0.50.0

### Attach Files

Save: [report.sav.gz](https://github.com/user-attachments/files/17367416/report.sav.gz)

Log with error: [megamek.log](https://github.com/user-attachments/files/17367420/megamek.log)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by SJuliez** [comment]
@gsparks3 could you pass me that Icaro unit file

**Comment by gsparks3** [comment]
[Icaro Support Helicopter.zip](https://github.com/user-attachments/files/17441363/Icaro.Support.Helicopter.zip)
