### ISSUE TITLE
bots use single blind rule has botched description text

### ISSUE THREAD

**Issue by renanksan** [MegaMek/megamek#6102]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

![image](https://github.com/user-attachments/assets/427434f1-d309-4168-92be-ac9d22ab7d8a)
when you hold the mouse over this rule 
![image](https://github.com/user-attachments/assets/f7c4b4e4-2906-43c1-a4f3-c763005c7e31)
it shows broken text

### Steps to Reproduce

enter into MM 
enter a match
go to game options 
advanced rules
all the way at the bottom of advanced rules

### Operating System *

Windows 10

### Java Version *

17

### MegaMek Suite Version *

v0.50.0

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by UlyssesSockdrawer** [comment]
With the new heatmapping for Princess, was the single-blind stuff removed? I'm not sure.
