### ISSUE TITLE
No PSR in high gravity for Princess

### ISSUE THREAD

**Issue by Desertdream2** [MegaMek/megamek#6108]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

Playing a MekHQ match in MegaMek with 1.1 gravity. I am being forced to do PSR's when jumping (both a PXH and FS9) but Princess with a VND jumped but faced no PSR.

First screen shot is what I faced when trying to jump:
![image](https://github.com/user-attachments/assets/b5836e49-596f-4783-bd4a-cbaaf4976148)
Second screen shot is the round report showing the PSRs I faced (but no jumping PSRs for Princess):
![image](https://github.com/user-attachments/assets/2ace3199-b36c-4f60-92e9-80ec5deadbe4)
Third screen shot is the same round report showing Princess did jump (clicked on Princess shooting at me to show the adjusted TN included "Attacker Jumped":
![image](https://github.com/user-attachments/assets/d5c8fe29-0a40-490d-8394-d5be23d8239f)

Rule from TO:AR page 53.
[megamek.log](https://github.com/user-attachments/files/17401687/megamek.log)
[gamelog.zip](https://github.com/user-attachments/files/17401724/gamelog.zip)

### Steps to Reproduce

Deploy Princess units with jump capability in High (1.1g) gravity.

### Operating System *

Windows 10

### Java Version *

17.0.12

### MegaMek Suite Version *

v0.50.0

### Attach Files

[megamek.log](https://github.com/user-attachments/files/17401738/megamek.log)
[gamelog.zip](https://github.com/user-attachments/files/17401739/gamelog.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by neoancient** [comment]
Could not reproduce.

![image](https://github.com/user-attachments/assets/3caae385-a98c-4082-9faa-fc04befc998a)

**Comment by Desertdream2** [comment]
Would there be some setting I had checked (or unchecked) where my Princess was not forced into PSRs but Neoancient's was?

**Comment by Desertdream2** [comment]
I do use Double Blind, would that meant that Princess was facing PSRs (and passing them) but I never saw them in the round report?

**Comment by Desertdream2** [comment]
So now fighting (still double blind) Princess in low gravity and I am seeing the PSRs for Princess when they jump past their normal MP in low gravity, so I just want to clarify, this issue I found was when I was in 1.1 gravity, just in case the exact amount of gravity affects whether princess takes a PSR.

**Comment by SuperStucco** [comment]
Small differences from standard 1.0g can end up with some awkward in-game effects, because whether or not a PSR is required is based on design walk MP rather than available or used jumping MP.

> Playing a MekHQ match in MegaMek with 1.1 gravity. I am being forced to do PSR's when jumping (both a PXH and FS9) but Princess with a VND jumped but faced no PSR.

In the original post, the Phoenix Hawk and Firestarter Mechs have a high enough standard walking MP that they are forced into gravity-related PSRs.  Meanwhile, a Vindicator that moves 4/6/4 may be slow enough not be required to check.  This can also show up with 'fast ground, short jump' Mechs like the Jenner - despite having the same jump capability as the Vindicator the high ground speed means it has to make PSRs when jumping.

The second example, with a different unit - another Phoenix Hawk - is a little more concerning.  Depending on game settings, opponents may be making the piloting checks with them not showing up at all in the round report.

**Comment by neoancient** [comment]
I tested in 1.1 gravity, but without double blind. MegaMek makes no distinction between whether the unit is controlled by a human or a bot when making these checks. The amount of damage taken for jumping in high gravity depends on the difference between the normal walking MP and the reduced walking MP. A Phoenix Hawk would have 6 walking reduced to 5 (6 / 1.1 = 5.45, rounded down to 5). A Vindicator would still have all 4 walking MP (4 / 1.1 = 3.636, rounded up to 4). As there is no MP reduction, it would take no damage and the PSR is not made.

**Comment by IllianiCBT** [comment]
Out of curiosity, is it possible you're simply not being shown the roll in double-blind? iirc, some rolls are hidden if you don't have LOS to the unit depending on your game settings.
