### ISSUE TITLE
[0.50.01-SNAPSHOT] Selecting alternate ammunition does not display the ammo that will be fired correctly

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megamek#6138]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

When selecting alternate ammunition such as LBX Cluster, the weapons dropdown does not update to show the selected ammo and remains showing the default loaded ammunition, as shown in the screenshot below:

![image](https://github.com/user-attachments/assets/3a8723de-0b0a-4f18-9660-961b2aca8090)

The correct ammunition is actually fired, and you can see the -1 Cluster ammo modifier is taking effect in the modifiers pane, this appears to be a purely visual bug.

### Steps to Reproduce

Using a mech that has alternate ammo available (LBX, LRM, SRM, etc) try to select an ammo type other than the type loaded at start

### Operating System *

Windows 10

### Java Version *

Java Version: 17.0.6

### MegaMek Suite Version *

Free Text (type manually)

### Custom MegaMek Version

megamek.MegaMek.initializeLogging(MegaMek.java:146) - Starting MegaMek v0.50.1-SNAPSHOT     Build Date: 2024-10-22T03:24:07.974368271     Today: 2024-10-23     Origin Project: MekHQ     Java Vendor: Eclipse Adoptium     Java Version: 17.0.6     Platform: Windows 10 10.0 (amd64)     System Locale: en_US     Total memory available to MegaMek: 8 GB     MM Code Revision: 630bba8695c2b1004e65501fe900f4e1b8c9e973     MML Code Revision: 384380362038ce744734c3a05836fd5d511d1df0     MHQ Code Revision: 035ff6c725a948b98d811bdaac45d7375ea67074

### Attach Files

[AmmoSelectionBug.zip](https://github.com/user-attachments/files/17495001/AmmoSelectionBug.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by RaozSpaz** [comment]
I can confirm this on the #1661 Nightly
