### ISSUE TITLE
Unloading Units from DS at Altitude X is Possible in Deploy

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/megamek#614]
0.43.3

The "Unload" command is available while all units are Loaded in a DS. Clicking "Unload" switches deployable unit to one of the units onboard DS. Then you can place that unit on the Ground Map and move normally. MM switches back to Deploying the DS on the Map after this is done.

The Unload command should not be available if all units are loaded in a DS.
Save attached... no errors in log
[SpheroidDS_UNLOAD.sav.gz](https://github.com/MegaMek/megamek/files/1265447/SpheroidDS_UNLOAD.sav.gz)

**Comment by arlith** [comment]
The deploy/unload buttons in the lounge aren't really designed to represent those units taking those actions during deployment, but more it's allowing you to adjust the current state of units.  Basically, it allows you to take those infantry you forgot to put into an APC in the lounge and load them up.  Or take those units you accidentally loaded and unload them.  This is more of a pre-game adjustment.  

Given that, I feel like the behavior you describe is perfectly acceptable.  If it's not suitable for your scenario... don't do it?

**Comment by scJazz2** [comment]
Request re-open... since now Deployment/Initiative is screwed up.

Last unit(s) to move in any Ground Phase are Dropships. So now there is a situation where a DropShip is forced to last move in Deploy. Then unloads a Ground Unit, and that unit can now move normally. This makes winning Initiative kind of sort of useless. If, as you say, this behavior is acceptable as a fix for screwing things up in the Lobby that is fine. But it does create a situation where "fixing your screwup" in Deployment violates Initiative Rules. Essentially, creating a "I Win Deployment" button during Deployment phase regardless of intent.

**Comment by BLOODWOLF333** [comment]
But the other player would call foul and stop the game if they wanted to "cheat" like that.  I think having it so you can fix a mistake with loading/unloading out-weighs keeping people from cheating.  Thats something that should be worked out between the players and not the programs responsibility.

**Comment by scJazz2** [comment]
Reasonable... I just wanted to make sure.

Keep it closed.
