### ISSUE TITLE
Issues with offboard artillery v.50.00

### ISSUE THREAD

**Issue by Lhomme-du-nord** [MegaMek/megamek#6140]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

When targeting hostile off-board artillery with my own (either onboard or offboard), if there is a change to the amount of enemy offboard units a nullpointer error pops up.

### Steps to Reproduce

In any all games with enemy off-board arty, I can counter battery a few turns, until a few rounds in the errors start happening

### Operating System *

Windows 11

### Java Version *

17.0.12

### MekHQ Suite Version *

v0.50.0

### Attach Files

[logs.zip](https://github.com/user-attachments/files/17514119/logs.zip)
[CampaignSave.zip](https://github.com/user-attachments/files/17514122/CampaignSave.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by repligator** [comment]
Can you clarify what you mean by "change to the amount of enemy offboard units?"

**Comment by Lhomme-du-nord** [comment]
If I destroy one or make it disengage.

Nate Tremblay
