### ISSUE TITLE
LAM in fighter mode uses wrong hit location table

### ISSUE THREAD

**Issue by FunAndEngaging** [MegaMek/megamek#6144]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

![image](https://github.com/user-attachments/assets/61d4f16c-dda9-4acc-8e4b-dfea5a479d34)

When attacking a LAM in air-to-air (well, space-to-space) combat, I observed the head getting hit by frontal attacks.
This shouldn't be possible according to the LAM Fighter Hit Location Table (IO p.112), which only allows head hits from the side.

A cursory glance at the code suggests that the rollHitLocation method is overloaded, and only one version of it is correctly overwritten in the LandAirMek class. The attack in question - possibly even all attacks - use the second version with additional parameters.

This also means that various secondary effects described on the LAM Fighter Hit Location Table would not be applied correctly.

### Steps to Reproduce

1. Create a scenario with LAMs in fighter mode
2. Attack said LAMs from the front. A large number of attack rolls is recommended to account for randomness
3. Observe hits to the Head despite the head location not being on the Nose hit location table 

### Operating System *

Linux

### Java Version *

17.0.11

### MegaMek Suite Version *

v0.50.0

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by DM0000** [comment]
Do airMek(wige) and fighter have the same hit locations?  Looks like its only checking if its in fighter mode to change hit locations.  Can correct it but want rules clarification.

**Comment by SJuliez** [comment]
should be fixed
