### ISSUE TITLE
Side Torso destruction forces LAM to crash-land in space

### ISSUE THREAD

**Issue by FunAndEngaging** [MegaMek/megamek#6145]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

![image](https://github.com/user-attachments/assets/e3e50f7e-1ae7-4838-8f25-67a5033b260a)

Now I've heard of a 'hard vacuum' before, but I don't think that's what it means. FWIW, IO p.108 agrees with me that the loss of a side torso only removes a LAM's ability to fly _in atmosphere_.

Searching the unique line from the round report leads me to the MovePathHandler class, which indeed does not check if a LAM is operating in space or not. Not sure what could trigger it in this phase though (processing falls?).

### Steps to Reproduce

1. Create a space map scenario featuring LAMs in fighter mode
2. Destroy the side torso of a LAM
3. Observe spurious aerodynamic effects followed by a sudden stop

### Operating System *

Linux

### Java Version *

17.0.11

### MegaMek Suite Version *

v0.50.0

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by DM0000** [comment]
Can anything crash in space?     If no then I can submit quick fix adding   movePath.isOnAtmosphericGroundMap()  to willCrash

**Comment by SJuliez** [comment]
@DM please do, I don't think anything can crash in that way on a pure space map and we have nothing else atm
