### ISSUE TITLE
Randomly zooming in the map when using touchpad (on MacbookPro)

### ISSUE THREAD

**Issue by Scoppio** [MegaMek/megamek#6151]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

Specifically using touchpad of a macbook pro, when moving the cursor around its very frequent that suddent spikes of "mouse scroll" will be received, this causes a sudden zoom-in to a single hex.

### Steps to Reproduce

1. Use a macbook pro.
2. Open megamek and start a game.
3. Try to move the cursour using the touchpad un both map or minimap.
4. sometimes an unnintended scroll happens.
5. the scroll is unbounded and will go to the maximum.

### Operating System *

Mac

### Java Version *

OpenJDK Runtime Environment GraalVM CE 23+37.1 (build 23+37-jvmci-b01) OpenJDK 64-Bit Server VM GraalVM CE 23+37.1 (build 23+37-jvmci-b01, mixed mode, sharing)

### MegaMek Suite Version *

v0.50.0

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by phillipjohnston** [comment]
What was the workaround or resolution for this? Suffering this terribly

**Comment by Scoppio** [comment]
> What was the workaround or resolution for this? Suffering this terribly
Client settings, disable scroll zoom on board.
