### ISSUE TITLE
Show physical attack modifiers

### ISSUE THREAD

**Issue by RaozSpaz** [MegaMek/megamek#6169]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical 

### Brief Description *

The standard -2 to hit on a kick is currently not applying on physical attacks in the #1661 nightly.

![image](https://github.com/user-attachments/assets/2462e7dc-d462-445c-b2cb-cbcfa7f3d640)

### Steps to Reproduce

1. Load up a megamek game
2. Approach a target
3. Choose to kick them

### Operating System *

Windows 10

### Java Version *

Version 17 Adoptium

### MegaMek Suite Version *

Free Text (type manually)

### Custom MegaMek Version

#1661 Nightly

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by cooshoo** [comment]
![image](https://github.com/user-attachments/assets/0338b93e-afdc-4c71-a5c4-b2f0b4296cb8)

My experience is slightly different, but also weird. 
It seems none of the melee attacks show modifiers in the calculation of to-hit. They are included in the "base" number, see screenshot: kick being 2, melee weapon 3, and kick 4. But they are not explicitly described as -2, -1, or +0, respectively

**Comment by SJuliez** [comment]
The physical modifiers are not displayed but included in the base. This has not been any different for a long time, see this from 0.48 (pilot has piloting 5):
![image](https://github.com/user-attachments/assets/9acc6592-514d-4812-a73e-086d8d89ec7f)
I'll assume that the pilot from the initial screenshot has piloting 6. I can see however that we might want to show the modifier, so converting this to RFE.

**Comment by RaozSpaz** [comment]
Ah. I didnt notice that the base was lower. Thank you Juliez. I 100% accept the change to an RFE XD
