### ISSUE TITLE
Right-click > Convert to vehicle doesn't work with quadvee 0.43.3

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#617]
At the beginning of a game, I right-clicked on my quadvee, which was deployed in quad mode.  I went to convert, then clicked on "Vehicle", and MegaMek tries to convert the unit to a quad, even thought it already is in quad mode.  It even expends 4 MP.

The workaround is to just click on the "Convert" button in the main button group at the bottom of the screen.  That works the conversion properly.

**Comment by BLOODWOLF333** [comment]
I just tested this with the standalone Megamek 0.43.3 and right clicking > convert > vehicle.  Works correctly with a Arion (uses 2 MP).  And next turn can convert to a mech using 2MP successfully. 
Do you have a saved game that can be tested, maybe its a specific unit?

***Edit there is an issue with the image for Arion
`Missing i18n entry: MovementDisplay.moveModeAir
Entry is null make sure that there is a default entry for Arion (Standard) in both mechset.txt and wreckset.txt.  Default to default_light
Round 2 memory usage: 117,556 kB
c:s:Contents of Send Queue: Contents of Send Queue: `

Player name: BLOODWOLF
[Issue617.zip](https://github.com/MegaMek/megamek/files/1278620/Issue617.zip)

**Comment by BLR-IIC** [comment]
I think I was playing with a Boreas.  Would the actual unit really make a difference?

**Comment by neoancient** [comment]
I ended up rewriting the way the menu works with conversions when I did LAMs because of a few things I hadn't anticipated, but it works correctly in the current code. We're hoping to have a new snapshot out soon.

**Comment by neoancient** [comment]
Closing as fixed.
51af43cb
