### ISSUE TITLE
Spheroid DS Able to Move in any direction on Ground Map

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/megamek#618]
0.43.3

Spheroid DS able to move in any direction or combination almost as if it is moving as a ground unit on the Ground Map.

Screen Shot
![spheroid ds movement](https://user-images.githubusercontent.com/16738384/29978276-76c0ecc8-8f0e-11e7-8c15-905f39da1c55.jpg)

Save Game
[SpheroidDS.sav.gz](https://github.com/MegaMek/megamek/files/1270836/SpheroidDS.sav.gz)

No Errors in logs.

Total Warfare Errata 4.4 Pg 8 (Changing page 84 Total Warfare) implies that a Spheroid DS can only move up or down or in a straight line 16 hexes on the Ground Map.

**Comment by neoancient** [comment]
The rules for ground maps are on page 91-2 of TW, and state that spheroid units "may move into any ground hex within eight hexes of their current position at a cost of 1 MP. (4th printing, which incorporates v4.4 of the errata). This has not been changed in later errata.

One thing that needs to change is that unless I misread the rules they are limited to spending a single thrust point for lateral movement in the atmosphere, which allows one hex on the low altitude map and eight hexes on the ground map. One low altitude hex normally equals sixteen ground, but here the rules explicitly limit the movement to eight on the ground map.

**Comment by Dylan-M** [comment]
I read them the same way, and my explanation for the half distance is that it also has to use thrust for lift.

**Comment by AaronGullickson** [comment]
Trying to tackle some of these aerospace bugs. @neoancient That is not how I read the rules. I don't see anywhere where it says they are limited to spending a single thrust point for lateral movement. It simply states that they can move 8 hexes for 1MP.  I see how there is some ambiguity there, but it might need a rules clarification.

**Comment by NickAragua** [comment]
This has been corrected some versions ago, and now spheroid dropships are limited to moving 8 hexes on the ground map (and one hex on the low altitude map), subject to restrictions similar to mech jump jet usage.
