### ISSUE TITLE
Wrong calculations of bonus damage for beast infantry

### ISSUE THREAD

**Issue by Dark-Hobbit** [MegaMek/megamek#6192]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

Beast infantry has bonus damage to attacks against targets in the same hex: +1 damage against vehicles/Mechs and +1d6 damage against conventional infantry. However, right now this damage is applied not once per attack but once per every soldier in the beast infantry that hit the target - resulting in very high amounts of damage.
![Wrong beast infantry damage - against infantry](https://github.com/user-attachments/assets/e361eb8a-5bee-434a-a721-e65d81729fcb)
![Wrong beast infantry damage - against Mech](https://github.com/user-attachments/assets/d2d8cbd7-916f-4ef4-8693-dbddc66d43f3)

### Steps to Reproduce

1. Take a unit of beast infantry (tested with Kangaroo, rifle/laser rifle).
2. Move into the same unit hex as opponent.
3. Successfully attack the unit you are sharing the hex with.
4. See the bonus damage multiplied for every soldier in the unit that hit the target.

### Operating System *

Windows 11

### Java Version *

Eclipse Adoptium 11.0.22

### MegaMek Suite Version *

v0.49.19.1

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by Setsul** [comment]
Going by some quick and dirty tests this still happens in v0.50.0-Development and the current v0.50.1-SNAPSHOT.

For completeness:
TO:AU page 108 mentions the anti-vehicle bonus being per platoon.
It's not explicitly mentioned for the anti-infantry bonus, but as far as I know, all of the xD6 "burst-fire" bonuses from weapons are also once per platoon, regardless of the number of weapons used.
However, I don't use beast-mounted infantry, so it would be good if someone could confirm this is actually a bug and not working as intended.
