### ISSUE TITLE
[Data] Several XCT Infantry Platoons Missing Specialization

### ISSUE THREAD

**Issue by stonewall072** [MegaMek/megamek#6207]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

The Mechanized Assault XCT Word of Blake Militia NBC, Motorized XCT Infantry Explorer Corps Hostile Environment, and XCT Marine Special Asteroid Support Forces are missing their Xenoplanetary Condition-Trained Troops specializations. It's noted on their record sheets in RS 3085 Unabridged: Cutting Edge

### Operating System *

Windows 11

### Java Version *

17.0.11

### MegaMek Suite Version *

Free Text (type manually)

### Custom MegaMek Version

0.50.01

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by HammerGS** [comment]
Fixed with https://github.com/MegaMek/megamek/commit/fa352b945c6440690414ebd9a3ceb097e782b76b
