### ISSUE TITLE
Data issue - SpecOps Paratrooper MI6 Extraction Team

### ISSUE THREAD

**Issue by pavelbraginskiy** [MegaMek/megamek#6213]
The SpecOps Paratrooper platoon should have 1 Sonic Stunner per squad (TRO3085, p197), but has 2 per squad in MM.
Additionally, their design year is 2500, but their Federated-Barrett M42B doesn't exist until the 3000s.

### MegaMek Suite Version *

Nightly 0.50.02

**Comment by HammerGS** [comment]
Fixed with https://github.com/MegaMek/megamek/commit/fa352b945c6440690414ebd9a3ceb097e782b76b
