### ISSUE TITLE
[RFE] Add Locust and Jackrabbit quirks from BMM Errata v7.01

### ISSUE THREAD

**Issue by Setsul** [MegaMek/megamek#6214]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is a request to implement Errata

### Brief Description *

Per [BattleMech Manual Errata v7.01](https://bg.battletech.com/wp-content/uploads/2023/09/BattleMech-Manual-2023-09-17-v7.01.pdf), page 13, the following Quirks should be added:
**Jackrabbit**: Easy To Maintain; Bad Reputation
**Locust**: Ubiquitous

For completeness: The erratum regarding the Stabilized Weapon Quirk on the Peregrine (Horned Owl) from the same version has already been implemented.

### MegaMekLab Suite Version *

v0.50.02 Nightly

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by HammerGS** [comment]
Fixed with https://github.com/MegaMek/megamek/commit/fa352b945c6440690414ebd9a3ceb097e782b76b
