### ISSUE TITLE
Camo doesn't change for GM Traitor'ed units in round report at end of game

### ISSUE THREAD

**Issue by repligator** [MegaMek/megamek#6215]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

Camo doesn't change for GM Traitor'ed units in round report at end of game.
![Screenshot_20241123_171453](https://github.com/user-attachments/assets/420035ea-c7f4-434b-88f3-44595a896585)

### Steps to Reproduce

1. Traitor the last unit a team has.
2. Observe round report.

### Operating System *

Linux

### Java Version *

17

### MegaMek Suite Version *

Free Text (type manually)

### Custom MegaMek Version

https://github.com/MegaMek/megamek/commit/f6174fc4a3ca85b9a84751b6f056c3c51528e286

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Should traitors be re-camo’d or should they use their origin color?

**Comment by HammerGS** [comment]
In my mind if a unit traitors in game, it wouldn't get a repaint and should stay the same but that is a fluff reason vs a mechanics issue.

**Comment by repligator** [comment]
Huh. I didn't really think of it like that. My brain is too used to RTS games where colors switch instantly to show control (Warcraft, Starcraft, AoE, etc.), but you're right, nobody is going to repaint a warship in the middle of a battle.
