### ISSUE TITLE
Unable to exit Add Unit window

### ISSUE THREAD

**Issue by Shenaldrac** [MegaMek/megamek#623]
While connecting to a friend's server, running 43.0 on both server and client,  I tried to add units to my force. However, they would not appear visually on my end, while my friend claimed he could see them. The more troubling issue was that attempting to close the Combat Unit window did not work, via using "Select and Close", Close, and the upper right corner "X" button. None of those would close it, and I had to manually terminate the program from the task manager. Attached is the session log.

[megameklog.txt](https://github.com/MegaMek/megamek/files/1273329/megameklog.txt)

**Comment by HammerGS** [comment]
Please see here and update your version of Megamek
https://github.com/MegaMek/megamek/releases/tag/v0.43.0

**Comment by Shenaldrac** [comment]
Thank you.

**Comment by arlith** [comment]
As Hammer indicated, the 43.0 release was bad.  I'm closing this.
