### ISSUE TITLE
[V50.01] ASF that has flown off the board still shows as on board. May still be targetable

### ISSUE THREAD

**Issue by RaozSpaz** [MegaMek/megamek#6243]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

![image](https://github.com/user-attachments/assets/e8c547db-0b9e-43d2-8742-ddfdb3c05db8)
![image](https://github.com/user-attachments/assets/63424fe6-16c7-4e58-b011-dd30d590a4b6)
![image](https://github.com/user-attachments/assets/9d392663-ec1b-47cc-b0dc-d78714735d75)

The first image is from one of my own games. The second are from SQW's post in our MML discord section. ASF remain on the board after flying off the board [regardless of whether it was due to an illegal move or voluntarily]. The second and third image SQW said that his ASF was still able to be targeted even though it was 'off board' at that point. I know for 95% certainty it was not doing this in the last nightly I was using [#1661]. 

### Steps to Reproduce

Just launch an MM game and give yourself an ASF. Fly off the board and it should persist.

### Operating System *

Windows 10

### Java Version *

V17 Adoptium

### MegaMek Suite Version *

Free Text (type manually)

### Custom MegaMek Version

V50.01

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by psikomonkie** [comment]
I believe this is working as intended. It is now possible to shoot at an aircraft as it leaves the battlefield. On subsequent turns, the aircraft will still show, to represent what side of the map it'll return on, but cannot be targeted on these turns.
