### ISSUE TITLE
Offboard artillery cannot unjam critted weapons

### ISSUE THREAD

**Issue by Tempest-56** [MegaMek/megamek#6252]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

If off-board artillery is critted by counterbattery fire and suffers a weapon jam as a result, there is no option to unjam it as that happens in the movement phase and off-board units don't activate in that phase.

### Operating System *

Windows 11

### Java Version *

17

### MegaMek Suite Version *

Free Text (type manually)

### Custom MegaMek Version

v0.50.01

### Attach Files

[Jammed.sav.gz](https://github.com/user-attachments/files/18056876/Jammed.sav.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by Tempest-56** [comment]
On a similar note, they could also probably use an Eject option. While Disengage is usually fine, if the offboard unit takes move crits it will be unable to use the Disengage option. Having the option for the crew/pilot to abandon rather than die with the unit is probably sensible.

**Comment by psikomonkie** [comment]
I took a brief look at this tonight. There looks to be two different unjammings - RAC/UAC/AC with special rules unjamming which happens in the movement phase, and the weapon jam, which happens in the firing phase. I think it's the firing phase unjamming we would need to also make available in the Offboard phase.
