### ISSUE TITLE
12/6 logistics artifact - Unable to intentionally flee ASF units on ground map

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/megamek#6261]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

![image](https://github.com/user-attachments/assets/78a68eb6-4ee8-4158-b07a-84f3f85ab473)
![image](https://github.com/user-attachments/assets/52a1b9ce-0dc5-43c1-b66d-6b04a72ada26)
![image](https://github.com/user-attachments/assets/15160579-0353-4e24-bafc-52a731b56f0d)
When attempting to flee it seems that it checks the velocity and if it finds any left it will not process, which would prevent fleeing in all occasions as a player as you need at least 1 excess velocity in order to move offboard.

### Steps to Reproduce

1. bring aerospace to a megamek battle
2. attempt to flee

### Operating System *

Windows 10

### Java Version *

17

### MegaMek Suite Version *

None

### Custom MegaMek Version

12/6 logistics artifact

### Attach Files

[logs.zip](https://github.com/user-attachments/files/18120833/logs.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by Sleet01** [comment]
I've seen this as well; I believe it's new in v0.50.02-SNAPSHOT - which, for the record, is the version that generated the attached logs.
