### ISSUE TITLE
RFE - Tool to prevent Missing Sprite in mech selector causes hard crash

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#627]
From this bug - https://github.com/MegaMek/megamek/issues/623

Is there a way we can get Megamek to switch to the default image on the fly rather than crash when an sprite is missing the mech selector?

As part of this expand the mechset report to test and catch those crashes?

**Comment by arlith** [comment]
I'm going to consider this fixed by virtue of the `MechSelectorDialog` no longer crashing.
