### ISSUE TITLE
12/13 Logistics artifact - 0.50.02 - Offboard artillery at 17 maps landing on round it is fired

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/megamek#6271]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

![image](https://github.com/user-attachments/assets/3090ae8b-12af-4e24-8843-83ff4dfaa55f)
Arty fires, my mechs complete their first movement phase, arty lands. Started at the 3rd hex from the edge and ran in 3/5 assaults for reference.

![image](https://github.com/user-attachments/assets/2a634645-549a-4178-9a02-e50505e8bb53)
Round report shows Round 1 artillery landing

Attached MM save has artillery available to shoot at you for testing if needed.
[logs.zip](https://github.com/user-attachments/files/18138559/logs.zip)

### Steps to Reproduce

1. Have enemy artillery deployed offboard
2. Begin round, move, receive 1st round impacts

### Operating System *

Windows 10

### Java Version *

17

### MegaMek Suite Version *

None

### Custom MegaMek Version

12/13 Logistics Overhaul '0.50.02-SNAPSHOT'

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by psikomonkie** [comment]
Unable to replicate in MegaMek under normal settings; I'm going to check out your campaign file and see if there's any planetary effects or rules that could impact this.

**Comment by psikomonkie** [comment]
Ah, I see what's up, the closest hexes to the edge with artillery is only offboard-distance away, which means artillery can get same-turn landing on those hexes. I'm looking into this.
