### ISSUE TITLE
Gained BV On Round Two (LAMS, Tripods, & QuadVees)

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#628]
Beta testing today's fixes and features.  Round 1 I'm at 100% BV from initial.  Round two (after converting the LAM to airmech and the QuadVee to tracked) I gained 7% BV.
![github](https://user-images.githubusercontent.com/16950832/30044540-420a825c-91c3-11e7-820b-fb3df459176b.png)

![github0](https://user-images.githubusercontent.com/16950832/30044543-44885608-91c3-11e7-8fae-2f7c2bd3f454.png)

Maybe #626 somehow uncovered this?

Player Name: BLOODWOLF
[BV Calculation.zip](https://github.com/MegaMek/megamek/files/1276014/BV.Calculation.zip)

**Comment by neoancient** [comment]
The BV calculation uses getWalkMP(false, true, true) to determine base movement, but this is variable for LAMs and wheeled QuadVees depending on mode. Replaced with getOriginalWalkMP(), which returns the base movement without situational modifiers.

**Comment by neoancient** [comment]
Meh, that fix is not going to work because it ignores MP reducing damage. Coffee hasn't kicked in yet.
