### ISSUE TITLE
Field Guns/Artillery all arrive on the battlefield with broken guns

### ISSUE THREAD

**Issue by repligator** [MegaMek/megamek#6290]
### Environment
Java 17
Linux
Master (Latest PR https://github.com/MegaMek/mekhq/commit/d9a07a3c8f79c902c2c188a1590b53ee786de3bd)

### Description
This campaign is using the default start date of 3151, so all the weapons should be available. It is also using the default settings under the second preset. All of the units were purchased from the "Purchase Unit" menu. None of them were refit, or had ammo type adjusted. They were staffed by right clicking and selecting Hire Minimum Compliment.

In MHQ, they all appear fine. In the MM lobby, they all appear fine. However, once battle starts, all of their Field Guns/Artillery will appear broken, and can not be fired.

If I launch a second instance of MM (completely separate from the MHQ one) then copy and paste the units from the MM-launched-from-MHQ lobby, they work fine. Somehow this issue is specific to MM when it is launched from MHQ.

### Files
[megamek.log](https://github.com/user-attachments/files/16740639/megamek.log)
[mekhq.log](https://github.com/user-attachments/files/16740641/mekhq.log)
[Freddie's Field Guns31510307.cpnx.gz](https://github.com/user-attachments/files/16740642/Freddie.s.Field.Guns31510307.cpnx.gz)

**Comment by IllianiCBT** [comment]
You’re knocking them out! And done <3
