### ISSUE TITLE
[RFE] Teach Princess that Leaping (TacOps:AR) is dangerous!

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#6295]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

The 'Leaping' rules in TacOps:AR (p.20) can be useful, but if the optional rule is switched on in MM, it appears that Princess does not recognise the dangers of doing so. 'Leaping' triggers two PSRs, but Princess' eagerness for doing so suggests that those PSRs and the risk of damage are not being figured into the pathfinder logic (probably because it's an optional rule).
The suggestion is that, if the 'Leaping' movement option is enabled, Princess' pathfinder takes account of the PSRs that it would trigger.

### MegaMekLab Suite Version *

v.0.50.1

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by Sleet01** [comment]
Closed by #6311
