### ISSUE TITLE
[0.50.02-SNAPSHOT] Board text overlays appearing beneath units when isometric view is enabled

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megamek#6297]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

A picture is worth a thousand words:
![image](https://github.com/user-attachments/assets/8cdd9bab-3e58-4641-97fb-faa893b8c8ac)

This only occurs when Isometric view is enabled (T hotkey). If I turn off isometric view, the text appears on top as expected:
![image](https://github.com/user-attachments/assets/0f1d3c05-5379-4a4c-834d-64956eca0cf4)

### Steps to Reproduce

Enable Isometric view and move a unit into/past a hex with another unit

### Operating System *

Windows 10

### Java Version *

Java Version: 17.0.6

### MegaMek Suite Version *

Free Text (type manually)

### Custom MegaMek Version

megamek.MegaMek.initializeLogging(MegaMek.java:146) - Starting MegaMek v0.50.02-SNAPSHOT     Build Date: 2024-12-20T03:22:42.532160220     Today: 2024-12-20     Origin Project: MekHQ     Java Vendor: Eclipse Adoptium     Java Version: 17.0.6     Platform: Windows 10 10.0 (amd64)     System Locale: en_US     Total memory available to MegaMek: 8 GB     MM Code Revision: 8ad58dcbbf41e73ffd3e20b6a9bb3d159d6616dd     MML Code Revision: 543ecc92823ad4c939d7f5316c0075cd50616d25     MHQ Code Revision: f1a5c049c57b3a692995ae0039836f34b46fe8bd

### Attach Files

[overlaysBug.sav.gz](https://github.com/user-attachments/files/18213391/overlaysBug.sav.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by PhoenixHeart512** [comment]
Actually I may have it backwards, the map is flat so it's hard to tell if iso mode is enabled or disabled, but I think it's actually a problem when NOT using isometric view, and is fixed by using isometric view

**Comment by Sleet01** [comment]
I think this is also related to / causing the issue where bomb graphics are hidden by other things in the hex they hit.

**Comment by HoneySkull** [comment]
Checked 0.50.0, This behaves this way in 0.50.0 as well where the movement text is under the unit in non-isometric, and shows on top in isometric.

**Comment by HoneySkull** [comment]
This also occurs with flight path indicators on non-isometric. 

![image](https://github.com/user-attachments/assets/c1b7d5d2-0015-434b-96e5-510496751aaa)
