### ISSUE TITLE
RFE: Show quirks in the Unit view when in the mech selector

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#631]
In the mech selector when you are looking at a mech would be nice to see the Quirks listed.  See pic with bad yellow coloring 

![image](https://user-images.githubusercontent.com/13752452/30092115-5e05b406-927a-11e7-89e3-ae147235919c.png)

**Comment by pheonixstorm** [comment]
The unit view in the MekHQ hangar does show the quirks so getting this added to MM might be rather easy. In theory.

**Comment by HammerGS** [comment]
You up for having a look and doing a PR. I'm working on the Quirks from BMM, and it would help me a lot.

**Comment by pheonixstorm** [comment]
I can take a peek. Will message my findings in slack.
