### ISSUE TITLE
ArrayIndexOutofBoundsException Indirect Fire

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#636]
[ArrayIndexException.zip](https://github.com/MegaMek/megamek/files/1289476/ArrayIndexException.zip)
Tested out eight turrets, gave princess four clan mechs.  Spotted two clan mechs for indirect fire, set my LRM turret to mode: indirect then click on spotted clan unit and nothing.  Nothing updates in the weapon tab in the unit display for targeting the unit and the game became sluggish and suspected my log was filling up and found an NPE or something.
`Report.addNewline failed, array index out of bounds
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 1
    at megamek.common.Crew.isActive(Crew.java:623)`

Player name:  BLOODWOLF

**Comment by BLOODWOLF333** [comment]
Forgot, this is a Beta version pulled from master on Sep 5th.

**Comment by HammerGS** [comment]
I think this might be related to the second bug uncovered in this guy
https://github.com/MegaMek/megamek/issues/582

**Comment by BLOODWOLF333** [comment]
Fixed in 1658f6f
