### ISSUE TITLE
Infantry in swamp/mud terrain should not have a psr check (Bog Down)

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/megamek#637]
> Infantry: For infantry entering such a hex, roll 2D6. On a result of 4 or less, the unit gets stuck. To escape getting stuck, an infantry unit need only make a 2D6 roll of 4+.

At present infantry are rolling a psr based on anti-mech skill.

**Comment by neoancient** [comment]
I also removed the check for infantry jumping into the terrain, per the line just above the one quoted (TacOps p. 63).

**Comment by BLOODWOLF333** [comment]
![github](https://user-images.githubusercontent.com/16950832/34809508-05ade586-f65b-11e7-8663-a9d0b6bd9961.png)

Is the -1 supposed to be applying or literally should just be a 4+
