### ISSUE TITLE
Incorrect MP cost for moving BA into building hexes

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#638]
BA set to "go through" often seem to take 3 MP to move into an adjacent building hex when it should cost 1 MP (and used to cost 1 MP). The second building hex costs the correct 1 MP to move into however.

![megamek](https://user-images.githubusercontent.com/1191378/30245277-2bf01394-9617-11e7-8a52-a719851faee3.jpg)

For BA with only 1 ground MP, it still shows 3 MP to move into the hex. Sometimes, it will show the correct 1 MP cost however.

![megamek2](https://user-images.githubusercontent.com/1191378/30245296-bb20c9c8-9617-11e7-95eb-6a4428ed1b14.jpg)

Can be replicated with standard BA on any map with building hexes. This is for 43.3.

[test.zip](https://github.com/MegaMek/megamek/files/1290172/test.zip)

**Comment by BLOODWOLF333** [comment]
climb mode

**Comment by Question2** [comment]
Please clarify. I had the BA set to "go through".

**Comment by neoancient** [comment]
What version are you using? I just tested with the current code in the repository and I'm getting a cost of 1 for go through and 3 for climb up.

**Comment by Question2** [comment]
43.3.

**Comment by arlith** [comment]
Have you changed the climb mode manually, or are you assuming the climb mode?  The default climb mode has changed from previous versions (and will likely suffer some changes again in the future).

**Comment by Question2** [comment]
@arlith : im not sure what you mean. All i did was click climb to set the BA to "go through". I made no other changes.

**Comment by arlith** [comment]
Yes, that's what I mean.  When you click the climb mode button, it cycles through modes, but each unit already starts at one mode.  I wanted to know if you were assuming the unit was in "go through" mode, or if you had clicked the button to set it there.  It seems that you've answered the question.

**Comment by Question2** [comment]
I think this is fixed in 43.4.
