### ISSUE TITLE
"Skip ineligible during firing phase" doesn't appear to take into account weapons fired during the targeting phase

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#639]
If you have an artillery unit with only artillery weapons (e.g. 1 long tom) and fire all of them during the targeting phase for an indirect attack, during the firing phase megamek won't skip the unit even though it has no eligible weapons left to use in the firing phase.

[test.zip](https://github.com/MegaMek/megamek/files/1290402/test.zip)

**Comment by arlith** [comment]
It can still spot.

**Comment by arlith** [comment]
I left my previous comment pretty quickly.  I checked the code, and it's pretty explicit that spotting is the cause of this.  Because of that, there's very few units that can properly be skipped.  Basically, it includes units that are shut down, unconscious, or otherwise ineligible for a turn.
