### ISSUE TITLE
Stepping on Bridges doesn't work

### ISSUE THREAD

**Issue by SJuliez** [MegaMek/megamek#64]
Maybe I'm doing it wrong, but I can't seem to step onto a bridge with a mech, even when tonnage < CF.
e.g. archipelago1, mech Commando, in MM version 0.3.23 as well as in the current 0.41.16.

**Comment by beerockxs** [comment]
You need to set climb mode to "climb up".

**Comment by SJuliez** [comment]
Oh. Danke.
