### ISSUE TITLE
Land-Air Mechs incapable of making maneuvers while in Fighter mode.

### ISSUE THREAD

**Issue by TigerShark** [MegaMek/megamek#641]
LAMs do not have the option to use Maneuvers in Fighter mode.

**Comment by neoancient** [comment]
What maneuvers are you trying to do? I tried a couple of them and didn't have any problems (other than failing the control roll on one of them).

![screenshot from 2017-09-10 19-51-03](https://user-images.githubusercontent.com/16927464/30254667-9b61282c-9661-11e7-84e6-9c1687a756e3.png)

![screenshot from 2017-09-10 19-51-21](https://user-images.githubusercontent.com/16927464/30254669-9fd999f2-9661-11e7-9c89-234fa7202fbb.png)

**Comment by neoancient** [comment]
Effect of side slip

![screenshot from 2017-09-10 19-54-28](https://user-images.githubusercontent.com/16927464/30254693-e2494dc8-9661-11e7-94fd-c7438ad4424b.png)
