### ISSUE TITLE
Window Draw Error. Possible Offset Issue

### ISSUE THREAD

**Issue by elementx54** [MegaMek/megamek#647]
### Steps to reproduce problem
I was trying this out in the latest pull from GitHub. Log is found below.
1. Start a new game.
1. Add the bot.
1. Add a unit.  
![before](https://user-images.githubusercontent.com/13558671/30304599-832e6d4e-972b-11e7-93d5-5073bf51c041.png)
1. Click drop down box to switch to adding units for the bot. And this is where the issue begins directly to the right of the drop down box.  
![clickbutton](https://user-images.githubusercontent.com/13558671/30304668-deb51c3a-972b-11e7-9865-7c9a3f12c14b.png)
1. Moving around the mouse in the window causes white space to cover buttons and boxes/buttons being draw in weird spots. For example:  (The lower right box scrolls as the actual one does, too.)
![offsetexample](https://user-images.githubusercontent.com/13558671/30304728-36cbfdb2-972c-11e7-81c2-df9c523f744b.png)

This makes the game unplayable. The buttons are draw correctly if the mouse is over the button but then disappears again when the mouse moves away.

Attached is the log: 
[megameklog.txt](https://github.com/MegaMek/megamek/files/1294511/megameklog.txt)

### Possible ideas
 * Windows 10 is screwing with Java.
 * Nvidia is screwing with Java.
 * Swing isn't handling the combo drop down box properly when it extends outside the window frame.  

It also looks like the stuff from one window, when closed, is placed onto the window behind it, like the stuff wasn't reset or discarded.  

I'm looking for ideas or a fix for this. I haven't gotten around to trying this out on Linux, so I will.
 - [x] Test on Linux for same issue.  

P.S. I couldn't figure it out on my own so I'm looking for help.

**Comment by HammerGS** [comment]
I'm running Windows 10, with latest NVIDIA drivers and Java 1. (144) and I can't duplicate this.

**Comment by dericpage** [comment]
Do you have any screen capture software running?  I seem to recall an issue a while back with some screen capture software messing up java-base GUI.  It wasn't isolated to MM either.

**Comment by elementx54** [comment]
I figured it wasn't a MegaMek bug or else WAY more people would be having it. So some external thing is causing the issue.  

I'm not aware of any screen capture software but I did turn off much of what I could find. I'll google this issue some more. I guessing that this issue will end with the solution being posted without needing any merges to the code. I'll let you know if I find anything.

**Comment by elementx54** [comment]
Also, the first screen that has the "start new game" and "connect as bot" buttons never has any problems even when the other screens are all horrible.

**Comment by elementx54** [comment]
I believe I have found the fix. \o/ The command line option `-Dsun.java2d.d3d=false` was suggested as a fix for Java 8. I'm not sure of the details, but here is the link:  
https://stackoverflow.com/questions/22737535/swing-rendering-appears-broken-in-jdk-1-8-correct-in-jdk-1-7

Should this line be included in the starter for Windows?  

I'm still testing the "fix" but so far no issues.

**Comment by elementx54** [comment]
I tested this on Linux and it doesn't happen. 👏   

And the fix above of setting the 3D stuff to false works for now. Should that option be added to the Window's starter?

**Comment by pheonixstorm** [comment]
As long as it doesn't cause other issues. As with hammer I am running Win 10 with a Nvidia 960 and have no issues. Java 8 needs an update as do my vid drivers.

**Comment by arlith** [comment]
This option is disabling direct draw (D3D) I believe.  I think this should be fine. D3D was the precursor to DirectX.

**Comment by pheonixstorm** [comment]
Direct Draw was part of DirectX until version 7 with parts of it folded into D3D (Direct3D). The precursor to DirectX was a horrid beast

**Comment by elementx54** [comment]
I'm going to add it in as it is easy to add and will be easy to remove if it turns out to not work (or makes other problems).

**Comment by elementx54** [comment]
Sorry in advance if this pops up on your feed, but I'd like to help others who might have the same problem as me. This still exists and the work around still works, but for some reason in another Java application that isn't MegaMek, the command line option did not work.

However, setting an environmental variable "J2D_D3D" with a value of "false" fixed that program that had the same behavior this bug shows. So posterity or future people seeing this, I hope this helps you with your Java menu draw artifacts. Someday I hope this Java bug is fixed, but for now this is the work around that I've had success with.

**Comment by HammerGS** [comment]
Covered in the Wiki here - https://github.com/MegaMek/megamek/wiki/Known-Issues-and-Workarounds
