### ISSUE TITLE
43.3 fire phase locked up

### ISSUE THREAD

**Issue by Axe64** [MegaMek/megamek#648]
[megameklog (2).txt](https://github.com/MegaMek/megamek/files/1294720/megameklog.2.txt)
[autosave (1).sav.gz](https://github.com/MegaMek/megamek/files/1294721/autosave.1.sav.gz)
[spottingtesting.sav.gz](https://github.com/MegaMek/megamek/files/1294722/spottingtesting.sav.gz)
i think the game might have stopped working from spotting.

**Comment by BLOODWOLF333** [comment]
https://github.com/MegaMek/megamek/issues/636
Is that what you are seeing?  Arlith fixed it already with spotting and indirect LRM fire.

**Comment by arlith** [comment]
Yea, this is the same issue with spotting that was fixed in #636 and the second bug in #582.
