### ISSUE TITLE
Right click -> Set all MGs to burst fire doesn't work

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#657]
If you right click a unit with MGs in the lobby (e.g. Fenrir Assault BA) and use the "set all MGs to burst fire" option, it doesnt actually work. When you double click the unit in the lobby, the MGs will be set to rapid fire in the equipment tab, but when you get ingame, the MGs will not be set to rapid fire.

The change only takes effect if you manually double click every unit with MGs and click "okay", "next" or "previous". You will then get the normal message that "unit XXX has been customized", and then the unit will have rapid fire MGs ingame.

Im guessing the problem is that the right click -> set all MGs to burst fire option is setting them to burst fire, but not actually saving them, which only happens when you double click a unit and use the okay, next or previous buttons.

[megameklog.txt](https://github.com/MegaMek/megamek/files/1308554/megameklog.txt)

**Comment by neoancient** [comment]
It's changing the setting in the client but not sending the change to the server, so it gets overwritten when the server updates all the clients in the exchange phase between the lounge and deployment. I saw that the same is true of setting all lrms to hotload/normal or turning a searchlight on or off, so I fixed those also.
