### ISSUE TITLE
APC sprites incorrectly named?

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#663]
The mechset.txt file appears to be pointing to APC images that have not been renamed to the new format.

E.G. exact "Armored Personnel Carrier (Tracked SRM)" "vehicles/Armored Personnel Carrier (Tracked SRM).png"

There is no such image file in my images folder, all the APC sprites appear to have names like "ht_apc_s.gif".

The missing sprites are causing NPEs : 

Trying to load image for a non-existant file! Path: data\images\units\vehicles\Armored Personnel Carrier (Tracked SRM).png
Received null image from ImageUtil.loadImageFromFile!  File: data\images\units\vehicles\Armored Personnel Carrier (Tracked SRM).png
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException

[mekhqlog.txt](https://github.com/MegaMek/megamek/files/1318849/mekhqlog.txt)

**Comment by arlith** [comment]
Pretty sure this was a packaging issue.  Haven't seen any reports with subsequent releases.
