### ISSUE TITLE
Enhancement Request: Get linked Equipment to work with Bay Weapons

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/megamek#666]
For Artemis and such.  Attack value isn't getting the proper bonus because the current bay weapon code can't read linked equipment.  You can assign this one to me.

**Comment by HammerGS** [comment]
Left a message on Slack with reference to the code I think is part of the issue.

**Comment by mkerensky** [comment]
Fixed in PR #715

**Comment by NickAragua** [comment]
Fixed with PR #715
