### ISSUE TITLE
Dev version: Unit Loading Failures on recent commits

### ISSUE THREAD

**Issue by mhjacks** [MegaMek/megamek#669]
I have been building my own versions to test lately; I might be doing it wrong (ant -f packaging_local.xml nix-release).

Recent builds from master (starting after Sept 18) are showing a bunch of unit load failures, which didn't show before; the units have existed for a while.

![screenshot from 2017-09-22 19-13-21](https://user-images.githubusercontent.com/7352852/30768583-635fd492-9fcf-11e7-9bb3-f0ece79fdddf.png)

Attached is also the log that shows where the NPE's are occurring.

[megameklog.txt](https://github.com/MegaMek/megamek/files/1326162/megameklog.txt)

I could be building them wrong.

**Comment by HammerGS** [comment]
I can't reproduce the errors. Are you sure you're updated with the latest unit files? The errors are related to IO Tech progression.

Also have you deleted the unit.cache and let the new version rebuild it.

**Comment by pheonixstorm** [comment]
I got the same on my custom version after starting a MM game from HQ, thought it might be because I just copied over the binaries and lib/mmconf folders but guess not. Going to start a new custom tonight so will test again and pull both dailies.

**Comment by neoancient** [comment]
I'm pretty sure I know the cause based on the log file. I may not have a chance to do anything about it until tomorrow.

**Comment by mhjacks** [comment]
I'm building the full nix-release target from a pristine checkout of the master branch at commit c24a0b2ab6, built on my own system.  Where are the dailies kept?

**Comment by neoancient** [comment]
Yes, that's a separate issue.
