### ISSUE TITLE
Issue with hidden units and point blank shots - end hex resets to first PBS location

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/megamek#672]
Working on fixing hidden units in buildings and ran across this. The Mech traveled to 0809 and was hit by TWO point blanks shots then at the end of its movement ended its movement in 0808. Based on my reading of the rules a PBS should not have any affect on the movement of the target of the pbs unless the unit in question sustained critical damage (or something that would end movement via destruction or failed psr). Viewing the mech during the movement phase shows no damage that would cause this issue.

The log shows both pbs but no errors as to why this may have happened.

To use this save you can modify infantry.java ln538 adding:
`&& !hex.containsTerrain(Terrains.BUILDING)) {`

If you would prefer I can send a jar via PM in slack

[megameklog.txt](https://github.com/MegaMek/megamek/files/1327010/megameklog.txt)
[pointblankbug.sav.gz](https://github.com/MegaMek/megamek/files/1327011/pointblankbug.sav.gz)
![pbs_reverse](https://user-images.githubusercontent.com/1787879/30779151-7281fb8e-a0b6-11e7-9ebd-202a5fc312b2.png)

**Comment by NickAragua** [comment]
Fixed with PR #857
