### ISSUE TITLE
Negative elevation (VTOL)

### ISSUE THREAD

**Issue by mwberlindeu** [MegaMek/megamek#674]
The elevation of a VTOL flying in negative Terrain (e.g. in a Canyon at Level -2) is not shown properly. The Situation can be recreated easily with the map "Factory V9 32X32"

**Comment by neoancient** [comment]
What is shown is not the absolute level, but the elevation over the underlying terrain.

In this image the elevation is correctly shown as increasing as the VTOL flies at level 1 above terrain that decreases in level.

![image](https://user-images.githubusercontent.com/16927464/32621331-138c3e92-c545-11e7-8741-3c3868434499.png)

Here the VTOL has dropped to level -1, and is correctly shown at 1 elevation above the level -2 terrain.
![image](https://user-images.githubusercontent.com/16927464/32621609-fb5e4666-c545-11e7-8de7-8c1a519a9631.png)
