### ISSUE TITLE
MegaMek Lab - Infantry PDF Print/Print Name not Changing

### ISSUE THREAD

**Issue by FrozenIceman01** [MegaMek/megamek#677]
In MegaMek Lab - If you create an Infantry unit, save a .blk file and then print to pdf (or printer) the name will print correctly.  If you modify that infantry unit with a different weapon, change the name and save it it will save correctly.  However if you attempt to print that Record sheet the name printed will be of the original name not the new name you changed and saved it to.

A work around is to close MML and load the .blk file of the new unit and it will print normally.

**Comment by HammerGS** [comment]
Wrong Tracker. Moved here
https://github.com/MegaMek/megameklab/issues/82

**Comment by FrozenIceman01** [comment]
Much appreciated, thank you!
