### ISSUE TITLE
[0.43.2-git : Error] Princess Direct Fired Thumper Rounds At Aero Causing Error

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#679]
Princess field artillery decided to direct fire my aero using Thumper rounds.

Screen shot, before and after save, log attached.

![princessdirectfiredthumperroundsataerocausingerror](https://user-images.githubusercontent.com/17064665/30793722-58672828-a1f6-11e7-9624-1788c3fc83be.png)
[PrincessDirectFiredThumperRoundsAtAeroCausingError-RoundStart.sav.gz](https://github.com/MegaMek/megamek/files/1328352/PrincessDirectFiredThumperRoundsAtAeroCausingError-RoundStart.sav.gz)
[PrincessDirectFiredThumperRoundsAtAeroCausingError-AfterError.sav.gz](https://github.com/MegaMek/megamek/files/1328350/PrincessDirectFiredThumperRoundsAtAeroCausingError-AfterError.sav.gz)
[PrincessDirectFiredThumperRoundsAtAeroCausingError-Log.txt](https://github.com/MegaMek/megamek/files/1328351/PrincessDirectFiredThumperRoundsAtAeroCausingError-Log.txt)

**Comment by BLOODWOLF333** [comment]
Princess doesnt understand artillery yet she isnt coded for it.

**Comment by SirMegaV** [comment]
I know that.. just curious how did Princess even get to target an aero with arti when a player can't target it (which is also illegal).

**Comment by servo01** [comment]
How was the map grid and hex numbering turned off in the above image?

**Comment by BLOODWOLF333** [comment]
Im pretty sure Mega uses a custom tileset.  But if you go into view>client settings>graphics and select the BW_Atmospheric tileset it will get rid of the hex borders (I didnt put any grey/black border around the images for the terrain).  And then view>client settings>advanced find Hex Numbers and change it to False to shut the hex coordinates off.

**Comment by SirMegaV** [comment]
Yup. I'm using custom tileset with BW_Atmospheric as the base. The hex
number can be turned off somewhere in the last tab in the client settings.

**Comment by NickAragua** [comment]
As part of my work on #2042 , I tested having the bot direct-fire thumper rounds at aerospace units, and I do not believe this is an issue any longer.
