### ISSUE TITLE
[Nightly Build 368] Unit deployment graphical glitch

### ISSUE THREAD

**Issue by NickAragua** [MegaMek/megamek#682]
Start up the attached save game as the "Magistracy of Canopus". Attempt to deploy unit in hex 0602. Note the Saracen in 0703 decides to jump around a little bit.
[SaracenWTF.sav.gz](https://github.com/MegaMek/megamek/files/1331214/SaracenWTF.sav.gz)

Log file attached, but I don't see anything useful in there.
[megameklog.txt](https://github.com/MegaMek/megamek/files/1331215/megameklog.txt)

**Comment by Question2** [comment]
Is this the same issue as https://github.com/MegaMek/megamek/issues/215?

**Comment by NickAragua** [comment]
Yes, I think so.

**Comment by NickAragua** [comment]
Same issue as #215, closing duplicate.
