### ISSUE TITLE
[Nightly build 371] Mech able to climb up two-hex cliff

### ISSUE THREAD

**Issue by NickAragua** [MegaMek/megamek#683]
Rifleman in hex 1832 is able to move to hex 1833, even though 1832 is at level -3 and 1833 is at level -1. 

[riflemanuptwolevels.sav.gz](https://github.com/MegaMek/megamek/files/1342191/riflemanuptwolevels.sav.gz)

**Comment by BLOODWOLF333** [comment]
TW .48
LEVEL CHANGE
While moving forward, a 'Mech may change level or depth
by only 1 or 2 levels per hex, at a cost of 1 MP per level.

-3 to -1 is only 2 levels......or am I not reading your thing right?

**Comment by NickAragua** [comment]
Huh. Didn't realize mechs could climb up two levels.
