### ISSUE TITLE
Alternative Proto-AC ammo

### ISSUE THREAD

**Issue by Xeno426** [MegaMek/megamek#684]
I would like to request that Protomech AutoCannons get access to alternative ammo, as per TO Errata rules.

> ③ ProtoMech Autocannons (Proto-AC) (p. 286)
Under “Game Rules”, first sentence
ProtoMech Autocannons use the same rules as standard autocannons.
Change to:
ProtoMech Autocannons use the same rules as standard autocannons, including the ability to use special munitions (when
using armor-piercing ammo and checking for armor-piercing critical hits, apply the following modifiers: PAC 2 (–4), PAC 4
(–3), PAC 8 (–2))

**Comment by HammerGS** [comment]
I'll give this a try.

**Comment by HammerGS** [comment]
Implemented and tested here.  In the same commit I've also added the Clan Improved Autocannons ability to use special ammos.

https://github.com/MegaMek/megamek/commit/b7110f64c1aa8f8c1bf02bea5b109554d92c1c0b
