### ISSUE TITLE
Destrier doesn't get a chance to fire artillery

### ISSUE THREAD

**Issue by mhjacks** [MegaMek/megamek#690]
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/1347656/autosave.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/1347655/megameklog.txt)

The Destrier superheavy artillery piece seems not to be getting a chance to fire its artillery during the off-board phase.  It gives me the option to fire the long toms during the regular fire phase.

I'm using a build I did myself at commit a940064eb4.

**Comment by HammerGS** [comment]
But they are equipped with Long Tom Cannons not Long Toms.

To pg 285
_Artillery Cannons are classified as ballistic weapons, rather than artillery weapons, and may not be used to deliver Indirect Artillery attacks._
