### ISSUE TITLE
Incomplete Deployment of Force

### ISSUE THREAD

**Issue by Flibjib** [MegaMek/megamek#695]
I'm attempting to start a scenario with a lance of Meks from MekHQ. They are all in working order, and the pilots are healthy. They all appear in the initial setup, but when I begin the game, I can only deploy 2 of the 5. 

I have seen this behavior before with units or mechs that were KIA in previous battles and edited back to life, but never with ones that were just damaged.
[Hold the Line (Attacker)bugged.mul.zip](https://github.com/MegaMek/megamek/files/1375904/Hold.the.Line.Attacker.bugged.mul.zip)
[Minnesota Tribe28270402.cpnx.zip](https://github.com/MegaMek/megamek/files/1375905/Minnesota.Tribe28270402.cpnx.zip)

**Comment by Question2** [comment]
I've seen this as well, but restarting mekhq always fixes it.
