### ISSUE TITLE
Princess bot floods chat with path calculation messages

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#697]
Since I upgraded to 43.4, it seems that the princess bot keeps flooding the chat with path calculation messages, even with verbosity set to OFF. I have kicked and replaced the bot several times, each time with verbosity set to OFF and it still keeps flooding the chat.

![megamek](https://user-images.githubusercontent.com/1191378/31454871-a2a65576-af02-11e7-92b4-361d9d99032d.jpg)

save : https://github.com/MegaMek/megamek/files/1376511/battletech.sav.gz

log : https://github.com/MegaMek/megamek/files/1376514/mekhqlog.txt

**Comment by dericpage** [comment]
The attached log file appears to be incomplete.

**Comment by Question2** [comment]
I double checked and it doesn't appear to be incomplete, im looking at it now and most of the last lines are just "could not find a match for building..."

**Comment by scJazz2** [comment]
> I double checked and it doesn't appear to be incomplete, im looking at it now and most of the last lines are just "could not find a match for building..."

Cause you attached the HQ log not the MM Log

**Comment by Question2** [comment]
MekHQ games used to write to the mekhq log...is it supposed to write to the megamek log now?

**Comment by MGM175** [comment]
I can confirm that Princess in MegaMek itself also have that problem. Can you add a DEBUG switch for that bot's options?

**Comment by dericpage** [comment]
Code has been written to better handle this.  It's just waiting for me to get the chance to actually test it and merge it in.  Unfortunately, I'm about 2 weeks away from a code freeze at my real job, so testing likely won't happen before then.

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/3e9fd36c74ae5a3b45b6792428561113f83feb04
