### ISSUE TITLE
0.43.4 - Unable to deploy ASF over Woods

### ISSUE THREAD

**Issue by Nightstalker17** [MegaMek/megamek#702]
Since version 0.43.4 it seems to be impossible to deploy ASF over wooded terrain. I started several existing and new campaigns with MekHQ, loaded the units into Megamek and tried to deploy them - always with the same result.

**Comment by pheonixstorm** [comment]
this on the ground map or atmosphere map?

**Comment by Nightstalker17** [comment]
On a ground map. ASF always at standard altitude of 5. Deployment of VTOLSs over wooded terrain works as it should. Have not tested it with other units so far.

**Comment by HammerGS** [comment]
I can duplicate and have a fix of ASF's but till figuring out how to do it for LAMs
