### ISSUE TITLE
Add a units original BV/current BV info in Unit Display

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/megamek#703]
On the General Tab... just like it appears on Mouse Over and change the Text Label to Battle Value.

**Comment by kuronekochomusuke** [comment]
is this still an issue?

**Comment by HammerGS** [comment]
I believe it only shows updates in summary reports not in the unit overview.

**Comment by kuronekochomusuke** [comment]
is this what they are asking for?

![image](https://user-images.githubusercontent.com/116095479/200414219-0dedf972-ae44-4120-9e3c-267d9fc56a62.png)

**Comment by HammerGS** [comment]
Yep, that's how I understand it.

**Comment by kuronekochomusuke** [comment]
so this can be closed?

**Comment by HammerGS** [comment]
I hadn't noticed do we have this now?

**Comment by HammerGS** [comment]
Let me know of any others that can be closed you find. Thanks
