### ISSUE TITLE
Princess hangs when having surviving infantry unit abandon immobile APC/Carrier vehicle

### ISSUE THREAD

**Issue by Flibjib** [MegaMek/megamek#704]
I've noticed this for a long while, at least as far back of 4.2, that when an infantry carrying vehicle is immobilized, the AI will hang when the choice comes to disembark from the vehicle.

**Comment by NickAragua** [comment]
Could you provide a saved game and logs/megamek.log file from when this occurs? It'll make troubleshooting it a whole lot easier.

**Comment by Flibjib** [comment]
[strandedinfantrylocked.sav.gz.zip](https://github.com/MegaMek/megamek/files/1416866/strandedinfantrylocked.sav.gz.zip)
Can be easily replicated by loading infantry into an APC, and then immobilizing but not destroying it.

**Comment by Flibjib** [comment]
[megameklog.txt](https://github.com/MegaMek/megamek/files/1416871/megameklog.txt)

**Comment by NickAragua** [comment]
Fixed with PR #722
