### ISSUE TITLE
[43.4] Unable to get up from 'hull down' in depth 1 water

### ISSUE THREAD

**Issue by NickAragua** [MegaMek/megamek#705]
[hulldownbug.sav.gz](https://github.com/MegaMek/megamek/files/1391204/hulldownbug.sav.gz)

No errors in the log. 

Select the "Hull down" Wasp and attempt to get up. He *should* be able to, having 6 walking MP, but he's not.

**Comment by NickAragua** [comment]
In addition to the above-described problem, going 'hull down' as a result of a failed PSR while walking/running ends movement (whereas falling does not). 

Fixing this is a non-trivial effort, as the movement processing code is ... "organizationally challenged", to put it mildly.

**Comment by SJuliez** [comment]
I could not reproduce the getting up problem on the current 0.47 version. Took a wasp, activated TacOps Hull Down (both with and without TacOps advanced falling) and went hull down in lvl1 water. Could get up without problems.

**Comment by NickAragua** [comment]
It's not a voluntary hull down, it's a failed PSR. I think I was going to work on it a while back, but then discovered that the problem was in Server.ProcessMovement.
