### ISSUE TITLE
MekHq Allows Negative ability scores (tactics)

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#707]
Latest version (43.4) rolled a pilot in the market with a tactics score of negative one (-1). While funny, this is clearly an error. 

[The Rolling HoundsNegTac.zip](https://github.com/MegaMek/megamek/files/1400816/The.Rolling.HoundsNegTac.zip)

I did not test if this pilot actually applied a penalty in MM missions. He might.

**Comment by VampireSeraphin** [comment]
Also, this is in the wrong place and I don't know how to move it.

**Comment by pheonixstorm** [comment]
Can't be moved, but I would suggest leaving this alone as it will be useful in the future. Except for the market.. that shouldn't give negative abilities.

**Comment by HammerGS** [comment]
@VampireSeraphin Please reopen this on the MekHQ tracker and you can close this one out.

**Comment by VampireSeraphin** [comment]
I showed it to jazz, looks like he already opened a ticket on #504 https://github.com/MegaMek/mekhq/issues/504
