### ISSUE TITLE
Swarming Battle Armor do not check for fires in hex

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#708]
What it says on the tin. Same game save as #556 .

**Comment by VampireSeraphin** [comment]
Errata may be needed for this, myself and Obvioustech were unable to find a definite answer in rule books or the forums.

**Comment by VampireSeraphin** [comment]
Still awaiting official response in this thread:

http://bg.battletech.com/forums/index.php?topic=59142.0

**Comment by Dylan-M** [comment]
@VampireSeraphin can you bump the thread to try and get a response please?

**Comment by HammerGS** [comment]
See here for answer - http://bg.battletech.com/forums/index.php?topic=14289.msg331593#msg331593

So Swarming units (BA and Infantry) can burn per the rules on TO pg 45
