### ISSUE TITLE
[0.43.2-git : Bug] Aero's Fire Control System

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#711]
An aero with its fire control system destroyed should be marked as 'crippled' since it can no longer shoot. Save game attached.

[AerosFireControlSystem.sav.gz](https://github.com/MegaMek/megamek/files/1403737/AerosFireControlSystem.sav.gz)

**Comment by mkerensky** [comment]
Makes good sense to me.  I'll take a look at this one.

**Comment by mkerensky** [comment]
Fixed in PR#726

**Comment by NickAragua** [comment]
Fixed with PR #726
