### ISSUE TITLE
Feature Request: View unit displays bombs and ordiance on fighters with type names

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#713]
Presently, an enemy aero fighter carrying bombs, if clicked and viewed, only shows "altitude bomb/Dive Bomb." Instead, they should list the bombs they are carrying (rocket pod 3, Cluster Bomb 2, Inferno Bomb 1, etc...)

**Comment by neoancient** [comment]
You can see the bomb types by looking in the nose section of the systems tab.
![image](https://user-images.githubusercontent.com/16927464/32621892-f4d0462c-c546-11e7-8807-11864e221203.png)

**Comment by VampireSeraphin** [comment]
Is this in the documentation somewhere yet? MM is not a bastion of clarity on a good day and this was obscure eniugh to slip by me and probably others as well.


Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone
-------- Original message --------From: neoancient <notifications@github.com> Date: 11/9/17  1:11 PM  (GMT-05:00) To: MegaMek/megamek <megamek@noreply.github.com> Cc: VampireSeraphin <buttardc@gmail.com>, Author <author@noreply.github.com> Subject: Re: [MegaMek/megamek] Feature Request: View unit displays bombs and
  ordiance on fighters with type names (#713) 
You can see the bomb types by looking in the nose section of the systems tab.



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MegaMek/megamek","title":"MegaMek/megamek","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/MegaMek/megamek"}},"updates":{"snippets":[{"icon":"PERSON","message":"@neoancient in #713: You can see the bomb types by looking in the nose section of the systems tab.\r\n![image](https://user-images.githubusercontent.com/16927464/32621892-f4d0462c-c546-11e7-8807-11864e221203.png)\r\n"}],"action":{"name":"View Issue","url":"https://github.com/MegaMek/megamek/issues/713#issuecomment-343241870"}}}
