### ISSUE TITLE
Bug: Targeting a non-Entity with Arrow IV Homing Missile Causes NPE

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/megamek#716]
I caused this one when I wrote AMS code for Arrow IV homing missiles. If the tagged target isn't an entity (such as a hex target), an NPE occurs when the homing weapon handler tries to call calcCounterAV().  Fix forthcoming...

**Comment by mkerensky** [comment]
Fixed in PR #717

**Comment by NickAragua** [comment]
Fixed with PR #717
