### ISSUE TITLE
Enyo (Standard) MGs in body

### ISSUE THREAD

**Issue by Xeno426** [MegaMek/megamek#719]
As of version 0.43.4, the Enyo Strike Tank (Standard) has two machineguns, but they are placed in BD (body) rather than on the left and right sides, as per TRO 3067, page 35.

https://imgur.com/FiEdwut

**Comment by HammerGS** [comment]
Fixed here - https://github.com/MegaMek/megamek/commit/0d2100d819204ef9ff9f53d6e0a319dc4ce92b06
