### ISSUE TITLE
Manual battle resolution /defeat / victory in command line does not work

### ISSUE THREAD

**Issue by mwberlindeu** [MegaMek/megamek#732]
The manual resolution of the attached battle via /defeat and /victory command does not work. Does anybody have a hint, how to generate the result files (.mul files) ?

[Castor4.sav.gz](https://github.com/MegaMek/megamek/files/1433582/Castor4.sav.gz)

**Comment by neoancient** [comment]
Unable to duplicate.
I loaded the saved games as one of the players and assigned bots to the others, declared victory, and the game ended at the end of the turn.
After victory is declared all other players must acknowledge defeat. The bot will do this automatically, but if any players are disconnected the victory command will not take effect.

![image](https://user-images.githubusercontent.com/16927464/32615631-d6ad07fe-c535-11e7-9b16-c0c314a2e553.png)

**Comment by HammerGS** [comment]
Cross-linking five issues that turn out to share a root: ending a game by command when the
phases will not hold still long enough to do it.

- #2768 - the chatbox resets on every phase change in a bot-only game, so `/victory` can never be finished
- #545 - asks for a `/victory` button on the resolution screens, for that same reason
- #8415 - asks for `/victory` on the bot commands bar, which is what resolved #2768
- #6301 - `/victory` does not skip the remaining phases even with phase skipping enabled
- #732 (this issue) - `/victory` and `/defeat` do not work from the command line at all

#8415 is the live one of the five. All five carry the Victory Conditions label.
