### ISSUE TITLE
4.32 Elementals allowed to use Rapid Fire MGs

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#733]
I've notice in the lobby that elemental MGs can be set to rapid fire. Since elementals use no ammo, this breaks the ammo consumption rules of rapid fire.

Can we get some rules clarification on this?

**Comment by HammerGS** [comment]
Have a look at TO pg 102 under Rapid fire.

_Battle Armor may use this rule, and roll for each active trooper firing an MG separately._

**Comment by wildj79** [comment]
For those with an older printing of the rules, the section that @HammerGS is referring to is in the errata for TO on page 22.

[Tactical Operations Errata v3.6](http://d15yciz5bluc83.cloudfront.net/wp-content/uploads/2017/06/Tactical-Operations-v3.6.pdf?x64300)
