### ISSUE TITLE
Targetting A Unit With LRMs Causes Your Unit To Sink One Elevation

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#739]
So, during the targeting phase, if you have LRMs selected in your weapon list and you then select an enemy unit, your firing unit's sprite drops one elevation, has shadows drawn around it like its on a building and gets a -1 over the unit sprite.  No option to go up or down.  Climb mode, selecting next unit, hulldown, walk, selecting a different weapon, none of them fix it.  And also LRMs default target seems to be set on the hex(clear) instead of the occupying enemy unit.  You have to right click and manually select the unit to get it off targeting the hex.  Next turn the unit will either be stuck and all movement hex overlays blacked out or act like its on a building if a building is next to your unit.  Jumping does get the unit out of this condition and back to normal until you select another enemy with LRMs.
[beforefire.sav.gz](https://github.com/MegaMek/megamek/files/1443736/beforefire.sav.gz)

![github1](https://user-images.githubusercontent.com/16950832/32411736-df09ee90-c1b0-11e7-903d-9382278995c1.png)
![grass](https://user-images.githubusercontent.com/16950832/32411745-f0a2ff02-c1b0-11e7-9af7-227e26a41bfd.png)
![heavy](https://user-images.githubusercontent.com/16950832/32411748-080adef8-c1b1-11e7-82a6-7cea78f86aee.png)

**Comment by BLOODWOLF333** [comment]
And what is the (none) on the ammo mean?
![kittens](https://user-images.githubusercontent.com/16950832/32411776-c45ab0ec-c1b1-11e7-8580-710238e79f23.png)

**Comment by ObviousTech** [comment]
The || in this line is probably supposed to be in parenthesis with something next to it:

https://github.com/MegaMek/megamek/blame/master/megamek/src/megamek/common/actions/WeaponAttackAction.java#L541

**Comment by ObviousTech** [comment]
if (usesAmmo && (wtype.getAmmoType() == AmmoType.T_LRM) 
|| (wtype.getAmmoType() == AmmoType.T_LRM_IMP)

should be
if (usesAmmo && ((wtype.getAmmoType() == AmmoType.T_LRM) 
|| (wtype.getAmmoType() == AmmoType.T_LRM_IMP))

**Comment by NickAragua** [comment]
Fixed with PR #744
