### ISSUE TITLE
Bog Down Rules - Both stuck/unstuck should use same PSR modifiers (answered by CGL)

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/megamek#74]
Currently stuck/unstuck using two different PSR rolls. One accounts for only the bog down modifier and the pilots skill (avoid bogging down) while the other uses the terrain modifiers as well (unstuck). 

Reading over the rules I would think only the pilots skill and the bog down modifier would be used since but it seems someone used both (or two someones) I have posted a question on the BT boards so as with #43 this will be another item that may sit around for awhile.

**Comment by pheonixstorm** [comment]
This has now been answered http://bg.battletech.com/forums/index.php?topic=51586.0

**Comment by arlith** [comment]
Fixed with PR #183.
