### ISSUE TITLE
Skidding Vehicle freezing Client(s)

### ISSUE THREAD

**Issue by SnyderPhilip** [MegaMek/megamek#743]
Using the advanced vehicle movement rules, the PSR checks for vehicles before they do advanced maneuvers will sometimes cause an issue where the vehicle that fails the PSR will skid or fishtail, and if it does not end the movement of the vehicle, the client(s) (and the bot) will attempt to continue the movement, however the new facing and/or position of the affected unit are not updated in the client(s). At this point the game will become unresponsive.  You can still click the map, select everything on the board, do anything you would otherwise be able to do, except move the unit.  You also cannot just end movement there and be done with it.  Something at this point is out of sync between the client and the game itself, and the game will not allow you to continue until it is brought back in sync, which is usually a save and then a reload.

[megameklog.txt](https://github.com/MegaMek/megamek/files/1451450/megameklog.txt)
[Skid.sav.gz](https://github.com/MegaMek/megamek/files/1451453/Skid.sav.gz)

This is an autosave of the turn it happened, there's only a handful of vehicles on the board but I think the one that is going to cause the freeze has severe steering damage.   I will generate another mission where it can happen more reliable, if this can't be duplicated.

**Comment by mkerensky** [comment]
I noticed this too a few months back when this feature was brand new. At the time I wanted to finish my game, so I turned of the option in the save file and the rest of it went just fine. 
I'm pretty sure I can duplicate it and figure it out, though it will take me a bit to get to it as I'm currently working through a large feature addition.

**Comment by neoancient** [comment]
The skid code assumes that you cannot not skid on the first step, which is no longer true, and it throws an exception when trying to check the non-existent previous step.
