### ISSUE TITLE
Bug (0.43.4): Impossible to select IMP rounds for iATM

### ISSUE THREAD

**Issue by Xeno426** [MegaMek/megamek#750]
After adding a unit with iATMs in a new game, it is impossible to select Improved Magnetic Pulse (IMP) rounds for the unit.
https://i.imgur.com/ZlxYElh.png

**Comment by HammerGS** [comment]
Need a bunch more information. What year is the game taking place in? If it's after 3080 they are extinct.

**Comment by Xeno426** [comment]
Ok, that would be the problem. The year was set to 3200.

Still, why does it go extinct? Same with the Nova? We know the latter is in use by Clan Stone Lion, and if the IIW are still fine then why not the IMP? While we don't know what is happening in the Homeworlds, it would seem presumptuous to declare these things "extinct" as a result.

**Comment by HammerGS** [comment]
Per WoR Supplemental pg 18

_Of the new weapon systems that made their battlefield debut during the chaotic Reavings, only
the Nova CEWS has been banned from OmniMech and BattleMech design and development. The
Stone Lions have trialed for and won most of the salvaged systems; no Clan has chosen to construct
these components. The Lions recently received permission from the Grand Council to experiment
with incorporating the system in its second line and solahma vehicle forces. The lone stipulation to
the Council’s authorization was that it could only be used against non-Clan opponents_

_All usage of genetic diseases, mutagenic virotherapy, and other Society weapons are
forbidden by the Grand Council. What data was recovered after the Reavings was summarily
purged or destroyed. Possession of such material is immediate grounds for a Trial of Annihilation._

As I read that things aren't looking good for ANY of The Society Equipment.  But ultimately this is something you need to take up with CGL.  Per Int. Ops we follow the extinction dates as listed.  If they errata it then we'll update.

**Comment by pheonixstorm** [comment]
While extinct you still should be able to use it after 3080, but I think there is an option for allowing extinct equipment or you may have to change the TL to unofficial I don't remember... I know for campaign play (MekHQ) it is +5 to acquire extinct equipment. I forget how MM handles extinct equipment though.

**Comment by Xeno426** [comment]
Even when the tech level is set to unofficial, extinct units and equipment cannot be used. There doesn't seem to be any way to allow extinct equipment in any era.
