### ISSUE TITLE
Protomechs and ghost targets

### ISSUE THREAD

**Issue by Xeno426** [MegaMek/megamek#761]
Ghost Targets normally require a Pilot roll +3 to take effect, however Protomechs do not have Pilot scores.  In their absence, the Protomech's Gunnery score <i>should</i> be used, but right now it does not.
<a href="https://imgur.com/VKrli81"><img src="https://i.imgur.com/VKrli81.png" title="source: imgur.com" /></a>
This is obviously a target number of 5+3=7. I set this unit's Gunnery at 1, so the target should have been 4.

This has been confirmed for future errata clarification.
http://bg.battletech.com/forums/index.php?topic=59324.0

**Comment by neoancient** [comment]
The ghost target mod was changed in errata from +2 to +3 and I fixed this as well.
