### ISSUE TITLE
[43.5 beta] Aerotech fighter can "torso twist" by shift-clicking.

### ISSUE THREAD

**Issue by NickAragua** [MegaMek/megamek#763]
Give yourself an aerospace fighter with weapons in the forward arc on a ground or space map. Proceed to the firing phase. Shift-click and observe how your aerospace fighter magically torso twists towards the indicated direction.

![fightertorsotwist](https://user-images.githubusercontent.com/29387808/33107480-77e47b88-cf05-11e7-95f2-8ce18a69a5ed.jpg)

**Comment by mkerensky** [comment]
Hah, yeah that has been around for a few versions. I use it to reset my units if I screw up weapon fire declarations.
