### ISSUE TITLE
New Errata - Impacting crashes of Aero Units

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#770]
http://bg.battletech.com/forums/index.php?topic=54315.0

Crashes (p. 81)
⑤ Replace the first paragraph with the following:

     If a unit’s altitude matches the level of the hex it occupies and it does not attempt to land (see Landing, p. 87), it crashes. If the unit was Out of Control when the crash happened and is a DropShip or larger craft, it is destroyed. Otherwise, the unit’s controller rolls 2D6, multiplying the result by 10 and then multiplying again by the current velocity of the unit. If the unit had no velocity when it crashed, use a value of 2 for velocity when calculating damage. The final result is the number of damage points the unit suffers.
     Apply damage to randomly determined locations in ten-point groups. If the unit is a fighter, aerodyne DropShip or aerodyne small craft, use the Nose Hit Location Table for the appropriate unit class. If the unit is a spheroid DropShip or small craft, use the Aft Hit Location Table instead.

**Comment by Sleet01** [comment]
It looks like we are currently doing all of this _except_ destroying out-of-control DropShips (or larger) that crash.
