### ISSUE TITLE
Smoke LRM doesn't work

### ISSUE THREAD

**Issue by Playergh** [MegaMek/megamek#773]
I was playing a game with my friend earlier and I had a lot of LRM with smoke ammo, but they behaved exactly like normal LRM. I don't know yet if they did the lesser ammo explosion damage like they should but still do normal damage to targets, or if they're exactly the same as normal LRM, but I know that they did normal damage and did not create smoke

**Comment by HammerGS** [comment]
What version are you using? 

Please review. 
https://github.com/MegaMek/megamek/wiki/Making-a-Bug-Report

**Comment by Playergh** [comment]
Version 0.43.4
Would it help if I sent a copy of the saved game? It's a huge game with hundreds of units on the field, so it might take a while to get to the smoke-using units

**Comment by HammerGS** [comment]
Yes, 43.4 had fixes to Smoke LRMs to bring them in Line with the current TO rules.

**Comment by Playergh** [comment]
[cluster_vs_regiment.sav.gz](https://github.com/MegaMek/megamek/files/1523932/cluster_vs_regiment.sav.gz)
Here is a copy of the saved game. It's strange that they don't work despite the version having fixed them as you said.

**Comment by arlith** [comment]
There is a problem with you saved game attachment.  The file appears to be corrupted (I can't even unarchive to view the .sav file in a text editor).

**Comment by arlith** [comment]
I ran a test game with the latest version of MM and smoke seemed to work fine to me.  You'll either have to be more specific, give a list of your game options, or give a saved game that works.  I'm going to close this for now, but can re-open it if you provide more information.
