### ISSUE TITLE
Space battle attack phase report truncated 0.43.5

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#774]
For some reason, the attack phase reports are truncated for space battles.  Below, you will see that the _McKenna_ destroyed all three ships, but the attacks aren't shown.

The gamelog can't be attached since Github doesn't support HTML, so here's a copy-paste:

`Initiative Phase for Round #2
-------------------
Harold rolls a 6[6+0].
Princess rolls a 9[9+0].

The turn order for movement is:
  Harold, Princess, Princess, Princess

Wind direction is Southeast.  Wind strength is Calm.  The weather is Clear.  Visibility is Daylight.
  Fog level is None.
Harold: 463319 BV remaining (239.0% of 193164 initially) 0 BV fled
Princess: 370653 BV remaining (182.0% of 203562 initially) 0 BV fled

Targeting Phase
-------------------

Princess: Moving Sovetskii Soyuz Heavy Cruiser. 1 paths to consider.  Estimated time to completion: 0 seconds

Princess: ... 100% complete.

Princess: Sovetskii Soyuz Heavy Cruiser (Clan) #2 (Princess) is crippled and withdrawing.

Princess: Moving Sovetskii Soyuz Heavy Cruiser. 1 paths to consider.  Estimated time to completion: 0 seconds

Princess: ... 100% complete.

Princess: Sovetskii Soyuz Heavy Cruiser (Clan) (Princess) is crippled and withdrawing.

Princess: Moving Sovetskii Soyuz Heavy Cruiser. 1 paths to consider.  Estimated time to completion: 0 seconds

Princess: ... 100% complete.

Movement Phase
-------------------

Offboard Attack Phase
-------------------

Weapon Attack Phase
-------------------

McKenna Battleship (Clan) (Harold) rolls a 7 for ECCM (target 5): ECM will be reduced by 2.
Sovetskii Soyuz Heavy Cruiser (Clan) (Princess) rolls a 4 for ECCM (target 5): ECM will be reduced by 0.
Sovetskii Soyuz Heavy Cruiser (Clan) #2 (Princess) rolls a 9 for ECCM (target 8): ECM will be reduced by 1.
Sovetskii Soyuz Heavy Cruiser (Clan) #3 (Princess) rolls a 10 for ECCM (target 5): ECM will be reduced by 5.
    Capital Missile Bay at McKenna Battleship (Clan) (Harold); needs 6, rolls 5 : misses

Physical Attack Phase
-------------------

Heat Phase
-------------------
McKenna Battleship (Clan) (Harold) gains 12640 heat, sinks 12640 heat and is now at 0 heat.

Control Rolls
-------------------

End Phase
-------------------
Team 1 has achieved all required victory conditions!

Victory!
-------------------

Winner is: TEAM #1

Harold: 460821 BV remaining (238.0% of 193164 initially) 0 BV fled
Princess: 0 BV remaining (0.0% of 203562 initially) 0 BV fled

Survivors are:
McKenna Battleship (Clan) (Harold)
Crew : Ning-qing Cen [4/5]
Kills : 3

Graveyard contains:
Sovetskii Soyuz Heavy Cruiser (Clan) (Princess)
Crew : Martyn Leroux [4/5]
Kills : 0
Destroyed by McKenna Battleship (Clan) (Harold)

Sovetskii Soyuz Heavy Cruiser (Clan) #2 (Princess)
Crew : Jamie Hansen [4/5]
Kills : 0
Destroyed by McKenna Battleship (Clan) (Harold)

Sovetskii Soyuz Heavy Cruiser (Clan) #3 (Princess)
Crew : Akello Ibrahim [4/5]
Kills : 0
Destroyed by McKenna Battleship (Clan) (Harold)

Detailed unit status saved to entitystatus.txt

***Server: Princess disconnected.`

[megameklog.txt](https://github.com/MegaMek/megamek/files/1525451/megameklog.txt)

**Comment by mkerensky** [comment]
I've done a LOT of work on space battles in 0.43.5, which is due for release 'soon'. Reporting changes among many others. If you still have this issue in the new version, let me know.

**Comment by wildj79** [comment]
@BLR-IIC Just an FYI, a way to get around Github's limitation is to change the file extension for the logs from `.html` to `.txt` or just add `.txt` to the end of the file name. You could also zip everything up and attach it that way. See attachments for examples.

[gamelog.html.txt](https://github.com/MegaMek/megamek/files/1527721/gamelog.html.txt)
[gamelog.txt](https://github.com/MegaMek/megamek/files/1527722/gamelog.txt)
[gamelog.zip](https://github.com/MegaMek/megamek/files/1527723/gamelog.zip)

**Comment by BLR-IIC** [comment]
Space battle reports are still being truncated in 0.43.5, although they are improved from the last version (changed issue title to reflect that bug is still present in 0.43.5):

[autosave.sav.gz](https://github.com/MegaMek/megamek/files/1579049/autosave.sav.gz)
[gamelog.zip](https://github.com/MegaMek/megamek/files/1579055/gamelog.zip)

**Comment by BLR-IIC** [comment]
Here's another gamelog.  It was a rough battle between a _Liberator_ and a _Texas_, but I didn't see all the details of the _Texas_ taking the other ship apart.
[gamelog.zip](https://github.com/MegaMek/megamek/files/1579199/gamelog.zip)

**Comment by mkerensky** [comment]
Go ahead and assign this one to me @HammerGS  

BLR-IIC - Would you say that you're getting all the reports for Capital Missiles, but not your other weapons?
And can you attach your 0.43.5 megamek.log?  Among other things, it will tell me easily what game options you have turned on. I use all of the advanced aero options, with the exception of a couple unofficial ones, when developing, testing and playing, so it's quite possible that something doesn't work right with fewer options than that.

**Comment by mkerensky** [comment]
BLR-IIC -  you're using the Aero Sanity Mod, which is currently unsupported.  When I last stopped using it, I recall it truncating reports just as you describe.
Turn that off and it should fix your future games.

I plan at some point to fix and support Aero Sanity, after I get all the canon space rules in. Don't hold your breath. It will take me a while to reach that point.

**Comment by BLR-IIC** [comment]
Indeed, turning off the Aero Sanity Mod option fixed the report problem I was experiencing.  I can do without that option for now :)

**Comment by BLR-IIC** [comment]
I noticed that the Aero Sanity Mod option actually doesn't have a bug warning in its tooltip.  Perhaps one should be added until it's fixed?

**Comment by HammerGS** [comment]
Added here - https://github.com/MegaMek/megamek/commit/4362aeec6289325b9d4223b2099477477844fb15

**Comment by mkerensky** [comment]
Full support for Aero Sanity has been implemented. This can be closed.
