### ISSUE TITLE
[43.5 beta] Can deploy naval units on surface roads.

### ISSUE THREAD

**Issue by NickAragua** [MegaMek/megamek#777]
![navyroad](https://user-images.githubusercontent.com/29387808/33644415-85c43780-da12-11e7-9cf5-2884ace834b5.jpg)

Set yourself up with a naval unit and a board that has a road on it, like in the screenshot. You can't deploy the naval unit anywhere else, but you sure can deploy it to the road.

**Comment by BLOODWOLF333** [comment]
Have something to do with #521 ?
