### ISSUE TITLE
unitNumber producing invalid XML

### ISSUE THREAD

**Issue by nderwin** [MegaMek/megamek#78]
While researching the feasibility of removing the remaining usage of XStream to replace it with JAXB (https://github.com/MegaMek/megamek/issues/62#issuecomment-195764033), I found an issue in Entity where invalid XML is being generated.

Entity.unitNumber is initialized to a char representation of -1, which turns into character `\uffff`.  When this is marshaled into the save file, it is turned into `&#xffff;`, which is illegal for XML (http://www.xml.com/2000/05/10/conformance/reports/report-xerces-nv.html).  Attempting to un-marshal the file, even without full object mappings, with JAXB will fail due to the illegal character.  If you change the PrettyPrintWriter that XStream uses to generate the file to use strict XML 1.0 or 1.1, that will fail due to the illegal character.  XStream, by default, uses quirks mode, which is allowing it to read/write this value.

So, any change with this attribute will result in a breaking change with existing save files, even if the data type is changed, or the initial value is changed.  A conversion program could be written that can open the gzipped save file and do a search for "&#ffff;" and replace it with "-1", or some other value.

What is the consensus of the development team for how to handle this?

**Comment by Akjosch** [comment]
Wait, `char` in Java is *unsigned*, it can't even hold negative numbers. Like, *ever*. How does that even work?

Looks like save game breakage it is, then. At least as far as my personal opinion goes. Making XStream save the XML properly (by writing a `Converter` for `Entity`) could be a short-term band-aid, but at some point it just won't be worth the work.

**Comment by nderwin** [comment]
@Akjosch The magic of casting...  https://github.com/MegaMek/megamek/blob/master/megamek/src/megamek/common/Entity.java#L546

**Comment by Akjosch** [comment]
@nderwin I saw how it was used, I'm just astonished why it didn't crash and burn somewhere else already.

**Comment by arlith** [comment]
I think changing `Entity.unitNumber` to a short would be fine. If anyone is concerned about how much memory an instance of Entity takes up, they are far far better off looking at how Quirks are stored.

**Comment by nderwin** [comment]
Here's a branch where I changed it from `char` to `short`.  No PR yet, I want to do some more testing on setting the unit number.  I was able to get it to be 0 (instead of -1) for a set of 5 Protomechs, but I suspect there may be some other ways of setting this.

https://github.com/nderwin/megamek/tree/bugfix/78-unitNumber-producting-invalid-XML

**Comment by arlith** [comment]
I dunno if it's clear, but unitNumber is (currently, to my knowledge) only used for protomechs.  Protomechs have special movement rules, where they are supposed to move as a "unit" even though they will have multiple, separate, unit icons on the map.  They're it's like a hybrid treatment between BA (where the squad has multiple suits) and a 'mech lance.

The unit number is used to determine which protos belong to which unit.  In theory, it could be used for other purposes, but it is *not* used for the "mek/vee moves multi" unofficial rules, which basically can make meks or vees move like protos (aka, you move 1 mek, then you have to move the rest of the lance; I'm told this makes very large games move much faster).

Entity.unitNumber needs to be -1, which indicates that an Entity is not a member of a unit, which is going to be the case most of the time.
