### ISSUE TITLE
[43.5 beta] Hidden units are visible on the minimap

### ISSUE THREAD

**Issue by NickAragua** [MegaMek/megamek#780]
When a player deploys a hidden unit, opponents can still see the hidden unit on the minimap.

![hiddenunitwhoops](https://user-images.githubusercontent.com/29387808/33750887-eb725c54-dba4-11e7-9c41-9fb269522b94.jpg)

**Comment by NickAragua** [comment]
View from the other player's client.

![hiddenunitwhoops2](https://user-images.githubusercontent.com/29387808/33750918-052c4074-dba5-11e7-82a5-d86e98ced361.jpg)

**Comment by mkerensky** [comment]
On the same subject, with Double-Blind on, hidden units can be found by your own units being revealed when within a hidden unit's line of sight.
