### ISSUE TITLE
[43.5 beta] Hidden units not allowed to self-reveal?

### ISSUE THREAD

**Issue by NickAragua** [MegaMek/megamek#781]
Steps to reproduce:
- Check 'Advanced Rules -> Hidden Units'
- Give yourself a unit, make sure to configure it as hidden in the deployment tab
- Deploy as normal
- Hidden unit does not have the option to reveal itself during the movement or firing phases. It's skipped completely during the movement phase and any firing attempt during the firing phase tells us that "hidden units are only allowed to spot".

**Comment by pheonixstorm** [comment]
I believe it did work as I remembering doing so no long after arlith added it.

**Comment by NickAragua** [comment]
Upon further research, the self-reveal functionality is buried in the 'Extras' tab.
