### ISSUE TITLE
Turrets Will Need To Become Targetable 

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#792]
![image](https://user-images.githubusercontent.com/16950832/34021343-f71ae0e4-e0fe-11e7-9879-71cc567e4cf2.png)

I know gun emplacements are a hack right now as Arlith has stated but, until they become entities then players may run into cases where the turret can shoot them but, the player cannot shoot back and it's an invincible turret.

I use the TacOps Advanced Diagramming LOS rules (where in TO is this?  I see the dead-zone rules but nothing called "Advanced Diagramming" that isnt compatible with the dead-zone rules.) which are not broken.  That LRM turret at the top of the screen can see my superheavy mech and fire at it as it should but, my superheavy cannot target the turret and has to target the building.  Who's LOS is blocked by the terrain in front of the building that the turret is sitting on.  That tends to give players fits.

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/34048490-83fc6648-e179-11e7-8d80-a1757b79a962.png)

**Comment by BLOODWOLF333** [comment]
Im not sure if the 6, 5, 3, on the turrets is their level including their height or if thats the height of the roofs?

**Comment by BLOODWOLF333** [comment]
![slack](https://user-images.githubusercontent.com/16950832/34048590-e4d2c16a-e179-11e7-84ef-20006073bf95.png)
If those numbers are the roof height then I think i still should be able to fire on the turret.

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/34052984-57be8244-e18a-11e7-8c54-4dddf0b76ac9.png)
TO Diagramming LOS rule is on
[TO_LOS_DIAG.sav.gz](https://github.com/MegaMek/megamek/files/1563488/TO_LOS_DIAG.sav.gz)

**Comment by BLOODWOLF333** [comment]
[TO_DEADZONE.sav.gz](https://github.com/MegaMek/megamek/files/1563497/TO_DEADZONE.sav.gz)
[STANDARD_LOS.sav.gz](https://github.com/MegaMek/megamek/files/1563498/STANDARD_LOS.sav.gz)

The other LOS rules

**Comment by NickAragua** [comment]
Should be fixed with PR #830. Since you're technically targeting the building, not the gun emplacement, it was considering line of sight to the height of the building, not height of the building + 1. Added in a special case where, if a building contains a rooftop gun emplacement, the targeting height is adjusted by 1.

**Comment by SimonLandmine** [comment]
Not sure that this fix has worked, as the same issue seems to continue to be the case.
