### ISSUE TITLE
43.x invalid boards

### ISSUE THREAD

**Issue by IReallyHateGithub** [MegaMek/megamek#793]
I've amassed a good number of maps over the years, and the 43.x branch is refusing to load a number of them. I've had this problem in 43.1, 43.2 and more recently, Bloodwolf's unofficial 43.5 beta. All of these boards work fine in 41.25

the client log spits out "Error reading board, data invalid." when I try to select the board, and when I load it in the editor, it warns me that the map has errors. Doesn't say what the errors ARE, or how to fix them. 

Attached, is one of many boards that generates the error. 
[55x55 Mech Rush.zip](https://github.com/MegaMek/megamek/files/1561259/55x55.Mech.Rush.zip)

**Comment by BLOODWOLF333** [comment]
swamp:0 terrain doesnt exist.

**Comment by IReallyHateGithub** [comment]
Given that this is happening to a number of different boards, and that the above example has been around for over 15 years before megamek complained about it and the other boards, having to hunt for errors like that by hand is a bit onerous and unpleasant. Any way that I could get an option to have the mm map editor strip invalid terrain types/list errors in a map/have megamek load it anyway and ignore the invalid terrain types?

**Comment by BLOODWOLF333** [comment]
[55x55 Mech Rush.zip](https://github.com/MegaMek/megamek/files/1561282/55x55.Mech.Rush.zip)
Changed all swamp:0 to swamp:1 's with notepad++ opened in the 0.43.5 map editor to verify fix.

I dont know if it would work but it might be possible to open every single board file we have in boards and then with notepad++ change all swamp:0, woods:0, any other illegal terrain types to the ones listed in the tileset files for every single board.

I'm learning VB.NET right now and plan to write an app to go through and open every single .board file we have, fix all illegal terrain, and then save them but, that's a little over my head right now.

**Comment by IReallyHateGithub** [comment]
Thanks, but I'm kinda wondering what changed from the old development version to the current devopment line, that caused these boards that worked for over 15 years, to suddenly stop. and if it can be optionally disabled?

**Comment by BLOODWOLF333** [comment]
They created a board validator recently.

**Comment by IReallyHateGithub** [comment]
I can fix them in notepad++, it's just really tedious. 

We have a mech-validator-disable feature, I'd love the same for the map validator (and any other validator that gets added) I'd rather have holes in maps that I can use, than have maps I can't use.

**Comment by Qwertronix** [comment]
The distinction is between _invalid_ and _rules-illegal_, IMO. A 'Mech that is against the rules can still be a valid entity in MM Data that runs fine and acts as the code expects in every way. An invalid board does not, and most likely has bugs in the edge cases (if a fire tries to spread to a tile that has invalid terrain, what happens? etc.)

Putting in the work to add a feature to let users bypass _validation_ might not be worth it, when a little bit more work than that could produce better reporting so the maps can be fixed in the first place.

**Comment by pheonixstorm** [comment]
Its not just rules-legal ness, there were actually boards floating around that were just plain junk that would crash MM. I went over every extra map that was included in ralgiths custom data awhile back and fixed almost all of them. A couple of them were just garbled/corrupt. Still haven't gotten around to sending the fixed maps to hammer yet though... really need to.

**Comment by IReallyHateGithub** [comment]
Did that include the old Jakes Map Pack maps?

**Comment by pheonixstorm** [comment]
Looks like it. Not sure if it is all of them or not though.

**Comment by HammerGS** [comment]
I've also lost track of the number of times I've run the Boards validator and fixed maps in releases. I also know SirMegaV is currently working on fixing maps.

**Comment by IReallyHateGithub** [comment]
Are these fixed maps available for download somewhere?

**Comment by HammerGS** [comment]
They are fixed and add to the releases. SirMegaV is still working on his project.  In the Repo their are currently only 3 maps that fail.

![image](https://user-images.githubusercontent.com/13752452/34052551-1f8634b2-e180-11e7-9f07-59abde77e864.png)

**Comment by IReallyHateGithub** [comment]
Most of my dead boards seem to be in a more up-to-date version of the Jake's Map Pack than seems to be included, and in the NBTBoards pack. Attaching both in hopes someone can fix them, I can't find what's wrong with a number of them. 
[jmp-11-17-05.zip](https://github.com/MegaMek/megamek/files/1565035/jmp-11-17-05.zip)
[NBT Boards.zip](https://github.com/MegaMek/megamek/files/1565036/NBT.Boards.zip)

**Comment by arlith** [comment]
I made a number of quality-of-life adjustments around this issue.

Entries from history.txt:
>+ Board editor hex preview indicates if hex is invalid, tool tip lists why
>+ Board view in board editor shows invalid terrain and adds the reason why to the tooltip
>+ Board editor now has validate button which will report all of the errors on the board

Commits: 
244dbe
59b199
8cd2bd

**Comment by HammerGS** [comment]
Just re-opening this long enough to leave the Batch report for the boards attached above.

[Mega Board Issues.txt](https://github.com/MegaMek/megamek/files/1565335/Mega.Board.Issues.txt)

**Comment by Dylan-M** [comment]
This should be closed to fixed now with the PR I accepted awhile back that had many fixes to boards. I have noticed that those changes have broken a few roads however, so the maps aren't 100% fixed. They are however, organized better and can continue to be worked on.

**Comment by HammerGS** [comment]
Closing per last comment.
