### ISSUE TITLE
Careful Stand Inop

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#794]
Using the MekHq 0.43.5-BetaNov11, MM gives you the pop-up asking for careful stand, click yes, done, and it does not apply.

Player Name: BLOODWOLF
[CarefulStand.sav.gz](https://github.com/MegaMek/megamek/files/1564496/CarefulStand.sav.gz)

**Comment by arlith** [comment]
I can't figure out which commit to checkout to run this saved game.

**Comment by BLOODWOLF333** [comment]
Reloaded the saved game tonight and now its applying the -2 for careful stand........gremlins.  How is this stuff possible that I will encounter a bug while playing, make a saved game and BR, and some how reloading the game fixes it?
