### ISSUE TITLE
Java.awt.IllegalComponentStateException

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#797]
Have been playing a tournament by myself and 7 princess bots.  Last game had the tileset on largetextures and after it was done and was in the lobby setting up the next game I changed the tileset to Bw Atmospheric.  Finished setting it up and clicked done to have the next 2 princess bots fight it out and seen this:

![github](https://user-images.githubusercontent.com/16950832/34082478-c0dca102-e324-11e7-9579-8f04a08a53f7.png)

Changed the tileset back to largetextures while the bots were fighting and didnt fix it.  And had the NPE in the log on line 3,272.  Must not have liked that I changed the tileset while in the MM lobby when the board is not displayed.

[megameklog.txt](https://github.com/MegaMek/megamek/files/1565907/megameklog.txt)

Did not get a saved game because when it is princess vs princess its too fast, steals focus constantly, and just wont let you finish typing.
MekHQ 0.43.5-BetaNov11

**Comment by BLOODWOLF333** [comment]
I am thinking the illegal component NPE might be caused by turning ISO view on.  Every time I start a new instance of Megamek my ISO is always turned off again and I think thats when it throw this NPE in the log (using my bw_atmospheric tileset if that has anything to do with it).

**Comment by SJuliez** [comment]
There is no error in the log. I very much doubt that it's possible to track this error now. Therefore I'm closing this.

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/121267750-48f12900-c882-11eb-9426-89cc9b084aae.png)
But, yeah this is so old nevermind
