### ISSUE TITLE
0.43.5 MiniMap Double Blind error

### ISSUE THREAD

**Issue by SnyderPhilip** [MegaMek/megamek#799]
The mini map shows unit Icon indicators for all units detected, even those that have just been spotted by sensors and not IDed visually.  The game map shows correctly the unidentified sensor contact icon.  This error did NOT exist in the 43.5BetaNov11 version.

**Comment by NickAragua** [comment]
Probably an issue with changes I made for not displaying hidden units on the minimap.

**Comment by NickAragua** [comment]
Fixed with PR#801
