### ISSUE TITLE
Add Aerospace Functionality for AMS/LAMS

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/megamek#8]
Anti missile systems are currently nonfunctional in space combat. They don't reduce the damage of standard missile flights, attempt to shoot down thunderbolts, or inflict damage to capital missiles as detailed on pages 96-97 in StratOps.

It may be that Point Defense Bays need to be given AMS functionality. Individual AMS/LAMS weapons within the bays still have an on/off function as if they're working normally, but it's the bay that fires.

**Comment by arlith** [comment]
I'm going to guess that, since these are rules in SO, that it's likely this is something that isn't yet implemented.  As much of space combat that is there, I think there's a lot of space combat that just hasn't been looked at yet.

**Comment by mkerensky** [comment]
Good enough for me. I play space battles quite often, and I'm very happy with all the work that's been put into it so far.

**Comment by mkerensky** [comment]
This has been completed.
