### ISSUE TITLE
6-Way Road Intersection Draw

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#803]
![image](https://user-images.githubusercontent.com/16950832/34140446-6822e996-e440-11e7-8810-b3b0482dc36a.png)

Have been seeing this in other versions as well, when the board first draws it will not draw the 6-way intersection image until you zoom in/out or change the tileset.

[RoadIntersection.sav.gz](https://github.com/MegaMek/megamek/files/1570356/RoadIntersection.sav.gz)
With my luck reloading the save will cause it to redraw correctly

**Comment by SirMegaV** [comment]
Bloodwolf, are you using the intersection road with traffic lights
(animated gif)? If so, yes, loading animated gifs (road) seems to have this
'delayed/slow' loading.

**Comment by BLOODWOLF333** [comment]
Oh, yes I am using your animated gif intersection.  Is that still a bug?

**Comment by SirMegaV** [comment]
I think you asked the same thing last time. The conclusion was something
similar to not fully support animated gif.

**Comment by SJuliez** [comment]
Closing this as per Dylan's comment.
