### ISSUE TITLE
Princess Aero Invalid Movement Packet

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#806]
For some reason Princess would get to 96% calculating the movement for the Lighting and then freeze.  With the error:
22:23:23,016 ERROR [megamek.server.Server] {Packet Pump} 
error: server got invalid movement packet from connection 1, Entity: Lightning LTN-G15
BotClient calculated turns, Princess phase PHASE_FIRING 8/8
IOException during AbstractConnection#update()

![image](https://user-images.githubusercontent.com/16950832/34193257-5ec2fdd6-e518-11e7-9a2e-e2c5dccb78f1.png)

I dont see anything wrong with where that Lightning could move?

MekHQ0.43.5 Windows Release
Player Name:  BLOODWOLF
[PrincessAero.sav.gz](https://github.com/MegaMek/megamek/files/1574350/PrincessAero.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/1574354/megameklog.txt)

**Comment by NickAragua** [comment]
After I fixed #807 and improving Princess' ability to evaluate bombing runs, I haven't been able to reproduce the behavior described here. Let's keep an eye on it though.

**Comment by BLOODWOLF333** [comment]
I can't reproduce this behavior anymore and no one else has run into this so, closing.
