### ISSUE TITLE
Princess Oververbose

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#808]
Princess is still displaying the 0-100% calculation chat messages in the megamek of MekHQ0.43.5 Windows Release. #697 #698 

![image](https://user-images.githubusercontent.com/16950832/34193598-27979662-e51a-11e7-8073-e5e2b7416ac8.png)

[VSAero.sav.gz](https://github.com/MegaMek/megamek/files/1574390/VSAero.sav.gz)

**Comment by dericpage** [comment]
Are you certain you have the Princess Verbosity level set to ERROR or WARN rather than INFO or DEBUG?  If so, can you attach the log file from this game?

**Comment by BLOODWOLF333** [comment]
Same game as #805 and #806 
[megameklog.txt](https://github.com/MegaMek/megamek/files/1575959/megameklog.txt)

I cannot say for certain what her verbosity was set on when I added her but, I know i did not adjust it so, I'm thinking it should have been on the default value.

**Comment by BLOODWOLF333** [comment]
Other's have verified (and I think I verified this was fixed with the beta I built) that this is fixed in the standalone MegaMek version but, this bug report is using HQ's.

**Comment by BLOODWOLF333** [comment]
I carry over my megamek.I4j, clientsettings, customweaponorder, bot, and gameoptions files to each new version but, didnt see any fields in any of those for her verbose setting if those have anything to do with this?

**Comment by dericpage** [comment]
Going by the log file, it appears that Princess may have been set to INFO verbosity.  You can adjust her chat verbosity via the Verbosity field in the Configure Bot dialog.  You can also adjust it during the game via the Verbose chat command.  You can check her current verbosity level via the Show Behavior chat commands.  The full syntax for the chat commands is in the PrincessBoDocumentation.html help file.

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/34218257-57149864-e573-11e7-9612-bef5ceb16ba0.png)

New install of HQ0.43.5 on my work laptop, she comes with the default setting.  Gave her a Mechbuster CF.

![image](https://user-images.githubusercontent.com/16950832/34218462-d9b0be38-e573-11e7-98ca-9cf1b7d49c47.png)

Still does it.  I personally dont mind it and lets you know if she freezes but, since a bug report was made previously and PR I'm just reporting what I'm seeing.

Player Name:  BLOODWOLF
[Verbose.sav.gz](https://github.com/MegaMek/megamek/files/1576369/Verbose.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/1576370/megameklog.txt)

**Comment by neoancient** [comment]
This occurs when an AtB scenario is launched from MekHQ because the verbosity setting in the dialog is not being saved.

**Comment by dericpage** [comment]
Good catch.

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/34808469-c43846f6-f654-11e7-870d-bc0e9262e1fe.png)

This behavior is still present in the 0.43.7-betaJan2 of Megamek

[OVPrincess.sav.gz](https://github.com/MegaMek/megamek/files/1621240/OVPrincess.sav.gz)
