### ISSUE TITLE
Princess freezes giving move orders

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/megamek#810]
[megameklog.txt](https://github.com/MegaMek/megamek/files/1576981/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/1576982/mekhqlog.txt)

princess attempting to move a unit for the first time gets stuck.
https://megamek.org/bb/thread-2479.html
[glitch.sav.gz](https://github.com/MegaMek/megamek/files/1576978/glitch.sav.gz)
Logs might have changed some since the event.  Logs from immediately after the event can be found via the forum link

**Comment by dericpage** [comment]
Can you post the log file and save game for this?

**Comment by neoancient** [comment]
The log file shows a fatal exception when trying to check the damage potential of the building a gun emplacement is mounted on but there is no building in the hex. There was a bug in this version that allowed turrets to be deployed in road hexes, but that has since been fixed.
