### ISSUE TITLE
Can't fire at fighter that passed directly overhead

### ISSUE THREAD

**Issue by fmoody** [MegaMek/megamek#813]
The Hunchback HBK-4G can't fire at either Golden or Imperial Eagle with the explanation of "Target out of range" even though they both passed directly overhead.

[Why.sav.gz](https://github.com/MegaMek/megamek/files/1577664/Why.sav.gz)

**Comment by NickAragua** [comment]
This seems incorrect, I'll work on it over the next couple of days.

**Comment by HammerGS** [comment]
Pg 107 TW.  Your shooting at Aircraft at Altitude 5.  So 1 hex from the flight path, 2 hexes per Altitude (10 Hexes).  11 Hexes Range, best range on the Hunchie's weapons is 9 hexes.  So Out of Range.

**Comment by NickAragua** [comment]
Heh. Thanks for the reality check, Hammer. 

On the plus side, this save provided an excellent testbed for some princess-related code changes.
