### ISSUE TITLE
Space movement for aero units being resolved incorrectly 0.43.5

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#815]
Aerospace unit movement on space maps seems very off.  When I add thrust from a standstill, it starts counting how many hexes I can move.  For an example, I accelerate a _Texas_ with three thrust points, yet I can only move two hexes.  If I try to move three hexes, I get the "This unit has not used all of its velocity." error.  I can only move two hexes at the most.

![image](https://user-images.githubusercontent.com/18338059/34254965-7caa7f04-e61c-11e7-9954-37884dd314fd.png)

![image](https://user-images.githubusercontent.com/18338059/34255008-a03486c2-e61c-11e7-9af2-2219bd57ed98.png)

**Comment by mkerensky** [comment]
Can you attach your megameklog.txt so I can see what options you're using?  I play with the advanced movement rules, and it looks like you are not in this example.  True?

**Comment by mkerensky** [comment]
I was able to reproduce this with a new game. I'll have to play with it some and read the standard space movement rules to see what is really happening.

**Comment by neoancient** [comment]
This is also true on the atmospheric map, but not the ground map.
