### ISSUE TITLE
Fighter stuck on atmospheric map with no movement options 0.43.5

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#818]
My Guardian fighter failed a control roll but didn't crash.  It's now at -1A with 1 velocity point.  It cannot move anywhere.  Game save and log attached.

[stuckfighter.sav.gz](https://github.com/MegaMek/megamek/files/1581293/stuckfighter.sav.gz)
[gamelog.zip](https://github.com/MegaMek/megamek/files/1581296/gamelog.zip)
[megameklog.txt](https://github.com/MegaMek/megamek/files/1581297/megameklog.txt)

**Comment by neoancient** [comment]
Do you remember what altitude it had before it failed the control roll? I assumed 5, since the round report says it lost 6 elevation and it's now at -1, but I can't find any code path that could avoid processing the crash.

**Comment by neoancient** [comment]
Nevermind. I see it now; you're on a low-altitude map in a hex with negative elevation, and since the low altitude map treats elevations as altitudes, you're still above the surface.

My current thinking on this is that any terrain with a level below zero should be treated as zero.

**Comment by arlith** [comment]
I would bet that the rules in the book don't necessarily cover this.  It seems like disallowing negative altitudes on the boards would be an option, although just treating negative terrain as 0 altitude seems like a better way to handle that.

I feel like the rule should be able to handle negative elevations, and I could think of situations where you might want negative terrains (for instance, it's practically a trope to drop down into a canyon to try to evade enemies).  But at least in terms of source code, I'm sure there are lots of places this would cause problems with how we wrote code...

**Comment by neoancient** [comment]
I'm not sure they considered negative elevations when they wrote that section, but the rules explicitly define zero altitude the ground, and state that no aerospace unit can enter a hex at zero altitude without crashing or landing (with exceptions noted for higher level terrain, but jot lower). Given the non-linear progression of the sizes of altitude bands, I don't think it's much of a stretch to understand negative elevations on the map as a difference of a few meters and not enough to make a difference in altitude. I also thought of the desirability of being able to drop into a canyon to evade enemies, but that could be achieved with a map that is mostly elevation 1 or 2 with rows of hexes at zero elevation.
