### ISSUE TITLE
Charging Damage against Buildings looks wrong (Mech skidding into building)

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#823]
See this post - http://bg.battletech.com/forums/index.php?topic=246.840

3 hex move into a Hardened Building resulted in 100 points of damage to the Charging Mech.

According to TW pg 148 - 

> Unusual Targets: If a charge attack is made against a target with no tonnage, such as a building or hill (for example, as the result of a skid), calculate damage to the attacker using the attacker’s tonnage rather than the target’s. For the purposes of Charge Attacks, DropShips are considered unusual targets.

So in this case the unit should have taken 8 points of Damage (3 hexes x (25/10)) round up.

**Comment by neoancient** [comment]
MM was using 10% of the current CF in that hex. There was a comment that declared it was an assumption, so whoever coded it probably just missed seeing the rule and it's gone undiscovered until now.
