### ISSUE TITLE
Switching off PPC Field Inhibitor has no effect

### ISSUE THREAD

**Issue by ShawnRonin** [MegaMek/megamek#829]
Hi, I started playing Megamek this year and I want to do some contributing. I've noticed that turning off a PPC's Field Inhibitor does not remove the minimum range modifier and after firing there is no roll for explosion due to feedback. I'd like to take a shot at fixing this issue myself if someone here might be able to help me get started. I've got a science degree, so I know some coding just not Java.

SR

**Comment by NickAragua** [comment]
You need to have the "TacOps PPC Field Inhibitor Disengage" setting (in the "advanced combat" tab of game options) turned on in order for the field inhibitor disengage to work. So the main issue is that the game UI allows you to switch inhibitor status without having the setting on.

My suggestion would be to disable the "mode" button for PPCs if that setting is not turned on.

**Comment by SJuliez** [comment]
@ShawnRonin are you still out there?

**Comment by SJuliez** [comment]
Question: Do rules for Inhibitors only apply to Mechs? TacOps p103 seems ambiguous to me. The rules for dialing back dmg p102 dont have any unit restriction.

Currently the mode code for PPC stuff is within Mech. Thus, when only tanks with PPCs are present they will never get to dial down their damage, yet when a Mech is also present the tank guys gain sudden insight and can dial down. Guess that's not working as intended...

Concerning the button I'd rather have the modes set correctly and the mode button respect those (and dutifully be disabled when no modes are available)
