### ISSUE TITLE
[43.6] Hidden units revealed by "show firing solutions" overlay

### ISSUE THREAD

**Issue by NickAragua** [MegaMek/megamek#831]
Looking up above the J.Edgar hover tank and below the Pegasus in the center, you'll see some mysterious Xs over supposedly empty terrain. That's probably where the "hidden" infantry is.

[hiddenunitwhoops.sav.gz](https://github.com/MegaMek/megamek/files/1591584/hiddenunitwhoops.sav.gz)
"1st Octopus Overlords"

**Comment by arlith** [comment]
X marks the spot, as they say...

**Comment by NickAragua** [comment]
Fixed that and also the mysterious ability to confirm the location of a hidden unit by clicking on the hex where it's hidden during the firing phase.
