### ISSUE TITLE
(PlayerColors) java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#834]
### Environment
HQ's MegaMek 0.43.6
Java version 1.8.0_144
Platform Windows 8.1 6.3 (amd64)

### Description
So if you select one of the camo patterns other than those listed in no camo, megamek will not display the unit image, will not let you close the window until you change the weight or unit type, and doesnt want to populate the unit list unless you change the unit type or weight class back and forth and sometimes that doesnt work.

I just changed it to Tank-light and is staying on assault mechs
![image](https://user-images.githubusercontent.com/16950832/34450787-e61e3e36-ecd8-11e7-9b77-0ed8b1ccf6f6.png)

### Files
Occurs inside the megamek lobby on start-up
[megameklog.txt](https://github.com/MegaMek/megamek/files/1594137/megameklog.txt)

**Comment by BLOODWOLF333** [comment]
Downloading the stand alone megamek0.43.6 and issue is present.  Can't even get the add unit window to open on first start-up after selecting one of the Davion marches camos.

**Comment by HammerGS** [comment]
Relevant part of the Stack Trace

```
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -1
	at megamek.client.ui.swing.util.PlayerColors.getColorRGB(PlayerColors.java:95)
	at megamek.client.ui.swing.ClientGUI.loadPreviewImage(ClientGUI.java:1740)
	at megamek.client.ui.swing.UnitSelectorDialog.refreshUnitView(UnitSelectorDialog.java:706)
	at megamek.client.ui.swing.UnitSelectorDialog$1.valueChanged(UnitSelectorDialog.java:270)
```

**Comment by MGM175** [comment]
Also encountered that bug while using just 0.43.6 as a headless server with some of my buddies.
Literally after picking up camo, the lobby just go frozen; we couldn't pick up another units or modify them.
