### ISSUE TITLE
[0.43.6] bug: Client-Server communication Out-of-sync issue with poor network route.

### ISSUE THREAD

**Issue by PhoenyxCullen** [MegaMek/megamek#836]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.

### Environment
What version of MegaMek does your issue apply to?  Note whether it is the stand alone MegaMek or HQ's MegaMek.
*0.43.6*

What operating system are you using?  Windows, Mac, or Linux?
*windows*

What java version are you using?  If unsure it will state your java version at the top of the megameklog.txt file.
*Version 8 Update 152*

### Description
Describe the issue and provide screenshots ingame if able.
Provide the rulebook, page number, and text if you feel like this is a rules issue.
And provide the steps you have taken to reproduce the issue in the saved game if applicable.

*During a physical attack stage, somehow my client was disconnected and did not post to the server my lack of a physical attack. I reconnected, and there is a out-of-sync issue between the client and the server (Dwarbit). On mine, it shows waiting on Princess Bot, while on his screen, it's waiting on me. Screenshots are available. During a reload of the save game, the issue resolved on the server's end about my lack of physical attack. Can the network code get a review to help maintain a better connected state or at least report to the client that the connection has dropped? Also, the heapdump (even zipped) is larger than 10MB (137,031 KB).*

### Files
Provide a saved game of when the issue was found.  If possible try to save the game during the phase before the issue occurs so the 
developers can step through the code and find exactly what it is that is breaking in the code.
Provide the megameklog.txt file for any NPE's or errors that MegaMek might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual megameklog.txt file
And provide your playername so that they can load the saved game.

[Dwarbit_Aldaek.7.26.2.sav.gz](https://github.com/MegaMek/megamek/files/1594983/Dwarbit_Aldaek.7.26.2.sav.gz)
![schultza_client_outofsync](https://user-images.githubusercontent.com/33883504/34459244-fd8a7d3a-eda7-11e7-98a4-b2454e1ac85d.png)
![dwarbit_server_screenshot](https://user-images.githubusercontent.com/33883504/34459245-fd9c54f6-eda7-11e7-8079-e49dfeb6ae0a.png)
[megameklog.txt](https://github.com/MegaMek/megamek/files/1594986/megameklog.txt)
[Dwarbit.OutofSink.GameOptions.xml.zip](https://github.com/MegaMek/megamek/files/1594987/Dwarbit.OutofSink.GameOptions.xml.zip)

**Comment by PhoenyxCullen** [comment]
The game was saved from the host's side. Players include:
Dwarbithian Argonauts # the host
schultza's Valhallan Einherjar # me, the client

**Comment by HammerGS** [comment]
NPE from the Log file.

```
java.lang.NullPointerException
	at mekhq.MekHQ.gameVictory(MekHQ.java:506)
	at megamek.common.event.GameVictoryEvent.fireEvent(GameVictoryEvent.java:70)
	at megamek.common.Game.processGameEvent(Game.java:3108)
	at megamek.client.Client.handlePacket(Client.java:1474)
	at megamek.client.Client$1$2.run(Client.java:220)
java.lang.NullPointerException
	at mekhq.MekHQ.gameVictory(MekHQ.java:506)
	at megamek.common.event.GameVictoryEvent.fireEvent(GameVictoryEvent.java:70)
	at megamek.common.Game.processGameEvent(Game.java:3108)
	at megamek.client.Client.handlePacket(Client.java:1474)
	at megamek.client.Client$1$2.run(Client.java:220)
```

**Comment by neoancient** [comment]
The NPE in MekHQ has to do with processing the victory and is unrelated to the issue submitted. There has been some work on the network code since this was submitted, so I'm closing this as out of date.
