### ISSUE TITLE
[43.6 Bug] Mauser IIc and other clan infantry weapons missing in customization

### ISSUE THREAD

**Issue by IReallyHateGithub** [MegaMek/megamek#837]
Tried to configure my elementals and could not locate the Mauser IIC laser rifle for them. Per http://bg.battletech.com/forums/index.php?topic=59867.msg1375993#msg1375993 it looks like the weapon options are defaulting to IS-Only.

**Comment by neoancient** [comment]
It was filtering by the entity's intro year and tech level instead of the game year and tech level. So most Elementals were only seeing what was available as standard tech in 2868.
