### ISSUE TITLE
NPE Princess.calculatePhysicalTurn

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#838]
### Environment
Megamek standalone 0.43.5
Java version 1.8.0_144
Platform Windows 8.1 6.3 (amd64)

### Description
Princess hangs during her physical attack phase.

Line 3,747
> java.lang.NullPointerException
	at megamek.client.bot.princess.Princess.calculatePhysicalTurn(Princess.java:803)
	at megamek.client.bot.BotClient.calculateMyTurn(BotClient.java:460)
	at megamek.client.bot.BotClient.access$000(BotClient.java:83)
	at megamek.client.bot.BotClient$CalculateBotTurn.run(BotClient.java:104)

![github](https://user-images.githubusercontent.com/16950832/34464259-002d3942-ee3e-11e7-8903-0f7f0ea3cca2.png)

### Files
Player Name:  BLOODWOLF
[PhysicalPhase.sav.gz](https://github.com/MegaMek/megamek/files/1595475/PhysicalPhase.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/1595476/megameklog.txt)

**Comment by BLOODWOLF333** [comment]
Duplicate of #255

**Comment by neoancient** [comment]
One thing they both have in common is that they appear to be a result of `Game` not being thread-safe.
