### ISSUE TITLE
Princess limited weapons use

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/megamek#839]
### Environment
MegaMek 0.43.6 via MekHQ
windows 8.1
Java 1.8.0_121

### Description
In an 8 way free for all situation (7 princess bots) princess will only use weapons against player controlled targets.  All of the other princess targets only get considered for melee. 

### Files
Player name: Gladiatoral Retribution
[glitch (2).zip](https://github.com/MegaMek/megamek/files/1596567/glitch.2.zip)

**Comment by NickAragua** [comment]
They all seem to be on "team 0". How did you add all these bots?

**Comment by bczretribution** [comment]
add bot->team dropdown-> selected none-> add combat unit-> set starting location.  

I set them all to none for team as there were only 5 teams and I needed 8.  my player controlled faction should have been team none as well.  They did behave as hostile to each other as can be seen in the game log, just with limited firepower.

**Comment by NickAragua** [comment]
Fixed with PR#849. Bot was treating "no team" as the same team for the purposes of firing weapons.
