### ISSUE TITLE
DropShip to DropShip fire conversion error 0.43.6

### ISSUE THREAD

**Issue by SnyderPhilip** [MegaMek/megamek#840]
I ran a short space battle through MekHQ's instance of MegaMek (not launched from HQ, but the instance that is included in the HQ release).  The reason is was so short was that apparently my Union Class DropShips were equipped with Micro Nuclear Weapons.

When I fired on a Fighter, the LRM bays acted normally.  When I fired on an Avenger Class DropShip, the damage went from 5 damage per cluster against the Lucifer II, to 65 damage per cluster against the Avenger.  Needless to say the DropShip was wrecked instantly.

Weapons fire for Union (2708) (Femme Fatale)
    LRM Bay at Lucifer II LCF-R16K #4 (Princess); needs 7, rolls 7 :  - Glancing Blow - 
        LRM 20 at Lucifer II LCF-R16K #4 (Princess); 
hits.

        Lucifer II LCF-R16K #4 (Princess) takes 5 damage to LWG.
            19 Armor remaining.
            Possible critical hit (Damage threshold exceeded); needs 8, rolls (5+2) = 7 : no effect.

        Lucifer II LCF-R16K #4 (Princess) takes 5 damage to LWG.
            14 Armor remaining.
            Possible critical hit (Damage threshold exceeded); needs 8, rolls (8+2) = 10 : no bombs to destroy.

        Lucifer II LCF-R16K #4 (Princess) takes 2 damage to LWG.
            12 Armor remaining.

        LRM 20 at Lucifer II LCF-R16K #4 (Princess); 
hits.

        Lucifer II LCF-R16K #4 (Princess) takes 5 damage to AFT.
            21 Armor remaining.
            Possible critical hit (Damage threshold exceeded); needs 8, rolls (4+1) = 5 : no effect.

        Lucifer II LCF-R16K #4 (Princess) takes 4 damage to LWG.
            8 Armor remaining.
            Possible critical hit (Damage threshold exceeded); needs 8, rolls (8+1) = 9 : no bombs to destroy.

    LRM Bay at Lucifer II LCF-R16K #4 (Princess); needs 7, rolls 6 : misses

    LRM Bay at Avenger (2816) (Princess); needs 8, rolls 9 : 
        LRM 20 at Avenger (2816) (Princess); 
hits.

        Avenger (2816) (Princess) takes 65 damage to RS.
            138 Armor remaining.
            Possible critical hit (Damage threshold exceeded); needs 8, rolls (9+1) = 10 : An Cargo bay door is destroyed!

        Avenger (2816) (Princess) takes 65 damage to AFT.
            115 Armor remaining.
            Possible critical hit (Damage threshold exceeded); needs 8, rolls (6+1) = 7 : no effect.

        Avenger (2816) (Princess) takes 65 damage to NOS.
            165 Armor remaining.
            Possible critical hit (Damage threshold exceeded); needs 8, rolls (7+1) = 8 : Sensors Hit!

        Avenger (2816) (Princess) takes 13 damage to RS.
            125 Armor remaining.

        LRM 20 at Avenger (2816) (Princess); 
hits.

        Avenger (2816) (Princess) takes 65 damage to RS.
            60 Armor remaining.
            Possible critical hit (Damage threshold exceeded); needs 8, rolls (5+1) = 6 : no effect.

        Avenger (2816) (Princess) takes 65 damage to RS.
            Armor destroyed.
 5 damage transfers to the SI. 19 SI remaining.
            Possible critical hit (Damage threshold exceeded); needs 8, rolls (5+1) = 6 : no effect.
            Possible critical hit (SI damaged); needs 8, rolls (6+1) = 7 : no effect.

        Avenger (2816) (Princess) takes 26 damage to RS.
 26 damage transfers to the SI. 0 SI remaining.
*** Avenger (2816) (Princess) DESTROYED by Structural Integrity Collapse! ***
            Possible critical hit (Damage threshold exceeded); needs 8, rolls (5+1) = 6 : no effect.
            Possible critical hit (SI damaged); needs 8, rolls (8+1) = 9 : No undestroyed transport bay found.
[gamelog.zip](https://github.com/MegaMek/megamek/files/1598248/gamelog.zip)
[megameklog.txt](https://github.com/MegaMek/megamek/files/1598251/megameklog.txt)

**Comment by SnyderPhilip** [comment]
I don't have the log on this one... but this was sent to me by a friend who does a ATB campaign with me, all the same rules.

Weapons fire for Hunter Light Support Tank (LRM15) (Independent (Periphery))
    LRM 15 at Union (2708) (The Flying Dutchmen); needs 5, rolls 7 : 9 missile(s) hit (using Right Side table).
hits.

        Union (2708) (The Flying Dutchmen) takes 45 damage to RS.
            135 Armor remaining.
            Possible critical hit (Damage threshold exceeded); needs 8, rolls 7 : no effect.

        Union (2708) (The Flying Dutchmen) takes 36 damage to RS.
            99 Armor remaining.
            Possible critical hit (Damage threshold exceeded); needs 8, rolls 8 : An Cargo bay door is destroyed!

**Comment by HammerGS** [comment]
You are using the Aero Sanity Mod.  Don't use it. It's known to be extremely buggy and cause all types of issues.

**Comment by sixlettervariables** [comment]
Fixed in #1258.
