### ISSUE TITLE
Feature Request: Ignore Extinction

### ISSUE THREAD

**Issue by Xeno426** [MegaMek/megamek#841]
While it is currently possible to play with blatantly illegal designs should all players agree to it, there's no such way to play with mechs and equipment that are extinct by the game's set time. Since, should everyone involve be fine with it, MegaMek allows me to play a mirror match of a twin-AC/20 Locust, I see no reason a more reasonable allowance for mechs and equipment deemed Extinct (like C3i in 3150) should be disallowed if all parties are consenting.

A simple option like "Ignore Extinction Dates" would be great.

**Comment by repligator** [comment]
Appears to be functioning as requested as of 49.20
