### ISSUE TITLE
[43.6] Cannot Delete Units

### ISSUE THREAD

**Issue by IReallyHateGithub** [MegaMek/megamek#848]
### Environment
What version of MegaMek does your issue apply to?  Note whether it is the stand alone MegaMek or HQ's MegaMek.

43.6

What operating system are you using?  Windows, Mac, or Linux?

Windows 7 Ultimate x64

What java version are you using?  If unsure it will state your java version at the top of the megameklog.txt file.

C:\Users\restless>java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

### Description

I am unable to delete mechs from the lobby.  The only error I see in the logfiles is one relating to my opponent disconnecting because his client froze up. 

### Files
[MMClientlog.txt](https://github.com/MegaMek/megamek/files/1609116/MMClientlog.txt)
[megameklog.txt](https://github.com/MegaMek/megamek/files/1609117/megameklog.txt)

**Comment by neoancient** [comment]
The error in the log file shows this to be the same issue as #834, which was fixed with 2561595.
