### ISSUE TITLE
Designate Artillery Auto-Hit Targets Phase Does Not Advance

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#855]
### Environment
MegaMek 0.43.7-betaJan2
Java version 1.8.0_151
Platform Windows 7 6.1 (x86)

### Description
After designating the auto-hit arty hexes and clicking done the button greys out but the phase does not advance.  Have to /reset and remove the arty units or just turn off the auto-hit rule to play a game.

![image](https://user-images.githubusercontent.com/16950832/34840135-a9750e56-f6c9-11e7-9dc2-7a2f2ca5749c.png)

Line 1228 of log:

> ERROR: GameReports.get() was asked for reports of a round [1] which it does not posses.
java.lang.RuntimeException: ERROR: GameReports.get() was asked for reports of a round [1] which it does not posses.
	at megamek.common.GameReports.get(GameReports.java:65)
	at megamek.common.Game.getReports(Game.java:2722)

### Files
Player Name: Princess
[ArtyDesignatePrincess.sav.gz](https://github.com/MegaMek/megamek/files/1623679/ArtyDesignatePrincess.sav.gz)

[megameklog.txt](https://github.com/MegaMek/megamek/files/1623682/megameklog.txt)

**Comment by NickAragua** [comment]
I haven't been able to reproduce this with a fresh game using off-board artillery. I suspect it was fixed after the beta, but will leave it open for confirmation.

**Comment by BLOODWOLF333** [comment]
If it makes a difference we were using on-board artillery in the saved game.

**Comment by NickAragua** [comment]
Just checked on-board as well, no dice on repro.

**Comment by NickAragua** [comment]
Gonna close it, then.
