### ISSUE TITLE
-1 For Infantry Entering A Mud Hex

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#856]
### Environment
MegaMek 0.43.7-betaJan2
Windows 8.1
Java 1.8

### Description
![image](https://user-images.githubusercontent.com/16950832/34852353-d2fd90e8-f6f3-11e7-90e4-210d092456d0.png)

According to http://bg.battletech.com/forums/index.php?topic=60088.0 the -1 for entering a mud hex should not apply to an infantry's 4+ to avoid getting stuck.  (Thinks those messages shouldn't even really show for infantry moving into these terrain types).

### Files
Player Name: BLOODWOLF
[OASPA.sav.gz](https://github.com/MegaMek/megamek/files/1624476/OASPA.sav.gz)

**Comment by NickAragua** [comment]
Should be implemented.
