### ISSUE TITLE
MissileWeaponHandler NPE

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#863]
### Environment
MegaMek 0.43.7-betaJan2 Standalone
Java version 1.8.0_144
Platform Windows 8.1 6.3 (amd64)

### Description
Not sure which missile ammo type I used that caused the NPE but, allowed me to fire all the weapons on every eligible unit and click done.  But then would not advance the phase.  /skip failed to function and caused it's own NPE on line 3,518 of the log.

Line 3,488:
`Exception in thread "Packet Pump" java.lang.NullPointerException
	at megamek.common.weapons.MissileWeaponHandler.isNemesisConfusable(MissileWeaponHandler.java:1107)
	at megamek.common.weapons.MissileWeaponHandler.handle(MissileWeaponHandler.java:750)
	at megamek.server.Server.handleAttacks(Server.java:36153)
	at megamek.server.Server.handleAttacks(Server.java:36082)
	at megamek.server.Server.endCurrentPhase(Server.java:3105)
	at megamek.server.Server.changeToNextTurn(Server.java:3430)
	at megamek.server.Server.endCurrentTurn(Server.java:2457)
	at megamek.server.Server.receiveAttack(Server.java:13723)
	at megamek.server.Server.handle(Server.java:31883)
	at megamek.server.Server$PacketPump.run(Server.java:368)
	at java.lang.Thread.run(Unknown Source)`

### Files
Player Name:  BLOODWOLF
[MissileHandler.sav.gz](https://github.com/MegaMek/megamek/files/1629018/MissileHandler.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/1629020/megameklog.txt)

**Comment by BLOODWOLF333** [comment]
Im not sure if any of the other guys were using this warship but could this NPE have to do with the equipment naming issues?

>     Loading from zip file >> JHS Terra/Naga Caspar II Control Ship.blk
      Failed to load equipment: White Shark
      Failed to load equipment: White Shark

**Comment by mkerensky** [comment]
This can be assigned to me.  It is probably an issue with a fighter squadron - Nemesis pods are a NARC special ammo, and no warships that I know of have Narc.  Also, warships should never be using MissileWeaponHandler. They use MissileBayWeaponHandler instead, or CapitalMissileBayWeaponHandler for White Shark missiles.

Looking at this again, I suspect a fighter squadron tried to fire a narc pod at the warship, and I didn't write any code to deal with narc when I was working on large craft AMS.  I do think the Naga CASPAR II has AMS/point defense bays.

**Comment by mkerensky** [comment]
The savegame is unloadable in 0.43.8-RC2.  I tried to set up a new game and recreate the issue using aeros equipped with Narc vs a dropship, but I didn't get an NPE from that. 

There is a minor bug in narc handling by AMS.  Reports state that AMS shoots down all incoming missiles when you fire a narc, since it has an AV of 0, but the pod still gets attached.
Aeros can't load narc-capable missiles, so the narc pod doesn't do anything, but I do need to fix that report.

**Comment by BLOODWOLF333** [comment]
I cant load it either
[megameklog.txt](https://github.com/MegaMek/megamek/files/1662413/megameklog.txt)

Will reload with 0.43.7-betaJan2 of Megamek and figure out what unit has the iNARC.

**Comment by BLOODWOLF333** [comment]
None of the dropships, warships, or fighter squadrons have iNarc in any of the three forces in the saved game.  One unit has Artemis IV FCS but, I see no Nemesis or Narc pods on any unit.

The (0)'s seem very odd to me.
![image](https://user-images.githubusercontent.com/16950832/35369253-c3cd9ac4-014c-11e8-94b1-17503b82833c.png)

The Thunderbirds are the ones with the LRM20's and they all have ammo and no Narc pods so, I got nothing.
![image](https://user-images.githubusercontent.com/16950832/35369311-fd1a0e98-014c-11e8-884d-e8a380387dd9.png)

**Comment by BLOODWOLF333** [comment]
loaded all three muls in the megamek lobby and went through every single one in the configure unit window and no one has any units with iNarc....this makes no sense and am at a lost on what more to do.

**Comment by mkerensky** [comment]
Just need to do some testing with these MULs and try to reproduce the NPE.  It happens when something fires missiles. I'll see if I can do that.

**Comment by mkerensky** [comment]
This may very well be your version.  I looked back at the log of your issue and I see that it happens at line 1107 of MissileWeaponHandler.  MissileWeaponHandler no longer HAS a line 1107, so your version probably came out before my consolidation of large craft AMS got merged.  isNemesisConfusible  is now roughly 100 lines back, starting at 1002.

**Comment by neoancient** [comment]
@mkerensky The code that generated the error is still there. You will need to check out an older version from the repository to work on this.

**Comment by mkerensky** [comment]
Found the old copy of the handler.   Line 1107 is  AmmoType atype = (AmmoType) ammo.getType();   so something had a null ammo type.  That might be happening intermittently with fighter squadrons, but I couldn't reproduce the issue reliably with the current version.  An NPE related to squadron damage/reloading weapons with an empty ammo slot from a new one that used to be very common seems to be gone.

**Comment by mkerensky** [comment]
Also trying to fire a weapon with (0) remaining due to damage no longer causes an NPE, which is awesome.

**Comment by BLOODWOLF333** [comment]
I get different errors when i attempt to click done after loading the save in 0.43.7-betaJan2 Megamek.

`Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at megamek.client.ui.swing.FiringDisplay.clear(FiringDisplay.java:2433)
	at megamek.client.ui.swing.FiringDisplay$19.performAction(FiringDisplay.java:674)
	at megamek.client.ui.swing.util.MegaMekController.dispatchKeyEvent(MegaMekController.java:140)`

[megameklog.txt](https://github.com/MegaMek/megamek/files/1666265/megameklog.txt)

**Comment by mkerensky** [comment]
Since I can't reproduce the issue reliably, I'm going to have to bump this to lower priority and keep an eye on it.  If it happens again with a different version, don't hesitate to post additional logs, and a save (which perhaps I'll be able to load successfully this time). 

I haven't played one of my big space battles in my own campaign since I started programming, but I plan to start it back up once we hit the new stable. If I can find one of these issues in a game, it will help a lot.

**Comment by BLOODWOLF333** [comment]
Verified that this is fixed tonight.  Point defense operates and adds the +1 TH when missiles are fired at a unit.  And the phases advance.  Closing.
