### ISSUE TITLE
[43.7 Beta] Graphical glitching NPEs

### ISSUE THREAD

**Issue by IReallyHateGithub** [MegaMek/megamek#865]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.

### Environment
What version of MegaMek does your issue apply to?  Note whether it is the stand alone MegaMek or HQ's MegaMek.
What operating system are you using?  Windows, Mac, or Linux?
What java version are you using?  If unsure it will state your java version at the top of the megameklog.txt file.

 This is using MegaMek 43.7Beta (Jan 3rd) from Bloodwolf, on both Windows 7 and Windows 10, with 
C:\Users\Restless>java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

### Description
Describe the issue and provide screenshots ingame if able.
Provide the rulebook, page number, and text if you feel like this is a rules issue.
And provide the steps you have taken to reproduce the issue in the saved game if applicable.

Buttons and mech display/chatbox/minimap elements present draw errors, going blank/disappearing. there are some gui and tooltip related errors in the log files. Seems to come up more often if my zoom level changes.

### Files
Provide a saved game of when the issue was found.  If possible try to save the game during the phase before the issue occurs so the 
developers can step through the code and find exactly what it is that is breaking in the code.
Provide the megameklog.txt file for any NPE's or errors that MegaMek might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual megameklog.txt file
And provide your playername so that they can load the saved game.

[MMClientlog.txt](https://github.com/MegaMek/megamek/files/1633115/MMClientlog.txt)
[megameklog.txt](https://github.com/MegaMek/megamek/files/1633116/megameklog.txt)

**Comment by BLOODWOLF333** [comment]
Got a saved game for all the:
`15:57:43,446 ERROR [megamek.common.pathfinder.LongestPathFinder] {Princess-precognition (Princess)} 
Entity invalid.
java.lang.IllegalArgumentException: Entity invalid.
	at megamek.common.Compute.isPilotingSkillNeeded(Compute.java:455)
	at megamek.common.MovePath.addStep(MovePath.java:474)
	at megamek.common.MovePath.addStep(MovePath.java:255)
	at megamek.common.MovePath.addStep(MovePath.java:167)`
errors with princess?

**Comment by IReallyHateGithub** [comment]
game is in progress actually. attaching a savegame.

[autosave.sav.gz](https://github.com/MegaMek/megamek/files/1633135/autosave.sav.gz)

**Comment by IReallyHateGithub** [comment]
additional information, the problem seems to go away when Client Settings "Show Map Hex Popup" is disabled.

**Comment by BLOODWOLF333** [comment]
#797 is that similar to what you saw?

**Comment by BLOODWOLF333** [comment]
> Make sure that this line is in your MegaMek.l4j file:

Code: [Select]
-Dsun.java2d.d3d=false

That has solved all my graphical glitching.

Or the .bat file for Linux.  Did this fix your issue?

**Comment by IReallyHateGithub** [comment]
Yes, I just finished running a test battle with that added to the batch file I use to launch (I use the .jar download) and it appears to be resolved.
