### ISSUE TITLE
[43.7] GameReports.get() was asked for reports of a round [1] which it does not posses.

### ISSUE THREAD

**Issue by IReallyHateGithub** [MegaMek/megamek#871]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.

### Environment
What version of MegaMek does your issue apply to?  Note whether it is the stand alone MegaMek or HQ's MegaMek.
What operating system are you using?  Windows, Mac, or Linux?
What java version are you using?  If unsure it will state your java version at the top of the megameklog.txt file.

Bloodwolf's 43.7Beta(Jan3), Windows, java 1.8.0_151

### Description
Describe the issue and provide screenshots ingame if able.
Provide the rulebook, page number, and text if you feel like this is a rules issue.
And provide the steps you have taken to reproduce the issue in the saved game if applicable.

Placing Artillery-autohit hexes for a largescale battle, finish placement and hit done, game refuses to proceed. Error in MegaMeklog.txt

### Files
Provide a saved game of when the issue was found.  If possible try to save the game during the phase before the issue occurs so the 
developers can step through the code and find exactly what it is that is breaking in the code.
Provide the megameklog.txt file for any NPE's or errors that MegaMek might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual megameklog.txt file
And provide your playername so that they can load the saved game.

Log
[megameklog.txt](https://github.com/MegaMek/megamek/files/1648452/megameklog.txt)

Saved after error
[GameReports.sav.gz](https://github.com/MegaMek/megamek/files/1648453/GameReports.sav.gz)

Hopefully saved before error
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/1648454/autosave.sav.gz)

Player names were Restless and OpFor

**Comment by NickAragua** [comment]
I'm seeing an error in the log that's related to an issue that prevents the player from progressing past the artillery phase that was fixed between the january 3rd beta and the january 14th beta. While this particular save game is going to be unrecoverable, the issue should no longer occur as of the jan 14th beta.

**Comment by neoancient** [comment]
Closing as resolved.
