### ISSUE TITLE
Over Verbose Princess

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#875]
### Environment
MegaMek 0.43.7-betaJan14 Standalone
Java version 1.8.0_144
Platform Windows 8.1 6.3 (amd64)

### Description
#808 I deleted the clientsettings.xml that I have been carrying over to each new version and used a new extracted from the zip xml and this concern is still present. With princess filling up the chat with her progress calculating her move when her verbose setting is on Off.

![image](https://user-images.githubusercontent.com/16950832/35190370-47553a3a-fe25-11e7-8275-e9fb2898a8b5.png)

![image](https://user-images.githubusercontent.com/16950832/35190372-50988af2-fe25-11e7-9798-d2b477ee1364.png)

### Files
[VerbosePrincess.sav.gz](https://github.com/MegaMek/megamek/files/1649481/VerbosePrincess.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/1649482/megameklog.txt)

**Comment by dericpage** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/12e59f189b1ad63867faf4823e2ef8ab2fa9c155.
