### ISSUE TITLE
BV Increasing Over 100% Suspect C3

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#889]
### Environment
Megamek 0.43.8-RC2 (MekHQ)
Java version 1.8.0_144
Platform Windows 8.1 6.3 (amd64)

### Description
Using the megamek.jar of the current state of megamek my BV is over 100% and I suspect it is because of my two dropships having C3.  When hovering the cursor over my other units it shows that their BV has been increased for some reason.  Obvious and I are both using squadrons and only thing unique about my force is the two dropships with C3 that I can come up with as to why the BV is over 100% (I also have nukes as well).  In my betaJan2 version of megamek I did not see this behavior with it going over 100%.

![github](https://user-images.githubusercontent.com/16950832/35469000-f9443000-02f0-11e8-925b-0690f431ca05.png)

![image](https://user-images.githubusercontent.com/16950832/35469005-075d69c2-02f1-11e8-985e-07885245dbe9.png)

### Files
[megameklog.txt](https://github.com/MegaMek/megamek/files/1669796/megameklog.txt)
[BVIncrease.sav.gz](https://github.com/MegaMek/megamek/files/1669799/BVIncrease.sav.gz)
Player Name: BLOODWOLF
[MUL.zip](https://github.com/MegaMek/megamek/files/1669800/MUL.zip)

**Comment by mkerensky** [comment]
I did not code any BV for Naval C3, so that might be it.  Also, I understand nuclear warheads were in use this game as alternate capital munitions. I did code an arbitrary high BV for those, as IO states that they inherently break the BV system.

**Comment by BLOODWOLF333** [comment]
well thats fine but, could it be made to consider 100% the actual BV the unit is while in the lobby with nukes and not have it read over 100% once you get into the game.  and if nukes is the case then should only increase the BV of my warship and not every unit on my like which is what was occurring.

**Comment by mkerensky** [comment]
It seems to be nukes, and only those mounted on warships.   I can recreate the issue with your MUL and save, and I can get the BV to change with new adds when altering start munitions, though not enough to change the BV percentage. 

I'm tempted to leave this one be until neo is done with warship construction and verification rules.

**Comment by mkerensky** [comment]
So...   entity.setInitialBV  is returning a different value from entity.calculateBattleValue   in your savegame and MUL.    Your MUL has pre-existing damage, which includes movement values that are way off.  The McKenna is showing as 1/1 where it should be 3/5,  the dropships 0/0 when they should each be 3/5, etc.  That's what is lowering your BV below the values it should have. I can't duplicate this when I add new units of the same type and tweak them, so I really don't know how you managed to get that effect.  I don't see any pre-existing damage (ie engine damage)  except armor values - in the savegame, your units have the correct movement values (that's where you get the higher percentage, currentBV / (lower initialBV).

I would think we can safely close this issue.

**Comment by Dylan-M** [comment]
Per the discussion, I'm going to close this. If it happens again with MULs saved from the same version then please open a new issue.
