### ISSUE TITLE
Bug: Fatigue is not calculated correctly for Infantry

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/megamek#894]
Infantry do not have a "Piloting" skill so Fatigue is being calculated incorrectly.

Pursuant to this post on BT Game Questions
http://bg.battletech.com/forums/index.php?topic=60067.0

Quoting Hammer on Slack
hammer-developer [12:28 PM]
Going with lowest of either gunnery or AM skill
scjazz [12:29 PM]
right, which is why the proposed change will be to use gunnery for Fatigue, and Gunnery or Anti-Mek whichever is lower for CO <<<< this?

Fix: Use Gunnery skill to determine Fatigue level of Infantry.

**Comment by SJuliez** [comment]
I looked into this. Fatigue is computed in `Crew`. `Crew `doesn't know if it is an Infantry. It shares the `CrewType `"CREW" with Tanks. I couldn't see a non-hack way to find out the type of Entity within `Crew`. 

So, options I see are:
- Find how to check for Infantry within `Crew`
- Infantry gets its own `CrewType`
- `Crew `learns the entity type as a class field
- Handling fatigue gets moved up to `Entity`

I'd prefer adding a CrewType if no easier way is there. Any opinions?

**Comment by scJazz2** [comment]
just going to toss these $0.02 in...

Battle Armor are covered by this rule change as they are "Infantry" and also do not have a piloting skill. I do not know the code by this fact might inform your choice of fixes.
