### ISSUE TITLE
WKT-2S Wildkatze

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/megamek#9]
This variant fighter is referenced in the upcoming FM-3145 RATs.  It is a canon unit, but doesn't seem to have a published record sheet (I presume this is why it isn't already coded into MM).  I read the fluff and attempted to create a faithful representation. 
[Wildkatze WKT-2S.zip](https://github.com/MegaMek/megamek/files/104195/Wildkatze.WKT-2S.zip)

**Comment by HammerGS** [comment]
Commit 1cabaca
