### ISSUE TITLE
Request Program To Remember Sizing & Position Of All Windows

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#901]
Mainly just a reminder from past discussions (mainly about the RAT generator window) for the program to remember the location and size the user adjusted them to like how the mini map, unit display, and main megamek display currently behaves.  Possible stop gap for coming up with a standard resolution that windows should be sized to?

And may be a bug or possibly is related to this but have observed the configure unit window will appear in different areas of the screen while in the megamek lobby and is a little annoying.  Have had scjazz verify the behavior on his machine as well.

![image](https://user-images.githubusercontent.com/16950832/36082039-9adbaeda-0f6b-11e8-8dd2-e68e5179a47b.png)

![image](https://user-images.githubusercontent.com/16950832/36082041-aad888a8-0f6b-11e8-8b8f-a3c4cf3dc044.png)

This is with just right clicking units and clicking configure unit without moving the window any.  Thats just where they are starting out at on my machine depending the unit type it seems like.

**Comment by Dylan-M** [comment]
@BLOODWOLF333 Remembering the location, size, and shape won't help with this issue, because you still won't be able to resize it past it's defined minimum size. But yes, it is definitely something that needs done for all of the dialogs.

**Comment by repligator** [comment]
Appears to be working as requested as of 49.20
