### ISSUE TITLE
Incorrect heat for Prototype Rocket Launcher 15

### ISSUE THREAD

**Issue by blah2355** [MegaMek/megamek#906]
### Environment
MegaMek (and MegaMekLab) 0.43.8-RC2
Windows
Java version 1.8.0_161

### Description
The heat in MegaMek and MegaMekLab for the Prototype Rocket Launcher 15 is 5 heat, when it should be 4 according to Interstellar Operations p. 216.

**Comment by HammerGS** [comment]
Fixed here - https://github.com/MegaMek/megamek/commit/9a5a8553ee9501da1f38a5198c1355f70931b906
