### ISSUE TITLE
MM gives back wrong bark on ammo crit for new energy weapon turrets

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#907]
![image](https://user-images.githubusercontent.com/19868605/36278216-24e83826-1261-11e8-8d1e-610b3ab9fce7.png)

Weapons fire for Phoenix Hawk PXH-1 #2 (The Infamous Dust)
    Large Laser at Hex 3733 of Building #1876667794 (Collapse)needs 4, rolls 8 : hits.

        Medium Standard Building #1876667794 absorbs 8 points of damage. 
            42 CF remaining.
        Damage threshold exceeded. Possible critical hit!
            Ammunition explosion! Building #1876667794 takes 0 damage, reducing its CF to 42.

Turret bark should be "luckily there is no ammo to explode." IIRC. Guess they need a minor update to account for the new turrets. 

side note: should this crit have been re-rolled since energy weapon turrets have no ammo? I'm unsure. 

v 43.8

**Comment by NickAragua** [comment]
Per tac ops page 120, a crit on non-existent building equipment has no effect. So, no reroll. However, the message should definitely be adjusted.

**Comment by the-real-grinny** [comment]
I'm going to try and fix this as a first issue. Let's see how this goes.
