### ISSUE TITLE
Aero Targeting: Still a bit off

### ISSUE THREAD

**Issue by TigerShark** [MegaMek/megamek#91]
I've noticed that you are able to click on the flight path to pull a To-Hit for the closest point, but you are not able to click on other areas of the flight path to recalculate.

Example: A flight path is 2 hexes from my Vehicle, giving me a distance of 12 and a Side location. But if I click another 2 hexes down the path, I should be targeting their Aft. The latter part isn't functioning.

**Comment by beerockxs** [comment]
As far as I understand the rules, to-Hit is always calculated against the closest point of the flight path.

**Comment by arlith** [comment]
Could you attach a saved game with this setup?  It would be easier to help understand the situation.

**Comment by arlith** [comment]
There are cases where there are two locations along the flightpath that are equidistant.  In this case, the attacker gets a choice.  I presume this may be what @TigerShark is referring to.  In this case, MM does allow the user to click either of the hexes, and it will target them.  It should highlight the targeted hex in teal.  

This is why having a saved game can make discussion easier.  Or at the very least, a screenshot, but a saved game would be easiest.

**Comment by TigerShark** [comment]
I will grab one once I'm at home. And I'll check the errata. This may be a failing of mine to understand the rules-as-written. Thanks, guys!

**Comment by TigerShark** [comment]
http://bg.battletech.com/forums/index.php?topic=51768.msg1194712#msg1194712

Asked this question of the developers. According to the errata, the current rules are working as-written.

**Comment by arlith** [comment]
I suspect that the answer is going to be "no" but we'll see.  In the meantime, I'm going to mark this issue as pending, since there's nothing we can do until a response come back.

**Comment by HammerGS** [comment]
Errata answered and per Arlith closing this.

http://bg.battletech.com/forums/index.php?topic=51768.0
