### ISSUE TITLE
Feature Request: Flamer Heat&Damage Unofficial Option

### ISSUE THREAD

**Issue by Retry2000** [MegaMek/megamek#911]
Currently, an option exists that is checked by default under basic options called "Flamers can deal heat instead of damage".  This gives Flamers some additional utility, however, players still may find the flamer and its variants lacking.

A second option under this option could be introduced which allows Flamer variants (Flamer, ER Flamer, Vehicle Flamer & Heavy Flamer) to inflict both heat _and_ damage instead of either heat _or_ damage, similar to how the Plasma Rifle works.  For instance, a flamer that targets (and hits) a heat-tracking unit like a Battlemech would deal 2 damage to an armor location & raise the battlemech's heat production by 2 points as well, instead of simply dealing 2 damage OR 2 heat.

It'd be a fairly simple, nice option to boost the utility of flamers and flamer-carrying units like the Firestarter.

**Comment by TigerShark** [comment]
This is in the BattleMech Manual as an official, optional rule. Heat and damage are produced simultaneously in the text.

**Comment by TigerShark** [comment]
Enhanced Flamers (Optional): If using this optional rule,
whenever a flamer of any kind strikes a target that tracks heat (such
as a ’Mech), apply both the flamer’s heat and damage to the target.

Page 99

**Comment by binaryspica** [comment]
It would be a good addition I think. Normally flamers are deals lesser damage than its heat despite it is a point-blank range weapon.

**Comment by TigerShark** [comment]
Any word on this one?

**Comment by sixlettervariables** [comment]
None of the core developers have picked this up yet. I'll mark it as help wanted.

**Comment by TigerShark** [comment]
This should probably be changed to an "official option," as this is in no way a house rule.

**Comment by NickAragua** [comment]
The rule in BMM p. 99 has been implemented and will be out in the next release, although it doesn't really help flamers that much. ;)
