### ISSUE TITLE
[.43.8 RC2] Bridge has a basement for some reason

### ISSUE THREAD

**Issue by NickAragua** [MegaMek/megamek#913]
When a fully amphibious prowler goes under a specific bridge section on the Archipelago map, it triggers a "basement". Whoops!

Save game attached. Send the Prowler under the bridge in hex 0309. Note that this isn't a problem with a boat or a hovercraft.

This is more of a reminder for myself than anything else, as I discovered it while enabling the prowler and other "fully amphibious" vehicles to cross water.

[bridge_oops.sav.gz](https://github.com/MegaMek/megamek/files/1765587/bridge_oops.sav.gz)

**Comment by mkerensky** [comment]
You mean to tell us that this isn't the secret underwater HQ of Section 7?

**Comment by NickAragua** [comment]
Shhhhh! :D

**Comment by Dylan-M** [comment]
Couple thoughts here:

- Are bridges considered a building? (I don't recall offhand)
- Are you using random basements?
- Is this one of the maps someone thought it would be great to add basements to every building, even when it wasn't built with them?
- Have you tested other bridges with maps? Cause if it's from the generation of basements on every building, that was done to a _lot_ of maps, and will likely affect more.
