### ISSUE TITLE
41.15 : Canon units being flagged as invalid designs

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#92]
A lot of canon units seem to be flagged as invalid designs in megamek, but MML's unit validation shows no problems...

[megameklog.txt](https://github.com/MegaMek/megamek/files/183071/megameklog.txt)
![megamek](https://cloud.githubusercontent.com/assets/1191378/13933588/10bb8642-f002-11e5-84f6-fd279e720864.jpg)

**Comment by Dylan-M** [comment]
This is a known issue, and I thought there was an existing bug report about it. However, I cannot find said bug report at this time... @arlith?

**Comment by HammerGS** [comment]
Should be this one...

https://sourceforge.net/p/megamek/bugs/4671/

**Comment by Dylan-M** [comment]
That'd be it. I'm still at work, so someone on the team should close that SF one in favor of this GH one as our policy thus far has been to favor GH duplicates over the SF versions and just link back.

**Comment by Question2** [comment]
Oh ok. Are you guys still keeping track of the existing bug tickets on sourceforge? In other words, if the bug ticket is already on sourceforge and still open, we don't need to make a copy here?

**Comment by Dylan-M** [comment]
Correct. SF isn't abandoned by us, just relegated to backup.

**Comment by VictorMorson** [comment]
Yep sorry about not realizing that myself earlier.  I've wanted to see infantry inside of buildings fixed for a while (I remember ages ago it worked properly) and rebugged it recently; didn't realize it was still open on the other tracker.

**Comment by arlith** [comment]
I commented out the code that checks for engine, cockpit and gyro tech levels in fa9190d.  This basically goes back to how things were in the past.  The failing units won't be marked as failures for now, but we will need to figure out how we're going to handle this and implement a real fix in the future.  I'm going to close this issue for now.
