### ISSUE TITLE
Map Editor - Selecting Terrain Features

### ISSUE THREAD

**Issue by jayof9s** [MegaMek/megamek#920]
### Environment
0.43.8-RC2
Windows7
Most recent java8

### Description
When you have terrain types in the Terrain window, you can no longer select them (single or double click) and have the dropdown below update so you can easily change.

I.e. I copy a building from the map and want to change the elevation, CF, and building type. I now have to dig into the drop down for each to make updates. In the past I used to just be able to click on Building and the drop down would automatically change to 'Building' and fill in the current value.

Currently if I double click, it will carry the current value down but leave whatever the previous selection is for the dropdown.

See the example screenshot. I clicked 'Building' in the window and it added the value to "Arms".

![why](https://user-images.githubusercontent.com/13820640/37215997-9c32f22c-2387-11e8-8f4a-d32ea2341aaf.png)

**Comment by SJuliez** [comment]
This should be fixed (and look somewhat differently) with pull request #918 (including #796)

**Comment by SimonLandmine** [comment]
This one still seems to be an issue, as of Stable 0.46, Development 0.47.1
