### ISSUE TITLE
[0.43.8-RC2] shooting trough Heavy Forest

### ISSUE THREAD

**Issue by seem8** [MegaMek/megamek#925]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.

### Environment
MegaMek-0.43.8-RC2, Linux, Java 1.8.0_151

### Description
In Round 4 Mithras Light Tank was able to shoot trough Heavy Forest

### Files
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/1799871/autosave.sav.gz)
I am attaching autosave. My player name is SeeM.

**Comment by neoancient** [comment]
Heavy forest does not block line of sight unless there is at least one other intervening woods hex

**Comment by seem8** [comment]
thanks
