### ISSUE TITLE
[0.43.8-RC2] two critical chance rolls after one PPC hit

### ISSUE THREAD

**Issue by seem8** [MegaMek/megamek#926]
### Environment
MegaMek 0.43.8-RC2, Linux Java 1.8.0_151"

### Description
In round 7 Piranha takes damage in center torso and makes 2 critical rolls.

### Files
I am attaching autosave and my player name is SeeM.
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/1799870/autosave.sav.gz)

**Comment by neoancient** [comment]
A single hit can result in as many as three critical hits.

**Comment by seem8** [comment]
thanks
