### ISSUE TITLE
Feature Request: NARCed target indicator

### ISSUE THREAD

**Issue by SnyderPhilip** [MegaMek/megamek#929]
I like ATB because it puts me in units I wouldn't otherwise choose, and in this campaign I find myself in a KTO-19 Kintaro.  I don't usually find the NARC all that useful unless its the iNarc and even then only in limited circumstances.  But since I have it, and have to use it, I noticed that there is no indicator on the main board of what targets have been NARCed, forcing me to go back through the round report to find which units I've hit with the NARC.

I would suggest something simple like an N at the bottom of the unit icon, along with perhaps a mention of it on the Unit Status Card.

**Comment by Tecmes** [comment]
What happened with this request? It would be cool...

**Comment by sixlettervariables** [comment]
If there isn't a developer assigned, nothing.
