### ISSUE TITLE
Unofficial rule : AMS may fire more than once per round

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#93]
Currently AMS only fires once per round which makes it pretty ineffective at stopping incoming missile fire considering that it weighs 1.5 tons for the AMS + ammo (or 1 ton for the clan version). It is also almost impossible to use up 1 ton's worth of ammo (especially for the clan version) and there is no benefit to adding extra AMS ammo to a design.

Stratops page 97 has an optional rule where AMS may be used to fire multiple times per round, generating heat each time, up to a maximum of once per attack. For example if a ship with 4 AMS had 4 LRM-20s fired at it, the 4 AMS could fire up to 4 times, once against each LRM-20. Under normal rules, a mech with a AMS would only be able to fire it's AMS once a round, even if 4 LRM-20s hit it that round.

To encourage players to make more use of AMS and AMS ammo in their designs, I would like to suggest an unofficial rule where AMS can fire more than once per round similar to the strat ops rule. 

Essentially : 

-With the optional rule active, AMS would automatically fire more than once per round, once per missile attack until it runs out of ammo

-AMS would only fire a maximum of once if doing so would put the unit above it's heat threshold (similar to strat ops)

E.G. With the unofficial rule, a mech with an AMS is attacked by 4 LRM-20s. The AMS fires 4 times, generating 4 heat total. If the mech had moved/fired weapons so that it was at heat capacity before the AMS fires, the AMS would only fire once.

To address the issue of units mounting multiple AMS, perhaps each additional AMS would inflict an additional penalty to the cluster hit table? Under strat ops, this isn't a problem as AMS inflict a set amount of damage and capital scale missiles require multiple AMS hits to destroy, but this works differently for standard play.

**Comment by Dylan-M** [comment]
Umm, the SO rule should already be in, and affect all unit types. Why would we make an unofficial rule to do the same thing?!

@arlith @HammerGS ??

**Comment by pheonixstorm** [comment]
Sounds like the SO rule does not affect ground units only dropships and the like. So this request just makes the SO optional rules available to mechs which is not the case currently.

**Comment by Question2** [comment]
Sorry if this is not clear, i'm referring to standard play (ground combat on the ground map) where AMS only fires once per round only. I can't find any mention of the strat ops advanced point defense rule in the game options nor can i get it to work for ground units on the ground map.

**Comment by mkerensky** [comment]
I requested SO Advanced AMS/Point Defense functionality in GH#8 in January, as a repeat from a report on Sourceforge. I was told it's just not implemented yet, which is why you wouldn't see the option in the current version.

**Comment by mkerensky** [comment]
I have implemented the stratops rule. It will be available in Dev release 0.43.5.  Only large spacecraft (dropships and up) that have AMS bays can fire multiple times per round. The implementation adds more AMS functionality all around - ground units and fighters with AMS can shoot down Arrow IV homing missiles, AAA, LAA, AS and ASEW missiles. Dropships and up can shoot down everything from LRM5s to capital missile bay attacks per the SO rule.   I did NOT add unofficial functionality for ground units with single ams to fire them multiple times per round, since that's expressly against the rules. I'll admit that a mech with 1 AMS isn't all that great for the weight consumed, but it is nice to have if you shoot it with thunderbolt missiles or arrow IVs...

**Comment by Question2** [comment]
Well, yes, its expressly against the rules, then again every unofficial rule is. I was hoping an unofficial rule like that would make AMS more useful and since it would be an unofficial rule, players could keep it toggled off if they wanted it.

**Comment by mkerensky** [comment]
Gotcha.  I don't mind putting it in my queue to add, but it will be in my low-priority list and might be quite a while in development.

**Comment by Question2** [comment]
Oh thats okay, thanks a lot for adding it to your queue.

**Comment by mkerensky** [comment]
I may be able to get to this soon.  I will add as something of a warning that if your unit has multiple AMS, like the Thor D, the code is going to tend to overuse one of them and only let the other one play if the first is out of arc/destroyed/etc.  Those units are somewhat rare, so I doubt it will be a big deal.

**Comment by mkerensky** [comment]
A PR implementing this has been created. You should see it in the next version or so.

**Comment by NickAragua** [comment]
This has been implemented.
