### ISSUE TITLE
0.43.8-RC2 - Support Particle Cannons vastly overweight

### ISSUE THREAD

**Issue by Flibjib** [MegaMek/megamek#934]
Environment

0.43.8-RC2
MacOS 10.12.6
Jave vers. 1.8.0_65

Description

As I was looking through my cargo capacity, and warehouse contents, I noticed that support particle cannons are looking **heavy**. They are supposed to weigh 1800kg, not 1800 tons.

<img width="1050" alt="screen shot 2018-03-13 at 10 41 47 am" src="https://user-images.githubusercontent.com/32344358/37352943-b4ade9da-26b4-11e8-8de8-37459feb34aa.png">

### Files
[customs.zip](https://github.com/MegaMek/megamek/files/1807644/customs.zip)
[Wolven Winter30461026.cpnx.zip](https://github.com/MegaMek/megamek/files/1807645/Wolven.Winter30461026.cpnx.zip)
[megameklog.txt](https://github.com/MegaMek/megamek/files/1807646/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/1807647/mekhqlog.txt)

**Comment by HammerGS** [comment]
I've got a fix for this, but won't be able to commit for a bit.

**Comment by pheonixstorm** [comment]
@HammerGS did this ever get fixed?

**Comment by HammerGS** [comment]
Fixed with https://github.com/MegaMek/megamek/commit/34ff14d13a74ae71e3b65f6e0f99fa56ea76e9b0
