### ISSUE TITLE
[43.9 RC3] Shaky Stick SPA applied to air-to-air attacks

### ISSUE THREAD

**Issue by NickAragua** [MegaMek/megamek#942]
The Shaky Stick SPA is incorrectly applied to attacks by aircraft against aircraft, whereas it should only apply to anti-aircraft fire from ground units.

To reproduce, give an opponent an airborne unit (conventional fighter, ASF, etc), and configure the pilot to have the Shaky Stick special pilot ability. And yourself one as well.

Attempt to fire on the enemy airborne unit. Note that the 'shaky stick' modifier applies to the air-to-air attacks.

**Comment by pheonixstorm** [comment]
That would be in line 1265-1268 of `WeaponAttackAction.java`
