### ISSUE TITLE
Cannot launch 0.43.8 RC2

### ISSUE THREAD

**Issue by silverbullitt850** [MegaMek/megamek#944]
### Environment
What version of MegaMek does your issue apply to? **0.43.8**
Note whether it is the stand alone MegaMek or HQ's MegaMek. **Stand alone zip version, non installed**
What operating system are you using?  Windows, Mac, or Linux? **Win 8.1 Enterprise**
What java version are you using?  If unsure it will state your java version at the top of the megameklog.txt file. **Java 6 and 7 are enabled on my machine**

### Description
Describe the issue and provide screenshots ingame if able. **Get a Java exception error when trying to launch via .exe. Below is the error when launching via command prompt**
![image](https://user-images.githubusercontent.com/37590372/37668259-6fc00c50-2c3a-11e8-8c05-79b48fa7763b.png)

### Files
No megameklog.txt because the game cannot be launched.

**Comment by neoancient** [comment]
MegaMek, MegaMekLab, and MekHQ require Java 8.

**Comment by silverbullitt850** [comment]
What do I need to do to launch this via the .jar? I checked and ostermiller, tinyxml, and collections (.jar) are not on my computer. Do I need to download those separately and then perform the readme instruction?

    On Tuesday, March 20, 2018, 12:33:43 PM EDT, neoancient <notifications@github.com> wrote:  
 
 
MegaMek, MegaMekLab, and MekHQ require Java 8.

**Comment by neoancient** [comment]
The message "Unsupported major.minor version 52.0" means that it requires Java 8. You must download and install Java 8 to run it from the jar or from the exe.

**Comment by silverbullitt850** [comment]
Right, I have Java 8 and can run the .exe. I'm asking how to run the program from the .jar.
 

    On Thursday, April 5, 2018, 1:02:38 PM EDT, neoancient <notifications@github.com> wrote:  
 
 
The message "Unsupported major.minor version 52.0" means that it requires Java 8. You must download and install Java 8 to run it from the jar or from the exe.

**Comment by wildj79** [comment]
Open a command prompt and run the following:

`java -version`

Paste your results into your response. My guess is that your system `PATH` is pointing to one of the older versions of java on your machine. If it is, you'll need to update this to point to the correct version. 

Also, if you don't need them, it would probably be a good idea to uninstall the older versions. Java **does not** do this automatically when you update.
