### ISSUE TITLE
Error in armor of Reptar and Araña

### ISSUE THREAD

**Issue by Xeno426** [MegaMek/megamek#948]
### Environment
MegaMek 0.43.7 RC1
Win7
Java build 1.8.0_151-b12

### Description
When viewing both the Araña and Reptar, their armor is listed as "!MechView.UNKNOWN!". If opened in MML, the armor becomes Patchwork.

### Files
https://i.imgur.com/NGseGAR.jpg
https://i.imgur.com/TC3jpoC.jpg

**Comment by HammerGS** [comment]
Please try to see if the error exists in the current RC3
