### ISSUE TITLE
Tactical Genius Re-roll Still Available Without Pilot

### ISSUE THREAD

**Issue by jayof9s** [MegaMek/megamek#954]
### Environment
Megamek included with MHQ RC2
Windows7
Latest java8

### Description
When you have a pilot with Tactical Genius you can reroll initiative. If the pilot has lost his 'Mech he shouldn't be able to still roll for initiative (doubly so if he's off the map entirely or sitting in the belly of an enemy hovercraft). Currently, you can still reroll - see attached save.
[Init-Reroll.gz](https://github.com/MegaMek/megamek/files/1854350/Init-Reroll.gz)

**Comment by kuronekochomusuke** [comment]
this looks to be fixed.  seems to work as expected in 0.49.10   

the code looks to check it the mech is still good.

    public boolean hasTacticalGenius(Player player) {
        for (Entity entity : entities) {
            if (entity.hasAbility(OptionsConstants.MISC_TACTICAL_GENIUS)
                    && entity.getOwner().equals(player) && !entity.isDestroyed() && entity.isDeployed()
                    && !entity.isCarcass() && !entity.getCrew().isUnconscious()) {
                return true;
            }
        }
        return false;
    }
