### ISSUE TITLE
Weapons Tab Display

### ISSUE THREAD

**Issue by BairdEC** [MegaMek/megamek#961]
### Environment
MM 0.43.9-RC3, started from MHq
Win10
Java v8 build 161

### Description
If a targeted unit has a long name  like "Jump Support Infantry Star Corps Jump Assault Infantry (Capellan Confederation (Local Forces))," the text in the Unit Display weapon tab is shifted left so that the standard text (Name, Target, Range, etc.) displays the first letter and an ellipsis.

![weapon_display](https://user-images.githubusercontent.com/38081112/38323810-351113dc-37f3-11e8-82bd-276784d599c4.png)

### Files
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/1876883/autosave.sav.gz) (Dickson's Dodgers)

**Comment by Dylan-M** [comment]
You can resize that window as needed.
