### ISSUE TITLE
Artillery indirect fire with SPAs freezes game

### ISSUE THREAD

**Issue by blah2355** [MegaMek/megamek#965]
### Environment
MegaMek 0.43.9 RC3
Windows 8.1
Java 1.8.0_161

### Description
Firing an artillery weapon with Oblique Attacker, Oblique Artilleryman, or Forward Observer SPAs that doesn't land on the same turn causes the game to freeze up after the firing phase is finished. If it lands on the same turn, it resolves normally. Log file seems to indicate the indirect fire artillery handler is the issue.

### Files
[megameklog.txt](https://github.com/MegaMek/megamek/files/1887029/megameklog.txt)
[blah2355.sav.gz](https://github.com/MegaMek/megamek/files/1887030/blah2355.sav.gz)
Player name: blah2355

**Comment by mkerensky** [comment]
I believe that this issue was found and fixed a few days after 0.43.9 RC3 was released.  Try again when the next release is available and let us know if it's still a problem for you.

**Comment by Dylan-M** [comment]
Fixed by 01622000d1d3c93d879ba98c16110bdb83ee352c
