### ISSUE TITLE
Buccaneer sprites default to dropship version

### ISSUE THREAD

**Issue by blah2355** [MegaMek/megamek#966]
### Environment
MegaMek 0.43.9 RC3

### Description
Custom Buccaneer mechs should default to the default sprite (data\images\units\mechs\buccaneer.png) but instead display as the dropship sprite (data\images\units\dropships\buccaneer.png). This is because both units look for "buccaneer" chassis but since the dropship is first on the list (data\images\units\mechset.txt) it defaults to that. I'm thinking that all dropship .blks chassis names needs to be renamed as Buccaneer (Dropship) to avoid confusion.

### Files
![image](https://user-images.githubusercontent.com/26724418/38463401-3b7e5e0a-3ac8-11e8-888d-8597b7929e21.png)

![image](https://user-images.githubusercontent.com/26724418/38463405-476fd450-3ac8-11e8-8754-a95055cb2546.png)

**Comment by Dylan-M** [comment]
This is working as designed. You must use the localclient_mechset in order to set your own sprite definition to what you want to use for your custom units when this happens.
