### ISSUE TITLE
[0.43.9-RC3 : Bug] Map Editor's "Terrain List" Selection No Longer Update The Terrain Pull Down Menu

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#972]
### Environment

0.43.9-RC3

### Description

In Map Editor, previously when you select a "Terrain" in the "Terrain List/Box", the Terrain pull down menu will also be updated for easy editing. It's no longer the case.

To replicate:
1. At Map Editor, load any existing map with buildings (better for example).
2. At the terrain list/box, select any terrain.
3. Previously, the terrain pull down menu (below the "Remove Terrain" button) will also be updated to the selection above, but not anymore. 

Not editing breaking, but more effort are required to edit now.

My explanation might be bad, message me in Slack.

### Files

N/A

**Comment by SimonLandmine** [comment]
Is this the same bug as #920?

**Comment by Windchild292** [comment]
I believe so @SimonLandmine, and will retest this on #1613 to ensure it is fixed.

**Comment by SJuliez** [comment]
Since #1613 is merged and the GUI is different, I believe this issue is outdated. Therefore closing it.
