### ISSUE TITLE
[0.43.9-RC3 : Feature Request] Princess to Eject Crippled Conventional/Aero/Small Craft/Dropship/Warship

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#973]
Princess controlled conventionals, aeros, small crafts, dropships and warships will never flee or eject. Will be great if they flee when crippled (if possible), or eject if cannot take off or fly off.

**Comment by mkerensky** [comment]
Related here is that we need to implement correct aero ejection.  That's very near future on my to-do list.  For princess to do this, she has to be able to fly these craft in space too :)   I hear that's coming this year.

**Comment by SirMegaV** [comment]
For grounded aeros/conven too. Hate it when they are grounded and cannot
take off yet refuse to eject. And at the end of the battle, I cannot
salvage because they escaped (How??? How???)

**Comment by Windchild292** [comment]
@NickAragua can she handle this at this point?

**Comment by NickAragua** [comment]
They are able and willing to flee when airborne and crippled.
Probably able to eject when grounded and crippled.
Unable to take off yet, as whether or not to take off depends very much on the scenario being played (e.g. are you allowed to take off, when, etc)

**Comment by Windchild292** [comment]
This has been implemented.
