### ISSUE TITLE
[0.43.9-RC3 : Feature Request] RAT Generator Missing Infantry Artillery Role

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#979]
RAT generator currently do not have infantry artillery role.

**Comment by NickAragua** [comment]
Seems like it's present now (top-right checkbox in the mission/role section)
![image](https://user-images.githubusercontent.com/29387808/45597164-d8996f80-b995-11e8-891f-e0af70eb8c54.png)
