### ISSUE TITLE
[0.43.9-RC3 : Bug] NPE at ToolTipManager$insideTimerAction.actionPerformed

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#987]
### Environment

0.43.9-RC3

### Description

Occasionally see this error, but cannot replicate. Save and reload the game will solve this error even when repeating the same moves.

### Files

Log, custom files, and save game attached. Savegame made after getting the error.

[NPE-ToolTipManager$insideTimerAction.actionPerformed-Log.txt](https://github.com/MegaMek/megamek/files/2043505/NPE-ToolTipManager.insideTimerAction.actionPerformed-Log.txt)
[Uploading NPE-ToolTipManager$insideTimerAction.actionPerformed-Game.sav.gz…]()

**Comment by SirMegaV** [comment]
Kicking the bot player, then skip the unit, will solve the problem too.

**Comment by NickAragua** [comment]
I believe the exception has been fixed in 43.10.

**Comment by NickAragua** [comment]
Since we haven't had any reports of this for the last four stable releases, I'll consider this resolved.
