### ISSUE TITLE
Graphical Issues

### ISSUE THREAD

**Issue by byornski** [MegaMek/megamek#990]
### Environment
megamek-0.42.2-windows
Windows 10 v1803
What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file. 

GTX970, Driver version 397.93. 1440p (but not high dpi enabled). Gsync

### Description
Have been getting serious graphical issues throughout a game. Screens were not redrawn properly in many occasions.  Moving the mouse down menu items in game would print copies of what should be drawn under the mouse pointer. 

Unfortunately I do not have any examples for the actual in game behavior but it was quite similar to the menu behavior. 
https://imgur.com/a/tYz03D8

**Comment by MGM175** [comment]
Seems to be a Java issue. You didn't mentioned the version.
It should be at Help -> About.

**Comment by byornski** [comment]
Tested with both Java Version 8 Update 171 and Version 10.0.1 but both have these issues. The screenshots were with java 8.171

**Comment by HammerGS** [comment]
Have a look here and see if this helps/
http://www.mekwars.org/mediawiki-1.20.2/index.php/FAQ

**Comment by Windchild292** [comment]
Closing as a Java issue with no further discussiom in nearly three years
