### ISSUE TITLE
Portraits displayed in 1:1.16 pixel ratio regardless of image's dimensions

### ISSUE THREAD

**Issue by crazys1** [MegaMek/megamek#992]
### Environment

MegaMek version 0.43.10-RC4
Windows 10
Java version 1.8.0_171

### Description

MegaMek displays portraits with a 1:1.16 pixel ratio regardless of image's dimensions. As an extreme example, I created an image that is 20 pixels wide, 100 pixels high:

![20x100](https://user-images.githubusercontent.com/21768936/41073417-01183d5c-69b8-11e8-9278-49f271ae56ec.jpg)

This image displays as follows in MegaMek:

![image](https://user-images.githubusercontent.com/21768936/41073427-1851e040-69b8-11e8-9736-6607a783ac78.png)

However, MekHQ preserves the dimensions ratio:

![image](https://user-images.githubusercontent.com/21768936/41073465-4d854496-69b8-11e8-8647-59a4911b5f0e.png)

I then tried with an image that is 100 pixels wide, 20 pixels high:

![100x20](https://user-images.githubusercontent.com/21768936/41073663-3d1b5194-69b9-11e8-8be9-f6e692997564.jpg)

MegaMek:
![image](https://user-images.githubusercontent.com/21768936/41073656-32cd769a-69b9-11e8-870b-a7a928e16e04.png)

MekHQ:
![image](https://user-images.githubusercontent.com/21768936/41073542-9f15077e-69b8-11e8-9d03-7702deb89757.png)

The pixel ratio was retained in MekHQ.

MegaMek should preserve the image's dimensions ratio just as MekHQ does.

**Comment by Windchild292** [comment]
MegaMek and MekHQ now use the same code for portraits, and this now works as intended with the addendum being we center any image
![image](https://user-images.githubusercontent.com/39067288/104505270-a4f4a180-55b1-11eb-9acb-55182fefa225.png)
